Fix milestone API state parameter unhandled (#10049)
go-gitea/gitea pull request #10053
Opened 2020-01-29 08:09 UTC by lunny

backport from #10049

* Fix milestone API state parameter unhandled
* Fix test

2020-01-29 09:57 UTC, lafriks approved these changes

2020-01-29 09:58 UTC, lafriks commented on integrations/api_issue_milestone_test.go
> +	defer prepareTestEnv(t)()
this should be changed to what it was in v1.10

2020-01-29 11:55 UTC, 6543 requested changes
As per lafriks comment on test

2020-01-30 02:20 UTC, 6543 approved these changes

2020-01-30 03:49 UTC, merged