resolved #91: automatically generate gitea version
go-gitea/gitea pull request #101
Opened 2016-11-07 03:22 UTC by lunny

And I create the make.bash for linux and mac, we need another make.bat for windows. Of course, this is a beginning of make bash. I think a bash file to make is simple and better than Makefile.

2016-11-07 06:01 UTC, tboerger commented
I personally prefer a makefile, most of the bash content is done there.

2016-11-07 06:26 UTC, tboerger commented on make.bash
> +	cat /etc/passwd | read version
Passed?

2016-11-07 06:26 UTC, tboerger commented on make.bash
> +        go build -ldflags "-X main.Version=tip+${tag}"
I'm not a fan of tip as a "version"

2016-11-07 06:30 UTC, makhov commented
What's wrong with Makefile? Why we need make.bash?

2016-11-07 07:55 UTC, lunny commented
You have to install extra make system. But for a bash, it has no more dependency.

2016-11-07 08:21 UTC, tboerger commented
To be serious, I think nearly all people working with Go got make installed. I personally don't really want to maintain 2 files for a single use case.

2016-11-07 08:25 UTC, tboerger commented
And if we change the version assignment I would also drop https://github.com/go-gitea/gitea/blob/master/modules/setting/setting.go#L51-L52 and the places where it gets used.

2016-11-07 08:37 UTC, tboerger commented
And this is my suggestion for the Makefile to get it working based on this proposal, I would always keep a valid version number, `tip` is not a version number and with a plain `0.0.0` we can still always see that this have been built from master:

```patch
--- Makefile.current	2016-11-07 09:25:49.668272844 +0100
+++ Makefile	2016-11-07 09:33:32.880272024 +0100
@@ -4,31 +4,30 @@
 EXECUTABLE := gitea
 IMPORT := github.com/go-gitea/gitea

-SHA := $(shell git rev-parse --short HEAD)
-DATE := $(shell date -u '+%Y-%m-%d %I:%M:%S %Z')
-
 BINDATA := $(shell find conf | sed 's/ /\\ /g')
 STYLESHEETS := $(wildcard public/less/index.less public/less/_*.less)
 JAVASCRIPTS :=

-LDFLAGS += -X "github.com/go-gitea/gitea/modules/setting.BuildTime=$(DATE)"
-LDFLAGS += -X "github.com/go-gitea/gitea/modules/setting.BuildGitHash=$(SHA)"
+REF ?= $(shell git rev-parse --abbrev-ref HEAD)
+SHA ?= $(shell git describe --tag --always)

 TARGETS ?= linux/*,darwin/*,windows/*
 PACKAGES ?= $(shell go list ./... | grep -v /vendor/)

 TAGS ?=

-ifneq ($(TRAVIS_TAG),)
-	VERSION ?= $(TRAVIS_TAG)
+ifneq ($(REF),HEAD)
+	VERSION ?= 0.0.0+$(SHA)
 else
-	ifneq ($(TRAVIS_BRANCH),)
-		VERSION ?= $(TRAVIS_BRANCH)
+	ifneq ($(REF),master)
+		VERSION ?= 0.0.0+$(SHA)
 	else
-		VERSION ?= master
+		VERSION ?= $(REF)+$(SHA)
 	endif
 endif

+LDFLAGS += -X "main.Version=$(VERSION)"
+
 .PHONY: all
 all: clean test build
```

2016-11-07 08:45 UTC, strk commented
What's wrong with just using SHA ? Why do we need REF too ? Do you have example resulting VERSION strings ?

2016-11-07 08:50 UTC, tboerger commented
`REF` is used to detect if it's `HEAD`, `master` or a tag, `SHA` just adds the commit hash. So of course we need both if we want to detect the version automatically.

2016-11-07 08:54 UTC, strk commented
And why do we want to distinguish, was my question.
When calling `git describe --always --tag` while in a tag, I do get the tag as the version, which is what we want, while being not in a tag would give you the most recent tag + a count of commits + the actual hash, what else are we missing from that ?

2016-11-07 12:15 UTC, tboerger commented
We WANT to have `master=0.0.0|HEAD=0.0.0|tag=1.0.0+commit-sha`, maybe we also want to strip the `v` from the tag name.

2016-11-07 12:54 UTC, strk commented
On Mon, Nov 07, 2016 at 04:15:17AM -0800, Thomas Boerger wrote:
> We WANT to have `master=0.0.0|HEAD=0.0.0|tag=1.0.0+commit-sha`, maybe we also want to strip the `v` from the tag name.

I don't get this, why don't you always want an unambiguous
version number, including the "commit-sha" ?

2016-11-07 14:38 UTC, tboerger commented
We want a proper version scheme that applies for package managers.

2016-11-07 14:46 UTC, strk commented
Maybe I misunderstood your suggestion, as long as the `+commit-sha` is always appended (also for master/HEAD) I'm ok with the proposal

2016-11-07 15:19 UTC, tboerger requested changes

2016-11-07 15:19 UTC, tboerger commented on main.go
> +var Version = "0.9.99.0915"
I would set that to `var Version = "0.0.0+master"`

2016-11-07 17:39 UTC, strk commented
On Mon, Nov 07, 2016 at 07:19:43AM -0800, Thomas Boerger wrote:

>  // Version holds the current Gitea version
> -const Version = "0.9.99.0915"
> +var Version = "0.9.99.0915"
> 
> I would set that to `var Version = "0.0.0+master"`

Based on
https://github.com/go-gitea/gitea/issues/91#issuecomment-258865894
the hard-coded version should probably be "1.0.0+dev"
(target version for current master is 1.0.0)

2016-11-11 22:29 UTC, tboerger commented on main.go
> +var Version = "0.9.99.0915"
If I remember correctly you can not manipulate `const` from outside? Need to confirm that.

2016-11-12 00:21 UTC, lunny commented on main.go
> +var Version = "0.9.99.0915"
A const can not be set via go build flag.

2016-11-24 10:02 UTC, tboerger commented
Let's close that in favor of #190

2016-11-24 10:02 UTC, closed without merging