Additional OAuth2 providers
go-gitea/gitea pull request #1010
Opened 2017-02-22 12:41 UTC by willemvd

This is a followup on #679 (this PR is based on the merged #679 master) which only included GitHub as an OAuth2 provider.

For now the following providers are implemented (incl signin image and tip text in admin/auths/new):
Google+
GitLab 
Bitbucket
Twitter
Facebook
Dropbox
OpenID Connect

I will add and test new providers on request in this PR (or on gitter?), list of possible providers can be found at : https://github.com/markbates/goth/#supported-providers

2017-02-22 13:18 UTC, lunny commented
build failed.

2017-02-22 14:20 UTC, willemvd commented
fixed

2017-02-22 14:24 UTC, appleboy commented on models/login_source.go
> +	"sort"
Move local package to top

2017-02-22 14:26 UTC, appleboy commented on modules/auth/oauth2/oauth2.go
> +	"math"
See https://github.com/go-gitea/gitea/blob/master/CONTRIBUTING.md#styleguide

2017-02-22 14:36 UTC, willemvd commented on modules/auth/oauth2/oauth2.go
> +	"math"
done, changed to goimports style

2017-02-22 14:36 UTC, willemvd commented on models/login_source.go
> +	"sort"
done, changed to goimports style

2017-02-22 14:41 UTC, appleboy commented
@willemvd build fails

2017-02-22 14:42 UTC, willemvd commented
Build failure over a file I didn't change and cannot be found at that location? 😕 
modules/helper.go -> golint failure but file does not exist

2017-02-23 01:14 UTC, appleboy commented
@willemvd Please rebase the latest version of master. See https://github.com/go-gitea/gitea/pull/1017

2017-02-23 07:43 UTC, willemvd commented
Not sure what happend , but rebase seems to have messed up my PR 
See duplicate commits in my history 😕 
Not sure what will happen when this gets merged... maybe create a new PR ?

2017-02-23 07:54 UTC, willemvd commented
@lunny @appleboy any idea ? (see my previous comment) & when I do a merge locally on master with this PR , history will be messed up with duplicate entries

2017-02-23 08:22 UTC, lunny commented
```
git fetch origin
git rebase master
... resolve the conflict
git add <conflict file>
git rebase --continue
git push --force <your repo and branch>

2017-02-23 08:28 UTC, willemvd commented
Will that work even in this broken state?

2017-02-23 08:46 UTC, willemvd commented
@lunny created a new branch of upstream/master and cherry-picked the commits on top of it, after git push --force it seems to be ok now 😄

2017-02-23 19:35 UTC, strk commented on models/error.go
> +
Maybe you could take the chance to start with splitting error.go into error_oauth.go ...

2017-02-24 15:34 UTC, willemvd commented on models/error.go
> +
done , also moved some stuff from login_source.go to oauth2.go

2017-02-28 00:15 UTC, morrildl commented
I just noticed this is on the 1.2.0 milestone; is there any chance it could make it into 1.1.0, or is it too late for that?

(I'm waiting on Google OAuth2 support before deploying a Gitea instance, and I'm impatient. :)

2017-02-28 00:18 UTC, lunny commented
It should be in v1.2. You can use master version after this merged.

2017-02-28 07:14 UTC, willemvd commented
Annoying... every time someone changes something to login_source.go it becomes a merge conflict since part of the code is moved to another file and it doesn't recognizes that quite right..

So I will wait for 1.1 to be released and 1.2 features gets merged to master

2017-03-02 09:45 UTC, strk commented
@willemvd any chance to get dynamic client registration for `OpenID Connect` provider, in a way to let people log-in using an URL ? (seeking provider data in the page at URL and dynamically registering the client...)

2017-03-02 09:47 UTC, strk commented
For dynamic client registration, see https://github.com/markbates/goth/issues/142

2017-03-02 13:09 UTC, willemvd commented
@strk no don't have any plans to do so
Also feel a major drawbacks to this, because I think it will open up a possible security hole.
An admin is now not in control about what systems are attached and allows people from a possible not secure source.

Also think there is no real need since it is only supported by a very few providers which all allow manual registration (the current approach)

2017-03-02 18:23 UTC, strk commented
What's an "insecure source" when it comes to authenticating users ?
If you have an "open registration" policy why "certainty" of identity
cannot be left to the user being authenticated ?

It's like letting users choose their passwords...

2017-03-02 18:37 UTC, morrildl commented
FWIW, I agree with @willemvd.

The concern isn't so much that an incoming self-registered user identity is "false" (since the whole point of OpenID/OAuth is that you are delegating that), but rather that it can be stolen.

If you operate a Gitea instance with an open registration policy, you are presumably doing so to allow anyone to publish code for others to use. So, if I as a user choose to use a poor/insecure OpenID service to sign up, someone could steal my identity and use it to publish malware into repos I've published.

This is something that can happen with any provider, but it's far less likely with Github or Google or Facebook, than a random self-hosted OpenID instance or similar. It should be up to admins to decide which they trust. And while you can argue that the admins are choosing to trust dynamic registrations, it seems to me that Gitea as a tool for distributing source ought to be careful about what it enables.

IMO it makes sense to first finish up OAuth2 in general with a fixed list of supported providers, and get some deployments of that configuration. Then think about dynamic registrations later.

2017-03-02 19:26 UTC, strk commented
I completely disagree on the assumption that a Big Auth Provider
gives more security. An attacker needs to only break into that Big Auth
Provider to compromise thousand of identities.

If someone stole your identity, I'll consider you responsible for
that and suspend your account, until you fix that (if I know and trust
you).

2017-03-02 19:37 UTC, willemvd commented
Adding providers on the fly by Gitea user is basically adding users without passwords or security at all.
The only ones inGitea that should be able to add these kind of dynamic registration urls should be Gitea admins. That way they can skip the part of manually creating a secret and a key. That is the only reason why you should want this extra feature.

When Gitea end users can enter there own urls they could setup any open system on there provider side and always allow anyone.
OAuth2 is about delegating the login part to a trusted party and verify in the background that you agree both on the secret.
With dynamic registration from end users this is not possible in a secure way.

I'm not going to add this feature so if you (@strk) want this after all, you will have to submit a PR after this to add that.

2017-03-03 09:50 UTC, strk commented
How's that different from letting users self-register ?
You still want some bot and spam protection, in both cases.

> When Gitea end users can enter there own urls they could setup any open system on there provider side and always allow anyone.

Same as creating a user and publishing its password, to let it be usable
by anyone.

I'm not saying to *force* that LoginSource to exist, just letting Admins
decide if they want or not to allow it.

Anyway: understood it's not in your plans to do that :)

2017-03-10 02:00 UTC, lunny commented
@willemvd this could be continued since v1.1 released.

2017-03-11 05:03 UTC, lunny commented
build failed.

2017-03-17 14:07 UTC, geek1011 commented on models/login_source.go
> +	if err == nil && source.IsOAuth2() && source.IsActived {
Spelling: source.IsActive , this needs to be renamed.

2017-03-17 14:07 UTC, geek1011 commented on models/oauth2.go
> +	"twitter":       {Name: "twitter", DisplayName: "Twitter", Image: "/img/auth/twitter.png"},
Maybe add stack exchange as well?

2017-03-17 14:07 UTC, geek1011 commented on templates/admin/auth/new.tmpl
> +					<h5>GMail Settings:</h5>
Gmail, not GMail. Maybe also add this to translations?

2017-03-17 14:07 UTC, geek1011 commented on templates/admin/auth/new.tmpl
> +			</div>
Is there a way to make this automated (maybe a loop)?

2017-03-20 11:11 UTC, willemvd commented on models/login_source.go
> +	if err == nil && source.IsOAuth2() && source.IsActived {
This is reuse of existing code, so I think out of scope for this PR

2017-03-20 11:11 UTC, willemvd commented on models/oauth2.go
> +	"twitter":       {Name: "twitter", DisplayName: "Twitter", Image: "/img/auth/twitter.png"},
Think this is not yet available in https://github.com/markbates/goth/#supported-providers or is it named differently?

2017-03-20 11:11 UTC, willemvd commented on templates/admin/auth/new.tmpl
> +					<h5>GMail Settings:</h5>
This is reuse of existing code, so I think out of scope for this PR

2017-03-20 11:12 UTC, willemvd commented on templates/admin/auth/new.tmpl
> +			</div>
Will have a look if this can be a loop over the existing OAuth2 providers

2017-03-20 11:22 UTC, strk commented on models/oauth2.go
> +	"twitter":       {Name: "twitter", DisplayName: "Twitter", Image: "/img/auth/twitter.png"},
for the record; stackexchange (also?) supports OpenID-2.0, and you can use `openid.stackexchange.com` to login (will be converted to actual URL upon logging in)

2017-03-20 11:30 UTC, strk commented on models/login_source.go
> +	if err == nil && source.IsOAuth2() && source.IsActived {
Not only that, it's also in a DB model so changing that field would require a migration :/

2017-03-20 11:32 UTC, strk commented
It would also be nice to get #1300 merged before this. @geek1011 can you resolve conflicts there ?

2017-04-06 01:55 UTC, lunny commented
@willemvd is this ready to review?

2017-04-06 09:09 UTC, willemvd commented
@lunny yes it is, unfortunately the last push didn't triggered a drone build so maybe you can manually trigger this (or I could do a merge/rebase with master)

2017-04-06 12:56 UTC, lunny commented
@willemvd please send a rebase, I cannot find the link to the drone build.

2017-04-06 14:10 UTC, willemvd commented
@lunny drone is almost done without failures, so it is ready! 😄

2017-04-07 15:10 UTC, lunny commented
I have tested `google+` and `twitter`, both are OK. but `/user/link_account` UI is broken. Otherwise LGTM

2017-04-19 11:33 UTC, bkcsoft commented
Are we allowed to use these logos? Why not use the ones in FontAwesome?

2017-04-19 11:40 UTC, bkcsoft requested changes
formatting

2017-04-19 11:40 UTC, bkcsoft commented on routers/admin/auths.go
> +	"github.com/Unknwon/com"
Newline before external packages

2017-04-19 11:40 UTC, bkcsoft commented on templates/admin/auth/edit.tmpl
> +						<!-- OAuth2 -->
Weird indentation

2017-04-28 11:42 UTC, willemvd commented on routers/admin/auths.go
> +	"github.com/Unknwon/com"
added

2017-04-28 11:42 UTC, willemvd commented on templates/admin/auth/edit.tmpl
> +						<!-- OAuth2 -->
fixed

2017-04-28 14:42 UTC, sapk commented
Build seems to failed because the vendor `github.com/mrjones/oauth` doesn't correspond to remote. If you make change in the lib please revert them. A simple command to revert to original version is `govendor fetch github.com/mrjones/oauth`. This will also update the lib but, in this case, since it is not allready in repo there is no problems.

2017-04-28 23:22 UTC, bkcsoft approved these changes

2017-05-01 06:10 UTC, willemvd commented
Didnt change anything to that lib so not sure why this happened, but I have updated the lib

2017-05-01 13:23 UTC, appleboy approved these changes

2017-05-01 13:24 UTC, appleboy commented
LGTM

2017-05-01 13:26 UTC, merged