Fix invalid repo urls after change username
go-gitea/gitea pull request #10150
Opened 2020-02-05 13:15 UTC by mavenbline

Fix #10141

2020-02-05 13:17 UTC, zeripath approved these changes

2020-02-05 13:49 UTC, sapk approved these changes

2020-02-05 13:52 UTC, sapk commented
No need to backport to 1.11 since it was introduced in #9717

2020-02-05 13:52 UTC, zeripath commented
Hmm... So this functionality should really be folded in to https://github.com/go-gitea/gitea/blob/77431599f6708b87019a7e929d02fe8d1b95a8e7/models/user.go#L1073. There's a race here that could break things.

2020-02-06 01:15 UTC, lunny commented
But if rename folder succeed but database changed failed? That will break the repository.

2020-02-06 18:37 UTC, mavenbline commented
> But if rename folder succeed but database changed failed? That will break the repository.
If database request failed, we can rename folder back.
But what if folder name rollback failed? :o
Will this be cause for panic?

2020-02-07 02:24 UTC, lunny commented
The orgnization update needs a rewritten.

2020-02-07 05:58 UTC, lafriks requested changes

2020-02-07 05:58 UTC, lafriks commented on models/user.go
> +	sess := x.NewSession()
It would be better to move L1053-L1061 before directory rename to minimize possiblity of having one thing done and other failing

2020-02-08 14:59 UTC, lafriks approved these changes

2020-02-08 14:59 UTC, merged