Fix reply on code review
go-gitea/gitea pull request #10227
Opened 2020-02-11 03:11 UTC by lunny

Should fix #9891

2020-02-11 04:21 UTC, guillep2k approved these changes
Just one question, anyway LGTM

2020-02-11 04:55 UTC, lunny commented on web_src/js/index.js
> +  if (form.length > 0 && form.hasClass('comment-form')) {
Just copied from onCodeReviewClicked. :)

2020-02-11 11:50 UTC, silverwind commented
Why not just use `<button type="submit">`. Inline HTML `onclick` should be avoided.

2020-02-11 11:52 UTC, silverwind requested changes
See above.

2020-02-12 01:16 UTC, lunny commented
> Why not just use `<button type="submit">`? Inline HTML `onclick` should be avoided ([some](https://stackoverflow.com/questions/5871640/why-is-using-onclick-in-html-a-bad-practice) [reasons](https://www.reddit.com/r/javascript/comments/3kamqn/why_is_inline_onclickfunction_considered_such_a/)) and if it has to be JS, use `addEventListener`, but I'm pretty certain this issue can be fixed without using any JS because it's a simple form submission that browers can do just fine without JS (unless you want to submit it async, but this case is sync submission).

I have tried that, but it's not work.

2020-02-12 01:25 UTC, silverwind reviewed
Guess I won't block as this is a bugfix, but these form submissions should be cleaned up to work without JS.

2020-02-12 09:09 UTC, 6543 approved these changes
yes a other pr can minimize js for souch things :)

2020-02-13 05:18 UTC, lunny commented
make L-G-T-M work

2020-02-13 05:22 UTC, merged