fix: Admin can see all private repositories on Explore page.
go-gitea/gitea pull request #1026
Opened 2017-02-23 03:50 UTC by appleboy

fix #1022 

* Remove counter function in `RepoSearchOptions`
* Check IsAdmin Flag in search.

2017-02-23 04:18 UTC, lunny commented on models/repo.go
> +	countSess = *sess
It's not a good idea to copy Session. I think you can use cond?

2017-02-23 04:18 UTC, lunny commented on models/repo.go
> +	count, err := countSess.Count(new(Repository))
`count, err := x.Where(cond).Cound(new(Repository))`

2017-02-23 04:26 UTC, appleboy commented on models/repo.go
> +	count, err := countSess.Count(new(Repository))
Done https://github.com/go-gitea/gitea/pull/1026/commits/e8924042e6596176ba79273181afeae0e16c8915

2017-02-23 04:26 UTC, appleboy commented on models/repo.go
> +	countSess = *sess
Done https://github.com/go-gitea/gitea/pull/1026/commits/e8924042e6596176ba79273181afeae0e16c8915

2017-02-23 06:19 UTC, lunny commented
LGTM

2017-02-25 15:20 UTC, lunny commented
conflicted

2017-02-25 15:28 UTC, appleboy commented
fixed conflicts.

2017-02-26 04:09 UTC, ethantkoenig requested changes

2017-02-26 04:09 UTC, ethantkoenig commented on models/repo.go
> +	count = countRepositories(-1, opts.Private)
Here, we check `opts.Private` to see if we should include private repos, but when populating the `repos` slice, we always include private repos regardless of `opts.Private`

2017-02-26 04:09 UTC, ethantkoenig commented on models/repo.go
> +func Repositories(opts *SearchRepoOptions) (_ RepositoryList, count int64, err error) {
Why does this function not examine the contents of `opts.Searcher`, and exclude repos accordingly (like `Repositories(..)`)?

2017-02-26 04:30 UTC, appleboy commented on models/repo.go
> +func Repositories(opts *SearchRepoOptions) (_ RepositoryList, count int64, err error) {
Why need to examine the contents of `opts.Searcher`? 

https://github.com/go-gitea/gitea/blob/master/models/issue_indexer.go#L119
https://github.com/go-gitea/gitea/blob/master/routers/admin/repos.go#L28

2017-02-26 04:33 UTC, appleboy commented on models/repo.go
> +	count = countRepositories(-1, opts.Private)
`Repositories` always returns all repositories. maybe we need to change `countRepositories(-1, true)`?

2017-02-26 04:42 UTC, ethantkoenig commented on models/repo.go
> +func Repositories(opts *SearchRepoOptions) (_ RepositoryList, count int64, err error) {
Since `Repositories(..)` only looks at `opts.PageSize`, `opts.Page`, and `opts.OrderBy`, would it be better to have it take 3 arguments?

2017-02-26 04:46 UTC, appleboy commented on models/repo.go
> +	count = countRepositories(-1, opts.Private)
I can create another PR to refactor the codes according your suggestion.

2017-02-26 04:51 UTC, ethantkoenig approved these changes
LGTM

2017-02-26 04:52 UTC, appleboy commented on models/repo.go
> +func Repositories(opts *SearchRepoOptions) (_ RepositoryList, count int64, err error) {
NO. I think using `SearchRepoOptions` would be better than take 3 arguments if we want to extend the function.

2017-02-26 05:59 UTC, appleboy commented
let L-G-T-M work

2017-02-26 05:59 UTC, merged