Fix URL handling in the whole markdown module, improve test coverage (fix #997)
go-gitea/gitea pull request #1027
Opened 2017-02-23 05:02 UTC by andrew-boyarshin

As it is in the title.

Plus, links to issues or PRs in external repositories will no longer be rewritten to current repo.

2017-02-23 05:08 UTC, andrew-boyarshin commented on vendor/code.gitea.io/sdk/gitea/miscellaneous.go
> +	Wiki    string
Public Gitea API changed, optional Wiki parameter added.

2017-02-23 05:09 UTC, andrew-boyarshin commented on routers/api/v1/misc/markdown_test.go
> +<li>Bezier widget (by <a href="` + AppURL + `r-lyeh" rel="nofollow">@r-lyeh</a>)<a href="https://github.com/ocornut/imgui/issues/786" rel="nofollow">#786</a></li>
Note, link hosts are no longer rewritten. No more dead links.

2017-02-23 05:12 UTC, andrew-boyarshin commented on modules/markdown/markdown.go
> +	cwdIndex := strings.Index(res, "/./")
URLJoin now correctly handles ```.``` and ```..``` path elements.

2017-02-23 05:12 UTC, andrew-boyarshin commented on modules/markdown/markdown.go
> +	AnySHA1Pattern = regexp.MustCompile(`(http\S*)://(\S+)/(\S+)/(\S+)/(\S+)/([0-9a-f]{40})(?:/?([^#\s]+)?(?:#(\S+))?)?`)
Protocol is important now.

2017-02-23 05:29 UTC, lunny requested changes

2017-02-23 05:29 UTC, lunny commented on vendor/code.gitea.io/sdk/gitea/miscellaneous.go
> +	Wiki    string
But you have to send a PR to SDK project at first before this can be merged.

2017-02-23 08:36 UTC, andrew-boyarshin commented on vendor/code.gitea.io/sdk/gitea/miscellaneous.go
> +	Wiki    string
@lunny done.

2017-02-24 01:55 UTC, lunny approved these changes

2017-02-24 09:48 UTC, lunny commented
LGTM

2017-02-24 12:16 UTC, andrew-boyarshin commented
In case someone hasn't noticed, I force-pushed amended commits for both gitea and gitea-sdk repos with string -> bool change.

2017-02-24 13:19 UTC, appleboy commented
LGTM

2017-02-24 13:19 UTC, appleboy approved these changes

2017-02-24 14:11 UTC, andrew-boyarshin commented
Pending merge.

2017-02-24 14:59 UTC, merged