Show the username as a fallback on feeds if full name is blank
go-gitea/gitea pull request #10438
Opened 2020-02-24 09:00 UTC by jamesorlakin

While the `DEFAULT_SHOW_FULL_NAME` works well, there's a bug on the feed/dashboard page that causes the username not be used as a fallback and nothing shown instead:
![image](https://user-images.githubusercontent.com/7294642/75138947-5c0ad480-56e3-11ea-94de-f51ee8934293.png)

This PR copies the logic from `DisplayName` in `models/user.go:731` to return the username as a fallback for the template:
![image](https://user-images.githubusercontent.com/7294642/75139227-fec35300-56e3-11ea-87b6-d2cc516bd2c2.png)
_(where `review` is the username, and `Jimbo` as a user with the full name set)_

I'm happy to make a backport too. 😃

2020-02-24 09:02 UTC, zeripath reviewed
Not that we're the most efficient system but perhaps it would be better to restructure this so we only do the trimspace if the setting is set.

2020-02-24 09:09 UTC, jamesorlakin commented
To be honest I'm not really sure what the trim is there for. I guess if the user puts in a full name of just spaces we should ignore it, but surely that validation should be done at setting time?

2020-02-24 10:28 UTC, jamesorlakin commented
@zeripath String trimming in both the user and action models are now done only if `DEFAULT_SHOW_FULL_NAME` is configured.

2020-02-24 11:37 UTC, zeripath approved these changes

2020-02-24 12:18 UTC, lafriks requested changes

2020-02-24 12:18 UTC, lafriks commented on models/action.go
> +			return a.GetActFullName()
```suggestion
			return trimmedFullName
```

2020-02-24 13:17 UTC, jamesorlakin commented on models/action.go
> +			return a.GetActFullName()
Doh! 🤦‍♂

2020-02-24 18:32 UTC, 6543 approved these changes

2020-02-26 20:48 UTC, lafriks approved these changes

2020-02-26 22:08 UTC, merged