Link OAuth2 account to 2FA enabled account (fix #1050)
go-gitea/gitea pull request #1052
Opened 2017-02-25 13:24 UTC by willemvd

fixes #1050 where linking an account to a 2fa enabled account failed because we forgot to really link the account when 2fa is completed

2017-02-25 13:51 UTC, strk commented
LGTM

2017-02-25 15:19 UTC, lunny requested changes

2017-02-25 15:19 UTC, lunny commented on routers/user/auth.go
> +			models.LinkAccountToUser(u, gothUser.(goth.User))
handle the error?

2017-02-26 13:34 UTC, geek1011 commented
This works for me.

2017-02-26 13:34 UTC, geek1011 commented
This works for me. Thanks.

2017-02-27 09:23 UTC, bkcsoft commented
Other than lunnys note, LGTM

2017-02-27 09:58 UTC, willemvd commented
@lunny updated so errors are handled

2017-02-27 09:59 UTC, lunny approved these changes

2017-02-27 10:10 UTC, merged