API: support /users/:username/repos
go-gitea/gitea pull request #1059
Opened 2017-02-25 19:25 UTC by awwalker

Fix for half of: #494. I'm not 100% sure about the movement of functions and files and defer to you but I thought this grouping made sense.

2017-02-25 21:29 UTC, ethantkoenig requested changes

2017-02-25 21:29 UTC, ethantkoenig commented on routers/api/v1/api.go
> +			m.Combo("/repos", reqToken()).Get(user.ListMyRepos).
`reqToken()` isn't required here; it is already included on line 301.

2017-02-25 21:30 UTC, ethantkoenig commented
One small tweak, otherwise LGTM

2017-02-26 01:01 UTC, awwalker commented on routers/api/v1/api.go
> +			m.Combo("/repos", reqToken()).Get(user.ListMyRepos).
Got it, thanks.

2017-02-26 01:11 UTC, ethantkoenig approved these changes

2017-02-26 01:33 UTC, appleboy requested changes

2017-02-26 01:33 UTC, appleboy commented on routers/api/v1/user/repo.go
> +
remove empty line

2017-02-26 01:33 UTC, appleboy commented on routers/api/v1/user/repo.go
> +	showPrivateRepos := ctx.User.ID == userID && ctx.IsSigned
`(ctx.User.ID == userID || ctx.User.IsAdmin) && ctx.IsSigned`

2017-02-26 05:04 UTC, awwalker commented on routers/api/v1/user/repo.go
> +
Done.

2017-02-26 05:54 UTC, appleboy approved these changes

2017-02-26 05:54 UTC, appleboy commented
LGTM

2017-02-27 06:45 UTC, bkcsoft commented
LGTM

2017-02-27 06:46 UTC, merged