Bug fixed for org avatar caused by #1049
go-gitea/gitea pull request #1070
Opened 2017-02-26 13:29 UTC by lunny

2017-02-26 14:06 UTC, appleboy approved these changes

2017-02-26 14:15 UTC, appleboy commented
LGTM

2017-02-26 14:41 UTC, ethantkoenig requested changes

2017-02-26 14:41 UTC, ethantkoenig commented on models/user.go
> +		if !com.IsExist(u.CustomAvatarPath()) || !com.IsFile(u.CustomAvatarPath()) {
Can just have `!com.IsFile(u.CustomAvatarPath())`; `com.IsFile(..)` will return `false` if the file does not exist.

2017-02-26 14:41 UTC, ethantkoenig commented
One small tweak, otherwise LGTM

2017-02-26 17:51 UTC, ethantkoenig approved these changes
LGTM

2017-02-27 00:42 UTC, lunny commented
let L-G-T-M work

2017-02-27 00:42 UTC, merged