[UI] language status icon size
go-gitea/gitea pull request #10749
Opened 2020-03-17 08:27 UTC by everhopingandwaiting

adjust the repository language status icon size 

## before 

![image](https://user-images.githubusercontent.com/6021724/76836653-1ec1de80-686c-11ea-8f0f-ccef5a4b2e69.png)

### after 

![image](https://user-images.githubusercontent.com/6021724/76836502-e7ebc880-686b-11ea-87c6-30487fffbb7b.png)

2020-03-17 11:45 UTC, silverwind commented
10px seems to small, old one was ~18px. Suggestion:

```css
.color-icon {
  margin: .5rem 0;
  display: inline-block;
  border-radius: 100%;
  width: 14px;
  height: 14px;
  position: relative;
  top: 1px;
}

2020-03-17 21:17 UTC, lafriks commented
Yeah, looks a bit too small

2020-03-17 21:18 UTC, lafriks commented
14 could probably be more sensible

2020-03-18 00:46 UTC, everhopingandwaiting commented
![image](https://user-images.githubusercontent.com/6021724/76914281-b9660000-68f4-11ea-8de3-99883d2e784a.png)

@silverwind seems a little big ， if change the height size to 14px

2020-03-18 23:06 UTC, silverwind commented
> seems if change the height size to 14px, need to adjust the class of item , otherwise the icon can not align with text

The `position` and `top` in my example is for the vertical alignment. Flexbox centering might even be better.

2020-03-31 19:48 UTC, 6543 requested changes
to smal ...

2020-04-02 03:26 UTC, everhopingandwaiting commented
![image](https://user-images.githubusercontent.com/6021724/78207645-dabe1300-74d4-11ea-89aa-765db076d166.png)

2020-04-02 06:47 UTC, lafriks requested changes

2020-04-02 06:47 UTC, lafriks commented on web_src/less/_base.less
> +    //padding-right: .7em;
```suggestion
```

2020-04-02 06:47 UTC, lafriks commented on web_src/less/_base.less
> +    //padding-left: .5em;
```suggestion
```

2020-04-02 06:48 UTC, lafriks approved these changes

2020-04-02 10:27 UTC, 6543 approved these changes

2020-04-02 11:18 UTC, merged