[feature] provide `OwnerName` field for README template
go-gitea/gitea pull request #10981
Opened 2020-04-06 01:37 UTC by everhopingandwaiting

reopen: pr  #10356

2020-04-06 02:05 UTC, 6543 approved these changes

2020-04-06 02:06 UTC, 6543 commented
I think we net do ducument the vars ... I'll send a pull for this

2020-04-07 00:26 UTC, 6543 commented
@everhopingandwaiting since #10983 got merged:
can you "update" your featurebranc and extend `docs/content/doc/advanced/customizing-gitea.en-us.md` by adding your new variable to the note?

2020-04-07 00:53 UTC, 6543 commented
@everhopingandwaiting a hint: you should make `git pull -r`  before `git push`

2020-04-07 01:03 UTC, everhopingandwaiting commented
> @everhopingandwaiting a hint: you should make `git pull -r` before `git push`

should I choose rebase or merge to select upstream changes in my origin branch?
![image](https://user-images.githubusercontent.com/6021724/78618971-93f26380-78ae-11ea-975e-22ba2f476ef9.png)

2020-04-07 01:09 UTC, 6543 commented
@everhopingandwaiting If you like to chat with me -> https://discord.gg/Gitea

2020-04-07 01:10 UTC, everhopingandwaiting commented
> @everhopingandwaiting since #10983 got merged:
> can you "update" your featurebranch and extend `docs/content/doc/advanced/customizing-gitea.en-us.md` by adding your new variable to the note?

```
**NOTE:** readme templates support **variable expansion**.  
currently there are `{Name}` (name of repository), `{Description}`, `{CloneURL.SSH}` and `{CloneURL.HTTPS}`

```
seems I should change `OwnerName` to `Name`   😉

```go
"Description":    repo.Description,
		"CloneURL.SSH":   cloneLink.SSH,			"CloneURL.SSH":   cloneLink.SSH,
		"CloneURL.HTTPS": cloneLink.HTTPS,			"CloneURL.HTTPS": cloneLink.HTTPS,
		"OwnerName":      repo.OwnerName,
```

2020-04-07 01:12 UTC, guillep2k approved these changes

2020-04-07 01:13 UTC, 6543 requested changes
blocking since need addition to docs

2020-04-07 01:14 UTC, 6543 commented
just add your `OwnerName` to the list in `docs/content/doc/advanced/customizing-gitea.en-us.md`

2020-04-07 01:20 UTC, everhopingandwaiting commented
> @everhopingandwaiting If you like to chat with me -> https://discord.gg/Gitea

Unknown cause ， the site is blocked 😜
![image](https://user-images.githubusercontent.com/6021724/78619749-c8ffb580-78b0-11ea-94e6-d410ad3db6a5.png)

2020-04-07 01:20 UTC, 6543 commented on docs/content/doc/advanced/customizing-gitea.en-us.md
> +currently there are `{OwnerName}` (name of repository), `{Description}`, `{CloneURL.SSH}` and `{CloneURL.HTTPS}`
```suggestion
currently there are `{Name}` (name of repository), `{Description}`, `{CloneURL.SSH}`, `{CloneURL.HTTPS}` and `{OwnerName}`
```

2020-04-07 01:20 UTC, 6543 requested changes
just "apply"

2020-04-07 01:21 UTC, 6543 approved these changes
thx

2020-04-07 01:40 UTC, merged

2020-04-14 08:50 UTC, a1012112796 commented
I wander why this PR is not on any Milestone ?

2020-04-14 08:56 UTC, everhopingandwaiting commented
on 1.12, but reopen

2020-04-14 09:21 UTC, lunny commented
@a1012112796 most docs PRs we haven't added milestone because most of them are outdate documents so that we should not mark them on the milestone.

2020-04-14 09:25 UTC, a1012112796 commented on modules/repository/init.go
> +		"OwnerName":      repo.OwnerName,
@lunny But  I also wander it's only a docs change ...