fix some bug about Request review
go-gitea/gitea pull request #11040
Opened 2020-04-10 17:19 UTC by a1012112796

* fix ``CreateComment`` wrong using ,it will not work when use Sqlite
* fix wrong js click event code , it will send wrong data when it has many choices

2020-04-10 17:23 UTC, lafriks approved these changes

2020-04-10 17:25 UTC, lafriks requested changes

2020-04-10 17:25 UTC, lafriks commented on web_src/js/index.js
> +    const issue_id = $(this).data('issue-id');
```suggestion
    const issueId = $(this).data('issue-id');
```

2020-04-10 17:25 UTC, lafriks commented on web_src/js/index.js
> +    const is_checked = $(this).data('is-checked');
```suggestion
    const isChecked = $(this).data('is-checked');
```

2020-04-10 17:25 UTC, lafriks commented on web_src/js/index.js
> +      issue_id,
```suggestion
      issueId,
```

2020-04-10 17:25 UTC, lafriks commented on web_src/js/index.js
> +      is_checked
```suggestion
      isChecked
```

2020-04-10 17:51 UTC, mrsdizzie approved these changes

2020-04-10 18:37 UTC, lafriks approved these changes

2020-04-10 21:34 UTC, 6543 commented on models/review.go
> +	comment, err = createComment(sess, &CreateCommentOptions{
nice catch

2020-04-10 21:36 UTC, 6543 commented
@a1012112796 `GetReviewerByIssueIDAndUserID` also need a version witch can use sess !!

2020-04-10 21:38 UTC, 6543 commented
for **GetReviewerByIssueIDAndUserID**: rename it to **getReviewerByIssueIDAndUserID** and create a second function caled **GetReviewerByIssueIDAndUserID** witch use **getReviewerByIssueIDAndUserID**

similar to what you can find here:
https://github.com/go-gitea/gitea/blob/bc362ea3c611a94e7920a3cf4691fd108f874ef0/models/issue_comment.go#L768-L773

2020-04-10 21:39 UTC, 6543 commented
then use getReviewerByIssueIDAndUserID in RemoveRewiewRequest - thanks!

2020-04-11 02:49 UTC, a1012112796 commented
@6543 done your suggestion, please review . Thanks

2020-04-11 04:13 UTC, guillep2k approved these changes

2020-04-11 04:44 UTC, merged

2020-04-11 06:21 UTC, 6543 commented
@a1012112796 thanks, it was exactly what I ment :)