[Partial Backport]  add tracked time fix to doctor (part of #11111)
go-gitea/gitea pull request #11138
Opened 2020-04-19 16:46 UTC by 6543

backport tracked-time fix (part of #11111)

to fix an issue witch v1.11 gitea instances can have (#10280)

2020-04-19 16:46 UTC, 6543 commented on cmd/doctor.go
> +		isDefault: false,
```suggestion
		isDefault: true,
```

2020-04-19 19:12 UTC, zeripath approved these changes

2020-04-21 03:30 UTC, guillep2k approved these changes
For consistency, I'd rather front-port this PR and work #11111 from there.

2020-04-21 06:37 UTC, zeripath requested changes
Blocked until #11111 is merged

2020-05-18 17:48 UTC, 6543 commented
since doctor got released this is now **kind/breaking** !

2020-05-20 21:06 UTC, lafriks commented
Released in what version?

2020-05-20 22:40 UTC, 6543 commented
1.11 since doctor got backported by @zeripath

2020-05-21 11:50 UTC, lafriks approved these changes

2020-05-29 13:25 UTC, zeripath commented
Do we still want this backported to 1.11.6? my suspicion is not but I guess it might be helpful?

2020-05-29 13:30 UTC, 6543 commented
@zeripath I would partialy backport it to fix an issue described in #10280

I would leave this implementation as it is now and the comand wont change from there on only get more functions&checks :)

2020-05-29 13:38 UTC, 6543 commented
@zeripath or should I add DB version check and move fix functions into models ?

(as 11111 has now)

2020-05-29 13:50 UTC, zeripath approved these changes

2020-05-29 15:40 UTC, zeripath commented
make lg-tm work

2020-05-29 15:41 UTC, merged