Split some words from template to improve translation.
go-gitea/gitea pull request #11221
Opened 2020-04-26 17:11 UTC by L0veSunshine

As title.

2020-04-26 18:38 UTC, lafriks submitted a review, later dismissed

2020-04-26 18:38 UTC, lafriks commented on options/locale/locale_en-US.ini
> +settings.search_team = Search Team...
```suggestion
settings.search_team = Search Team…
```

2020-04-26 18:58 UTC, 6543 requested changes

2020-04-26 18:58 UTC, 6543 commented on templates/repo/settings/collaboration.tmpl
> +					<div class="ui eight wide column poping up" data-content={{$.i18n.Tr "repo.settings.change_team_permission_tip"}}>
```suggestion
					<div class="ui eight wide column poping up" data-content="{{$.i18n.Tr "repo.settings.change_team_permission_tip"}}">
```

2020-04-26 18:58 UTC, 6543 commented on templates/repo/settings/collaboration.tmpl
> +						<div class="ui two wide column {{if .IncludesAllRepositories}}poping up{{end}}" {{if .IncludesAllRepositories}} data-content= {{$.i18n.Tr "repo.settings.delete_team_tip"}} {{end}}>
```suggestion
						<div class="ui two wide column {{if .IncludesAllRepositories}}poping up{{end}}" {{if .IncludesAllRepositories}} data-content="{{$.i18n.Tr "repo.settings.delete_team_tip"}}"{{end}}>
```

2020-04-26 18:58 UTC, 6543 commented on templates/repo/settings/collaboration.tmpl
> +								<input class="prompt" name="team" placeholder={{$.i18n.Tr "repo.settings.search_team"}} autocomplete="off" autofocus required>
```suggestion
								<input class="prompt" name="team" placeholder="{{$.i18n.Tr "repo.settings.search_team"}}" autocomplete="off" autofocus required>
```

2020-04-26 19:46 UTC, 6543 approved these changes

2020-04-29 06:45 UTC, zeripath approved these changes

2020-04-29 10:12 UTC, 6543 commented
@lafriks this needs your review

2020-05-08 12:38 UTC, zeripath commented
make lg-tm work

2020-05-08 12:39 UTC, merged