BugFix: updateLabel can updated not allowed fields
go-gitea/gitea pull request #11242
Opened 2020-04-28 21:48 UTC by 6543

fix #11238

2020-04-28 21:54 UTC, lafriks requested changes

2020-04-28 21:54 UTC, lafriks commented on models/issue_label.go
> +func updateLabelNum(e Engine, l *Label) error {
There is no point for this function

2020-04-28 22:15 UTC, zeripath approved these changes

2020-04-28 22:33 UTC, lafriks commented on models/issue_label.go
> +	return updateLabelCols(x, l, "name", "description", "color", "num_issues", "num_closed_issues")
```suggestion
	return updateLabelCols(x, l, "name", "description", "color")
```

2020-04-28 22:35 UTC, lafriks approved these changes

2020-04-28 23:12 UTC, 6543 commented
ping lgtm bot

2020-04-28 23:28 UTC, merged

2020-04-30 04:31 UTC, guillep2k commented
@6543 I marked this as skip-changelog as I believe the bug was introduced in the 1.12-dev branch. Please correct me if I'm wrong.

2020-04-30 09:59 UTC, 6543 commented
you are right ... :)