[WIP] GPG commit validation
go-gitea/gitea pull request #1150
Opened 2017-03-09 00:25 UTC by sapk

Display signed commit and validation against gpg key in database. I have started with a very little UI with the a simple title attr indicating the reason. 

Examples:
Good signature :
![capture d ecran_2017-03-09_01-21-09](https://cloud.githubusercontent.com/assets/4052400/23730241/bbc65110-0466-11e7-9903-6fb923083f6c.png)

Unknown signature :
![capture d ecran_2017-03-09_01-20-21](https://cloud.githubusercontent.com/assets/4052400/23730242/bbc68630-0466-11e7-9bc7-40e1489faa90.png)

For comparison : https://github.com/sapk/testing-git/commits/master

Need and follow : #710 go-gitea/git#36

2017-03-09 00:46 UTC, lunny commented
build failed. and it seems the image is not transparent ?

2017-03-09 01:13 UTC, appleboy requested changes

2017-03-09 01:13 UTC, appleboy commented on models/gpg_key.go
> +)
please following the style guide. https://github.com/go-gitea/gitea/blob/master/CONTRIBUTING.md#styleguide

2017-03-09 09:48 UTC, sapk commented on models/gpg_key.go
> +)
Thx for the catch i will fix it in the PR of the API from where I start : https://github.com/go-gitea/gitea/pull/710/files

2017-03-09 10:05 UTC, sapk commented
I didn't precise but this is a really early WIP. For the build failed is that it need the go-gitea/git#36 change.
In this go-gitea/git#36 we need to discuss a litlle about https://github.com/sapk-fork/git-module/blob/1395a17c1a5a05a465032519932794c486e43559/commit.go#L35 and test in this PR if we could do without or if is to much burden and keep the raw payload.

I open this PR mainly to be able to discuss UI design.

2017-03-11 00:42 UTC, sapk commented
Validation of commit is ok and display a simple message on hover (title attr) with user/key that succeed or why it failed. 

I need to add more detail in commit page.

For the little API part, I have a problem with json auto-encoding replacing "<" and ">" don't know the good way to tckle this prob in gitea.
https://golang.org/pkg/encoding/json/#Marshal
```
"verification": {
            "verified": true,
            "reason": "Antoine GIRARD \u003csapk@sapk.fr\u003e / AE8255B8A0D828E4",
            "signature": "-----BEGIN PGP SIGNATURE-----\n\niQEzBAABCAAdFiEEEIOwJg/1vpF1itJ4roJVuKDYKOQFAljC2uIACgkQroJVuKDY\nKOSkQgf+KFT2smNxRlL8S3zptsJAr4fQVV1Lmia5TdepJIUGDvlZMTNuNk2gHqeQ\nnuIJtKGzTD8s5vJIHUQSH2R82oizRPJNSaFKbohTwmMNphQ5uq4gt5DEELkfcNpo\n75N8m0ck+L2+iyPUqmvcofaUqRYjqrvMz/BJ7fB8kEzEJukvjkepfKAQ59T+dzYD\nTd5TY48L18lJv5EdBlNdzpP62/731LEEktUWb6Nttl4MCRXR5CBRPlpBv8rQekjX\nycUAnVM1Yk1BxUQ6zBXJj7xIrc5RChbsDnvAVZmzWtEzME+9w9JiTHg51EJ/fT36\nX6TUL4VQhEhdoQZqJDbzUmIYwPbUoQ==\n=lqpn\n-----END PGP SIGNATURE-----",
            "payload": "tree 7377d79e8a22b4ba522ea204fcdd175490706dd2\nparent 74cde12677bc548487ed1caf192eb19b0b7cf99c\nauthor Antoine GIRARD \u003csapk@sapk.fr\u003e 1488936721 +0100\ncommitter Antoine GIRARD \u003csapk@sapk.fr\u003e 1489165026 +0100\n\nImplement GPG API\n"
        },  
```

2017-03-12 18:55 UTC, wevcode commented
Great work! Like to see it in Gitea. 👍 
But in my opinion your display solution looks more like a CI indicator. Maybe you want to use something like a lock which is green, open or gray. What do you think?

(And "Message" should be on the same line than all commit messages.)

2017-03-12 22:42 UTC, sapk commented
Visual updated in description.

2017-03-12 22:48 UTC, wevcode commented
@sapk Great! If you only see the question mark, you do not know *what* is missing. I would use a gray lock which indicates that this commit is signed but not trusted.

2017-03-12 23:03 UTC, sapk commented
I think that if we use a grey lock it could be understood as trusted (with less security) also by the user and that is not the case. Actually if you hover the question mark it display "No good signature found in keystore" but i plan to find a better describing string like "No known key found for this signature" ?
Furthermore, I will add more detail in the commit page about the signature and is validity against key in db.

2017-03-12 23:05 UTC, wevcode commented
@sapk I think it will also be much cleaner if you use no border radius between the hash and the symbol. 
![noborderradiuslock](https://cloud.githubusercontent.com/assets/24939399/23836952/895a52d6-0780-11e7-9937-e3bad3b8a1d2.png)
One might use `border-top-left-radius` and its variations. :)

2017-03-12 23:06 UTC, wevcode commented
@sapk I see your point. What about an open gray lock?

2017-03-12 23:26 UTC, sapk commented
Changes made 
I also tested changing the icon background a little darker but I don't really know if it is usefull.
![capture d ecran_2017-03-13_00-22-05](https://cloud.githubusercontent.com/assets/4052400/23837117/8908fc80-0783-11e7-89b3-3705f1ac2f44.png)

2017-03-12 23:30 UTC, wevcode commented
Nice! :100:

Background is ok. Do you think some kind of really small green border around the hash and icon looks good? (Border)

2017-03-12 23:42 UTC, sapk commented
Like that ? 
![image](https://cloud.githubusercontent.com/assets/4052400/23837279/f1446d96-0785-11e7-83db-8a5557a4a8b7.png)

2017-03-12 23:45 UTC, wevcode commented
Yes, looks good. :) Green border: "my hash is trusted" :check:

2017-03-12 23:51 UTC, sapk commented
![image](https://cloud.githubusercontent.com/assets/4052400/23837361/31f44cf2-0787-11e7-9bd6-5ddb4dff611a.png)
 Better ?

2017-03-12 23:54 UTC, wevcode commented
This is really good! But then we should add a gray border around untrusted signatures and commits without. :)

2017-03-13 00:02 UTC, sapk commented
![image](https://cloud.githubusercontent.com/assets/4052400/23837447/c4393d6a-0788-11e7-9cfe-7d0fadb802f8.png)

2017-03-13 00:57 UTC, sapk commented
Some test for commit page.

![image](https://cloud.githubusercontent.com/assets/4052400/23837944/503e1568-0790-11e7-8bde-c8e0524f6993.png)

![image](https://cloud.githubusercontent.com/assets/4052400/23837939/3ceb6394-0790-11e7-8314-b7a330f4002e.png)

![image](https://cloud.githubusercontent.com/assets/4052400/23837947/5ad57692-0790-11e7-85ce-a07d4a2f7a45.png)

2017-03-13 06:51 UTC, wevcode commented
Looks good. I would use a grey lock on commit page as you have used in the commit list - not a black one.

2017-03-13 06:53 UTC, wevcode commented
I am not sure if one should also use the border system of the commit list for the whole commit box on these single pages - so a green border around everything, might be too colorful.

2017-03-13 07:03 UTC, lunny commented
Yes. green border and background with black text maybe better.

2017-03-13 09:36 UTC, wevcode commented
@lunny Border and background yes - but I would keep the green font for the signature itself.

2017-03-13 18:49 UTC, sapk commented
Like that : 
![image](https://cloud.githubusercontent.com/assets/4052400/23870228/10cd02ae-0826-11e7-9940-22feacc314a0.png)
![image](https://cloud.githubusercontent.com/assets/4052400/23870238/1900eb34-0826-11e7-93e6-c3d67fb29b24.png)
Note : now the build should be a succes with the updated git dep

2017-03-13 19:25 UTC, wevcode commented
Expand the border around "Google GPG" and "Browse Source" but do not change the background. :) I think that was the @lunny 's idea.

2017-03-13 21:12 UTC, sapk commented
For the border around complete block could be done but i have to tweak a little the css of attached to change side border on .attached, + bottom for .bottom, + top for .top

I will try something.

2017-03-13 22:06 UTC, sapk commented
![image](https://cloud.githubusercontent.com/assets/4052400/23877230/9bc1b5ce-0841-11e7-9385-6118998b45fd.png)
Like that ?

2017-03-13 22:32 UTC, wevcode commented
Yes, but not around diffs - I would say.

2017-03-13 22:35 UTC, Fastidious commented
I agree with @wevcode, around diffs would be too much, IMHO.

2017-03-14 01:24 UTC, lunny commented
@sapk Great and I agree with @wevcode and @Fastidious

2017-03-14 10:33 UTC, sapk commented
Ok I will clean this up a little.

2017-03-15 23:25 UTC, sapk commented
![image](https://cloud.githubusercontent.com/assets/4052400/23975080/1362ca5c-09df-11e7-824a-506abf61d5c2.png)

2017-03-15 23:26 UTC, Fastidious commented
@sapk excellent, and lovely!

2017-03-15 23:28 UTC, wevcode commented
@sapk Amazing! What is the overall status of this huge feature?


On March 16, 2017 00:26:54 Fastidious <notifications@github.com> wrote:

> @sapk excellent, and lovely!
>
> --
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/go-gitea/gitea/pull/1150#issuecomment-286911357

2017-03-15 23:40 UTC, sapk commented
I updated the post todo list.
It just need some new translation strings.
For deps of this PR, the git changes are merged and updated in vendor of this PR. 
The #710 could be merge, it "just" need to be finally review and LGTM.

For usability, I talk a little in gitter for the UI to manage users keys. It could be done by api via #710 but really need a easy to use interface. I will go rework a little ssh keys page that could have impact so i will do it in a other PR maybe to be more readable.

2017-03-16 00:27 UTC, sapk commented
Translation done this is reviewable now. But since it need #710 maybe wait for it to be merge a just take in account the two last commit.

2017-03-16 07:01 UTC, strk commented on models/error.go
> +// ErrGPGKeyNotExist represents a "GPGKeyNotExist" kind of error.
May I suggest to put this in error_gpg.go instead ?

2017-03-16 07:47 UTC, lunny commented
@sapk #710 merged but there are conflicts

2017-03-16 10:18 UTC, sapk commented
I will rebase on current master

2017-03-16 10:33 UTC, sapk commented on models/error.go
> +// ErrGPGKeyNotExist represents a "GPGKeyNotExist" kind of error.
This is a change maid in #710 but I can split it to make more simple file.

2017-03-16 10:39 UTC, wevcode commented
Hopefully it will be finished for 1.2.0

2017-03-16 11:01 UTC, strk commented on models/error.go
> +// ErrGPGKeyNotExist represents a "GPGKeyNotExist" kind of error.
Yes, I meant for the whole GPG block, not just for that single class :)

2017-03-16 12:41 UTC, sapk commented
So I rebase on master, this will be easier to review.

2017-03-17 09:51 UTC, sapk commented
There a more efficient way to validate signature that I will have to test more.

2017-03-17 10:43 UTC, lunny commented
One could have two same gpg keys?

2017-03-17 10:57 UTC, Fastidious commented
@lunny no.

2017-03-17 11:05 UTC, sapk commented
@lunny https://github.com/go-gitea/gitea/pull/710/files#diff-212b9fa4c927665ecbc5a5a36382ecedR111

2017-03-17 11:40 UTC, lunny commented on models/gpg_key.go
> +	"github.com/ngaut/log"
why use this log?

2017-03-17 12:39 UTC, sapk commented on models/gpg_key.go
> +	"github.com/ngaut/log"
That my editor that auto-import :-(

2017-03-17 23:25 UTC, sapk commented
So after testing it seems that .IssuerKeyId in sig is not the same the the KeyID of key so remove testing commits.

2017-03-18 03:03 UTC, lunny commented
Another thing, maybe all `Id` should be `ID`.

2017-03-19 17:24 UTC, sapk commented
@lunny I didn't found any "Id" string in my change where did you see it ?

2017-03-19 17:37 UTC, strk commented
@sapk `make lint` should find any of those, but given drone passes I guess there are none ?

2017-03-19 17:43 UTC, strk commented
LGTM, great to also see tests in here !

2017-03-19 17:45 UTC, strk commented
@sapk I guess migrations are needed, right ?

2017-03-19 17:57 UTC, sapk commented
@strk I have try to separate api and db from validation and presentation.
So there is no change in DB in this PR. All change needed were made in the API PR (with a bug for mariadb #1303). All the new types are just for display (CommitVerification, SignCommit). This PR is just validation of commit and display it. API handle change in DB and manipulation via API (Add, remove, list, ...)
A other PR for managing user gpg keys via UI is in WIP. #1293.

I think it will be best to merge it after fix #1303.

2017-03-21 00:57 UTC, lunny commented
@sapk #1303 is merged, maybe this need rebase?

2017-03-21 09:45 UTC, sapk commented
@lunny I could rebase to be sure that everything works and be more clear but it's not needed. The goal of API was to put the foundation with db format and base object. This PR don't change DB and base object so this would merge seamlessly. All the new code is only call for rendering and don't even write to DB.

2017-03-21 10:05 UTC, lunny commented
@sapk this PR is ready to review and merge?

2017-03-21 10:17 UTC, sapk commented
Yes and allready have a LGTM ^^

2017-03-22 09:10 UTC, strk commented
LGTM, but I think we should deal with vendoring in a different way (as I know another `git` vendor upgrade is needed for the `--follow` support :/)

2017-03-22 09:11 UTC, strk commented
Make L-G-T-M work !

2017-03-22 10:42 UTC, lunny commented
LGTM

2017-03-22 10:43 UTC, merged