API return json on 500 error
go-gitea/gitea pull request #11574
Opened 2020-05-23 01:28 UTC by 6543

if ctx.InternalServerError(err) is used it will return the default 500 html page

on API a json Error is expected

2020-05-23 01:30 UTC, 6543 commented
just noticed this behaviour - it was not documented at all - of coures if you do a code lookup you can see it too :)

2020-05-23 01:31 UTC, 6543 commented
@techknowlogick can we backport this somehow?

2020-05-23 01:34 UTC, techknowlogick commented
whoops. label didn't apply at first. It's there now:)

2020-05-23 01:45 UTC, 6543 reviewed
better error logging

2020-05-23 01:45 UTC, 6543 commented on routers/api/v1/misc/markdown.go
> +				ctx.Error(http.StatusInternalServerError, "", err)
```suggestion
				ctx.Error(http.StatusInternalServerError, "ctx.Write", err)
```

2020-05-23 01:45 UTC, 6543 commented on routers/api/v1/misc/markdown.go
> +				ctx.Error(http.StatusInternalServerError, "", err)
```suggestion
				ctx.Error(http.StatusInternalServerError, "markdown.Render", err)
```

2020-05-23 01:45 UTC, 6543 commented on routers/api/v1/misc/markdown.go
> +			ctx.Error(http.StatusInternalServerError, "", err)
```suggestion
			ctx.Error(http.StatusInternalServerError, "markdown.RenderRaw", err)
```

2020-05-23 01:45 UTC, 6543 commented on routers/api/v1/misc/markdown.go
> +		ctx.Error(http.StatusInternalServerError, "", err)
```suggestion
		ctx.Error(http.StatusInternalServerError, "markdown.RenderRaw", err)
```

2020-05-23 01:45 UTC, 6543 commented on routers/api/v1/notify/repo.go
> +		ctx.Error(http.StatusInternalServerError, "", err)
```suggestion
		ctx.Error(http.StatusInternalServerError, "GetQueryBeforeSince", err)
```

2020-05-23 01:45 UTC, 6543 commented on routers/api/v1/notify/repo.go
> +		ctx.Error(http.StatusInternalServerError, "", err)
```suggestion
		ctx.Error(http.StatusInternalServerError, "GetNotifications", err)
```

2020-05-23 01:45 UTC, 6543 commented on routers/api/v1/notify/repo.go
> +		ctx.Error(http.StatusInternalServerError, "", err)
```suggestion
		ctx.Error(http.StatusInternalServerError, "nl.LoadAttributes", err)
```

2020-05-23 01:45 UTC, 6543 commented on routers/api/v1/notify/repo.go
> +			ctx.Error(http.StatusInternalServerError, "", err)
```suggestion
			ctx.Error(http.StatusInternalServerError, "time.Parse", err)
```

2020-05-23 01:45 UTC, 6543 commented on routers/api/v1/notify/repo.go
> +		ctx.Error(http.StatusInternalServerError, "", err)
```suggestion
		ctx.Error(http.StatusInternalServerError, "GetNotifications", err)
```

2020-05-23 01:45 UTC, 6543 commented on routers/api/v1/notify/repo.go
> +			ctx.Error(http.StatusInternalServerError, "", err)
```suggestion
			ctx.Error(http.StatusInternalServerError, "SetNotificationStatus", err)
```

2020-05-23 01:45 UTC, 6543 commented on routers/api/v1/notify/threads.go
> +		ctx.Error(http.StatusInternalServerError, "", err)
```suggestion
		ctx.Error(http.StatusInternalServerError, "n.LoadAttributes", err)
```

2020-05-23 01:45 UTC, 6543 commented on routers/api/v1/notify/threads.go
> +		ctx.Error(http.StatusInternalServerError, "", err)
```suggestion
		ctx.Error(http.StatusInternalServerError, "SetNotificationStatus", err)
```

2020-05-23 01:45 UTC, 6543 commented on routers/api/v1/notify/threads.go
> +			ctx.Error(http.StatusInternalServerError, "", err)
```suggestion
			ctx.Error(http.StatusInternalServerError, "GetNotificationByID", err)
```

2020-05-23 01:45 UTC, 6543 commented on routers/api/v1/notify/user.go
> +		ctx.Error(http.StatusInternalServerError, "", err)
```suggestion
		ctx.Error(http.StatusInternalServerError, "GetQueryBeforeSince", err)
```

2020-05-23 01:45 UTC, 6543 commented on routers/api/v1/notify/user.go
> +		ctx.Error(http.StatusInternalServerError, "", err)
```suggestion
		ctx.Error(http.StatusInternalServerError, "GetNotifications", err)
```

2020-05-23 01:45 UTC, 6543 commented on routers/api/v1/notify/user.go
> +		ctx.Error(http.StatusInternalServerError, "", err)
```suggestion
		ctx.Error(http.StatusInternalServerError, "nl.LoadAttributes", err)
```

2020-05-23 01:45 UTC, 6543 commented on routers/api/v1/notify/user.go
> +			ctx.Error(http.StatusInternalServerError, "", err)
```suggestion
			ctx.Error(http.StatusInternalServerError, "time.Parse", err)
```

2020-05-23 01:45 UTC, 6543 commented on routers/api/v1/notify/user.go
> +		ctx.Error(http.StatusInternalServerError, "", err)
```suggestion
		ctx.Error(http.StatusInternalServerError, "GetNotifications", err)
```

2020-05-23 01:45 UTC, 6543 commented on routers/api/v1/notify/user.go
> +			ctx.Error(http.StatusInternalServerError, "", err)
```suggestion
			ctx.Error(http.StatusInternalServerError, "SetNotificationStatus", err)
```

2020-05-23 01:45 UTC, 6543 commented on routers/api/v1/org/team.go
> +		ctx.Error(http.StatusInternalServerError, "", err)
```suggestion
		ctx.Error(http.StatusInternalServerError, "GetUnits", err)
```

2020-05-23 01:45 UTC, 6543 commented on routers/api/v1/repo/branch.go
> +		ctx.Error(http.StatusInternalServerError, "", err)
```suggestion
		ctx.Error(http.StatusInternalServerError, "IsProtectedBranch", err)
```

2020-05-23 01:45 UTC, 6543 commented on routers/api/v1/repo/issue.go
> +		ctx.Error(http.StatusInternalServerError, "", err)
```suggestion
		ctx.Error(http.StatusInternalServerError, "GetIssueByID", err)
```

2020-05-23 01:45 UTC, 6543 commented on routers/api/v1/repo/issue.go
> +		ctx.Error(http.StatusInternalServerError, "", err)
```suggestion
		ctx.Error(http.StatusInternalServerError, "issue.LoadMilestone", err)
```

2020-05-23 01:45 UTC, 6543 commented on routers/api/v1/repo/issue_comment.go
> +		ctx.Error(http.StatusInternalServerError, "", err)
```suggestion
		ctx.Error(http.StatusInternalServerError, "comment.LoadIssue", err)
```

2020-05-23 01:45 UTC, 6543 commented on routers/api/v1/repo/issue_subscription.go
> +		ctx.Error(http.StatusInternalServerError, "", err)
```suggestion
		ctx.Error(http.StatusInternalServerError, "CheckIssueWatch", err)
```

2020-05-23 01:45 UTC, 6543 commented on routers/api/v1/repo/issue_tracked_time.go
> +		ctx.Error(http.StatusInternalServerError, "", err)
```suggestion
		ctx.Error(http.StatusInternalServerError, "GetQueryBeforeSince", err)
```

2020-05-23 01:45 UTC, 6543 commented on routers/api/v1/repo/issue_tracked_time.go
> +		ctx.Error(http.StatusInternalServerError, "", err)
```suggestion
		ctx.Error(http.StatusInternalServerError, "GetQueryBeforeSince", err)
```

2020-05-23 01:45 UTC, 6543 commented on routers/api/v1/repo/issue_tracked_time.go
> +		ctx.Error(http.StatusInternalServerError, "", err)
```suggestion
		ctx.Error(http.StatusInternalServerError, "GetQueryBeforeSince", err)
```

2020-05-23 01:45 UTC, 6543 commented on routers/api/v1/repo/topic.go
> +		ctx.Error(http.StatusInternalServerError, "", err)
```suggestion
		ctx.Error(http.StatusInternalServerError, "ListTopics", err)
```

2020-05-23 01:45 UTC, 6543 commented on routers/api/v1/repo/topic.go
> +		ctx.Error(http.StatusInternalServerError, "", err)
```suggestion
		ctx.Error(http.StatusInternalServerError, "SaveTopics", err)
```

2020-05-23 01:45 UTC, 6543 commented on routers/api/v1/repo/topic.go
>  		log.Error("ListTopics failed: %v", err)
```suggestion
```

2020-05-23 01:45 UTC, 6543 commented on routers/api/v1/repo/topic.go
>  		log.Error("SaveTopics failed: %v", err)
```suggestion
```

2020-05-23 01:45 UTC, 6543 commented on routers/api/v1/repo/topic.go
> +		ctx.Error(http.StatusInternalServerError, "", err)
```suggestion
		ctx.Error(http.StatusInternalServerError, "AddTopic", err)
```

2020-05-23 01:45 UTC, 6543 commented on routers/api/v1/repo/topic.go
>  		log.Error("AddTopic failed: %v", err)
```suggestion
```

2020-05-23 01:45 UTC, 6543 commented on routers/api/v1/repo/topic.go
>  		log.Error("AddTopic failed: %v", err)
```suggestion
```

2020-05-23 01:45 UTC, 6543 commented on routers/api/v1/repo/topic.go
> +		ctx.Error(http.StatusInternalServerError, "", err)
```suggestion
		ctx.Error(http.StatusInternalServerError, "AddTopic", err)
```

2020-05-23 01:45 UTC, 6543 commented on routers/api/v1/repo/topic.go
> +		ctx.Error(http.StatusInternalServerError, "", err)
```suggestion
		ctx.Error(http.StatusInternalServerError, "DeleteTopic", err)
```

2020-05-23 01:45 UTC, 6543 commented on routers/api/v1/repo/topic.go
>  		log.Error("DeleteTopic failed: %v", err)
```suggestion
```

2020-05-23 01:45 UTC, 6543 commented on routers/api/v1/repo/topic.go
>  		log.Error("SearchTopics failed: %v", err)
```suggestion
```

2020-05-23 01:45 UTC, 6543 commented on routers/api/v1/repo/topic.go
> +		ctx.Error(http.StatusInternalServerError, "", err)
```suggestion
		ctx.Error(http.StatusInternalServerError, "SearchTopics", err)
```

2020-05-23 01:45 UTC, 6543 commented on routers/api/v1/repo/transfer.go
> +		ctx.Error(http.StatusInternalServerError, "", err)
```suggestion
		ctx.Error(http.StatusInternalServerError, "GetUserByName", err)
```

2020-05-23 01:45 UTC, 6543 commented on routers/api/v1/repo/transfer.go
> +		ctx.Error(http.StatusInternalServerError, "", err)
```suggestion
		ctx.Error(http.StatusInternalServerError, "TransferOwnership", err)
```

2020-05-23 01:45 UTC, 6543 commented on routers/api/v1/repo/transfer.go
> +		ctx.Error(http.StatusInternalServerError, "", err)
```suggestion
		ctx.Error(http.StatusInternalServerError, "GetRepositoryByName", err)
```

2020-05-23 01:45 UTC, 6543 commented on routers/api/v1/user/app.go
> +		ctx.Error(http.StatusInternalServerError, "", err)
```suggestion
		ctx.Error(http.StatusInternalServerError, "AccessTokenByNameExists", err)
```

2020-05-23 10:36 UTC, silverwind commented
Bit of a shame that this needs to be done in every route. The way I'd handle this in JS routing is to let errors throw in the routes and then process them in a "catch-all" route but I guess with missing exceptions, this is not possible in Golang.

2020-05-24 05:45 UTC, zeripath approved these changes

2020-05-24 05:46 UTC, zeripath commented
The other option is for the API context to provide its own internalservererror function

2020-05-24 12:40 UTC, 6543 commented
we should keep it simple ...

2020-05-24 13:34 UTC, zeripath commented
That would be simpler...

in modules/context/api.go add the following function:

```

// InternalServerError responds with an error message to the client with the error as a message and the file and line of the caller.
func (ctx *APIContext) InternalServerError(err error) {
	log.ErrorWithSkip(1, "InternalServerError: %v", err)

	ctx.JSON(http.StatusInternalServerError, APIError{
		Message: err.Error(),
		URL:     setting.API.SwaggerURL,
	})
}
```

And whilst you're at it change the above function to: ```go
// Error responds with an error message to client with given obj as the message.
// If status is 500, also it prints error to log.
func (ctx *APIContext) Error(status int, title string, obj interface{}) {
	var message string
	if err, ok := obj.(error); ok {
		message = err.Error()
	} else {
		message = obj.(string)
	}

	if status == http.StatusInternalServerError {
		log.ErrorWithSkip(1, "%s: %s", title, message)
	}

	ctx.JSON(status, APIError{
		Message: message,
		URL:     setting.API.SwaggerURL,
	})
}
```

2020-05-24 14:21 UTC, zeripath commented on modules/context/api.go
>  		message = obj.(string)
Just thinking on this might be nicer

```suggestion
		message = fmt.Sprintf("%s", obj)
```

2020-05-24 14:24 UTC, zeripath approved these changes
Much simpler

2020-05-24 15:50 UTC, lafriks requested changes
But won't this reveal internal error messages in api? That would be bad from security point of view

2020-05-24 18:27 UTC, silverwind commented
What secrets would they reveal? Does it matter in an open-source application?

2020-05-24 23:28 UTC, 6543 commented
> But won't this reveal internal error messages in api? That would be bad from security point of view

@lafriks 
they already do it now!!
just in html output and now in json

2020-05-24 23:38 UTC, lafriks commented
I don't think actual error message is returned, if it is it should be fixed not to be. Even returning things like paths where Gitea is installed can be dangerous as it could give out information about where files are located. Also knowing what exact unexpected error is happening is so much easier to use it.
This does not matter if app is open source or not.

2020-05-25 06:16 UTC, zeripath commented
@lafriks the actual error message is returned currently - but yeah we shouldn't do that.
@6543 add a check like: 

https://github.com/go-gitea/gitea/blob/02a52d683b32e2670f746d898bd0041954390e7b/modules/context/context.go#L180

Before setting the message.

2020-05-26 09:47 UTC, zeripath approved these changes

2020-05-26 10:28 UTC, 6543 commented
@lafriks I think to hide 500 errors on API will need its own pull to correct 500 errors witch should have other http status codes ...

2020-05-26 11:05 UTC, zeripath commented
@6543 to fix the tests I guess if you just ensure that macaron.Env is set to development for them?

2020-05-26 23:05 UTC, 6543 commented
I would consider this as hotfix only

2020-05-26 23:13 UTC, lafriks approved these changes

2020-05-27 04:01 UTC, 6543 commented
Close this untill consensus reached, if it is done this way it is kind/breaking

I'll chat about tia on discord and reopen it avterwards again

2020-05-27 07:12 UTC, zeripath commented
Hmm... It's not breaking to make security changes - no one should be relying on reading the message of an internal security error.

500s mean that there is a bug.

They should not ever be expected.

2020-05-27 07:20 UTC, silverwind commented
I guess you can never make sure 500's don't happen but if they do, they should at least be in expected format (e.g. content-type json).

2020-05-27 09:30 UTC, 6543 commented
The problem Is: If tests fail they relay on the "message" part of an 500 error. witch mean there exist APIs witch return 500 for **expected** errors witch should be not the case in first place but they are

2020-05-27 09:44 UTC, zeripath commented
OK well technically it's a security bug to reveal errors in this fashion as it can be used to probe the server for vulnerabilities - so we have to fix this and can't just ignore it.

2020-05-27 09:48 UTC, 6543 commented
@zeripath @lafriks I think we should **revert** https://github.com/go-gitea/gitea/pull/11574/commits/8467b2cee674ad205b452780ca88abb1b27643c8 for **this** pull and fix this in a other one avter API endpoints dont return expected 500, else we cant realy backport this

2020-05-27 09:53 UTC, zeripath commented
How about we just put the err protection on the InternalServerError route? That way we don't make the situation any worse than we currently have and we can fix the Error(500, ...)s later?

2020-05-27 10:00 UTC, 6543 commented
@zeripath https://github.com/go-gitea/gitea/pull/11641#issuecomment-634556686 and 497f22689e1244dd6e2d294ace0ad08a09fa4e12

2020-05-27 10:02 UTC, zeripath approved these changes
Shame about the api.Error endpoint - but if you don't have time to fix those right now - at least we can get a fix in for the ostensible reason for this PR.

These changes now at least don't make the situation worse.

2020-05-27 10:58 UTC, 6543 commented
should we merge 🚀 ?

2020-05-28 04:28 UTC, guillep2k approved these changes

2020-05-28 06:38 UTC, lafriks approved these changes

2020-05-28 06:42 UTC, lafriks requested changes
I don't see where InternalServerError function is used anymore :)

2020-05-28 10:04 UTC, 6543 commented
?

2020-05-28 10:26 UTC, zeripath commented
This PR provides a `modules/context.APIContext.InternalServerError(...)` method override for a method in `modules/context.Context`.

An example of a piece of code affected is in routers/api/v1/misc/markdown.go:79:`ctx.InternalServerError(err)`

Where `ctx` is actually a `modules/context.APIContext` and `modules/context.APIContext` is:

```go
// APIContext is a specific macaron context for API service
type APIContext struct {
	*Context
	Org *APIOrganization
}
```

As there was previously no `InternalServerError` method defined for `APIContext` then the one used for `Context` was used. This PR stops that by providing a method specific for these to `APIContext`.

2020-05-28 14:16 UTC, lafriks approved these changes

2020-05-28 14:16 UTC, lafriks commented
sorry my bad :)

2020-05-28 15:50 UTC, 6543 commented
I would say ready to merge

2020-05-28 16:58 UTC, merged

2020-05-28 16:59 UTC, guillep2k commented
Please send backport. Can you check whether the "Allow maintainers to edit this post" checkbox shows and is checked up before posting? It's an ongoing mistery.... 🕵️

2020-05-28 17:12 UTC, 6543 commented
I agree It's an ongoing mistery!

2020-05-28 17:24 UTC, 6543 commented
have created backport to v1.11 too - old untuched code allowed it easely ;)