Fix alignment for commits on dashboard
go-gitea/gitea pull request #11595
Opened 2020-05-24 05:22 UTC by mrsdizzie

Fix allignment issue between commit SHA and commit message

Old:
<img width="710" alt="Screen Shot 2020-05-24 at 1 01 44 AM" src="https://user-images.githubusercontent.com/1669571/82746358-c7088d80-9d5c-11ea-9a3a-c21b817f076c.png">

New:
<img width="708" alt="Screen Shot 2020-05-24 at 1 08 10 AM" src="https://user-images.githubusercontent.com/1669571/82746361-d4257c80-9d5c-11ea-9326-122bb52d166b.png">

2020-05-24 05:32 UTC, zeripath approved these changes

2020-05-24 07:49 UTC, zeripath commented
Hmm this seems to make the text jump for me here:

![Screenshot from 2020-05-24 08-49-00](https://user-images.githubusercontent.com/1824502/82748611-71070a80-9d9b-11ea-9826-559cbd71202c.png)

2020-05-24 07:49 UTC, zeripath requested changes
doesn't appear to work

2020-05-24 11:51 UTC, mrsdizzie commented
@zeripath hmm weird -- does the dashboard on gitea.com look ok to you? Right now for me everything (which is only mirror synching) looks broken like my first screenshot. This change makes them all look normal for me in every browser.

Do you see them as broken but this change doesn't fix it?

2020-05-24 13:48 UTC, zeripath commented
No the gitea.com dashboard looks broken too. 

Fiddling a little the issue might be that the SHA link isn't display: inline-block

2020-05-24 13:53 UTC, zeripath commented
Sorry or rather that the text.truncate is display: inline-block

2020-05-24 22:11 UTC, CirnoT commented
Does not work here either, it's broken with and without this PR, just in different direction. Changing it to -4px works for me but that's a rather poor hack that most likely depend on font too.

2020-05-24 22:48 UTC, mrsdizzie commented
Weird, must be some combination of font/os that gives different results it looks totally fine in all 3 browsers on MacOs with this PR but I just tried in a windows vm and see the same thing as @zeripath . 

The fact that its a negative margin makes me feel like its making up for something else that needs to be fixed, though unsetting display: inline-block makes it look mostly better, and causes margin top and bottom to just have no effect. WIll need to look into more

2020-05-25 13:19 UTC, silverwind commented
Remove all hacky margins on `img` and `span` and set `<li>` to `display: flex; align-items: center`:

<img width="234" alt="image" src="https://user-images.githubusercontent.com/115237/82815952-89118380-9e9a-11ea-86eb-09629c147884.png">

The flexbox makes the whitespace collapse so you'll need something like `li > * + * {margin-left: .35rem}` to restore it:

<img width="235" alt="image" src="https://user-images.githubusercontent.com/115237/82816237-0c32d980-9e9b-11ea-8c86-dc154a60a8b0.png">

2020-05-25 13:22 UTC, silverwind commented
Also, I think you can add small top/bottom margins to `<li>` so multiple messages are not stuffed together so tightly, e.g. `.125rem` on both sides.

2020-05-26 02:09 UTC, mrsdizzie commented
@silverwind thanks, applied those changes and seems to work better in all places now

2020-05-26 19:17 UTC, zeripath commented
![Screenshot from 2020-05-26 20-17-43](https://user-images.githubusercontent.com/1824502/82941255-fbaf5b80-9f8d-11ea-9079-a66304fbada8.png)

2020-05-26 19:18 UTC, zeripath commented
seems not unfortunately

2020-05-26 23:54 UTC, CirnoT commented
Works for me @zeripath

2020-05-27 00:00 UTC, silverwind commented
Works for me too:

<img width="549" alt="image" src="https://user-images.githubusercontent.com/115237/82961498-d4708280-9fbd-11ea-8626-57b7f76e59fb.png">

2020-05-27 00:00 UTC, silverwind approved these changes

2020-05-27 00:20 UTC, mrsdizzie commented
@zeripath you use Ubuntu right? I set up a vm and think this is an issue with Liberation Mono font which was the font it chose with default settings

It seems to just size much different than others. Removing it from the mono font stack fixes it, but obviously a problem if that is going to be the default font selected for many users. Not really sure what would be a good way of working with that:


![May-26-2020 20-18-49](https://user-images.githubusercontent.com/1669571/82962435-3618f880-9f8e-11ea-803c-c3f2a265aac5.gif)

2020-05-27 00:31 UTC, silverwind commented
If Liberation Mono is causing issues, maybe we want to move it after all other monospace fonts, right before `monospace`. Thought I'm not sure if any better suitable fonts are present by default on Linux systems.

2020-05-27 00:41 UTC, mrsdizzie commented
In this test for Ubuntu it falls back to 'monospace' when removing Liberation Mono which seems to then use DejaVu Sans Mono from the system which looks better imo. Not sure what other distributions have installed other than Liberation Mono but I can't imagine there is only one monospace font installed.

2020-05-27 00:45 UTC, silverwind commented
Adding DejaVu Sans Mono before Liberation Mono sounds like a good idea, if it works better.

2020-05-27 00:53 UTC, mrsdizzie commented
Google suggest there are several other mono space fonts included in various linux distros -- Id vote to remove liberation mono as a specifically named font all together if it somehow has the ability to look different enough to break styling in some situations compared to all other monospace font.

I'm not a desktop Linux user though so not sure what the real experience with others is. Maybe somebody who is could say.

2020-05-27 00:54 UTC, CirnoT reviewed
How about this?

![chrome_2020-05-27_02-54-01](https://user-images.githubusercontent.com/1447794/82964268-5617de80-9fc5-11ea-8261-5e49d1e565c8.png)

2020-05-27 00:54 UTC, CirnoT commented on web_src/less/_dashboard.less
> +            align-items: center;
```suggestion
            align-items: baseline;
```

2020-05-27 00:54 UTC, CirnoT commented on web_src/less/_dashboard.less
> +        }
```suggestion
            img {
                align-self: flex-end;
            }
        }
```

2020-05-27 01:06 UTC, mrsdizzie commented
@CirnoT those changes seem to make it look ok and similar enough with Libertion Mono so seem good to me as long as this works for everybody and doesn't look broken as it does now

2020-05-27 01:27 UTC, silverwind commented
That `baseline` change does shift all the hash and message 1px up for me, I think I prefer the `center` and fix the fonts.

2020-05-27 09:00 UTC, CirnoT commented
Fix the fonts is not a proper solution; you can try manipulate list to look fine to you but in the end you can never be sure what user has installed and what browser will use. Aligning to baseline seems like the only option where you can be sure that different fonts will be aligned to each other visually.

2020-05-27 09:03 UTC, CirnoT approved these changes

2020-05-27 09:05 UTC, silverwind commented
I'd say the behaviour in https://github.com/go-gitea/gitea/pull/11595#issuecomment-634224764 is a font/browser bug that should not require is to make specific workarounds for as these may bite us in the long run (after the font/browser is fixed).

2020-05-27 09:06 UTC, CirnoT commented
Yes on Libertion Mono the text is around 1px too high compared to avatar, but that's because the font's baseline is off. My proposed changes do not workaround the font issue, they align items to their baseline. This looks off on Libertion Mono for same reason the original solution did, but at least it's less visible now. Other fonts look fine to me and text is aligned perfectly to avatar.

2020-05-27 09:09 UTC, CirnoT commented
In the end, baseline is the only thing that is guaranteed to visually align two different font types and I consider it the proper solution long-term.

2020-05-27 09:27 UTC, silverwind commented
The alignment looks ok in those screenshots. What I don't quite get is how `align-self: flex-end;` on the `<img>` fixes the image. Care to explain?

2020-05-27 09:51 UTC, CirnoT commented
Good question, I have no idea why it actually visually centers image.

2020-05-27 09:53 UTC, CirnoT reviewed
Try with this and

```css
        .push.news .content ul {
            line-height: 18px;
```

2020-05-27 09:53 UTC, CirnoT commented on web_src/less/_dashboard.less
> +                align-self: flex-end;
```suggestion
                align-self: flex-start;
```

2020-05-27 10:12 UTC, CirnoT commented
There does indeed seem to be some misalignment when zoomed out
![chrome_2020-05-27_12-09-37](https://user-images.githubusercontent.com/1447794/83006870-255e9600-a013-11ea-99bc-5b0aa26de090.png)

The new proposed changes (flex-start and line-height) seem to eliminate it at the cost of putting the image slightly down when zoomed in; same as on GitHub

2020-05-27 10:14 UTC, zeripath commented
it's possibly font x-height differences between the monospace font and the sans-serif font used for the message. 

The solution might simply be to stick the sha in side a rounded-box like we do elsewhere then the jarring font change would be less visible.

2020-05-27 10:21 UTC, CirnoT commented
The new changes seem to work rather well for me

Default font on Windows 10:
![chrome_2020-05-27_12-16-53](https://user-images.githubusercontent.com/1447794/83007638-407dd580-a014-11ea-9107-bcde7784c2af.png)
![chrome_2020-05-27_12-17-14](https://user-images.githubusercontent.com/1447794/83007641-41166c00-a014-11ea-9439-172a1e298b07.png)

Liberation Mono:
![chrome_2020-05-27_12-17-43](https://user-images.githubusercontent.com/1447794/83007739-63a88500-a014-11ea-9529-1e2017b7f23a.png)
![chrome_2020-05-27_12-17-32](https://user-images.githubusercontent.com/1447794/83007737-630fee80-a014-11ea-91f7-2982cf5a185d.png)

---
For reference, GitHub:
![chrome_2020-05-27_12-18-26](https://user-images.githubusercontent.com/1447794/83007816-7e7af980-a014-11ea-92a7-8048ce561a30.png)
![chrome_2020-05-27_12-18-41](https://user-images.githubusercontent.com/1447794/83007819-7f139000-a014-11ea-8c86-31f94111005f.png)

2020-05-27 13:39 UTC, mrsdizzie commented
@CirnoT applied those changes, looks ok to me on various systems/fonts

@zeripath I think one of my least favorite parts of Gitea UI is the SHA1 inside of a rounded box : (  I'd rather see those all eventually get replaced rather than add another one here. These changes seem to make it work and look as it is intended to look now

2020-05-27 14:00 UTC, CirnoT approved these changes

2020-05-27 20:30 UTC, zeripath approved these changes

2020-05-27 20:31 UTC, merged

2020-05-28 12:56 UTC, mrsdizzie commented
I think this should be backported to 1.12 -- I'm not sure exactly where but the bug this fixes seems like it was introduced somewhere in 1.12 (probably one of the larger timeline UI changes). I don't see it on 1.11

2020-05-29 13:19 UTC, zeripath commented
Please send backport