translate: Change translate for admin.config.enable_captcha
go-gitea/gitea pull request #11657
Opened 2020-05-28 15:01 UTC by a1012112796

add 'register' to make it more accurate

sadly, it has been misunderstood by Chinese translators, It was translated as "enable login CAPTCHA".😂
![image](https://user-images.githubusercontent.com/25342410/83158212-16710400-a137-11ea-8dc5-ab35e631d08b.png)

2020-05-28 15:08 UTC, a1012112796 commented
![image](https://user-images.githubusercontent.com/25342410/83158864-e9712100-a137-11ea-9d72-6b77251b1fb1.png)

![image](https://user-images.githubusercontent.com/25342410/83158955-06a5ef80-a138-11ea-8807-68989681c1c5.png)

What happend?🤔 @lunny

2020-05-28 17:55 UTC, CirnoT commented
You can always propose change on Crowdin if some translation got it wrong.

2020-05-29 00:05 UTC, a1012112796 commented
> You can always propose change on Crowdin if some translation got it wrong.

I'm sorry, I haven't check Crowdin before, but after check it , I found an amazing thing , that the translation in cowdin is “启用验证码”，but the translation pushed by crowdin bot is  "启用登录验证码" which is different with cowdin , I wander .... 
This pr is am to change english version form "" Enable CAPTCHA" to "Enable register CAPTCHA" to make it more exact. The english version can't change in crowdin. Thanks.

2020-05-29 00:14 UTC, CirnoT requested changes

2020-05-29 00:14 UTC, CirnoT commented on options/locale/locale_en-US.ini
> +enable_captcha = Enable register CAPTCHA
```suggestion
enable_captcha = Enable registration CAPTCHA
```

2020-05-29 00:18 UTC, a1012112796 commented on options/locale/locale_en-US.ini
> +enable_captcha = Enable register CAPTCHA
Thanks

2020-05-29 00:32 UTC, CirnoT approved these changes
I think it's fine

2020-05-29 01:26 UTC, 6543 approved these changes

2020-05-29 07:51 UTC, lafriks approved these changes

2020-05-29 08:36 UTC, merged