ui: change commentTag style
go-gitea/gitea pull request #11668
Opened 2020-05-29 03:38 UTC by a1012112796

* Add comment tag in first comment (issue content)
* Show CommentTagPoster in other way

view:
![image](https://user-images.githubusercontent.com/25342410/83218536-ac8d4480-a1a0-11ea-97f2-34f5347fe29a.png)

2020-05-29 07:53 UTC, lafriks commented on routers/repo/issue.go
> +	if err != nil {
```suggestion
	if issue.ShowTag, err = commentTag(repo, issue.Poster, issue); err ! = nil {
```

2020-05-30 15:56 UTC, lunny requested changes

2020-05-30 15:56 UTC, lunny commented on models/issue_comment.go
> -	CommentTagPoster
No, you cannot delete this line.

2020-06-14 21:36 UTC, CirnoT commented
Related https://github.com/go-gitea/gitea/issues/11592

2020-06-18 10:01 UTC, lunny commented on models/issue_comment.go
> +	CommentTagPoster
I would like put the new enmuerate value to the last.

2020-08-17 11:56 UTC, a1012112796 commented
ping :)

2020-08-17 12:14 UTC, lunny approved these changes

2020-09-10 17:34 UTC, techknowlogick approved these changes

2020-09-10 18:09 UTC, merged