bug: fix comment update permision check
go-gitea/gitea pull request #11671
Opened 2020-05-29 07:25 UTC by a1012112796

Now the ui only allow poster to update or delet comment, which is not reasonable and different with handle logic, this pr change it to allow poster of comment do it.

ref code:
https://github.com/go-gitea/gitea/blob/e8955173a9be1acaa9a3755c37b6059422acda20/routers/repo/issue.go#L1636

https://github.com/go-gitea/gitea/blob/e8955173a9be1acaa9a3755c37b6059422acda20/routers/repo/issue.go#L1681

fix #11663

2020-05-29 07:30 UTC, lafriks approved these changes

2020-05-29 07:39 UTC, lafriks requested changes
I think it should be better to add function to context.go:
```go
// IsUser returns true if current user is specified one
func (ctx *Context) IsUser(id int64) bool {
	return ctx.IsSigned && (ctx.User.ID == id)
}
```

2020-05-29 07:39 UTC, lafriks commented on templates/repo/diff/comments.tmpl
> +			{{template "repo/issue/view_content/context_menu" Dict "ctx" $.root "item" . "delete" true "diff" true "IsCommentPoster" .IsCommentPoster}}
```suggestion
			{{template "repo/issue/view_content/context_menu" Dict "ctx" $.root "item" . "delete" true "diff" true "IsCommentPoster" ($.root.IsUser .PosterID)}}
```

2020-05-29 14:07 UTC, a1012112796 commented
@lafriks I think this style is simpler. Do you think so? Thanks.

2020-05-29 15:49 UTC, lafriks approved these changes

2020-05-29 15:52 UTC, lafriks commented
What needs to be verified is if `SignedUserID` does not equals to ghost/deleted or imported user comment poster id

2020-05-29 18:42 UTC, zeripath commented on templates/repo/diff/comments.tmpl
> +			{{template "repo/issue/view_content/context_menu" Dict "ctx" $.root "item" . "delete" true "diff" true "IsCommentPoster" (eq $.root.SignedUserID .PosterID)}}
```suggestion
			{{template "repo/issue/view_content/context_menu" Dict "ctx" $.root "item" . "delete" true "diff" true "IsCommentPoster" (and $.root.IsSigned (eq $.root.SignedUserID .PosterID))}}
```

2020-05-29 18:42 UTC, zeripath commented on templates/repo/issue/view_content/comments.tmpl
> +							{{template "repo/issue/view_content/context_menu" Dict "ctx" $ "item" . "delete" true "diff" false "IsCommentPoster" (eq $.SignedUserID .PosterID)}}
```suggestion
							{{template "repo/issue/view_content/context_menu" Dict "ctx" $ "item" . "delete" true "diff" false "IsCommentPoster" (and $.root.IsSigned (eq $.SignedUserID .PosterID))}}
```

2020-06-04 09:45 UTC, a1012112796 commented
Please review, Thanks :)

2020-06-04 14:24 UTC, 6543 commented
didnt this worked before too?!?

2020-06-04 16:37 UTC, 6543 approved these changes

2020-06-04 20:00 UTC, lafriks commented
make lg-tm work

2020-06-05 10:08 UTC, lafriks commented
make it work

2020-06-05 10:10 UTC, merged

2020-06-05 10:10 UTC, lafriks commented
Please send backport