Add changelog for 1.11.6
go-gitea/gitea pull request #11695
Opened 2020-05-30 17:35 UTC by guillep2k

As title

2020-05-30 17:40 UTC, techknowlogick commented on CHANGELOG.md
> +* ENHANCEMENT
```suggestion
```

2020-05-30 17:40 UTC, techknowlogick commented on CHANGELOG.md
> +* BUILD
```suggestion
```

2020-05-30 18:46 UTC, jolheiser approved these changes

2020-05-30 19:18 UTC, lafriks requested changes

2020-05-30 19:18 UTC, lafriks commented on CHANGELOG.md
> +  * Fix missing authorization check on pull for public repos of private/limited org (#11656) (#11683)
This should be security

2020-05-30 19:18 UTC, lafriks commented on CHANGELOG.md
> +  * Use session for retrieving org  teams (#11438) (#11439)
This also should be security

2020-05-30 20:21 UTC, lafriks approved these changes

2020-05-30 20:21 UTC, merged

2020-05-30 23:23 UTC, 6543 commented
Need Frontport to master and v1.12 branch

2020-05-31 00:07 UTC, guillep2k commented
So, there's no "front-port" label. 😂

2020-05-31 03:21 UTC, lunny commented
@guillep2k Now we have https://github.com/go-gitea/gitea/labels?q=frontport .

2020-06-18 16:25 UTC, 6543 commented
hihi frontport 🎉