Docker image fixes
go-gitea/gitea pull request #117
Opened 2016-11-08 08:42 UTC by willemvd

Docker build was broken due to different naming of the artifact from Go, paths changed and glide has been removed.
This should fix these issues (haven't got time to properly test it all)

Signed-off-by: Willem van Dreumel (willem@opencirclesolutions.nl)

2016-11-08 09:33 UTC, bkcsoft requested changes

2016-11-08 09:33 UTC, bkcsoft commented on docker/s6/gogs/setup
>  chmod 0755 /data /data/gogs ~git/
shouldn't these two lines be changed as well?

2016-11-08 09:33 UTC, bkcsoft commented on docker/s6/gogs/setup
>  chmod 0755 /data /data/gogs ~git/
And you'd have to update the Dockerfile as well then.

2016-11-08 09:50 UTC, willemvd commented on docker/s6/gogs/setup
>  chmod 0755 /data /data/gogs ~git/
Why would this need a change?

2016-11-08 13:47 UTC, strk commented on docker/s6/gogs/setup
>  chmod 0755 /data /data/gogs ~git/
to be named "gitea" instead of "gogs" ?

2016-11-08 13:47 UTC, strk commented on docker/build.sh
>  rm -r $GOPATH /app/gogs/vendor
Should it be /app/gitea/vendor ?

2016-11-08 13:51 UTC, xinity commented
i think we should move out of the Dockerfile the build process
as @tboerger will build binaries, we'll just have to add them in the shipped IMAGE.
PR incoming in my case :)

2016-11-08 15:07 UTC, LefsFlarey commented
@xinty Actually, the whole point of a Dockerfile is to allow the user to build the binary him/herself. We should not be putting binaries in there if we can build it ourselves.

2016-11-08 17:27 UTC, metalmatze commented
Not sure if I understand @LefsFlarey correctly. But what will happen is that everyone can simply run `make build`on their machine and create a binary. Our CI Pipeline will then use the binary created by the same command and simply copy it into the docker image. No need to have Go inside the container. Just a binary.
Right @tboerger ?

2016-11-08 18:08 UTC, xinity commented
Agree @metalmaze

2016-11-09 05:52 UTC, tboerger commented
It will be automated, the makefile tasks are already there, just need to add drone as ci

2016-11-18 16:09 UTC, willemvd commented
Changed the whole docker image to be able to run it as unprivileged user (needed for some docker environments like OpenShift v3 which do not allow to run as root) and merged the current master into the pull request

2016-11-24 10:05 UTC, tboerger commented
I'm really not a fan of the current approach. I really dislike the switch away from Alpine.

2016-11-25 22:29 UTC, leitzler requested changes

2016-11-25 22:29 UTC, leitzler commented on Dockerfile
> +FROM willemvd/ubuntu-unprivileged-git-ssh:latest
This opens up a huge security hole and should not, in any way, be accepted by the maintainers of Gitea.

2016-11-27 22:46 UTC, stevenroose commented
It should definitively be possible to build Gitea on an alpine container without too much hassle.

2016-11-28 00:25 UTC, LefsFlarey commented on Dockerfile
> +FROM willemvd/ubuntu-unprivileged-git-ssh:latest
I agree, what's wrong with alpine?

2016-11-28 07:40 UTC, tboerger commented
So we agree to build only on official images

2016-11-28 13:20 UTC, tboerger commented
Should we take https://github.com/go-gitea/gitea/pull/288 in favor of this?

2016-11-29 06:23 UTC, tboerger commented
Thanks for the work, we have merged #288 now to properly build docker images.

2016-11-29 06:23 UTC, closed without merging