Fix GO source vendoring
go-gitea/gitea pull request #12010
Opened 2020-06-22 04:58 UTC by ElXreno

This commit fixes error like this:
```
CC= GOOS= GOARCH= go generate -mod=vendor -tags 'bindata pam sqlite sqlite_unlock_notify' 
go: inconsistent vendoring in /builddir/build/BUILD/gitea-1.12.1:
	src.techknowlogick.com/xgo@v0.0.0-20200602060627-a09175ea9056: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt

run 'go mod vendor' to sync, or use -mod=mod or -mod=readonly to ignore the vendor directory
go: inconsistent vendoring in /builddir/build/BUILD/gitea-1.12.1:
	src.techknowlogick.com/xgo@v0.0.0-20200602060627-a09175ea9056: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt

run 'go mod vendor' to sync, or use -mod=mod or -mod=readonly to ignore the vendor directory
make: *** [Makefile:518: generate] Error 1
```

Maybe somebody's got a better fix? I'm not sure if my decision is right because the vendor is already in the repository.

2020-06-22 14:03 UTC, techknowlogick requested changes
The `release` targets in the makefile are useful shortcuts for the Gitea project itself for releasing Gitea via Drone. As well go modules are disabled during release steps. I am hesitant about this change as if you would like to build Gitea then the make build step is what you need to use.

2020-06-22 14:18 UTC, silverwind commented
I think `make vendor` should fix inconsistent vendoring. Did someone forget to run it?

https://github.com/go-gitea/gitea/blob/121103fecf0fb72ccd8bf1fe2b63b3d20d1d4426/Makefile#L332-L343

2020-06-22 15:17 UTC, ElXreno commented
@techknowlogick this pull request fixes the generation of an archive with all dependencies for offline build. It is generated, and is called as gitea-src-$VERSION.tar.gz, so I think it's required.

2020-06-22 15:18 UTC, ElXreno commented
@silverwind Thank you for the find! I didn't even notice it once.

2020-06-22 15:25 UTC, silverwind commented
`test-vendor` already runs as part of every CI job ([example](https://drone.gitea.io/go-gitea/gitea/27401/1/4)) and the build would fail if there were inconsistencies. So I don't think adding this to the release task is a good idea. Question is how did your vendoring get inconsistent, assuming you're building of one of our tested branches?

2020-06-22 16:06 UTC, ElXreno commented
@silverwind To be honest, I don't know why it breaks. Everything was compiled without the Internet to version 1.11.6 inclusive. The next step was to manually re-pack the archive, pre-making a `go mod vendor`.
And sorry for my bad English, I may have misunderstood your question.

2020-06-22 16:11 UTC, silverwind commented
I think the issue is that the release tasks do `go get -u src.techknowlogick.com/xgo` which will add xgo to the module dependencies. One way to workaround this would be to `cd` outside the project while installing global commands. I wonder why this doesn't fail for our release tasks.

2020-06-22 16:34 UTC, techknowlogick commented
`go get -u src.techknowlogick.com/xgo` shouldn't be run when doing the  release targets during drone because the docker container already has the xgo binary in it.

2020-06-22 20:03 UTC, silverwind commented
This issue is essentially https://github.com/golang/go/issues/30515.

We could potentially `GO111MODULE=off go get -u src.techknowlogick.com/xgo` to avoid having go touch the module files.

2020-06-23 15:39 UTC, silverwind commented
Alternative PR: https://github.com/go-gitea/gitea/pull/12030

2020-06-26 19:47 UTC, closed without merging