Trim to 255 runes instead of bytes
go-gitea/gitea pull request #12150
Opened 2020-07-05 16:46 UTC by juergenhoetzel

Prevents invalid UTF-8 encoding for Description and Website. Refs #7905

Prevents Internal Server errors when repo is created with description > 255 bytes, for example 160*ü (320 bytes):

`
üüüüüüüüüüüüüüüüüüüüüüüüüüüüüüüüüüüüüüüüüüüüüüüüüüüüüüüüüüüüüüüüüüüüüüüüüüüüüüüüüüüüüüüüüüüüüüüüüüüüüüüüüüüüüüüüüüüüüüüüüüüüüüüüüüüüüüüüüüüüüüüüüüüüüüüüüüüüüüüü`

2020-07-05 16:59 UTC, lafriks requested changes
import is missing

2020-07-05 17:18 UTC, juergenhoetzel commented
> import is missing

Ups. Forgot to stage the import. 

I just amended the commit

2020-07-05 19:17 UTC, zeripath commented on models/repo.go
> +		repo.Description = string([]rune(repo.Description))[:255]
```suggestion
		repo.Description = string([]rune(repo.Description)[:255])
```

2020-07-05 19:17 UTC, zeripath commented on models/repo.go
> +		repo.Website = string([]rune(repo.Website))[:255]
```suggestion
		repo.Website = string([]rune(repo.Website)[:255])
```

2020-07-05 19:57 UTC, zeripath approved these changes

2020-07-06 09:53 UTC, lunny commented
So we also need to adjust the database column size.

2020-07-06 11:43 UTC, juergenhoetzel commented
> So we also need to adjust the database column size.

255 is still below the current limits:

```
	Description         string             `xorm:"TEXT"`
	Website             string             `xorm:"VARCHAR(2048)"`
```

2020-07-07 07:16 UTC, lunny commented
I don't know why we need to trim the content to 255 runes since it could hold 65535 bytes?

2020-07-07 14:57 UTC, juergenhoetzel commented
> I don't know why we need to trim the content to 255 runes since it could hold 65535 bytes?

I also don't knew. I just  wanted to change as little as possible to avoid breaking other parts.

Actually according to the DB-schema it's 65536 **Codepoints/Runes** not **bytes.**

2020-07-07 18:01 UTC, lafriks approved these changes

2020-07-07 20:27 UTC, lafriks commented
:rocket:

2020-07-07 21:35 UTC, merged

2020-07-07 21:36 UTC, lafriks commented
Please send backport