Send notifications to partecipants in issue comments
go-gitea/gitea pull request #1217
Opened 2017-03-11 08:51 UTC by strk

Closes #1216

NOTE: I didn't test this with GUI notifications so might need a review
from @andreynering to deal with that -- this is just a straight port
from the Gogs commit

2017-03-11 08:55 UTC, lunny requested changes

2017-03-11 08:55 UTC, lunny commented on models/issue_mail.go
> +	for i := range participants {
ignore self on watchers too?

2017-03-11 08:59 UTC, strk commented
It's done one line below:

```
  if participants[i].ID == doer.ID {
    continue
```

2017-03-11 09:02 UTC, lunny commented
I mean `watchers` not `participants`

2017-03-11 09:49 UTC, strk commented
Done also for `watchers`:
```
        for i := range watchers {
                if watchers[i].UserID == doer.ID {
                        continue
                }
```

2017-03-11 10:07 UTC, lunny commented
Where is the commit?

2017-03-11 10:22 UTC, strk commented
It was already in the file, so not changed by the commit.
The code can be seen in the file as modified by the commit:
https://github.com/strk/gitea/blob/809ecfddbb8fd69b67144fcf77abb512ec12e5e8/models/issue_mail.go#L41-L44

2017-03-11 15:35 UTC, strk commented on models/issue_mail.go
> +	for i := range participants {
this is already done in the file, a few lines above (see the full file)

2017-03-11 19:15 UTC, puffybsd commented
Did some testing on 'issue notifications'.  For the most part, it worked, although I wasn't able to reproduce an issue on master, some emails were delayed and issue counts for the issue creator were out of sync (but eventually synchronized).

Using two accounts & two email accounts (one gmail, one yahoo, sparkpost relay), creator of issue is a participant, repo owner is a participant. confirmed that emails are sent to the other participant when a change is made (creator opens an issue- email sent to repo owner, not to creator; repo owner comments, email sent to creator, not to repo owner).  Let me know if there's something else you'd like tested.

2017-03-11 21:16 UTC, strk commented
@puffybsd I'd love you to try the same on try.gitea.io to spot the difference, but I'm not sure email notification there work at the moment (due to #1223)

2017-03-12 15:13 UTC, lunny commented
LGTM, I just made some simple tests, it works.

2017-03-12 15:14 UTC, lunny approved these changes

2017-03-12 15:19 UTC, lunny commented
But maybe you don't consider one situation. Issue creators seem will not receive emails?

2017-03-12 15:23 UTC, strk commented
Had you tried that @lunny ? @puffybsd had you (making sure creator was not "Watching" the repo)

2017-03-12 15:37 UTC, lunny commented
line 86 should has a bug. the poster maybe the comment poster not the issue poster. So poster should be a param to `MailParticipants`.
```Go
func (issue *Issue) MailParticipants() (err error) {
```

2017-03-12 17:14 UTC, strk commented
@lunny actually I don't understand the issue. Are you saying that the issue poster should *not* receive an email notification when someone comments on the issue ?

2017-03-12 17:17 UTC, ethantkoenig requested changes

2017-03-12 17:17 UTC, ethantkoenig commented on models/issue.go
> +func GetParticipantsByIssueID(issueID int64) ([]*User, error) {
Could we add tests for this new function?

2017-03-12 17:45 UTC, strk commented on models/issue.go
> +func GetParticipantsByIssueID(issueID int64) ([]*User, error) {
Will look into it as time permits (possibly next week)

2017-03-12 17:46 UTC, strk commented
@lunny @Unkwon actually confirmed the bug and reports it as fixed by https://github.com/gogits/gogs/commit/5f058c3f071b5a754bdd5b556b49d678bf1477f1

Great reviews, thanks everyone !

2017-03-13 14:30 UTC, andreynering commented
Trusted LGTM

2017-03-13 15:25 UTC, lunny commented
@strk I don't think that will fix the problem entirely, I will test this tomorrow again.

2017-03-13 17:51 UTC, strk commented
192ca213f08b4d613c45bce22b78d7497f342ff5 stubs an initial test, and fails revealing still a bug !
(the one you're talking about @lunny ?)

I don't know what @Unknwon idea was for that function (GetParticipantsByIssueID), but  to me it does make sense for the original poster to be among the partecipants...

2017-03-15 06:43 UTC, strk commented
So basically what's the failing test telling us is that the current `GetParticipantsByIssueID` function (in this PR) is returning all the users who commented and those who applied labels, but not the issue author. I don't know what @Unknwon thinks about this but I would not include labels changers while I would include the issue author. What do other think about it ? In other words, what consistitutes "partecipation" in an issue ?

2017-03-15 14:39 UTC, lunny commented on models/issue.go
> +	userIDs := make([]int64, 0, 5)
nothing.

2017-03-16 01:34 UTC, lunny commented
let L-G-T-M work

2017-03-16 01:34 UTC, merged