Rename /forget_password url to /forgot_password
go-gitea/gitea pull request #1219
Opened 2017-03-11 09:47 UTC by strk

2017-03-11 09:55 UTC, lunny requested changes
just remove the wrong line is ok

2017-03-11 09:55 UTC, lunny commented on options/locale/locale_en-US.ini
> +forgot_password = Forgot password?
duplicated.

2017-03-11 09:56 UTC, strk commented on options/locale/locale_en-US.ini
> +forgot_password = Forgot password?
Fixed (I don't think this is `kind/docs`, btw)

2017-03-11 09:58 UTC, strk commented
Hold on a second, there are duplications in each and every translation :/
I'm not sure what happened. Maybe someone added a question mark after I initially made the PR, and the rebase didn't recognize it. Fixing it

2017-03-11 09:58 UTC, lunny commented
@strk every file has a duplicated line.

2017-03-11 10:15 UTC, strk commented
ok, figured. The `forgot_password` key is currently being used as the title for the `Forgot Password` page,
while the `forget_password` key is used for the link text.

So the new commit (replacing the others) changes `forgot_password` to `forgot_password_title` and then changes `forget_password` to `forgot_password`. Should be good now.

2017-03-11 22:03 UTC, bkcsoft commented
This needs a big disclaimer in the changelog 😛

2017-03-11 22:49 UTC, strk commented
@bkcsoft you seemed less concerned in https://github.com/go-gitea/gitea/pull/862#issuecomment-279224102 ? Or is this specifically for the translation keys ?

2017-03-12 00:00 UTC, bkcsoft commented
@strk Well, people might depend on the link, so we need a changelog entry, as for the API it doesn't care 🙂

2017-03-12 10:30 UTC, strk commented
Did anyone setup that changelog/ support mechanism ?
I'd be glad to provide a changelog within this PR if that's the case
(and if so: where is it documented?)

2017-03-12 15:28 UTC, lunny commented
Why we need two similar strings?

2017-03-12 19:31 UTC, strk commented
One is the link text (usually ends with a question mark: "Forgot password?")
the other is the title of the HTML page where you click the confirmation
button (thus the "_title" suffix in the new key).

2017-03-13 03:18 UTC, lunny approved these changes

2017-03-13 03:19 UTC, lunny commented
LGTM except @bkcsoft 's opinion

2017-03-13 07:51 UTC, strk commented
@bkcsoft I'm ok with the changelog entry, should I add it to the current CHANGELOG, drafting the new line (and fixing conflicts as we go) ? Or we could use a `[changelog:compatibility]` tag in commit logs to extract later ? Or what else do you want me to do for this to be accepted ?

2017-03-13 16:38 UTC, bkcsoft commented
Put it in the Changelog under "Unreleased" (make a section at the top) and someone will take take of it 😉

2017-03-13 16:40 UTC, 0xbaadf00d commented
LGTM

2017-03-13 17:17 UTC, bkcsoft requested changes

2017-03-13 17:17 UTC, bkcsoft commented on cmd/web.go
> +		m.Get("/forgot_password", user.ForgotPasswd)
Just put a changelog somewhere (just so it can't be merged before that 😂  )

2017-03-13 17:20 UTC, strk commented on cmd/web.go
> +		m.Get("/forgot_password", user.ForgotPasswd)
Are you @go-gitea/maintainers ok if we start dropping changelogs in files under a `pending-changelogs/` directory, to be checked and cleaned up before final release ?

2017-03-13 18:37 UTC, strk commented
@bkcsoft section added, and squash rebased against master

2017-03-14 21:53 UTC, bkcsoft approved these changes

2017-03-14 21:54 UTC, merged

2017-03-20 01:15 UTC, bkcsoft commented on cmd/web.go
> +		m.Get("/forgot_password", user.ForgotPasswd)
@strk `changelog/unreleased` as per #1298 😉