Clarify documentation of SKIP_VERIFY
go-gitea/gitea pull request #12203
Opened 2020-07-09 22:05 UTC by cipherboy

The documentation clearly documents the empty value as the default,
however at least one user reported this as being unclear. Mark values
explicitly so it is clear what values it can take. This clarifies that
an empty value in fact leaves certificate verification enabled, whereas
it has to be explicitly set to true to disable certificate verification.

Resolves: #12117

`Signed-off-by: Alexander Scheel <alexander.m.scheel@gmail.com>`

2020-07-09 22:12 UTC, silverwind commented
Please also sync to [here](https://github.com/go-gitea/gitea/blob/6a62884782b29653bcd4462188e263018e5e21e8/custom/conf/app.example.ini#L646).

2020-07-09 22:22 UTC, cipherboy commented
ACK, done. Thanks @silverwind.

2020-07-10 14:31 UTC, mrsdizzie requested changes
I think we should only use true/false for boolean examples and not mention empty. While empty will always evaluate to false, having it as a 3rd option seems to be what caused the original confusion this is meant to fix. Showing false as the default makes that more clear. Also slight change to comment just so it is the same between both files

2020-07-10 14:31 UTC, mrsdizzie commented on docs/content/doc/advanced/config-cheat-sheet.en-us.md
> +- `SKIP_VERIFY`: **\<empty\>**: Whether or not to skip verification of certificates; empty or `false` to enable verification; `true` to disable verification.
```suggestion
- `SKIP_VERIFY`: **false**: Whether or not to skip verification of certificates; `true` to disable verification.
```

2020-07-10 14:31 UTC, mrsdizzie commented on custom/conf/app.example.ini
>  SKIP_VERIFY =
```suggestion
SKIP_VERIFY = false
```

2020-07-10 14:31 UTC, mrsdizzie commented on custom/conf/app.example.ini
> +; !!Unsafe!! Whether or not to skip verification of certificates; empty or `false` to enable verification; `true` to disable verification. Consider adding the target certificate into the system trust
```suggestion
; Whether or not to skip verification of certificates; `true` to disable verification. This option is unsafe. Consider adding the certificate to the system trust store instead.
```

2020-07-20 19:12 UTC, cipherboy commented
Sorry, was out of internet range. Updated!

2020-07-20 19:45 UTC, mrsdizzie approved these changes

2020-07-21 17:57 UTC, silverwind approved these changes

2020-07-21 23:50 UTC, merged