[API] Extend get milestone list by name filter
go-gitea/gitea pull request #12336
Opened 2020-07-27 12:47 UTC by 6543

it include also a refactor (merge GetMilestones and GetmilestonesByRepoID)

2020-07-27 13:09 UTC, lunny requested changes
Otherwise LGTM

2020-07-27 13:09 UTC, lunny commented on models/issue_milestone.go
> +	if err := sess.Begin(); err != nil {
We don't need a transaction here.

2020-07-27 13:37 UTC, 6543 commented
@lunny done

2020-07-27 13:38 UTC, 6543 commented
need labels :)

2020-07-28 03:12 UTC, lunny approved these changes

2020-07-28 11:28 UTC, zeripath approved these changes
I note you've changed the default to do a sort by deadline then by id - we're probably going to have to update our API to allow this kind of multiple sorting at some point.

2020-07-28 11:30 UTC, merged