[WIP] Feature/docker updates
go-gitea/gitea pull request #125
Opened 2016-11-09 11:58 UTC by xinity

WIP docker cleanup.

has been done so far:

- [x] remove build from Dockerfile
- [x] cleanup start.sh (only crond exists)
- [x] readme.md updates

**note**: doesn't build for now but very soon :)

2016-11-09 12:58 UTC, bkcsoft requested changes

2016-11-09 12:58 UTC, bkcsoft commented on README.md
> +4. If you think there are vulnerabilities in the project, please talk privately to **security@gitea.io**. Thanks!
change the list numbers ;)

2016-11-09 12:58 UTC, bkcsoft commented on README.md
> +6. If your team/company is using Gogs and would like to put your logo on [our website](https://gitea.io), contact us by any means.
`Gogs` :trollface:

2016-11-09 12:58 UTC, bkcsoft commented on README.md
> +**Note: As Gitea is a [Gogs](https://github.com/gogits/gogs) fork, tutorials and documentation related to gogs applies to Gitea too**
`Gogs` should be Capitalized :)

2016-11-09 12:58 UTC, bkcsoft commented on README.md
> -- [Install from binary](https://gogs.io/docs/installation/install_from_binary.html)
Why remove binary, source and package?

2016-11-09 12:58 UTC, bkcsoft commented on docker/README.md
> +$ docker volume create --name gitea-data
There's techincally no need for this, since `docker run` will auto-create it if it doesn't exist

2016-11-09 12:58 UTC, bkcsoft commented on docker/README.md
> -- **SOCAT_LINK**:
Has `socat`-support been removed?

2016-11-09 12:58 UTC, bkcsoft commented on docker/README.md
> +Steps to upgrade gitea with Docker:
`Gitea` capitalized

2016-11-28 13:20 UTC, tboerger commented
Should we take https://github.com/go-gitea/gitea/pull/288 in favor of this?

2016-11-29 06:23 UTC, tboerger commented
Thanks for the work, we have merged #288 now to properly build docker images.

2016-11-29 06:23 UTC, closed without merging