Add notice that LFS mirroring is not supported
go-gitea/gitea pull request #1251
Opened 2017-03-14 16:48 UTC by fabian-z

As discussed in #849:

Mirroring LFS objects is no easy feat, so this PR adds a notice to the migration UI which tells the user that Gitea does not support it currently, hinting at ```git lfs``` functionality.

2017-03-14 20:28 UTC, geek1011 commented
LGTM

2017-03-16 00:24 UTC, andreynering commented on options/locale/locale_de-DE.ini
> +migrate.lfs_mirror_unsupported = Migrieren von LFS Objekten wird nicht unterstützt - verwenden Sie stattdessen 'git lfs fetch --all' und 'git lfs push --all'.
Strings for langs other than English should not be added directly, but via [Crowdin](https://crowdin.com/project/gitea)

2017-03-16 01:30 UTC, lunny requested changes

2017-03-16 01:30 UTC, lunny commented on options/locale/locale_de-DE.ini
> +migrate.lfs_mirror_unsupported = Migrieren von LFS Objekten wird nicht unterstützt - verwenden Sie stattdessen 'git lfs fetch --all' und 'git lfs push --all'.
^

2017-03-16 10:19 UTC, fabian-z commented
Dropped German translation as requested

2017-03-16 11:17 UTC, lunny approved these changes

2017-03-16 11:18 UTC, lunny commented
LGTM

2017-03-16 11:33 UTC, merged