Hide 'New Project board' button for users that are not signed in
go-gitea/gitea pull request #12547
Opened 2020-08-20 17:28 UTC by wULLSnpAXbWZGYDYyhWTKKspEQoaYxXyhoisqHf

As communicated in `discord/develop`, here's this little PR.
I believe there is no reason to show the 'New Project board' button for users that are not signed in.
**Before:**
![before](https://user-images.githubusercontent.com/61180606/90804795-007c7500-e31b-11ea-9f86-487ad66cfa49.png)
**After:**
![after](https://user-images.githubusercontent.com/61180606/90804808-04a89280-e31b-11ea-8188-80e643584f41.png)

2020-08-20 21:21 UTC, lafriks requested changes

2020-08-20 21:21 UTC, lafriks commented on templates/repo/projects/view.tmpl
> +					{{ if $.IsSigned }}
It would be better to add this condition to previous if:
```go
{{if and $.IsSigned .PageIsProjects }}
```

2020-08-20 21:58 UTC, 6543 approved these changes

2020-08-20 22:00 UTC, zeripath reviewed
This is not the correct test - we should only show the button if the user can create project boards

2020-08-20 22:37 UTC, wULLSnpAXbWZGYDYyhWTKKspEQoaYxXyhoisqHf commented
> This is not the correct test - we should only show the button if the user can create project boards

This should now be addressed by the latest changes.
Button is not shown for unauthorized users nor if the repo is archived.

2020-08-21 00:02 UTC, wULLSnpAXbWZGYDYyhWTKKspEQoaYxXyhoisqHf commented
![projectboardmenu](https://user-images.githubusercontent.com/61180606/90837347-0ccff480-e352-11ea-9a59-355e32baad7a.png)
Only show this dropdown menu to authorized users (same as the button).
as per f60df0d

2020-08-21 06:05 UTC, lafriks approved these changes

2020-08-22 06:58 UTC, techknowlogick approved these changes

2020-08-22 06:59 UTC, merged