rewrite pre-commit, post-commit and options hooks (fixes #1250)
go-gitea/gitea pull request #1257
Opened 2017-03-14 23:14 UTC by philfry

see #1250

2017-03-15 06:29 UTC, strk requested changes
I see you're feeding a bash script to a user-configurable `scriptType`, sounds fragile to me. Can you us a POSIX syntax please ?

2017-03-15 06:31 UTC, strk requested changes

2017-03-15 06:31 UTC, strk commented on models/repo.go
> +		hookTpl = fmt.Sprintf("#!/usr/bin/env %s\ndata=$(cat)\nexitcodes=()\nhookname=$(basename $0)\nGIT_DIR=${GIT_DIR:-$(dirname $0)}\n\nfor hook in ${GIT_DIR}/hooks/${hookname}.d/*; do\ntest -x \"${hook
bash-specific syntax (`$(cat)`) in what could be running with something else (`setting.ScriptType`).
Not that I understand how can Gitea possibly contains code to be run by unknown scripts, anyway the app.ini Cheat Sheet says `ScriptType` is usually bash or sh...

2017-03-15 07:23 UTC, vtolstov commented
Why we can't create symlink for hooks to gitea binary? In this case we
don't need bash, sh and other stuff. And gitea handle hook internally.

15 Мар 2017 г. 9:29 пользователь "Sandro Santilli" <notifications@github.com>
написал:

> *@strk* requested changes on this pull request.
>
> I see you're feeding a bash script to a user-configurable scriptType,
> sounds fragile to me. Can you us a POSIX syntax please ?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/go-gitea/gitea/pull/1257#pullrequestreview-26999306>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AAdYG9TihPxRzcXJdX42SJmwKrkEb0KBks5rl4UugaJpZM4MdRlY>
> .
>

2017-03-15 09:17 UTC, philfry commented on models/repo.go
> +		hookTpl = fmt.Sprintf("#!/usr/bin/env %s\ndata=$(cat)\nexitcodes=()\nhookname=$(basename $0)\nGIT_DIR=${GIT_DIR:-$(dirname $0)}\n\nfor hook in ${GIT_DIR}/hooks/${hookname}.d/*; do\ntest -x \"${hook
`data=$(cat)`  is not bash-specific.

`bash` can be run in posix mode when either invoking the script either using `sh` (`sh scriptname`, `sh` in shebang) or by using the switch `--posix` (or using `set -o posix` in the script itself). Tried both of it, script worked fine. Even though `myarray=()` is a bashism.

Some Debian systems might symlink `/bin/sh` to `/bin/dash` (the Debian Almquist Shell), so we might want to force using `bash` in this case.

Or, to make it more posix-compliant, give up on arrays:
```sh
#!/bin/sh

data=$(cat)
exitcodes=""
hookname=$(basename $0)
GIT_DIR=${GIT_DIR:-$(dirname $0)}

for hook in ${GIT_DIR}/hooks/${hookname}.d/*; do
	test -x "${hook}" || continue
	echo "${data}" | "${hook}"
	exitcodes="${exitcodes} $?"
done

for i in ${exitcodes}; do
	[ $i -eq 0 ] || exit $i
done
```
(tested with `dash`)

2017-03-20 17:29 UTC, strk commented
I dunno why are you talking about symlinks, but yes I think we could just invoke the commands, if executables. But please make sure you touch all files containing that bash invocation, I see 3 places.
Also it would be great to have unit tests for this

2017-03-20 17:44 UTC, philfry commented
Am I missing something? The `migrations`?
```
$ find . -name '*.go' -print0 | xargs -r0 grep -P '^(?!//).*\bsh\b'
./models/migrations/v22.go:			fmt.Sprintf("#!/usr/bin/env %s\nORI_DIR=`pwd`\nSHELL_FOLDER=$(cd \"$(dirname \"$0\")\";pwd)\ncd \"$ORI_DIR\"\nfor i in `ls \"$SHELL_FOLDER/pre-receive.d\"`; do\n    sh \"$SHELL_FOLDER/pre-receive.d/$i\"\ndone", setting.ScriptType),
./models/migrations/v22.go:			fmt.Sprintf("#!/usr/bin/env %s\nORI_DIR=`pwd`\nSHELL_FOLDER=$(cd \"$(dirname \"$0\")\";pwd)\ncd \"$ORI_DIR\"\nfor i in `ls \"$SHELL_FOLDER/update.d\"`; do\n    sh \"$SHELL_FOLDER/update.d/$i\" $1 $2 $3\ndone", setting.ScriptType),
./models/migrations/v22.go:			fmt.Sprintf("#!/usr/bin/env %s\nORI_DIR=`pwd`\nSHELL_FOLDER=$(cd \"$(dirname \"$0\")\";pwd)\ncd \"$ORI_DIR\"\nfor i in `ls \"$SHELL_FOLDER/post-receive.d\"`; do\n    sh \"$SHELL_FOLDER/post-receive.d/$i\"\ndone", setting.ScriptType),
./models/migrations/v19.go:			fmt.Sprintf("#!/usr/bin/env %s\nORI_DIR=`pwd`\nSHELL_FOLDER=$(cd \"$(dirname \"$0\")\";pwd)\ncd \"$ORI_DIR\"\nfor i in `ls \"$SHELL_FOLDER/pre-receive.d\"`; do\n    sh \"$SHELL_FOLDER/pre-receive.d/$i\"\ndone", setting.ScriptType),
./models/migrations/v19.go:			fmt.Sprintf("#!/usr/bin/env %s\nORI_DIR=`pwd`\nSHELL_FOLDER=$(cd \"$(dirname \"$0\")\";pwd)\ncd \"$ORI_DIR\"\nfor i in `ls \"$SHELL_FOLDER/update.d\"`; do\n    sh \"$SHELL_FOLDER/update.d/$i\" $1 $2 $3\ndone", setting.ScriptType),
./models/migrations/v19.go:			fmt.Sprintf("#!/usr/bin/env %s\nORI_DIR=`pwd`\nSHELL_FOLDER=$(cd \"$(dirname \"$0\")\";pwd)\ncd \"$ORI_DIR\"\nfor i in `ls \"$SHELL_FOLDER/post-receive.d\"`; do\n    sh \"$SHELL_FOLDER/post-receive.d/$i\"\ndone", setting.ScriptType),
./vendor/golang.org/x/text/language/maketables.go:	"ro", "ru", "sh", "si", "sk", "sl", "sq", "sr", "sv", "sw", "ta", "te", "th",
./vendor/golang.org/x/text/language/maketables.go:	lang.updateLater("sh", "hbs")
./vendor/golang.org/x/sys/unix/types_openbsd.go:Input to cgo -godefs.  See also mkerrors.sh and mkall.sh
./vendor/golang.org/x/sys/unix/types_darwin.go:Input to cgo -godefs.  See also mkerrors.sh and mkall.sh
./vendor/golang.org/x/sys/unix/types_netbsd.go:Input to cgo -godefs.  See also mkerrors.sh and mkall.sh
./vendor/golang.org/x/sys/unix/types_freebsd.go:Input to cgo -godefs.  See also mkerrors.sh and mkall.sh
./vendor/golang.org/x/sys/unix/types_linux.go:Input to cgo -godefs.  See also mkerrors.sh and mkall.sh
./vendor/golang.org/x/sys/unix/types_solaris.go:Input to cgo -godefs.  See also mkerrors.sh and mkall.sh
./vendor/golang.org/x/sys/unix/types_dragonfly.go:Input to cgo -godefs.  See also mkerrors.sh and mkall.sh
./modules/base/tool.go:	sh := sha1.New()
./modules/base/tool.go:	sh.Write([]byte(data + setting.SecretKey + startStr + endStr + com.ToStr(minutes)))
./modules/base/tool.go:	encoded := hex.EncodeToString(sh.Sum(nil))
./modules/highlight/highlight.go:		".sh":     true,
```

2017-03-20 17:47 UTC, strk commented
Yes, the migrations. I'm not very sure what are them for, and how to effectively test them, will be tricky.
You can always trigger them by setting version.version in the database to the lowest version (19, in this case) and starting Gitea again. I guess it takes installing some hooks in the old format to test the migrations.

2017-03-21 01:00 UTC, lunny commented
The migrations will be simple to rewrite all the scripts. But don't forget wiki repo's hooks.

2017-03-21 10:44 UTC, philfry commented
afaics the wiki pages use the same hooks as the repos do. Which leads to funny side-effects[1] but that's not relevant here.
So, nothing to do for the wikis here.

I'm a little concerned about the migration scripts. In my understanding the scripts should update database schemas, scripts (i.e. hooks) and other stuff that might have changed between gitea versions.
I can change `v19.go` and `v22.go` to match the new hook scripts. So when updating from gitea .. say 0.9 .. the hooks will be rewritten. But when updating from gitea 1.1.0  to gitea > 1.1.0 will the changes be applied? Or do we need a completely new migration script `v23.go` (or whatever it will be named) that replaces the hooks once again?



[1] I have `git-multimail.py` in my git templates so on every wiki page change I get a mail with the diff :)

2017-03-21 14:44 UTC, strk commented
Good question about migrations. I think first step is understanding what those migrations did in `v19` and `v22`. If they installed broken scripts, now we'd need a new migration to fix those scripts (if we can ensure those scripts are "owned" by gitea)

2017-03-21 17:18 UTC, philfry commented
the migration works for me.
Tested:
- freshly installed gitea 1.0.0 → 1.1.0 → 1.1.0fix_hooks
- freshly installed gitea 1.1.0 → 1.1.0fix_hooks
- gitea 1.1.0 w/ custom hooks → 1.1.0fix_hooks

2017-03-21 17:19 UTC, bkcsoft commented
As @strk pointed out, don't touch existing migrations, it will break things even worse. Create a new migration that updates all existing hooks.

2017-03-21 17:41 UTC, philfry commented
@bkcsoft I did not touch existing migrations.

2017-03-22 00:57 UTC, lunny requested changes

2017-03-22 00:57 UTC, lunny commented on models/migrations/v26.go
> +package migrations
comment header

2017-03-22 01:24 UTC, lunny commented on models/migrations/migrations.go
> +  NewMigration("generate and migrate repo and wiki Git hooks", generateAndMigrateGitHookChains),
Format

2017-03-22 01:28 UTC, lunny commented
And maybe you can also fix another issue
```
SyncRepositoryHooks
```
This function didn't sync wiki repository's hooks.

2017-03-22 01:30 UTC, lunny commented
otherwise LGTM

2017-03-22 09:14 UTC, strk commented on models/migrations/migrations.go
> +  NewMigration("generate and migrate repo and wiki Git hooks", generateAndMigrateGitHookChains),
Run `make fmt` should be enough (and we need our bot to guard after this, I may give that a try)

2017-03-22 09:18 UTC, strk commented
So doesn't it take any migration to fix the existing hooks ? How/when do those wrapper scripts get installed in git repos ?

2017-03-22 09:47 UTC, philfry commented
@strk I'm not sure what you're talking about. Actually there _is_ a migration script (`v26.go`) to install the new hooks.

@lunny I'll try to fix it. Do you want it in this PR or shall I open a new PR when done?
btw - the "comment header" change is done but this PRs status is still on "Changes requested".

2017-03-22 10:55 UTC, lunny approved these changes

2017-03-22 15:52 UTC, strk commented
@philfry sorry I think I was fooled by github as when I wrote that comment I really didn't see the migration file !

LGTM (trusted, didn't really test it)

2017-03-23 01:12 UTC, merged

2017-03-23 01:15 UTC, lunny commented
@philfry, could you send a backport PR to v1.1? But maybe the migrations is difficult to handle.