Escape more things that are passed through str2html
go-gitea/gitea pull request #12622
Opened 2020-08-27 14:28 UTC by zeripath

Signed-off-by: Andrew Thornton <art27@cantab.net>

2020-08-27 18:16 UTC, mrsdizzie requested changes

2020-08-27 18:16 UTC, mrsdizzie commented on templates/user/dashboard/feeds.tmpl
> +							{{$.i18n.Tr "action.delete_branch" .GetRepoLink (.GetBranch|Escape .ShortRepoPath | Str2html}}
```suggestion
							{{$.i18n.Tr "action.delete_branch" .GetRepoLink (.GetBranch|Escape) .ShortRepoPath | Str2html}}
```
```suggestion
							{{$.i18n.Tr "action.delete_branch" .GetRepoLink (.GetBranch|Escape .ShortRepoPath | Str2html}}
```

2020-08-27 18:16 UTC, mrsdizzie commented on templates/user/dashboard/feeds.tmpl
> +							{{$.i18n.Tr "action.mirror_sync_push" .GetRepoLink $branchLink (.GetBranch|Escape .ShortRepoPath | Str2html}}
```suggestion
							{{$.i18n.Tr "action.mirror_sync_push" .GetRepoLink $branchLink (.GetBranch|Escape) .ShortRepoPath | Str2html}}
```
```suggestion
							{{$.i18n.Tr "action.mirror_sync_push" .GetRepoLink $branchLink (.GetBranch|Escape .ShortRepoPath | Str2html}}
```

2020-08-27 18:16 UTC, mrsdizzie commented on templates/user/dashboard/feeds.tmpl
> +							{{$.i18n.Tr "action.mirror_sync_create" .GetRepoLink (.GetBranch|Escape .ShortRepoPath | Str2html}}
```suggestion
							{{$.i18n.Tr "action.mirror_sync_create" .GetRepoLink (.GetBranch|Escape) .ShortRepoPath | Str2html}}
```
```suggestion
							{{$.i18n.Tr "action.mirror_sync_create" .GetRepoLink (.GetBranch|Escape .ShortRepoPath | Str2html}}
```

2020-08-27 18:16 UTC, mrsdizzie commented on templates/user/dashboard/feeds.tmpl
> +							{{$.i18n.Tr "action.mirror_sync_delete" .GetRepoLink (.GetBranch|Escape .ShortRepoPath | Str2html}}
```suggestion
							{{$.i18n.Tr "action.mirror_sync_delete" .GetRepoLink (.GetBranch|Escape) .ShortRepoPath | Str2html}}
```
```suggestion
							{{$.i18n.Tr "action.mirror_sync_delete" .GetRepoLink (.GetBranch|Escape .ShortRepoPath | Str2html}}
```

2020-08-27 19:49 UTC, mrsdizzie approved these changes

2020-08-27 21:09 UTC, zeripath commented on routers/user/oauth.go
> +	ctx.Data["ApplicationUserLink"] = "<a href=\"" + html.EscapeString(setting.AppURL) + url.PathEscape(app.User.LowerName) + "\">@" + html.EscapeString(app.User.Name) + "</a>"
```suggestion
	ctx.Data["ApplicationUserLink"] = "<a href=\"" + html.EscapeString(setting.AppURL) + html.EscapeString(url.PathEscape(app.User.LowerName)) + "\">@" + html.EscapeString(app.User.Name) + "</a>"
```

2020-08-28 03:41 UTC, techknowlogick approved these changes

2020-08-28 04:37 UTC, merged