Refactor: move Commit To APIFormat Code & Lot of StopWatch related things
go-gitea/gitea pull request #12729
Opened 2020-09-05 17:58 UTC by 6543

close #12723

## StopWatch
* extend TestAPIListStopWatches
* remove type Stopwatches
* rewrite Stopwatch List to APIFormat Convert (in convert package) <- now cache issue & repo

 ## Commit:
* create own file for related things in convert package
* rename ToCommit ToPayloadCommit
* move toCommit into convert package

2020-09-06 14:19 UTC, zeripath approved these changes

2020-09-18 07:47 UTC, lunny requested changes
Otherwise LGTM

2020-09-18 07:47 UTC, lunny commented on modules/convert/git_commit.go
> +// Copyright 2020 The Gogs Authors. All rights reserved.
Gitea

2020-09-18 07:50 UTC, lunny commented
And I think this could be moved to v1.13 once it's ready.

2020-09-18 11:31 UTC, 6543 commented on modules/convert/git_commit.go
> +// Copyright 2020 The Gogs Authors. All rights reserved.
```suggestion
// Copyright 2020 The Gitea Authors. All rights reserved.
```

2020-09-18 11:32 UTC, 6543 commented on modules/convert/git_commit.go
> +// Copyright 2020 The Gogs Authors. All rights reserved.
@lunny done

2020-09-18 12:08 UTC, lunny approved these changes

2020-09-18 12:09 UTC, merged