Move git update-server-info to hooks
go-gitea/gitea pull request #12826
Opened 2020-09-13 16:23 UTC by zeripath

As mentioned in #10133 - update-server-info doesn't really belong in the running gitea process but in the hook during its update. 

This PR moves this call to the hook directly. 

We should consider whether this git method is actually still necessary as `routers/repo/http.go:616:getInfoRefs` appears to run this command anyway.

Signed-off-by: Andrew Thornton <art27@cantab.net>

2020-10-10 22:37 UTC, 6543 approved these changes
update-server-info is cheep to execute ...

2020-10-11 01:34 UTC, techknowlogick commented
🚀

2020-10-11 12:44 UTC, lunny commented
But HTTP protocol push will miss that update?

2020-10-13 00:04 UTC, jolheiser approved these changes

2020-10-13 00:51 UTC, lunny commented
> But HTTP protocol push will miss that update?

@zeripath

2020-10-13 01:00 UTC, techknowlogick requested changes, later dismissed
blocking per @lunny Question.

2020-10-13 06:07 UTC, zeripath commented
No it won't - http push always runs the hooks too.

This is simply running update-server-info as part of post-receive (the modern equivalent of post-update where it is supposed to be run)

2020-10-13 06:53 UTC, lafriks approved these changes

2020-10-13 16:24 UTC, merged