WIP: Generate Changelog automagically
go-gitea/gitea pull request #1298
Opened 2017-03-17 05:54 UTC by bkcsoft

Automagically generate changelog on `make release` 🎉 

TODO:
- [x] Generate changelog
- [x] Append historical changelog (kept in `changelog/HISTORICAL.md`
- [x] Move unreleased-section in current changelog to yaml-files
- [x] Updated the Makefile
- [ ] Make it efficient 😂 

Current implementation is _extremely_ write-intensive... That should be fixed 🙄 

_Please_ be brutal when reviewing this, since **it needs to work** 100% flawless

I assigned all Owners to review, since _we_ deal with this pain. Also assigned Team maintainers since I want more eyes on this code 😆

2017-03-17 06:05 UTC, bkcsoft commented
@strk Since I moved your changelog to a file, do you want your full name in there or nickname? (or both)

2017-03-17 06:45 UTC, tboerger requested changes
Maybe generally use log instead of fmt?

2017-03-17 06:45 UTC, tboerger commented on scripts/generate-changelog.go
> +	version    = flag.String("version", "", "Version for changelog")
The definition into main to avoid conflicts?

2017-03-17 06:45 UTC, tboerger commented on scripts/generate-changelog.go
> +	flag.Parse()
Within the other scripts I have moved that into main as well

2017-03-17 06:45 UTC, tboerger commented on scripts/generate-changelog.go
> +		fmt.Printf("Error: writing changelog: %v\n", err)
Exit?

2017-03-17 06:45 UTC, tboerger commented on scripts/generate-changelog.go
> +	cleTmpl = `
Incomplete or unused?

2017-03-17 06:46 UTC, tboerger commented on changelog/HISTORICAL.md
> +## Unreleased
Shouldn't be part of the historical file

2017-03-17 07:02 UTC, bkcsoft commented on scripts/generate-changelog.go
> +	cleTmpl = `
Unused

2017-03-17 08:51 UTC, strk commented on Makefile
> +	cat changelog/HISTORICAL.md >> CHANGELOG.md
This sounds brutal. A Makefile target that always unconditionally appends to a file ?
I see that file is created by the unreleased/*.md target, but it isn't at all intutitive.

2017-03-17 09:24 UTC, lunny commented
ChangeLog codes maybe should be in `modules/changelog` so that we can add a feature to gitea as `generate a changelog`. Then when we eat dogfood, we could use it and no need write twice.

2017-03-19 17:00 UTC, bkcsoft commented
@lunny I thought `go run` didn't like modules. But now that I think about it, it makes a lot of sense to make it a package 😄

2017-03-19 17:01 UTC, bkcsoft commented
@lunny Maybe even it's own repo?

2017-03-20 01:16 UTC, lunny commented
@bkcsoft I just give an advice to reuse the functions. But I cannot give you some ideas about how to do that.

2017-03-20 01:23 UTC, bkcsoft commented on Makefile
> +	cat changelog/HISTORICAL.md >> CHANGELOG.md
I've updated it so it hopefully makes more sense :)

2017-03-20 01:24 UTC, bkcsoft commented
@tboerger I've updated according to your request :)

2017-03-24 14:44 UTC, bkcsoft commented
@lunny @tboerger I made it into it's own repo. You can find it here: https://gitlab.com/bkc/changelogger

2017-03-25 04:59 UTC, lunny commented
@bkcsoft great!

2017-04-07 13:06 UTC, lunny commented
build failed.

2017-04-25 22:39 UTC, bkc-soft commented
Gitea is stupid

2017-06-15 02:42 UTC, bkcsoft commented
I'm closing this in favour of the actual package.

2017-06-15 02:42 UTC, closed without merging