Adding visual cue for "Limited" & "Private" organizations.
go-gitea/gitea pull request #13040
Opened 2020-10-05 21:40 UTC by smtaylorslc

Implements #13017 .

Label for "Limited" & "Private" organizations added to org header, org homepage, and navbar.

Before:

> <img width="306" alt="Screen Shot 2020-10-05 at 4 06 59 PM" src="https://user-images.githubusercontent.com/19273870/95134749-05f61900-0729-11eb-90ad-292a98f42cd1.png">
> <img width="646" alt="Screen Shot 2020-10-05 at 4 06 49 PM" src="https://user-images.githubusercontent.com/19273870/95134757-0abacd00-0729-11eb-9e1c-a13487a48a40.png">

After:

> <img width="485" alt="Screen Shot 2020-10-05 at 4 06 07 PM" src="https://user-images.githubusercontent.com/19273870/95134774-127a7180-0729-11eb-95c5-b4c81a83cb20.png">
> <img width="381" alt="Screen Shot 2020-10-05 at 4 07 30 PM" src="https://user-images.githubusercontent.com/19273870/95134795-17d7bc00-0729-11eb-8d93-86311ef52010.png">
> <img width="737" alt="Screen Shot 2020-10-05 at 4 21 25 PM" src="https://user-images.githubusercontent.com/19273870/95134818-202ff700-0729-11eb-8f8b-95bd8f4e416e.png">
> <img width="458" alt="Screen Shot 2020-10-05 at 4 21 18 PM" src="https://user-images.githubusercontent.com/19273870/95134831-23c37e00-0729-11eb-9b9d-7449bae2834f.png">
> <img width="785" alt="Screen Shot 2020-10-05 at 4 06 28 PM" src="https://user-images.githubusercontent.com/19273870/95134949-50779580-0729-11eb-8086-38be25afa78d.png">
> <img width="579" alt="Screen Shot 2020-10-05 at 4 07 20 PM" src="https://user-images.githubusercontent.com/19273870/95134971-5c635780-0729-11eb-97be-7df883461094.png">

2020-10-05 21:51 UTC, zeripath approved these changes

2020-10-06 00:55 UTC, 6543 requested changes
I realy like how it looks like ...

two TODO's:
 * move inline css to less files
 * public repos in limited orgs are limited too

2020-10-06 00:55 UTC, 6543 commented on templates/org/header.tmpl
> +					{{if .Visibility.IsLimited}}<div class="ui medium orange horizontal label" style="margin-left: 5px; margin-top: 2px">{{$.i18n.Tr "org.settings.visibility.limited_shortname"}}</div>{{end}}
move css into less files (web_src/less)

2020-10-06 04:08 UTC, smtaylorslc commented
@6543 Moved styles to .less files in commit 17fbba7 . Re: repository "Limited" labels -- do we want to find some way to visually show that the "Limited" attribute/label is inherited from the org (opposed to the "Private" attribute, which is set at the repository level & also creates a label next to the repo name)?

2020-10-06 05:55 UTC, techknowlogick approved these changes

2020-10-06 06:25 UTC, techknowlogick commented
🚀

2020-10-06 06:25 UTC, techknowlogick commented
@6543 I think the 2nd one can be saved for later PR

2020-10-06 06:25 UTC, merged