Add mentionable teams to tributeValues
go-gitea/gitea pull request #13198
Opened 2020-10-18 13:12 UTC by a1012112796

As title, example view:
![2020-10-18 20-48-13屏幕截图](https://user-images.githubusercontent.com/25342410/96368140-c4338c80-1184-11eb-9a82-ce9006f5159c.png)

TODO:

- [ ] Maybe need change the rule for team mention to @{{OrgName}}/{{TeamName}}  to protect a team have same name with a user.
- [ ] have no idea about how to fix avatar bug now

2020-10-18 19:44 UTC, 6543 commented
@a1012112796 avatar bug: use the same icon as with pullreview-requested-teams:

![Screenshot at 2020-10-18 21-43-47](https://user-images.githubusercontent.com/24977596/96378265-0a8bea00-118b-11eb-8094-d99fc22dec17.png)
?

2020-10-18 20:28 UTC, silverwind commented on templates/base/head.tmpl
> +      	{{if .RequireTribute}}
```suggestion
      {{if .RequireTribute}}
```

2020-10-18 20:29 UTC, silverwind commented on templates/base/head.tmpl
> +      	{{if .RequireTribute}}
```suggestion
			{{if .RequireTribute}}
```

2020-10-18 20:30 UTC, silverwind commented on templates/base/head.tmpl
> +		{{end}}
```suggestion
			{{end}}
```

2020-10-18 20:31 UTC, silverwind commented
> use the same icon as with pullreview-requested-teams

I'd use the org icon if possible

2020-10-18 22:08 UTC, lafriks commented
Imho we should prefix them with org name and other possibility is to use specific group icon

2020-10-21 13:41 UTC, lunny commented
I think maybe we should support mention anyone at first.

2020-10-23 02:16 UTC, a1012112796 commented
> I think maybe we should support mention anyone at first.

Do you means "@all" ?

2020-10-23 11:33 UTC, lunny commented
> > I think maybe we should support mention anyone at first.
> 
> Do you means "@ALL" ?

No. I mean currently we can only mention the orgnizaion members. We should allow to mention anyone in this Gitea instance.

2020-10-23 11:47 UTC, a1012112796 commented
> > > I think maybe we should support mention anyone at first.
> > 
> > 
> > Do you means "@ALL" ?
> 
> No. I mean currently we can only mention the orgnizaion members. We should allow to mention anyone in this Gitea instance.
you can mention anyone now. but not support hint on ui  now. gitea only add all assignees and participants to the list now.

2020-10-23 11:51 UTC, a1012112796 commented on modules/markup/html.go
> +func mentionProcessor(ctx *postProcessCtx, node *html.Node) { // TODO
```suggestion
func mentionProcessor(ctx *postProcessCtx, node *html.Node) {
```

2020-10-23 15:19 UTC, silverwind commented
I generally think those mentions need to be rewritten to use a AJAX call to obtain the mentionees. I think tribute.js already supports async loading of data. Doesn't need to be done in this PR but would be nice to have.

2020-10-23 17:46 UTC, lafriks requested changes

2020-10-23 17:46 UTC, lafriks commented on models/issue.go
> +		mentionTeams = make([]string, 5)
```suggestion
		mentionTeams = make([]string, 0, 5)
```

2020-10-24 11:58 UTC, lafriks approved these changes

2020-12-21 12:33 UTC, 6543 commented on models/issue.go
> +			if len(checked) > 0 {
reason to change this?

2020-12-21 12:38 UTC, 6543 commented on modules/references/references.go
> +	mentionPattern = regexp.MustCompile(`(?:\s|^|\(|\[)(@[0-9a-zA-Z-_]+|@[0-9a-zA-Z-_]+\/?[0-9a-zA-Z-_]+|@[0-9a-zA-Z-_][0-9a-zA-Z-_.]+\/?[0-9a-zA-Z-_.]+[0-9a-zA-Z-_])(?:\s|[:,;.?!]\s|[:,;.?!]?$|\)|\])`)
we should add tests for this regexp ...!

2020-12-21 14:26 UTC, a1012112796 commented on models/issue.go
> +			if len(checked) > 0 {
Hmm, It's not usefull.
```suggestion
			if len(checked) != 0 {
```

2020-12-21 15:11 UTC, 6543 approved these changes

2020-12-21 15:39 UTC, merged