skip email validation on empty string
go-gitea/gitea pull request #13627
Opened 2020-11-18 23:09 UTC by 6543

- move validation into its own function
- use a session for UpdateUserSetting

close #13587

2020-11-19 11:15 UTC, lunny approved these changes

2020-11-19 15:41 UTC, 6543 commented
regression of #13475 - so I'll add skip-changelog label

2020-11-19 23:16 UTC, lafriks approved these changes

2020-11-19 23:17 UTC, lafriks commented on models/user_mail.go
> +	if len(email) != 0 {
It would be better to inverse this if and return nil if len == 0

2020-11-19 23:18 UTC, lafriks requested changes
As per my comment

2020-11-19 23:22 UTC, 6543 commented
@lafriks done

2020-11-20 21:45 UTC, lafriks approved these changes

2020-11-20 21:45 UTC, merged