Include formatting check to the `make check` rule
go-gitea/gitea pull request #1366
Opened 2017-03-22 10:41 UTC by strk

... and give it its own standalone target too (make fmt-check)

\cc @lunny, @tboerger, @bkcsoft

2017-03-22 15:52 UTC, appleboy approved these changes

2017-03-22 15:59 UTC, appleboy commented
```diff
fmt:
- 	find . -name "*.go" -type f -not -path "./vendor/*" | xargs gofmt -s -w
+ 	find . -name "*.go" -type f -not -path "./vendor/*" | xargs gofmt -d -s -w
```

display diffs on drone logs.

2017-03-22 16:05 UTC, strk commented
@appleboy I don't understand your comment. This PR is about making drone *fail* unless the PR code was threated by running `make fmt`

2017-03-24 00:19 UTC, bkcsoft commented
@appleboy the way I read the docs for `gofmt` `-d` and `-w` would be mutually exclusive. So that wouldn't work either :) and `make fmt` is there so contributors can easily fix formating :)

>   -d    display diffs instead of rewriting files
>   -w    write result to (source) file instead of stdout

2017-03-24 00:35 UTC, bkcsoft requested changes

2017-03-24 00:35 UTC, bkcsoft commented on Makefile
> +test: fmt-check
This make it part of `make test`, not `make check` as the title says. Change one of them 🙂

2017-03-24 03:47 UTC, appleboy commented
@strk I mean that the `-d` flag show all diff data in logs so the developer can look at it.

2017-03-24 21:27 UTC, strk commented on Makefile
> +test: fmt-check
clarified the title (check is an alias for test)

2017-03-24 21:46 UTC, strk commented
@appleboy gofmt -d seems indeed useful, but doesn't tell in the exit code if there was or not a diff.
With b2e1367 I removed the --quiet argument to diff so you do get to see the changes, and also I've added messages to give hint about how to fix the problem

2017-03-25 03:23 UTC, appleboy commented
@strk Good work. It is working for me https://github.com/go-training/training/tree/master/example01

LGTM

Don't forget to run `make fmt` to fix build errors.

![screen shot 2017-03-25 at 11 21 42 am](https://cloud.githubusercontent.com/assets/21979/24319121/6039a93e-114d-11e7-922a-335a034e19fe.png)

2017-03-25 11:27 UTC, strk commented
@bkcsoft please lift your barrier and let this flow  ! :)

2017-03-27 15:10 UTC, bkcsoft approved these changes

2017-03-29 11:18 UTC, strk commented
I've just installed Go 1.8 and `gofmt` from that version also doesn't change any file in this branch. So it looks like 1.7 was bogus or something like that, what do you think @tboerger ?

2017-03-29 11:24 UTC, strk commented
Actually I just tried the `make fmt` rule with `go version go1.7 linux/amd64` and it also didn't change a thing in this branch, so it looks like the difference is elsewhere.

2017-03-29 11:34 UTC, tboerger commented
I don't like such complicated make tasks without a bigger benefit.

2017-03-29 12:29 UTC, strk commented
I don't like the complexity either, so if we cannot ensure any Go version would format the code in the same way, let's forget about it (and beware of the "make fmt" rule too as it might be doing and undoing the same thing)

2017-05-02 09:23 UTC, sapk commented
Any news on that ? 
For the difference of format depending of go version, I think we just need to choose one (the simplest should be to choose the one of the drone instance)

2017-05-02 13:47 UTC, strk commented
If I'm not wrong I was using the same version used on Drone, still
the format was different, so maybe it's not just version but also
architecture ?

2017-05-04 00:55 UTC, appleboy commented
@strk How about the following check script so we can run fmt check with unstaged changes.

```makefile
.PHONY: fmt-check
fmt-check:
	# get all go files and run go fmt on them
	@files=$$($(GOFILES) | xargs $(GOFMT) -l); if [ -n "$$files" ]; then \
		echo "Please run 'make fmt' and commit the result:"; \
		echo "$${files}"; \
		exit 1; \
		fi;
```

2017-05-04 05:15 UTC, strk commented
The reason to forbid running with unstaged changes is to avoid
changing the tree state. The current `fmt-check` rule does
a `checkout .` after the gofmt run, so you're left with what you
had before you started.

If gofmt -l ensures that, I'm ok with the change.
But where are GOFILES and GOFMT defined ?
Was your code just an example @appleboy ?

2017-05-04 06:06 UTC, appleboy commented
@strk I updated the previous comment and add missing variables on Makefile.

I can confirm that `gofmt -l` is working on your scenario with Drone.

2017-05-08 08:19 UTC, strk commented
@appleboy I gave your version a try but it is less informative than my version.
My version, run against current master, returns:
```
$ make fmt-check-old
make[1]: Entering directory '/home/strk/go/src/code.gitea.io/gitea'
find . -name "*.go" -type f -not -path "./vendor/*" | xargs gofmt -s -w
make[1]: Leaving directory '/home/strk/go/src/code.gitea.io/gitea'
diff --git a/models/repo.go b/models/repo.go
index d29df1b..88cffa5 100644
--- a/models/repo.go
+++ b/models/repo.go
@@ -286,7 +286,7 @@ func (repo *Repository) APIFormat(mode AccessMode) *api.Repository {
                Description:   repo.Description,
                Private:       repo.IsPrivate,
                Empty:         repo.IsBare,
-               Size:          int(repo.Size/1024),
+               Size:          int(repo.Size / 1024),
                Fork:          repo.IsFork,
                Mirror:        repo.IsMirror,
                HTMLURL:       repo.HTMLURL(),

Please run 'make fmt' and commit the result

Makefile:97: recipe for target 'fmt-check-old' failed
make: *** [fmt-check-old] Error 1
```

Your version:
```
$ make fmt-check
# get all go files and run go fmt on them
Please run 'make fmt' and commit the result:
./models/repo.go
Makefile:87: recipe for target 'fmt-check' failed
make: *** [fmt-check] Error 1
```

I find the diff output more useful, especially as we find that different versions can give different results...

2017-05-08 08:20 UTC, strk commented
Oh, and this now explains why my version could not be run with unstaged changes... (as it would be destructive upon checkout after the format run)

2017-05-08 08:22 UTC, strk commented
Note also that my version really runs `make fmt` so there's no possibility for checking and executing to go out of sync. I've pushed a rebase against current master, so we can see if the check reports anything.

2017-05-08 08:30 UTC, appleboy commented
@strk 

```diff
GOFILES := find . -name "*.go" -type f -not -path "./vendor/*"
GOFMT ?= gofmt "-s"

.PHONY: fmt-check
fmt-check:
	# get all go files and run go fmt on them
-	@files=$$($(GOFILES) | xargs $(GOFMT) -l); if [ -n "$$files" ]; then \
+	@files=$$($(GOFILES) | xargs $(GOFMT) -d); if [ -n "$$files" ]; then \
		echo "Please run 'make fmt' and commit the result:"; \
		echo "$${files}"; \
		exit 1; \
		fi;
```

just change `-l` to `-d`

2017-05-08 08:46 UTC, strk commented
Another problem with not relying on the `make fmt` rule is that the `make fmt` rule does the version check, so anyone running 1.6 would not get stuck in a loop (fails make check because version is different, but cannot fix because the rule doesn't let fix).

I guess the latter could be fixed by a common "require-format-version" rule or similar.

2017-05-08 08:54 UTC, strk commented
See how you like the code now. Has a rule to check dependency and uses `$(GOFILES)` in both `fmt` and `fmt-check` rules. I did not push the actual format fix to let you see the Drone output...

2017-05-08 09:08 UTC, strk commented
I can tell there are way more issues found by `fmt-check` on Drone than on my machine:
https://drone.gitea.io/go-gitea/gitea/3000

2017-05-09 06:22 UTC, appleboy approved these changes

2017-05-09 06:22 UTC, appleboy commented
LGTM

2017-05-09 13:54 UTC, sapk commented
LGTM

2017-05-09 14:17 UTC, lunny commented
but build failed

2017-05-09 14:36 UTC, sapk commented
@strk you should rebase and apply `make fmt` in this PR so that code formatting after this PR is also good.

2017-05-10 14:13 UTC, strk commented
@sapk what I wrote before means that if I run `make fmt` and commit the result this PR would still fail because my `make fmt` would do something different from Travis' `make fmt`. This is the whole reason why this PR is blocked here...

To recap, my `make check-fmt` only reports a single line to be changed, while you can see Travis reporting much more

2017-05-10 14:13 UTC, strk commented
For the output on my machine, see https://github.com/go-gitea/gitea/pull/1366#issuecomment-299803225

2017-05-12 03:01 UTC, appleboy commented
@strk Still build fail.

2017-06-03 15:20 UTC, appleboy commented
@strk any updates?

2017-06-06 08:23 UTC, strk commented
@appleboy I gave up due to the differences in formatting choices on different machines (mine, and drone's). Do you want to try from your side ? It'd be a pain to be unable to fix a problem reported by Drone because the developers `make fmt` would produce a different output. I think this is what makes this PR unmergeable...

2017-06-06 08:31 UTC, strk commented
Anyway, rebased for a final review. Running `make fmt` on my machine results in on changes, and `make fmt-check` passes here. Let's see if Drone made his mind...

2017-06-06 08:35 UTC, appleboy commented
@strk We should ignore the `bindata` file. otherwise LGTM

2017-06-06 08:52 UTC, sapk commented
LGTM let merge this if CI don't complain ^^

2017-06-06 09:18 UTC, appleboy commented
https://drone.gitea.io/go-gitea/gitea/3383

@strk Can you fix some format error?

2017-06-06 09:20 UTC, strk commented
@appleboy as I wrote before, `make fmt` on my machine results in no change. This is with `go version go1.7.4 linux/amd64` -- Sorry, but gofmt is failing here :/

2017-06-06 09:21 UTC, appleboy commented
@strk Please rebase the latest code. I just merged https://github.com/go-gitea/gitea/pull/1881 so the CI trigger error.

2017-06-06 09:32 UTC, strk commented
Ok with the rebase I do have format changed on `make fmt`, should I commit them too ?

2017-06-06 10:23 UTC, strk commented
So now Drone was happy before my `make fmt` invocation, this means it'll be probably unhappy now. Contending styles. This is a no-go.

2017-06-06 10:43 UTC, appleboy commented
@strk So let's merge this PR or any concern?

2017-06-06 10:48 UTC, strk commented
Uhm, as it's still happy (and I am too on my side) - let's merge this.
Even if I don't understand how it works ... we'll eventually file a ticket if things go wrong.

2017-06-06 11:42 UTC, lunny commented
@appleboy @strk I think move this to v1.2 and merge it is a good idea.

2017-06-06 13:53 UTC, appleboy commented
@lunny Done. move to `1.2.0`

2017-06-06 13:53 UTC, merged