backport of PR #1257 for release/v1.1: rewrite pre-commit, post-commit and options hooks
go-gitea/gitea pull request #1376
Opened 2017-03-23 08:52 UTC by philfry

See #1257

2017-03-23 08:56 UTC, philfry commented
I kept the version name `v26` to avoid conflicts with future merges, even though it breaks the consistency of numbering the migrations. Any thoughts on this -- shall I rename it back to `v23`?

2017-03-23 13:03 UTC, lunny commented
keep v26 or change it to v23 will both make it impossible to upgrade from v1.1.1 to v1.2.

2017-03-23 14:21 UTC, strk requested changes
We cannot change db version in stable branches

2017-03-23 14:21 UTC, strk commented on models/migrations/migrations.go
> +	NewMigration("generate and migrate repo and wiki Git hooks", generateAndMigrateGitHookChains),
No migrations can be allowed in 1.1 branch

2017-03-23 17:25 UTC, philfry commented
Ok, so no migration for 1.1. I removed the questionable parts.

2017-03-23 22:40 UTC, strk commented
LGTM

2017-03-24 01:16 UTC, lunny commented
So we have to add a notice on Release Notes that if he cannot work on other script type hook, he should click the `resync public key ...` button on the Admin Panel. @tboerger 
Then LGTM

2017-03-24 01:34 UTC, bkcsoft commented
This is another reason why I want to change the way migrations work 🙂 

Add a release-file in `changelog/v1.1.1` please. Format in #1298

2017-03-24 03:16 UTC, bkcsoft commented
Oh, I found a new use for my `changelog`-script... generate entries for the blog-post, with _notes_ 😂

2017-03-28 07:47 UTC, lunny commented
@bkcsoft let's move the changelog thing after v1.2

2017-03-28 07:48 UTC, merged