[WIP] Generate swagger json
go-gitea/gitea pull request #1402
Opened 2017-03-28 22:20 UTC by sapk

Use https://github.com/go-swagger/go-swagger with go generate to (auto-)build public/swagger.json

Related : #194 

I will fill missing API descriptions. For the responses descriptions, tags must be add to sdk repo (so in a other PR).

2017-04-14 02:18 UTC, lunny commented
Maybe we need an API docs site? Or a link on docs.gitea.io?

2017-04-14 07:29 UTC, sapk commented
Once fully implented we could use swagger ui for presentation. There is two choice possible :
- We use a remote one. This require to have CORS enable to be able to execute test request from ui. (example : http://petstore.swagger.io/)
- We use expose a swagger ui inside gitea and we have complete access to api and docs is accessible alongside gitea. 

As global documentation we could start a docker containing swagger ui (allready avalaibe) for try.gitea.io : https://github.com/swagger-api/swagger-ui

2017-04-14 08:29 UTC, sapk commented
I think that I will simply copy https://github.com/swagger-api/swagger-ui/tree/master/dist into public/assets this will provide swagger-ui on all instance.

2017-04-14 13:03 UTC, lunny commented
@sapk so add new `make` subcommand is enough?

2017-04-14 13:08 UTC, sapk commented
@lunny For generating swagger.json, I added a go generate here :
https://github.com/go-gitea/gitea/pull/1402/files#diff-2620fdbeeb83ce43692534e6c2c39452R5

So **make generate** will update it and place it under public folder.

For swagger-ui, I am thinking of adding a other step to **assets**

2017-04-14 13:14 UTC, sapk commented
In parallel, I will PR to fix little things like go-gitea/go-sdk#50 (it will need a PR in gitea also) to put all data structure under go-sdk and add missing api request. A other PR to go-gitea/go-sdk will be added to add swagger comment to api response and params.

This PR is a long running one to complete ^^. It will maybe need a second pass to adjust comments but the base will be there.

2017-04-14 13:15 UTC, lunny commented
Or maybe we can add a link on the bottom or top on Gitea named `API` to the API docs home page.

2017-04-18 05:48 UTC, bkcsoft requested changes

2017-04-18 05:48 UTC, bkcsoft commented on Makefile
> +	sed -i "s/http:\/\/petstore.swagger.io\/v2\/swagger.json/..\/..\/swagger.v1.json/g" public/assets/swagger-ui/index.html
maybe use `"s;https://...;...;g"` instead for readability?

2017-04-18 05:48 UTC, bkcsoft commented on Makefile
> +	rm -Rf /tmp/swagger-ui
Just download a tar.gz release instead. We shouldn't depend on latest master being functional

2017-04-18 05:48 UTC, bkcsoft commented on routers/api/v1/misc/markdown.go
>  // see https://github.com/gogits/go-gogs-client/wiki/Miscellaneous#render-an-arbitrary-markdown-document
Maybe update the doc links while you're at it :)

2017-04-18 05:48 UTC, bkcsoft commented on routers/api/v1/misc/markdown.go
>  // see https://github.com/gogits/go-gogs-client/wiki/Miscellaneous#render-an-arbitrary-markdown-document
Or remove them since they now become redundant 😅

2017-04-18 05:48 UTC, bkcsoft commented on vendor/vendor.json
> +			"origin": "github.com/sapk-fork/gitea-go-sdk/gitea",
This needs to be fixed before merge :)

2017-04-18 05:50 UTC, bkcsoft commented
Actually, would it make sense to have this in `go-gitea/sdk` instead?

2017-04-18 21:05 UTC, sapk commented on vendor/vendor.json
> +			"origin": "github.com/sapk-fork/gitea-go-sdk/gitea",
Yes this temporary and will be added in a PR in sdk. All the input and output format (used by api) are in sdk and I have already done one PR to move a struct in gitea to sdk.

2017-04-18 21:26 UTC, sapk commented on Makefile
> +	sed -i "s/http:\/\/petstore.swagger.io\/v2\/swagger.json/..\/..\/swagger.v1.json/g" public/assets/swagger-ui/index.html
I am not a big expert in sed. ^^

2017-04-19 05:13 UTC, lunny commented
Is this still WIP?

2017-04-19 10:06 UTC, sapk commented
@lunny yes because it is missing some api url and it need a PR in sdk for all format response and request. But you can review tooling around it like Makefile and the only changes that will append next are swagger comment so It will be ready to merge when complete.

2017-04-19 11:56 UTC, sapk commented on Makefile
> +	rm -Rf /tmp/swagger-ui
I use git tag now to fix the version. (less things to change ^^)

2017-04-29 09:47 UTC, lunny commented
@sapk maybe move this to v1.3?

2017-04-29 10:28 UTC, sapk commented
@lunny There is two possibility : 
 - Push it in v1.2, everything is working it just need to doc (add comment) to the not yet documented API in other(s) PR.
 - Wait v1.3 to have complete documentation.

2017-04-29 10:50 UTC, bkcsoft commented
@lunny @sapk For API-docs I'm actually fine with having partial docs for a while. Better than to have no docs at all 😅

2017-04-29 10:51 UTC, bkcsoft commented
This will have my LG-TM once the gogs docs links are gone 🙂

2017-04-29 11:19 UTC, JonasFranzDEV commented
The swagger file is not complete. Some parts of the API are missing like the issue management.

2017-04-29 11:30 UTC, sapk commented
@JonasFranzDEV That what I say ^^
@bkcsoft ok I will clean this up for fully documented in swagger

2017-04-29 22:41 UTC, sapk commented
I rebase/squash all changes into a fully working version. I vendor go-gitea/go-sdk#53 in the wait of it validation so that this PR is working for validation also. I will revert it back as soon that go-gitea/go-sdk/pull/53 is merged.

For testing, just build gitea like always, start it, and go to `http://localhost:3000/swagger`

Fix/Hack that I have implemented : (This is if someone has a better/cleaner idea)
- Swagger-ui doesn't support recursive deps like GPGKey that contain sub-GPGKey that contain .... -> I use a `sed`in go generate to set sub-GPGKey as object.

Improvements to be done in other PR : 
- Add all missing API
- Improve documentation of parameters and responses. (For example : add a regex for armored key params)
- Add params for in url/path params. As of now they are displayed but we need struct to link them to params in code and be able to set them in swagger-ui.

Over all, this PR should not have an big impact on code functionality as it is mostly comments.

2017-04-30 05:45 UTC, lunny commented
@sapk I like first chosen. So is it ready to review and merge?

2017-04-30 09:10 UTC, sapk commented
@lunny Yes, the only thing that bother me is the little fix/hack for recursive structure not supported by swagger-ui. (describe in my previous comment)

2017-04-30 15:18 UTC, KangoV commented
Which version are you using? We've just switched to using swagger-ui v3.0.7. Has a much nicer look. This is getting ready for OpenAPI v3.0 later in the year: http://swagger.io/new-swagger-ui-and-swagger-editor/.
It's also much easier to integrate.

2017-04-30 15:44 UTC, sapk commented
@KangoV I have added swagger-ui v3.0.7 (get via makefile). I used go-swagger to generate the JSON from code comments.

2017-05-02 09:09 UTC, lunny commented
Is this ready for review?

2017-05-02 11:17 UTC, sapk commented
@lunny yes like I said two days ago ^^

2017-05-02 11:41 UTC, lunny commented
LGTM

2017-05-02 13:34 UTC, bkcsoft approved these changes

2017-05-02 13:34 UTC, bkcsoft commented
LGTM

2017-05-02 13:35 UTC, bkcsoft commented
make LG-TM work

2017-05-02 13:35 UTC, merged