WIP: Add filter for Sensitive words
go-gitea/gitea pull request #14049
Opened 2020-12-18 09:37 UTC by lunny

This PR implements an optional feature to detect sensitive words via DFA algorithm. 

Once enabled.

- [ ] sensitive words on Issue/pr/comment title and content will be replaced by **
- [x] sensitive words on commit push will be rejected

2020-12-18 21:01 UTC, silverwind commented
>  sensitive words on commit push will be rejected

does it have to reject? can't we alter the message?

2020-12-18 21:17 UTC, mrsdizzie commented
Can't this already be done through adding hooks and custom markdown render? Does this really need to be built into gitea?

2020-12-19 06:15 UTC, lunny commented
> Can't this already be done through adding hooks and custom markdown render? Does this really need to be built into gitea?

Hook can only affect git push but not issues, comments. This PR can control all inputs placement with the same setting.

2020-12-19 06:17 UTC, lunny commented
> > sensitive words on commit push will be rejected
> 
> does it have to reject? can't we alter the message?

Did you mean send message to the pusher or to site administrator?

2020-12-19 14:38 UTC, CirnoT commented
> > sensitive words on commit push will be rejected
> 
> does it have to reject? can't we alter the message?

It actually goes through whole diff and looks for "sensitive" words in patch itself.

I'm sorry but I don't think we need this in Gitea, nor the current implementation seems sane enough to merge it. The amount of false-positives catched in patch (including old code, not only new) will be enormous.

2020-12-19 14:41 UTC, CirnoT requested changes

2020-12-19 14:41 UTC, CirnoT commented on routers/private/hook.go
> +		if setting.WordsFilter.Enabled {
The whole code here will catch and rejected instances of OLD code, causing lot of false-positives and ??? reactions from commiter.

Also this will fail on migrations and mirrors and is slow as hell.

2020-12-19 14:45 UTC, CirnoT commented on routers/private/hook.go
> +		if setting.WordsFilter.Enabled {
Just to clarify: You can't simply rely on `+` to catch only new code, there are numerous instances when old code will show up as so

2020-12-19 14:48 UTC, CirnoT commented on routers/private/hook.go
> +		if setting.WordsFilter.Enabled {
Oh it will also catch lot of false positives on stuff like lockfiles, vendor dirs etc.

2020-12-19 15:00 UTC, lunny commented on routers/private/hook.go
> +		if setting.WordsFilter.Enabled {
@CirnoT As I know, The git diff line should begin with `+`, `-`, ` `, `+++`, `---`. What's old code did you mean?

2020-12-19 15:05 UTC, CirnoT commented on routers/private/hook.go
> +		if setting.WordsFilter.Enabled {
For simplest example, imagine fixing indentation.

2020-12-19 15:10 UTC, CirnoT commented on routers/private/hook.go
> +		if setting.WordsFilter.Enabled {
Also imagine adding `whitelist` to filter and having future commits updating vendor dir blocked because one dependency 3 layers deep used it. That and lack of any control per repository shows that this PR is not in any usable state aside from simple PoC. At minimum, it should skip over generated and vendor files.

2020-12-19 15:11 UTC, lunny commented
> > > sensitive words on commit push will be rejected
> > 
> > 
> > does it have to reject? can't we alter the message?
> 
> It actually goes through whole diff and looks for "sensitive" words in patch itself.
> 
> I'm sorry but I don't think we need this in Gitea, nor the current implementation seems sane enough to merge it. The amount of false-positives catched in patch (including old code, not only new) will be enormous.

This is an optional feature and default is disabled. The user has the freedom to enable or not enable this feature, just like so many other features.

For public code host sites, pornography, gamble and drugs information and some other informations should be rejected by country laws. This let's that possible out-of-the-box.

2020-12-19 15:13 UTC, CirnoT commented
Imagine hosting public Git service and blocking code because `sex` appears in code.
Imagine hosting public Git service and blocking https://easylist.to/ from using it because it has URL for gambling site.

2020-12-19 15:23 UTC, lunny commented
`sex` is really not a sensitive word that should not be blocked.

Even chrome browser will indicate some URL may harm to your computer. But URL analysis is not the responsibility of this PR.

And any idea about to manage a public site to disallow those informations?

2020-12-19 22:00 UTC, zeripath commented
I have to say I have deep reservations about this proposed PR and the proposed methods for how it does things. I don't necessarily think that this is something that should be in Gitea. 

We could certainly add all the necessary hooks that could be used to allow this kind of filtering - as they would likely be helpful elsewhere - for example automatic mirroring of comments, maximum number of comments per hour, etc. I also suspect that there is plenty of software that could do the filtering detection without putting it in Gitea directly. The only benefit to placing code in Gitea directly to do this is if the intention is to do the filtering badly - we don't have expertise in this kind of thing.

It's difficult because whilst I am keenly aware of why you need this and why others from different countries, including my own, need this, it makes me deeply uncomfortable.

2020-12-20 19:19 UTC, mrsdizzie commented
> > Can't this already be done through adding hooks and custom markdown render? Does this really need to be built into gitea?
> 
> Hook can only affect git push but not issues, comments. This PR can control all inputs placement with the same setting.

You can use the same script for hook and as external markdown renderer which will cover issues/comments. Heres a really simple example that covers issues/comments and hook without adding any new code to Gitea at all:

```perl
#!/usr/bin/perl

use strict;
use warnings;
use Getopt::Long;

my $hook = '';    # if run from hook
GetOptions( 'hook' => \$hook );

#badwords.txt:
# sex
# gambling
# pornhub.com

my $filename = '/Users/mrsdizzie/badwords.txt';
open( my $fh, '<:encoding(UTF-8)', $filename )
    or die "Could not open file '$filename' $!";

chomp( my @badWords = <$fh> );

while ( my $line = <> ) {
    if ($hook) {
        if ( grep( $line =~ /$_/, @badWords ) ) {
            die "commit rejected because of bad words\n";
        }
    }
    else {
        $line =~ s/$_/****/g for @badWords;
        print "$line";
    }
}

}
```

```ini
[markup.markdown]
ENABLED         = true
FILE_EXTENSIONS = .md,.markdown
RENDER_COMMAND  = /Users/mrsdizzie/filter.pl
```


https://user-images.githubusercontent.com/1669571/102722066-a392ca80-42cc-11eb-82ec-58265d37c8b2.mp4

 pre-receive hook
```bash
#!/bin/bash
set -e
echo "pre-receive HOOK"
while read old_sha new_sha refname
do
    git diff "$old_sha" "$new_sha" | /Users/mrsdizzie/untitled.pl --hook
done
exit 0
```

https://user-images.githubusercontent.com/1669571/102722094-cc1ac480-42cc-11eb-8618-4948211efa04.mp4

A solution to this problem has to be very customizable to each instance and it doesn't make sense to do filtering inside Gitea itself -- as an example this 30 line script seems to do about the same as the thousands+ line change to Gitea and is much more easily customizable by any users.

There are probably improvements we could do on the Gitea side to make adding things like this even better, like allow custom render to be used on areas that aren't already processed as markdown so they could be filtered if needed.

2020-12-20 19:21 UTC, mrsdizzie commented
I also think this use case could be a good example to show off the features git and gitea already have for adding additional features certain users might need

2020-12-21 02:45 UTC, DuckDuckWhale commented
I also think it is not a good idea to add this to Gitea. Tom Scott has an excellent video on this topic: [Why Web Filters Don't Work: Penistone and the Scunthorpe Problem](https://www.youtube.com/watch?v=CcZdwX4noCE)

A simple word filter is not a good solution to this problem. People can easily guess the words from the surrounding context even if they are removed, and a slight variation would still pass the filter and making it completely ineffective. On top of the collateral damage it would cause to the cases where the usage is of good motive (making it harder to read and reminding the user of a bad meaning), it could even agitate those who are determined to use these words and cause an opposite effect than the one intended. Broadening the match would cause even more collateral damage. In my opinion this is so ineffective and has so many side effects that it is not even worth adding this option, as those who see the option and enable it without giving a second thought would most likely not understand its consequences.

2020-12-21 05:39 UTC, lunny commented
> > > Can't this already be done through adding hooks and custom markdown render? Does this really need to be built into gitea?
> > 
> > 
> > Hook can only affect git push but not issues, comments. This PR can control all inputs placement with the same setting.
> 
> You can use the same script for hook and as external markdown renderer which will cover issues/comments. Heres a really simple example that covers issues/comments and hook without adding any new code to Gitea at all:
> 
> ```perl
> #!/usr/bin/perl
> 
> use strict;
> use warnings;
> use Getopt::Long;
> 
> my $hook = '';    # if run from hook
> GetOptions( 'hook' => \$hook );
> 
> #badwords.txt:
> # sex
> # gambling
> # pornhub.com
> 
> my $filename = '/Users/mrsdizzie/badwords.txt';
> open( my $fh, '<:encoding(UTF-8)', $filename )
>     or die "Could not open file '$filename' $!";
> 
> chomp( my @badWords = <$fh> );
> 
> while ( my $line = <> ) {
>     if ($hook) {
>         if ( grep( $line =~ /$_/, @badWords ) ) {
>             die "commit rejected because of bad words\n";
>         }
>     }
>     else {
>         $line =~ s/$_/****/g for @badWords;
>         print "$line";
>     }
> }
> 
> }
> ```
> 
> There are much better filtering programs and scripts you could use in the same way, but this is just a very simple example.
> 
> ```ini
> [markup.markdown]
> ENABLED         = true
> FILE_EXTENSIONS = .md,.markdown
> RENDER_COMMAND  = /Users/mrsdizzie/filter.pl
> ```
> 
>  badword.mp4 
> pre-receive hook
> 
> ```shell
> #!/bin/bash
> set -e
> echo "pre-receive HOOK"
> while read old_sha new_sha refname
> do
>     git diff "$old_sha" "$new_sha" | /Users/mrsdizzie/untitled.pl --hook
> done
> exit 0
> ```
> 
>  badcommit.mp4 
> A solution to this problem has to be very customizable to each instance and it doesn't make sense to do filtering inside Gitea itself -- as an example this 30 line script seems to do about the same as the thousands+ line change to Gitea and is much more easily customizable by any users.
> 
> There are probably improvements we could do on the Gitea side to make adding things like this even better, like allow custom render to be used on areas that aren't already processed as markdown so they could be filtered if needed.

Thanks!

2020-12-21 05:39 UTC, closed without merging