[WIP] Sync interval specifed as duration string
go-gitea/gitea pull request #1407
Opened 2017-03-29 10:32 UTC by cez81

My attempt on solution for #1140. Would love to hear your comments if I'mon the right track?

Mirror.Interval is changed from int to string so that would require a migration script?

2017-03-29 10:39 UTC, strk commented
Changing a table column type would require a migration, yes.
Keeping the integer but changing semantic (for example: have them interpreted as minutes) would also require a migration.

I guess you'll want admins to be able to limit the minimum frequency of migrations (if allowed at all).

2017-03-29 11:38 UTC, lunny requested changes
And it should have a minimal duration, for example `1m` ?

2017-03-29 11:38 UTC, lunny commented on models/repo.go
> +		duration, err := time.ParseDuration(setting.Mirror.DefaultInterval)
compitable?

2017-03-29 12:00 UTC, geek1011 commented on models/repo.go
> +		duration, err := time.ParseDuration(setting.Mirror.DefaultInterval)
Also, just a note, time.ParseDuration accepts negative durations. This should be checked for.

2017-03-29 19:26 UTC, cez81 commented
I have taken your comments on board and done a few changes.
* Added a new setting mirror.MinInterval with 10 minutes as default
* MinInterval must be >1 minute or defaults to 1 minute
* DefaultInterval must be > MinInterval or defaults to 8h
* Set Interval must be >MinInterval
* Changed back to storing the interval as int in the database (store as time.Duration ie nanoseconds)

2017-03-30 00:59 UTC, lunny commented on modules/setting/setting.go
> +	Mirror.MinInterval = sec.Key("MIN_INTERVAL").MustDuration(time.Second * 55)
why is `time.Secdon * 55`?

2017-03-30 06:12 UTC, cez81 commented on modules/setting/setting.go
> +	Mirror.MinInterval = sec.Key("MIN_INTERVAL").MustDuration(time.Second * 55)
Oops they shouldn't be there. Removed as MustDuration will return 0 on error and that will be picked up with the following if cases.

2017-03-30 10:07 UTC, cez81 commented on modules/setting/setting.go
> +	Mirror.MinInterval = sec.Key("MIN_INTERVAL").MustDuration()
Hmm somethings not right with this. Doesn't read default from built in app.ini

2017-04-06 03:22 UTC, lunny requested changes

2017-04-06 03:22 UTC, lunny commented on models/migrations/v27.go
> +		_, err := x.Id(mirror.ID).Cols("interval").Update(mirror)
This may needs a transaction.

2017-04-06 03:22 UTC, lunny commented on routers/repo/setting.go
> +			ctx.Handle(500, "UpdateMirror", err)
This should show a hint not give a 500.

2017-04-06 03:23 UTC, lunny commented
Otherwise LGTM

2017-04-06 08:04 UTC, lunny commented on models/migrations/v27.go
> +	if err := sess.Commit(); err != nil {
```Go
return sess.Commit()
```
is more cleaner.

2017-04-06 08:06 UTC, lunny approved these changes

2017-04-08 14:17 UTC, geek1011 commented
LGTM

2017-04-08 15:27 UTC, merged