[Notifications Step 6] Per issue/PR watch/unwatch
go-gitea/gitea pull request #1410
Opened 2017-03-30 00:13 UTC by andreynering

- Users that don't watch the repo can choose watch a single issue
- Users that watch the repo can choose unwatch a single issue

![watch](https://cloud.githubusercontent.com/assets/7011819/24481925/367a42d2-14c4-11e7-9ea3-b3b36ede1698.png)

![unwatch](https://cloud.githubusercontent.com/assets/7011819/24481930/3e41251c-14c4-11e7-816b-adb2118369dd.png)

2017-03-30 00:24 UTC, pgaskin reviewed
Looks good other than some minor fixes, still need to try testing it.

2017-03-30 00:24 UTC, geek1011 commented on models/issue_watch.go
> +func (iw *IssueWatch) BeforeUpdate() {
Needs a documentation comment

2017-03-30 00:24 UTC, geek1011 commented on models/issue_watch.go
> +func GetIssueWatchers(issueID int64) ([]*IssueWatch, error) {
Needs a documentation comment

2017-03-30 00:24 UTC, geek1011 commented on models/issue_watch.go
> +}
IMO, this should store the time in a variable and use that, to improve the accuracy of the times, and to optimize the code a bit.

2017-03-30 00:24 UTC, geek1011 commented on options/locale/locale_en-US.ini
> +issues.unwatch_issue = Unwatch issue
Maybe subscribe and unsubscribe like github (because it is slightly shorter and more clear)?

2017-03-30 00:24 UTC, geek1011 commented on templates/repo/issue/view_content/sidebar.tmpl
> +							<i class="octicon octicon-megaphone"></i>
Use `octicon-unmute` for consistency.

2017-03-30 00:24 UTC, geek1011 commented on models/issue_watch.go
> +func GetIssueWatchers(issueID int64) ([]*IssueWatch, error) {
Nevermind, you just fixed it

2017-03-30 00:24 UTC, geek1011 commented on models/issue_watch.go
> +func (iw *IssueWatch) BeforeUpdate() {
Nevermind, you just fixed it

2017-03-30 10:07 UTC, strk commented on options/locale/locale_en-US.ini
> +issues.unwatch_issue = Unwatch issue
subscribe/unsubscribe also matches the icon better (which should otherwise be an eye)

2017-03-30 10:12 UTC, strk requested changes
It's great to see this coming. I guess it needs a migration, and would be great to see a unit test for it.

2017-03-30 10:12 UTC, strk commented on models/issue_watch.go
> +package models
copyright header please

2017-03-30 10:12 UTC, strk commented on models/issue_watch.go
> +	iw.UpdatedUnix = time.Now().Unix()
Same here, call time.Now() a single time please

2017-03-30 10:12 UTC, strk commented on routers/repo/issue_watch.go
> +package repo
Copyright header please

2017-03-30 23:24 UTC, andreynering commented
@geek1011 and @strk 

Updated with your suggestions + added unit tests.

2017-03-31 08:44 UTC, appleboy commented on models/issue_watch.go
> +	iw, exists, err = getIssueWatch(x, userID, issueID)
return getIssueWatch(x, userID, issueID)

2017-03-31 08:44 UTC, appleboy commented on models/issue_watch.go
> +	iw, exists, err = getIssueWatch(x, userID, issueID)
otherwise LGTM

2017-03-31 08:45 UTC, appleboy approved these changes

2017-03-31 11:20 UTC, lunny requested changes

2017-03-31 11:20 UTC, lunny commented on models/issue_watch.go
> +func getIssueWatch(e Engine, userID, issueID int64) (iw *IssueWatch, exists bool, err error) {
need a blank line.

2017-03-31 11:20 UTC, lunny commented on models/issue_watch.go
> +func getIssueWatchers(e Engine, issueID int64) (watches []*IssueWatch, err error) {
^

2017-03-31 11:47 UTC, strk requested changes
Great progress, I hope you can fill the final gaps :)

2017-03-31 11:47 UTC, strk commented on models/issue_watch_test.go
> +	assert.NoError(t, err)
Can you also check a user having no entry in issue_watch table here ?
Also, ideally both a user who's watching and one who's not watching the repository containing the issue.

2017-03-31 11:47 UTC, strk commented on models/issue_watch_test.go
> +	assert.Equal(t, 1, len(iws))
Please also check an issue with multiple watchers and check the actual content of the returned slice

2017-03-31 11:50 UTC, lunny commented
otherwise LGTM

2017-04-01 13:06 UTC, andreynering commented
Updated

2017-04-01 13:34 UTC, lunny approved these changes

2017-04-01 13:41 UTC, strk commented
I would still like to see a test with multiple watchers
and something showing how repository watchers affect (or not)
the issue-watch-list retriving function

2017-04-01 13:48 UTC, andreynering commented
@strk The test as is is enough to show that it works as expected.

2017-04-01 14:20 UTC, strk commented
@andreynering is it not expected that the GetIssueWatchers function return the information about who are the watchers ? The test is not checking that. Why don't you want to check that ? Also, is it expected that an issue can have more than a single watcher ? I find those to be legit cases to test. I've no problem with this being merged as is (LGTM) but as you are on it it would be nice to get a better test coverage.

2017-04-01 18:12 UTC, merged

2017-04-01 18:13 UTC, andreynering commented
@strk Testing the data would makes sense for data we are saving in the database.

But in this case, we would be testing data present on test fixtures. This don't makes sense, we know the data on fixtures is right.