API: Make BasicAuth Header & Prefix case insensitive
go-gitea/gitea pull request #14106
Opened 2020-12-22 05:01 UTC by 6543

Before:
* `curl -X POST "http://gitea.com/api/v1/... -H  "accept: application/json" -H  "Authorization: Basic dTE6MTIzMTIz" ...`

After:
 * `curl -X POST "http://gitea.com/api/v1/... -H  "accept: application/json" -H  "authorization: Basic dTE6MTIzMTIz" ...`
 * `curl -X POST "http://gitea.com/api/v1/... -H  "accept: application/json" -H  "authorization: basic dTE6MTIzMTIz" ...`
 * `curl -X POST "http://gitea.com/api/v1/... -H  "accept: application/json" -H  "Authorization: basic dTE6MTIzMTIz" ...`
 * `curl -X POST "http://gitea.com/api/v1/... -H  "accept: application/json" -H  "Authorization: Basic dTE6MTIzMTIz" ...`
 * `curl -X POST "http://gitea.com/api/v1/... -H  "accept: application/json" -H  "Authorization: bAsIc dTE6MTIzMTIz" ...`
 * ...

2020-12-22 05:05 UTC, lunny commented on modules/auth/sso/basic.go
> +	if len(auths) != 2 || strings.ToLower(auths[0]) != "basic" {
`(auths[0] != "Basic" && auths[0] != "basic")` Otherwise it will allow `bAsic`.

2020-12-22 05:09 UTC, 6543 commented on modules/auth/sso/basic.go
> +	if len(auths) != 2 || strings.ToLower(auths[0]) != "basic" {
```suggestion
	if len(auths) != 2 || (auths[0] != "Basic" && auths[0] != "basic") {
```

2020-12-22 05:51 UTC, lunny approved these changes

2020-12-22 07:42 UTC, lafriks requested changes, later dismissed
See https://play.golang.org/p/crtMhYsMDGY

2020-12-22 07:42 UTC, lafriks commented on modules/auth/sso/basic.go
> +		baHead = ctx.Req.Header.Get("authorization")
This is not needed. Header.Get is case insensitivie

2020-12-22 07:46 UTC, lafriks commented on modules/auth/sso/basic.go
> +		baHead = ctx.Req.Header.Get("authorization")
It does already work with lowercase header name:
![image](https://user-images.githubusercontent.com/165205/102862953-8d0a8180-443a-11eb-80f2-383951e71152.png)

2020-12-22 16:02 UTC, 6543 commented
@lafriks done

2020-12-23 18:08 UTC, zeripath approved these changes

2020-12-23 19:52 UTC, 6543 commented
:rocket:

2020-12-23 19:52 UTC, merged