Add hyperlink markup for Reviewed-on links on Pull Request textareas
go-gitea/gitea pull request #14338
Opened 2021-01-14 13:43 UTC by juanpablo-santos

At work we have some webhooks that use the data submitted by the PR textarea to add a comment to a Jira instance. We also decorate the text submitted with some additional jira-markup, so it appears inside a panel, with all lines converted to italic (prepending and appending a `_` character to each line, among other things - we'd like to not touch this process if possible).

However, the `Reviewed-on:` lines don't get correctly formatted, as Jira thinks that the `_` ending character is part of the URL. Adding the brackets around the url is enough to fix our issue and get those lines correctly formatted, and doesn't seem to affect gitea, as the url is rendered anyways, no matter if it's enclosed by brackets or not. 

Currently we use a custom template for this file, but that forces us to keep the file in sync every time we upgrade, which is not ideal, hence the PR (no issue created for it as it is a trivial change).

txs,
juan pablo

2021-01-14 13:46 UTC, jace788 approved these changes

2021-01-14 13:47 UTC, jace788 approved these changes

2021-01-14 13:47 UTC, jace788 approved these changes

2021-01-14 14:00 UTC, jace788 approved these changes

2021-01-14 14:45 UTC, tomaswarynyca approved these changes

2021-01-14 16:26 UTC, lafriks approved these changes

2021-01-19 05:40 UTC, CirnoT commented
That is a very-very specific case you got there and this change breaks previous behavior that more users (than only you) might rely on, and it also breaks convention where other entries are not enclosed in brackets.

It does also look quite weird to me:
> Reviewed-on: [#995]
> Reviewed-on: #995

I would however consider a change to just use `#995` instead of full link.

2021-01-19 05:47 UTC, lunny commented
Yes, please don't. When review it on git command, it's wired.

2021-01-19 05:48 UTC, lunny requested changes
The change will affect the messages on git command line.

2021-01-19 21:42 UTC, juanpablo-santos commented
Hi @CirnoT , @lunny 

yeah, this PR is for a very specific use case. I was unaware that it would affect messages on the git command line; in fact I thought that it was pretty much harmless / self-contained, so that's why I tried with a PR. Thanks for reviewing it anyways :-) (also thanks to other people who did that!)

As for using `#995` instead of the full link, I'd prefer the latter: it's easier to see without hovering into the issue where it cames from., whereas with the short form you have to hover to see from which repo does the issue came from. Hence, I think it's better if I close the PR, and just let the actual behaviour as it is

best regards,

2021-01-19 21:42 UTC, closed without merging