Enable race detector for CI
go-gitea/gitea pull request #1441
Opened 2017-04-04 08:20 UTC by typeless

Depends on #1438 

For #1430

2017-04-04 08:22 UTC, tboerger commented
I thought more about a flag like ENABLE_RACE or something like that

2017-04-04 08:33 UTC, typeless commented
@tboerger I am okay with either way. We can have the final decision discussed in #1430. I'll change the PRs accordingly.

2017-04-04 08:37 UTC, strk commented
LGTM

2017-04-04 08:43 UTC, typeless commented
I have checked 'Allow edits from maintainers.'.  You know 😄 
Otherwise, we need a follow-up PR to update the signature.

2017-04-11 13:32 UTC, appleboy commented
LGTM

2017-04-11 13:32 UTC, appleboy approved these changes

2017-04-18 20:44 UTC, strk commented
@appleboy can you help with the signature ? @tboerger mentioned you as his preferred successor as he's stepping down (mentioned on Gitter)

2017-04-19 07:26 UTC, strk commented
It is the coverage step that fails, due to:
```
Unable to authenticate user. Error fetching user. GET https://api.github.com/user: 401 Bad credentials []
```

Is that what the signature is for ?
Was there a plan to *drop* the signature requirement @appleboy ?

2017-04-19 07:47 UTC, appleboy commented
@strk I don't have permission to update the sig file. @lunny can help this.

2017-04-30 05:44 UTC, strk commented
The mysql check fails on drone with:
```
undefined reference to `__libc_malloc'
race_linux_amd64.sy
```

Some linker flags missing @typeless ?

2017-04-30 06:31 UTC, appleboy commented
@lunny Need to resign drone config.

2017-04-30 09:59 UTC, lunny commented
build failed. what's this `collect2: error: ld returned 1 exit status`

2017-05-03 01:16 UTC, bkcsoft commented
Is the drone.sig updated? otherwise put `status/blocked` on this :sli

2017-05-03 01:41 UTC, lunny commented
@bkcsoft yes, updated

2017-05-25 02:24 UTC, lunny commented
@typeless any news?

2017-05-25 02:49 UTC, typeless commented
It looks that glibc is absent. Alpine Linux uses musl libc which is probably incompatible (or it only supports static linking?)

Also I found this https://github.com/golang/go/issues/9918.

2017-05-25 03:00 UTC, lunny commented
So let's move it to v1.x.x

2017-09-15 15:30 UTC, lunny commented
need rebase

2017-09-18 06:18 UTC, typeless commented
@lunny Done.

2017-11-21 05:56 UTC, lunny commented
CI still failed.

2017-12-24 14:24 UTC, strk commented
From build log:
```
# runtime/race
race_linux_amd64.syso: In function `__sanitizer::InternalAlloc(unsigned long, __sanitizer::SizeClassAllocatorLocalCache<__sanitizer::SizeClassAllocator32<0ul, 140737488355328ull, 0ul, __sanitizer::SizeClassMap<3ul, 4ul, 8ul, 17ul, 64ul, 14ul>, 20ul, __sanitizer::TwoLevelByteMap<32768ull, 4096ull, __sanitizer::NoOpMapUnmapCallback>, __sanitizer::NoOpMapUnmapCallback> >*, unsigned long)':
gotsan.cc:(.text+0x16e1): undefined reference to `__libc_malloc'
race_linux_amd64.syso: In function `__sanitizer::GetArgv()':
gotsan.cc:(.text+0x4543): undefined reference to `__libc_stack_end'
```

@typeless still willing to fix this ?

2017-12-25 02:17 UTC, typeless commented
@strk It seems that we have to wait for the upstream fix according to https://github.com/golang/go/issues/9918.

2018-09-07 02:30 UTC, lunny commented
@typeless could you rebase this PR?

2018-09-07 05:55 UTC, typeless commented
@lunny Done.

2018-09-07 08:14 UTC, lunny commented
@typeless  But this build binary will be included in docker?

2018-09-07 08:41 UTC, typeless commented
@lunny Yeah, it is undesirable to enable this in production. I didn't find any obvious way to distinguish CI mode in the Makefile or `.drone.yml`. Do you have any suggestions?

2018-09-08 15:09 UTC, lunny requested changes
race flag should not be in docker.

2018-10-26 03:12 UTC, typeless commented
I want to add a simple `modules/race` package to get if `-race` is enabled at runtime. Otherwise, it is hard to tell whether race detector is actually working.

2018-10-26 04:04 UTC, typeless commented
Not ready yet. I need the `race detector enabled` string shown on the log when `make test-sqlite`.

2018-10-26 06:18 UTC, typeless commented
This PR is ready. Currently, I based it on https://github.com/go-gitea/gitea/pull/5174. So it better be merged after that.

2018-10-27 14:52 UTC, lunny commented
@ethantkoenig data race detected on issue indexer

```
WARNING: DATA RACE
Write at 0x00c000030de0 by main goroutine:
  code.gitea.io/gitea/vendor/github.com/ethantkoenig/rupture.(*singleIndexFlushingBatch).Flush()
      /go/src/code.gitea.io/gitea/vendor/github.com/blevesearch/bleve/index/index.go:239 +0x103
  code.gitea.io/gitea/models.populateIssueIndexer()
      /go/src/code.gitea.io/gitea/models/issue_indexer.go:41 +0x496
  code.gitea.io/gitea/modules/indexer.InitIssueIndexer()
      /go/src/code.gitea.io/gitea/modules/indexer/issue.go:66 +0x1d9
  code.gitea.io/gitea/models.InitIssueIndexer()
      /go/src/code.gitea.io/gitea/models/issue_indexer.go:21 +0x3e
  code.gitea.io/gitea/routers.GlobalInit()
      /go/src/code.gitea.io/gitea/routers/init.go:72 +0x768
  code.gitea.io/gitea/integrations.initIntegrationTest()
      /go/src/code.gitea.io/gitea/integrations/integration_test.go:138 +0x4b3
  code.gitea.io/gitea/integrations.TestMain()
      /go/src/code.gitea.io/gitea/integrations/integration_test.go:40 +0x44
  main.main()
      _testmain.go:278 +0x221

Previous read at 0x00c000030de0 by goroutine 49:
  code.gitea.io/gitea/vendor/github.com/blevesearch/bleve/index/upsidedown.(*UpsideDownCouch).Batch.func1()
      /go/src/code.gitea.io/gitea/vendor/github.com/blevesearch/bleve/index/upsidedown/upsidedown.go:814 +0x52

Goroutine 49 (finished) created at:
  code.gitea.io/gitea/vendor/github.com/blevesearch/bleve/index/upsidedown.(*UpsideDownCouch).Batch()
      /go/src/code.gitea.io/gitea/vendor/github.com/blevesearch/bleve/index/upsidedown/upsidedown.go:813 +0x27f
  code.gitea.io/gitea/vendor/github.com/blevesearch/bleve.(*indexImpl).Batch()
      /go/src/code.gitea.io/gitea/vendor/github.com/blevesearch/bleve/index_impl.go:304 +0xfd
  code.gitea.io/gitea/vendor/github.com/ethantkoenig/rupture.(*singleIndexFlushingBatch).Flush()
      /go/src/code.gitea.io/gitea/vendor/github.com/ethantkoenig/rupture/flushing_batch.go:61 +0x96
  code.gitea.io/gitea/models.populateIssueIndexer()
      /go/src/code.gitea.io/gitea/models/issue_indexer.go:41 +0x496
  code.gitea.io/gitea/modules/indexer.InitIssueIndexer()
      /go/src/code.gitea.io/gitea/modules/indexer/issue.go:66 +0x1d9
  code.gitea.io/gitea/models.InitIssueIndexer()
      /go/src/code.gitea.io/gitea/models/issue_indexer.go:21 +0x3e
  code.gitea.io/gitea/routers.GlobalInit()
      /go/src/code.gitea.io/gitea/routers/init.go:72 +0x768
  code.gitea.io/gitea/integrations.initIntegrationTest()
      /go/src/code.gitea.io/gitea/integrations/integration_test.go:138 +0x4b3
  code.gitea.io/gitea/integrations.TestMain()
      /go/src/code.gitea.io/gitea/integrations/integration_test.go:40 +0x44
  main.main()
      _testmain.go:278 +0x221
==================
==================
WARNING: DATA RACE
Read at 0x00c0001ec090 by goroutine 52:
  code.gitea.io/gitea/vendor/github.com/blevesearch/bleve/index/upsidedown.(*UpsideDownCouch).Batch.func1()
      /go/src/code.gitea.io/gitea/vendor/github.com/blevesearch/bleve/index/upsidedown/upsidedown.go:814 +0x52

Previous write at 0x00c0001ec090 by goroutine 51:
  code.gitea.io/gitea/vendor/github.com/ethantkoenig/rupture.(*singleIndexFlushingBatch).Flush()
      /go/src/code.gitea.io/gitea/vendor/github.com/blevesearch/bleve/index/index.go:239 +0x103
  code.gitea.io/gitea/models.processIssueIndexerUpdateQueue()
      /go/src/code.gitea.io/gitea/models/issue_indexer.go:73 +0x22b

Goroutine 52 (running) created at:
  code.gitea.io/gitea/vendor/github.com/blevesearch/bleve/index/upsidedown.(*UpsideDownCouch).Batch()
      /go/src/code.gitea.io/gitea/vendor/github.com/blevesearch/bleve/index/upsidedown/upsidedown.go:813 +0x27f
  code.gitea.io/gitea/vendor/github.com/blevesearch/bleve.(*indexImpl).Batch()
      /go/src/code.gitea.io/gitea/vendor/github.com/blevesearch/bleve/index_impl.go:304 +0xfd
  code.gitea.io/gitea/vendor/github.com/ethantkoenig/rupture.(*singleIndexFlushingBatch).Flush()
      /go/src/code.gitea.io/gitea/vendor/github.com/ethantkoenig/rupture/flushing_batch.go:61 +0x96
  code.gitea.io/gitea/models.processIssueIndexerUpdateQueue()
      /go/src/code.gitea.io/gitea/models/issue_indexer.go:73 +0x22b

Goroutine 51 (running) created at:
  code.gitea.io/gitea/models.InitIssueIndexer()
      /go/src/code.gitea.io/gitea/models/issue_indexer.go:23 +0xb1
  code.gitea.io/gitea/routers.GlobalInit()
      /go/src/code.gitea.io/gitea/routers/init.go:72 +0x768
  code.gitea.io/gitea/integrations.initIntegrationTest()
      /go/src/code.gitea.io/gitea/integrations/integration_test.go:138 +0x4b3
  code.gitea.io/gitea/integrations.TestMain()
      /go/src/code.gitea.io/gitea/integrations/integration_test.go:40 +0x44
  main.main()
      _testmain.go:278 +0x221
==================
```

2018-10-27 23:19 UTC, typeless commented
@lunny Done.

2018-10-29 06:19 UTC, techknowlogick approved these changes

2018-10-29 06:31 UTC, tboerger commented
Is it only me who thinks it's strange to have an additional version output if the race detector is enabled?

2018-10-29 06:48 UTC, typeless commented
@tboerger It is difficult to tell whether the race detector is enabled or not at runtime. I made several 'false-negative' mistakes due to forgetting to add the `-race` flag during the testing/debugging process. The additional version output was the reaction of that experience.

2018-10-29 06:58 UTC, lunny commented
@typeless  Why we need to know if data race is enabled on runtime?

2018-10-29 07:03 UTC, tboerger commented
I would enable the race detector by default for development :)

Besides that, AFAIK it doesn't matter if you have built a production binary with or without the race flag.

2018-10-29 07:34 UTC, typeless commented
@tboerger I need to think about 'by default for development' a little bit. I still have no clear idea about how we distinguish between 'dev' build and 'prod' build in terms of the structure of the Makefile. Regarding the difference in production, enabling `-race` would make the performance worse. I think it's unlikely that a user would file a performance regression due to an accidentally enabled race detector. But I did make mistakes from time to time that I thought I had turned it on, but I had not, and had to rebuild again to be sure.

@lunny the motivation/rationale is to make the developers' life easier when working with the race-related issues. If the user-visible part is a concern, maybe we can leave only the change about logging message.

2018-10-29 10:05 UTC, tboerger commented
We could enable the race flag by default within the makefile and disable it via env variables within drone. On top of that I would add a note to the docs for building Gitea manually to provide this env variable for production builds.

2018-10-30 01:34 UTC, typeless commented
@tboerger SGTM. Will work on it later.

2018-11-01 05:40 UTC, typeless commented
Done. As per @tboerger 's suggestions.

2018-11-02 01:50 UTC, lunny commented
@typeless could confirm that data race enabled since Drone PASS but we haven't do something.

2018-11-02 02:30 UTC, typeless commented
@lunny Fixed.

2019-05-05 00:44 UTC, lunny commented
@typeless could you resolve the conflicts?

2019-05-05 02:46 UTC, typeless commented
@lunny Done.

2019-07-08 02:26 UTC, lunny commented
@typeless conflicted agin. :)

2019-07-09 06:50 UTC, typeless commented
Any suggestions about how to run build steps depending on events?
The new format does not allow the same step names with different conditions.
An example would be helpful.

2019-09-03 15:41 UTC, lunny commented
@typeless Is this still blocked by https://github.com/go-gitea/gitea/pull/1441#issuecomment-303907947 ? I think maybe we can merge it.

2019-09-04 00:36 UTC, typeless commented
@lunny
if CI can pass I think it has been fixed

2019-09-15 15:20 UTC, lunny commented on .drone.yml
> +    when:
It seems these changes are unnecessary?

2019-09-15 15:21 UTC, lunny commented
LGTM except my comment on https://github.com/go-gitea/gitea/pull/1441/files#r324468107

2019-09-15 15:34 UTC, lunny commented
It seems CI will not be invoked on this PR.

2019-09-16 02:28 UTC, typeless commented
I need a way to disable `-race` when the builds are for releases.
The old way to do it is to add an environment variable `RACE_ENABLED` at the `build` step of the pipeline. I don't think it's correct, given that all release steps ultimately depend on the `build` step.

2019-09-16 05:42 UTC, typeless commented
Disable race detector only when `make release`

2019-09-16 14:02 UTC, lunny commented
It seems race detected on log package.

2019-09-17 12:38 UTC, lunny approved these changes

2019-09-17 14:36 UTC, lunny commented
CI failed because of another problem.

2019-11-02 21:21 UTC, 6543 commented
@typeless @lunny whats the state?

2019-11-03 00:28 UTC, lunny commented
I think this needs more work.

2019-11-03 02:31 UTC, typeless commented
@6543 there are still some data races that are not trivial to fix.

2019-11-15 08:21 UTC, lunny commented
@typeless please resolve the conflicts. I think at least one of the races has been resolved.

2019-11-15 11:37 UTC, typeless commented
@lunny I'll have a look.

2019-11-25 19:21 UTC, zeripath commented
I've pushed a fix for the apparent data race in the test logger. Basically the issue is that the testlogger would print logs to the last test that had `PrintCurrentTest` called - we now prevent that by pushing a queue of `testing.TB` which get popped off with defer.

2019-11-27 02:53 UTC, lunny commented
@zeripath it seems the testlogger datarace is still there.

```
WARNING: DATA RACE
Read at 0x00c003f32343 by goroutine 61:
  testing.(*common).logDepth()
      /usr/local/go/src/testing/testing.go:665 +0xa1
  testing.(*common).Log()
      /usr/local/go/src/testing/testing.go:658 +0x77
  testing.(*T).Log()
      <autogenerated>:1 +0x61
  code.gitea.io/gitea/integrations.(*testLoggerWriterCloser).Write()
      /go/src/code.gitea.io/gitea/integrations/testlogger.go:71 +0x212
  code.gitea.io/gitea/modules/log.(*WriterLogger).LogEvent()
      /go/src/code.gitea.io/gitea/modules/log/writer.go:235 +0x1ed
  code.gitea.io/gitea/integrations.(*TestLogger).LogEvent()
      <autogenerated>:1 +0x4d
  code.gitea.io/gitea/modules/log.(*ChannelledLog).Start()
      /go/src/code.gitea.io/gitea/modules/log/event.go:75 +0x340

Previous write at 0x00c003f32343 by goroutine 96:
  testing.tRunner.func1()
      /usr/local/go/src/testing/testing.go:900 +0x353
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:913 +0x1bb

Goroutine 61 (running) created at:
  code.gitea.io/gitea/modules/log.NewChannelledLog()
      /go/src/code.gitea.io/gitea/modules/log/event.go:60 +0x408
  code.gitea.io/gitea/modules/log.(*Logger).SetLogger()
      /go/src/code.gitea.io/gitea/modules/log/logger.go:33 +0xd1
  code.gitea.io/gitea/modules/log.NewNamedLogger()
      /go/src/code.gitea.io/gitea/modules/log/log.go:62 +0xf3
  code.gitea.io/gitea/modules/log.NewLogger()
      /go/src/code.gitea.io/gitea/modules/log/log.go:45 +0xde
  code.gitea.io/gitea/modules/setting.newLogService()
      /go/src/code.gitea.io/gitea/modules/setting/log.go:270 +0xcaa
  code.gitea.io/gitea/modules/setting.NewLogServices()
      /go/src/code.gitea.io/gitea/modules/setting/log.go:295 +0x47
  code.gitea.io/gitea/modules/setting.NewServices()
      /go/src/code.gitea.io/gitea/modules/setting/setting.go:1060 +0x59
  code.gitea.io/gitea/routers.NewServices()
      /go/src/code.gitea.io/gitea/routers/init.go:47 +0x47
  code.gitea.io/gitea/routers.GlobalInit()
      /go/src/code.gitea.io/gitea/routers/init.go:83 +0x380
  code.gitea.io/gitea/integrations.initIntegrationTest()
      /go/src/code.gitea.io/gitea/integrations/integration_test.go:173 +0x5bf
  code.gitea.io/gitea/integrations.TestMain()
      /go/src/code.gitea.io/gitea/integrations/integration_test.go:58 +0x47
  main.main()
      _testmain.go:2054 +0x343

Goroutine 96 (finished) created at:
  testing.(*T).Run()
      /usr/local/go/src/testing/testing.go:960 +0x651
  testing.runTests.func1()
      /usr/local/go/src/testing/testing.go:1202 +0xa6
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:909 +0x199
  testing.runTests()
      /usr/local/go/src/testing/testing.go:1200 +0x521
  testing.(*M).Run()
      /usr/local/go/src/testing/testing.go:1117 +0x2ff
  code.gitea.io/gitea/integrations.TestMain()
      /go/src/code.gitea.io/gitea/integrations/integration_test.go:84 +0x297
  main.main()
      _testmain.go:2054 +0x343
```

Except that, we have only one datarace which related with indexer.
```
WARNING: DATA RACE
Write at 0x00c005a7a6a0 by goroutine 107:
  github.com/ethantkoenig/rupture.(*singleIndexFlushingBatch).Flush()
      /go/src/code.gitea.io/gitea/vendor/github.com/blevesearch/bleve/index/index.go:310 +0x106
  code.gitea.io/gitea/models.updateRepoIndexer()
      /go/src/code.gitea.io/gitea/models/repo_indexer.go:185 +0x450
  code.gitea.io/gitea/models.processRepoIndexerOperationQueue()
      /go/src/code.gitea.io/gitea/models/repo_indexer.go:374 +0x339

Previous read at 0x00c005a7a6a0 by goroutine 30:
  github.com/blevesearch/bleve/index/upsidedown.(*UpsideDownCouch).Batch.func1()
      /go/src/code.gitea.io/gitea/vendor/github.com/blevesearch/bleve/index/upsidedown/upsidedown.go:815 +0x52

Goroutine 107 (running) created at:
  code.gitea.io/gitea/models.InitRepoIndexer.func1()
      /go/src/code.gitea.io/gitea/models/repo_indexer.go:81 +0xba

Goroutine 30 (finished) created at:
  github.com/blevesearch/bleve/index/upsidedown.(*UpsideDownCouch).Batch()
      /go/src/code.gitea.io/gitea/vendor/github.com/blevesearch/bleve/index/upsidedown/upsidedown.go:814 +0x20c0
  github.com/blevesearch/bleve.(*indexImpl).Batch()
      /go/src/code.gitea.io/gitea/vendor/github.com/blevesearch/bleve/index_impl.go:309 +0x113
  github.com/ethantkoenig/rupture.(*singleIndexFlushingBatch).Flush()
      /go/src/code.gitea.io/gitea/vendor/github.com/ethantkoenig/rupture/flushing_batch.go:61 +0x99
  code.gitea.io/gitea/models.updateRepoIndexer()
      /go/src/code.gitea.io/gitea/models/repo_indexer.go:185 +0x450
  code.gitea.io/gitea/models.processRepoIndexerOperationQueue()
      /go/src/code.gitea.io/gitea/models/repo_indexer.go:374 +0x339
```

2019-11-28 15:55 UTC, lunny commented
It seems datarace was gone. But some test failed.

2019-12-08 11:12 UTC, lunny commented
@typeless Please rebase

2019-12-09 01:58 UTC, typeless commented
@lunny Done

2019-12-09 05:00 UTC, zeripath commented
Please note testlogger never had a data race. 

The race error that we were seeing is because logging occurs between tests - meaning that the test Gitea is doing stuff between tests. That's the data race - not the logger.

The fix I've put in papers over this problem so you don't see it - but the underlying race is still there.

2019-12-09 06:08 UTC, lunny commented
It seems unit test coverage and integration tests didn't enable race detect?

2019-12-09 06:59 UTC, typeless commented
@zeripath noted it.
@lunny fixed (hopefully). 

Btw, the integration tests for migration do not use `-mod=vendor`. I am not sure if that is intended or not.

2019-12-10 14:53 UTC, lunny commented
Since we enable race on test, it is slower than before and some test timeout I think that's why ci failed.

2019-12-11 00:43 UTC, guillep2k commented
> 
> 
> Since we enable race on test, it is slower than before and some test timeout I think that's why ci failed.

The unit test failed because of #8474

2019-12-13 05:37 UTC, typeless commented
Reference https://github.com/etcd-io/bbolt/issues/187

2019-12-13 06:10 UTC, lunny commented
@typeless but we are using go1.13 not go1.14?

2019-12-14 01:33 UTC, lunny commented
I think that because some tests timeout because race detector spend more time than before.

2019-12-14 02:08 UTC, lunny commented
We could change `timeout -s ABRT 20m make test-sqlite` to `timeout -s ABRT 30m make test-sqlite`.

2019-12-14 03:28 UTC, lunny commented
OK. Only one left I think. `integrations/attachement_test.go:55`

```diff
-func TestCreateAnonymousAttachment(t *testing.T) {
-	prepareTestEnv(t)
+func TestCreateAnonymousAttachment(t *testing.T) {
+	prepareTestEnv(t)()
```

```diff
-func TestCreateIssueAttachement(t *testing.T) {
-	prepareTestEnv(t)
+func TestCreateIssueAttachement(t *testing.T) {
+	prepareTestEnv(t)
```

2019-12-14 06:37 UTC, zeripath commented on integrations/attachement_test.go
> +	prepareTestEnv(t)()
```suggestion
	defer prepareTestEnv(t)()
```

2019-12-14 06:37 UTC, zeripath commented on integrations/attachement_test.go
> +	prepareTestEnv(t)()
```suggestion
	defer prepareTestEnv(t)()
```

2019-12-14 06:42 UTC, zeripath commented
`prepareTestEnv(t)` returns a (potentially deferrable) function to cancel its changes. It should be called either as: 

```go
defer prepareTestEnv(t)()
``` 

or as 

```go
cancel = prepareTestEnv(t)
...
cancel()
```

2019-12-14 06:46 UTC, typeless commented on integrations/attachement_test.go
> +	prepareTestEnv(t)()
Done

2019-12-14 06:46 UTC, typeless commented on integrations/attachement_test.go
> +	prepareTestEnv(t)()
Done

2019-12-15 08:38 UTC, lunny commented
Dryrun should not add race detector. Only tests need that.

2019-12-15 23:34 UTC, zeripath commented
Hmm looks like my last PR has likely caused a problem.

2019-12-16 02:20 UTC, typeless commented
@lunny Which CI step do you mean? I suppose that RACE_ENABLED=1 only effects the steps with `go build` or `go test` .

2019-12-16 16:01 UTC, lunny commented
New data races were introduced by recent PRs.

2019-12-28 19:49 UTC, 6543 commented
current status?

2019-12-30 02:12 UTC, typeless commented
@6543 There are still remaining test failures.

2020-01-02 11:43 UTC, typeless commented
The problem is due to https://github.com/go-gitea/gitea/blob/master/integrations/git_test.go#L453-L458  updates the variable while reading by another thread.
What is the reason that `setting.Repository.EnablePushCreateUser` has to be set `false` before calling  https://github.com/go-gitea/gitea/blob/master/integrations/git_test.go#L454?

If what we want is to ensure `EnablePushCreateUSer` to be set `true`, can we just set the variable at the beginning of the test? Hopefully that would avoid the problem.

2020-01-04 09:12 UTC, zeripath commented
That probably needs the same trick that gpggittest does with shutting down the test instance which at least leads to the chance that everything is finished before the setting is changed.

Some of our integration tests need to change setting but Gitea has been written to expect that setting is immutable.

2020-01-20 16:06 UTC, lunny commented
Please resolve the conflicts.

2020-01-30 11:59 UTC, 6543 commented
@typeless please resolve conflicts

2020-01-31 08:49 UTC, typeless commented
@6543 Done.

2020-01-31 08:51 UTC, 6543 approved these changes

2020-01-31 09:20 UTC, lunny commented
It's strange all races gone? @typeless

2020-01-31 09:51 UTC, typeless commented
@lunny Yeah, Since there is  `GOTESTFLAGS ?= -race` in a previous commit. I thought I should make it compatible with that change. But I probably misunderstand what you want.

Do you think we should enable both `GOFLAGS` and `GOTESTGLAGS` when `RACE_ENABLED` is set?

2020-01-31 13:40 UTC, lunny commented
@typeless I mean there is no race detection on default test. Once `RACE_ENABLED` defined, the tests will enable race detection.

2020-01-31 14:23 UTC, typeless commented
@lunny Updated.

2020-03-31 19:34 UTC, 6543 commented
confilicts :D

2020-04-01 01:56 UTC, typeless commented
@6543 I will fix it later.

2020-04-06 08:11 UTC, typeless commented
@6543 Updated.

2020-04-27 22:04 UTC, lafriks commented
@typeless please resolve conflicts

2020-04-28 02:21 UTC, typeless commented
@lafriks  Done.

2020-09-04 14:40 UTC, 6543 commented
It is starting to look good :)
only **TestAPIDeleteFile** found a race around the *code indexer**

2020-09-05 10:45 UTC, lunny commented
I found the race is about queues related with `LevelQueue` but I checked the tests of `LevelQueue`. All are PASSed. It's wired.

2020-09-05 12:16 UTC, zeripath commented
So it appears that the data.race detector thinks there's a race in queue_disk_channel_test.go.

https://github.com/go-gitea/gitea/blob/e80eda7d01ca0ea06e48f6f2fc22b174c5a5c91a/modules/queue/queue_disk_channel_test.go#L55

I suspect this line should be:

```go
		err := queue.Push(&test2)
```

(note the assignment operator)

Even that assignment is not really racy because the goroutine should have taken action already but meh.

I'm fairly certain that there isn't another data-race - the <-handlerChan mean that there can't be - however, if the data-race detector decides that there is another one there, convincing it of that could be difficult. I really do not want add additional locking to the queue push commands - there's enough locking there already.

2020-09-05 16:29 UTC, 6543 commented
golang upstream issue ?!?

2020-09-05 23:51 UTC, lunny commented
Another one

```

==================
--



```

2020-09-06 10:03 UTC, lafriks commented
There is still race in blew code indexer

2020-09-06 12:10 UTC, lunny commented
I suspect another one https://drone.gitea.io/go-gitea/gitea/29917/2/13 is because of mssql driver's bug.

```log
WARNING: DATA RACE
Write at 0x00c00225c001 by goroutine 23:
  github.com/denisenkom/go-mssqldb.(*tdsBuffer).BeginPacket()
      /go/src/code.gitea.io/gitea/vendor/github.com/denisenkom/go-mssqldb/buf.go:126 +0x164
  github.com/denisenkom/go-mssqldb.sendRpc()
      /go/src/code.gitea.io/gitea/vendor/github.com/denisenkom/go-mssqldb/rpc.go:50 +0xf1
  github.com/denisenkom/go-mssqldb.(*Stmt).sendQuery()
      /go/src/code.gitea.io/gitea/vendor/github.com/denisenkom/go-mssqldb/mssql.go:476 +0xcb7
  github.com/denisenkom/go-mssqldb.(*Stmt).queryContext()
      /go/src/code.gitea.io/gitea/vendor/github.com/denisenkom/go-mssqldb/mssql.go:591 +0x9e
  github.com/denisenkom/go-mssqldb.(*Stmt).QueryContext()
      /go/src/code.gitea.io/gitea/vendor/github.com/denisenkom/go-mssqldb/mssql.go:950 +0x244
  database/sql.ctxDriverStmtQuery()
      /usr/local/go/src/database/sql/ctxutil.go:82 +0x2c7
  database/sql.rowsiFromStatement()
      /usr/local/go/src/database/sql/sql.go:2688 +0x1fd
  database/sql.(*DB).queryDC()
      /usr/local/go/src/database/sql/sql.go:1673 +0x310
  database/sql.(*Tx).QueryContext()
      /usr/local/go/src/database/sql/sql.go:2375 +0x1b6
  xorm.io/xorm/core.(*Tx).QueryContext()
      /go/src/code.gitea.io/gitea/vendor/xorm.io/xorm/core/tx.go:149 +0x2d8
  xorm.io/xorm.(*Session).queryRows()
      /go/src/code.gitea.io/gitea/vendor/xorm.io/xorm/session_raw.go:63 +0x6fd
  xorm.io/xorm.(*Session).nocacheGet()
      /go/src/code.gitea.io/gitea/vendor/xorm.io/xorm/session_get.go:105 +0xfb
  xorm.io/xorm.(*Session).get()
      /go/src/code.gitea.io/gitea/vendor/xorm.io/xorm/session_get.go:92 +0x691
  xorm.io/xorm.(*Session).Get()
      /go/src/code.gitea.io/gitea/vendor/xorm.io/xorm/session_get.go:25 +0xa4
  code.gitea.io/gitea/models/migrations.addBranchProtectionCanPushAndEnableWhitelist.func3()
      /go/src/code.gitea.io/gitea/models/migrations/v111.go:407 +0x4ce
  code.gitea.io/gitea/models/migrations.addBranchProtectionCanPushAndEnableWhitelist()
      /go/src/code.gitea.io/gitea/models/migrations/v111.go:433 +0x591
  code.gitea.io/gitea/models/migrations.(*migration).Migrate()
      /go/src/code.gitea.io/gitea/models/migrations/migrations.go:44 +0x55
  code.gitea.io/gitea/models/migrations.Migrate()
      /go/src/code.gitea.io/gitea/models/migrations/migrations.go:319 +0x5c8
  code.gitea.io/gitea/integrations/migration-test.wrappedMigrate()
      /go/src/code.gitea.io/gitea/integrations/migration-test/migration_test.go:244 +0x5c
  code.gitea.io/gitea/models.NewEngine()
      /go/src/code.gitea.io/gitea/models/models.go:206 +0xfc
  code.gitea.io/gitea/integrations/migration-test.doMigrationTest()
      /go/src/code.gitea.io/gitea/integrations/migration-test/migration_test.go:258 +0x224
  code.gitea.io/gitea/integrations/migration-test.TestMigrations.func1()
      /go/src/code.gitea.io/gitea/integrations/migration-test/migration_test.go:278 +0x6a
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:1108 +0x202

Previous read at 0x00c00225c000 by goroutine 84:
  internal/race.ReadRange()
      /usr/local/go/src/internal/race/race.go:45 +0xb0
  syscall.Write()
      /usr/local/go/src/syscall/syscall_unix.go:215 +0x94
  internal/poll.ignoringEINTR()
      /usr/local/go/src/internal/poll/fd_unix.go:567 +0x62
  internal/poll.(*FD).Write()
      /usr/local/go/src/internal/poll/fd_unix.go:267 +0x20e
  net.(*netFD).Write()
      /usr/local/go/src/net/fd_posix.go:73 +0x65
  net.(*conn).Write()
      /usr/local/go/src/net/net.go:194 +0xeb
  net.(*TCPConn).Write()
      <autogenerated>:1 +0x69
  github.com/denisenkom/go-mssqldb.(*timeoutConn).Write()
      /go/src/code.gitea.io/gitea/vendor/github.com/denisenkom/go-mssqldb/net.go:38 +0xa6
  github.com/denisenkom/go-mssqldb.(*tdsBuffer).flush()
      /go/src/code.gitea.io/gitea/vendor/github.com/denisenkom/go-mssqldb/buf.go:73 +0x2d5
  github.com/denisenkom/go-mssqldb.(*tdsBuffer).FinishPacket()
      /go/src/code.gitea.io/gitea/vendor/github.com/denisenkom/go-mssqldb/buf.go:134 +0x144
  github.com/denisenkom/go-mssqldb.sendAttention()
      /go/src/code.gitea.io/gitea/vendor/github.com/denisenkom/go-mssqldb/tds.go:759 +0x159
  github.com/denisenkom/go-mssqldb.(*parseResp).sendAttention()
      /go/src/code.gitea.io/gitea/vendor/github.com/denisenkom/go-mssqldb/token.go:697 +0x75
  github.com/denisenkom/go-mssqldb.(*parseResp).iter()
      /go/src/code.gitea.io/gitea/vendor/github.com/denisenkom/go-mssqldb/token.go:740 +0x1004
  github.com/denisenkom/go-mssqldb.processResponse()
      /go/src/code.gitea.io/gitea/vendor/github.com/denisenkom/go-mssqldb/token.go:813 +0x12e
```

2020-09-06 12:34 UTC, lunny commented
Bleve Data Race maybe also upstream related.

```log
WARNING: DATA RACE
Write at 0x00c0095ed040 by goroutine 128:
  github.com/blevesearch/bleve/index.(*Batch).Reset()
      /go/src/code.gitea.io/gitea/vendor/github.com/blevesearch/bleve/index/index.go:318 +0x106
  github.com/blevesearch/bleve.(*Batch).Reset()
      /go/src/code.gitea.io/gitea/vendor/github.com/blevesearch/bleve/index.go:119 +0xcc
  github.com/ethantkoenig/rupture.(*singleIndexFlushingBatch).Flush()
      /go/src/code.gitea.io/gitea/vendor/github.com/ethantkoenig/rupture/flushing_batch.go:65 +0xad
  code.gitea.io/gitea/modules/indexer/code.(*BleveIndexer).Index()
      /go/src/code.gitea.io/gitea/modules/indexer/code/bleve.go:266 +0x42c
  code.gitea.io/gitea/modules/indexer/code.(*wrappedIndexer).Index()
      /go/src/code.gitea.io/gitea/modules/indexer/code/wrapped.go:65 +0x122
  code.gitea.io/gitea/modules/indexer/code.index()
      /go/src/code.gitea.io/gitea/modules/indexer/code/queue.go:44 +0x1b1
  code.gitea.io/gitea/modules/indexer/code.processRepoIndexerOperationQueue()
      /go/src/code.gitea.io/gitea/modules/indexer/code/queue.go:61 +0x49d

Previous read at 0x00c0095ed040 by goroutine 58:
  github.com/blevesearch/bleve/index/upsidedown.(*UpsideDownCouch).Batch.func1()
      /go/src/code.gitea.io/gitea/vendor/github.com/blevesearch/bleve/index/upsidedown/upsidedown.go:824 +0x10b
```

2020-10-05 23:44 UTC, 6543 commented
plz update :)

2020-12-11 16:58 UTC, 6543 commented
found a race in https://github.com/ethantkoenig/rupture we use ...

-> https://hatebin.com/vdbepbvnvm
-> https://github.com/ethantkoenig/rupture/issues/3

2021-01-24 08:21 UTC, lunny commented
New race detected.

```log
WARNING: DATA RACE
--
129 | Write at 0x0000047ecbe0 by goroutine 123:
130 | code.gitea.io/gitea/services/archiver.ArchiveRepository.func1()
131 | /go/src/code.gitea.io/gitea/services/archiver/archiver.go:315 +0x334
132 |  
133 | Previous read at 0x0000047ecbe0 by goroutine 61:
134 | code.gitea.io/gitea/services/archiver.releaseOneEntry()
135 | /go/src/code.gitea.io/gitea/services/archiver/archiver_test.go:52 +0xeb
136 | code.gitea.io/gitea/services/archiver.TestArchive_Basic()
137 | /go/src/code.gitea.io/gitea/services/archiver/archiver_test.go:180 +0xe7d
138 | testing.tRunner()
139 | /usr/local/go/src/testing/testing.go:1123 +0x202
140 |  
141 | Goroutine 123 (running) created at:
142 | code.gitea.io/gitea/services/archiver.ArchiveRepository()
143 | /go/src/code.gitea.io/gitea/services/archiver/archiver.go:273 +0x2f2
144 | code.gitea.io/gitea/services/archiver.TestArchive_Basic()
145 | /go/src/code.gitea.io/gitea/services/archiver/archiver_test.go:122 +0x8b5
146 | testing.tRunner()
147 | /usr/local/go/src/testing/testing.go:1123 +0x202
148 |  
149 | Goroutine 61 (running) created at:
150 | testing.(*T).Run()
151 | /usr/local/go/src/testing/testing.go:1168 +0x5bb
152 | testing.runTests.func1()
153 | /usr/local/go/src/testing/testing.go:1439 +0xa6
154 | testing.tRunner()
155 | /usr/local/go/src/testing/testing.go:1123 +0x202
156 | testing.runTests()
157 | /usr/local/go/src/testing/testing.go:1437 +0x612
158 | testing.(*M).Run()
159 | /usr/local/go/src/testing/testing.go:1345 +0x3b3
160 | code.gitea.io/gitea/models.MainTest()
161 | /go/src/code.gitea.io/gitea/models/unit_tests.go:88 +0xda7
162 | code.gitea.io/gitea/services/archiver.TestMain()
163 | /go/src/code.gitea.io/gitea/services/archiver/archiver_test.go:23 +0xa4
164 | main.main()
165 | _testmain.go:93 +0x371
```

2021-02-04 01:32 UTC, 6543 commented
**`code.gitea.io/gitea/services/archiver`** has a race:
```
WARNING: DATA RACE                                
Write at 0x0000050c41a0 by goroutine 98:                                                                                               
  code.gitea.io/gitea/services/archiver.ArchiveRepository.func1()
      /home/maddl/git/own/gitea/services/archiver/archiver.go:315 +0x274

Previous read at 0x0000050c41a0 by goroutine 39:
  code.gitea.io/gitea/services/archiver.releaseOneEntry()  
      /home/maddl/git/own/gitea/services/archiver/archiver_test.go:52 +0xeb
  code.gitea.io/gitea/services/archiver.TestArchive_Basic()
      /home/maddl/git/own/gitea/services/archiver/archiver_test.go:180 +0xe3d 
  testing.tRunner()
      /usr/lib/go/src/testing/testing.go:1123 +0x202
                                                                   
Goroutine 98 (running) created at:
  code.gitea.io/gitea/services/archiver.ArchiveRepository()
      /home/maddl/git/own/gitea/services/archiver/archiver.go:273 +0x2a8
  code.gitea.io/gitea/services/archiver.TestArchive_Basic()      
      /home/maddl/git/own/gitea/services/archiver/archiver_test.go:118 +0x866
  testing.tRunner()                                        
      /usr/lib/go/src/testing/testing.go:1123 +0x202                                                                                   
                                                                   
Goroutine 39 (running) created at:                  
  testing.(*T).Run()
      /usr/lib/go/src/testing/testing.go:1168 +0x5bb
  testing.runTests.func1()                                       
      /usr/lib/go/src/testing/testing.go:1439 +0xa6                                                                                    
  testing.tRunner()
      /usr/lib/go/src/testing/testing.go:1123 +0x202
  testing.runTests()
      /usr/lib/go/src/testing/testing.go:1437 +0x612
  testing.(*M).Run()      
      /usr/lib/go/src/testing/testing.go:1345 +0x3b3
  code.gitea.io/gitea/models.MainTest()
      /home/maddl/git/own/gitea/models/unit_tests.go:88 +0xda7
  code.gitea.io/gitea/services/archiver.TestMain()
      /home/maddl/git/own/gitea/services/archiver/archiver_test.go:23 +0xa4
  main.main()       
      _testmain.go:45 +0x271
```
:point_up: code has it's own smal Queue implementation ! :/ we should us our normal queue infrastructure instead!

2021-02-15 03:46 UTC, lunny commented
> New race detected.
> 
> ```
> WARNING: DATA RACE
> --
> 129 | Write at 0x0000047ecbe0 by goroutine 123:
> 130 | code.gitea.io/gitea/services/archiver.ArchiveRepository.func1()
> 131 | /go/src/code.gitea.io/gitea/services/archiver/archiver.go:315 +0x334
> 132 |  
> 133 | Previous read at 0x0000047ecbe0 by goroutine 61:
> 134 | code.gitea.io/gitea/services/archiver.releaseOneEntry()
> 135 | /go/src/code.gitea.io/gitea/services/archiver/archiver_test.go:52 +0xeb
> 136 | code.gitea.io/gitea/services/archiver.TestArchive_Basic()
> 137 | /go/src/code.gitea.io/gitea/services/archiver/archiver_test.go:180 +0xe7d
> 138 | testing.tRunner()
> 139 | /usr/local/go/src/testing/testing.go:1123 +0x202
> 140 |  
> 141 | Goroutine 123 (running) created at:
> 142 | code.gitea.io/gitea/services/archiver.ArchiveRepository()
> 143 | /go/src/code.gitea.io/gitea/services/archiver/archiver.go:273 +0x2f2
> 144 | code.gitea.io/gitea/services/archiver.TestArchive_Basic()
> 145 | /go/src/code.gitea.io/gitea/services/archiver/archiver_test.go:122 +0x8b5
> 146 | testing.tRunner()
> 147 | /usr/local/go/src/testing/testing.go:1123 +0x202
> 148 |  
> 149 | Goroutine 61 (running) created at:
> 150 | testing.(*T).Run()
> 151 | /usr/local/go/src/testing/testing.go:1168 +0x5bb
> 152 | testing.runTests.func1()
> 153 | /usr/local/go/src/testing/testing.go:1439 +0xa6
> 154 | testing.tRunner()
> 155 | /usr/local/go/src/testing/testing.go:1123 +0x202
> 156 | testing.runTests()
> 157 | /usr/local/go/src/testing/testing.go:1437 +0x612
> 158 | testing.(*M).Run()
> 159 | /usr/local/go/src/testing/testing.go:1345 +0x3b3
> 160 | code.gitea.io/gitea/models.MainTest()
> 161 | /go/src/code.gitea.io/gitea/models/unit_tests.go:88 +0xda7
> 162 | code.gitea.io/gitea/services/archiver.TestMain()
> 163 | /go/src/code.gitea.io/gitea/services/archiver/archiver_test.go:23 +0xa4
> 164 | main.main()
> 165 | _testmain.go:93 +0x371
> ```

This is the last race currently.

2021-06-02 18:23 UTC, 6543 commented on .drone.yml
> +      RACE_ENABLED: "0"
```suggestion
      RACE_ENABLED: true
```

2021-06-02 18:23 UTC, 6543 commented on .drone.yml
> +      RACE_ENABLED: "0"
```suggestion
      RACE_ENABLED: true
```

2021-06-03 16:54 UTC, 6543 commented on Makefile
> +ifneq ($(RACE_ENABLED),)
`export RACE_ENABLED=true` worked on my PC, but the CI somehow set it different ... so i moved back to just test if RACE_ENABLED is set ...

2021-06-25 04:55 UTC, lunny commented
last data race from bleve

```log
==================
WARNING: DATA RACE
Write at 0x00c045ec4978 by goroutine 118:
  github.com/blevesearch/bleve_index_api.(*Batch).Reset()
      /drone/src/vendor/github.com/blevesearch/bleve_index_api/batch.go:78 +0x106
  github.com/blevesearch/bleve/v2.(*Batch).Reset()
      /drone/src/vendor/github.com/blevesearch/bleve/v2/index.go:119 +0xcc
  github.com/ethantkoenig/rupture.(*singleIndexFlushingBatch).Flush()
      /drone/src/vendor/github.com/ethantkoenig/rupture/flushing_batch.go:65 +0xad
  code.gitea.io/gitea/modules/indexer/code.(*BleveIndexer).Index()
      /drone/src/modules/indexer/code/bleve.go:288 +0x2f5
  code.gitea.io/gitea/modules/indexer/code.(*wrappedIndexer).Index()
      /drone/src/modules/indexer/code/wrapped.go:65 +0x121
  code.gitea.io/gitea/modules/indexer/code.index()
      /drone/src/modules/indexer/code/indexer.go:102 +0x1b7
  code.gitea.io/gitea/modules/indexer/code.Init.func2()
      /drone/src/modules/indexer/code/indexer.go:155 +0x4b3
  code.gitea.io/gitea/modules/queue.(*Immediate).PushFunc()
      /drone/src/modules/queue/queue.go:139 +0xe6
  code.gitea.io/gitea/modules/queue.(*Immediate).Push()
      /drone/src/modules/queue/queue.go:129 +0x71
  code.gitea.io/gitea/modules/indexer/code.UpdateRepoIndexer()
      /drone/src/modules/indexer/code/indexer.go:278 +0xf8
  code.gitea.io/gitea/modules/notification/indexer.(*indexerNotifier).NotifyPushCommits()
      /drone/src/modules/notification/indexer/indexer.go:128 +0x315
  code.gitea.io/gitea/modules/notification.NotifyPushCommits()
      /drone/src/modules/notification/notification.go:255 +0x105
  code.gitea.io/gitea/services/repository.pushUpdates()
      /drone/src/services/repository/push.go:200 +0x2404
  code.gitea.io/gitea/services/repository.handle()
      /drone/src/services/repository/push.go:32 +0xf9
  code.gitea.io/gitea/modules/queue.(*Immediate).PushFunc()
      /drone/src/modules/queue/queue.go:139 +0xe6
  code.gitea.io/gitea/modules/queue.(*Immediate).Push()
      /drone/src/modules/queue/queue.go:129 +0x71
  code.gitea.io/gitea/services/repository.PushUpdates()
      /drone/src/services/repository/push.go:65 +0x3a1
  code.gitea.io/gitea/routers/private.HookPostReceive()
      /drone/src/routers/private/hook.go:426 +0x372f
  code.gitea.io/gitea/modules/web.Wrap.func1()
      /drone/src/modules/web/route.go:76 +0x51c
  net/http.HandlerFunc.ServeHTTP()
      /usr/local/go/src/net/http/server.go:2069 +0x51
  github.com/go-chi/chi.(*Mux).routeHTTP()
      /drone/src/vendor/github.com/go-chi/chi/mux.go:436 +0x3f7
  github.com/go-chi/chi.(*Mux).routeHTTP-fm()
      /drone/src/vendor/github.com/go-chi/chi/mux.go:410 +0x68
  net/http.HandlerFunc.ServeHTTP()
      /usr/local/go/src/net/http/server.go:2069 +0x51
  code.gitea.io/gitea/routers/private.CheckInternalToken.func1()
      /drone/src/routers/private/internal.go:31 +0x325
  net/http.HandlerFunc.ServeHTTP()
      /usr/local/go/src/net/http/server.go:2069 +0x51
  code.gitea.io/gitea/modules/context.PrivateContexter.func1.1()
      /drone/src/modules/context/private.go:42 +0x2fa
  net/http.HandlerFunc.ServeHTTP()
      /usr/local/go/src/net/http/server.go:2069 +0x51
  github.com/go-chi/chi.(*Mux).ServeHTTP()
      /drone/src/vendor/github.com/go-chi/chi/mux.go:70 +0xb8f
  github.com/go-chi/chi.(*Mux).Mount.func1()
      /drone/src/vendor/github.com/go-chi/chi/mux.go:311 +0x231
  net/http.HandlerFunc.ServeHTTP()
      /usr/local/go/src/net/http/server.go:2069 +0x51
  github.com/go-chi/chi.(*Mux).routeHTTP()
      /drone/src/vendor/github.com/go-chi/chi/mux.go:436 +0x3f7
  github.com/go-chi/chi.(*Mux).routeHTTP-fm()
      /drone/src/vendor/github.com/go-chi/chi/mux.go:410 +0x68
  net/http.HandlerFunc.ServeHTTP()
      /usr/local/go/src/net/http/server.go:2069 +0x51
  code.gitea.io/gitea/routers/common.Middlewares.func2.1()
      /drone/src/routers/common/middleware.go:72 +0x112
  net/http.HandlerFunc.ServeHTTP()
      /usr/local/go/src/net/http/server.go:2069 +0x51
  code.gitea.io/gitea/routers/common.LoggerHandler.func1.1()
      /drone/src/routers/common/logger.go:23 +0x332
  net/http.HandlerFunc.ServeHTTP()
      /usr/local/go/src/net/http/server.go:2069 +0x51
  github.com/go-chi/chi/middleware.StripSlashes.func1()
      /drone/src/vendor/github.com/go-chi/chi/middleware/strip.go:30 +0x202
  net/http.HandlerFunc.ServeHTTP()
      /usr/local/go/src/net/http/server.go:2069 +0x51
  github.com/chi-middleware/proxy.ForwardedHeaders.func1.1()
      /drone/src/vendor/github.com/chi-middleware/proxy/middleware.go:37 +0x105
  net/http.HandlerFunc.ServeHTTP()
      /usr/local/go/src/net/http/server.go:2069 +0x51
  code.gitea.io/gitea/routers/common.Middlewares.func1.1()
      /drone/src/routers/common/middleware.go:25 +0xa6
  net/http.HandlerFunc.ServeHTTP()
      /usr/local/go/src/net/http/server.go:2069 +0x51
  github.com/go-chi/chi.(*Mux).ServeHTTP()
      /drone/src/vendor/github.com/go-chi/chi/mux.go:87 +0x74e
  code.gitea.io/gitea/modules/web.(*Route).ServeHTTP()
      /drone/src/modules/web/route.go:298 +0x8d
  net/http.serverHandler.ServeHTTP()
      /usr/local/go/src/net/http/server.go:2887 +0xca
  net/http.(*conn).serve()
      /usr/local/go/src/net/http/server.go:1952 +0x87d

Previous read at 0x00c045ec4978 by goroutine 193:
  github.com/blevesearch/bleve/v2/index/scorch.(*Scorch).Batch.func2()
      /drone/src/vendor/github.com/blevesearch/bleve/v2/index/scorch/scorch.go:343 +0x10b

Goroutine 118 (running) created at:
  net/http.(*Server).Serve()
      /usr/local/go/src/net/http/server.go:3013 +0x644

Goroutine 193 (finished) created at:
  github.com/blevesearch/bleve/v2/index/scorch.(*Scorch).Batch()
      /drone/src/vendor/github.com/blevesearch/bleve/v2/index/scorch/scorch.go:341 +0xa64
  github.com/blevesearch/bleve/v2.(*indexImpl).Batch()
      /drone/src/vendor/github.com/blevesearch/bleve/v2/index_impl.go:307 +0x131
  github.com/ethantkoenig/rupture.(*singleIndexFlushingBatch).Flush()
      /drone/src/vendor/github.com/ethantkoenig/rupture/flushing_batch.go:61 +0x96
  code.gitea.io/gitea/modules/indexer/code.(*BleveIndexer).Index()
      /drone/src/modules/indexer/code/bleve.go:288 +0x2f5
  code.gitea.io/gitea/modules/indexer/code.(*wrappedIndexer).Index()
      /drone/src/modules/indexer/code/wrapped.go:65 +0x121
  code.gitea.io/gitea/modules/indexer/code.index()
      /drone/src/modules/indexer/code/indexer.go:102 +0x1b7
  code.gitea.io/gitea/modules/indexer/code.Init.func2()
      /drone/src/modules/indexer/code/indexer.go:155 +0x4b3
  code.gitea.io/gitea/modules/queue.(*Immediate).PushFunc()
      /drone/src/modules/queue/queue.go:139 +0xe6
  code.gitea.io/gitea/modules/queue.(*Immediate).Push()
      /drone/src/modules/queue/queue.go:129 +0x71
  code.gitea.io/gitea/modules/indexer/code.UpdateRepoIndexer()
      /drone/src/modules/indexer/code/indexer.go:278 +0xf8
  code.gitea.io/gitea/modules/notification/indexer.(*indexerNotifier).NotifyPushCommits()
      /drone/src/modules/notification/indexer/indexer.go:128 +0x315
  code.gitea.io/gitea/modules/notification.NotifyPushCommits()
      /drone/src/modules/notification/notification.go:255 +0x105
  code.gitea.io/gitea/services/repository.pushUpdates()
      /drone/src/services/repository/push.go:200 +0x2404
  code.gitea.io/gitea/services/repository.handle()
      /drone/src/services/repository/push.go:32 +0xf9
  code.gitea.io/gitea/modules/queue.(*Immediate).PushFunc()
      /drone/src/modules/queue/queue.go:139 +0xe6
  code.gitea.io/gitea/modules/queue.(*Immediate).Push()
      /drone/src/modules/queue/queue.go:129 +0x71
  code.gitea.io/gitea/services/repository.PushUpdates()
      /drone/src/services/repository/push.go:65 +0x3a1
  code.gitea.io/gitea/routers/private.HookPostReceive()
      /drone/src/routers/private/hook.go:426 +0x372f
  code.gitea.io/gitea/modules/web.Wrap.func1()
      /drone/src/modules/web/route.go:76 +0x51c
  net/http.HandlerFunc.ServeHTTP()
      /usr/local/go/src/net/http/server.go:2069 + [...]

2021-07-19 04:55 UTC, lunny commented
Now we have another data race which haven't occupied before. And it's surprising this is only at mssql test.

```
WARNING: DATA RACE
597s
235	Write at 0x00c0001b1318 by goroutine 240:
597s
236	  code.gitea.io/gitea/modules/log.(*MultiChannelledLog).internalResetLevel()
597s
237	      /drone/src/modules/log/event.go:371 +0x64
597s
238	  code.gitea.io/gitea/modules/log.(*MultiChannelledLog).DelLogger()
597s
239	      /drone/src/modules/log/event.go:205 +0x127
597s
240	  code.gitea.io/gitea/modules/log.(*MultiChannelledLogger).DelLogger()
597s
241	      /drone/src/modules/log/multichannel.go:54 +0xaa
597s
242	  code.gitea.io/gitea/modules/log.DelLogger()
597s
243	      /drone/src/modules/log/log.go:78 +0x73
597s
244	  code.gitea.io/gitea/cmd.setup()
597s
245	      /drone/src/cmd/serv.go:53 +0x47
597s
246	  code.gitea.io/gitea/cmd.runKeys()
597s
247	      /drone/src/cmd/keys.go:68 +0x2f8
597s
248	  github.com/urfave/cli.HandleAction()
597s
249	      /drone/src/vendor/github.com/urfave/cli/app.go:524 +0x15b
597s
250	  github.com/urfave/cli.Command.Run()
597s
251	      /drone/src/vendor/github.com/urfave/cli/command.go:173 +0x967
597s
252	  code.gitea.io/gitea/integrations.Test_CmdKeys.func1.1()
597s
253	      /drone/src/integrations/cmd_keys_test.go:48 +0x4f3
597s
254	  testing.tRunner()
597s
255	      /usr/local/go/src/testing/testing.go:1194 +0x202
597s
256	
597s
257	Previous read at 0x00c0001b1318 by goroutine 84:
597s
258	  code.gitea.io/gitea/modules/log.(*MultiChannelledLog).GetLevel()
597s
259	      /drone/src/modules/log/event.go:362 +0x87
597s
260	  code.gitea.io/gitea/modules/log.(*MultiChannelledLogger).Log()
597s
261	      /drone/src/modules/log/multichannel.go:59 +0x45
597s
262	  code.gitea.io/gitea/modules/log.Log()
597s
263	      /drone/src/modules/log/log.go:247 +0xdc
597s
264	  code.gitea.io/gitea/modules/log.Trace()
597s
265	      /drone/src/modules/log/log.go:109 +0x575
597s
266	  code.gitea.io/gitea/modules/queue.(*ByteFIFOQueue).readToChan()
597s
267	      /drone/src/modules/queue/queue_bytefifo.go:151 +0x42a
597s
268	  code.gitea.io/gitea/modules/queue.(*ByteFIFOQueue).Run()
597s
269	      /drone/src/modules/queue/queue_bytefifo.go:121 +0x426
597s
270	  code.gitea.io/gitea/modules/queue.(*LevelQueue).Run()
597s
271	      <autogenerated>:1 +0x6d
597s
272	  code.gitea.io/gitea/modules/queue.Queue.Run-fm()
597s
273	      /drone/src/modules/queue/queue.go:60 +0x63
597s
274	  code.gitea.io/gitea/modules/graceful.(*Manager).RunWithShutdownFns()
597s
275	      /drone/src/modules/graceful/manager.go:83 +0x1d4
597s
276	
597s
277	Goroutine 240 (running) created at:
597s
278	  testing.(*T).Run()
597s
279	      /usr/local/go/src/testing/testing.go:1239 +0x5d7
597s
280	  code.gitea.io/gitea/integrations.Test_CmdKeys.func1()
597s
281	      /drone/src/integrations/cmd_keys_test.go:40 +0xb88
597s
282	  code.gitea.io/gitea/integrations.onGiteaRun.func1()
597s
283	      /drone/src/integrations/git_helper_for_declarative_test.go:113 +0x65
597s
284	  code.gitea.io/gitea/integrations.onGiteaRunTB()
597s
285	      /drone/src/integrations/git_helper_for_declarative_test.go:108 +0x49d
597s
286	  code.gitea.io/gitea/integrations.onGiteaRun()
597s
287	      /drone/src/integrations/git_helper_for_declarative_test.go:112 +0x8e
597s
288	  code.gitea.io/gitea/integrations.Test_CmdKeys()
597s
289	      /drone/src/integrations/cmd_keys_test.go:23 +0x69
597s
290	  testing.tRunner()
597s
291	      /usr/local/go/src/testing/testing.go:1194 +0x202
597s
292	
597s
293	Goroutine 84 (running) created at:
597s
294	  code.gitea.io/gitea/modules/indexer/issues.InitIssueIndexer.func2()
597s
295	      /drone/src/modules/indexer/issues/indexer.go:194 +0x3fb
```

2021-07-19 15:44 UTC, zeripath commented
> Now we have another data race which haven't occupied before. And it's surprising this is only at mssql test.

Data races are non-deterministic - it'll be on everything.

> But `Serv` command should not init queue services.

Turns out it's not serv - it's keys.

```
WARNING: DATA RACE
> 597s
> 235	Write at 0x00c0001b1318 by goroutine 240:
> 597s
> 236	  code.gitea.io/gitea/modules/log.(*MultiChannelledLog).internalResetLevel()
...
> 246	  code.gitea.io/gitea/cmd.runKeys()
> 597s
> 247	      /drone/src/cmd/keys.go:68 +0x2f8
...
> 252	  code.gitea.io/gitea/integrations.Test_CmdKeys.func1.1()
> 597s
> 253	      /drone/src/integrations/cmd_keys_test.go:48 +0x4f3
> 597s
...
```

There are two problems:

1. There's a genuine datarace in log. We're missing a around GetLevel and GetStackTraceLevel if internal reset can be called whilst the logger is running.
2.  `Test_CmdKeys` should really just run the executable:

https://github.com/go-gitea/gitea/blob/2256499db53c158c3abe12c5a7191ea36eb4919e/integrations/cmd_keys_test.go#L45-L48

2021-07-21 21:22 UTC, 6543 commented
```
==================
WARNING: DATA RACE
Read at 0x00c0014f8043 by goroutine 103:
  testing.(*common).logDepth()
      /usr/local/go/src/testing/testing.go:754 +0x74
  testing.(*common).log()
      /usr/local/go/src/testing/testing.go:747 +0x5c
  testing.(*common).Log()
      /usr/local/go/src/testing/testing.go:786 +0x1c
  testing.(*T).Log()
      <autogenerated>:1 +0x4c
  code.gitea.io/gitea/integrations.(*testLoggerWriterCloser).Write()
      /drone/src/integrations/testlogger.go:78 +0x1ac
  code.gitea.io/gitea/modules/log.(*WriterLogger).LogEvent()
      /drone/src/modules/log/writer.go:235 +0x124
  code.gitea.io/gitea/integrations.(*TestLogger).LogEvent()
      <autogenerated>:1 +0x3c
  code.gitea.io/gitea/modules/log.(*ChannelledLog).Start()
      /drone/src/modules/log/event.go:76 +0x194

Previous write at 0x00c0014f8043 by goroutine 82:
  testing.tRunner.func1()
      /usr/local/go/src/testing/testing.go:1181 +0x36c
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:1198 +0x190

Goroutine 103 (running) created at:
  code.gitea.io/gitea/modules/log.NewChannelledLog()
      /drone/src/modules/log/event.go:61 +0x318
  code.gitea.io/gitea/modules/log.(*MultiChannelledLogger).SetLogger()
      /drone/src/modules/log/multichannel.go:34 +0x70
  code.gitea.io/gitea/modules/log.NewNamedLogger()
      /drone/src/modules/log/log.go:63 +0x80
  code.gitea.io/gitea/modules/log.NewLogger()
      /drone/src/modules/log/log.go:46 +0x88
  code.gitea.io/gitea/modules/setting.newLogService()
      /drone/src/modules/setting/log.go:327 +0x9c0
  code.gitea.io/gitea/modules/setting.NewLogServices()
      /drone/src/modules/setting/log.go:352 +0x20
  code.gitea.io/gitea/modules/setting.NewServices()
      /drone/src/modules/setting/setting.go:1190 +0x30
  code.gitea.io/gitea/routers.NewServices()
      /drone/src/routers/init.go:47 +0x20
  code.gitea.io/gitea/routers.GlobalInit()
      /drone/src/routers/init.go:86 +0x454
  code.gitea.io/gitea/integrations.initIntegrationTest()
      /drone/src/integrations/integration_test.go:240 +0x550
  code.gitea.io/gitea/integrations.TestMain()
      /drone/src/integrations/integration_test.go:90 +0xb8
  main.main()
      _testmain.go:697 +0x22c

Goroutine 82 (running) created at:
  testing.(*T).Run()
      /usr/local/go/src/testing/testing.go:1239 +0x438
  testing.runTests.func1()
      /usr/local/go/src/testing/testing.go:1512 +0x90
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:1194 +0x170
  testing.runTests()
      /usr/local/go/src/testing/testing.go:1510 +0x510
  testing.(*M).Run()
      /usr/local/go/src/testing/testing.go:1418 +0x2d0
  code.gitea.io/gitea/integrations.TestMain()
      /drone/src/integrations/integration_test.go:121 +0x278
  fmt.Sscanf()
      /usr/local/go/src/fmt/scan.go:114 +0x128
  github.com/syndtr/goleveldb/leveldb/storage.fsParseName()
      /drone/src/vendor/github.com/syndtr/goleveldb/leveldb/storage/file_storage.go:643 +0x74
  github.com/syndtr/goleveldb/leveldb/storage.(*fileStorage).List()
      /drone/src/vendor/github.com/syndtr/goleveldb/leveldb/storage/file_storage.go:458 +0x200
  github.com/syndtr/goleveldb/leveldb.(*DB).checkAndCleanFiles()
      /drone/src/vendor/github.com/syndtr/goleveldb/leveldb/db_util.go:52 +0x238
  github.com/syndtr/goleveldb/leveldb.openDB()
      /drone/src/vendor/github.com/syndtr/goleveldb/leveldb/db.go:130 +0x790
  github.com/syndtr/goleveldb/leveldb/storage.(*fileStorage).List()
      /drone/src/vendor/github.com/syndtr/goleveldb/leveldb/storage/file_storage.go:458 +0x200
  fmt.Fscanf()
      /usr/local/go/src/fmt/scan.go:143 +0xa4
  fmt.Sscanf()
      /usr/local/go/src/fmt/scan.go:114 +0x1e0
  github.com/syndtr/goleveldb/leveldb/storage.fsParseName()
      /drone/src/vendor/github.com/syndtr/goleveldb/leveldb/storage/file_storage.go:657 +0x134
  fmt.(*ss).doScanf()
      /usr/local/go/src/fmt/scan.go:1230 +0x310
  fmt.Fscanf()
      /usr/local/go/src/fmt/scan.go:143 +0xa4
  fmt.Sscanf()
      /usr/local/go/src/fmt/scan.go:114 +0x128
  github.com/syndtr/goleveldb/leveldb/storage.fsParseName()
      /drone/src/vendor/github.com/syndtr/goleveldb/leveldb/storage/file_storage.go:643 +0x74
  github.com/syndtr/goleveldb/leveldb/storage.(*fileStorage).List()
      /drone/src/vendor/github.com/syndtr/goleveldb/leveldb/storage/file_storage.go:458 +0x200
  fmt.Fscanf()
      /usr/local/go/src/fmt/scan.go:143 +0xa4
  fmt.Sscanf()
      /usr/local/go/src/fmt/scan.go:114 +0x128
  github.com/syndtr/goleveldb/leveldb/storage.fsParseName()
      /drone/src/vendor/github.com/syndtr/goleveldb/leveldb/storage/file_storage.go:643 +0x74
  github.com/syndtr/goleveldb/leveldb/storage.(*fileStorage).List()
      /drone/src/vendor/github.com/syndtr/goleveldb/leveldb/storage/file_storage.go:458 +0x200
  fmt.Fscanf()
      /usr/local/go/src/fmt/scan.go:143 +0xa4
  fmt.Sscanf()
      /usr/local/go/src/fmt/scan.go:114 +0x128
  github.com/syndtr/goleveldb/leveldb/storage.fsParseName()
      /drone/src/vendor/github.com/syndtr/goleveldb/leveldb/storage/file_storage.go:643 +0x74
  github.com/syndtr/goleveldb/leveldb/storage.(*fileStorage).List()
      /drone/src/vendor/github.com/syndtr/goleveldb/leveldb/storage/file_storage.go:458 +0x200
  github.com/syndtr/goleveldb/leveldb.(*DB).recoverJournal()
      /drone/src/vendor/github.com/syndtr/goleveldb/leveldb/db.go:476 +0x90
  github.com/syndtr/goleveldb/leveldb.openDB()
      /drone/src/vendor/github.com/syndtr/goleveldb/leveldb/db.go:125 +0x774
  github.com/syndtr/goleveldb/leveldb.Open()
      /drone/src/vendor/github.com/syndtr/goleveldb/leveldb/db.go:197 +0x1a0
  fmt.Fscanf()
      /usr/local/go/src/fmt/scan.go:143 +0xa4
  fmt.Sscanf()
      /usr/local/go/src/fmt/scan.go:114 +0x128
  github.com/syndtr/goleveldb/leveldb/storage.fsParseName()
      /drone/src/vendor/github.com/syndtr/goleveldb/leveldb/storage/file_storage.go:643 +0x74
  github.com/syndtr/goleveldb/leveldb/storage.(*fileStorage).List()
      /drone/src/vendor/github.com/syndtr/goleveldb/leveldb/storage/file_storage.go:458 +0x200
  github.com/syndtr/goleveldb/leveldb.(*session).recover.func1()
      /drone/src/vendor/github.com/syndtr/goleveldb/leveldb/session.go:113 +0xe4
  github.com/syndtr/goleveldb/leveldb.(*session).recover()
      /drone/src/vendor/github.com/syndtr/goleveldb/leveldb/session.go:121 +0x1494
  github.com/syndtr/goleveldb/leveldb.Open()
      /drone/src/vendor/github.com/syndtr/goleveldb/leveldb/db.go:183 +0xa0
  github.com/syndtr/goleveldb/leveldb.OpenFile()
      /drone/src/vendor/github.com/syndtr/goleveldb/leveldb/db.go:219 +0x7c
  code.gitea.io/gitea/modules/nosql.(*Manager).GetLevelDB()
      /drone/src/modules/nosql/manager_leveldb.go:135 +0x2354
  code.gitea.io/gitea/modules/queue.NewLevelQueueByteFIFO()
      /drone/src/modules/queue/queue_disk.go:71 +0x70
  code.gitea.io/gitea/modules/queue.NewLevelQueue()
      /drone/src/modules/queue/queue_disk.go:44 +0x15c
  code.gitea.io/gitea/modules/queue.NewQueue()
      /drone/src/modules/queue/queue.go:196 +0xb4
  code.gitea.io/gitea/modules/queue.CreateQueue()
      /drone/src/modules/queue/setting.go:53 +0x140
  code.gitea.io/gitea/modules/indexer/issues.InitIssueIndexer()
      /drone/src/modules/indexer/issues/indexer.go:130 +0x114
  code.gitea.io/gitea/routers.GlobalInit()
      /drone/src/routers/init.go:111 +0x57c
  fmt.Sscanf()
      /usr/local/go/src/fmt/scan.go:114 +0x128
  github.com/syndtr/goleveldb/leveldb/storage.fsParseName()
      /drone/src/vendor/github.com/syndtr/goleveldb/leveldb/storage/file_storage.go:643 +0x74
  github.com/syndtr/goleveldb/leveldb/storage.(*fileStorage).List()
      /drone/src/vendor/github.com/syndtr/goleveldb/leveldb/storage/file_storage.go:458 +0x200
  github.com/syndtr/goleveldb/leveldb.(*DB).checkAndCleanFiles()
      /drone/src/vendor/github.com/syndtr/goleveldb/leveldb/db_util.go:52 +0x238
  github.com/syndtr/goleveldb/leveldb.openDB()
      /drone/src/vendor/github.com/syndtr/goleveldb/leveldb/db.go:130 +0x790
  github.com [...]

2021-07-21 21:35 UTC, zeripath commented
Something is logging after or in-between tests again.

2021-07-22 04:03 UTC, lunny commented
The `testing.T` should not be shared by design but we did with no lock.

2021-07-22 10:15 UTC, zeripath commented
> The `testing.T` should not be shared by design but we did with no lock.

It's not that. This is a race forced by go because `t.Logf(...)` has been called between tests.

`testlogger` works by writing our logging to `t.Logf(...)` instead of to `os.Stdout`. This has the benefit that we only see logging from failed tests and that we have clear delineation of what logs relate to which tests.

If you look carefully at the stacktrace you will see that the race is detected deep within go internal code. This is a deliberate race added by Go in order to detect logging to `t` outside of a test.

Logging to `t` outside of a test is considered a race because tests are supposed to be self-contained and not make changes that could affect other tests or continue work outside of those tests.

---

I have three suspicions for what is happening:

## 1. Queue Asynchronicity

Let's look at a previous incarnation of this problem - (and perhaps one that has returned):

1. Test A involves pushing something to a Queue
2. Test A finishes successfully.
3. But... the Queue hasn't finished processing the item pushed to it.
4. The Queue logs something.
5. The logger is a testlogger which is a wrapper around the current `t.Logf()`
5. TestB hasn't started yet... so `t` is the previous completed Test A `t`.
6. Go's race detector detects this - and declares a Race in the testlogger. (Which is the technique go uses to detect this.)

I previously attempted to handle this through Flushing the queues - but this failed - and ultimately @lunny worked around this by adding the immediate queue - abandoning asynchronicity in queues during tests.

Now the above goroutine trace mentions a level db which makes me suspicious that there is still a non-immediate disk/level queue in the tests which may be the cause of this. That could be because of my changes to the default queue settings but it might have always been there waiting for some timing change to appear.

## 2. Logger Asynchronicity

Fundamentally the logger has to be asynchronous to be performant and it uses logevent channels as its method of asynchronicity. The current testlogger - which we absolutely need to be able to make interpreting our test logs at all helpful above - is hooked-in in a way using such a channel. There could be a queue of logs that that are waiting to be processed when the test ends. 

An additional `log.Flush` in the cleanup defer might help this issue - otherwise we're looking at another `immediate` type solution. Unfortunately an immediate log solution here would be more involved than in the queue case.

## 3. Other asynchronous behaviour

Gitea has other uncontrolled asynchronous activity that is external to Queues and could be the cause of this "race". Go's race detector here is deeply unhelpful as it's not telling us what was trying to be logged and the indirection used in the logger to make it asynchronous means that the stacktrace provided by go's race detection isn't telling us who actually called log. This makes debugging the issue difficult ... 

## Summary

Ultimately we're going to need to add complete lifecycle (start/stop) control to every test (and by extension the whole of Gitea) to prevent random races like this in the future. That is - each test will shutdown everything between each test - including logging. `graceful` gets us a long way toward this but there are still quite a lot of things that would need to be done for this. E.g. (live) reconfiguration, proper service registration, likely even dependency injection.

There's the other option of just throwing away inter-test logging or emitting it to console but that's just ignoring the issue.

2021-08-10 00:42 UTC, 6543 commented
:rocket:

2021-08-25 20:36 UTC, 6543 approved these changes

2021-08-26 08:50 UTC, merged