[API] Fix release API paths
go-gitea/gitea pull request #14596
Opened 2021-02-07 16:37 UTC by andbruch

Corrects the following release API routes:

- `GET /repos/{owner}/{repo}/releases/{id}/assets/{attachment_id}` 
- -> `GET /repos/{owner}/{repo}/releases/assets/{attachment_id}`
- `PATCH /repos/{owner}/{repo}/releases/{id}/assets/{attachment_id}` 
- -> `PATCH /repos/{owner}/{repo}/releases/assets/{attachment_id}`
- `DELETE /repos/{owner}/{repo}/releases/{id}/assets/{attachment_id}` 
- -> `DELETE /repos/{owner}/{repo}/releases/assets/{attachment_id}`

The routes were in conflict with the Github API:

- [GET /repos/{owner}/{repo}/releases/assets/{asset_id}](https://docs.github.com/en/rest/reference/repos#get-a-release-asset)
- [PATCH /repos/{owner}/{repo}/releases/assets/{asset_id}](https://docs.github.com/en/rest/reference/repos#update-a-release-asset)
- [DELETE /repos/{owner}/{repo}/releases/assets/{asset_id}](https://docs.github.com/en/rest/reference/repos#delete-a-release-asset)

The previous routes are marked as deprecated, but have not been removed.

2021-02-07 19:28 UTC, 6543 commented
I would not say it's a fix but an enhancement. since endpoints work just fine. only github had made some changes we are adopting with this ...

2021-02-07 19:33 UTC, 6543 commented on routers/api/v1/repo/release_attachment.go
> +	}
with this i can delete attachments i should not have the rights to do so ... you have to test if attachment you get belongs to this repo ...

2021-02-07 19:33 UTC, 6543 commented on routers/api/v1/repo/release_attachment.go
> +	}
& tests for this are needed + some general tests too

2021-02-25 11:31 UTC, 6543 commented
`make generate-swagger` is missing & some tests :)

2021-03-12 04:35 UTC, andrebruch commented
`make generate-swagger` was not missing ;)
On my system, the command did not append an extra line to the `v1_json.tmpl` file. 
After I manually inserted an empty line, the build is passing.

That was the error:
```
Please run 'make generate-swagger' and commit the result:
diff --git a/templates/swagger/v1_json.tmpl b/templates/swagger/v1_json.tmpl
index e217c174f..5da925a10 100644
--- a/templates/swagger/v1_json.tmpl
+++ b/templates/swagger/v1_json.tmpl
@@ -17070,4 +17070,4 @@
       "TOTPHeader": []
     }
   ]
-}
\ No newline at end of file
make: *** [Makefile:255: swagger-check] Error 1
+}

```

2021-04-15 20:39 UTC, 6543 requested changes

2021-04-15 20:39 UTC, 6543 commented on routers/api/v1/repo/release_attachment.go
> +	repo, err := models.GetRepositoryByOwnerAndName(ownerName, repoName)
you can get repo from context!

2021-04-15 20:39 UTC, 6543 commented
also we could dedublicate some code

2023-05-10 15:03 UTC, wxiaoguang commented
I guess Gitea's API has been different from GitHub's for long time.

Is this PR still related?

2023-05-23 19:12 UTC, closed without merging