Sanitation fix from Gogs
go-gitea/gitea pull request #1461
Opened 2017-04-07 07:31 UTC by bkcsoft

2017-04-07 07:39 UTC, tboerger approved these changes

2017-04-07 07:39 UTC, tboerger commented
LGTM

2017-04-07 08:24 UTC, appleboy approved these changes

2017-04-07 08:25 UTC, appleboy commented
LGTM

2017-04-07 08:28 UTC, appleboy requested changes

2017-04-07 08:28 UTC, appleboy commented on modules/markdown/sanitizer.go
> +	"github.com/gogits/gogs/modules/setting"
github.com/go-gitea/gitea

2017-04-07 10:07 UTC, strk commented on modules/markdown/sanitizer.go
> +	"github.com/gogits/gogs/modules/setting"
actually "code.gitea.io/gitea/modules/setting"

2017-04-07 11:19 UTC, tboerger commented on modules/markdown/sanitizer.go
> +	"github.com/gogits/gogs/modules/setting"
Good catch

2017-04-07 13:09 UTC, lunny commented on modules/markdown/sanitizer.go
> +	"github.com/gogits/gogs/modules/setting"
^

2017-04-07 13:11 UTC, lunny requested changes

2017-04-07 13:11 UTC, lunny commented on modules/markdown/sanitizer_test.go
> +	. "github.com/smartystreets/goconvey/convey"
goconvey has been removed before. I think change this test file to `github.com/stretchr/testify` is better

2017-04-07 15:58 UTC, bkcsoft commented on modules/markdown/sanitizer.go
> +	"github.com/gogits/gogs/modules/setting"
Noted

2017-04-07 15:58 UTC, bkcsoft commented
I'm getting nil-panics in some tests 🙄

2017-04-09 18:26 UTC, ChALkeR commented
<img src="https://gif.cmtt.space/3/club/bb/e5/f6/5d4dd430a056a4.jpg" height="100" />

2017-04-10 21:22 UTC, bkcsoft commented
And done! @appleboy @lunny please re-review 😄

2017-04-10 21:23 UTC, bkcsoft commented
Now it's working!

2017-04-11 01:04 UTC, lunny commented on modules/markdown/sanitizer.go
> +	if sanitizer == nil {
It seems a race problem?

2017-04-11 13:58 UTC, lunny commented on modules/markdown/sanitizer.go
> +	"code.gitea.io/gitea/modules/setting"
merge the gitea internal packages.

2017-04-11 14:07 UTC, lunny commented on modules/markdown/sanitizer.go
> +	if sanitizer.policy == nil {
how about
```Go
func init() {
NewSanitizer(0
}
```
?

2017-04-12 00:45 UTC, lunny commented on modules/markdown/sanitizer.go
> +	if sanitizer.policy == nil {
But this maybe a race problem.

2017-04-12 15:36 UTC, bkcsoft commented on modules/markdown/sanitizer.go
> +	if sanitizer.policy == nil {
It uses `sync.Once` so there's no race-condition that I can see...

2017-04-13 01:29 UTC, lunny commented on modules/markdown/sanitizer.go
> +	if sanitizer.policy == nil {
OK

2017-04-13 01:30 UTC, lunny approved these changes

2017-04-13 01:49 UTC, appleboy approved these changes

2017-04-13 02:31 UTC, lunny commented
let L-G-T-M work

2017-04-13 02:52 UTC, merged

2017-04-13 12:02 UTC, lunny commented
@bkcsoft could you send a backport to v1.1.1?