Add v171 (addSortingColToProjectBoard) migration for #14634
go-gitea/gitea pull request #14652
Opened 2021-02-11 17:51 UTC by 6543

#14634 introduced a new column in ProjectBoard, so we need migration too ...

2021-02-11 18:18 UTC, zeripath approved these changes

2021-02-11 18:18 UTC, zeripath commented
Oh I thought that was there in the previous PR..

2021-02-12 01:51 UTC, lafriks requested changes

2021-02-12 01:51 UTC, lafriks commented on models/migrations/v171.go
> +		Sorting int8 `xorm:"DEFAULT 0"`
It should probably be not null also

2021-02-12 09:51 UTC, 6543 commented
@lafriks done

2021-02-12 11:01 UTC, lafriks approved these changes

2021-02-12 11:01 UTC, merged