Fix go get
go-gitea/gitea pull request #14758
Opened 2021-02-20 13:15 UTC by lunny

Fix broken go get

2021-02-20 16:29 UTC, zeripath approved these changes

2021-02-20 16:31 UTC, 6543 approved these changes

2021-02-20 17:33 UTC, zeripath requested changes
blocking as per @techknowlogick

2021-02-20 20:17 UTC, techknowlogick commented on routers/routes/web.go
> +	branchName := "master"
Instead of master here, could you use Default branch from settings?

2021-02-21 09:19 UTC, lunny commented
@techknowlogick @zeripath Done.

2021-02-21 12:58 UTC, 6543 approved these changes

2021-02-21 14:27 UTC, zeripath approved these changes

2021-02-21 16:51 UTC, merged