Migrate to Go-JSON
go-gitea/gitea pull request #14914
Opened 2021-03-06 21:49 UTC by zeripath

Following advice from @silverwind and local testing there appears to be
considerable further improvement switching to go-json over jsoniter

Revert #14841 

Signed-off-by: Andrew Thornton <art27@cantab.net>

2021-03-06 22:45 UTC, zeripath commented
Well that's very interesting - the whole thing breaks!

@silverwind you might wanna take a look

2021-03-07 15:17 UTC, a1012112796 commented
I think this is ``refactor`` rather than ``feature``

2021-03-08 13:40 UTC, silverwind commented
Hmm, I hope we did not hit a bug in that module. I'm certainly worried it might now be as stable as the other alternatives.

2021-03-16 21:41 UTC, silverwind commented
Probably need to wait on next version of `go-json` which may have some of these crashes fixed (https://github.com/goccy/go-json/commit/4167aefe08213818e5de6914dd6a9d9bea626bf6).

2021-03-21 14:08 UTC, silverwind commented
[0.4.8 is out](https://github.com/goccy/go-json/releases/tag/v0.4.8), please try an update.

2021-03-21 15:26 UTC, silverwind commented
Still a crash in there along with some odd test failures.

2021-03-31 19:59 UTC, zeripath commented
nope - still crashes.

2021-03-31 20:21 UTC, silverwind commented
https://github.com/goccy/go-json/issues/169

2021-04-01 09:23 UTC, silverwind commented
Can you try adding [this debug option](https://github.com/goccy/go-json/issues/169#issuecomment-811597199) to the code [here](https://github.com/go-gitea/gitea/blob/3ec2f45f5c719af98b1c1dfc690405e4bd15944c/modules/context/context.go#L373)? I guess that would be easier than me trying to reproduce what the test suite does locally.

2021-04-02 03:42 UTC, 6543 commented
while running #15250 with master and this head branch ... I did not really notice any difference

2021-04-02 04:07 UTC, silverwind commented
Yeah it's likely that those performance claims are exaggerated, or that we just don't do enough JSON encoding that it makes a significant difference.

2021-04-02 09:10 UTC, silverwind commented
[0.4.10](https://github.com/goccy/go-json/releases/tag/v0.4.10) is out with a fix for our crash, please update once more.

2021-04-02 10:22 UTC, zeripath commented
@silverwind I've given you collaborator access to my fork - so feel free to update

2021-04-05 21:20 UTC, silverwind commented
Still another bug present, this time in the decoder it seems. Will check out later.

2021-05-09 22:00 UTC, zeripath commented
0.5.0 is out so I'll try to update this again at some point

2021-05-21 19:49 UTC, silverwind commented
Bumped to 0.5.1

2021-05-21 20:23 UTC, silverwind commented
Not sure if I screwed up or this is a module bug:

```
could not import github.com/goccy/go-json (/drone/src/vendor/github.com/goccy/go-json/encode.go:262:21: DebugRun not declared by package vm_escaped
```

2021-07-24 16:25 UTC, 6543 commented on modules/json/json.go
>  // Indent implements Interface, since jsoniter don't support Indent, just use encoding/json's
```suggestion
// Indent implements Interface
```

2021-07-24 18:53 UTC, techknowlogick commented on CONTRIBUTING.md
> +  "github.com/goccy/go-json"
This should be moved above, and referenced as `"code.gitea.io/gitea/modules/json"`

2021-08-11 19:16 UTC, zeripath commented
OK so looking a bit more closely at the first unit-test error

```json
{
  "push_only":true,
  // ... nil values ...
  {
    "push":true,
    // ... more nil values ...
  }
}
``` doesn't seem to get unmarshalled properly in to  ```go
models.HookEvent{PushOnly:true, ..., HookEvents:models.HookEvents{Push:true, ...}}
``` instead becomes: ```go
models.HookEvent{PushOnly:true, ..., HookEvents:models.HookEvents{Push:false, ...}}
```

2021-08-11 19:37 UTC, DasSkelett commented
As someone who followed the development of goccy/go-json for a few months, I can not recommend to put it in any sort of production setup as of now. While it is very fast compared to alternatives, it is very much alpha quality in my eyes. I would not want to see it already used in Gitea as Gitea user.
Especially if JSON encoding/decoding is not part of "the critical code path" that somehow limits performance of the whole server, I would not risk it. Maybe give it some time and keep an eye on it, check back when it hits 1.0.0.

2021-08-11 19:42 UTC, zeripath commented
@DasSkelett I am in agreement with you on this. Whilst Goccy appears interesting there still appear to be several very important bugs.

https://github.com/goccy/go-json/issues/270

2021-08-12 10:25 UTC, silverwind commented
Maybe close this PR and revisit once it's 1.0.

2021-08-12 10:38 UTC, zeripath commented
I'm happy to keep updating this tbh. It's a good way to keep an eye on whether this is ready or not.

2021-08-12 10:50 UTC, zeripath commented
```
--- FAIL: TestHTTPClientDownload (0.00s)
    http_client_test.go:255: 
        	Error Trace:	http_client_test.go:255
        	Error:      	Should be true
        	Test:       	TestHTTPClientDownload
        	Messages:   	case 1: 'not at beginning of value' should contain 'invalid json'
2021/08/12 11:25:11 ...ules/lfs/endpoint.go:73:endpointFromURL() [E] lfs.endpointFromUrl: unknown url
2021/08/12 11:25:11 ...s/lfs/http_client.go:106:batch() [E] Error decoding json: not at beginning of value
2021/08/12 11:25:11 ...s/lfs/http_client.go:106:batch() [E] Error decoding json: not at beginning of value
--- FAIL: TestHTTPClientUpload (0.00s)
    http_client_test.go:356: 
        	Error Trace:	http_client_test.go:356
        	Error:      	Should be true
        	Test:       	TestHTTPClientUpload
        	Messages:   	case 1: 'not at beginning of value' should contain 'invalid json'
FAIL
```

This one appears to be a difference in the way invalid json is reported.

2021-08-12 10:52 UTC, silverwind commented
Yeah, some error messages like that do not seem to match `encodings/json`, I guess we should report as go-json aims to be a drop-in replacement.

2021-08-12 17:11 UTC, zeripath commented
OK it finally looks like we're passing tests! 

I think https://github.com/goccy/go-json/issues/275 needs to be fixed and we need to test actually running gitea with this backend but it might actually be getting close.

2021-10-16 16:50 UTC, zeripath commented
OK GoCcy now works. 

My suspicion is that we shouldn't run with goccy by default but question is whether we can make the JSON variant selectable.

The problem is that as it currently stands `modules/json.DefaultJSONHandler` is not concurrent safe so we should set choose the JSON variant right at the start of gitea before any other goroutines start that might use it. This likely precludes its use in `setting.NewContext`.

Currently I've provided a way for the choice to be compiled in at link time by overwriting a variable at link time. e.g. `LDFLAGS="-X code.gitea.io/gitea/modules/json.DefaultJSONHandlerType=std"`.

2021-10-21 12:14 UTC, lunny commented on modules/json/json.go
> +		DefaultJSONHandlerType = "jsoniter"
fallthrough

2022-01-20 00:41 UTC, techknowlogick approved these changes

2022-01-20 07:47 UTC, wxiaoguang commented
I also have the question why do we need to make JSON library configurable.

Does it bring more benefits than the complexity?

2022-01-20 08:02 UTC, lunny requested changes
Sorry I will against make it configurable for end users. It should be a build tag.

2022-01-20 08:25 UTC, wxiaoguang commented
> Sorry I will against make it configurable for end users. It should be a build tag.

I would not even introduce a build tag. If I find something is good enough, just I will use it.

If there is no real benefit, we do not need to introduce too many options/tags.

2023-03-16 22:35 UTC, silverwind commented
Just checking the issue tracker of `go-json`, it still has crash bugs. Maybe revisit again in a few years if it ever becomes crash-free. 

I suggest sticking to `encoding/json`, as it will receive the more developer attention than those unstable/abandoned hobby projects.

2023-03-17 04:14 UTC, lunny commented
> Just checking the issue tracker of `go-json`, it still has crash bugs.
> 
> I suggest sticking to `encoding/json`, as it will receive much more developer attention than those unstable/abandoned hobby projects and is bound to only get faster over time.

I suggest we can close this one and open a new when something is ready.  @zeripath

2023-03-18 16:55 UTC, zeripath commented
When I last updated and fixed this PR go-json was working completely fine for Gitea - but the potential issue of there being bugs was a reason why I provided the configuration variable which some reviewers did not like.

@silverwind we're already using json-iterator over encoding/json and I would note that encoding/json has not increased in speed significantly for the entire period time I have been involved in gitea. 

However, it's clear that this PR is not going to be merged so I will close it.

2023-03-18 16:55 UTC, closed without merging

2023-03-18 16:57 UTC, silverwind commented
I recommend dropping `json-iterator` as well. It has a number of mind-bogging bugs. Gitea might not hit them currently, but it can in the future.

2023-03-18 17:19 UTC, zeripath commented
There is a *considerable* time penalty to using encoding/json over jsoniterator. You are more than welcome to write the PR and fix the multiple issues were we have relied on jsoniterator error interpretation (this PR has the fixes for those) and then do the performance tests to prove this.

2023-03-18 17:31 UTC, silverwind commented
I guess we shouldn't try to fix what aint broken then.

On topic of benchmarks, I do find https://medium.com/geekculture/my-golang-json-evaluation-20a9ca6ef79c from 2021, so I guess you are right, `encodings/json` is worst:

![image](https://user-images.githubusercontent.com/115237/226123223-b6bec96b-33ff-443d-a102-00561152c1d9.png)