Migration to change mirror interval from int to bigint
go-gitea/gitea pull request #1504
Opened 2017-04-17 15:51 UTC by cez81

Fix for #1496. When using MySQL or PostgreSQL migration to v27 didn't alter the column type to bigint (#1407). This new migration will alter the column type and set all mirror intervals that are < Mirror.MinInterval to Mirror.DefaultInterval.

2017-04-17 17:41 UTC, cez81 commented on models/migrations/v29.go
> +	_, err = x.Query("ALTER TABLE mirror MODIFY `interval` BIGINT;")
This might be better?
`if engine.Dialect().DataSourceName() == "mysql" { engine.Exec("ALTER TABLE mirror MODIFY interval BIGINT"); }`

2017-04-17 18:56 UTC, cez81 commented on models/migrations/v29.go
> +	_, err = x.Query("ALTER TABLE mirror MODIFY `interval` BIGINT;")
Confirmed in Postgres #1505

2017-04-18 01:07 UTC, lunny requested changes

2017-04-18 01:07 UTC, lunny commented on models/migrations/v29.go
> +	case "sqlite3":
missing `mssql`

2017-04-18 01:07 UTC, lunny commented on models/migrations/v29.go
> +		_, err = x.Exec("ALTER TABLE mirror MODIFY `interval` BIGINT")
why not use `sess.Exec` since we have in a transaction?

2017-04-20 22:16 UTC, cez81 commented on models/migrations/v29.go
> +	case "sqlite3":
Added

2017-04-21 01:14 UTC, lunny approved these changes

2017-04-21 14:06 UTC, lunny commented
LGTM

2017-04-21 14:19 UTC, sapk commented
Doesn't this fix need also change in models/migrations/v27.go ? Since the failed migration will still occur on applying v27 before this migration ?

2017-04-21 14:25 UTC, sapk commented
In fact all this change should be done in v27 since normally failing migration would stop the migration and people would be in blocked in v26 ?

2017-04-21 14:26 UTC, lunny commented
According to https://github.com/go-gitea/gitea/issues/1496, there is no error on migration v27.

2017-04-21 14:29 UTC, lunny commented
Yes. I'm wrong. @cez81 You are right. You should change the migration v27 but not add a new one.

2017-04-25 17:29 UTC, strk commented on models/migrations/v27.go
> +		Interval time.Duration
Are 5 fields being dropped here from the Mirror struct ? Is this intentional ? Would it affect database structure ?

2017-04-25 17:29 UTC, strk commented on models/migrations/v27.go
> +		_, err = sess.Exec("ALTER TABLE mirror ALTER COLUMN `interval` SET DATA TYPE bigint")
I dunno if XORM takes care of this @lunny but PostgreSQL quotes for identifiers should be doublequote, not backtick.

2017-04-25 17:31 UTC, cez81 commented on models/migrations/v27.go
> +		Interval time.Duration
No, just don't need them during the migration. As I understand it Xorm will notice and warn but fields are still there. Same as repo struct above. It has more fields not listed.

2017-04-25 17:33 UTC, cez81 commented on models/migrations/v27.go
> +		_, err = sess.Exec("ALTER TABLE mirror ALTER COLUMN `interval` SET DATA TYPE bigint")
Good catch, I haven't used PostgreSQL.

2017-04-25 18:17 UTC, cez81 commented on models/migrations/v27.go
> +		_, err = sess.Exec("ALTER TABLE mirror ALTER COLUMN `interval` SET DATA TYPE bigint")
Looks like SQL Server also uses doublequotes.

2017-04-25 22:06 UTC, cez81 commented
Rebased to pass Drone build

2017-04-26 00:40 UTC, lunny commented on models/migrations/v27.go
> +		Interval time.Duration
^

2017-04-29 10:22 UTC, bkcsoft commented
LGTM

2017-04-30 02:08 UTC, merged