API: Add repo mirror sync endpoint
go-gitea/gitea pull request #1508
Opened 2017-04-18 13:00 UTC by cez81

For stab at the API, please bear with me :)
Add mirror sync endpoint to the API.
`/repos/:owner/:repo/mirror-sync`

2017-04-18 14:00 UTC, appleboy approved these changes

2017-04-19 07:21 UTC, bkcsoft commented
LGTM

Small concise PRs that does _one thing only_ ❤️

2017-04-19 07:23 UTC, bkcsoft requested changes

2017-04-19 07:23 UTC, bkcsoft commented on routers/api/v1/repo/repo.go
> +	ctx.Status(202)
I'd go with 200 or 201 here. `202 Accepted` doesn't make any sense to me :)

https://http.cat/202

2017-04-19 07:58 UTC, bkcsoft approved these changes

2017-04-19 08:00 UTC, appleboy commented
LGTM wait CI build.

2017-04-19 08:01 UTC, bkcsoft commented
Let L-G-T-M WORK!

2017-04-19 08:40 UTC, lunny commented on routers/api/v1/repo/repo.go
> +	ctx.Status(202)
I found many place 202 and don't know the difference between 200, 201 and 202.

2017-04-19 09:53 UTC, strk commented
ready to merge (but still lacks unit test for being considered a perfect PR :)

2017-04-19 11:09 UTC, merged