feat: add download count field and unit testing.
go-gitea/gitea pull request #1512
Opened 2017-04-19 07:11 UTC by appleboy

* Add download count field in `attachment` table.
* Add unit testing.

2017-04-19 07:14 UTC, strk commented
It takes a migration to add that new field, right ?

2017-04-19 07:17 UTC, appleboy commented
@strk Yes.

2017-04-19 07:31 UTC, bkcsoft requested changes
Otherwise LGTM

2017-04-19 07:31 UTC, bkcsoft commented on models/attachment_test.go
> +	assert.NoError(t, err)
`assert.Equal(t, attachment.DownloadCount, int64(0))` ?

2017-04-19 07:36 UTC, appleboy commented on models/attachment_test.go
> +	assert.NoError(t, err)
@bkcsoft Done!

2017-04-19 07:37 UTC, appleboy commented on models/attachment_test.go
> +	assert.NoError(t, err)
See https://github.com/go-gitea/gitea/pull/1512/commits/8278ac976780fff9a42d2e1bbffba37a480b55e5

2017-04-19 07:59 UTC, bkcsoft approved these changes

2017-04-19 08:00 UTC, bkcsoft commented
LGTM

2017-04-19 10:02 UTC, strk commented
isn't this still lacking a migration ?

2017-04-19 12:35 UTC, bkcsoft requested changes

2017-04-19 12:35 UTC, bkcsoft commented on models/attachment.go
> +	DownloadCount int64
Instead of migration, do this:
```go
  DownloadCount int64 `xorm:"DEFAULT 0"`
```

2017-04-19 13:42 UTC, appleboy commented on models/attachment.go
> +	DownloadCount int64
Done https://github.com/go-gitea/gitea/pull/1512/commits/e35bbb2f1b2e195ab02de1c606367056e486de76

2017-04-19 14:09 UTC, strk commented on models/attachment.go
> +	DownloadCount int64
I remember @lunny calling for always adding a migration, not sure why

2017-04-19 14:58 UTC, lunny commented on models/attachment.go
> +	DownloadCount int64
It's better to do that. I think we can begin to ask all schema changes should use https://github.com/go-xorm/xorm/tree/master/migrate

2017-04-20 02:22 UTC, lunny commented
LGTM

2017-04-20 02:31 UTC, merged