fixed error calling eq: incompatible types for comparison
go-gitea/gitea pull request #15156
Opened 2021-03-25 15:48 UTC by BenKluwe

This pull requests fixes an error in the templates/graph/svgcontainer.tmpl file.

full error:

```
500 internal server error
template: repo/graph/svgcontainer:12:43: executing "repo/graph/svgcontainer" at <eq $glyph.Glyph '.'>: error calling eq: incompatible types for comparison
```

This was caused by an _ symbol in the output of the git graph command. When coming across '.', go templates interprets the . character as per https://golang.org/pkg/text/template/, second paragraph:

`Execution of the template walks the structure and sets the cursor, represented by a period '.' and called "dot", to the value at the current location in the structure as execution proceeds.`

Adding a \ eliminates interpretation and allows the code to proceed.

2021-03-25 16:01 UTC, lunny approved these changes

2021-03-26 11:30 UTC, a1012112796 approved these changes

2021-03-26 15:10 UTC, techknowlogick requested changes

2021-03-26 15:10 UTC, techknowlogick commented on templates/repo/graph/svgcontainer.tmpl
> +					{{- else if or (eq $glyph.Glyph '-') (eq $glyph.Glyph '\.') -}}
Per our tests this is resulting in:
```
panic: template: repo/graph/svgcontainer:12: invalid syntax
```

2021-03-26 15:45 UTC, BenKluwe commented
checked that this doesn't happen on latest commit so no need to merge. However, I was running off of commit ad2a288622c7bbf53b8670e136e2e1418331b121 and this was a necessary change to get the commit graph to work (also didn't cause any compilation errors).

2021-03-26 15:45 UTC, closed without merging