Fix wrong user returned in API (#15139)
go-gitea/gitea pull request #15151
Opened 2021-03-25 07:10 UTC by sotho

The API call: GET /repos/{owner}/{repo}/pulls/{index}/reviews/{id}/comments
returns always the reviewer, but should return the poster.

Co-authored-by: 6543 <6543@obermui.de>
Co-authored-by: zeripath <art27@cantab.net>

2021-03-25 07:16 UTC, 6543 approved these changes

2021-03-25 11:16 UTC, sotho commented
@6543 I think we should re-work the fix, see https://github.com/go-gitea/gitea/pull/15139#issuecomment-806507139

2021-03-25 19:36 UTC, 6543 requested changes
Blocking until <https://github.com/go-gitea/gitea/pull/15139#issuecomment-806507139> got solved

2021-03-25 19:48 UTC, sotho commented
@6543: How would you like that I proceed?
I do another pull request on master to correct the code (change the ReviewID back), then change the commit of the two PR for v1.3 and v1.4?

2021-03-25 20:02 UTC, zeripath approved these changes

2021-03-26 01:39 UTC, 6543 commented on modules/convert/pull_review.go
> +					ReviewID:     comment.PosterID,
```suggestion
					ReviewID:     review.ID,
```

2021-03-26 02:48 UTC, 6543 approved these changes

2021-03-26 03:20 UTC, merged