Rework Token API comments
go-gitea/gitea pull request #15162
Opened 2021-03-25 22:32 UTC by ianw

Move the token API discussion into a common section discussing the
generation and listing of the tokens.  Add a note on the display of
the sha1 during creation and listing.

2021-05-14 14:02 UTC, noerw requested changes

2021-05-14 14:02 UTC, noerw commented on docs/content/doc/developers/api-usage.en-us.md
> +You can also create an API key token via your Gitea installation's web
I'd put this first in this section as it is very short, and doesn't get lost in the API noise ;)

2021-05-14 14:02 UTC, noerw commented on docs/content/doc/developers/api-usage.en-us.md
> +As of v1.8.0 of Gitea, if using basic authentication with the API and
Reword so it's clearer that this is only for 2FA. And we don't need to hint at changes from 1.8, released in 2019 anymore ;)
```suggestion
To use the API with basic authentication with two factor authentication
enabled, you'll need to send an additional header that contains the one
time password (6 digitrotating token).
An example of the header is `X-Gitea-OTP: 123456` where `123456`
is where you'd place the code from your authenticator.
Here is how the request would look like in curl:
```

2021-05-16 07:31 UTC, 6543 approved these changes

2021-05-16 07:32 UTC, 6543 commented
@ianw pleace resolve conflicts

2021-05-16 11:06 UTC, noerw commented
@6543 that github code review suggestion thing messed things up (how do your reference multiple lines to be replaced in that UI anyway?)

2021-05-16 13:26 UTC, noerw approved these changes

2021-05-16 13:51 UTC, merged