Fix inline octicon vertical alignment (#15281)
go-gitea/gitea pull request #15366
Opened 2021-04-09 11:28 UTC by CL-Jeremy

Backport #15281

2021-04-09 12:07 UTC, zeripath approved these changes

2021-04-09 12:11 UTC, zeripath commented
ah the original has not been approved yet! my LGTM was therefore likely premature!

2021-04-09 22:12 UTC, techknowlogick commented
@CL-Jeremy are you in our discord? I'd like to send you a message there

2021-04-30 19:15 UTC, 6543 requested changes
#15281 not lgtm & merged yet

2021-06-18 00:31 UTC, closed without merging