Add possibility to make branch in branch page (#15911)
go-gitea/gitea pull request #15960
Opened 2021-05-23 13:40 UTC by Viktor-Yakovchuk

Add possibility to make branch in branch page
in the area next to Download and Delete buttons.
It is a more intuitive place in the interface
compared to what is already there.

Signed-off-by: Viktor Yakovchuk <viktor@yakovchuk.net>

2021-05-23 13:41 UTC, Viktor-Yakovchuk commented
I have posted screenshots in the issue #15911

2021-05-23 14:16 UTC, lafriks requested changes, later dismissed

2021-05-23 14:16 UTC, lafriks commented on options/locale/locale_ru-RU.ini
> +branch.create_new_branch=Создать ветку из ветки:
do not add translations in PR

2021-05-23 14:32 UTC, Viktor-Yakovchuk commented on options/locale/locale_ru-RU.ini
> +branch.create_new_branch=Создать ветку из ветки:
Thanks, fixed

2021-05-23 15:19 UTC, Viktor-Yakovchuk commented
continuous-integration seams failed with problem not related to this patch
amd64 failed but arm passed

2021-05-23 18:29 UTC, noerw approved these changes

2021-05-23 21:54 UTC, zeripath commented on templates/repo/branch/list.tmpl
> +											<div class="ui basic jump button icon poping up show-create-branch-modal" data-branch-from="{{EscapePound .Name}}" data-content="{{$.i18n.Tr "repo.branch.new_branch_from" (.Name)}}" data-v
```suggestion
											<div class="ui basic jump button icon poping up show-create-branch-modal" data-branch-from="{{EscapePound .Name}}" data-content="{{$.i18n.Tr "repo.branch.new_branch_from" .Name}}" data-variation="tiny inverted" data-position="top right" data-modal="#create-branch-modal" data-name="{{.Name}}">
```

2021-05-23 21:56 UTC, zeripath approved these changes

2021-05-24 14:55 UTC, zeripath commented
Make lgtm

2021-05-24 14:57 UTC, merged