Append to existing trailers in generated squash commit message
go-gitea/gitea pull request #15980
Opened 2021-05-25 17:53 UTC by jpraet

If the PR description already contains a trailer section (for example with a Signed-off-by: header), then just append the gitea-generated trailers (Co-authered-by, Reviewed-on, ...) to this existing section.

2021-05-26 18:51 UTC, zeripath commented on services/pull/pull.go
> +		commitMessageTrailersPattern := regexp.MustCompile(`(^|.*\n\n)([\w-]+: [^\n]+)(\n[\w-]+: [^\n]+)*$`)
Compile regexps once. Recompiling them every request is a bad idea.

2021-05-26 18:52 UTC, zeripath requested changes
as per comment

2021-06-20 21:59 UTC, zeripath commented
Thanks for the change. I'm still a bit suspicious about the regexp.

For example:

```
(^l.*\n\n)
```

Why not:

```
(?:^|\n\n)
```

Are you actually capturing the groups for some reason? If not use non capturing. (It can actually make a significant difference in time and memory allocation.)

Don't use `.*` if you don't need it. In fact in non 's' mode`.` doesn't capture `\n` so I'm not certain what the `.*` is looking for.

Your regexp also seems to require that trailers don't end with a newline which seems contrary to git which prefers messages end with a new line.

2021-06-21 18:10 UTC, jpraet commented
I'm a bit rusty with regex. It should be better now: https://regex101.com/r/UDBQe0/1

2021-06-21 18:29 UTC, zeripath commented on services/pull/pull.go
> +var commitMessageTrailersPattern = regexp.MustCompile(`(?:^|\n\n)(?:[\w-]+: [^\n]+\n*)+$`)
OK testing from git interpret-trailers I think this needs to be, at least:

```suggestion
var commitMessageTrailersPattern = regexp.MustCompile(`(?:^|\n\n)(?:[\w-]+[:=][^\n]+\n)*(?:[\w-]+: [^\n]+)\n*$`)
```

How trailers can be folded, see https://git-scm.com/docs/git-interpret-trailers

> When reading trailers, there can be whitespaces after the token, the separator and the value. There can also be whitespaces inside the token and the value. The value may be split over multiple lines with each subsequent line starting with whitespace, like the "folding" in RFC 822.

Which would make this:

```suggestion
var commitMessageTrailersPattern = regexp.MustCompile(`(?:^|\n\n)(?:[\w-]+[:=][^\n]+\n(?: [^\n]*\n)*)*(?:[\w-]+: [^\n]+(?:\n [^\n]*)*)\n*$`)
```

(I think)

2021-06-21 18:33 UTC, zeripath commented on services/pull/pull.go
> +var commitMessageTrailersPattern = regexp.MustCompile(`(?:^|\n\n)(?:[\w-]+: [^\n]+\n*)+$`)
```
echo -n 'Fix #1546                                                                         [19:26:27]

Signed-off-by: Not a trailer

Signed-off-by:Alice <alice@example.com>
Signed-off-by:   Bob <bob@example.com>
' | git interpret-trailers --parse
```

```
echo -n 'Fix #1546                                                                         [19:26:27]

Signed-off-by:Not a trailer

Signed-off-by:Alice <alice@example.com>
Signed-off-by:   Bob <bob@example.com>' | git interpret-trailers --parse
```

```
echo -n 'Fix #1546

Signed-off-by:Not a trailer

Signed-off-by:Alice <alice@example.com>
Signed-off-by:   Bob <bob@example.com>


' | git interpret-trailers --parse
```

```
echo -n 'Fix #1546

Signed-off-by:Not a trailer

Signed-off-by:Alice <alice@example.com>
Folded: This is a folded value
 with folded results
   preceding spaces?
Signed-off-by:   Bob <bob@example.com>' | git interpret-trailers --parse
```

2021-06-21 20:43 UTC, zeripath approved these changes

2021-06-25 11:08 UTC, noerw approved these changes

2021-06-25 11:08 UTC, noerw commented on services/pull/pull_test.go
> +	assert.False(t, commitMessageTrailersPattern.MatchString("Message body not correctly separated from trailer section by empty line.\nSigned-of-by: Bob <bob@example.com>"))
tiny typo
```suggestion
	assert.False(t, commitMessageTrailersPattern.MatchString("Message body not correctly separated from trailer section by empty line.\nSigned-off-by: Bob <bob@example.com>"))
```

2021-06-25 17:01 UTC, merged