fix use SMTP auth when port 25 is ban problem
go-gitea/gitea pull request #16104
Opened 2021-06-08 08:38 UTC by jnan88

Solve the authentication timeout problem caused by the unavailability of port 25 for SMTP authentication. When using TLS mode, use TLS connection for SMTP communication

2021-06-13 21:31 UTC, techknowlogick requested changes
I'm not sure what problem this PR is trying to solve. It is already possible to connect to alternative SMTP ports, also using TLS.

2021-06-15 08:27 UTC, jnan88 commented
> I'm not sure what problem this PR is trying to solve. It is already possible to connect to alternative SMTP ports, also using TLS.

The current code can configure TLS, but now it is based on the support of 25 to jump to use TLS. When 25 is not available, an unlinkable exception will be generated here. If TLS is confirmed in this modification, TLS will be directly used to connect, so as to avoid the abnormal unavailability when port 25 is not available

2021-06-15 08:37 UTC, jnan88 commented on models/login_source.go
>  	c, err := smtp.Dial(fmt.Sprintf("%s:%d", cfg.Host, cfg.Port))
```suggestion
	c, err := smtp.Dial(fmt.Sprintf("%s:%d", cfg.Host, cfg.Port))
```
Only non TLS links are used here

2021-06-15 08:38 UTC, jnan88 commented on models/login_source.go
> +	tlsClient, err := tls.Dial("tcp", addr, &tls.Config{InsecureSkipVerify:cfg.SkipVerify})
```suggestion
	tlsClient, err := tls.Dial("tcp", addr, &tls.Config{InsecureSkipVerify:cfg.SkipVerify})
```
New TLS connection

2021-06-15 08:39 UTC, jnan88 commented on models/login_source.go
> +			auth = smtp.PlainAuth("", login, password, fmt.Sprintf("%s:%d", cfg.Host, cfg.Port))
```suggestion
			auth = smtp.PlainAuth("", login, password, fmt.Sprintf("%s:%d", cfg.Host, cfg.Port))
```
When TLS connection is used, ports need to be added at the same time

2021-08-03 17:27 UTC, zeripath commented
Hi @jnan88 I've finally got round to looking at this - apologies for conflicting your PR.

I now think I understand the problem.

I think we simply have to make a breaking change with the configuration of this source and make it more like the configuration for the mailer.

That is:

1. If TLS is true or port = 465 use SMTPS
2. If the SMTP server offers STARTTLS and we're not on TLS : use STARTTLS

To that end I'm going to propose a breaking change PR which will attempt to rationalise the configuration.

2021-08-11 20:42 UTC, closed without merging