Changelog v1.14.3
go-gitea/gitea pull request #16131
Opened 2021-06-10 14:32 UTC by 6543

as title

2021-06-10 14:34 UTC, 6543 commented
just blocked by #16068 and it's backport

2021-06-10 21:31 UTC, 6543 commented on CHANGELOG.md
> +  * Fix bug on getIssueIDsByRepoID (#16119) (#16124)
```suggestion
  * Fix bug on getIssueIDsByRepoID (#16119) (#16124)
  * Set self-adjusting deadline for connection writing (#16068) (#16123)
```

2021-06-10 21:32 UTC, 6543 reviewed
ready from my side :rocket:

2021-06-10 22:15 UTC, tomaswarynyca commented
Could #16130 be fixed before releasing the new version?

2021-06-11 00:36 UTC, techknowlogick requested changes, later dismissed
Blocking per conversation in discord.

2021-06-14 20:14 UTC, 6543 commented on CHANGELOG.md
> +  * Move sans-serif fallback font higher than emoji fonts (#15855) (#15892)
```suggestion
  * Removable media support to snap package (#16136) (#16138)
  * Move sans-serif fallback font higher than emoji fonts (#15855) (#15892)
```

2021-06-17 14:43 UTC, bminer commented
Just want to ensure #15859 ends up in the Changelog (I saw #15758, but this PR will not work without the other one). Did #15859 get backported?

2021-06-18 13:42 UTC, khmarbaise approved these changes

2021-06-18 13:46 UTC, KN4CK3R approved these changes

2021-06-18 14:19 UTC, zeripath commented on CHANGELOG.md
> +  * Encrypt migration credentials at rest (#15895) (#16187)
```suggestion
  * Encrypt migration credentials at rest (#15895) (#16187)
  * Only check access tokens if they are likely to be tokens (#16164) (#16171)
```

2021-06-18 14:20 UTC, zeripath commented on CHANGELOG.md
> +  * Only check access tokens if they are likely to be tokens (#16164) (#16171)
```suggestion
```

2021-06-18 14:20 UTC, zeripath commented on CHANGELOG.md
> +  * Add missing SameSite settings for the i_like_gitea cookie (#16037) (#16039)
```suggestion
```

2021-06-18 14:21 UTC, zeripath commented on CHANGELOG.md
> +  * Fix setting of SameSite on cookies (#15989) (#15991)
```suggestion
```

2021-06-18 14:53 UTC, zeripath approved these changes

2021-06-18 15:25 UTC, merged

2021-06-18 15:31 UTC, 6543 commented
-> #16196