[WIP] Multi-stage dockerfile
go-gitea/gitea pull request #1615
Opened 2017-04-26 15:37 UTC by sapk

Implement multi-stage dockerfile. This will permit cleaner build and maybe if FROM are multi-arch to have only one dockerfile.

2017-04-28 16:50 UTC, sapk commented
This will need at least docker/moby@v17.05.0-ce-rc2 for multi-stage to work. So this PR is a little in advance. This will dependency is only for building multi-stage. The image resulting will be able to run even with older docker/moby version.

2017-04-28 18:40 UTC, bkcsoft requested changes

2017-04-28 18:40 UTC, bkcsoft commented on Dockerfile
> -MAINTAINER Thomas Boerger <thomas@webhippie.de>
Why remove the Maintainer? Add yourself instead :trollface:

2017-04-28 18:40 UTC, bkcsoft commented on Dockerfile
> +ARG TAGS
Maybe default to `sqlite`?

2017-04-28 18:40 UTC, bkcsoft commented on Dockerfile
> + && go get -u github.com/jteeuwen/go-bindata/...
No need to `go get go-bindata` since it will be fetched by `make generate`

2017-04-28 18:40 UTC, bkcsoft commented on Dockerfile
> +RUN pwd && ls -lah && make clean generate build
Why `pwd && ls -lah` ?

2017-04-28 18:40 UTC, bkcsoft commented on .dockerignore
> -!gitea
this should def. be here if we're building it inside the container now

2017-04-28 18:40 UTC, bkcsoft commented on .dockerignore
> -!gitea
Heck, all there things you've added in here should still go into the first build...

2017-04-28 18:40 UTC, bkcsoft commented on Dockerfile
> + && echo "git:$(date +%s | sha256sum | base64 | head -c 32)" | chpasswd
`echo "git:$(dd if=/dev/urandom bs=24 count=1 | base64)" | chpasswd` (24 byte => base64 => 32 byte)

2017-04-28 18:40 UTC, bkcsoft commented on Dockerfile
> -    /var/cache/apk/* && \
We should still remove the cache...

2017-04-28 18:40 UTC, bkcsoft commented on Makefile
> +docker-build:
Is this stage still required?

2017-04-28 18:45 UTC, bkcsoft commented
I added `status/blocked` since this is blocked on build-server getting Docker 17.05 **stable** 😉

2017-04-28 21:06 UTC, sapk commented on Dockerfile
> +RUN pwd && ls -lah && make clean generate build
Debug ^^

2017-04-28 21:06 UTC, sapk commented on Dockerfile
> -    /var/cache/apk/* && \
I can but with --no-cache it shouldn't

2017-04-28 21:11 UTC, sapk commented on Dockerfile
> -MAINTAINER Thomas Boerger <thomas@webhippie.de>
It's only needed for the published image (last FROM)

2017-04-28 21:15 UTC, sapk commented on Dockerfile
> + && go get -u github.com/jteeuwen/go-bindata/...
I have re-tested and you are right. I remember that one time it ask for it but don't remember why.

2017-04-28 21:16 UTC, sapk commented on Dockerfile
> + && go get -u github.com/jteeuwen/go-bindata/...
I think that it was because `git` wasn't installed so it couldn't be installed and failed after.

2017-04-28 21:17 UTC, sapk commented on Dockerfile
> + && echo "git:$(date +%s | sha256sum | base64 | head -c 32)" | chpasswd
I haven't touch that.

2017-04-28 21:21 UTC, sapk commented on Makefile
> +docker-build:
I have separate it but still keep it if someone want to build binaries via docker.

2017-04-28 21:45 UTC, sapk commented on Dockerfile
> -MAINTAINER Thomas Boerger <thomas@webhippie.de>
And I use the LABEL instruction since MAINTAINER is depraced.

2017-04-28 21:46 UTC, sapk commented on .dockerignore
> -!gitea
At startup docker "clone" local folder to build folder this limit what is copied into workspace but we need

2017-04-28 23:11 UTC, bkcsoft commented on Dockerfile
> -    /var/cache/apk/* && \
Erm no, completely different things... Don't remove this line...

2017-04-28 23:12 UTC, bkcsoft commented on Dockerfile
> + && echo "git:$(date +%s | sha256sum | base64 | head -c 32)" | chpasswd
right, it was more of a "since you're already screwing with it, might as well fix this" :trollface:

2017-04-28 23:20 UTC, sapk commented on Dockerfile
> -    /var/cache/apk/* && \
https://github.com/gliderlabs/docker-alpine/blob/master/docs/usage.md#disabling-cache It seem, it doesn't even need -U also.

2017-04-28 23:24 UTC, sapk commented on Dockerfile
> -    /var/cache/apk/* && \
I have checked after apk --no-cache -> /var/cache/apk is empty.

2017-04-28 23:27 UTC, sapk commented
To test against docker version in master : http://blog.alexellis.io/mutli-stage-docker-builds/#howcanitryitout

2017-04-28 23:30 UTC, bkcsoft requested changes

2017-04-28 23:30 UTC, bkcsoft commented on Makefile
> +docker: TAGS=sqlite
no, `ARG TAGS="sqlite"` in the Dockerfile...

2017-04-28 23:36 UTC, sapk commented on .dockerignore
> -!gitea
After re-thinking if we add all the repo (remove .dockerignore) we could be able to ask to compile a specific version (tag) at build stage via git.

2017-04-29 00:27 UTC, sapk commented
At this stage, Dockerfile should be buildable on platform amd64, arm, aarch64 simply by tapping docker build .

I am figuring out how to build them in drone and do multi-arch image.

2017-04-29 01:33 UTC, sapk commented on Dockerfile
>  ENV USER git
Reminder to myself : Check if this is usefull since this still run with root after.

2017-04-29 10:25 UTC, bkcsoft commented
@sapk There's no way to build this on the drone server until it's upgraded to 17.05 🙂

2017-04-29 10:27 UTC, bkcsoft commented on Dockerfile
> -    /var/cache/apk/* && \
>

2017-04-29 10:28 UTC, bkcsoft approved these changes

2017-04-29 11:42 UTC, sapk commented
@bkcsoft we could by using the method explain in http://blog.alexellis.io/mutli-stage-docker-builds/#howcanitryitout but this would make use build last version of docker and start a container with this version in it and build this Dockerfile in it. Not really efficient.

We could also do the same without docker building step and re-use release tar.gz

2017-04-29 12:43 UTC, klud1 commented
> I am figuring out how to build them in drone and do multi-arch image.

@sapk  I know it's not matter of this PR, but it'd be great if you make a HOW-TO on making a multi arch image, i'm interested in doing so as well.

2017-04-29 13:17 UTC, sapk commented
@klud1 a multi-arch image is just a fake image linking to various image corresponding for arch (documented in files like https://github.com/sapk/dockerfiles/tree/master/alpine-multi) that you push with github.com/estesp/manifest-tool (you can see command-line example in https://github.com/sapk/dockerfiles/blob/master/.travis.yml that update the refs).
 
So you build a image for each arch and reference them in a .yml 

For the multi-arch part, I use https://github.com/portainer/docker-manifest as a reference and use multiarch/alpine for a good base to have image on most arch.

2017-04-29 13:41 UTC, klud1 commented
@sapk amazing, thank you so much.

2017-04-30 18:04 UTC, sapk commented
I tested to do a docker build of the multi-stage image with multi-arch sapk/alpine-multi as base and this work seamlessly. \o/

I think that it would be more clean to push this change under Dockerfile.multi and keep the olds ones around until the needed version for docker is ready if is is ok with you.

2017-05-01 16:32 UTC, bkcsoft reviewed
otherwise LG-TM

2017-05-01 16:32 UTC, bkcsoft commented on docker/manifest/gitea-1-0-0.yml
> +image: sapk/gitea:1.0.0
What are all these manifests for?

2017-05-01 16:33 UTC, sapk commented on docker/manifest/gitea-1-0-0.yml
> +image: sapk/gitea:1.0.0
For generating multi-arch image that reference the image to corresponding arch.

2017-05-01 16:35 UTC, sapk commented on docker/manifest/gitea-1-0-0.yml
> +image: sapk/gitea:1.0.0
The only part missing is generation of image on arch. This could be done via qemu like https://github.com/multiarch/alpine does.

2017-05-15 14:09 UTC, appleboy commented
We need to waiting for this PR https://github.com/drone-plugins/drone-docker/pull/124 for Drone to support multi-stage build.

2017-05-16 09:40 UTC, sapk commented
Ok so for a little update. 

I remove olds Dockerfile.

The task `make docker` will build gitea/gitea for the platform you are running on (compatible with amd64, arm, arm64). (For this to fully work the multi-arch base gitea/gitea-base need to be set on docker hub by someone with rights. `DOCKER_MANIFEST=docker/manifest/base.yml make docker-multi-update-manifest` )

The tasks `make docker-multi-*` permit to cross-build and do multi-arch image. I don't think this is possible yet with drone-plugins/drone-docker.

2017-05-16 09:55 UTC, sapk commented
It's also possible to choose the version gitea we want in the container via variable `GITEA_VERSION`. It accept any ref that is accepted by `git checkout `

2017-06-16 13:11 UTC, sapk commented
I will break this into multiple PR to ease the process of validation.
- Unify dockerfile with one multi-arch as base. (permit to build the same dockerfile on every platform)
- Multi-stage (permit to have a stage build to limit image size)
- Multi-arch final image (permit to download from docker hub the corresponding image of your running arch with the same name for every platform)

2017-06-16 14:15 UTC, closed without merging