rename context.Query to context.Form
go-gitea/gitea pull request #16562
Opened 2021-07-27 17:00 UTC by lunny

The name `Query` on context derived from macaron is confusing because it should only get query parameters from URL query.
This PR renames `Query` to `Form` as the first step. Next step, we need add the real `Query` methods and change some routers' revocations.

2021-07-27 21:02 UTC, coolaj86 commented
> we need add the real `Query` methods

Why?

`ctx.Req.URL.Query()` is easy to understand without having to be familiar with a particular framework.

Why add layers on top of native Go APIs that are already simple, easy to use, well-understood, with predictable (and desirable) behavior?

2021-07-27 21:25 UTC, lafriks approved these changes

2021-07-27 21:26 UTC, lafriks commented on modules/context/context.go
>  // QueryTrim returns request form as string with default and trimmed spaces
Please fix comments

2021-07-27 21:28 UTC, lafriks commented on modules/context/context.go
>  // QueryTrim returns request form as string with default and trimmed spaces
```suggestion
// FormTrim returns request form as string with default and trimmed spaces
```

2021-07-28 00:49 UTC, 6543 requested changes
I thought it will already work as named ?!?

2021-07-28 01:24 UTC, lunny commented
> > Next step, we need add the real `Query` methods
> 
> Why?
> 
> `ctx.Req.URL.Query()` is easy to understand without having to be familiar with a particular framework.
> 
> Why add layers on top of native Go APIs that are already simple, easy to use, well-understood, well-documented, and that have predictable (and desirable) behavior?
> 
> Wouldn't it be better to go the opposite direction and remove the legacy Gogs/Macaron/Gitea code in favor of cleaner, simpler, native Go code?
> (unless there's a particular missing feature or unexpected caveat in how the native Go code works, of course)
> 
> I would much prefer to use the standard Go and Chi approaches:
> 
> ```go
> str := r.URL.Query().Get(k)
> val := r.FormValue(k)
> ctx := r.Context()
> data := r.Context().Value("data").(*Data)
> tpl := data["something"]
> ```
> 
> I also understand having a few convenience functions or perhaps an object to hold `Data`, as it is presently:
> 
> ```go
> r := ctx.Req
> str := r.URL.Query().Get(k)
> val := r.FormValue(k)
> tpl := ctx.Data["something"]
> ```
> 
> But the idea of adding new APIs that need new documentation around APIs that already work exactly as expected... makes me sad.

These simple wrap functions will help to convert string to int, bool or others. i.e. `QueryInt` will try to convert `r.URL.Query().Get(k)` to int. Since they will be used many places. You have to write `strconv.Atoi` and above codes everywhere.

2021-07-28 01:26 UTC, lunny commented
> I thought it will already work as named ?!?

Like @coolaj86  QueryXXX should warp `r.URL.Query().Get(k)` but not `r.Form.Values`. So rename `Query` to `Form` to make less confusing.

2021-07-28 01:52 UTC, lunny commented on modules/context/context.go
>  // QueryTrim returns request form as string with default and trimmed spaces
done.

2021-07-28 11:30 UTC, 6543 commented
This renamed funct. Are used in api a lot so we should migrate them all to use query directly. What porpuse does this form functions do have beside getting query values?!?

@lunny

2021-07-28 11:32 UTC, 6543 commented
Instead of renaming i propose to refactor it to do what the name sound like or just delete it

2021-07-28 12:57 UTC, 6543 commented
@lunny i would go this way: #16567

if you are ok with it, I'll finish my pull

2021-07-28 13:03 UTC, lunny commented
> @lunny i would go this way: #16567
> 
> if you are ok with it, I'll finish my pull

I'm strongly against that PR because it's wrong.

I agree we need use QueryX for those GET requests, but to make review easier, I would like to make it as two steps. This is the first step to rename QueryX to FormX, next step to add QueryX back and move functions on GET requests to use QueryX .

2021-07-29 01:37 UTC, 6543 approved these changes
one step at a time ...

2021-07-29 01:42 UTC, merged