golint fixed for parts of routers root, dev and org dirs
go-gitea/gitea pull request #167
Opened 2016-11-14 14:52 UTC by lunny

2016-11-14 14:58 UTC, tboerger approved these changes

2016-11-14 14:58 UTC, tboerger commented
LGTM

2016-11-14 15:16 UTC, appleboy commented
👍

2016-11-14 16:48 UTC, andreynering commented
Travis failed

2016-11-14 20:59 UTC, bkcsoft requested changes

2016-11-14 20:59 UTC, bkcsoft commented on routers/dev/template.go
> +// TemplatePreview render only on DEV mode for preview the template
This function always renders if asked, `RUN_MODE` is checked elsewhere

2016-11-14 20:59 UTC, bkcsoft commented on routers/home.go
> +// RepoSearchOptions options when calling search repositories
Maybe drop the additional `options` as it's redundant?

2016-11-14 20:59 UTC, bkcsoft commented on routers/home.go
> +// RenderUserSearch render user search page
This could just be `RenderUserSearch page` :)

2016-11-14 20:59 UTC, bkcsoft commented on routers/home.go
> +	TplHome base.TplName = "home"
Should these really be exported? :confused:

2016-11-14 20:59 UTC, bkcsoft commented on routers/install.go
> +	TplInstall base.TplName = "install"
Exported?

2016-11-14 20:59 UTC, bkcsoft commented on routers/org/members.go
> +	TplMembers base.TplName = "org/member/members"
Exported?

2016-11-14 20:59 UTC, bkcsoft commented on routers/org/org.go
> +	TplCreateOrg base.TplName = "org/create"
Exported?

2016-11-14 20:59 UTC, bkcsoft commented on routers/org/setting.go
> +	TplSettingsOptions base.TplName = "org/settings/options"
Exported?

2016-11-14 20:59 UTC, bkcsoft commented on routers/org/setting.go
> +// Settings render the main settings page
`organization main settings page` ?

2016-11-14 20:59 UTC, bkcsoft commented on routers/org/teams.go
> +	TplTeams base.TplName = "org/team/teams"
Exported?

2016-11-16 06:18 UTC, lunny commented
@bkcsoft Please review again.

2016-11-18 02:19 UTC, bkcsoft reviewed
Don't really care, but worth mentioning

2016-11-18 02:19 UTC, bkcsoft approved these changes

2016-11-18 02:19 UTC, bkcsoft commented
LGTM

2016-11-18 03:03 UTC, merged

2016-11-28 15:59 UTC, lunny commented
resolved #70