Adding #issuecomment to the URL in E-Mail notifications
go-gitea/gitea pull request #1674
Opened 2017-05-04 16:32 UTC by JonasFranzDEV

Reference: #1669

2017-05-04 19:19 UTC, bkcsoft requested changes

2017-05-04 19:19 UTC, bkcsoft commented on models/mail.go
> +	data := composeTplData(subject, body, issue.HTMLURL() + "#" +  comment.HashTag())
There's `comment.HTMLURL()` to replace `issue.HTMLURL() + "#" + comment.HashTag()` ... Also `go-fmt` :)

2017-05-04 19:23 UTC, bkcsoft commented on models/mail.go
> +	data := composeTplData(subject, body, issue.HTMLURL() + "#" +  comment.HashTag())
If you'd like, you can change `comment.HTMLURL()` to do this instead 😄 
```
	return fmt.Sprintf("%s#%s", issue.HTMLURL(), c.HashTag())
```

2017-05-04 19:42 UTC, bkcsoft requested changes
All the changes :trollface:

2017-05-04 19:42 UTC, bkcsoft commented on models/issue_mail.go
> +	SendIssueCommentMail(issue, doer, comment, tos)
Couldn't we merge these 2 (almost identical) functions by doing
```go
if comment != nil {
  SendIssueCommentMail(...)
} else {
  SendIssueActionMail(...)
}
```

2017-05-04 19:42 UTC, bkcsoft commented on models/issue_mail.go
> +
no newline

2017-05-04 19:42 UTC, bkcsoft commented on models/issue_mail.go
> +	if err != nil {
no newline between `set and check`s :)

2017-05-04 19:42 UTC, bkcsoft commented on models/issue_mail.go
> +		return nil, nil, err
the error should still we wrapped:
```go
  return nil, nil, fmt.Errorf("GetWatchers [repo_id: %d]: %v", issue.RepoID, err)
```

2017-05-04 19:42 UTC, bkcsoft commented on models/issue_mail.go
> +		return nil, nil, err
Same here, wrap the error :)

2017-05-04 19:42 UTC, bkcsoft commented on models/issue_mail.go
> +func prepareMailToParticipants(issue *Issue, doer *User) (tos []string, names []string, error error) {
I'm not really a fan for named returns, got a reason to do that?

2017-05-04 19:42 UTC, bkcsoft commented on models/issue_mail.go
> +			return nil, nil, err
Wrap error

2017-05-04 19:42 UTC, bkcsoft commented on models/issue_mail.go
> +	if err = mailIssueActionToParticipants(issue, issue.Poster, mentions); err != nil {
here you'd just call `mailIssueCommentToParticipants(issue, issue.Poster, nil, mentions)` instead

2017-05-04 19:42 UTC, bkcsoft commented on models/issue_mail.go
>  		log.Error(4, "mailIssueCommentToParticipants: %v", err)
technically wrong here, but maybe not later on ;)

2017-05-04 20:30 UTC, bkcsoft requested changes

2017-05-04 20:30 UTC, bkcsoft commented on models/issue_mail.go
>  		log.Error(4, "mailIssueCommentToParticipants: %v", err)
Wrong error-message, otherwise LGTM 🎉

2017-05-04 20:39 UTC, bkcsoft approved these changes

2017-05-04 20:39 UTC, bkcsoft commented
LGTM, but untested

2017-05-04 21:58 UTC, lafriks requested changes

2017-05-04 21:58 UTC, lafriks commented on models/issue_mail.go
> +// mailIssueCommentToParticipants can be used only for comment.
Shouldn't this comment should be changed back to original?

2017-05-04 21:58 UTC, lafriks commented on models/mail.go
> +		data = composeTplData(subject, body, issue.HTMLURL()+"#"+comment.HashTag())
Why comment.HTMLURL is not used here?

2017-05-04 22:02 UTC, JonasFranzDEV commented on models/mail.go
> +		data = composeTplData(subject, body, issue.HTMLURL()+"#"+comment.HashTag())
No because comment.HTMLURL returns an empty string by printing an error to the console (see gitter chat).

2017-05-04 22:11 UTC, lafriks approved these changes
Looks good but have to test it

2017-05-04 22:11 UTC, lafriks commented on models/mail.go
> +		data = composeTplData(subject, body, issue.HTMLURL()+"#"+comment.HashTag())
Ok

2017-05-08 06:35 UTC, bkcsoft commented on models/mail.go
> +		data = composeTplData(subject, body, issue.HTMLURL()+"#"+comment.HashTag())
@JonasFranzDEV Gitter chat is not searchable, mind sharing with the rest of the class? As I'm quite sure there's a better solution to this than re-implementing the wheel 🙂

2017-05-25 02:29 UTC, lunny commented
LGTM

2017-05-25 02:38 UTC, merged