Add configuration option for default permission to create Organizations
go-gitea/gitea pull request #1686
Opened 2017-05-05 15:07 UTC by lafriks

Defaults to false

2017-05-06 12:10 UTC, lunny commented
LGTM

2017-05-08 07:15 UTC, bkcsoft requested changes
Adding new config variables should not break the old behaviour.

2017-05-08 07:15 UTC, bkcsoft commented on conf/app.ini
> +DEFAULT_ALLOW_CREATE_ORGANIZATION = false
Default to `true` otherwise backwards compatability is broken.

2017-05-08 07:15 UTC, bkcsoft commented on public/less/_admin.less
> +			margin-left: 275px;
Why was this change necessary? Got any screenshots of how it looks before and after?

2017-05-08 07:15 UTC, bkcsoft commented on public/less/_admin.less
> +			width: 285px;
Same as above

2017-05-08 07:15 UTC, bkcsoft commented on modules/setting/setting.go
> +	DefaultAllowCreateOrganization bool
This has to default to `true` to not break the old behaviour

2017-05-08 07:27 UTC, appleboy approved these changes

2017-05-08 07:28 UTC, appleboy commented
Please update the default behavior as @bkcsoft suggestions. Otherwise L-G-T-M

2017-05-08 17:13 UTC, cez81 commented on modules/setting/setting.go
> +	Service.DefaultAllowCreateOrganization = sec.Key("DEFAULT_ALLOW_CREATE_ORGANIZATION").MustBool()
You need to set default to true here. Changing app.ini doesn't do anything

2017-05-08 17:17 UTC, lafriks commented on public/less/_admin.less
> +			margin-left: 275px;
Otherwise "Default permission to create Organizations" did not if in, it was cut to something like "Default permission to crea..."

2017-05-08 17:20 UTC, lafriks commented on modules/setting/setting.go
> +	Service.DefaultAllowCreateOrganization = sec.Key("DEFAULT_ALLOW_CREATE_ORGANIZATION").MustBool()
done :+1:

2017-05-08 17:26 UTC, lafriks commented
Changed default to keep backward compatibility but I would like to reconsider more sane default in the future. When adding this setting it should have not introduced such changes in default behavior. I see it could be useful only in deployments where gitea is used as SasS, in private repositories there would mostly also be only one person who will create organizations, in organizations that will do administrators.

2017-05-08 19:16 UTC, bkcsoft approved these changes

2017-05-08 19:16 UTC, bkcsoft commented
LGTM

2017-05-08 19:35 UTC, lafriks commented
LG-TM, please work :)

2017-05-08 19:51 UTC, merged