Adds ForkID property to the repo API
go-gitea/gitea pull request #1687
Opened 2017-05-05 19:07 UTC by guyzmo

hop! 👍

2017-05-05 19:22 UTC, lafriks commented
@guyzmo  you need to create PR to go-gitea/go-sdk to add required field

2017-05-05 20:07 UTC, guyzmo commented
done

2017-05-05 21:27 UTC, guyzmo commented
I just changed the content, to expose `Repository* BaseRepo` as `'parent'` property, instead of an id. because that's more restful.

2017-05-05 22:03 UTC, guyzmo commented
cf [github API](https://developer.github.com/v3/repos/#get), the parent is a full object. The only difference is that the parent does not contain its own parent in the project's tree (to avoid blowing up the connection). Also there's a `source` attribute, that contain the upmost parent project of the tree.

I guess that we can start iteratively, and give the `parent` property as it is currently implemented, at the risk of blowing the connection in case the project tree's branch is huge. Then in a second stage, hack the `parent` property so that it does not contain itself another `parent` property, or at least is set to `null` (and thus `fork=true` + `parent=null` means that there's more).

2017-05-05 23:12 UTC, lafriks commented
This code will panic when `BaseRepo` is `nil`. Also I'm not quite sure if `BaseRepo` will be have value at all before `GetBaseRepo` is called

2017-05-06 11:08 UTC, guyzmo commented
👌, so we need the code to keep calm when `BaseRepo` is `nil`. How?
And also we need to make sure that `BaseRepo` is valued when the API needs it. How?

I don't know the code base enough to tell how to hack that, so any pointers are welcomed ☺

2017-05-06 11:33 UTC, lunny commented
@guyzmo first at all, you should use `govendor update code.gitea.io/sdk` to update the dependency.

2017-05-07 16:50 UTC, lafriks commented
Now that dependency is set correctly you can see that unit tests is failing where BaseRepo is nil

2017-05-07 20:42 UTC, guyzmo commented
So what can be done, how can we make sure it's 👌 when the pointer is `nil` and also that a tentative is made to resolve the parent when not?

2017-05-07 22:12 UTC, lafriks commented
you need to move out assignment up something like:
```go
var parent *api.Repository
if repo.BaseRepo != nil {
    parent = repo.BaseRepo.APIFormat(AccessModeNone)
}
```

2017-05-07 22:35 UTC, guyzmo commented
and to make sure the `repo.BaseRepo` contains something?

2017-05-08 15:29 UTC, lafriks commented
Then just assign `Parent: parent,`

2017-05-08 15:32 UTC, lafriks commented
If you meant to actually load BaseRepo than it should be done outside APIFormat in function from where APIFormat is called

2017-05-08 16:12 UTC, guyzmo commented
ok, I've tried something to force load the `BaseRepo`. The build is failing, but it doesn't look like related to that code I wrote, but I might be wrong.

2017-05-08 21:01 UTC, lafriks requested changes

2017-05-08 21:01 UTC, lafriks commented on models/repo.go
> +		parent := repo.BaseRepo.APIFormat(AccessModeNone)
it must be `parent = repo.BaseRepo...`

2017-05-08 21:09 UTC, guyzmo commented on models/repo.go
> +		parent := repo.BaseRepo.APIFormat(AccessModeNone)
and I guess `parent := nil` as well. My bad! 👍

2017-05-08 21:17 UTC, lafriks commented
But somehow I don't think it will be so easy.
1. This will make loading parents recursively that is not desired
2. Access mode is not correct as you need to give access mode to that repository for current user

Looks like there will be need to load parent and format it outside and set it there

2017-05-08 21:38 UTC, guyzmo commented
1. yup, recursive loading isn't great, but as I suggested, it can be Ok, because the edge case where it'll blow the request will be hypra exceptional…
2. err… 🤔?

2017-05-09 02:08 UTC, bkcsoft commented on models/repo.go
> +	if repo.BaseRepo != nil {
Adding `populateParent bool` to the argument-list and then `if populateParent && repo.BaseRepo != nil {` should fix the potential infinite loop :)

2017-05-09 02:09 UTC, bkcsoft commented
AFAIK `BaseRepo` is the repo we forked from right? AFAIK you can't fork a fork so we can't get recursive lookups...

2017-05-09 11:54 UTC, guyzmo commented
*you can't fork a fork* → actually you can, but that's 👌

But what you really meant is that a fork cannot be the base of itself (self referencial), or the root and the leaf of a fork tree (cycle). And actually, one project can only be the fork of another project (whereas a project can have several forks). So the graph representation is a tree.

What does that mean? it's that if you don't limit the amount of recursion in the parent property, you might get a super heavy request answer making the HTTP connection timeout, but it cannot create an infinite lookup loop 😉

And to be honest, except for intended foulplay or experimentation, I've yet to see a project tree with more than 3 or 4 levels

2017-05-09 13:40 UTC, bkcsoft requested changes
Build breaks to hell and back otherwise 😂

2017-05-09 13:40 UTC, bkcsoft commented on models/repo.go
> +func (repo *Repository) APIFormatParent(mode AccessMode, isParent) *api.Repository {
`isParent bool`...

2017-05-09 13:50 UTC, guyzmo commented on models/repo.go
> +func (repo *Repository) APIFormatParent(mode AccessMode, isParent) *api.Repository {
never happened, I don't know what you're talking about 😇 😗

2017-05-09 13:54 UTC, bkcsoft requested changes

2017-05-09 13:54 UTC, bkcsoft commented on models/repo.go
> +	if repo.BaseRepo != nil {
You're still recursing endlessly 😆

2017-05-09 14:01 UTC, bkcsoft approved these changes

2017-05-09 14:05 UTC, bkcsoft commented
LGTM

2017-05-10 06:24 UTC, lafriks requested changes

2017-05-10 06:24 UTC, lafriks commented on models/repo.go
> +	err := repo.GetBaseRepo()
if `isParent` is true no need to try to load it as it will not be used anyway

2017-05-10 07:42 UTC, bkcsoft commented on models/repo.go
> +	err := repo.GetBaseRepo()
True :)

2017-05-10 07:43 UTC, bkcsoft requested changes

2017-05-10 07:43 UTC, bkcsoft commented on models/repo.go
> +		log.Error(4, "APIFormat issue: %v", err)
just `"APIFormat: %v", err` ;)

2017-05-10 09:22 UTC, guyzmo commented on models/repo.go
> +	err := repo.GetBaseRepo()
👌

2017-05-10 09:22 UTC, guyzmo commented on models/repo.go
> +		log.Error(4, "APIFormat issue: %v", err)
👌

2017-05-10 12:16 UTC, bkcsoft approved these changes

2017-05-10 12:16 UTC, bkcsoft commented
_now_ it's LGTM :tada:

2017-05-10 12:17 UTC, lafriks commented
LGTM

2017-05-10 12:18 UTC, lafriks approved these changes

2017-05-11 07:36 UTC, lunny commented on models/repo.go
> +func (repo *Repository) innerAPIFormat(mode AccessMode, isParent bool) *api.Repository {
blank line

2017-05-11 11:33 UTC, guyzmo commented on models/repo.go
> +func (repo *Repository) innerAPIFormat(mode AccessMode, isParent bool) *api.Repository {
done 👌

2017-05-12 00:55 UTC, lunny commented
let L-G-T-M work

2017-05-12 03:09 UTC, appleboy approved these changes

2017-05-12 03:09 UTC, merged