Show commit status icon in commits table
go-gitea/gitea pull request #1688
Opened 2017-05-06 00:44 UTC by lafriks

This would be the first step to display status icons in commit table

2017-05-06 01:25 UTC, lunny commented
`TargetURL` could be a link opened on a new tab. And it seems `CommitStatusState` need one more value `CommitStatusNone` if there is no status for a commit.

2017-05-06 01:26 UTC, lunny commented
@bkcsoft

2017-05-06 09:51 UTC, lafriks commented
Fixed also bug in https://github.com/go-gitea/gitea/pull/1688/commits/d066d05512646f4d13d0da3aeae4219e823e5b5c that it was failing render commits table when creating PR with signed commits

2017-05-06 11:27 UTC, lunny commented
Great enough and LGTM. Maybe add an integration test for the commit table page is better!

2017-05-06 11:30 UTC, lunny commented
Let L-G-T-M work

2017-05-06 20:16 UTC, lafriks commented
Added integration tests for commit table and all commit statuses

2017-05-06 22:34 UTC, lafriks commented
In master getting latest status does not work except for sqlite. Fixed this here in latest commit

2017-05-07 02:03 UTC, lunny commented on integrations/repo_commits_test.go
> +	//"fmt"
unused comment

2017-05-07 02:07 UTC, lunny requested changes

2017-05-07 02:07 UTC, lunny commented on models/status.go
> +		err = x.Where("repo_id = ?", repo.ID).And("sha = ?", sha).
Why need query it twice?

2017-05-07 02:56 UTC, appleboy commented
Testing with https://github.com/drone/drone/pull/2017 PR. It is working for me.

![screen shot 2017-05-07 at 10 54 28 am](https://cloud.githubusercontent.com/assets/21979/25777584/c1303194-3313-11e7-9457-c2fde3e93e77.png)

2017-05-07 06:10 UTC, lafriks commented on models/status.go
> +		err = x.Where("repo_id = ?", repo.ID).And("sha = ?", sha).
Because there is no way to get newest row grouped by context in one select that would work across all supported databases

2017-05-07 06:23 UTC, lunny commented on models/status.go
> +		err = x.Where("repo_id = ?", repo.ID).And("sha = ?", sha).
I suggest 
```Go
var ids []int64
err := x.Limit(10, page*10).
  Where("repo_id = ?", repo.ID).And("sha = ?", sha).
  Select("id").
  GroupBy("context").OrderBy("max(created_unix) desc").Find(&ids)
if len(ids) > 0 {
x.In("id", ids).Find(&statuses)
}
```

2017-05-07 06:57 UTC, lafriks commented on models/status.go
> +		err = x.Where("repo_id = ?", repo.ID).And("sha = ?", sha).
You can't select columns that are outside of group by expressions

2017-05-07 07:50 UTC, lafriks commented
Ok, I have rewritten latest commit status selects. Only drawback that it does not selects it by latest created_at column but by largest id. But that is sacrifice that can be taken for performance reasons

2017-05-07 14:10 UTC, lunny approved these changes

2017-05-07 14:39 UTC, appleboy approved these changes

2017-05-07 14:40 UTC, appleboy commented
LGTM

2017-05-07 14:40 UTC, appleboy commented
make LGTM work

2017-05-07 14:40 UTC, merged

2017-05-08 00:40 UTC, lunny commented
The next step maybe PR's commit status or PR's status?

2017-05-08 04:57 UTC, lafriks commented
I think PR commit table is same as repository commit table, so there already should be commit status. Next step would probably be PR status. Is it just PR latest commits status?

2017-05-08 05:59 UTC, lunny commented
Yes. I think PR status == PR latest commit status

2017-05-24 17:57 UTC, xxxtonixxx commented
Now https://github.com/drone/drone/pull/2017 has been merged, is the PR's status the next step?