Added URL mapping for Release attachments like on github.com
go-gitea/gitea pull request #1707
Opened 2017-05-11 11:57 UTC by gdeverlant

Implement a Git Hub style URL mapping for the attachment files in Release.

See screenshot : ![screenshot](https://cloud.githubusercontent.com/assets/26530975/25880055/6628ae2e-3535-11e7-994e-332d82d034e5.png)

2017-05-12 03:02 UTC, appleboy commented on models/attachment.go
> +		return nil, nil
Why remove err?

2017-05-12 03:03 UTC, appleboy commented on models/release.go
>  )
Please following import package style.

2017-05-12 09:29 UTC, gdeverlant commented on models/attachment.go
> +		return nil, nil
because a fucking retarded ask me to

https://github.com/go-gitea/gitea/pull/1700#pullrequestreview-37275893

2017-05-12 09:30 UTC, gdeverlant commented on models/release.go
>  )
I'm not going to do anything ... my text editor does this shit automatically

2017-05-12 12:59 UTC, lafriks commented on models/attachment.go
> +		return nil, nil
I'm that fucking retarded who asked but I did ask to do that in completly different file and before you rewrote error handling logic....

2017-05-12 22:59 UTC, gdeverlant commented
Can you merge this please!

2017-05-13 04:01 UTC, lafriks commented on templates/repo/release/list.tmpl
> +									{{$tagname := .TagName}}
Now that you have added $release you can use $release.TagName and this variable is not needed anymore

2017-05-13 05:14 UTC, lafriks commented on models/release.go
>  )
Structure is:
bultin imports
empty line
gitea imports
empty line
dependency imports

2017-05-15 18:21 UTC, lafriks commented on routers/routes/routes.go
> +	m.Get("/:username/:reponame/releases/download/:vTag/:fileName", ignSignIn, context.RepoAssignment(), repo.RedirectDownload)
This is can not be accepted to allow file download without authorization. This is security flaw

2017-05-15 18:32 UTC, lafriks requested changes

2017-05-15 18:32 UTC, lafriks commented on modules/util/file.go
> +	} else if bytes < 1048576000000000 { // tbytes
I think there should be only else for TB.

2017-05-15 19:13 UTC, gdeverlant commented on modules/util/file.go
> +	} else if bytes < 1048576000000000 { // tbytes
I don't care I leave it there if I feel like adding petabytes

2017-05-15 19:51 UTC, lafriks commented on modules/util/file.go
> +	} else if bytes < 1048576000000000 { // tbytes
else would work as fallback for all that is larger than 1TB and in most probably impossible case but anyway is to have 1024 TB than don't have unit at all

2017-05-15 20:44 UTC, gdeverlant commented on modules/util/file.go
> +	} else if bytes < 1048576000000000 { // tbytes
For you it is impossible because you think that the sky's the limit... I think that space is unlimited.

2017-05-16 04:38 UTC, lafriks commented on modules/util/file.go
> +	} else if bytes < 1048576000000000 { // tbytes
That's why I am saying that else is better at this would would work for any size

2017-05-16 10:18 UTC, gdeverlant commented on modules/util/file.go
> +	} else if bytes < 1048576000000000 { // tbytes
This is running in my server an it works well without the else ...

2018-10-29 03:07 UTC, techknowlogick commented
@gdeverlant would you be able to resolve conflicts as well as update per @lafriks's suggestion?

2019-01-06 21:25 UTC, techknowlogick approved these changes

2019-01-06 22:25 UTC, lafriks approved these changes

2019-01-06 22:37 UTC, merged

2019-02-03 08:18 UTC, rakshith-ravi commented
Forgive me for bothering, but I'm just trying to understand: What exactly does this PR do? I'm not able to understand clearly. We already have releases with attachments, don't we?

2019-02-14 18:00 UTC, techknowlogick commented
@rakshith-ravi it provides clean URLs for attachments (has filename in URL), instead of the URL being the UUID of the uploaded file.