Move login related structs and functions to models/login
go-gitea/gitea pull request #17093
Opened 2021-09-19 13:43 UTC by lunny

As title.

2021-09-22 21:54 UTC, axifive requested changes
https://github.com/go-gitea/gitea/blob/58ef57cf4b39eaf302e74885a85cfc92cfa3fed4/models/login/source.go#L250
`"CreateLoginSource" => "CreateSource"`

2021-09-22 21:54 UTC, axifive commented on routers/web/user/oauth.go
>  		ctx.ServerError("LoadUser", err)
```suggestion
		ctx.ServerError("GetUserByID", err)
```

2021-09-22 21:54 UTC, axifive commented on routers/web/admin/auths.go
>  		ctx.ServerError("GetLoginSourceByID", err)
```suggestion
		ctx.ServerError("login.GetSourceByID", err)
```

2021-09-22 21:54 UTC, axifive commented on routers/web/admin/users.go
>  		ctx.ServerError("LoginSources", err)
```suggestion
		ctx.ServerError("login.Sources", err)
```

2021-09-22 21:54 UTC, axifive commented on routers/web/admin/users.go
>  		ctx.ServerError("LoginSources", err)
```suggestion
		ctx.ServerError("login.Sources", err)
```

2021-09-22 21:54 UTC, axifive commented on routers/web/admin/users.go
>  			ctx.ServerError("GetLoginSourceByID", err)
```suggestion
			ctx.ServerError("login.GetSourceByID", err)
```

2021-09-22 21:54 UTC, axifive commented on routers/web/admin/users.go
>  		ctx.ServerError("LoginSources", err)
```suggestion
		ctx.ServerError("login.Sources", err)
```

2021-09-22 21:54 UTC, axifive commented on routers/web/admin/auths.go
>  		ctx.ServerError("GetLoginSourceByID", err)
```suggestion
		ctx.ServerError("login.GetSourceByID", err)
```

2021-09-22 21:54 UTC, axifive commented on routers/web/admin/auths.go
>  		ctx.ServerError("GetLoginSourceByID", err)
```suggestion
		ctx.ServerError("login.GetSourceByID", err)
```

2021-09-22 21:54 UTC, axifive commented on routers/web/admin/auths.go
>  			ctx.Flash.Error(fmt.Sprintf("DeleteSource: %v", err))
```suggestion
			ctx.Flash.Error(fmt.Sprintf("DeleteLoginSource: %v", err))
```

2021-09-22 21:54 UTC, axifive commented on routers/web/admin/auths.go
>  			ctx.ServerError("CreateSource", err)
```suggestion
			ctx.ServerError("login.CreateSource", err)
```

2021-09-22 21:54 UTC, axifive commented on models/login/source.go
>  		log.Error("ActiveLoginSources: %v", err)
```suggestion
		log.Error("ActiveSources: %v", err)
```

2021-09-22 21:54 UTC, axifive commented on routers/api/v1/admin/user.go
>  			ctx.Error(http.StatusInternalServerError, "GetLoginSourceByID", err)
```suggestion
			ctx.Error(http.StatusInternalServerError, "login.GetSourceByID", err)
```

2021-09-23 04:24 UTC, lunny commented
@axifive All done.

2021-09-23 08:18 UTC, axifive approved these changes

2021-09-23 14:21 UTC, axifive commented on routers/web/admin/auths.go
>  		ctx.ServerError("LoginSources", err)
found one more
```suggestion
		ctx.ServerError("login.Sources", err)
```

2021-09-23 15:44 UTC, lunny commented on routers/web/admin/auths.go
>  		ctx.ServerError("LoginSources", err)
done.

2021-09-24 10:47 UTC, wxiaoguang approved these changes

2021-09-24 11:32 UTC, lunny commented
make L-G-T-M work.

2021-09-24 11:32 UTC, merged