Add API to get/edit wiki
go-gitea/gitea pull request #17278
Opened 2021-10-09 07:03 UTC by qwerty287

Endpoints:
* `GET repos/{owner}/{repo}/wiki/pages` get meta for all pages
* `GET repos/{owner}/{repo}/wiki/revisions/{pageName}` get a wiki page's revisions
* `GET repos/{owner}/{repo}/wiki/page/{pageName}` get a wiki page
* `PATCH repos/{owner}/{repo}/wiki/page/{pageName}` edit a wiki page
* `DELETE repos/{owner}/{repo}/wiki/page/{pageName}` delete a wiki page
* `POST repos/{owner}/{repo}/wiki/new` create a new wiki page

closes #7221

2021-10-09 09:12 UTC, delvh commented on modules/convert/wiki.go
> +func ToWikiCommitList(commits []*git.Commit, count int64) *api.WikiCommitList {
Is there a reason why you have to pass the amount of commits as parameter?
Wouldn't it suffice to check that yourself using `Count: len(result)`?
```suggestion
func ToWikiCommitList(commits []*git.Commit) *api.WikiCommitList {
```

2021-10-09 09:12 UTC, delvh commented on modules/structs/repo_wiki.go
> +	Footer      string      `json:"footer"`
Is a `PageMeta` variable `MetaData` missing here? I think that would be the perfect place to use such a variable.

2021-10-09 09:12 UTC, delvh commented on modules/structs/repo_wiki.go
> +type WikiCommitList struct {
In terms of pagination: Do you think we should already change the `WikiCommitList` to be able to paginate or not?
Because I can see that pagination would be better at some point in the future, especially for really large history revisions like 1000 or so.
To ease the change then, it might be better to already define the necessary variables and simply not use them for now.
What's your opinion on this?

2021-10-09 09:12 UTC, delvh commented on routers/api/v1/api.go
> +					m.Get("/revisions/{pageName}", mustEnableWiki, repo.WikiRevision)
You forgot that endpoint in the PR description.

2021-10-09 09:12 UTC, delvh commented on routers/api/v1/swagger/options.go
> +	CreateWikiPageOptions api.CreateWikiPageOptions
I think `go fmt` should be run.

2021-10-09 09:12 UTC, delvh commented on modules/structs/repo_wiki.go
> +type PageMeta struct {
What do you think about renaming it to `WikiPageMetaData`?
While it is longer, it is also more clear in my opinion…

2021-10-09 09:12 UTC, delvh commented on routers/api/v1/swagger/repo.go
> +}
As already mentioned, I would make that a part of a `WikiPage`.

2021-10-09 09:12 UTC, delvh commented on routers/api/v1/api.go
> +						Patch(mustNotBeArchived, reqRepoWriter(models.UnitTypeWiki), mustEnableWiki, reqToken(), bind(api.CreateWikiPageOptions{}), repo.EditWiki).
While I can definitely understand why `Patch` in this case, what about duplicating this line for `Put`?

2021-10-09 09:12 UTC, delvh commented on routers/api/v1/repo/wiki.go
> +		form.Message = ctx.Tr("repo.editor.add", form.Title)
Hmm.
I am not a particular fan of displaying (localized) content here.
Most wikis are written in English only, so the current user locale should not have an effect on the outcome.
That is exactly the same as #14845 for wiki pages.
As I have just noticed, Gitea does not allow empty commit messages, so we have to insert some content.
But I am against a localized string, instead I would simply use
```suggestion
		form.Message = form.Title
```

2021-10-09 09:12 UTC, delvh commented on routers/api/v1/repo/wiki.go
> +		} else if models.IsErrWikiAlreadyExist(err) {
I can totally understand this approach.
Another alternative would have been to overwrite the page in this case, but I think in most cases it makes more sense to let the users decide for themselves what they want to do then.

2021-10-09 09:12 UTC, delvh commented on routers/api/v1/repo/wiki.go
> +		form.Message = ctx.Tr("repo.editor.update", form.Title)
See above, so
```suggestion
		form.Message = form.Title
```

2021-10-09 09:12 UTC, delvh commented on routers/api/v1/repo/wiki.go
> +		wikiName = "Home"
I doubt it is a good idea to **delete the wiki homepage** because no length was specified, so rather throw a `http.StatusBadRequest` and return.

2021-10-09 09:12 UTC, delvh commented on routers/api/v1/repo/wiki.go
> +func WikiPages(ctx *context.APIContext) {
`ListWikiPages`?

2021-10-09 09:12 UTC, delvh commented on routers/api/v1/repo/wiki.go
> +	}()
```suggestion
	if wikiRepo != nil {
		defer func() {
			wikiRepo.Close()
		}
	}()
```

2021-10-09 09:12 UTC, delvh commented on routers/api/v1/repo/wiki.go
> +	pages := make([]api.PageMeta, 0, len(entries))
Ah. You approach it that way.
I thought you would send a `WikiPage`, where the `PageMeta` would be part of.

2021-10-09 09:12 UTC, delvh commented on routers/api/v1/repo/wiki.go
> +		}
```suggestion
		if git.IsErrNotExist(err) {
			ctx.Error(http.StatusInternalServerError, "GetBranchCommit", err)
		} else {
			ctx.Error(http.StatusInternalServerError, "findWikiRepoCommit", err)
		}
```
Or am I misunderstanding something here?

2021-10-09 09:12 UTC, delvh commented on routers/api/v1/repo/wiki.go
> +		pageName = "Home"
Here I can understand it at least.

2021-10-09 09:12 UTC, delvh commented on routers/api/v1/repo/wiki.go
> +	if err != nil && !git.IsErrNotExist(err) {
Why exactly do you always differentiate between `!git.IsErrNotExist` and its complement?
Especially, why are those cases handled differently? That is something I absolutely don't understand.

2021-10-09 09:12 UTC, delvh commented on routers/api/v1/repo/wiki.go
> +	if err != nil && !git.IsErrNotExist(err) {
Again this differentiation? What's the purpose of that?
And why always in negated form?

2021-10-09 10:40 UTC, noerw commented on routers/api/v1/api.go
> +						Patch(mustNotBeArchived, reqRepoWriter(models.UnitTypeWiki), mustEnableWiki, reqToken(), bind(api.CreateWikiPageOptions{}), repo.EditWiki).
We generally use PATCH for edits of content throughout the API

2021-10-09 10:43 UTC, noerw commented on routers/api/v1/repo/wiki.go
> +func NewWiki(ctx *context.APIContext) {
```suggestion
func NewWikiPage(ctx *context.APIContext) {
```
this naming convention on all funcs in this file would be much more understandable

2021-10-09 10:46 UTC, noerw commented on modules/structs/repo_wiki.go
> +	Message string `json:"message"`
Please document the expected encoding for `Content`. AFAICS you currently take plain UTF-8 strings, but other file content APIs expect and return content base64 encoded (both read and write operations), we should aim for consistency here.

2021-10-09 10:49 UTC, noerw commented on routers/api/v1/repo/wiki.go
> +	}()
```suggestion
	if wikiRepo != nil {
		defer wikiRepo.Close()
	}
```

2021-10-09 12:33 UTC, qwerty287 commented on routers/api/v1/api.go
> +					m.Get("/revisions/{pageName}", mustEnableWiki, repo.WikiRevision)
I updated the description

2021-10-09 12:35 UTC, qwerty287 commented on routers/api/v1/repo/wiki.go
> +		form.Message = ctx.Tr("repo.editor.add", form.Title)
It's just copied from the web router - it also localizes every commit

Edit:
I definitely can understand you, but it's a bit strange if you have a commit message `Home`... Maybe you could just go with the English version `Add/edit Home`

2021-10-09 12:36 UTC, qwerty287 commented on routers/api/v1/swagger/options.go
> +	CreateWikiPageOptions api.CreateWikiPageOptions
This was already done - why is it bad?

2021-10-09 12:44 UTC, qwerty287 commented on routers/api/v1/repo/wiki.go
> +func NewWiki(ctx *context.APIContext) {
see https://github.com/go-gitea/gitea/pull/17278/commits/c908b691eb7c4b31968b9330151d9aec53758b61

2021-10-09 12:45 UTC, qwerty287 commented on routers/api/v1/repo/wiki.go
> +	if err != nil && !git.IsErrNotExist(err) {
see https://github.com/go-gitea/gitea/pull/17278/commits/d3ef69c5bd1db3b834eca037765aa450f0800975

2021-10-09 12:45 UTC, qwerty287 commented on routers/api/v1/repo/wiki.go
> +	if err != nil && !git.IsErrNotExist(err) {
see https://github.com/go-gitea/gitea/pull/17278/commits/d3ef69c5bd1db3b834eca037765aa450f0800975

2021-10-09 12:45 UTC, qwerty287 commented on routers/api/v1/repo/wiki.go
> +		}
see https://github.com/go-gitea/gitea/pull/17278/commits/d3ef69c5bd1db3b834eca037765aa450f0800975

2021-10-09 12:47 UTC, qwerty287 commented on modules/convert/wiki.go
> +func ToWikiCommitList(commits []*git.Commit, count int64) *api.WikiCommitList {
No, that's not possible. `count` is the total count, while `commits` only contains the commits that will be sent back (they are paginated and don't contain all commits)

2021-10-09 12:51 UTC, qwerty287 commented on modules/structs/repo_wiki.go
> +type PageMeta struct {
see https://github.com/go-gitea/gitea/pull/17278/commits/53f82fa897f92c26ee1acc97258a8977cf73e77c

2021-10-09 12:52 UTC, qwerty287 commented on routers/api/v1/api.go
> +						Patch(mustNotBeArchived, reqRepoWriter(models.UnitTypeWiki), mustEnableWiki, reqToken(), bind(api.CreateWikiPageOptions{}), repo.EditWiki).
Should I update it or not?

2021-10-09 12:53 UTC, qwerty287 commented on routers/api/v1/repo/wiki.go
> +		wikiName = "Home"
I know, but it's the same in the web router, so I thought it's fine to go with this (will remove it)

2021-10-09 12:55 UTC, qwerty287 commented on routers/api/v1/repo/wiki.go
> +func WikiPages(ctx *context.APIContext) {
see https://github.com/go-gitea/gitea/pull/17278/commits/23f647543079da0f64510085f0bd2b5ddfe06826

2021-10-09 12:55 UTC, qwerty287 commented on routers/api/v1/repo/wiki.go
> +		wikiName = "Home"
https://github.com/go-gitea/gitea/pull/17278/commits/ceabfd7725d0f9866204152865c5d19ff12cdbaf

2021-10-09 12:58 UTC, qwerty287 commented on modules/structs/repo_wiki.go
> +	Footer      string      `json:"footer"`
It is the first var

2021-10-09 13:00 UTC, qwerty287 commented on routers/api/v1/repo/wiki.go
> +	pages := make([]api.PageMeta, 0, len(entries))
A problem could be that a wiki page with a very long content would take a while to load. So I didn't load the content in the list, only if you request it directly.

2021-10-09 13:01 UTC, qwerty287 commented on routers/api/v1/repo/wiki.go
> +		pageName = "Home"
I just noticed that this will never be the case since the router will return a 404 if you try to get it without a page

2021-10-09 13:12 UTC, qwerty287 commented on modules/structs/repo_wiki.go
> +type WikiCommitList struct {
Hm maybe I don't understand you, but the endpoint has pagination (with the `page` parameter)

2021-10-09 14:19 UTC, qwerty287 commented on routers/api/v1/repo/wiki.go
> +		} else if models.IsErrWikiAlreadyExist(err) {
Overriding is a bad idea I'd say. You can use the the edit feature to edit a page.

2021-10-09 14:48 UTC, delvh commented on modules/convert/wiki.go
> +func ToWikiCommitList(commits []*git.Commit, count int64) *api.WikiCommitList {
Ah, makes sense.

2021-10-09 14:49 UTC, delvh commented on routers/api/v1/swagger/options.go
> +	CreateWikiPageOptions api.CreateWikiPageOptions
To me, it seems as if these two last variables have one indent less than the other variables in this file.

2021-10-09 14:50 UTC, delvh commented on routers/api/v1/api.go
> +						Patch(mustNotBeArchived, reqRepoWriter(models.UnitTypeWiki), mustEnableWiki, reqToken(), bind(api.CreateWikiPageOptions{}), repo.EditWiki).
No, the way it currently is suffices then.

2021-10-09 15:09 UTC, delvh commented on routers/api/v1/repo/wiki.go
> +		form.Message = ctx.Tr("repo.editor.add", form.Title)
> It's just copied from the web router - it also localizes every commit

That is another problem.
I agree with the commit message.
I thought `form.Message` referred to the page content. Go ahead with the English version.

2021-10-09 15:10 UTC, delvh commented on routers/api/v1/repo/wiki.go
> +		} else if models.IsErrWikiAlreadyExist(err) {
Yes, I know and agree. That would have been another approach, but I'm glad you chose the current approach.

2021-10-09 15:11 UTC, qwerty287 commented on routers/api/v1/swagger/options.go
> +	CreateWikiPageOptions api.CreateWikiPageOptions
OK - as mentioned I used go fmt and for me it seems to be the same (and the ci doesn't fail at this point)

2021-10-09 15:16 UTC, delvh commented on modules/structs/repo_wiki.go
> +type WikiCommitList struct {
Okay, if it already supports pagination then I'm fine with it.

2021-10-09 15:26 UTC, delvh commented on modules/structs/repo_wiki.go
> +	Footer      string      `json:"footer"`
Okay, thanks.
Surprisingly, I simply overlooked it previously, as confirmed by `git blame`.
Sorry for the unnecessary comment then.

2021-10-09 15:26 UTC, delvh commented on routers/api/v1/repo/wiki.go
> +func WikiRevision(ctx *context.APIContext) {
Okay, I just noticed that this function returns **all** revisions, not a specific one as I previously thought.
What about renaming it to `ListPageRevisions` then?
Alternatively, `ListWikiPageRevisions` would also be possible.

2021-10-09 15:26 UTC, delvh commented on integrations/api_wiki_test.go
> +	//"code.gitea.io/gitea/models/db"
```suggestion
```

2021-10-09 16:15 UTC, qwerty287 commented on routers/api/v1/repo/wiki.go
> +		form.Message = ctx.Tr("repo.editor.add", form.Title)
Fixed https://github.com/go-gitea/gitea/pull/17278/commits/8d568a448e1d11d8373650d2442f28f776fa17da

2021-10-09 22:27 UTC, delvh reviewed
Surprisingly, in the new implementation you often omit responses. Why's that?

2021-10-09 22:27 UTC, delvh commented on routers/api/v1/repo/wiki.go
>  			wikiRepo.Close()
I just noticed: There is a code path in which the repo won't be closed.
I think you should reuse the `defer` block we already talked about.
Especially as this removes some lines below.

2021-10-09 22:27 UTC, delvh commented on routers/api/v1/repo/wiki.go
> +	}
```suggestion
	if wikiRepo != nil {
		defer wikiRepo.Close()
	}
	if err != nil {
		ctx.Error(http.StatusInternalServerError, "findWikiRepoCommit", err)
		return
	}
```

2021-10-09 22:27 UTC, delvh commented on routers/api/v1/repo/wiki.go
> +		}
```suggestion
	if wikiRepo != nil {
		defer wikiRepo.Close()
	}
	if err != nil {
```

2021-10-09 22:27 UTC, delvh commented on routers/api/v1/repo/wiki.go
> +		if !ctx.Written() {
Why exactly do you want to return no response if `ctx.Written()`?

2021-10-09 22:27 UTC, delvh commented on routers/api/v1/repo/wiki.go
> +				ctx.NotFound(err)
I think that return value should be docmented inside the swagger definition.

2021-10-09 22:27 UTC, delvh commented on routers/api/v1/repo/wiki.go
> +		}
```suggestion
```

2021-10-09 22:27 UTC, delvh commented on routers/api/v1/repo/wiki.go
> +		}
And what do you return otherwise?

2021-10-09 22:27 UTC, delvh commented on routers/api/v1/repo/wiki.go
> +		}
```suggestion
```
Also, what response status do you return then? Because none is not a good idea.

2021-10-09 22:27 UTC, delvh commented on routers/api/v1/repo/wiki.go
> +		}
```suggestion
```
And again the same issue.

2021-10-09 22:27 UTC, delvh commented on routers/api/v1/repo/wiki.go
> +		ctx.NotFound()
```suggestion
		ctx.NotFound()
		return
```

2021-10-09 22:27 UTC, delvh commented on routers/api/v1/repo/wiki.go
> +		}
```suggestion
	if wikiRepo != nil {
		defer wikiRepo.Close()
	}
	if err != nil {
```

2021-10-09 22:27 UTC, delvh commented on routers/api/v1/repo/wiki.go
> +		}
And again a missing response if `ctx.Written`…

2021-10-09 22:27 UTC, delvh commented on routers/api/v1/repo/wiki.go
> +		}
```suggestion
```

2021-10-09 22:31 UTC, delvh commented
Regarding my last review:
Is the purpose of `ctx.Written` possibly to check whether a response has been sent already? If that is the case, you can ignore/ rewrite many of my suggestions/ comments.

2021-10-10 05:39 UTC, qwerty287 commented
Yes, ctx.Written is true if there already is a response set. That means that another function used ctx.Error or something else. Without the if statement it could report duplicated error reports to the client/end user.

2021-10-10 12:46 UTC, qwerty287 commented on routers/api/v1/repo/wiki.go
> +		}
Fixed in https://github.com/go-gitea/gitea/pull/17278/commits/1ea3fe118a62c3a3ff4f3d6d9a17f0cee66fa958

2021-10-10 12:50 UTC, qwerty287 commented on routers/api/v1/swagger/repo.go
> +}
Even if there could be the problem that a wiki page with a very long content would take a while to load?

2021-10-10 12:51 UTC, qwerty287 commented on routers/api/v1/repo/wiki.go
> +	pages := make([]api.PageMeta, 0, len(entries))
Should I change it?

2021-10-10 12:56 UTC, qwerty287 commented on routers/api/v1/repo/wiki.go
>  			wikiRepo.Close()
I think you included this in one of your review suggestion, so it is fixed.

2021-10-10 12:58 UTC, qwerty287 commented on modules/structs/repo_wiki.go
> +	Message string `json:"message"`
I added a documentation comment https://github.com/go-gitea/gitea/pull/17278/commits/f9455bcd2f289a461045c6a39e6802707ad238a4

2021-10-10 13:48 UTC, delvh commented on routers/api/v1/repo/wiki.go
> +	pages := make([]api.PageMeta, 0, len(entries))
No, I think the current approach is feasible.

2021-10-17 09:39 UTC, delvh commented on routers/api/v1/swagger/repo.go
> +}
As discussed, no, the current approach suffices.

2021-10-17 10:00 UTC, delvh approved these changes

2021-10-17 21:23 UTC, noerw reviewed
Might still be a good idea to base64-encode wiki page content, similar to `/repos​/{owner}​/{repo}​/contents​/{filepath}` API. (It's not an intended usecase, but this API can technically return binary files

2021-10-17 21:28 UTC, noerw commented on routers/api/v1/api.go
> +						Patch(mustNotBeArchived, reqRepoWriter(models.UnitTypeWiki), mustEnableWiki, reqToken(), bind(api.CreateWikiPageOptions{}), repo.EditWikiPage).
You can put the `mustEnableWiki` middleware on the outer `m.Group("/wiki" ..)` handler and remove it from all the inner handlers for better readability. Also I'm not sure if `reqToken()` is needed if you already have `reqRepoWriter()`, would need to test that

2021-10-17 21:31 UTC, noerw commented on routers/api/v1/repo/wiki.go
> +	ctx.Status(http.StatusNoContent)
return a `http.StatusCreated`

2021-10-17 21:51 UTC, noerw requested changes

2021-10-17 21:51 UTC, noerw commented on routers/api/v1/repo/wiki.go
> +	ctx.Status(http.StatusNoContent)
Other APIs return the modified entity after editing it. Might make sense to do here too, not sure

2021-10-17 21:51 UTC, noerw commented on routers/api/v1/repo/wiki.go
> +	//   "204":
could technically also return a 404 and 403 (most other routes as well)

2021-10-17 21:51 UTC, noerw commented on routers/api/v1/repo/wiki.go
> +	//   "201":
this should be 200

2021-10-17 21:51 UTC, noerw commented on routers/api/v1/repo/wiki.go
> +	//   "201":
see above

2021-10-17 21:51 UTC, noerw commented on routers/api/v1/repo/wiki.go
> +	wikiRepo, err := git.OpenRepository(ctx.Repo.Repository.WikiPath())
Who is responsible for closing this repo again?
This should be well documented, or even better enforced to be closed again within this function.

2021-10-17 21:51 UTC, noerw commented on routers/api/v1/repo/wiki.go
> +		if !isSidebarOrFooter {
Why do you distinguish this here?
It's hard to follow when a response is written, I'd refactor this to either never write a response here, or write it in all (error) cases. Then you can probably also drop the returned not-found-boolean..

2021-10-17 21:51 UTC, noerw commented on routers/api/v1/repo/wiki.go
> +	wikiPage := &api.WikiPage{
We have a `convert` module, which we use to transform between something returned by the `models` module and its corresponding API representation.
Please put this logic into a function  `convert.ToWikiPage()`. Same for `ListWikiPages` above and possibly other places where you generate API responses

2021-10-17 21:51 UTC, noerw commented on routers/api/v1/repo/wiki.go
> +		pages = append(pages, api.WikiPageMetaData{
Hmm, other listing APIs in Gitea return the same representation as the single item endpoint, just as an array.
Is there a reason you don't do that here? I'm not convinced this convention in Gitea's API is great, so I have no strong opinion here, just pointing out that this deviates from the standard

2021-10-18 07:15 UTC, qwerty287 commented on routers/api/v1/repo/wiki.go
> +		pages = append(pages, api.WikiPageMetaData{
Wiki pages usually have a bit more content and it would take a while for clients to load the content if it only requests the page list.

2021-10-18 07:15 UTC, qwerty287 commented on routers/api/v1/repo/wiki.go
> +	ctx.Status(http.StatusNoContent)
https://github.com/go-gitea/gitea/pull/17278/commits/ecc7ba6836c8b5648ab749d826fdd94c6d2c0fd9

2021-10-18 07:15 UTC, qwerty287 commented on routers/api/v1/repo/wiki.go
> +	ctx.Status(http.StatusNoContent)
https://github.com/go-gitea/gitea/pull/17278/commits/ecc7ba6836c8b5648ab749d826fdd94c6d2c0fd9

2021-10-18 07:16 UTC, qwerty287 commented on routers/api/v1/repo/wiki.go
> +	//   "204":
https://github.com/go-gitea/gitea/pull/17278/commits/ecc7ba6836c8b5648ab749d826fdd94c6d2c0fd9

2021-10-18 07:16 UTC, qwerty287 commented on routers/api/v1/repo/wiki.go
> +	//   "201":
https://github.com/go-gitea/gitea/pull/17278/commits/ecc7ba6836c8b5648ab749d826fdd94c6d2c0fd9

2021-10-18 07:16 UTC, qwerty287 commented on routers/api/v1/repo/wiki.go
> +	//   "201":
https://github.com/go-gitea/gitea/pull/17278/commits/ecc7ba6836c8b5648ab749d826fdd94c6d2c0fd9

2021-10-18 07:17 UTC, qwerty287 commented on routers/api/v1/repo/wiki.go
> +	wikiRepo, err := git.OpenRepository(ctx.Repo.Repository.WikiPath())
the `defer` in the calling functions - should I add a comment to show that it's done there?

2021-10-18 07:18 UTC, qwerty287 commented on routers/api/v1/repo/wiki.go
> +		if !isSidebarOrFooter {
If there is no sidebar or footer, this will return a 500 error because these files doesn't exist. Only solution would probably be to remove the sidebar and footer from the responses, so you have to load them by getting the `_Sidebar` or `_Footer` page.

2021-10-18 07:32 UTC, qwerty287 commented on routers/api/v1/repo/wiki.go
> +	wikiPage := &api.WikiPage{
https://github.com/go-gitea/gitea/pull/17278/commits/34c6d719e6f63cc8f192e8e053b771445f03c984

2021-10-18 07:34 UTC, qwerty287 commented on routers/api/v1/api.go
> +						Patch(mustNotBeArchived, reqRepoWriter(models.UnitTypeWiki), mustEnableWiki, reqToken(), bind(api.CreateWikiPageOptions{}), repo.EditWikiPage).
That doesn't work for me, since it needs the `APIContext` and it isn't possible to add a function that has an APIContext to the Group - or am I doing something wrong?

2021-10-20 05:25 UTC, lunny commented on routers/api/v1/api.go
> +				})
Isn't `}, mustEnableWiki)` work here?

2021-10-20 05:35 UTC, qwerty287 commented on routers/api/v1/api.go
> +				})
@noerw recommended this too, but then you can't use the `APIContext` argument in this function

2021-10-22 14:53 UTC, qwerty287 commented on routers/api/v1/api.go
> +				})
updated in https://github.com/qwerty287/gitea/pull/1

2021-10-22 16:59 UTC, noerw approved these changes
:tada: LGTM so my "changes requested" disappears.
disclaimer: I contributed more than a bit to this PR

2021-10-22 17:13 UTC, wxiaoguang commented on modules/structs/repo_wiki.go
> +	ContentBase64 string `json:"content"`
Should `json:"content"` be `json:"content_base64"` ?

2021-10-22 17:13 UTC, wxiaoguang commented on modules/structs/repo_wiki.go
> +	SubURL     string      `json:"suburl"`
HTMLURL = html_url, while SubURL = suburl, a little strange.

2021-10-22 17:13 UTC, wxiaoguang commented on modules/structs/repo_wiki.go
> +	ContentBase64 string `json:"content"`
Should json:"content" be json:"content_base64" ?

2021-10-22 17:14 UTC, wxiaoguang commented on modules/structs/repo_wiki.go
> +	ID        string      `json:"sha"`
Why `sha` is used instead of `id`?

2021-10-22 18:06 UTC, noerw commented on modules/structs/repo_wiki.go
> +	ID        string      `json:"sha"`
[For consistency with other places where the API returns a commit](https://gitea.com/api/swagger#/repository/repoGetAllCommits)
The API has accumulated a couple of idiosyncracies like this (partially also inherited from github's api), that could benefit from a change. This could be done in /api/v2 at some point, but additions to v1 should optimize for consistency between endpoints imho. (Though in this API we're technically free as it doesn't have a GH equivalent).

2021-10-23 10:00 UTC, lunny commented on modules/structs/repo_wiki.go
> +	SubURL     string      `json:"suburl"`
`sub_url`

2021-10-23 12:31 UTC, qwerty287 commented on modules/structs/repo_wiki.go
> +	ContentBase64 string `json:"content"`
https://github.com/go-gitea/gitea/pull/17278/commits/daf8ee07a5d0219eddfabd80ba149a507f27cec2

2021-10-23 12:31 UTC, qwerty287 commented on modules/structs/repo_wiki.go
> +	ContentBase64 string `json:"content"`
https://github.com/go-gitea/gitea/pull/17278/commits/daf8ee07a5d0219eddfabd80ba149a507f27cec2

2021-10-23 12:32 UTC, qwerty287 commented on modules/structs/repo_wiki.go
> +	SubURL     string      `json:"suburl"`
https://github.com/go-gitea/gitea/pull/17278/commits/7105721b417166132af4698ae96f1c25b99a2d2a

2021-10-23 14:27 UTC, delvh commented on modules/structs/repo_wiki.go
> +	ContentBase64 string `json:"content_base64"`
Must the content really be base64 encoded?
How would it be possible to send binary data? Isn't it an `html` or `markdown` file you're sending?

2021-10-23 14:27 UTC, delvh commented on modules/structs/repo_wiki.go
> +	ContentBase64 string `json:"content_base64"`
Must the content really be base64 encoded?
How would it be possible to send binary data? Isn't it an `html` or `markdown` file you're sending?

2021-10-23 14:37 UTC, qwerty287 commented on modules/structs/repo_wiki.go
> +	ContentBase64 string `json:"content_base64"`
The files API returns base64 data too, so @noerw suggested to change it here too.

2021-10-23 14:56 UTC, wxiaoguang approved these changes

2021-10-23 19:30 UTC, noerw commented on modules/structs/repo_wiki.go
> +	ContentBase64 string `json:"content_base64"`
It's a git repo, it can contain anything.

2021-10-25 03:43 UTC, merged