Fix FOUC on Firefox
go-gitea/gitea pull request #1728
Opened 2017-05-14 18:02 UTC by sondr3

As mentioned in #1698 Firefox users experience a brief FOUC while loading various pages in Gitea, this commit should fix this by using Filament Groups loadCSS library to asynchronously load the CSS that makes the pages flash.

This commit will add ~1.5kB of JS to the `<head>` of the webpages. The scripts need to be in the head for the FOUC to not occur, if you do it with the scripts in the bottom of the page it will load the CSS to late and the FOUC will occur regardless. You could potentially also inline them but I went with linking to them.

You will notice in the before and after from the developer panel that the Font Awesome CSS is loaded last because it will not load until the DOM content is ready.
<img width="1057" alt="screen shot 2017-05-14 at 19 56 08" src="https://cloud.githubusercontent.com/assets/2280539/26036523/7ab1f078-38df-11e7-9f68-11cb0ed64f3a.png">
<img width="1048" alt="screen shot 2017-05-14 at 19 56 23" src="https://cloud.githubusercontent.com/assets/2280539/26036524/7d78ef50-38df-11e7-8b97-39da4df633f9.png">

*NOTE*: In case users don't have JS enabled it will load the CSS as normal. However I'm not sure if this is required and that I could just remove the `<noscript>` line.

This is my first pull request to Gitea, so let me know if I need to change anything. 😃

2017-05-16 04:21 UTC, MCF commented
I've tested this on MacOS as well.  Looks good in Firefox and Chrome.  Did not see any small flashes in Firefox at all, which occasionally show up without this patch applied.

I'll try to find some time to test on Windows 7 in the next few days.

2017-05-16 23:44 UTC, MCF commented
Built and tested on Windows 7.  I tested Firefox 53, Chrome 58 and IE 11.  No FOUC on any of them, not even on initial (uncached) page load.  Better than github in that regard.

I did not notice any obvious problems with page load speeds on any of the browsers.  But I just browsed around the site and compared it to try.gitea.io.  No real timing tests.

Nice job with the fix.

2017-05-17 22:04 UTC, ethantkoenig requested changes

2017-05-17 22:04 UTC, ethantkoenig commented on templates/base/head.tmpl
> +  <link rel="stylesheet" href="{{AppSubUrl}}/assets/octicons-4.3.0/octicons.min.css">
lines 24 and 25 are indented with spaces

2017-05-17 22:26 UTC, sondr3 commented on templates/base/head.tmpl
> +  <link rel="stylesheet" href="{{AppSubUrl}}/assets/octicons-4.3.0/octicons.min.css">
Oh, you use tabs, I didn't notice, I'll fix it.

2017-05-17 22:31 UTC, sondr3 commented on templates/base/head.tmpl
> +  <link rel="stylesheet" href="{{AppSubUrl}}/assets/octicons-4.3.0/octicons.min.css">
And done 😄

2017-05-18 15:02 UTC, lunny commented
So this will fix #1271?

2017-05-18 16:12 UTC, MCF commented
Not sure about that one, but it does fix https://github.com/go-gitea/gitea/issues/1698

2017-05-18 19:18 UTC, sondr3 commented
@lunny, this specifically fixes #1698 and if it fixes anything else that's purely coincidental 😃

2017-05-20 04:21 UTC, lunny commented
@sondr3 I have tested that this will fix #1271, so LGTM

2017-05-28 04:48 UTC, strk commented
LGTM

2017-05-28 04:49 UTC, strk commented
Actually @sondr3  please add the license of the new .js files to https://github.com/go-gitea/gitea/blob/master/public/assets/librejs/librejs.html

2017-05-28 04:50 UTC, strk commented
@sondr3 see #1484 (there are also more librejs things missing, in case you want to deal with this in a separate PR)

2017-05-28 10:46 UTC, lunny commented
@ethantkoenig please confirm your codereview

2017-05-28 16:45 UTC, sondr3 commented
@strk I'll add them to this PR when I get to my computer in a few hours and push a new change 😃

2017-05-28 20:44 UTC, sondr3 commented
Alright, added the JS files to the `librejs.html` file, I wasn't sure where to link to the license since there's not a canonical homepage for it but OSI seemed like a good fit.

2017-05-30 17:35 UTC, ethantkoenig approved these changes

2017-05-31 01:05 UTC, merged