Sync gitea app path for git hooks and authorized keys when starting
go-gitea/gitea pull request #17335
Opened 2021-10-17 06:48 UTC by wxiaoguang

Background:

Gitea writes its own AppPath into git hook scripts. If Gitea's AppPath changes, then the git push will fail. The previous PRs ( https://github.com/go-gitea/gitea/pull/17274 , https://github.com/go-gitea/gitea/pull/17157 ) seem to be difficult to resolve this problem fundamentally.

This PR:

1. Introduce an `AppState` module, it can persist app states into database, I believe https://github.com/go-gitea/gitea/pull/17212 will also benifit from this feature and we can drop separate database dependency then.
2. During `GlobalInit`, Gitea will check if the current AppPath is the same as last one. If they don't match, Gitea will sync git hooks.
3. Refactor some code to make them more clear.
4. Also, https://github.com/go-gitea/gitea/issues/11341 is related, we call `models.RewriteAllPublicKeys` to update ssh authorized_keys file

2021-10-17 13:09 UTC, lunny commented on modules/appstate/file.go
> +	return path.Join(f.path, item.Name())
`filepath.Join`?

2021-10-17 13:11 UTC, lunny commented on modules/setting/appstate.go
> +	appStatePath := path.Join(AppDataPath, "appstate")
filepath.Join

2021-10-17 13:14 UTC, lunny commented
Out of the topic, we could also introduce a file system layer for all the dir path, so they could be picked from non-disk storage.

2021-10-17 13:42 UTC, wxiaoguang commented on modules/appstate/file.go
> +	return path.Join(f.path, item.Name())
But there were so many `path.Join`

And AppDataPath itself was generated by `	AppDataPath = sec.Key("APP_DATA_PATH").MustString(path.Join(AppWorkPath, "data"))`

![image](https://user-images.githubusercontent.com/2114189/137629573-878a64a7-3ad4-419e-8671-e28905d4384d.png)

Should we clean then later?

2021-10-17 14:30 UTC, wxiaoguang commented on modules/appstate/file.go
> +	return path.Join(f.path, item.Name())
Now `filepath.Join` is used in my code, others are left as they were.

2021-10-17 22:58 UTC, delvh commented on modules/appstate/file.go
> +func (f *FileStore) Get(item StateItem) error {
Shouldn't a "get" operation return the retrieved item as well as the error?

2021-10-17 22:58 UTC, delvh commented on modules/appstate/appstate.go
> +	Get(item StateItem) error
Shouldn't a "get" operation return the retrieved item as well as the error?

2021-10-18 04:09 UTC, wxiaoguang commented on modules/appstate/file.go
> +func (f *FileStore) Get(item StateItem) error {
It works like `xorm.Get`

2021-10-18 05:42 UTC, lunny commented on modules/appstate/file.go
> +func (f *FileStore) Get(item StateItem) error {
I agree with @delvh . `Xorm` use that because we can get the table name from the object. But for this situation, it seems it's unnecessary.

2021-10-18 07:41 UTC, wxiaoguang commented on modules/appstate/file.go
> +func (f *FileStore) Get(item StateItem) error {
As discussed in private message, here is OK. 

1. We let callers to decide the StateItem structure, so we need a pre-allocated structure to do unmarshal
2. If we want to run Gitea as a cluster, here we need some Redis or other distributed providers.

2021-10-18 08:19 UTC, lunny approved these changes

2021-10-18 08:45 UTC, delvh approved these changes

2021-10-18 13:32 UTC, lafriks requested changes

2021-10-18 13:32 UTC, lafriks commented on modules/appstate/appstate.go
> +	Get(item StateItem) error
imho it would be better to use `Get() (StateItem, error)`

2021-10-18 13:32 UTC, lafriks commented on modules/appstate/file.go
> +func (f *FileStore) Get(item StateItem) error {
There is no point in initializing and passing it as parameter as you can't pass anything but this single structure. otherwise you need change parameter to `interface{}` to allow pass anything but there is no point in that imho

2021-10-18 13:32 UTC, lafriks commented on modules/appstate/appstate.go
> +	Delete(item StateItem) error
Let's not add functionality that's not used, if it will be needed than we can add it later on

2021-10-18 13:32 UTC, lafriks commented on routers/init.go
> +func syncAppPathForGit(ctx context.Context) (err error) {
```suggestion
func syncAppPathForGit(ctx context.Context) error {
```

2021-10-18 13:32 UTC, lafriks commented on routers/init.go
> +	if err = setting.AppState.Get(runtimeState); err != nil {
Imho this looks much cleaner:

```suggestion
	runtimeState, err := setting.AppState.Get()
	if err != nil {
```

2021-10-18 14:01 UTC, wxiaoguang commented on modules/appstate/appstate.go
> +	Get(item StateItem) error
No. This module is designed for further usage. For example:

```
type RemoteVersion {
    LatestStableVersion string
    LatestRcVersion string
}

remoteVersion := new(RemoteVersion)
AppState.Get(remoteVersion)
```

2021-10-18 14:02 UTC, wxiaoguang commented on routers/init.go
> +	if err = setting.AppState.Get(runtimeState); err != nil {
As above

2021-10-18 21:20 UTC, zeripath commented on modules/setting/setting.go
> +		// FIXME: Many calls to MkdirAll are using 0644 (not executable) or `os.ModePerm`(0o777, world-wide writable), which are incorrect.
I don't think this is correct.

```
MkdirAll creates a directory named path, along with any necessary parents, and returns nil, or else returns an error. The permission bits perm (before umask) are used for all directories that MkdirAll creates. If path is already a directory, MkdirAll does nothing and returns nil.
```

My own user umask is 002

Therefore when I run 

```go
package main

import (
	"fmt"
  "os"
)

func main() {
	fmt.Println(os.MkdirAll("test-dir/some-child", os.ModePerm)
}
```

It is created with mode 775. 

I don't think that's unreasonable, umask exists for a reason and its up to server administrators to decide what the correct umask is for their users - otherwise we're just going to have to create our own mini umask code for whatever it is we want to create.

In any case this comment doesn't belong in the code at this point - it's not helpful and it's not going to remind people to look for this issue. You should open another issue or fix the code.

2021-10-18 21:20 UTC, zeripath commented on modules/setting/setting.go
> +		// Now we can take the first step to do correctly (Mkdir) in other packages, and prepare the AppDataPath here, then make a refactor in future.
Whilst I understand this point and can see how this is bad for docker-like and some server situations - you need to remember that Gitea is supposed to be runnable from the binary as quick start.

The creation of directories etc. is part of that quickstart. We would need to come up with some way of being to cope with both situations. Another setting flag perhaps? Or perhaps only create directories if INSTALL_LOCK is not set.

2021-10-18 21:20 UTC, zeripath commented on modules/setting/setting.go
> +		err = os.MkdirAll(AppDataPath, os.FileMode(0755))
Let server administrators decide this. umask exists for a reason.

2021-10-18 21:48 UTC, lafriks commented on modules/appstate/appstate.go
> +	Get(item StateItem) error
But what is use case to define multiple structures vs one with multiple fields?

2021-10-19 04:29 UTC, wxiaoguang commented on modules/appstate/appstate.go
> +	Get(item StateItem) error
Using multiple structures can decouple the code for different modules.

For example, a `RemoteVersion` shouldn't depend on the `LastAppPath`.

And we can introduce Lock mechanism (flock or Redis lock) in future to protect concurrency writing.

Separate state item also makes it easier to reset one item without changing others (from user side or from code side)

And if state items become large (a lot of bytes in disk), separated item files also improve performance. We do not need to rewrite whole file if only a single item changes.

2021-10-19 04:42 UTC, wxiaoguang commented on modules/setting/setting.go
> +		// Now we can take the first step to do correctly (Mkdir) in other packages, and prepare the AppDataPath here, then make a refactor in future.
Agree. A new comment is added: "For quickstart, the parent directories should be created automatically for first startup (eg: a flag or a check of INSTALL_LOCK)."

2021-10-19 07:41 UTC, lafriks commented on modules/appstate/appstate.go
> +	Get(item StateItem) error
State does need to be read only once pretty much, I don't see why it would be needed to be read for each request where performance or size would matter. Also I don't see becoming it becoming so large where it would be problem.

2021-10-19 07:50 UTC, wxiaoguang commented on modules/appstate/appstate.go
> +	Get(item StateItem) error
OK, we can cache, but caching is not the duty of this module, all users using this module can do their own cache.

This module is just like a lightweight key-value database to store structured data.

I can not understand what's the problem or defect here, does this design make code hard to understand, or hard to use, or run slowly?

2021-10-19 08:30 UTC, lafriks commented on modules/appstate/appstate.go
> +	Get(item StateItem) error
It just about keeping things simple, I don't see a need for abstracting things here and defining multiple types for appstate in multiple modules when we can create single appstate type in this module.

Yes, I agree caching is implemention details

2021-10-19 08:35 UTC, wxiaoguang commented on modules/appstate/appstate.go
> +	Get(item StateItem) error
But without this abstracting, LastAppPath will be mixed with RemoteVersion, I don't think they should be mixed.

ps: I will drop the file support and use database to provide the storage for app state, then refactor RemoteVersion to use app state in a separate PR.

2021-10-19 09:47 UTC, wxiaoguang commented on modules/appstate/appstate.go
> +	Get(item StateItem) error
Re-worked.

2021-10-19 12:56 UTC, 6543 commented
does this make clustering imposible or harder?

2021-10-21 03:07 UTC, lunny commented
@lafriks  Need your review again.

2021-10-21 05:18 UTC, wxiaoguang commented
> Now reading @6543 comment it actually is the problem. What if you run gitea clustered but appstate is local (it's not guaranteed that all servers will have same apppath etc)

1. Test failure is not related, as discussed in discord.
2. Cluster won't be a problem, I have thought about it. We can add a `scope` column to separate global state and local state in future.

2021-10-21 06:55 UTC, lafriks approved these changes

2021-10-21 06:56 UTC, lafriks commented
Ok, this can be left for future than :)

2021-10-21 09:22 UTC, merged