feat: improve render time in large file diffs
go-gitea/gitea pull request #17363
Opened 2021-10-19 22:22 UTC by dpschen

By using content-visibility: auto we get an immediate performance boost in browsers that support that feature at the cost of a bit delayed rendering and jumping scrollbars while scrolling. See https://css-tricks.com/almanac/properties/c/content-visibility/ for a better explanation.

I'm adding this because I was just working on a pull request with >7000 lines changed. Before this change the rendering performance in Chrome on my late 2013 MacBook Pro was that bad that I was not even able to click on the reply button on comments. After this change: no problem.

I'm pretty sure the 500px of the `contain-intrinsic-size` can be chosen more wisely. I just did a random guess.
Might also be that this rule is better preserved in a different selector.

Signed-off-by: Dominik Pschenitschni <mail@celement.de>

2021-10-20 08:36 UTC, dpschen commented
> I can somewhat understand your guess: For a file for which we know nothing about, 500px seems to be close to the expected height. I would have maybe guessed 600-700px, but 500px should also be fine.

I also just realised that the same class applies to the code excerpts in the comments in the conversation tab of a pull request. There this leads to a problem: since the browser expects now a rendering height of 500px and its usually just a few lines—much less— it will jump around :/

Since I don't know the style of gitea very well I'm not sure where else I could apply these rules. Any idea?

2021-11-09 11:50 UTC, lunny approved these changes

2021-11-11 00:50 UTC, Gusted requested changes

2021-11-11 00:50 UTC, Gusted commented on web_src/less/_repository.less
> +      content-visibility: auto;
```suggestion
      // `content-visibility: auto` makes a performance boost in modern browsers for large diffs, `contain-intrinsic-size: 500px` is a magic number which fits most cases.
      content-visibility: auto;
```

Let's just add the suggested comment, and get it merged before v1.16.0 is released.

2021-11-11 01:48 UTC, wxiaoguang commented
> > I can somewhat understand your guess: For a file for which we know nothing about, 500px seems to be close to the expected height. I would have maybe guessed 600-700px, but 500px should also be fine.
> 
> I also just realised that the same class applies to the code excerpts in the comments in the conversation tab of a pull request. There this leads to a problem: since the browser expects now a rendering height of 500px and its usually just a few lines—much less— it will jump around :/
> 
> Since I don't know the style of gitea very well I'm not sure where else I could apply these rules. Any idea?

Agree, jumping around seems to be a small problem. I think we had better tune a little more before merge. ps: I haven't got an answer for this. Maybe other developers can help.

2021-11-11 16:41 UTC, Gusted commented
>  I think we had better tune a little more before merge. ps: I haven't got an answer for this. Maybe other developers can help.

I've tried to give it a shot, to measure the performance of rendering with different values of `contain-intrinsic-size`.

Well now I would like to give you the results, but they are worthless. I have seen little to no difference in the rendering performance between different values, and even removing the `content-visibility` CSS did nothing to the rendering performance, all values where within margin of error, no significant differences. 

I have a feeling that the CSS is applied incorrect, it might be due to that the CSS is applied to a element that also contents a `header`-like element which is a `sticky` element (just a guess). 

Also, this CSS is only applied to a specific mode(split-mode) of diff. If we want to improve render time in large files (diffs) we should apply it a more generic selector.

Note:
The diff was 2.5K lines long, measuring the performance was done on chromium via the built-in performance tab in devtools. No background-services was enabled, just the local gitea server and the browser.

2022-05-24 07:49 UTC, wxiaoguang commented
This PR has been stale for a long time. If no progress or agreement about how to continue, you can use a customized CSS file to apply personal styles for Gitea even if this PR isn't merged.

And thank you for your idea.

2022-06-23 02:05 UTC, closed without merging