make xorm log configable
go-gitea/gitea pull request #174
Opened 2016-11-15 03:30 UTC by lunny

Before xorm's log will be stored `xorm.log`, now it will use the same configuration as `gogs.log`, except the file name from `gogs.log` to `xorm.log`. So that, user could set it to be rotated to avoid disk usage.

2016-11-15 06:58 UTC, tboerger commented on modules/setting/setting.go
> +			Cfg.Section("log").Key("LEVEL").In("Trace", validLevels),
Trace is also part of the slice above

2016-11-15 07:31 UTC, strk requested changes
I pulled this PR locally and tried to create a repository, got:

```
2016/11/15 08:29:30 [...routers/repo/repo.go:101 handleCreateError()] [E] CreatePost: initRepository: initRepoCommit: git push: remote: panic: runtime error: invalid memory address or nil pointer dereference        
remote: [signal 0xb code=0x1 addr=0x0 pc=0x63f930]        
remote: 
remote: goroutine 1 [running]:        
remote: panic(0xfd7e20, 0xc8200121e0)        
remote:         /usr/lib/go-1.6/src/runtime/panic.go:481 +0x3e6        
remote: code.gitea.io/gitea/modules/log.(*XORMLogBridge).ShowSQL(0x0, 0xc82031ac68, 0x1, 0x1)        
remote:         /home/strk/go/src/code.gitea.io/gitea/modules/log/xorm.go:104 +0x40        
remote: code.gitea.io/gitea/vendor/github.com/go-xorm/xorm.(*Engine).ShowSQL(0xc8203052c0, 0xc82031ac68, 0x1, 0x1)        
remote:         /home/strk/go/src/code.gitea.io/gitea/vendor/github.com/go-xorm/xorm/engine.go:51 +0x60        
remote: code.gitea.io/gitea/models.SetEngine(0x0, 0x0)        
remote:         /home/strk/go/src/code.gitea.io/gitea/models/models.go:184 +0x2f2        
remote: code.gitea.io/gitea/cmd.setup(0x1154320, 0xa)        
remote:         /home/strk/go/src/code.gitea.io/gitea/cmd/serve.go:57 +0x103        
remote: code.gitea.io/gitea/cmd.runUpdate(0xc8202cf2c0, 0x0, 0x0)        
remote:         /home/strk/go/src/code.gitea.io/gitea/cmd/update.go:37 +0xcc        
remote: code.gitea.io/gitea/vendor/github.com/urfave/cli.HandleAction(0xe57260, 0x13233b0, 0xc8202cf2c0, 0x0, 0x0)        
remote:         /home/strk/go/src/code.gitea.io/gitea/vendor/github.com/urfave/cli/app.go:471 +0x5e        
remote: code.gitea.io/gitea/vendor/github.com/urfave/cli.Command.Run(0x1128300, 0x6, 0x0, 0x0, 0x0, 0x0, 0x0, 0x1256c80, 0x2e, 0x0, ...)        
remote:         /home/strk/go/src/code.gitea.io/gitea/vendor/github.com/urfave/cli/command.go:191 +0x10b7        
remote: code.gitea.io/gitea/vendor/github.com/urfave/cli.(*App).Run(0xc8201b7860, 0xc82000a180, 0x6, 0x6, 0x0, 0x0)        
remote:         /home/strk/go/src/code.gitea.io/gitea/vendor/github.com/urfave/cli/app.go:241 +0xb65        
remote: main.main()        
remote:         /home/strk/go/src/code.gitea.io/gitea/main.go:40 +0x3a1        
remote: error: hook declined to update refs/heads/master        
To /home/strk/gitea-repositories/strk/repo1.git
 ! [remote rejected] master -> master (hook declined)
error: failed to push some refs to '/home/strk/gitea-repositories/strk/repo1.git'
```

Reverting application of this PR made the new repository creation work.

2016-11-16 07:01 UTC, lunny commented
Yes, a bug, I'm fixing.

2016-11-24 10:09 UTC, tboerger commented
Do we really want to delay that for 1.1.0?

2016-11-24 10:44 UTC, strk commented
Personally I think the soon we can get to 1.0.0 the better, so anything not fundamental can wait if it takes time away from that focus.

2016-11-24 12:21 UTC, lunny commented
I will fix this. Maybe we need change a new log system

2016-11-24 12:34 UTC, tboerger commented
What about a single logrus logger?

2016-11-24 12:35 UTC, tboerger commented
And additionally separate log levels for the different types of logs, so that you can enable general debug log, but disable debug output of xorm

2016-12-29 10:31 UTC, tboerger commented
@lunny please fix the conflicts.

2017-01-11 19:26 UTC, Bwko commented
@lunny Could you resolve the conflicts?

2017-01-12 04:40 UTC, lunny commented
I will update this later.

2017-01-26 04:59 UTC, lunny commented on modules/setting/setting.go
> +			Cfg.Section("log").Key("LEVEL").In("Trace", validLevels),
Yes, this is the default log level

2017-02-12 05:31 UTC, bkcsoft commented
@lunny Any update/status on this?

2017-02-12 05:40 UTC, lunny commented
It's ready to review. I have posted some messages on gitter.

2017-02-12 07:52 UTC, bkcsoft commented
Well, LGTM :)

2017-02-17 21:01 UTC, ethantkoenig requested changes

2017-02-17 21:01 UTC, ethantkoenig commented on modules/setting/setting.go
> +		if disableConsole && mode == "console" {
Should this check take place after calling `strings.TrimSpace()`?

2017-02-17 21:01 UTC, ethantkoenig commented on modules/log/xorm.go
> +package log
Copyright?

2017-02-19 03:31 UTC, lunny commented on modules/setting/setting.go
> +		if disableConsole && mode == "console" {
done.

2017-02-19 03:31 UTC, lunny commented on modules/log/xorm.go
> +package log
done.

2017-02-19 03:49 UTC, ethantkoenig approved these changes

2017-02-19 04:29 UTC, lunny commented
resolved conflicts.

2017-02-19 16:49 UTC, strk commented
starts for me, and logs lots of things on stdout. what/how to test more of it ? is documentation ready somewhere ?

2017-02-20 01:15 UTC, lunny commented
It's controlled by the `[log]` in `app.ini`.

2017-02-20 07:39 UTC, strk commented
Ok, LGTM -- I'm still seeing Macaron logs on console but I guess that's a different thing

2017-02-20 08:11 UTC, merged