Implementation of all repositories of a user from user->settings
go-gitea/gitea pull request #1740
Opened 2017-05-17 14:47 UTC by DblK

This PR implement the display of all repository owned by the user in its settings.

Here is the UI:

The menu:
![image](https://cloud.githubusercontent.com/assets/832617/26159982/462727b8-3b20-11e7-9a36-b97fbf3f7dfd.png)

With no repository:
![image](https://cloud.githubusercontent.com/assets/832617/26160028/64a9a0c6-3b20-11e7-8898-03a6915e4ac5.png)

With all kind of repositories:
![image](https://cloud.githubusercontent.com/assets/832617/26159965/3d8998f2-3b20-11e7-98b9-71510225f161.png)

2017-05-17 15:16 UTC, sondr3 commented on options/locale/locale_en-US.ini
> +repos_none = You do not owned any repository
The phrasing on this is a bit awkward, "You do not own any repositories" is more correct. Although I'm not sure using "own" here is the right term either.

2017-05-17 16:03 UTC, DblK commented on options/locale/locale_en-US.ini
> +repos_none = You do not owned any repository
"You do not have any repositories", maybe?

2017-05-17 16:11 UTC, sondr3 commented on options/locale/locale_en-US.ini
> +repos_none = You do not owned any repository
Ah, yeah, that sounds a lot better in my opinion. Maybe even "You do not currently have any repositories". 😃

2017-05-17 20:11 UTC, geek1011 commented on options/locale/locale_en-US.ini
> +repos_none = You do not currently have any repositories
That's a bit wordy and is not consistent with the rest of the strings. I think it should be "You do not own any repositories".

2017-05-17 20:35 UTC, sondr3 commented on options/locale/locale_en-US.ini
> +repos_none = You do not currently have any repositories
I commented on this earlier and I don't like the wording where you own repositories, I get the meaning behind it but don't think it's too accurate.

2017-05-17 21:24 UTC, geek1011 commented on options/locale/locale_en-US.ini
> +repos_none = You do not currently have any repositories
All the other strings refer to it as owning repositories. Consistency makes everything easier to use and look like everything fits together. What do you mean by it isn't too accurate.

2017-05-20 21:49 UTC, bkcsoft requested changes
Otherwise LGTM :)

2017-05-20 21:49 UTC, bkcsoft commented on options/locale/locale_fr-FR.ini
> +repos=Dépôts
This should be done via CrowdIn. (all languages other than English)

2017-05-21 20:46 UTC, DblK commented on options/locale/locale_fr-FR.ini
> +repos=Dépôts
I removed the french translation

2017-05-21 21:04 UTC, bkcsoft approved these changes

2017-05-21 21:05 UTC, bkcsoft commented
Looks good 🙂  why the ad-hoc list though? It differs from all other lists (tables) in the App. Looks very "thrown together" and out of place 😕

2017-05-22 13:38 UTC, DblK commented
You are right. I didn't know how to display it. It was the same as Github was before.
Here is the new UI I've done for this:
![image](https://cloud.githubusercontent.com/assets/832617/26311108/6231afb4-3f03-11e7-94a9-f89dea8deca0.png)

L-G-T-M does not seems to see your last comments.
Commit and push will be done pretty soon ;)

2017-05-28 04:45 UTC, strk commented
LGTM - but it would be great if you could add integration tests for this new endpoint.

2017-06-16 02:30 UTC, geek1011 commented
LGTM

2017-06-16 02:47 UTC, lunny commented
@geek1011 so many conflicted files?

2017-06-16 04:15 UTC, geek1011 commented
@lunny I was saying L-G-T-M about the idea, and the fact that it works when that branch is build, not the conflicts for merging it.

2017-06-19 06:36 UTC, bkcsoft commented
fixed merge-conflicts

2017-06-23 01:36 UTC, lunny commented
It seems there is a line break after the icon?
![untitled](https://user-images.githubusercontent.com/81045/27462995-44e65a24-57f7-11e7-908f-08baa28f4a0c.png)

2017-06-23 06:35 UTC, lunny commented
@DblK Please confirm the problem, maybe we could move this to v1.2.

2017-06-23 22:03 UTC, geek1011 commented
@lunny @DblK Yes, there is a problem. 

It can be fixed by making the icon and content inline-block, instead of floating it. Floating is less predictable, and it does not work because the content div fills as much space as possible.

2017-07-04 12:29 UTC, DblK commented
I'll fix it soon I hope kinda busy right now.

2017-08-28 01:32 UTC, lunny commented
This could be merged after the little problem resolved. @DblK maybe some maintainer could help you if you are busy now.

2017-09-09 01:35 UTC, DblK commented
If someone else cqn finish it go for it. Not much time right now.

2017-09-14 09:34 UTC, lunny commented
rebased and see below screenshot.
![-1](https://user-images.githubusercontent.com/81045/30422552-e1741e6e-9972-11e7-9849-a991dc39bb5d.png)

2017-09-14 11:46 UTC, merged