Avoid requesting an Avatar image bigger than what the template asks for
go-gitea/gitea pull request #17422
Opened 2021-10-24 17:16 UTC by strk

Hopefully fixes #16287

It makes NO sense to request an avatar of 1160x1160 when it is rendered MUCH MUCH smaller.
See https://try.gitea.io/strk and right-click -> open image in new tab, then check the URL, is formed with `?size=1160` now. I think this PR makes it ask for a size=256 instead (default 128, sizeFactor 2)

2021-10-25 03:41 UTC, wxiaoguang commented on models/avatars/avatar.go
> +const DefaultAvatarPixelSize = 128
This const shouldn't be changed. It is used for small avatars.

2021-10-25 03:41 UTC, wxiaoguang commented on models/avatars/avatar.go
> +const AvatarRenderedSizeFactor = 2
This one seems fine. L-G-T-M.

2021-10-25 03:51 UTC, lunny commented on models/avatars/avatar.go
> +const AvatarRenderedSizeFactor = 2
But I think it just has been changed in #15941 from 2 to 4. @silverwind

2021-12-15 17:48 UTC, zeripath commented
@strk https://github.com/strk/gitea/pull/1  makes this configurable.

2021-12-15 21:25 UTC, strk commented
Thanks @zeripath - I've merged your PR

2021-12-15 21:29 UTC, zeripath approved these changes
I'm going to approve this as it's now configurable. 

I don't mind which setting is used but 4 is almost certainly too high and 1 may be too low.

However, in the interests of getting this merged I will approve.

2021-12-15 21:56 UTC, lafriks commented
Can we make default more close to current behavior, for example `3`?

2021-12-15 22:18 UTC, silverwind commented
Yes, default should be `3` for reasons outlined in https://github.com/go-gitea/gitea/pull/17951.

2021-12-15 23:05 UTC, zeripath commented
I put a pr against @silverwind's to add configuration - I'd be happy to approve that or if you want to make the suggestions against this pr to make the default 3 I think that would be acceptable to.

2021-12-15 23:45 UTC, silverwind commented
https://github.com/go-gitea/gitea/pull/17951 is ready again.

2021-12-16 00:44 UTC, wxiaoguang approved these changes

2021-12-16 00:49 UTC, silverwind requested changes
Blocking merge as the consensus seems to be factor 3 is a good default. https://github.com/go-gitea/gitea/pull/17951 replaces this PR.

2021-12-16 00:56 UTC, wxiaoguang commented
Oh, I see the different, then we use #17951  😊

2021-12-16 02:18 UTC, closed without merging

2021-12-16 16:40 UTC, strk commented
Thanks guys !