Add appearance section in settings
go-gitea/gitea pull request #17433
Opened 2021-10-25 17:40 UTC by qwerty287

Adds a new section "appearance" to the settings and moves the themes/language settings to it. 
See https://github.com/go-gitea/gitea/pull/17414#issuecomment-950395874

cc @lafriks @noerw 

![](https://user-images.githubusercontent.com/80460567/138913155-d9ab9941-df96-42a8-be12-aee9db015151.png)

2021-10-26 15:23 UTC, lafriks requested changes

2021-10-26 15:23 UTC, lafriks commented on routers/web/user/setting/profile.go
> +		ctx.Redirect(setting.AppSubURL + "/user/settings/account")
```suggestion
		ctx.Redirect(setting.AppSubURL + "/user/settings/appearance")
```

2021-10-26 15:23 UTC, lafriks commented on routers/web/user/setting/profile.go
> +		ctx.Redirect(setting.AppSubURL + "/user/settings/account")
```suggestion
		ctx.Redirect(setting.AppSubURL + "/user/settings/appearance")
```

2021-10-26 15:23 UTC, lafriks commented on routers/web/user/setting/profile.go
> +		ctx.Redirect(setting.AppSubURL + "/user/settings/account")
```suggestion
		ctx.Redirect(setting.AppSubURL + "/user/settings/appearance")
```

2021-10-27 11:58 UTC, wxiaoguang approved these changes

2021-10-27 13:00 UTC, lafriks approved these changes

2021-10-27 15:40 UTC, merged