Add more config options to installation page
go-gitea/gitea pull request #17476
Opened 2021-10-28 17:03 UTC by qwerty287

Adds some more config options to the installation page:
* code search (`indexer.REPO_INDEXER_ENABLED`)
* webhooks (`security.DISABLE_WEBHOOKS`)
* OAuth2 provider (`oauth2.ENABLE`)
* attachments (`attachments.ENABLED` and `attachments.MAX_SIZE`)

closes #17389

2021-10-28 18:20 UTC, zeripath commented on options/locale/locale_en-US.ini
> +git_hooks_popup = Disables Git Hooks. If unchecked, users with Git Hook privilege can create custom Git Hooks. WARNING: Custom git hooks can be used to perform arbitrary code execution on the host op
these should be disabled by default and only enabled by people who know what they're doing. I'd argue against including them in this PR.

2021-10-29 02:45 UTC, techknowlogick commented on options/locale/locale_en-US.ini
> +git_hooks_popup = Disables Git Hooks. If unchecked, users with Git Hook privilege can create custom Git Hooks. WARNING: Custom git hooks can be used to perform arbitrary code execution on the host op
+1 for what @zeripath said. This could lead to a situation where someone runs the binary and forgets to install, and by allowing git hooks the first user is an admin which provides shell to the admin.

2021-10-29 02:46 UTC, techknowlogick requested changes
Blocking per @zeripath & my feedback

2021-10-29 05:36 UTC, qwerty287 commented on options/locale/locale_en-US.ini
> +git_hooks_popup = Disables Git Hooks. If unchecked, users with Git Hook privilege can create custom Git Hooks. WARNING: Custom git hooks can be used to perform arbitrary code execution on the host op
Ok, then I'll remove it from the options

2021-11-23 17:25 UTC, qwerty287 commented
@wxiaoguang @techknowlogick @zeripath I'm going to close this because it adds unnecessary complexity. I agree with you that the default values are fine for most users (and I don't need more options for me, just thought this could be useful). If you think this may be still a good change, you can reopen/comment and I'll finish my work on this.

2021-11-23 17:25 UTC, closed without merging

2021-12-13 14:25 UTC, qwerty287 commented
@techknowlogick @wxiaoguang @zeripath since this is closed now, could somebody add the wontfix label to the corresponding issue #17389?