Move unit into models/unit/
go-gitea/gitea pull request #17576
Opened 2021-11-07 03:21 UTC by lunny

As title

2021-11-07 04:03 UTC, wxiaoguang commented
Go doesn't like `mypkg.MyPkgXxx` naming style, that's stupid

2021-11-08 03:38 UTC, wxiaoguang approved these changes

2021-11-08 22:52 UTC, 6543 commented on modules/context/repo.go
> +	unit_model "code.gitea.io/gitea/models/unit"
double import!

2021-11-08 22:56 UTC, 6543 requested changes

2021-11-08 22:56 UTC, 6543 commented on routers/web/repo/setting.go
> +	"code.gitea.io/gitea/models/unit"
same

2021-11-08 22:56 UTC, 6543 commented on routers/api/v1/repo/repo.go
> +	"code.gitea.io/gitea/models/unit"
same

2021-11-09 11:55 UTC, lunny commented
@6543 Done. Please review again.

2021-11-09 11:59 UTC, wxiaoguang commented
We have double-import lint now, so it's easier to find double-imports. 

(CI failure is still related 😂)

2021-11-09 19:07 UTC, 6543 approved these changes

2021-11-09 19:57 UTC, merged