Fix close issue but time watcher still running
go-gitea/gitea pull request #17761
Opened 2021-11-22 15:10 UTC by lunny

back port from #17643

2021-11-22 16:52 UTC, Gusted approved these changes

2021-11-22 22:36 UTC, zeripath requested changes

2021-11-22 22:36 UTC, zeripath commented on models/issue_stopwatch.go
> +	if err := issue.loadRepo(x); err != nil {
```suggestion
	if err := issue.loadRepo(e); err != nil {
```

2021-11-23 02:12 UTC, lunny commented
@zeripath done.

2021-11-23 07:01 UTC, zeripath commented
Do we need to fix main too?

2021-11-23 08:19 UTC, zeripath approved these changes

2021-11-23 08:25 UTC, zeripath commented
There are many ways in which races resulting in a double stopwatches could still happen here.

Realistically the decision to finish or open a new stopwatch should be done within a transaction with select for updates etc.

However this is a backport and this is just yet another example of easily induceable inconsistency under load.

We have to address this at some point though.

2021-11-23 12:05 UTC, merged