Add default host for different database
go-gitea/gitea pull request #17873
Opened 2021-12-01 06:28 UTC by lunny

When set `DBType` as postgres but left `HOST` empty, then the default value of host in installation page will become `127.0.0.1:3306`. It's totally wrong.

2021-12-01 13:07 UTC, silverwind approved these changes

2021-12-01 14:02 UTC, wxiaoguang commented
I think it can be fixed in  https://github.com/go-gitea/gitea/blob/main/web_src/js/features/install.js 

Then we can have a unique behavior, instead of splitting code into backend and frontend.

2021-12-01 14:44 UTC, silverwind commented
> I think it can be fixed in https://github.com/go-gitea/gitea/blob/main/web_src/js/features/install.js

But that applies only to installation, what about already installed apps that just have this configuration wrong? I think certain duplication may be necessary.

2021-12-01 14:50 UTC, wxiaoguang commented
For installed config, if the HOST is lost, then the user's config file must have been corrupted, we should not guess a potential incorrect config option for the user either. Doing too many uncertain things will cause more troubles.

2021-12-02 20:38 UTC, zeripath approved these changes

2021-12-02 21:18 UTC, 6543 approved these changes

2021-12-02 21:19 UTC, 6543 commented
I think it should go in as is ... the UI part is another thing - witch should be fixed by this too ...

2021-12-03 02:04 UTC, wxiaoguang commented
The UI is the key problem, the purpose of this PR is to make the install page show correct default database host, it can be fixed in JS clearly. If we do not want to fix the install UI, we do not need to patch anything.

Changing the default values of the setting module in backend may bring some negative effects:

1. It splits the default values from install page, and it makes it difficult to keep them the same in future (some developers may forget one of them).
2. This changed behavior is not documented. No one has the expectation that HOST has default values (and the default values differ by TYPE)
3. If we want to refactor the setting module in future, such default values may lead to breaking changes.

Since this PR was marked to `wip` by lunny, I think we can keep it as `wip` and wait for lunny's thoughts.

2021-12-03 23:51 UTC, techknowlogick requested changes
marking as blocked per @wxiaoguang's feedback

2021-12-06 09:34 UTC, lunny commented
replaced by #17919

2021-12-06 09:34 UTC, closed without merging