Tab on user profile to show starred repos
go-gitea/gitea pull request #181
Opened 2016-11-15 12:56 UTC by andreynering

Improvements pending for future PRs:

- Have a timestamp in star table and order by it
- Pagination
- Filter

2016-11-17 02:05 UTC, lunny requested changes

2016-11-17 02:05 UTC, lunny commented on models/star.go
> +}
I think all the SQL should be executed in one transaction.

2016-11-17 02:05 UTC, lunny commented on models/star.go
> +		sess = sess.Join("LEFT", "star", "user.id = star.uid")
Just use 
```Go
sess.Join("LEFT", "star", "`user`.id = star.uid")
```
is OK.

2016-11-17 10:56 UTC, lunny commented on models/star.go
> +		sess = sess.Join("LEFT", "star", "user.id = star.uid")
Both are OK.

2016-11-17 10:56 UTC, lunny approved these changes

2016-11-17 11:01 UTC, 0xbaadf00d commented
LGTM

2016-11-18 00:46 UTC, lunny requested changes

2016-11-18 00:46 UTC, lunny commented on models/star.go
> +func StarRepo(userID, repoID int64, star bool) (err error) {
golint error

2016-11-18 00:46 UTC, lunny commented on models/star.go
> +type Star struct {
golint error

2016-11-18 00:46 UTC, lunny commented on models/star.go
> +func (repo *Repository) GetStargazers(page int) ([]*User, error) {
golint

2016-11-18 00:46 UTC, lunny commented on models/star.go
> +func (u *User) GetStarredRepos(private bool) (repos []*Repository, err error) {
golint

2016-11-19 16:15 UTC, andreynering commented
@lunny Updated

2016-11-20 01:02 UTC, lunny requested changes

2016-11-20 01:02 UTC, lunny commented on models/star.go
> +		if _, err := x.Exec("UPDATE `repository` SET num_stars = num_stars + 1 WHERE id = ?", repoID); err != nil {
sess.

2016-11-20 01:02 UTC, lunny commented on models/star.go
> +		if _, err := x.Exec("UPDATE `user` SET num_stars = num_stars + 1 WHERE id = ?", userID); err != nil {
sess.

2016-11-20 01:02 UTC, lunny commented on models/star.go
> +		if _, err := x.Delete(&Star{0, userID, repoID}); err != nil {
sess.

2016-11-20 01:02 UTC, lunny commented on models/star.go
> +		if _, err := x.Exec("UPDATE `repository` SET num_stars = num_stars - 1 WHERE id = ?", repoID); err != nil {
sess.

2016-11-20 01:02 UTC, lunny commented on models/star.go
> +		if _, err := x.Exec("UPDATE `user` SET num_stars = num_stars - 1 WHERE id = ?", userID); err != nil {
sess.

2016-11-20 18:51 UTC, andreynering commented
@lunny You was right. Fixed now.

2016-11-21 00:10 UTC, lunny requested changes

2016-11-21 00:10 UTC, lunny commented on models/star.go
> +
defer sess.Close()

This must be called and sess.Rollback will be invoked in Close if Commit will not be invoked.

2016-11-23 22:45 UTC, andreynering commented on models/star.go
> +
@lunny Updated

2016-11-24 01:45 UTC, lunny approved these changes

2016-12-27 21:38 UTC, andreynering commented
Deprecated in favor of https://github.com/go-gitea/gitea/pull/519

2016-12-27 21:38 UTC, closed without merging