docs(code style): remove unnecessary section
go-gitea/gitea pull request #18209
Opened 2022-01-08 09:38 UTC by appleboy

According to https://github.com/go-gitea/gitea/pull/18145#issuecomment-1007855218 @wxiaoguang comment. 

Signed-off-by: Bo-Yi Wu <appleboy.tw@gmail.com>

2022-01-08 10:09 UTC, wxiaoguang commented
Maybe the text should be replaced by `make lint-backend`, there is only something about lint-frontend but no information about lint-backend.

If I understand correctly, now `make lint-backend` can do all golangci-lint/vet (including revive/misspell), right?

2022-01-08 10:12 UTC, 6543 approved these changes

2022-01-08 10:13 UTC, 6543 requested changes
looking at it again - `make lint-backend` still is usefull!

2022-01-08 10:27 UTC, zeripath approved these changes

2022-01-08 11:34 UTC, appleboy commented
@wxiaoguang Yes, golangci-lint include revive/misspell linter.

2022-01-08 16:25 UTC, techknowlogick approved these changes

2022-01-08 22:14 UTC, 6543 commented
I think we should still mention `lint-backend`

2022-01-11 06:30 UTC, lunny commented
> I think we should still mention `lint-backend`

That could be another PR.

2022-01-11 16:06 UTC, 6543 approved these changes

2022-01-11 23:27 UTC, merged

2022-01-12 13:00 UTC, wxiaoguang commented
I proposed a new PR
* https://github.com/go-gitea/gitea/pull/18249

Hopefully we can keep documents correct and up-dated.