Updated Chroma to v0.10.0
go-gitea/gitea pull request #18270
Opened 2022-01-14 14:42 UTC by MrGussio

Updated Chroma to v0.10.0, and ran the commands `go mod vendor` and `make build`.

2022-01-14 16:44 UTC, techknowlogick approved these changes

2022-01-14 18:17 UTC, zeripath commented
it appears that chroma has now changed its rendering significantly adding `<span class=\"line\"><span class=\"cl\">` before/around lines.

2022-01-14 18:23 UTC, MrGussio commented
> it appears that chroma has now changed its rendering significantly adding `<span class=\"line\"><span class=\"cl\">` before/around lines.

Yes, I noticed. Just did a commit which should fix these issues. Locally I did not have any test errors anymore, now the wait is for the CI to check them as well.

2022-01-14 19:36 UTC, zeripath commented
I think we need to double check what if any effect this has on rendering. 

I think the `<span class="line">` will be being sanitized to `<span>` and there's no CSS for the ".cl" in dark or light.less.

Do you know what these spans are supposed to be doing?

2022-01-14 23:31 UTC, techknowlogick commented
apologies for these conflicts.

2022-01-15 11:21 UTC, singuliere commented
@MrGussio screenshots showing the rendering before and after the upgrade would go a long way to show it looks good. Thanks a lot for this upgrade!

2022-01-15 16:30 UTC, silverwind commented
Need to rebase and remove the `vendor` files as we no longer vendor them since https://github.com/go-gitea/gitea/commit/84145e45c50130922fae9055535ab5ea0378e1d4.

2022-01-15 16:57 UTC, zeripath commented
rebased and updated

2022-01-15 17:20 UTC, silverwind commented
https://github.com/alecthomas/chroma/commit/d6e61d3cbed4f2349d7720b29c14d44ea90ca10d appears to be related to the HTML changes.

I agree we need to be careful here that this does not break any assumptions about Chroma's HTML in our CSS. Possibly also need to update themes in case new classes are introduced.

2022-01-16 05:21 UTC, wxiaoguang requested changes
And we could wait for a new release of Chroma now.

* https://github.com/alecthomas/chroma/pull/595  Many thanks to @silverwind 👍

2022-01-16 11:10 UTC, MrGussio commented
> @MrGussio screenshots showing the rendering before and after the upgrade would go a long way to show it looks good. Thanks a lot for this upgrade!

Build using the latest version of my fork:
![image](https://user-images.githubusercontent.com/5089229/149657266-9c4b0ad6-c223-4042-8f03-a5fea0436ed3.png)
![image](https://user-images.githubusercontent.com/5089229/149657279-f435107e-850b-4946-a3d8-2694a34898f8.png)

Build of commit d7c2a2951c6a0a85f43675c83d3d639cd50eccb4 (before the Chroma update):
![image](https://user-images.githubusercontent.com/5089229/149657334-b6bc1d31-8b03-4561-bbdc-77ea816ac0f4.png)
![image](https://user-images.githubusercontent.com/5089229/149657323-03b8a000-ead3-427f-85ec-9fdea2a060b2.png)

It seems to have no real visual impact. Changes seem to be coming from https://github.com/alecthomas/chroma/commit/d6e61d3cbed4f2349d7720b29c14d44ea90ca10d and https://github.com/alecthomas/chroma/commit/5ed5054d7369706ea7c48993a254a833e194d289 as already mentioned above.

2022-01-19 21:52 UTC, zeripath approved these changes
It doesn't look like chroma is releasing an update soon so I think we should just approve - merge and see how things look IRL.

2022-01-19 23:29 UTC, silverwind commented
I didn't notice any immediate regression from this but I guess the extra wrapping element is unneccary in our rendering too, but I guess it can be improved upon later.

2022-01-19 23:30 UTC, silverwind approved these changes

2022-01-20 03:27 UTC, wxiaoguang commented
A little off-topic, just to remind developers: Chroma uses a lot of abbr class names like `nx`, `nt`, `cl`, `p`.

We also wrote a lot of abbr class names like `df`, `pr`, `ac`, `tc`, `sb`, `vm`, etc. If we continue to use ambiguous abbr names globally, they would conflict and lead to strange bugs in one day.

We should stick to non-ambiguous names in future.

2022-01-20 07:27 UTC, silverwind commented
Happy to accept a PR that refactors our helper classes to something longer.

2022-01-20 09:22 UTC, wxiaoguang approved these changes

2022-01-20 09:59 UTC, merged