Fix some mistakes
go-gitea/gitea pull request #1833
Opened 2017-05-29 22:53 UTC by geek1011

Just noticed some mistakes while using Gitea.

2017-05-29 22:58 UTC, DblK commented
LGTM

2017-05-29 23:04 UTC, ethantkoenig requested changes

2017-05-29 23:04 UTC, ethantkoenig commented on options/locale/locale_en-US.ini
> +settings.add_webhook_desc = Gitea will send a <code>POST</code> request to the URL you specify, along with information about the event that occurred. You can also specify what data format you would l
recieve -> receive

2017-05-29 23:04 UTC, ethantkoenig commented on options/locale/locale_en-US.ini
> +settings.hooks_desc = Webhooks are much like basic HTTP POST event triggers. Whenever something occurs in Gitea, we will send a notification to the target host. Learn more in the <a target="_blank" r
If you're going to decapitalize "webhooks" (in "webhooks guide" at the end of the line), I would also decapitalize "guide"

2017-05-30 09:46 UTC, sapk commented on options/locale/locale_en-US.ini
> +settings.add_webhook_desc = Gitea will send a <code>POST</code> request to the URL you specify, along with information about the event that occurred. You can also specify what data format you would l
If you decapitalize "webhooks guide" in settings.hooks_desc you need to do it here also.

2017-05-31 15:31 UTC, geek1011 commented on options/locale/locale_en-US.ini
> +settings.hooks_desc = Webhooks are much like basic HTTP POST event triggers. Whenever something occurs in Gitea, we will send a notification to the target host. Learn more in the <a target="_blank" r
OK, I forgot

2017-05-31 15:32 UTC, geek1011 commented on options/locale/locale_en-US.ini
> +settings.add_webhook_desc = Gitea will send a <code>POST</code> request to the URL you specify, along with information about the event that occurred. You can also specify what data format you would l
OK, I forgot about that too. I was rushing.

2017-05-31 15:33 UTC, geek1011 commented
Fixed

2017-05-31 15:38 UTC, ethantkoenig approved these changes

2017-05-31 15:38 UTC, ethantkoenig commented
LGTM

2017-05-31 21:56 UTC, sapk commented on options/locale/locale_en-US.ini
> +twofa_passcode_incorrect = Your passcode is incorrect. If you misplaced your device, you can use your scratch code to login.
I would not add "you can use" since it is the only solution "If you misplaced your device"

2017-05-31 21:57 UTC, sapk commented on options/locale/locale_en-US.ini
> +settings.add_webhook_desc = Gitea will send a <code>POST</code> request to the URL you specify, along with information about the event that occurred. You can also specify what data format you would l
We always forgot something (me first) ^^

2017-06-01 15:32 UTC, geek1011 commented on options/locale/locale_en-US.ini
> +twofa_passcode_incorrect = Your passcode is incorrect. If you misplaced your device, you can use your scratch code to login.
Done

2017-06-01 18:01 UTC, sapk commented
LGTM

2017-06-02 00:41 UTC, merged