Changelog for 1.16.0-rc2
go-gitea/gitea pull request #18456
Opened 2022-01-29 21:40 UTC by zeripath

## [1.16.0-rc2](https://github.com/go-gitea/gitea/releases/tag/v1.16.0) - 2022-01-29

* SECURITY
  * Disable content sniffing on `PlainTextBytes` (#18359) (#18365)
  * Only view milestones from current repo (#18414) (#18417)
* BUGFIXES
  * Fix detection of no commits when the default branch is not master (#18422) (#18423)
  * Fix broken oauth2 authentication source edit page (#18412) (#18419)
  * Place inline diff comment dialogs on split diff in 4th and 8th columns (#18403) (#18404)
  * Fix restore without topic failure (#18387) (#18400)
  * Fix commit's time (#18375) (#18392)
  * Fix partial cloning a repo (#18373) (#18377)
  * Stop trimming preceding and suffixing spaces from editor filenames (#18334)
  * Prevent showing webauthn error for every time visiting `/user/settings/security` (#18386)
  * Fix mime-type detection for HTTP server (#18370) (#18371)
* MISC
  * Update github.com/duo-labs/webauthn (#18357) (#18364)

Signed-off-by: Andrew Thornton <art27@cantab.net>

2022-01-29 21:43 UTC, Gusted approved these changes

2022-01-30 10:17 UTC, delvh approved these changes

2022-01-30 10:30 UTC, lunny requested changes
Please wait a coming PR

2022-01-30 15:29 UTC, zeripath commented on CHANGELOG.md
> +  * Fix detection of no commits when the default branch is not master (#18422) (#18423)
```suggestion
  * GitLab reviews may not have the updated_at field set (#18450) #18461
  * Fix detection of no commits when the default branch is not master (#18422) (#18423)
```

2022-01-30 15:29 UTC, zeripath commented on CHANGELOG.md
> +## [1.16.0-rc2](https://github.com/go-gitea/gitea/releases/tag/v1.16.0) - 2022-01-29
```suggestion
## [1.16.0-rc2](https://github.com/go-gitea/gitea/releases/tag/v1.16.0) - 2022-01-30
```

2022-01-30 16:51 UTC, zeripath commented
Closing in favour of jumping straight to 1.16.0

2022-01-30 16:51 UTC, closed without merging