Delete Public SSH Key tmp file after calculating fingerprint
go-gitea/gitea pull request #1855
Opened 2017-06-02 09:12 UTC by dnmgns

Delete the temporary public key file after it has been used to calculate the public key fingerprint.

When using LDAP User Synchronization (#1478) with LDAP Public SSH Keys synchronization (#1844), the public key fingerprint calculation might be running with a quite high frequency.

As the tmp-files for calculating public key fingerprint is not deleted, the system could end up with lots of public tmp files causing inode issue and running out of disk space.

This PR addresses this issue by cleaning up the tmp-file after the fingerprint has been calculated.

2017-06-04 12:06 UTC, sapk commented
LGTM 
overall we should use `ssh-keygen -lf -` and pass keycontent in those cases. This will limit write for performance and maybe preserve some fragile fs like sd card (ex: rpi)

2017-06-04 15:54 UTC, lafriks reviewed
It should be after check for error as on error `writeTmpKeyFile` will return empty string.

2017-06-05 12:22 UTC, dnmgns commented
@lafriks - Yeah, nice catch. And if `writeTmpKeyFile` returns an empty string, there's no file to remove. The defer statement will cause the remove to run even if empty string is returned, thus I guess it's better to put it right before the last return statement and remove the defer statement.

2017-06-05 17:58 UTC, sapk commented on models/ssh_key.go
> +	os.Remove(tmpPath)
You should still use defer before executing ssh-keygen since if the check failed the file is not removed otherwise.

2017-06-05 18:59 UTC, lafriks requested changes

2017-06-05 18:59 UTC, lafriks commented on models/ssh_key.go
> +	os.Remove(tmpPath)
See `SSHKeyGenParsePublicKey` on where to place defer remove

2017-06-07 07:55 UTC, dnmgns commented
Thanks guys! @lafriks @sapk

2017-06-07 08:35 UTC, lafriks approved these changes

2017-06-07 08:36 UTC, lafriks commented
LGTM

2017-06-08 02:08 UTC, merged