Add vendoring section
go-gitea/gitea pull request #187
Opened 2016-11-16 18:13 UTC by strk

Addresses #178

2016-11-16 18:40 UTC, bkcsoft requested changes

2016-11-16 18:40 UTC, bkcsoft commented on CONTRIBUTING.md
> +managing updates via the `govendor` command (github.com/kardianos/govendor)
maybe change to `[govendor](https://github.com/kardianos/govendor)` instead to be consistent :)

2016-11-16 18:40 UTC, bkcsoft commented on CONTRIBUTING.md
> +Pull requests should only include vendor/ updates IFF they are
s/IFF/IF/

2016-11-16 18:40 UTC, bkcsoft commented on CONTRIBUTING.md
> +Pull requests should only include vendor/ updates IFF they are
Also prefer **bold** over CAPS

2016-11-16 18:40 UTC, bkcsoft commented on CONTRIBUTING.md
> +In any case, the vendor/ change needs to be justified as part
`The vendor update needs to be`

2016-11-16 18:42 UTC, strk commented on CONTRIBUTING.md
> +Pull requests should only include vendor/ updates IFF they are
IFF stands for `IF and only IF`

2016-11-16 18:44 UTC, strk commented on CONTRIBUTING.md
> +Pull requests should only include vendor/ updates IFF they are
Anyway, dropped IFF as of 15bd941 (the "only" part is already expressed before)

2016-11-16 19:21 UTC, bkcsoft commented on CONTRIBUTING.md
> +In any case, the vendor/ update needs to be justified as part
I meant get rid of `In any case, `, but that might've been ambiguous :slightly_smiling_face:

2016-11-16 20:00 UTC, strk commented on CONTRIBUTING.md
> +In any case, the vendor/ update needs to be justified as part
Yes, it was. See how you like ac644fd

2016-11-16 22:30 UTC, andreynering commented
LGTM

2016-11-17 02:26 UTC, lunny commented
LGTM. And changes of `CONTRIBUTING.md` should be agreed with all the three owners. @tboerger

2016-11-17 14:05 UTC, bkcsoft approved these changes

2016-11-17 15:06 UTC, tboerger requested changes
And I would put the vendor/ into backticks, makes it better visible as a folder name.

2016-11-17 15:06 UTC, tboerger commented on CONTRIBUTING.md
> +We keep a cached copy of dependencies under the vendor/ directory,
within the vendor/

2016-11-17 16:11 UTC, tboerger commented
You forgot the backticks around the vendor/ mentions

2016-11-17 16:13 UTC, strk commented
I can't see any missing backtick in the files changed tab, can you comment there if you do ?

2016-11-17 16:26 UTC, strk commented
https://github.com/go-gitea/gitea/pull/187/commits/39b3fcad1ddbef541affdc0a1b3e63606da0c85f

2016-11-17 19:21 UTC, tboerger approved these changes

2016-11-17 19:21 UTC, tboerger commented
LGTM

2016-11-17 19:35 UTC, merged

2017-02-06 14:36 UTC, moltam commented
The Vendoring section was removed in [this commit](https://github.com/go-gitea/gitea/commit/91d6c715ea3323cd4b06d21c1aae20364a47a2a0#diff-6a3371457528722a734f3c51d9238c13L60). Was this intentional?

2017-02-10 14:41 UTC, tboerger commented
> The Vendoring section was removed in this commit. Was this intentional?

Not intentional, maybe somebody else got the time to add it back to all our repos?

2017-02-10 15:23 UTC, lunny commented
fixed by https://github.com/go-gitea/gitea/pull/890, @moltam