Set max text height to prevent overflow
go-gitea/gitea pull request #18862
Opened 2022-02-23 02:44 UTC by kdumontnu

Sets a max height for review text boxes to prevent a very annoying bug where users cannot access the "submit" button.

Before:
![image](https://user-images.githubusercontent.com/12700993/155253001-e1dab086-aaf3-4338-889d-6a861728274a.png)

After:
![image](https://user-images.githubusercontent.com/12700993/155253144-5b9a3547-9582-412f-867f-41a45a14a0fe.png)

Interestingly, I don't see this bug on Firefox.

2022-02-23 03:07 UTC, techknowlogick approved these changes

2022-02-23 03:43 UTC, silverwind commented
I think this is an issue with the overall page layout where something prevents this dropdown from creating scrollable page overflow.

That said, this fix does not seem to work in all cases. I still see dropdown cut off on small vertical viewport.

Also I found a potentially related comment here: https://github.com/go-gitea/gitea/blob/2b5e0134307a45581860029de99449e8be8f807e/web_src/js/features/repo-issue.js#L463-L465.

2022-02-23 03:44 UTC, wxiaoguang requested changes
1. EasyMDE has it's own options, see https://github.com/Ionaru/easy-markdown-editor , maxHeight , and our code already supports the customized options, grep `createCommentEasyMDE(textarea, easyMDEOptions = {})`
2. `calc(100vh - 920px)` is incorrect. What if `100vh=930px`, then minHeight=10px?

2022-02-23 03:51 UTC, silverwind commented
We should not need to deal with `max-height` at all. Instead we should allow the page to overflow in such a case. If content goes below the footer, that's okay, I see it happening on GitHub too.

2022-02-23 03:59 UTC, wxiaoguang commented
GitHub's behavior is indeed better. 

At that time, `minHeight` was enough for most cases, and `.diff-detail-box.sticky { position: sticky; }` makes the page difficult to be overflowed with scrollbar, so I just left a comment there.

Although there might need some more CSS work, making the page can be overflowed correctly could be better. 

Either is fine to me and I can also accept that we use maxHeight here as a temporary solution as this PR.

2022-02-23 04:09 UTC, silverwind commented
`position: sticky` alone does not prevent overflow. There's something else preventing it, but it's at least no obvious to me.

2022-02-23 04:48 UTC, wxiaoguang approved these changes

2022-02-23 04:51 UTC, kdumontnu commented
> That said, this fix does not seem to work in all cases. I still see dropdown cut off on small vertical viewport.

Mmm, I see what you mean. I can see it cut off with client height < 400px, which is pretty tiny. Still, I'm not sure how to fix the innate overflow issue and I think this is significantly improved.

2022-02-23 04:59 UTC, kdumontnu commented
Looks like GitHub is broken too, so we can claim feature parity! 😄 
![image](https://user-images.githubusercontent.com/12700993/155263992-cd6f7eb6-50a9-458c-8226-ab184ba4d439.png)

2022-02-23 20:17 UTC, merged

2022-02-23 20:17 UTC, zeripath commented
Please send backport.

2022-03-04 16:45 UTC, CirnoT commented
Was it the intention of this PR to create this situation?

![firefox_2022-03-04_17-35-59](https://user-images.githubusercontent.com/1447794/156802942-1a91e37c-1e7c-4839-91ee-9bbefceb9950.png)
![firefox_2022-03-04_17-36-18](https://user-images.githubusercontent.com/1447794/156802947-e54f25f2-5555-453e-bb83-92830bf573b4.png)
![firefox_2022-03-04_17-36-57](https://user-images.githubusercontent.com/1447794/156802948-a0ce3621-e437-45ac-888d-e944be49cadf.png)

It would seem that this doesn't apply `max-height` but `min-height` instead:
![firefox_2022-03-04_17-41-13](https://user-images.githubusercontent.com/1447794/156803931-f394d95d-eb62-49bf-80b9-8483ad124f62.png)

![firefox_2022-03-04_17-41-00](https://user-images.githubusercontent.com/1447794/156803914-85b5ea81-581a-47d3-b014-b4914062f869.png)

2022-03-04 17:26 UTC, wxiaoguang commented
The PR to fix it:

* https://github.com/go-gitea/gitea/pull/19003