Prevent invalid GPG key response
go-gitea/gitea pull request #18961
Opened 2022-03-01 20:50 UTC by KN4CK3R

Prevents the invalid reponse if there are no keys:
```
-----BEGIN PGP PUBLIC KEY BLOCK-----

=twTO
-----END PGP PUBLIC KEY BLOCK-----
```

Additional questions:
- Should `ShowSSHKeys` do the same?
- Is this an "api" endpoint and the response should be just the plain 404 response code instead of the html page? If yes we need to add an addition route for `/orgs/<org>.gpg` to get the same behaviour there too.

2022-03-01 20:54 UTC, 6543 approved these changes

2022-03-01 21:01 UTC, Gusted approved these changes

2022-03-01 21:04 UTC, Gusted commented
> * Should `ShowSSHKeys` do the same?

Yes.



> Is this an "api" endpoint and the response should be just the plain 404 response code instead of the html page? If yes we need to add an addition route for `/orgs/<org>.gpg` to get the same behaviour there too.

So far I can see, it's only used in the web part.

2022-03-01 21:06 UTC, KN4CK3R commented
> So far I can see, it's only used in the web part.

Yes, but the response looks like something a tool uses as input which could be confused by html error page.

2022-03-01 21:08 UTC, Gusted commented
> > So far I can see, it's only used in the web part.
> 
> Yes, but the response looks like something a tool uses as input which could be confused by html error page.

Well, I hope that tools can detect a simple 404 statuscode 😅 .

2022-03-01 21:50 UTC, zeripath approved these changes

2022-03-01 21:51 UTC, zeripath requested changes

2022-03-01 21:51 UTC, zeripath commented on routers/web/user/home.go
> +		ctx.NotFound("", nil)
Actually - no this should just return a blank page.

2022-03-01 21:51 UTC, zeripath commented
This should be a blank page.

2022-03-02 10:35 UTC, Gusted approved these changes

2022-03-02 10:37 UTC, Gusted commented
CI errors are related `TestExportUserGPGKeys` test needs to be adjusted.

2022-03-02 12:14 UTC, Gusted commented
Should this be backported?

2022-03-02 14:57 UTC, zeripath approved these changes

2022-03-02 14:58 UTC, zeripath commented
This is very minor - a backport is reasonable but equally not sending one is also reasonable.

2022-03-02 16:32 UTC, merged