API Endpoint for watching
go-gitea/gitea pull request #191
Opened 2016-11-17 21:39 UTC by ethantkoenig

This pull request adds the following API endpoints:
- `GET /users/:username/subscriptions`: List repositories watched by a user
- `GET /user/subscriptions`: List repositories watched by authenticated user
- `GET /user/subscriptions/:owner/:repo`: If authenticated user is watching a repository
- `PUT /user/subscriptions/:owner/:repo`: Watch a repository (as authenticated user)
- `DELETE /user/subscriptions/:owner/:repo`: Unwatch a repository (as authenticated user)

Each of these endpoints already exists in [the Github API](https://developer.github.com/v3/activity/watching/).

2016-11-18 00:25 UTC, lunny requested changes

2016-11-18 00:25 UTC, lunny commented on routers/api/v1/user/watch.go
> +package user
copyrigt

2016-11-18 04:23 UTC, ethantkoenig commented on routers/api/v1/user/watch.go
> +package user
Added

2016-11-19 18:08 UTC, ethantkoenig commented
@lunny I have added the copyright, please review again.

2016-11-29 13:09 UTC, bkcsoft requested changes

2016-11-29 13:09 UTC, bkcsoft commented on routers/api/v1/user/watch.go
> +		repos[i] = watched.APIFormat(&api.Permission{true, true, true})
Please don't guess the Permissions...

2016-11-29 13:09 UTC, bkcsoft commented on routers/api/v1/user/watch.go
> +		ctx.Status(204)
You should return the following data as well:
```
{
  "subscribed": true,
  "ignored": false,
  "reason": null,
  "created_at": "2012-10-06T21:34:12Z",
  "url": "https://api.github.com/repos/octocat/example/subscription",
  "repository_url": "https://api.github.com/repos/octocat/example"
}
```

2016-11-29 13:09 UTC, bkcsoft commented on routers/api/v1/user/watch.go
> +		ctx.Status(500)
_Never_ silently drop errors... _Always_ log them

2016-11-29 13:09 UTC, bkcsoft commented on routers/api/v1/user/watch.go
> +		ctx.Status(500)
Ditto

2016-11-29 13:10 UTC, bkcsoft commented
At a closer look it seems like you're implementing the _legacy_ Watching-API, any reason why you're not implementing the new one?

2016-11-29 15:14 UTC, lunny commented on routers/api/v1/user/watch.go
> +package user
The Gitea Authors?

2016-11-29 22:16 UTC, ethantkoenig commented on routers/api/v1/user/watch.go
> +package user
Whoops, fixed.

2016-11-29 22:22 UTC, ethantkoenig commented
@bkcsoft When I wrote this code (~1 month ago), the legacy watching API was not yet legacy; apologies for not keeping my PR up-to-date.

I've addressed all of your issues except the repo permissions. I have not been able to find any places in the code where `api.Permission` is correctly populated for an arbitrary repo. For instance, the `GET /repos/:owner/:repo` endpoint defaults to `true`. Since I can't find any examples to emulate, I'm not sure how to go about correctly populating `api.Permission`. If you can point me in the right direction, I would be happy to fix it.

2016-11-30 01:30 UTC, lunny commented
lint errors, see https://drone.gitea.io/go-gitea/gitea/176

2016-11-30 01:33 UTC, lunny approved these changes

2016-12-01 08:58 UTC, bkcsoft commented on routers/api/v1/user/watch.go
> +			Pull:  true,
basically you do this:
```
user, err := models.GetUserById(userID) // check error
access ,err := models.AccessLevel(user, watched) // check error
repos[i] = [...] {
  Admin: access >= models.AccessModeAdmin,
  Push: access >= models.AccessModeWrite,
  Pull: access >= models.AccessModeRead,
}
```
For faster checks, fetch `user, err :=` _outside_ the loop :)
(Untested, Unverified, Not sanity-checked 😆 )

2016-12-01 15:25 UTC, ethantkoenig commented on routers/api/v1/user/watch.go
> +			Pull:  true,
Thanks for the pointer! Fixed.

2016-12-02 08:07 UTC, bkcsoft approved these changes

2016-12-02 08:07 UTC, bkcsoft commented
LGTM

2016-12-03 03:13 UTC, ethantkoenig commented
@bkcsoft @tboerger @lunny Is this ready to merge?

2016-12-03 05:39 UTC, lunny commented
LGTM and I think this could be merged after 1.0 released.

2016-12-03 09:27 UTC, tboerger commented
Yeah we really need to finish 1.0.0

2016-12-07 07:00 UTC, richmahn commented on routers/api/v1/user/watch.go
> +		repos[i] = watched.APIFormat(&api.Permission{
If you want this to work with your api/fixes branch, need to change this to just watched.APIFormat(access)

2016-12-07 14:14 UTC, ethantkoenig commented on routers/api/v1/user/watch.go
> +		repos[i] = watched.APIFormat(&api.Permission{
I was aware, but thanks for the heads up.

2016-12-24 01:49 UTC, lunny commented
I think this could be merged.

2016-12-24 01:52 UTC, lunny commented
LGTM

2016-12-24 01:53 UTC, merged