Switch to keybase go-crypto (for some elliptic curve key) + test
go-gitea/gitea pull request #1925
Opened 2017-06-10 00:09 UTC by sapk

Fix #1898 by using keybase/go-crypto in place of golang.org/x/crypto.

In folder openpgp, keybase/go-crypto is not that far away of golang.org/x/crypto and implement more key type.

2017-06-11 07:40 UTC, bkcsoft commented
LGTM. Though I'd prefer go-crypto/openpgp to be merged into stdlib 😉

2017-06-12 22:07 UTC, ethantkoenig requested changes

2017-06-12 22:07 UTC, ethantkoenig commented on models/gpg_key_test.go
> +	assert.Nil(t, err, "Could not parse a valid GPG armored key", key)
For checking errors, you should use `assert.NoError(..)`

2017-06-13 13:28 UTC, ethantkoenig approved these changes

2017-06-13 13:34 UTC, sapk commented on models/gpg_key_test.go
> +	assert.Nil(t, err, "Could not parse a valid GPG armored key", key)
done and update all test in this file to use .Error .NotError

2017-06-13 21:00 UTC, Bwko commented
LGTM

2017-06-14 00:43 UTC, merged