Restrict creating organisations by user
go-gitea/gitea pull request #193
Opened 2016-11-18 18:30 UTC by Schwobaland

Allows to restrict, wether an user is allowed to create organisations. See #177.

2016-11-18 19:54 UTC, strk commented on conf/locale/locale_de-DE.ini
> +form.create_org_not_allowed=Dieser Benutzer darf keine Organisation erstellen.
I think you're supposed to only modify the english localization, whereas other languages are delegated to an external service. Please @lunny, @bkcsoft, @tboerger  correct me if I'm wrong

2016-11-18 19:55 UTC, strk commented on models/migrations/v15.go
> +	return x.Sync2(new(UserV15))
What's the default value set for existing users upon migration ?

2016-11-18 19:57 UTC, strk commented on models/migrations/migrations.go
> +	ini "gopkg.in/ini.v1"
If this isn't needed for your patch please avoid the change

2016-11-18 19:58 UTC, strk requested changes
Please don't include bindata.go modifications in the PR

2016-11-18 21:09 UTC, Schwobaland commented on conf/locale/locale_de-DE.ini
> +form.create_org_not_allowed=Dieser Benutzer darf keine Organisation erstellen.
I didn't find the translation service for gitea. There is only Crowdin for (gogs)[https://crowdin.com/project/gogs] and an empty project for (gitea)[https://crowdin.com/project/gitea].

2016-11-18 21:14 UTC, tboerger commented on conf/locale/locale_de-DE.ini
> +form.create_org_not_allowed=Dieser Benutzer darf keine Organisation erstellen.
We want to use an external service again but it's not enabled yet

2016-11-18 21:15 UTC, tboerger commented on models/migrations/migrations.go
> +	ini "gopkg.in/ini.v1"
As long as it's done in a separate commit it's OK. It's an goimports correction.

2016-11-18 21:19 UTC, tboerger commented
Please never update vendored libs, it needs to be integrated upstream first and than updated via govendor

2016-11-18 21:54 UTC, Schwobaland commented
Thanks for your reviews. I reverted the changes you suggested to remove. The field AllowCreateOrganization is set to true in migration script.
Please review again.

2016-11-18 22:57 UTC, tboerger commented
It already looks pretty fine, but you want to set a default value to true, otherwise registered users are not allowed to create organizations

2016-11-20 17:23 UTC, Schwobaland commented
added default value both in  `CreateUser`-function and in xorm-annotation

2016-11-21 09:28 UTC, strk commented
It would be useful if the site administrator was given the option to decide which permissions to give by default to new users.

2016-11-24 10:14 UTC, tboerger commented
This PR needs to be delayed until the branch of 1.0 anyway.

2016-12-06 18:32 UTC, bkcsoft commented
LGTM. While I do agree with @strk, that can be implemented at a later point :)

2016-12-14 17:46 UTC, ethantkoenig commented on models/migrations/migrations.go
> +	NewMigration("create user colum allow create organization", createAllowCreateOrganizationColumn),
`"... column ..."`?

2016-12-14 17:46 UTC, ethantkoenig commented on models/user.go
> +// CanCreateOrg returns true if user can create organisation.
`CanCreateOrganization`?

2016-12-29 10:34 UTC, tboerger commented
Please resolve the conflicts

2016-12-30 20:43 UTC, Schwobaland commented on models/migrations/migrations.go
> +	NewMigration("create user colum allow create organization", createAllowCreateOrganizationColumn),
fixed typo

2016-12-30 20:43 UTC, Schwobaland commented on models/user.go
> +// CanCreateOrg returns true if user can create organisation.
fixed typo

2016-12-30 20:47 UTC, Schwobaland commented
conflicts resolved

2016-12-31 02:32 UTC, lunny commented
LGTM

2016-12-31 02:33 UTC, merged