Fix panic in teams API when requesting members
go-gitea/gitea pull request #19360
Opened 2022-04-09 15:15 UTC by delvh

As title.

Should fix #19359

2022-04-09 15:23 UTC, delvh commented
CI is dead, that's the reason why the build fails.

2022-04-09 15:29 UTC, Gusted approved these changes
If this code also exist in the release/1.16 branch it should be backported.

2022-04-09 15:41 UTC, lunny approved these changes

2022-04-09 15:42 UTC, lunny requested changes
No, you can't do both. I think you can just change only line 390.

2022-04-09 15:42 UTC, lunny commented on routers/api/v1/org/team.go
> +	for _, member := range teamMembers {
```suggestion
	for i, member := range teamMembers {
		members[i] = convert.ToUser(member, ctx.Doer)
```

2022-04-09 15:43 UTC, lunny commented on routers/api/v1/org/team.go
> +		members = append(members, convert.ToUser(member, ctx.Doer))
```suggestion
	for i, member := range teamMembers {
		members[i] = convert.ToUser(member, ctx.Doer)
```

2022-04-09 15:44 UTC, delvh commented
I mean, what's the benefit?
Both should work, with the only difference that with `append` another error like this cannot happen...
But I can apply it of course.

2022-04-09 15:52 UTC, lunny approved these changes

2022-04-09 15:53 UTC, lunny commented
> I mean, what's the benefit? Both should work, with the only difference that with `append` another error like this cannot happen... But I can apply it of course.

Both should work, but you should only chose one. You can't chose both, otherwise the slice will have 2 times elements and the first part are empty elements.

2022-04-11 12:49 UTC, wxiaoguang approved these changes

2022-04-11 12:49 UTC, merged