Fix deleted milestone bug
go-gitea/gitea pull request #1942
Opened 2017-06-12 02:43 UTC by ethantkoenig

Fixes a bug where viewing an issue from a deleted milestone resulted in a 500 (because comments from that issue would still refer to the deleted milestone, which gitea would then try to load).

When deleting a milestone, delete all comments referencing that milestone.

2017-06-14 00:48 UTC, lunny commented
Why delete these comments?

2017-06-14 01:21 UTC, ethantkoenig commented
@lunny Setting `MilestoneID` to 0 won't fix the problem, as long as the comment exists, we will try to load milestone `comment.MilestoneID` and get an error

2017-06-15 00:47 UTC, bkcsoft commented
Just don't load the milestones instead? 😖 Deleting all comments on issue where the milestone doesn't exist is _not_ the solution...

2017-06-15 00:47 UTC, bkcsoft commented
Why does the comments even link to milestones in the first place?! 😂

2017-06-15 00:51 UTC, ethantkoenig commented
To be clear, the "comments" that are being deleted are not comments that users write, but things like "userXYZ added label123 three days ago"

2017-06-15 00:57 UTC, bkcsoft commented
Right, personally I'd just replace `1.2.0` with `<deleted>` (or similar) whenever we can't find the milestone we're looking for (similar to a Ghost User)

2017-06-15 16:36 UTC, ethantkoenig commented
@lunny @bkcsoft Updated to use "ghost" milestones instead of deleting comments.

2017-06-15 20:34 UTC, lafriks commented
When build is fixed than LG-TM

2017-06-15 21:51 UTC, ethantkoenig commented
Rebased to re-run CI

2017-06-15 21:52 UTC, lafriks requested changes

2017-06-15 21:52 UTC, lafriks commented on models/issue_milestone.go
> +		Name: "Deleted",
This should be translatable

2017-06-15 23:47 UTC, ethantkoenig commented
FWIW, we currently set comments `labelID` to 0 when a label is, which is effectively equivalent to deleting the comment (the comment is never displayed again).

2017-06-15 23:48 UTC, ethantkoenig commented on models/issue_milestone.go
> +		Name: "Deleted",
Done

2017-06-15 23:51 UTC, ethantkoenig commented
CI build keeps failing due to locking in `make test-sqlite` :cry:

2017-06-16 00:55 UTC, lunny commented
@ethantkoenig I restarted it and LGTM

2017-06-16 00:56 UTC, lunny requested changes

2017-06-16 00:56 UTC, lunny commented on models/issue_comment.go
> +		has, err := x.ID(c.OldMilestoneID).Get(oldMilestone)
should be `&oldMilestone`

2017-06-16 00:56 UTC, ethantkoenig commented on models/issue_comment.go
> +		has, err := x.ID(c.OldMilestoneID).Get(oldMilestone)
Good catch

2017-06-16 15:33 UTC, lafriks approved these changes

2017-06-16 15:43 UTC, lafriks commented
LGTM

2017-06-16 16:49 UTC, ethantkoenig commented on models/issue_comment.go
> +		has, err := x.ID(c.OldMilestoneID).Get(oldMilestone)
@lunny Fixed

2017-06-17 04:50 UTC, lunny approved these changes

2017-06-17 04:51 UTC, merged