Add wrapping to long diff lines to fix #1827
go-gitea/gitea pull request #1954
Opened 2017-06-12 16:23 UTC by mjwwit

This PR adds line wrapping to the unified diff view (for long lines) (#1827). Wrapping was already done in the split view.
An additional change has been made to align the line-numbers of wrapped diff lines to the top of the line.
![gitea-long-diff-line-wrapped](https://user-images.githubusercontent.com/4455124/27043956-2a14577c-4f9c-11e7-9cef-913284beb9e2.png)

2017-06-12 16:40 UTC, bkcsoft commented
Maybe have a checkbox toggle? For those that don't want wrapping :)

Also Closes #1827

2017-06-12 16:47 UTC, mjwwit commented
The wrapping was already default behavior for the split view, are you sure you want a setting for this?
If you do want a setting, where should it be located? (we don't really have a user preferences view)
Also, should it store the preference server-side or simply keep it client-side?

2017-06-12 17:21 UTC, ethantkoenig requested changes

2017-06-12 17:21 UTC, ethantkoenig commented on public/css/index.css
> +  vertical-align: top;
Please don't edit `index.css` directly, instead edit the appropriate `.less` file

2017-06-12 18:01 UTC, silverwind commented
> If you do want a setting, where should it be located?

Maybe beside 'View File' in the header?

BTW I also noticed an error in the `.wrap` CSS: The current `break-word` value for `word-break` is invalid. It should be `break-all`. I recommend these rules for it:

```
white-space: pre-wrap;
word-break: break-all;
overflow-wrap: break-word;
```

Oh, and I also think this change should apply to regular code view, not just diffs.

2017-06-12 19:54 UTC, mjwwit commented on public/css/index.css
> +  vertical-align: top;
Ugh... I hate generated code in VCS... I'll fix it though, good spot!

2017-06-12 20:11 UTC, mjwwit commented
I assumed the `wrap` class would have a proper implementation, as it turns out I was wrong. I have to keep the non-standard `word-break: break-word;` as well though, as it's needed for WebKit to function properly.

2017-06-12 20:37 UTC, silverwind commented
Looks like `word-break: break-word` [is superceded](https://stackoverflow.com/a/15137272/808699) by `overflow-wrap: break-word`, so these two should be equivalent. I can at least say that the former isn't recognized by Firefox any more:

<img width="357" src="https://user-images.githubusercontent.com/115237/27054004-b167b282-4fbf-11e7-9f84-e0229da8384d.png">

2017-06-12 20:52 UTC, mjwwit commented
Interesting, reading the W3C spec leads me to believe `overflow-wrap` can be used in in addition to `word-break`. I don't think one is superseded by the other.

`word-break: break-word;` should only be used (and will only be accepted) by WebKit. Other browsers correctly implemented the standard `word-break: break-all;` value.

2017-06-12 20:59 UTC, silverwind commented
Both are valid in WebKit:

<img width="248" src="https://user-images.githubusercontent.com/115237/27054792-8596a052-4fc2-11e7-9b81-c3799689f76b.png">

The [spec](https://www.w3.org/TR/css-text-3) seems pretty clear to me. `word-wrap` does not list it as a valid property value and `overflow-wrap` contains this note:

> For legacy reasons, UAs must treat ‘word-wrap’ as an alternate name for the ‘overflow-wrap’ property, as if it were a shorthand of ‘overflow-wrap’.

2017-06-12 21:34 UTC, lafriks requested changes

2017-06-12 21:34 UTC, lafriks commented on public/less/_base.less
> +  	overflow-wrap: break-word;
Something seems to be wrong with tabs

2017-06-13 14:07 UTC, ethantkoenig approved these changes

2017-06-13 17:26 UTC, mjwwit commented
> The spec seems pretty clear to me. `word-wrap` does not list it as a valid property value and `overflow-wrap`...
But we're talking about `word-break` and `overflow-wrap`, not `word-wrap`.

2017-06-14 00:45 UTC, lunny commented
need @lafriks approval.

2017-06-14 09:57 UTC, silverwind commented
> But we're talking about word-break and overflow-wrap, not word-wrap.

Yeah, my error, I meant `word-break`. Anyways, I think you should try my suggestion in https://github.com/go-gitea/gitea/pull/1954#issuecomment-307868910, it should be all that's needed to achieve consistent cross-browser wrapping.

2017-06-14 22:09 UTC, lafriks approved these changes

2017-06-14 22:18 UTC, lafriks requested changes
When tabs are fixed than LG-TM

2017-06-14 22:18 UTC, lafriks commented on public/less/_repository.less
> +						td.message .isSigned {
Too much tabs

2017-06-14 22:18 UTC, lafriks commented on public/less/_repository.less
> +						.jumpable-path {
Too much tabs

2017-06-14 22:18 UTC, lafriks commented on public/less/_repository.less
> +								font-family: "Consolas", monospace;
Too much tabs

2017-06-14 22:18 UTC, lafriks commented on public/less/_repository.less
> +				td.sha .sha.label {
Too much tabs

2017-06-14 22:18 UTC, lafriks commented on public/less/_repository.less
> +		#commits-table td.sha .sha.label, #repo-files-table .sha.label{
Too much tabs in all levels

2017-06-14 22:18 UTC, lafriks commented on public/less/_repository.less
> +				&:not(.positive){
Too much tabs

2017-06-14 22:18 UTC, lafriks commented on public/less/_repository.less
> +		display: none;
One tab too much :)

2017-07-04 08:19 UTC, mjwwit commented
This whole formatting problem is caused by the .editorconfig file stating that indentation should be done using 4 spaces, but the less files are using tabs. Which should it be?

2017-07-05 10:42 UTC, mjwwit commented
Lack of response leads me to believe nobody really cares if indentation is done using spaces or tabs, so I'll go with 4 spaces.

2017-07-05 16:07 UTC, silverwind commented
Getting back to the topic of having it also apply on regular code views: Why should it only wrap in diffs? If you have a long line in a diff, it'll be a long line in the regular code view. I'd rather have both wrap for consistence.

Of course, a checkbox toggle in the header would be ideal, but that can come later, imho.

2017-07-05 18:47 UTC, mjwwit commented
This may just be me, but I generally hate wrapping in code. The only time I do find it useful is when I need to see the difference between two pieces of code in a single glance. The wrapping is especially useful in a side-by-side diff, where the horizontal space is extra limited. I'm not against implementing wrapping in normal code-views as well, but I'd rather build the toggle setting with it so I can turn it off. Would you be willing to wait for the normal code view wrapping until that time?

2017-07-05 19:25 UTC, lafriks commented
@mjwwit in code view and diff view code wrapping is needed as otherwise if code block is larger than screen you have to scroll to the bottom of code block to be able to scroll to right

2017-07-06 15:36 UTC, silverwind commented
I'm fine if you want to do it later with the toggle. Having it in diffs is already an improvement. Side-by-side diffs already wrap without this patch for me, by the way.

Also agree with @lafriks, horizontal scroll on big files is generally a bad UX, but there are options like using the arrow keys to scroll.

2017-07-06 15:36 UTC, silverwind approved these changes

2017-07-06 17:03 UTC, lafriks approved these changes

2017-07-06 17:07 UTC, lafriks commented
I'm vote for 4 spaces for tabing just wanted more opinion from other Gitea developers. If other are also OK with that than it is LG-TM

2017-07-06 17:53 UTC, bkcsoft commented
@lafriks LG-TM on 4 space. Haven't reviewed this one though so no real LG-TM from me ;)

2017-09-15 15:10 UTC, lunny commented
hi, please rebase.

2017-10-25 20:38 UTC, lafriks commented
Rebased and tested, LGTM

2017-10-26 21:27 UTC, closed without merging