GetFeeds must always discard actions with dangling repo_id
go-gitea/gitea pull request #19598
Opened 2022-05-03 22:42 UTC by singuliere

See https://discourse.gitea.io/t/blank-page-after-login/5051/12
for a panic in 1.16.6.

2022-05-03 22:58 UTC, 6543 commented on models/fixtures/action.yml
> +  repo_id: 1700
```suggestion
  repo_id: 1700 # dangling intentional
```

2022-05-03 22:58 UTC, 6543 approved these changes

2022-05-03 23:09 UTC, Gusted approved these changes
LGTM, seems a bit hacky tbh. Seems like we should actually fix `loadRepoOwner` to not panic.

2022-05-03 23:30 UTC, 6543 requested changes
`TestPrivateActivityNoVisibleForPublic` fails related :/

2022-05-04 00:24 UTC, singuliere commented
> LGTM, seems a bit hacky tbh. Seems like we should actually fix `loadRepoOwner` to not panic.

I agree. Now that the tests are passing I'll try to follow your suggestion.

2022-05-04 00:37 UTC, singuliere commented
@Gusted Added a safeguard so **loadRepoOwner** is no longer susceptible to panic on action.Repo == nil

2022-05-04 06:10 UTC, techknowlogick commented
@singuliere please refrain from force pushes, it makes it hard to review PRs

2022-05-04 07:57 UTC, lunny approved these changes

2022-05-04 10:10 UTC, 6543 approved these changes

2022-05-05 15:39 UTC, merged

2022-05-05 15:39 UTC, techknowlogick commented
@singuliere please send backport :)