Issue #1957 - Fix forwarding stdin to pre/post-receive scripts
go-gitea/gitea pull request #1975
Opened 2017-06-15 07:51 UTC by coredumb

Fix https://github.com/go-gitea/gitea/issues/1957
Ensure stdin is forwarded for pre/post-receive hooks

2017-06-15 07:59 UTC, lafriks requested changes
It should be as new migration step as otherwise scripts won't be updated for anyone using 1.1+ version

2017-06-15 08:01 UTC, coredumb commented
Oh now I have to get a grasp of those migration steps ^^

2017-06-18 13:45 UTC, lunny commented
And maybe some integration test? There are many examples in `integrations` directory.

2017-06-19 08:39 UTC, bkcsoft requested changes

2017-06-19 08:39 UTC, bkcsoft commented on models/migrations/v22.go
> +			fmt.Sprintf("#!/usr/bin/env %s\nORI_DIR=`pwd`\nSHELL_FOLDER=$(cd \"$(dirname \"$0\")\";pwd)\nread STDIN\ncd \"$ORI_DIR\"\nfor i in `ls \"$SHELL_FOLDER/pre-receive.d\"`; do\n    echo \"$STDIN\" | s
No, this need a _new_ migration since this has already been ran...

2017-06-19 08:42 UTC, coredumb commented on models/migrations/v22.go
> +			fmt.Sprintf("#!/usr/bin/env %s\nORI_DIR=`pwd`\nSHELL_FOLDER=$(cd \"$(dirname \"$0\")\";pwd)\nread STDIN\ncd \"$ORI_DIR\"\nfor i in `ls \"$SHELL_FOLDER/pre-receive.d\"`; do\n    echo \"$STDIN\" | s
I agree for already migrated instances, but not on instances still on gogs that will migrate to gitea...
Or you mean that it's pointless anyway cause it needs its own migration step anyway that will happen in both cases ?

2017-06-19 08:44 UTC, bkcsoft commented on models/migrations/v22.go
> +			fmt.Sprintf("#!/usr/bin/env %s\nORI_DIR=`pwd`\nSHELL_FOLDER=$(cd \"$(dirname \"$0\")\";pwd)\nread STDIN\ncd \"$ORI_DIR\"\nfor i in `ls \"$SHELL_FOLDER/pre-receive.d\"`; do\n    echo \"$STDIN\" | s
For instances migrating from Gogs, they will have to go through all migrations. The latest migration to touch a file "wins" 🙂

2017-06-19 09:07 UTC, coredumb commented on models/migrations/v22.go
> +			fmt.Sprintf("#!/usr/bin/env %s\nORI_DIR=`pwd`\nSHELL_FOLDER=$(cd \"$(dirname \"$0\")\";pwd)\nread STDIN\ncd \"$ORI_DIR\"\nfor i in `ls \"$SHELL_FOLDER/pre-receive.d\"`; do\n    echo \"$STDIN\" | s
Understood. I'll remove the modification from there and add it in its own migration step then.

2017-07-01 21:51 UTC, lafriks commented
This issue is actually already resolved in commit https://github.com/go-gitea/gitea/commit/fe94032f74298569512f6ece2fbe4f7ab9a24e46 and this PR just fixes older migrations that will be overridden by migration v26 anyway

2017-07-01 21:51 UTC, closed without merging