Added sorting to the milestones page
go-gitea/gitea pull request #199
Opened 2016-11-20 16:45 UTC by Bwko

Partially solves  #10

2016-11-20 19:04 UTC, andreynering requested changes
Thank you for the PR.

Made just a single small request of change.

2016-11-20 19:04 UTC, andreynering commented on conf/locale/locale_en-US.ini
> +milestones.filter_sort.closestduedate = Closest due date
Use underscore for translation keys:

`closestduedate` -> `closest_due_date`

2016-11-20 19:16 UTC, Bwko commented
@andreynering I've updated my PR

2016-11-20 19:45 UTC, andreynering commented
LGTM

2016-11-20 19:45 UTC, andreynering approved these changes

2016-11-20 20:42 UTC, 0xbaadf00d commented
LGTM

2016-11-20 21:36 UTC, tboerger requested changes

2016-11-20 21:36 UTC, tboerger commented on templates/repo/issue/labels.tmpl
> +			<div class="ui dropdown type jump item">
Please fix the indentation

2016-11-21 10:44 UTC, Bwko commented
@tboerger Do you mean the` <!-- Sort --> & </div>?`
Is there a tool to automatically format the Golang template files?

2016-11-21 11:41 UTC, tboerger commented
If your editor supports editorconfig it should save it properly

2016-11-21 12:35 UTC, Bwko commented
My editor didn't support editorconfig files, I had to add a plugin.
Fixed & rebased

2016-11-21 13:32 UTC, tboerger commented on templates/repo/issue/milestones.tmpl
> +        </div>
Still some wrong indentation :D

2016-11-21 14:38 UTC, Bwko commented
Solved

2016-11-21 23:20 UTC, tboerger commented
LGTM, will be merged when we branch the 1.0 release

2016-11-21 23:20 UTC, tboerger approved these changes

2016-11-24 07:36 UTC, lunny commented
This maybe needs rebase and resolved the conflicts.

2016-11-24 08:26 UTC, Bwko commented
@lunny I can't see the conflict. Only the conflicting file but not which line

2016-11-24 08:31 UTC, lunny commented
You can handle the conflict before merging. You have to handle it on command line and your local.

2016-11-24 10:06 UTC, Bwko commented
Fixed

2016-11-24 14:04 UTC, lunny commented
Great, this PR will be delayed until 1.0 released.

2016-12-24 01:48 UTC, lunny commented
Please resolve the conflict and we will merge it.

2016-12-24 14:41 UTC, lunny commented
LGTM work

2016-12-24 14:41 UTC, merged