Make branch deletion URL more like GitHub's, fixes #1397
go-gitea/gitea pull request #1994
Opened 2017-06-17 11:06 UTC by lafriks

Also fixes broken branch deletion as MergeCommitID is not in HeadBranch so it allways was giving error message that branch has new commits and it can not be deleted.

2017-06-17 11:57 UTC, lunny commented
Maybe add an integration test since merge test is ready.

2017-06-17 16:25 UTC, ethantkoenig requested changes
Will this URL change prevent us from being able to support deleting arbitrary branches (even those not associated with any PR) in the future?

2017-06-17 16:25 UTC, ethantkoenig commented on routers/repo/pull.go
> +	if !gitRepo.IsBranchExist(pr.HeadBranch) || pr.HeadBranch == "master" {
Should it be `ctx.Repo.Repository.DefaultBranch` instead of `"master"`?

2017-06-17 16:25 UTC, ethantkoenig commented on routers/repo/pull.go
> +		ctx.Handle(404, "CleanUpPullRequest", nil)
403 seems better than 404 here (although I'm no expert, could be wrong).

2017-06-18 00:33 UTC, lunny commented on routers/repo/pull.go
> +		ctx.Handle(404, "CleanUpPullRequest", nil)
No, 404 is better.

2017-06-18 19:02 UTC, lafriks commented
Changed to checking for default repository branch name instead of "master"

2017-06-18 19:04 UTC, lafriks commented
This URL meant to be used only for deleting PR branch and does very specific checks and functionality. For branch deletion from other places it would be better to create new URL with new handler

2017-06-19 01:17 UTC, lunny commented
When I try to delete the merged pull branch, it shows `lunny/test2 cannot be deleted because it has new commits after merging.`

2017-06-19 06:19 UTC, lafriks commented
@lunny did you do it for fork? Does it works on try gitea? If both answers are yes, than you are hitting this bug #2007

2017-06-19 08:35 UTC, bkcsoft commented on routers/repo/pull.go
> +	if !gitRepo.IsBranchExist(pr.HeadBranch) || pr.HeadBranch == "master" {
Yes

2017-06-19 08:35 UTC, bkcsoft commented on routers/repo/pull.go
> +		ctx.Handle(404, "CleanUpPullRequest", nil)
If you can see the PR you should get a 403, otherwise 404

2017-06-19 08:48 UTC, lafriks commented on routers/repo/pull.go
> +		ctx.Handle(404, "CleanUpPullRequest", nil)
I think it will check for PR view rights in routes.go already

2017-06-19 09:27 UTC, bkcsoft commented on routers/repo/pull.go
> +		ctx.Handle(404, "CleanUpPullRequest", nil)
Then 403 is correct

2017-06-19 23:03 UTC, lafriks commented
Added integration test does fail without #2007 applied, so it covers both my PR :)

2017-06-20 01:19 UTC, lunny commented
The close comment and deletion comment is not shown but I think that should be another issue. So I give this LGTM.

2017-06-20 01:22 UTC, lunny commented
Another thinking: if pull branch is a protected branch?

2017-06-20 03:21 UTC, ethantkoenig requested changes

2017-06-20 03:21 UTC, ethantkoenig commented on integrations/pull_merge_test.go
> +	json.Unmarshal(resp.Body, respJSON)
Unchecked error, I'd recommend using the `DecodeJSON(..)` helper function here:

```
DecodeJSON(t, resp, respJSON)
```

2017-06-20 07:10 UTC, lafriks commented
@ethantkoenig fixed

2017-06-20 08:08 UTC, lafriks commented
@lunny added checks to not allow deleting protected branches

2017-06-20 08:09 UTC, lafriks commented
Missing comments are bug introduced in 255adc40ae1e0a03547326f143f685be41fa591f and needs to be fixed in other PR

2017-06-20 19:02 UTC, lafriks commented
@ethantkoenig need your approval

2017-06-20 19:52 UTC, ethantkoenig commented
@lafriks Still need to address https://github.com/go-gitea/gitea/pull/1994#discussion_r122571873

2017-06-20 20:20 UTC, lafriks commented
@ethantkoenig ok, done

2017-06-20 20:21 UTC, ethantkoenig approved these changes

2017-06-20 20:21 UTC, ethantkoenig commented
LGTM

2017-06-20 21:28 UTC, lafriks commented
@lunny @ethantkoenig I added additional check so that code would not panic if forked repository has been deleted.
There are some other places where it does panic but for them I will create new PR

2017-06-21 01:00 UTC, merged