Fix sender of issue notifications
go-gitea/gitea pull request #2
Opened 2016-11-02 17:24 UTC by strk

It is the FROM field in mailer configuration that needs be used,
not the USER field, which is for authentication.

Migrated from https://github.com/gogits/gogs/pull/3616

2016-11-02 18:04 UTC, tboerger commented
LGTM, but needs to be rebased.

2016-11-02 19:35 UTC, strk commented
Sorry, I'm confused, should this target develop or master branch ?

2016-11-02 19:36 UTC, bkcsoft commented
according to consensus in Gitter, it should go into `master` :slightly_smiling_face:

2016-11-02 19:39 UTC, joubertredrat commented
@bkcsoft  :scream: is possible to change target or only with new PR?

2016-11-02 19:50 UTC, bkcsoft commented
The others that has been merged targeted develop, so leave it at that :)

2016-11-02 20:07 UTC, tboerger requested changes

2016-11-02 20:07 UTC, tboerger commented on .gopmfile
> +strk.kbt.io/projects/go/libravatar = commit:5eed7bf
Not related to this pr

2016-11-02 20:10 UTC, strk commented
It was a bogus base (master) -- now based on develop branch, should be fine.

2016-11-02 20:17 UTC, tboerger approved these changes

2016-11-02 20:17 UTC, tboerger commented
LGTM

2016-11-02 21:36 UTC, andreynering commented
Please reopen this against master

2016-11-03 08:00 UTC, lunny commented
LGTM

2016-11-03 08:06 UTC, merged