fix push mirrors URL are no longer displayed on the UI
go-gitea/gitea pull request #20011
Opened 2022-06-17 22:05 UTC by mohsek

I saw after the changes on this PR https://github.com/go-gitea/gitea/pull/18649   the push mirrors URL are no longer displayed on the UI 

![image](https://user-images.githubusercontent.com/98962410/174406724-948d12c3-f866-4c17-a726-26ef4697b0e5.png)

2022-06-17 22:06 UTC, Gusted approved these changes

2022-06-17 22:13 UTC, zeripath commented
this doesn't make sense.

2022-06-17 22:16 UTC, Gusted commented
> this doesn't make sense.

Eh, seems like the condition should be removed as a whole.

2022-06-17 22:19 UTC, zeripath commented on modules/templates/helper.go
>  	}
The correct solution is to remove this entire test. 

```suggestion
```

Your solution will break pull mirrors

2022-06-17 22:20 UTC, zeripath requested changes
As it current stands flipping the test from `!m.IsMirror` to `m.IsMirror` will break pull mirrors.

The correct solution is to remove this test on IsMirror as it is incorrect.

2022-06-17 22:21 UTC, zeripath approved these changes

2022-06-17 22:22 UTC, delvh approved these changes

2022-06-18 03:30 UTC, lunny commented
make L-G-T-M work

2022-06-18 03:30 UTC, merged