Always return valid go-get meta, even if unauthorized
go-gitea/gitea pull request #2010
Opened 2017-06-19 09:18 UTC by bkcsoft

(Not leaking information, returns valid metadata for ALL requests... even broken ones...)

This is required because `go get` doesn't know about `.netrc`

2017-06-19 13:17 UTC, tboerger commented
LGTM

2017-06-19 13:24 UTC, lafriks requested changes

2017-06-19 13:24 UTC, lafriks commented on modules/context/context.go
> +			if err != nil {
It will leak users/organizations, it should skip searching for repository by name if there is error and never return 500 or any other error

2017-06-21 14:10 UTC, bkcsoft commented on modules/context/context.go
> +			if err != nil {
Seems to be fetching the default branch-name, so `if err { branchName = "master" }` ?

2017-06-21 15:10 UTC, lunny commented
Just return even if repo is not exist.

2017-06-21 15:30 UTC, lafriks commented on modules/context/context.go
> +			if err != nil {
I would say something like that:
```go
			owner, err := models.GetUserByName(ownerName)
			if err == nil {
				repo, err := models.GetRepositoryByName(owner.ID, repoName)
				if err == nil && len(repo.DefaultBranch) > 0 {
					branchName = repo.DefaultBranch
				}
			}
```

2017-06-23 01:27 UTC, lunny requested changes

2017-06-23 01:27 UTC, lunny commented on modules/context/context.go
> +			if err != nil {
Maybe just return meta tag with no `GetUserByName` and `GetRepositoryByName`.

2017-06-25 18:40 UTC, bkcsoft commented on modules/context/context.go
> +			if err != nil {
Done :)

2017-06-25 18:42 UTC, bkcsoft commented
Now it should be done :) @lunny

2017-06-25 18:49 UTC, lafriks commented
LGTM

2017-06-26 01:06 UTC, lunny approved these changes

2017-06-26 01:06 UTC, merged

2017-06-26 20:51 UTC, bkcsoft commented
@lunny that would break default branches 🙄

2017-06-26 23:46 UTC, lunny commented
Where?

2017-06-27 18:47 UTC, bkcsoft commented
@lunny 
> Maybe just return meta tag with no GetUserByName and GetRepositoryByName.

☝️ that 😄