revert #2001 and fix issue comments hidden
go-gitea/gitea pull request #2016
Opened 2017-06-20 08:10 UTC by lunny

@ethantkoenig

2017-06-20 09:07 UTC, lafriks commented
LGTM

2017-06-20 10:18 UTC, lafriks commented on models/issue_comment.go
> +	if opts.Type > -1 {
Probably it would be better to use `opts.Type != CommentTypeUnknown` in this case

2017-06-20 11:22 UTC, lunny commented on models/issue_comment.go
> +	if opts.Type > -1 {
done.

2017-06-20 13:44 UTC, ethantkoenig requested changes

2017-06-20 13:44 UTC, ethantkoenig commented on models/issue_comment.go
> +		cond = cond.And(builder.Eq{"issue.id": opts.IssueID})
Could use `"comment.issue_id"` instead of `"issue.id"`, so that we can avoid joining if `opts.RepoID` is 0.

2017-06-20 13:44 UTC, ethantkoenig commented on models/issue_comment.go
> +// FindCommentsOptions describes the condtions to Find comments
condtions -> conditions

2017-06-20 13:44 UTC, ethantkoenig commented on models/issue_comment.go
> +	return comments, e.Join("INNER", "issue", "issue.id = comment.issue_id").
The join is only necessary if `opts.RepoID > 0`, it would be preferable to only join when we have to.

2017-06-20 15:04 UTC, lunny commented on models/issue_comment.go
> +		cond = cond.And(builder.Eq{"issue.id": opts.IssueID})
done.

2017-06-20 15:04 UTC, lunny commented on models/issue_comment.go
> +	return comments, e.Join("INNER", "issue", "issue.id = comment.issue_id").
done.

2017-06-20 19:51 UTC, ethantkoenig approved these changes

2017-06-20 19:52 UTC, ethantkoenig commented
LGTM

2017-06-21 01:00 UTC, lunny commented
make L-G-T-M work

2017-06-21 01:00 UTC, merged