Added email notification option
go-gitea/gitea pull request #20179
Opened 2022-06-30 07:37 UTC by tyroneyeh

Closes 20149

Sometimes users want to receive email notifications of messages they create or reply to,
Added an option to personal preferences to allow users to choose

2022-07-04 00:22 UTC, Gusted requested changes
Translation isn't working. Otherwise seems fine.

2022-07-04 00:22 UTC, Gusted commented on options/locale/locale_en-US.ini
> +email_notifications.andyourown = And Your Own Email Notifications
```suggestion
settings.email_notifications.andyourown = And Your Own Email Notifications
```

2022-07-04 00:22 UTC, Gusted commented on templates/user/settings/account.tmpl
> +										<div data-value="andyourown" class="{{if eq .EmailNotificationsPreference "andyourown"}}active selected {{end}}item">{{$.i18n.Tr "settings.email_notifications.andyourown"}}</div>
```suggestion
										<div data-value="andyourown" class="{{if eq .EmailNotificationsPreference "andyourown"}}active selected {{end}}item">{{$.locale.Tr "settings.email_notifications.andyourown"}}</div>
```

2022-07-04 07:13 UTC, tyroneyeh commented
> Translation isn't working. Otherwise seems fine.

Sorry, I came from the 1.16 merge and didn't notice the difference, thanks

2022-07-04 17:24 UTC, Gusted approved these changes

2022-07-09 01:45 UTC, Gusted approved these changes
LGTM code-wise

2022-07-28 04:27 UTC, wxiaoguang approved these changes

2022-07-28 08:29 UTC, wxiaoguang commented
bot

2022-07-28 08:30 UTC, merged

2022-07-28 10:57 UTC, tyroneyeh commented
Strange, locale_en-US.ini has been added, why not display the correct text?
![353](https://user-images.githubusercontent.com/1255041/181489373-21a1bf3b-feea-439e-9ebc-768fe338e398.png)

2022-07-28 11:49 UTC, wxiaoguang commented
The i18n was put to the incorrect place.

The fix:
* https://github.com/go-gitea/gitea/pull/20518