not request login for view public org members
go-gitea/gitea pull request #20330
Opened 2022-07-12 10:36 UTC by a1012112796

fix #7501

Signed-off-by: a1012112796 <1012112796@qq.com>

2022-07-12 21:24 UTC, Gusted approved these changes

2022-07-13 07:14 UTC, wxiaoguang approved these changes, later dismissed

2022-07-13 17:33 UTC, zeripath commented on routers/web/web.go
> +		}, context.OrgAssignment())
OrgAssignment and HandleOrgAssignment don't appear to be correctly handling visibility in here.

2022-07-13 17:33 UTC, zeripath requested changes
This PR reveals the existence of private organisations as it stands.

2022-07-13 19:24 UTC, zeripath commented
```patch
diff --git a/modules/context/org.go b/modules/context/org.go
index 9f4ce485e..fd808403d 100644
--- a/modules/context/org.go
+++ b/modules/context/org.go
@@ -12,6 +12,7 @@ import (
 	"code.gitea.io/gitea/models/perm"
 	user_model "code.gitea.io/gitea/models/user"
 	"code.gitea.io/gitea/modules/setting"
+	"code.gitea.io/gitea/modules/structs"
 )
 
 // Organization contains organization context
@@ -69,6 +70,18 @@ func HandleOrgAssignment(ctx *Context, args ...bool) {
 		return
 	}
 	org := ctx.Org.Organization
+
+	// Handle Visibility
+	if org.Visibility != structs.VisibleTypePublic && !ctx.IsSigned {
+		// We must be signed in to see limited or private organizations
+		ctx.NotFound("OrgAssignment", err)
+		return
+	} else if org.Visibility == structs.VisibleTypePrivate {
+		requireMember = true
+	} else if ctx.IsSigned && ctx.Doer.IsRestricted {
+		requireMember = true
+	}
+
 	ctx.ContextUser = org.AsUser()
 	ctx.Data["Org"] = org
 
diff --git a/routers/web/org/home.go b/routers/web/org/home.go
index d565a0c24..63243a391 100644
--- a/routers/web/org/home.go
+++ b/routers/web/org/home.go
@@ -39,11 +39,6 @@ func Home(ctx *context.Context) {
 
 	org := ctx.Org.Organization
 
-	if !organization.HasOrgOrUserVisible(ctx, org.AsUser(), ctx.Doer) {
-		ctx.NotFound("HasOrgOrUserVisible", nil)
-		return
-	}
-
 	ctx.Data["PageIsUserProfile"] = true
 	ctx.Data["Title"] = org.DisplayName()
 	if len(org.Description) != 0 {

```

I think this is required.

2022-07-14 00:19 UTC, wxiaoguang commented on routers/web/web.go
> +		}, context.OrgAssignment())
Good catch, I only checked that there is `IsOrgMember` in `org.Members` before.

Maybe it's worth to add a test for it to make sure the visibility handling is correct.

2022-07-14 12:35 UTC, zeripath approved these changes

2022-07-14 12:44 UTC, wxiaoguang approved these changes

2022-07-15 14:20 UTC, zeripath commented
Make lgtm work

2022-07-15 14:21 UTC, merged