Allow non-semver packages in the Conan package registry
go-gitea/gitea pull request #20412
Opened 2022-07-19 18:48 UTC by algernon

A lot of existing packages do not conform to SemVer, yet, they should be allowed in the Conan package registry as-is. To achieve this, remove the SemVer check from `NewRecipeReference`, and replace it with a simple empty string check.

A unit test with a non-semver version is also included.

Fixes #20405.

2022-07-19 18:54 UTC, 6543 commented on modules/packages/conan/reference.go
> +	if (version == "") {
```suggestion
	if version == "" {
```

2022-07-20 08:47 UTC, lafriks approved these changes

2022-07-20 14:46 UTC, KN4CK3R commented on modules/packages/conan/reference.go
> +	if version == "" {
```suggestion
	if strings.TrimSpace(version) == "" {
```
I would disallow whitespaces.

2022-07-20 14:59 UTC, 6543 approved these changes

2022-07-21 11:03 UTC, 6543 requested changes

2022-07-21 11:03 UTC, 6543 commented on modules/packages/conan/reference.go
> +	if strings.TrimSpace(version) == "" {
We should use trimed value

2022-07-21 18:29 UTC, 6543 approved these changes

2022-07-22 21:53 UTC, zeripath commented
make lgtm work

2022-07-22 21:54 UTC, merged

2022-07-24 18:50 UTC, 6543 commented
please send backport

2022-07-28 16:26 UTC, 6543 commented
-> #20523