Changelog v1.17.0
go-gitea/gitea pull request #20541
Opened 2022-07-29 17:29 UTC by 6543

as title

2022-07-29 17:56 UTC, KN4CK3R approved these changes

2022-07-29 19:58 UTC, noerw approved these changes

2022-07-29 20:01 UTC, jolheiser requested changes
Just blocking until ready. 🙂

2022-07-30 05:30 UTC, lunny commented
Could we wait for #20548 and #20549 ? Some users need that for v1.17.

2022-07-30 16:31 UTC, Gusted commented
> Could we wait for #20548 and #20549 ? Some users need that for v1.17.

Backporting features on the last moment? Looks risky for me, no time to iron out bugs etc.

2022-07-30 16:38 UTC, 6543 commented
we did reject a lot of "can we have this in v1.17" ... at that rate we just could v1.18 ... - I'm also against it

2022-07-30 16:50 UTC, 6543 commented on CHANGELOG.md
> +## [1.17.0](https://github.com/go-gitea/gitea/releases/tag/v1.17.0) - 2022-07-29
```suggestion
## [1.17.0](https://github.com/go-gitea/gitea/releases/tag/v1.17.0) - 2022-07-30
```

2022-07-30 17:06 UTC, 6543 commented on CHANGELOG.md
> +  * Ensure that all unmerged files are merged when conflict checking (#20528) (#20536)
```suggestion
  * WebAuthn CredentialID field needs to be increased in size (#20530) (#20555)
  * Ensure that all unmerged files are merged when conflict checking (#20528) (#20536)
```

2022-07-30 17:09 UTC, jolheiser approved these changes

2022-07-30 19:04 UTC, noerw approved these changes

2022-07-30 19:08 UTC, merged