Admin grammar fixes and improvements
go-gitea/gitea pull request #2056
Opened 2017-06-24 23:32 UTC by geek1011

Admin grammar fixes and improvements.

2017-06-24 23:33 UTC, geek1011 commented on options/locale/locale_en-US.ini
> +users.allow_create_organization = Allowed to create organizations
The above ones are checkboxes on the user edit page, so no need to say `This account`. This is why I changed these lines.

2017-06-27 21:30 UTC, cez81 commented on options/locale/locale_en-US.ini
> +users.still_own_repo = This user still owns one or more repositories. These repositories need to be deleted or transfered first.
transferred

2017-06-27 21:30 UTC, geek1011 commented on options/locale/locale_en-US.ini
> +users.still_own_repo = This user still owns one or more repositories. These repositories need to be deleted or transfered first.
Thanks

2017-06-27 21:32 UTC, cez81 commented
LGTM

2017-06-28 17:16 UTC, bkcsoft reviewed
I know it's just a grammar-check, but we might as well touch some of them up while we're at it 😉

2017-06-28 17:16 UTC, bkcsoft commented on options/locale/locale_en-US.ini
> +dashboard.resync_all_sshkeys = Rewrite '.ssh/authorized_keys' file (for Gitea SSH keys). Do not use this if you are using the built-in SSH server.
This should be `Disabled if you are using the built-in SSH server.` no? As in it won't do anything...

2017-06-28 17:16 UTC, bkcsoft commented on options/locale/locale_en-US.ini
> +dashboard.resync_all_sshkeys_success = All Gitea public keys have been rewritten.
`All public keys controlled by Gitea [...]`

2017-06-28 17:16 UTC, bkcsoft commented on options/locale/locale_en-US.ini
> +users.still_has_org = This user is still is a member of one or more organizations. This user needs to leave or delete them first.
Is this true? Is it not only if you're an Owner of an Org?

2017-06-28 17:16 UTC, bkcsoft commented on options/locale/locale_en-US.ini
> +auths.bind_password_helper = Warning: This password is stored in plain text. Do not use a high privilege account.
Maybe `Only use a read-only account` ?

2017-07-07 14:01 UTC, andreynering commented
LGTM

2017-07-07 19:21 UTC, lafriks commented
Please do not merge this before 1.2.0 is released as this will break already translated strings

2017-07-07 19:41 UTC, bkcsoft requested changes
@lafriks You can do empty "request changes" to "stall" PRs ;)

2017-07-12 09:34 UTC, lafriks commented
@geek1011 rebase

2017-08-28 01:31 UTC, lunny commented
Any update? Or we should close this one?

2017-08-28 13:37 UTC, geek1011 commented
Sorry, I have been quite busy for the last few weeks. I will update it soon.

2017-09-16 19:38 UTC, geek1011 commented
@lunny @bkcsoft 

Also, sorry for the delay, I have been really busy recently.

2017-10-18 21:33 UTC, lafriks commented
@bkcsoft need your approval

2017-10-19 05:04 UTC, lunny commented
@lafriks CI failed

2017-10-20 01:51 UTC, lunny commented
need @bkcsoft approval

2017-10-21 12:58 UTC, bkcsoft approved these changes

2017-10-21 13:15 UTC, lafriks commented
Make LG-TM work again

2017-10-21 13:30 UTC, merged