Check for valid renamed usernames
go-gitea/gitea pull request #2077
Opened 2017-06-28 13:56 UTC by ethantkoenig

Fixes #2066.

2017-06-28 13:59 UTC, lafriks commented
LGTM

2017-06-28 13:59 UTC, lafriks commented
May be add integration test?

2017-06-28 14:40 UTC, lunny commented
LGTM otherwise @lafriks 's comment.

2017-06-28 18:05 UTC, ethantkoenig commented
@lafriks @lunny Integration test added :smile:

2017-06-28 18:42 UTC, lafriks commented
Awsome 👍

2017-06-28 19:28 UTC, bkcsoft requested changes

2017-06-28 19:28 UTC, bkcsoft commented on integrations/user_test.go
> +		"name":  "%2f*", // not valid
Could you add more tests here? The original issue lists a bunch of cases that we should guard against 🤔 

```go
tests := []string{ ... }
for test := range tests {
  t.Logf("testing %q", test)
  req = NewRequest...("POST" ...)
  [...]
  models.AssertNot...
}
```
( ☝️ Table-driven testing 🙂 https://blog.golang.org/subtests )

2017-06-28 19:52 UTC, lafriks commented on integrations/user_test.go
> +		"name":  "%2f*", // not valid
It would be also nice to have valid user name change test

2017-06-28 23:25 UTC, ethantkoenig commented on integrations/user_test.go
> +		"name":  "%2f*", // not valid
Added all invalid cases from #2066, and a reserved username test, and a valid username test.

2017-06-29 15:30 UTC, bkcsoft commented on integrations/user_test.go
> +		)
now you have 3 identical loops, have them be a common function like so `testUpdateUser(t *testing.T, username, email string, code http.StatusCode)` 🙂

2017-06-29 15:58 UTC, ethantkoenig commented on integrations/user_test.go
> +		)
@bkcsoft They're not identical. A lot of the setup code (e.g. getting the CSRF token) is shared, but once you make the `POST /user/settings` request, they have little in common (different status codes, may or may not have to follow a redirect, may or may not check for whether rename succeeded, have to check for different error messages).

The boilerplate setup code is also shared with tests from other files, so IMO the best solution is to add helper functions for things like getting a CSRF token.

2017-06-29 18:09 UTC, lafriks commented
Please also add test case for username with space so that #2061 can be also closed

2017-06-29 21:18 UTC, ethantkoenig commented
@lafriks Done

2017-06-30 00:46 UTC, lunny commented
need @bkcsoft approval.

2017-06-30 16:49 UTC, lafriks commented on modules/auth/user_form.go
> +	Name             string `binding:"OmitEmpty;AlphaDashDot;MaxSize(35)"`
I think it is also needs to be `Required`

2017-06-30 16:53 UTC, lafriks commented
Related https://github.com/gogits/gogs/commit/e6dbfd918c8d68c29c01bf2617321b037393ada1

2017-07-01 12:21 UTC, lafriks commented
@bkcsoft need your approval

2017-07-01 18:19 UTC, bkcsoft approved these changes

2017-07-01 19:48 UTC, merged