Added attachments to the releases API
go-gitea/gitea pull request #2084
Opened 2017-06-29 21:54 UTC by stefan-lacatus

Very simple initial fix for #711. 
It's also my first interaction with GO so i'm sorry for stupid mistakes.

This only adds attachments for `/repos/:owner/:repo/releases[/:id]`.

If the API for github must be followed, where attachments are "assets", with a lot of additional metadata then this PR can be skipped, but for my limited usecase this is all I need.

2017-06-29 22:22 UTC, ethantkoenig requested changes

2017-06-29 22:22 UTC, ethantkoenig commented on models/release.go
> +		GetReleaseAttachments(r)
The `error` returned by `GetReleaseAttachments(r)` is unchecked.

2017-06-29 22:37 UTC, lafriks requested changes
I think we should follow GitHub api as close as possible so it would be better to name features same as GitHub so in this case as Assets.

Also do not change anything under vendor directory directly. If changes need to be done in sdk first you need to submit PR in https://github.com/go-gitea/go-sdk

Aslo this would need test

2017-06-30 04:43 UTC, stefan-lacatus commented
Understood. I'll separate this into 2 PRs for the appropriate repos. 
I'll also rename the json keys to match the github ones as much as possible. 

Thanks for the tips

2017-06-30 07:37 UTC, stefan-lacatus commented
Fixed the issue mentioned by @ethantkoenig

* Get releases `GET /repos/:owner/:repo/releases[/:id]` - now includes assets
* List assets: `GET /repos/:owner/:repo/releases/:id/assets`
* Get single asset: `GET /repos/:owner/:repo/releases/assets/:id`

@tboerger : can you give me some quick tips about adding tests? I'm a bit in the dark there.

2017-06-30 08:30 UTC, lafriks requested changes

2017-06-30 10:21 UTC, stefan-lacatus commented on models/attachment.go
> +	fileSize, err := a.GetSize()
Good point, thanks

2017-06-30 15:18 UTC, lafriks commented
Please rebase on master

2017-07-05 07:09 UTC, lafriks requested changes

2017-07-05 07:09 UTC, lafriks commented on models/release.go
> +	if !opts.IncludeDrafts {
There should be check for `IncludePrereleases`

2017-08-23 21:36 UTC, bkcsoft requested changes
Error Checking and a question

2017-08-23 21:36 UTC, bkcsoft commented on models/attachment.go
> +	log.Warn("Error getting the file size for attachment %s. ", a.UUID, err)
This should if in a `if err != nil` check.

I'd do this:
```go
fileSize, err := a.GetSize()
if err != nil {
  log.Warn(...)
}
// Effectively doing `Size = 0` on errors.
apiAttachment.Size = fileSize

return apiAttachment

2017-08-23 21:36 UTC, bkcsoft commented on routers/api/v1/repo/release.go
> +	ctx.JSON(200, releases[0].APIFormat())
e we sure that `[0]` is the latest one? (I don't see anything about sorting in the PR 🙂 )

2017-08-25 20:21 UTC, stefan-lacatus commented
I'll revisit this next week, as i've also identified some bugs internally.

2017-11-21 00:59 UTC, lunny commented
any update?

2017-12-03 06:08 UTC, stefan-lacatus commented
I'll redo on top of the master

2017-12-03 06:08 UTC, closed without merging