Add make command update-translations for update translations from crodwin
go-gitea/gitea pull request #2097
Opened 2017-07-02 05:13 UTC by lunny

Also I have sent a PR to ini package, see https://github.com/go-ini/ini/pull/110. After these two PR merged, it's easy to update the translations to local and create a translation PR is easy too. @lafriks

2017-07-02 20:51 UTC, lafriks requested changes
This code did not work for me as tar can not extract files from zip archives.
How about such code (it does work even without changes in go-ini):
```
.PHONY: update-translations
update-translations:
	mkdir -p ./translations
	cd ./translations && curl -L https://crowdin.com/download/project/gitea.zip > gitea.zip && unzip gitea.zip
	rm ./translations/gitea.zip
	$(SED_INPLACE) -e 's/="/=/g' -e 's/"$$//g' ./translations/*.ini
	$(SED_INPLACE) -e 's/\\"/"/g' ./translations/*.ini
	mv ./translations/*.ini ./options/locale/
	rmdir ./translations
```

Also changed from wget to curl as curl is also used in other places in Makefile

2017-07-02 21:01 UTC, lafriks commented
Also crowdin zip file needs to be regenerated as in Swedish translation there was error that did not allow gitea to start (I fixed it but zip file still contains old broken translation)

2017-07-03 00:56 UTC, lunny commented
@lafriks before download, we have to click the `build the project` on the UI. I haven't find any HTTP method except API key to do that.

2017-07-03 01:10 UTC, lunny commented
@lafriks done.

2017-07-03 08:44 UTC, lafriks approved these changes

2017-07-03 08:46 UTC, lafriks commented
Just thought that it could be more optimized by piping curl output directly to unzip and than `rm gitea.zip` is also not needed:
```
	cd ./translations && curl -L https://crowdin.com/download/project/gitea.zip | unzip
```
but otherwise LGTM

2017-07-03 11:05 UTC, lunny commented
@lafriks It didn't work on macOS

2017-07-03 11:17 UTC, lafriks commented
oh well, if it is not working on macos than just leave how it is :)

2017-07-03 13:32 UTC, ethantkoenig commented
LGTM

2017-07-03 13:37 UTC, merged