Support external renderers to PDF (#17635)
go-gitea/gitea pull request #21098
Opened 2022-09-06 21:46 UTC by PlushBeaver

For some formats, conversion to HTML is unavailable or lossy, while quality conversion of printing to PDF is available.
Examples include Office PPTX slides and TeX papers.

Add new option value markup.XXX.RENDER_CONTENT_MODE = "pdf".
It requires markup.XXX.NEED_POSTPROCESS = false.
In this mode, external renderer is only invoked for the standalone page.
Embedded rendering outputs a PDF.js widget with a link to that page.

The first commit is a required fix for this PR, although not limited to it.

2022-09-07 16:45 UTC, techknowlogick requested changes
Just adding a blocking comment, as this touches sensitive areas in regards to security, and so just ensuring that gets an extra focus in any review.

2022-09-08 03:09 UTC, wxiaoguang commented
> Just adding a blocking comment, as this touches sensitive areas in regards to security, and so just ensuring that gets an extra focus in any review.

Maybe consider with this one together.
* https://github.com/go-gitea/gitea/pull/20180

2022-11-01 02:17 UTC, lunny commented
Should fix #17635

2025-10-23 06:25 UTC, wxiaoguang commented
Implemented by  Make external iframe render work #35730

2025-10-23 06:25 UTC, closed without merging