Fix username rendering bug
go-gitea/gitea pull request #2122
Opened 2017-07-07 18:54 UTC by ethantkoenig

Fixes #1629.

Don't sanitize user's full names in the database. Since `user.FullName` and `user.DisplayName()` are strings, they are automatically already sanitized by the templating engine. If we sanitize the values stored in the database, users' full name end up being up sanitized twice.

I'm planning to add an integration test soon.

2017-07-07 19:32 UTC, lafriks requested changes
This needs migration to unsanitize already broken user full names

2017-07-07 19:35 UTC, lafriks commented
Integration test for this would be nice

2017-07-07 19:53 UTC, bkcsoft commented
@lafriks No migrations, `AfterSet` is ran on Read operations :)

2017-07-07 20:09 UTC, ethantkoenig commented
@bkcsoft True, but I also made changes to `updateUser(..)`.

@lafriks It's not always possible to reconstruct an unsanitized string from a sanitized one. For instance, if a sanitized full name is "a \&amp; b", the unsanitized version could be "a & b" or "a \&amp; b".

Additionally, we don't currently have a function unsanitizing, and IMO writing one seems like more trouble than it would be worth. I'm guessing only a small number of actual users have been affected by this, and they can just changes their names manually.

2017-07-07 20:34 UTC, bkcsoft commented
@ethantkoenig if it's sanitized `&amp;` would always be `&`, otherwise it would say `&amp;amp;` 😄

2017-07-07 21:07 UTC, ethantkoenig commented
@bkcsoft Both `markdown.Sanitize("&")` and `markdown.Sanitize("&amp;")` give me `"&amp;"`. So even though `"&amp;"` would ideally be sanitized as `"&amp;amp;"`, for our purposes we can't unsanitize without making assumptions

2017-07-08 11:30 UTC, lafriks commented
Even if &amp; is sanitized as &amp; I don't see how someone would have such symbols in full name so in all cases it can be changed to just &

2017-07-08 11:37 UTC, lafriks commented
For migration golangs built in `html.UnescapeString` could be used

2017-07-09 12:16 UTC, ethantkoenig commented
@lafriks Migration added

2017-07-09 12:22 UTC, lafriks approved these changes

2017-07-12 03:37 UTC, pgaskin approved these changes

2017-07-12 09:57 UTC, lafriks commented
LGTM

2017-07-12 14:18 UTC, lunny commented
LGTM

2017-07-12 14:58 UTC, merged