Use POSIX complaint ! operator in find
go-gitea/gitea pull request #2132
Opened 2017-07-09 11:31 UTC by rsmarples

-not is a GNU extension and not all find(8) implementations
support it. It's just an alias for ! which is POSIX compliant.

Now gitea compiles on NetBSD at least.

2017-07-09 11:56 UTC, lafriks requested changes

2017-07-09 11:56 UTC, lafriks commented on vendor/code.gitea.io/git/Makefile
> +	find . -name "*.go" -type f ! -path "./vendor/*" ! -path "./benchmark/*" | xargs gofmt -s -w
Do not make changes to vendor directory. Create PR in github.com/go-gitea/git/ repository for this change

2017-07-09 19:27 UTC, bkcsoft commented
What @lafriks said, vendored files are changed upstream :) https://github.com/go-gitea/git/ in this case

2017-07-09 21:42 UTC, lafriks commented
@bkcsoft why did you close PR, there was also gitea Makefile changes that are ok here?

2017-07-09 23:16 UTC, lafriks approved these changes

2017-07-10 01:24 UTC, bkcsoft commented
Ooh, must've missed that one. Sorry 😅

2017-07-10 01:24 UTC, bkcsoft commented
LGTM

2017-07-10 01:33 UTC, lunny commented
LGTM

2017-07-10 01:48 UTC, merged