Fix repo API bug
go-gitea/gitea pull request #2133
Opened 2017-07-09 12:26 UTC by ethantkoenig

Don't require authentication for some `GET` endpoints (e.g. `GET /repos/:owner/:repo`, `GET /repos/:owner/:repo/issues`, ...) whose corresponding Github endpoints do not require authentication.

Also add integration tests for some of the affected endpoints.

2017-07-09 19:23 UTC, bkcsoft requested changes

2017-07-09 19:23 UTC, bkcsoft commented on routers/api/v1/api.go
>  							m.Combo("").Get(repo.ListIssueComments).Post(bind(api.CreateIssueCommentOption{}), repo.CreateIssueComment)
`.Post` should have `reqToken()` :)

2017-07-09 21:47 UTC, ethantkoenig commented on routers/api/v1/api.go
>  							m.Combo("").Get(repo.ListIssueComments).Post(bind(api.CreateIssueCommentOption{}), repo.CreateIssueComment)
@bkcsoft Good catch, fixed.

2017-07-10 01:26 UTC, bkcsoft approved these changes

2017-07-10 15:48 UTC, sapk commented
LGTM

2017-07-10 15:49 UTC, sapk approved these changes

2017-07-10 15:54 UTC, sapk commented on routers/api/v1/utils/utils.go
> +func UserID(ctx *context.APIContext) int64 {
I would prefer the definition of a method like models.UserAccessLevel(ctx.User, repo) that check :
` if ctx.User == nil { ...` an return models.AccessLevel(

2017-07-10 19:06 UTC, ethantkoenig commented
Rebased to resolve conflict

2017-07-12 01:17 UTC, bkcsoft commented
LGTM

2017-07-12 01:23 UTC, merged