Fix broken link to frontend guidelines in hacking guidelines
go-gitea/gitea pull request #21382
Opened 2022-10-08 22:08 UTC by yardenshoham

Previously the link was broken on the hugo-generated site

When clicking [here](https://docs.gitea.io/en-us/hacking-on-gitea/#working-on-js-and-css)
![image](https://user-images.githubusercontent.com/20454870/194729393-7f867ec4-828b-4cbb-9042-69e80b90f4d6.png)
you'd get
![image](https://user-images.githubusercontent.com/20454870/194729413-3506e969-a011-4227-8067-f377c826a674.png)

Signed-off-by: Yarden Shoham <hrsi88@gmail.com>

2022-10-09 01:16 UTC, techknowlogick approved these changes

2022-10-09 01:17 UTC, techknowlogick requested changes
CI fail related: https://drone.gitea.io/go-gitea/gitea/61282/5/2

2022-10-11 17:19 UTC, wxiaoguang approved these changes

2022-10-12 01:23 UTC, techknowlogick approved these changes

2022-10-12 01:23 UTC, merged