Add `fmt-check` to Drone pipeline
go-gitea/gitea pull request #21452
Opened 2022-10-14 10:46 UTC by yardenshoham

* Following #21437 I realized the build system isn't actually checking that the code is formatted

2022-10-14 12:20 UTC, silverwind commented
Instead of adding another drone step, just add it to `checks-backend` as a dependency:

https://github.com/go-gitea/gitea/blob/9dc264a2eebbd30bbff483c26bf27f0406677f77/Makefile#L337

2022-10-14 12:26 UTC, silverwind approved these changes

2022-10-14 13:42 UTC, lunny approved these changes

2022-10-14 14:18 UTC, silverwind commented
I think we also need to add the `fmt` dependency to `fmt-check`, otherwise it will never see a diff.

2022-10-14 14:19 UTC, silverwind requested changes
I think we also need to add `fmt` to the dependencies of `fmt-check`, otherwise it will never see a diff.

2022-10-14 15:10 UTC, yardenshoham commented
Hmmm, I see, perhaps having a different way to handle `templates` formatting is not the best way to go. Simply having `fmt` being called during `fmt-check` drastically changes its behavior. Wrong Go formatting won't be detected in Drone at all. The best thing to do would be to have `gitea-fmt` include template formatting.

2022-10-14 15:17 UTC, silverwind commented
I'm not sure what you're getting at, but we use the same strategy already for other things like `tidy-check` which has the `tidy` dependency. When running `tidy-check`, make will just trigger the `tidy` target before it, nur "during" it.

So I think having `fmt-check: fmt` on line 315 is totally fine.

2022-10-14 15:23 UTC, yardenshoham commented
Suppose I commit a changeset with wrongly formatted Go code and correctly formatted templates, `fmt` runs, formatting my Go code on the CI filesystem and then `fmt-check` runs (reporting no errors as `fmt` formatted my bad Go code and templates is formatted correctly) and exits with success.

2022-10-14 16:02 UTC, silverwind commented
Ah, I see `fmt-check` also run the go formatting again, I missed that. So the solution should then be remove the formatting call in `fmt-check`, so that only the diffing is left, then add the dependency which in turn will make it work just like `tidy-check` does while keeping DRY as well :)

2022-10-14 19:11 UTC, yardenshoham commented
How about we merge this as-is and open an issue on how to handle the actual `fmt-check` logic? This PR is only about adding `fmt-check` to CI

2022-10-14 19:47 UTC, silverwind commented
https://github.com/go-gitea/gitea/pull/21458 for the proposed enhancements. Fine with me to land this before.

2022-10-14 19:47 UTC, silverwind approved these changes

2022-10-15 09:24 UTC, silverwind commented
I suggest we just land https://github.com/go-gitea/gitea/pull/21458 instead of this. The order of targets is different here, so if this lands my PR would conflict.

2022-10-15 09:24 UTC, closed without merging