Change `commits-table` column width
go-gitea/gitea pull request #21564
Opened 2022-10-23 12:51 UTC by KN4CK3R

Fixes 21561

Before
![image](https://user-images.githubusercontent.com/20903656/197388658-0ea1d941-8bc7-4f10-b5db-4ece8602b13a.png)

After
![image](https://user-images.githubusercontent.com/20903656/197388665-78fb8421-105d-408d-84cf-a86b1cc61e2e.png)

2022-10-23 13:02 UTC, wxiaoguang approved these changes

2022-10-23 13:08 UTC, lunny approved these changes

2022-10-23 13:11 UTC, delvh approved these changes

2022-10-23 17:23 UTC, yardenshoham approved these changes

2022-10-23 22:32 UTC, lafriks approved these changes

2022-10-24 01:16 UTC, zeripath commented
You need to check this at all of the screen widths.

I suspect that this isn't going to work below 1000px width

2022-10-24 01:52 UTC, zeripath requested changes
Please double check at other screen widths in particular those below 1000px

2022-10-24 07:57 UTC, KN4CK3R commented
What do you mean by "isn't going to work". For the default width it looks good now. The wrapping can't work anymore if there is a small width:
![grafik](https://user-images.githubusercontent.com/1666336/197476054-e47eeadc-3a70-468d-a684-e88c0080b479.png)

2022-10-24 17:26 UTC, silverwind commented
Generally speaking, the `<table>` needs to be replaced with flexbox, and possible media queries to re-align fields below certain widths, but I guess this is better than before at least.

2022-10-25 16:57 UTC, zeripath approved these changes
OK I've checked on different window sizes and a few different languages and this still works.

2022-10-25 17:00 UTC, merged