storage/minio: Add options to disable signature and multipart for Minio Client
go-gitea/gitea pull request #21780
Opened 2022-11-11 15:40 UTC by stevefan1999-personal

2022-11-11 15:47 UTC, KN4CK3R commented
Are you able to test it? From looking at the minio code it may be enough to set `DisableMultipart`. But then **all** `storage.Save´ calls need to provide the size of the content. Otherwise the upload just fails:
https://github.com/minio/minio-go/blob/7aa4b0e0d1a9fdb4a99f50df715c21ec21d91753/api-put-object.go#L236
Currently we do not provide a correct size everywhere:
https://github.com/go-gitea/gitea/pull/15264/files

2022-11-11 15:49 UTC, stevefan1999-personal commented
@KN4CK3R that's exactly the reason I put this on draft

2022-11-11 16:31 UTC, stevefan1999-personal commented
I can confirm that by disabling signature in Minio client, Docker registry push works. I'm not sure about others though.

2023-03-22 04:48 UTC, stevefan1999-personal commented
I have ran this internally in my company for the last few month and it pretty much works. I'm looking to get it merged ASAP

2023-03-22 11:57 UTC, yardenshoham requested changes
Missing documentation changes, see #23166 for example

2023-05-23 20:34 UTC, techknowlogick approved these changes
Thanks for this PR! Could you resolve conflicts?

2023-05-23 20:34 UTC, techknowlogick commented on modules/storage/minio.go
> +
```suggestion
```

2023-05-24 15:17 UTC, yardenshoham commented
Still missing documentation

2023-05-24 16:02 UTC, wxiaoguang commented
I agree with  KN4CK3R  here. After reading the code again, I think the callers to `Save` should provide the size/length.

Especially the `doArchive` in `archiver.go`, if the `Save` reads all the stream content to memory, it would take GB memory?

2023-05-25 07:14 UTC, lunny commented
> I agree with KN4CK3R here. After reading the code again, I think the callers to `Save` should provide the size/length.
> 
> Especially the `doArchive` in `archiver.go`, if the `Save` reads all the stream content to memory, it would take GB memory?

I can confirm the size parameter was added to fix the memory problem.

2023-05-27 23:16 UTC, stevefan1999-personal commented
Gimme a moment, I was on a trip and didn't catch up so soon :)

2023-05-27 23:18 UTC, stevefan1999-personal commented
I have another idra about multi-part upload, and that is to use mmap. If we can lock the file beforehand, using a memory map will not only solve the potential DoS problem, but that it will also drastically speed it up. I will see if I can implement it soon

2023-08-22 06:13 UTC, lunny commented
Please resolve the conflicts

2023-08-22 06:25 UTC, yardenshoham commented
Still missing documentation

2023-08-22 06:36 UTC, lunny commented on modules/storage/minio.go
> +	if disableMultipart && size < 0 {
So how to handle when size == 0?

2023-08-22 07:25 UTC, stevefan1999-personal commented
Should we use https://pkg.go.dev/github.com/go-mmap/mmap#section-readme, and only use fully file load buffer as a fallback?

2025-06-18 19:18 UTC, lunny commented
> Hi there, do you have any news.
> 
> I am having the same issue. What were the remaining points to get this merged ?
> 
> I can do another PR if needed.

Please do another PR with documentation update. I will close this one.

2025-06-18 19:18 UTC, closed without merging