Set session and indexers' data files rel to AppDataPath
go-gitea/gitea pull request #2192
Opened 2017-07-21 17:42 UTC by dubeg

The setting AppDataPath now defaults to being relative to the working directory.
The session svc's PROVIDER_CONFIG now defaults to AppDataPath/data/sessions.
The issue indexer's IssuePath now defaults to AppDataPath/indexers/issues.bleves.

This change targets the following [issue](https://github.com/go-gitea/gitea/issues/2159).

2017-07-21 21:01 UTC, cez81 commented
Also fixes #1378

2017-07-21 21:07 UTC, lafriks requested changes

2017-07-21 21:07 UTC, lafriks commented on models/models.go
> +	setting.Indexer.IssuePath = sec.Key("ISSUE_INDEXER_PATH").MustString(path.Join(setting.AppDataPath, "indexers/issues.bleve"))
It needs to be checked if path is absolute (see https://github.com/go-gitea/gitea/blob/master/modules/setting/setting.go#L842)

2017-07-24 21:47 UTC, dubeg commented
I am not used to the pull request process. I amended my current commit to include the feedback. Is this the correct method?

I added a new setting variable containing the working directory named `AppWorkPath`. Maybe I should've named it `AppWorkDir`?

2017-07-24 22:12 UTC, lafriks commented
Now it is called differently in multiple places so either dir or path but do not mix (i would vote for path). You can add commits to your branch and they will show up here

2017-07-25 14:47 UTC, dubeg commented
Ok I changed to workPath the fn & vars that were named workDir. Anything else?

2017-07-26 19:39 UTC, lafriks approved these changes

2017-07-31 14:01 UTC, dubeg commented
I just added a minor change to the path ProviderConfig. I forgot to remove the "data" in "data/sessions" when joining with AppDataPath. 

By the way, I noticed we use `path.Join` as well as `filepath.Join`  almost equally. I checked their definition and they're a bit different. What's the logic here? Should we use one or the other, or does it not matter?

2017-08-17 16:41 UTC, lafriks commented
@dubeg Please fix formatting issues (see drone build that is failing). `path.Join` should be used for URL's, `filepath.Join` for file path :)

2017-10-31 06:07 UTC, lunny commented
@dubeg need rebase

2017-10-31 09:24 UTC, lunny commented
need rebase.

2017-10-31 19:27 UTC, dubeg commented
Sorry I've been terribly busy and also lazy since August. I'll try to fix the PR this week. As for filepath to path, I didn't know the purpose of each of them until Lafriks commented on them. I'll review what I did on that matter.

2017-11-01 00:42 UTC, lunny commented
@dubeg Or could you give the permission to let maintainers to help you to push to this PR.

2017-11-01 13:13 UTC, dubeg commented
@lunny How can I do that? 
Is it related to this checkbox?
![editmaintainers](https://user-images.githubusercontent.com/6020602/32276279-de878000-bee4-11e7-892f-9eaafbed2237.PNG)

2017-11-01 13:25 UTC, lunny commented
@dubeg yes

2017-11-01 16:24 UTC, dubeg commented
Well it's been checked for a well. If you want to finish to modify the PR, go ahead. Otherwise I'll work on it this weekend.

2017-11-03 03:33 UTC, lunny commented
@dubeg rebased and LGTM

2017-11-03 08:24 UTC, lafriks commented on modules/setting/setting.go
> +			logPath = path.Join(filepath.Dir(logPath), "xorm.log")
@lunny please change to `filepath` methods for files

2017-11-03 08:56 UTC, lafriks commented
LGTM

2017-11-03 08:56 UTC, merged