Make gitea work using cmd.exe again
go-gitea/gitea pull request #22073
Opened 2022-12-08 21:47 UTC by zeripath

Gitea will attempt to lookup its location using LookPath however, this fails on cmd.exe if gitea is in the current working directory.

exec.LookPath will return an exec.ErrDot error which we can test for and then simply using filepath.Abs(os.Args[0]) to absolute gitea against the current working directory.

Fix #22063

Signed-off-by: Andrew Thornton <art27@cantab.net>

2022-12-08 21:51 UTC, delvh approved these changes

2022-12-08 21:51 UTC, jolheiser approved these changes

2022-12-09 05:23 UTC, lunny commented
`exec.ErrDot` is only supported by go1.19

2022-12-09 17:05 UTC, delvh requested changes
As per @lunny, blocking until we use at least Go 1.19.

2022-12-09 22:45 UTC, lafriks approved these changes

2022-12-13 09:30 UTC, delvh approved these changes

2022-12-13 17:55 UTC, techknowlogick commented
ping lg-tm

2022-12-14 06:15 UTC, merged