Fix autofilled text visibility in dark mode
go-gitea/gitea pull request #22088
Opened 2022-12-10 06:39 UTC by harryzcy

Fixes #22087

2022-12-11 03:41 UTC, lunny approved these changes

2022-12-11 03:55 UTC, a1012112796 commented on web_src/fomantic/build/semantic.css
> +  -webkit-text-fill-color: #000000 !important;
wonder whether it's okay to edit built file directly...?

2022-12-11 11:05 UTC, wxiaoguang requested changes
~~Do not do this.~~

~~It's generated from official build, the change will be lost.~~


----

Update: fixed

2022-12-12 02:41 UTC, harryzcy commented
The issue seems to be caused by Formatic UI, not directly from Gitea

2022-12-12 03:51 UTC, wxiaoguang commented
> The issue seems to be caused by Formatic UI, not directly from Gitea

Yup, so maybe it could only be overwritten by Gitea's CSS files, and it needs comments IMO

2022-12-12 15:30 UTC, silverwind approved these changes

2022-12-12 15:31 UTC, silverwind commented
Changing the background would arguably be better, but this is good enough for now. I would expect browsers to eventually choose a better background color depending on `color-scheme`, which we already set.

2022-12-12 23:19 UTC, harryzcy commented
The background of the autofill is chosen by Formantic UI here:
https://github.com/fomantic/Fomantic-UI/blob/27384cb4cb827221c336e95974a2bfbfb7ed29ee/src/themes/default/globals/site.variables#L1486

2022-12-13 03:15 UTC, wxiaoguang approved these changes

2022-12-13 09:47 UTC, delvh approved these changes

2022-12-13 11:06 UTC, merged

2022-12-13 19:13 UTC, silverwind commented
> The background of the autofill is chosen by Formantic UI here: https://github.com/fomantic/Fomantic-UI/blob/27384cb4cb827221c336e95974a2bfbfb7ed29ee/src/themes/default/globals/site.variables#L1486

I see, so this is part of Fomantic's `form` module, which isn't exactly easy to get rid of, but it should be an eventual goal to remove it.