Set type="password" on all auth_token fields
go-gitea/gitea pull request #22175
Opened 2022-12-19 22:51 UTC by h3xx

Set `type="password"` on all `auth_token` fields

Seen when migrating from other hosting platforms.

1. Prevents exposing the token to screen capture/cameras/eyeballs.
2. Prevents the browser from saving the value in its autocomplete dictionary, which often is not secure.

![exposed auth token](https://user-images.githubusercontent.com/615684/208541005-e2c9c6b0-3c6c-4a56-95d9-357b987aa0c8.png)

Closes #22174

2022-12-19 22:55 UTC, delvh commented
Well… This approach has the disadvantage that the browser will ask if the "password" can be saved, which is not a good idea either.
There's no middle ground to hide the text like a password without being treated as a password, right?
I'm not sure if I prefer the proposed approach or the current one.
I think I'm neutral on this PR.

2022-12-20 09:56 UTC, silverwind commented
> Well… This approach has the disadvantage that the browser will ask if the "password" can be saved, which is not a good idea either.

Set [autocomplete="new-password"](https://developer.mozilla.org/en-US/docs/Web/Security/Securing_your_site/Turning_off_form_autocompletion#preventing_autofilling_with_autocompletenew-password) to prevent autofill. This is honored by all password managers as far as I know. Not ideal, but many password managers ignore `autocomplete=off`, so this is the best way currently.

2022-12-20 10:00 UTC, silverwind commented
To prevent autofill, one method is to change `type` from "text" to "password" after the first `input` event in JS. Should check if such a method would also prevent browser save dialogs.

2022-12-20 10:03 UTC, silverwind commented
How do other sites handle such an issue? Any examples where auth token input is masked without the downsides of a password field?

2022-12-20 19:35 UTC, silverwind commented
There does exist a [font hack](https://stackoverflow.com/a/22457652/808699). I guess this may be acceptable if the font is lightweight (ideally woff2) and can ideally be embedded as base64 in CSS.

2022-12-20 19:45 UTC, silverwind commented
Here is a possible hack that replaces the font with dots. I think the only downside is that users may not see platform-native dots, but the ones provided by the font.

https://jsfiddle.net/silverwind/y4nfo9sx/

2022-12-23 22:35 UTC, silverwind commented
https://github.com/go-gitea/gitea/pull/22232 with the suggested approach.

2023-03-17 19:08 UTC, silverwind commented
Approach is too much of a hack, so I will not chase it further. To quote myself:

> Proper solution should be type=password, we just need to figure out how to suppress the browser from offering a "Save Password" prompt. Some other forms like webhook already use type=password and there is no prompt, so it must be possible somehow.

2023-03-17 19:13 UTC, silverwind commented
Maybe `autocomplete=off` will magically remove those prompts, I see we use it on some other password fields as well.

2023-03-17 19:38 UTC, silverwind commented
Sounds good let's add it. Could you verify in at least Chrome and Firefox? If it works there, I think we are good to merge this.

2023-03-18 18:15 UTC, h3xx commented
I got to thinking, "how do other sites construct similar forms?" Gitlab has a similar-looking one at `https://gitlab.com/<user>/<project>/-/hooks`:

![image](https://user-images.githubusercontent.com/615684/226125916-87fee81b-48a4-4293-a907-2e24211704bb.png)

That form is constructed with URL being `type="text" autocomplete="off"`, and the Token input is `autocomplete="new-password" type="password"`.

<details>
<summary>(click to expand, ~8 lines)</summary>

```html
<form class="js-webhook-form" id="new_hook" action="/h3xx/frotz/-/hooks" accept-charset="UTF-8" method="post">
    <div>
        <input id="webhook-url" name="hook[url]" type="text" placeholder="http://example.com/trigger-ci.json" class="gl-form-input form-control is-valid" data-testid="form-url" aria-describedby="__BVID__4__BV_description_" autocomplete="off">
    </div>
    <div>
        <input autocomplete="new-password" class="form-control gl-form-input" type="password" name="hook[token]" id="hook_token">
    </div>
</form>
```

</details>

The browser **still** asks to save the token as password. 🤷 

Firefox test:

| URL Field | Token Field | Browser | KeepassXC-browser
| - | - | - | -
| Unmodified (no `type` no `autocomplete`) | `type=password autocomplete=new-password` | asks | asks
| `type=url autocomplete=off` | `type=password autocomplete=new-password` | asks | does not ask

This means the Mozilla docs appear to not describe how Firefox works, which is somewhat annoying.

In conclusion, I'm not sure we can get away from the browser asking to save the auth token in its password vault.

Interesting to note that when I set the token field as `autocomplete=new-password`, the Firefox pops down an option below the active field to generate a secure random password, but only when "ask to save passwords" is enabled.

2023-03-18 18:48 UTC, silverwind commented
As per https://stackoverflow.com/questions/41217019, there appears to be no documented way to suppress these storage messages, so I'm fine with accepting this, despite this minor annoyance.

2023-03-18 18:49 UTC, silverwind approved these changes

2023-03-18 19:10 UTC, silverwind commented
There may be another issue: Browser and password managers will sometimes "helpfully" auto-fill any plain `type=password` field. To prevent that, `autocomplete=new-password` is the current recommended solution that has the most widespread support. Let's add it.

2023-03-18 19:10 UTC, silverwind commented on templates/repo/migrate/gitea.tmpl
> +						<input id="auth_token" name="auth_token" type="password" value="{{.auth_token}}" {{if not .auth_token}} data-need-clear="true" {{end}}>
```suggestion
						<input id="auth_token" name="auth_token" type="password" autocomplete="new-password" value="{{.auth_token}}" {{if not .auth_token}} data-need-clear="true" {{end}}>
```

2023-03-18 19:10 UTC, silverwind commented on templates/repo/migrate/github.tmpl
> +						<input id="auth_token" name="auth_token" type="password" value="{{.auth_token}}" {{if not .auth_token}}data-need-clear="true"{{end}}>
```suggestion
						<input id="auth_token" name="auth_token" type="password" autocomplete="new-password" value="{{.auth_token}}" {{if not .auth_token}}data-need-clear="true"{{end}}>
```

2023-03-18 19:11 UTC, silverwind commented on templates/repo/migrate/gitlab.tmpl
> +						<input id="auth_token" name="auth_token" type="password" value="{{.auth_token}}" {{if not .auth_token}}data-need-clear="true"{{end}}>
```suggestion
						<input id="auth_token" name="auth_token" type="password" autocomplete="new-password" value="{{.auth_token}}" {{if not .auth_token}}data-need-clear="true"{{end}}>
```

2023-03-18 19:11 UTC, silverwind commented on templates/repo/migrate/gogs.tmpl
> +						<input id="auth_token" name="auth_token" type="password" value="{{.auth_token}}" {{if not .auth_token}} data-need-clear="true" {{end}}>
```suggestion
						<input id="auth_token" name="auth_token" type="password" autocomplete="new-password" value="{{.auth_token}}" {{if not .auth_token}} data-need-clear="true" {{end}}>
```

2023-03-18 19:12 UTC, silverwind requested changes
Withdrawing

2023-03-18 22:12 UTC, h3xx commented
Merged your suggestions, rebased off current `main`.

2023-03-18 23:59 UTC, silverwind approved these changes

2023-04-23 08:44 UTC, wxiaoguang approved these changes
If no other objection, let's take this change?

2023-04-23 10:21 UTC, silverwind commented
.

2023-04-23 10:21 UTC, silverwind commented
.

2023-04-23 14:27 UTC, techknowlogick commented
🤖 🎺

2023-04-23 14:28 UTC, merged