Fix key signature error page (#22229)
go-gitea/gitea pull request #22230
Opened 2022-12-23 21:01 UTC by Gusted

- Backport of #22229
  - When the GPG key contains an error, such as an invalid signature or an email address that does not match the user.A page will be shown that says you must provide a signature for the token.
  - This page had two errors: one had the wrong translation key and the other tried to use an undefined variable [`.PaddedKeyID`](https://github.com/go-gitea/gitea/blob/e81ccc406bf723a5a58d685e7782f281736affd4/models/asymkey/gpg_key.go#L65-L72), which is a function implemented on the `GPGKey` struct, given that we don't have that, we use [`KeyID`](https://github.com/go-gitea/gitea/blob/e81ccc406bf723a5a58d685e7782f281736affd4/routers/web/user/setting/keys.go#L102) which is [the fingerprint of the publickey](https://pkg.go.dev/golang.org/x/crypto/openpgp/packet#PublicKey.KeyIdString) and is a valid way for opengpg to refer to a key.

2022-12-23 21:14 UTC, delvh approved these changes

2022-12-28 20:15 UTC, lafriks approved these changes

2022-12-29 01:52 UTC, lunny requested changes
wait #22229

2022-12-29 13:24 UTC, delvh commented
Yeah, I already found it interesting that the 1.17 version (#22231) was merged already…

2022-12-30 02:07 UTC, lunny approved these changes

2022-12-30 04:53 UTC, merged