Fixed robots.txt 404 error
go-gitea/gitea pull request #2226
Opened 2017-07-28 19:04 UTC by sinnlosername

Fixed: https://github.com/go-gitea/gitea/issues/2210

2017-07-29 20:02 UTC, lafriks requested changes

2017-07-29 20:02 UTC, lafriks commented on routers/routes/routes.go
> +			ctx.Status(404)
It is not fixing the problem, correct code would be `ctx.Handle(404, "", nil)`

2017-07-29 20:05 UTC, sinnlosername commented on routers/routes/routes.go
> +			ctx.Status(404)
Sure? As I looked at other locations in the code where it returns a working 404.

2017-07-29 20:13 UTC, lafriks commented on routers/routes/routes.go
> +			ctx.Status(404)
I tried your code and it still returned empty 404 page

2017-07-29 20:15 UTC, sinnlosername commented on routers/routes/routes.go
> +			ctx.Status(404)
Okay, changed it!

2017-07-29 20:16 UTC, lafriks commented on routers/routes/routes.go
> +			ctx.Status(404)
`ctx.Status(404)` is used only in API routes

2017-07-29 20:24 UTC, lafriks approved these changes

2017-07-29 20:25 UTC, lafriks commented
LGTM

2017-07-30 14:31 UTC, appleboy approved these changes

2017-07-30 14:31 UTC, appleboy commented
LGTM

2017-07-30 14:32 UTC, merged