Added vendor dir for js/css libs; Documented sources (#1484)
go-gitea/gitea pull request #2241
Opened 2017-07-31 21:24 UTC by MTecknology

This PR resolves #1484 and moves vendor'ed javascript (and other) libraries to public/vendor/. It also moves the documentation to vendor/librejs.html and includes documentation for both js and non-js libs.

With this commit, it is easy to prove only free/open-source libraries are being used by gitea, which helps meet GNU ethical repository criteria (#1524).

2017-07-31 21:51 UTC, MTecknology commented
Note: before merging, librejs.html still needs to be cleaned up.

2017-08-01 19:12 UTC, sapk commented
LGTM
Just, why do you choose to put all under /plugins ? Why not keep some under sub-folder /libs like jquery, vue or semantic ?

2017-08-02 05:32 UTC, MTecknology commented
@sapk 

There were times where the CSS components weren't kept with the JS bits, butc that wasn't consistent. I moved each lib into it's own directory partly to add consistency; I also wanted to be able to include a license file for each vendor'ed library to clearly identify each project as a separate work and clearly show the license terms of that source (which also helps meet license terms).

I kept them under plugins/ instead of breaking them into the other sub-directories because I wasn't able to discern the logic to the current layout.

Example:
```
jquery-1.11.3 was under public/js/
jquery.are-you-sure was under public/js/libs/
two other jquery libs were under public/plugins/<lib-name>/

public/js/libs/
    clipboard-1.5.9
    emojify-1.1.0
public/plugins/
    highlight-9.11.0
    simplemde-1.10.1
```

Even in the source, I couldn't find a reason why they should be considered different. Sorry, I didn't mean to get long-winded or ranty... just wanted to thoroughly explain my logic. :)

2017-08-02 09:42 UTC, sapk commented
@MTecknology ok not a problem just to know if there were any reason. But effectively there wasn't before also ^^. Maybe we should think of using versionning for web ressources like npm or bower in the future. (not sure everyone will aggree with me ^^).

2017-08-02 09:49 UTC, lafriks commented
@sapk in the future we should move to webpack to have single js file

2017-08-05 03:58 UTC, MTecknology commented
@lafriks I agree! It'd be nice to have a nice json file (or two) with a pretty script to update all libs and run unit testing. If we had that, librejs.html could be turned into a dynamic file that's built by reading existing json files. (sounds great for a lot of reasons)

For now, though, it'd be super if this could make it into 1.2.0. It'd make my life a whole super duper lot easier. :)

2017-08-08 09:13 UTC, bkcsoft requested changes
A part from the question. There's no file listing which versions we have. This _have_ to exist for this to be merged. I don't care if it's a real `package.json/yarn.lock` or just a plain-text file listing them, but it absolutely have to exist.

2017-08-08 09:13 UTC, bkcsoft commented on public/assets/librejs/librejs.html
> -<!DOCTYPE html>
Why has this file changed?

2017-08-08 09:14 UTC, bkcsoft commented
> don't care if it's a real `package.json`/`yarn.lock` or just a plain-text file listing them

With this I mean that for _this_ PR I don't care, any updates in the future should use yarn though ;)

2017-08-08 09:22 UTC, sapk commented on public/assets/librejs/librejs.html
> -<!DOCTYPE html>
It has moved under public/vendor/librejs.html

2017-08-08 09:24 UTC, sapk commented
@bkcsoft we could do that in an other PR.

2017-08-08 09:25 UTC, sapk commented
And in fact all the version are listed in archive link of librejs.html

2017-08-08 09:30 UTC, bkcsoft commented
@sapk Why I hate PRs that touch 1.3k files 😂

2017-08-08 09:51 UTC, sapk commented
Me too but in this case it is mostly rename.

2017-08-08 09:55 UTC, bkcsoft commented
@sapk right, my point was that we need a file `public/vendor/VERSIONS` that just lists all versions. Since I had no idea that `librejs.html` had that, and therefore no one else knows that either 😉

2017-08-08 20:20 UTC, MTecknology commented
@bkcsoft I think I [already responded](https://github.com/go-gitea/gitea/pull/2241#issuecomment-320394389) to most of those concerns. I agree librejs.html should be dynamically generated from the output of a tool that can keep JS libs up to date.

I also think that's something much better suited for a different PR. I tried to keep this PR to just file moves and documentation. librejs.html wasn't listed as a move because the file contents changed almost entirely.

Also, in the future, it'd be nice to apply a template to the rendered page so it's not just a boring table but a themed page with the <table> as the page body.

2017-08-16 06:47 UTC, strk commented
LGTM

2017-08-18 08:23 UTC, strk commented
This is ready to merge,  why waiting for 1.3.0 ? I think it is worth having this ib 1.2.0

2017-08-18 09:03 UTC, lunny commented
It's not tested well. I don't think move it to v1.2 is a good idea.

2017-08-18 16:12 UTC, strk commented
@lunny 1.2.0 could be the first version with a proper Debian package, but I've understood a Debian package depends on this PR, for licensing issues.

#2285 was more dangerous to put in 1.2.0, if you ask me, as I suspect it's what broke the UI (#2331)

2017-08-18 19:03 UTC, MTecknology commented
@lunny This is a large PR, but I would encourage you to review what is being changed.

1. Moved 3rd party libs to designated directory
2. Updated path references to match
3. Created/updated library documentation
3a. Added missing LICENSE files
4. Fixed issues for librejs users

This PR addresses some licensing concerns that, as @strk mentioned, are blockers for other bugs--one of those being a proper Debian package. I intentionally kept this changeset as small as possible to prevent this problem. I don't know what additional testing can be performed; if you tell me, I'll do my best to make it happen.

@bkcsoft You still have "changes requested," but I do not see what changes you are requesting. Could you please tell me so that I can make them?

2017-08-19 15:37 UTC, bkcsoft commented
@MTecknology A file listing packages and versions. (no, `librejs.html` does not count 🙂 )

2017-08-19 17:52 UTC, MTecknology commented
@bksoft Your comment was about the file being removed. The file was not
removed, it was relocated and modified.

I already commented on the inclusion of an alternate option. It's a cool
idea. This PR is already big enough, isn't it?

It's a really big PR and, as I mentioned, I tried hard to keep it minimal.
I tried to keep out functional changes and keep it to documentation and
cleanup.

I disagree very much that this should be held up to wait for an entirely
new and undiscussed feature.

2017-08-21 11:53 UTC, bkcsoft commented
@MTecknology It's not a new feature, the version were tracked by the folder-names (`jquery-1.1.3` etc), but now that information is removed and needs to be added back in some form. And as I've said, it does _not_ have to be yarn/npm, just a straight up flat file listing deps and versions...

2017-08-21 22:29 UTC, strk commented
Is a machine readable format you are after, @bkcsoft ?

2017-08-22 01:24 UTC, lunny commented
I found some links broken in librejs.html master version. If this PR will also fix that?

2017-08-22 04:35 UTC, MTecknology commented
@lunny Yes...

The [first commit](https://github.com/go-gitea/gitea/pull/2241/commits/9f357b5622393792980ad18237e7d80a7707484f) in this PR:
> This commit [moves] vendor'ed plugins into a vendor/ directory and document[s] their upstream source and license in vendor/librejs.html.

I'll say this again... very little actually changes in this PR. It's documentation and licensing crap. Please, look at what [files changed](https://github.com/go-gitea/gitea/pull/2241/files) and what file changes took place. I tried very hard to make this PR very easy to review for these exact reasons... I thought I'd succeeded... :(

2017-08-23 08:08 UTC, MTecknology commented on public/assets/librejs/librejs.html
> -<!DOCTYPE html>
[As requested](https://github.com/go-gitea/gitea/pull/2241#issuecomment-320909454) => the [VERSIONS](https://github.com/go-gitea/gitea/pull/2241/commits/926cb40203569545940cde0deb20aefc6897a34e) file

2017-08-23 14:56 UTC, bkcsoft commented
@MTecknology My main quarel with having them listed in `librejs.html` is because that file is not where I'd expect to find that information. Since you've now added a `VERSION` file this LGTM 🙂

2017-08-23 14:57 UTC, bkcsoft approved these changes

2017-08-23 14:58 UTC, merged

2017-08-23 15:10 UTC, kwill commented
Awesome!

2017-08-23 15:11 UTC, lunny commented
And If you want to this in v1.2, please send a back port PR to branch release/v1.2

2017-08-23 18:46 UTC, gsantner commented
I'm on current HEAD and there are things broken. I think it's related to this one

![unbenannt](https://user-images.githubusercontent.com/6735650/29632667-f31498dc-8843-11e7-8ca5-001d54296814.png)

2017-08-23 22:08 UTC, daviian commented
Furthermore integration tests are failing because of moved librejs file.

2017-08-23 22:27 UTC, strk commented
Is drone not running integration tests ?

2017-08-23 22:27 UTC, daviian commented
@tboerger mentioned that integration tests currently run only on master branch...