Fix database write context interleaving bug
go-gitea/gitea pull request #225
Opened 2016-11-23 20:46 UTC by stroucki

(Copied from gogits/gogs)
UpdateIssueUsersByMentions was calling database write operations while
a transaction session was in progress. MailParticipants was failing
silently because of the SQLITE_LOCKED error. Make sure failures in
MailParticipants enter the log, and pass on the transaction context.
Addresses #3760.

issue: let caller pass in database context, and use it
issue_comment: obtain database context to pass to UpdateIssueMentions
issue_comment: log any error from call to MailParticipants
issue_mail: pass on database context to UpdateIssueMentions

2016-11-23 20:56 UTC, strk commented
@lunny this one sounds important, could you check it is XORM-kosher ?
LGTM

2016-11-23 21:59 UTC, LefsFlarey commented
Looks important to me, LGTM.

2016-11-23 22:31 UTC, bkcsoft commented
This doesn't actually fix anything though...

2016-11-23 22:41 UTC, stroucki commented
It does though - it logs errors that would have otherwise been not logged, and permits mention emails to get sent out, that would otherwise have failed because of the SQLITE_LOCKED error.

2016-11-23 22:45 UTC, tboerger commented
:-1: it changes the model function behavior like it's currently done everywhere

2016-11-23 22:46 UTC, tboerger commented
If you only catch the error I'm fine with it

2016-11-23 23:06 UTC, stroucki commented
Just catching the error is not sufficient to fix the underlying problem. In the xorm log below:
```
[xorm] [info]  2016/10/26 23:30:23.088011 [sql] BEGIN TRANSACTION
[xorm] [info]  2016/10/26 23:30:23.088041 [sql] INSERT INTO `comment` (`type`,`poster_id`,`issue_id`,`commit_id`,`line`,`content`,`created_unix`,`updated_unix`,`commit_sha`) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?) [args] [0 4 5 0 0 @stroucki: x 1477539023 1477539023 ]
[xorm] [info]  2016/10/26 23:30:23.088209 [sql] UPDATE `issue` SET num_comments=num_comments+1 WHERE id=? [args] [5]
[xorm] [info]  2016/10/26 23:30:23.088278 [sql] SELECT `id`, `user_id`, `repo_id` FROM `watch` WHERE `repo_id`=? [args] [43]
[xorm] [info]  2016/10/26 23:30:23.088418 [sql] INSERT INTO `action` (`user_id`,`op_type`,`act_user_id`,`act_user_name`,`repo_id`,`repo_user_name`,`repo_name`,`ref_name`,`is_private`,`content`,`created_unix`) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) [args] [4 10 4 test 43 test test  false 2|@stroucki: x 1477539023]
[xorm] [info]  2016/10/26 23:30:23.088570 [sql] SELECT `id`, `lower_name`, `name`, `full_name`, `email`, `passwd`, `login_type`, `login_source`, `login_name`, `type`, `location`, `website`, `rands`, `salt`, `created_unix`, `updated_unix`, `last_repo_visibility`, `max_repo_creation`, `is_active`, `is_admin`, `allow_git_hook`, `allow_import_local`, `prohibit_login`, `avatar`, `avatar_email`, `use_custom_avatar`, `num_followers`, `num_following`, `num_stars`, `num_repos`, `description`, `num_teams`, `num_members` FROM `user` WHERE lower_name IN (?) ORDER BY `lower_name` ASC [args] [stroucki]
[xorm] [info]  2016/10/26 23:30:23.088870 [sql] UPDATE `issue_user` SET `uid` = ?, `issue_id` = ?, `repo_id` = ?, `milestone_id` = ?, `is_read` = ?, `is_assigned` = ?, `is_mentioned` = ?, `is_poster` = ?, `is_closed` = ? WHERE `id`=? [args] [1 5 0 0 false false true false false 0]
[xorm] [info]  2016/10/26 23:30:23.089178 [sql] COMMIT
```
a transaction is opened and commands are issued to that session, but in UpdateIssueUsersByMentions, the update issue_user command is issued from outside the session, resulting in a SQLITE_LOCKED error and the failure to send out an email.

2016-11-24 00:46 UTC, lunny commented on models/issue.go
>  	for _, uid := range uids {
If you mean this operation need a transaction, we should use `Begin()` and `Commit()`.
```Go
sess := x.NewSession()
defer sess.Close()
if err := sess.Begin(); err != nil {
    return err
}

...
return sess.Commit()
```

2016-11-24 01:30 UTC, stroucki commented
@lunny concerning the comment you made (which is not showing up here), there already is a transaction active. If you can create another transaction within an existing one (and have it succeed), then that should work.
What my pull-request does is bring down the existing session to UpdateIssueUsersByMentions.

2016-11-24 08:08 UTC, strk commented
@stroucki if you could showcase the bug with an automated testcase that'd be great and also ensure it won't break again in the future.

2016-11-24 08:19 UTC, lunny requested changes

2016-11-24 08:19 UTC, lunny commented on models/issue_mail.go
> +	if err = UpdateIssueMentions(x, issue.ID, mentions); err != nil {
There are two places which invoked `UpdateIssueMentions`.
This one will not contains any transaction, should this be fixed?

2016-11-29 01:20 UTC, stroucki commented on models/issue_mail.go
> +	if err = UpdateIssueMentions(x, issue.ID, mentions); err != nil {
Don't know - I haven't checked to see whether it gets called during a transaction.

2016-12-25 09:42 UTC, lunny commented
It seems I have merged this some PR?

2016-12-28 01:41 UTC, lunny commented
I thinks these have been merged by some other PR but I cannot find it. Please feel free to reopen this.

2016-12-28 01:41 UTC, closed without merging