GitHub API Compliance Fixes
go-gitea/gitea pull request #227
Opened 2016-11-23 21:06 UTC by bkcsoft

This fixes a few API-bugs

## Fixes!
- Label-data are now compliant
- Labels can be fetched by Name (as well as ID)
- API-Token can be sent via `?access_token=[...]`
- Issue-Listing can be queried for `?state=all` to fetch _all_ issues (for said repo)
- Repos can be fetched by ID with `/repositories/:id` (undocumented feature, but it's used by OctoKit 😒 )

## Backwards Compatability Breakage!
- `label.Color` is no longer prefixed with `#` (since GH doesn't do that)

Related Issue: #64 
I'm sure there are more Gogs-issues that I'm closing with this PR, but I'm to lazy ATM to look them up 😆

2016-11-23 21:23 UTC, 0xbaadf00d commented
LGTM

2016-11-23 21:56 UTC, LefsFlarey commented
LGTM.

2016-11-23 22:04 UTC, bkcsoft commented
@lunny @tboerger I want a 3rd opinion since I'm actually breaking stuff here as well :trollface:

2016-11-23 22:07 UTC, LefsFlarey commented
@bkcsoft would it not be technically a 4th and 5th opinion? 1st being yours, 2nd being @0xbaadf00d and 3rd being me... unless I'm not an opinion ._.

2016-11-23 22:08 UTC, bkcsoft commented
@LefsFlarey I didn't count myself 😆

2016-11-23 22:12 UTC, LefsFlarey commented
@bkcsoft oh ok. .-.

2016-11-24 01:43 UTC, lunny requested changes

2016-11-24 01:43 UTC, lunny commented on routers/api/v1/repo/repo.go
> +	repo, err := models.GetRepositoryByID(ctx.ParamsInt64(":id"))
golint

2016-11-24 20:40 UTC, bkcsoft commented
@lunny done :)

2016-11-24 20:56 UTC, bkcsoft commented
rebased and fixed conflicts :)

2016-11-29 10:30 UTC, bkcsoft commented
@lunny could you review again? :slightly_smiling_face:

2016-11-29 10:36 UTC, tboerger commented
LGTM

2016-11-29 10:36 UTC, tboerger commented
But maybe you need to rebase as the drone push failed with matrix builds.

2016-11-29 10:53 UTC, bkcsoft commented
@tboerger noted, I also need to rebase now that a few fixes in this one got fixed in #300 (related to go-sdk vendor update)...

2016-11-29 11:28 UTC, lunny approved these changes

2016-11-29 11:30 UTC, lunny commented
push failed

2016-12-02 09:03 UTC, bkcsoft commented
Now it should be fine :D

2016-12-02 09:04 UTC, merged