[WIP] Add OpenID configuration in install page
go-gitea/gitea pull request #2276
Opened 2017-08-08 09:16 UTC by strk

Allows enabling OpenID signin via installation page GUI

2017-08-08 09:36 UTC, strk commented
This needs be merged before 1.2.0 is out - but there's still a problem with routes depending on the configuration and the configuration being changed by install page but not being re-read upon changing it... So it takes re-starting gitea to be able to register first user via OpenID. I've to figure out how to do the settings update from form submission

2017-08-08 09:42 UTC, strk commented
I think the fix here is to always define the route but then return a Forbidden status if the service is not enabled

2017-08-08 09:50 UTC, strk commented
Ready for merge, tested locally.

2017-08-08 10:00 UTC, strk commented
@cweiske you might be interested in testing this too. It basically adds a way to configure OpenID at installation time (was missing, so it took manual intervention to enable it)

2017-08-08 10:02 UTC, lafriks requested changes
You have enabled all openid routes but added check that openid is enabled only in two of them

2017-08-08 10:15 UTC, strk commented
@lafriks 754dd4ea7c9b8c009bf164153dedead98331b636 fixes that,
thanks for spotting it !

2017-08-08 15:28 UTC, lunny commented
@strk CI failed.

2017-08-08 15:39 UTC, lafriks requested changes

2017-08-08 15:39 UTC, lafriks commented on routers/user/auth_openid.go
> +	if ! setting.Service.EnableOpenIDSignIn {
CI is failing because of space after `!`

2017-08-08 19:46 UTC, strk commented
Thanks @lafriks, I removed all those spaces and verified
that `make check` passes locally

2017-08-09 05:10 UTC, lafriks requested changes

2017-08-09 05:10 UTC, lafriks commented on routers/routes/routes.go
> +				Get(user.ConnectOpenID).
`ConnectOpenID` is still missing check if `EnableOpenIDSignIn` is enabled

2017-08-09 05:10 UTC, lafriks commented on routers/routes/routes.go
> +			m.Combo("").Get(user.SettingsOpenID).
`SettingsOpenID` is still missing check if `EnableOpenIDSignIn` is enabled

2017-08-09 05:10 UTC, lafriks commented on routers/user/setting_openid.go
> +	if !setting.Service.EnableOpenIDSignUp {
I think there should be check for `EnableOpenIDSignIn` not for `EnableOpenIDSignUp` that is for new user registration

2017-08-09 05:10 UTC, lafriks commented on routers/user/setting_openid.go
> +	if !setting.Service.EnableOpenIDSignUp {
There should also be check for `EnableOpenIDSignIn`

2017-08-09 05:10 UTC, lafriks commented on routers/user/setting_openid.go
> +	if !setting.Service.EnableOpenIDSignUp {
And there also should be check for `EnableOpenIDSignIn`

2017-08-09 15:40 UTC, strk commented
@lafriks please see ed9ade1d
To be honest for the settings we might not even check...

2017-08-11 15:59 UTC, bkcsoft requested changes

2017-08-11 15:59 UTC, bkcsoft commented on modules/auth/user_form.go
> +	DisableOpenIDRegistration      bool
I'd rather have these both as `EnableFoo` since it makes more sense when reading

2017-08-11 15:59 UTC, bkcsoft commented on routers/routes/routes.go
> +				Get(user.ConnectOpenID).
Agreed, any pre-requisite settings should be checked in the route-setup, not the route-handler 🙂

2017-08-11 16:03 UTC, strk commented
On Fri, Aug 11, 2017 at 08:59:31AM -0700, bkcsoft wrote:

> +	EnableOpenIDSignIn             bool
> +	DisableOpenIDRegistration      bool
> 
> I'd rather have these both as `EnableFoo` since it makes more sense when reading

Please take a look at the user GUI first.
There's a "DisableRegistration", so I made this
"DisableOpenIDRegistration" for consistency on that side of things.
The GUI makes the two go togheter (via Javascript).

2017-08-16 07:23 UTC, strk commented
@bkcsoft do you really want to hold this PR back due to the enable vs. disable wording ?

2017-08-16 09:11 UTC, strk commented
@bkcsoft I've renamed Disable to Enable, as you requested. And rebased to master.
@lafriks I think I've handled your requests too.

2017-08-16 09:21 UTC, strk commented
actually, the change was partial, more changes were needed around, so I reverted it.

2017-08-16 14:47 UTC, strk commented
latest commits fix the handling of checkboxes *and* turn openid sign-in on by default for new installs

2017-08-16 15:02 UTC, strk commented
And for @bkcsoft now I've also turned the "OpenID Registration" form into an "enable" rather than "disable". Also added more javascript to check/uncheck dependents...

2017-08-17 23:48 UTC, lafriks approved these changes

2017-08-17 23:52 UTC, lafriks commented
As for consideration it would probably be better as @bkcsoft recommended to create new handler/filter to check if openid signin/signup is enabled. Something like this:
https://github.com/go-gitea/gitea/blob/master/routers/routes/routes.go#L336

2017-08-18 14:28 UTC, strk commented
Can we get this merged before 1.2.0 please ? Aesthetic changes can happen in a second step, for now it's important for the functionality to be there.

2017-08-18 14:44 UTC, lafriks commented
I'm not against it, @bkcsoft?

2017-08-18 16:33 UTC, strk commented
@lafriks can you give your LGTM so it's there when needed ? :)

2017-08-18 16:34 UTC, strk commented
btw, there's something wrong with the LGTM bot, because I read `1 of 2 required approvals granted ` in the `approvals/lgtm` check but the label still reads `lgtm/need2`

2017-08-18 19:04 UTC, lafriks commented
BTW don't write LG-TM in comments for your own PR ;) otherwise I see LG-TM 1 label

2017-08-18 20:01 UTC, strk commented
Sorry about that, I thought it was fixed (definitely a bug, isn't it ?) - I wasn't seeing the label when I wrote the next comment, btw. Now I see it.

2017-08-19 01:50 UTC, lunny commented
@strk it was fixed I remember.

2017-08-19 07:12 UTC, strk commented
@lunny so it was not deployed? 
Anyway, can you review this PR  or at least mark it as targeted to 1.2?

2017-08-19 10:16 UTC, lunny commented
@strk I don't think it's necessary for add this config to installation on v1.2 since LDAP, OAuth and SMTP didn't add to the page. And I think a middleware to check is better than so many settings check on the route functions.

2017-08-19 10:44 UTC, strk commented
Ok now that master branch is fixed I've rebased and also committed a change using filters as suggested in previous comment. @bkcsoft can you please review and merge or at least label as targetted at 1.2.0

2017-08-19 10:53 UTC, lafriks commented
@strk please fix formatting issues (see Drone)

2017-08-19 11:07 UTC, strk commented
@lunny I committed the middleware check and dropped the checks in the
route functions. As per installation steps: OpenID is special in that
it is a config file, not database, configuration. That's why LDAP
and OAuth and SMTP do not belong in the installation page, while
OpenID does.

2017-08-19 11:34 UTC, lafriks commented
LG-TM

2017-08-19 15:33 UTC, bkcsoft approved these changes

2017-08-19 15:33 UTC, bkcsoft commented
LGTM

2017-08-19 15:34 UTC, merged