Added short-hash support to downloads
go-gitea/gitea pull request #228
Opened 2016-11-23 21:11 UTC by Bwko

Fixes #211

2016-11-23 21:35 UTC, strk commented
LGTM - this should go in 1.0.0 as bugfix

2016-11-23 21:36 UTC, strk commented on routers/repo/repo.go
> +	} else if len(refName) > 7 && len(refName) <= 40 {
btw, should that be >= 7 instead ?

2016-11-23 21:36 UTC, strk commented
Adding an automated testcase would be great too

2016-11-23 21:36 UTC, tboerger requested changes

2016-11-23 21:36 UTC, tboerger commented on routers/repo/repo.go
> +	} else if len(refName) > 7 && len(refName) <= 40 {
It should be == 7 or == 40, beside that I'm not sure if this is the only place that needs to be changed

2016-11-23 21:50 UTC, Bwko commented
Currently only a short hash of 8 characters work. But it's not mandatory for a short hash to be x characters long. See http://stackoverflow.com/a/21015031
Maybe we could set it from >=4 (minimum short hash is 4 characters) to <= 40?

2016-11-23 21:58 UTC, LefsFlarey commented
LGTM

2016-11-23 22:00 UTC, bkcsoft commented on routers/repo/repo.go
> +	} else if len(refName) > 7 && len(refName) <= 40 {
nope, should be `7 <= len(refName) <= 40` just like it is, otherwise `f00badf00d.tar.gz` wouldn't work 🙂

2016-11-24 06:44 UTC, tboerger commented on routers/repo/repo.go
> +	} else if len(refName) > 7 && len(refName) <= 40 {
So how have it worked before with == 40?

2016-11-24 07:54 UTC, strk commented
Before it didn't work for anything != 40, follow the reference
to the bug (filed by myself, btw).

The new code will still not support a 7-chars long refName
due to `len(refName) > 7` -- should read `len(refName) >= 7`,
or whatever min lenght you want to support.

Question: what happens if a colliding short hash is used ?

2016-11-24 08:10 UTC, Bwko commented
That's why I suggested this:

> Maybe we could set it from >=4 (minimum short hash is 4 characters) to <= 40?

Question: what happens if a colliding short hash is used ?

Git will produce an ambiguous error:

> error: short SHA1 0001 is ambiguous.

2016-11-24 08:13 UTC, strk commented
On Thu, Nov 24, 2016 at 12:10:32AM -0800, Bwko wrote:
> That's why I suggested this:
> 
> > Maybe we could set it from >=4 (minimum short hash is 4 characters) to <= 40?
> 
> Question: what happens if a colliding short hash is used ?
> 
> Git will produce an ambiguous error:
> 
> > error: short SHA1 0001 is ambiguous.

Is Gitea code ready to handle that or would it choke ?

2016-11-24 08:14 UTC, 0xbaadf00d commented
Github allow usage of 7 length commit hashes. No collision encountered on big repo (eg: Linux kernel have 700k commits)

2016-11-24 08:20 UTC, Bwko commented
I think it'll throw a 404 error. When using 7 characters the change of a collision is 1 in 250 million

2016-11-24 08:49 UTC, strk commented
On Thu, Nov 24, 2016 at 12:20:43AM -0800, Bwko wrote:
> I think it'll throw a 404 error.

Could you please check ?
Accept as low as 2 characters and try fetching a tarball with those.

> When using 7 characters the change of a collision is 1 in 250 million

Is there any reason for not accepting a few as 4 chars, from an API
point of view ? This is about *accepting*, not *providing*, so we
should be as liberal as possible, for the robustness principle.

I'm fine with starting as low as 7, in any case (but this PR starts
from 8 as far as I understand the code, so should still be changed)

2016-11-24 10:46 UTC, Bwko commented
@strk I've lowered the minimum length to 4. I've just tested this and collisions result in a 404 error

2016-11-24 10:57 UTC, tboerger approved these changes

2016-11-24 10:57 UTC, tboerger commented
LGTM

2016-11-24 11:37 UTC, strk commented
LGTM, please merge @go-gitea/owners

2016-11-24 12:38 UTC, merged