Adjust manifest to prevent tagging latest on rcs
go-gitea/gitea pull request #22811
Opened 2023-02-07 21:24 UTC by zeripath

Our current manifests will always tag `latest` whenever `auto_tag` is set - which it is when drone detects a tag.

This PR detects that the auto_tag build is for an rc by detecting if the build.tag contains `-rc` and if so does not tag `latest`.

Signed-off-by: Andrew Thornton <art27@cantab.net>

2023-02-07 22:28 UTC, jolheiser commented on docker/manifest.rootless.tmpl
> +{{#if contains "-rc" (first build.tags) }}
Shouldn't this use `unless` as well?

2023-02-07 22:31 UTC, jolheiser commented on docker/manifest.rootless.tmpl
> +
```suggestion
{{#unless contains "-rc" (first build.tags) }}
  - "latest-rootless"
{{/unless}}
{{/if}}
```

2023-02-07 23:02 UTC, techknowlogick reviewed
I believe this would still set `:1` and `:1.19`

2023-02-08 22:00 UTC, zeripath commented
My reasoning is thus:

The manifests are created here:

```.drone.yml
  - name: manifest-rootless
    image: plugins/manifest
    pull: always
    settings:
      auto_tag: true
      ignore_missing: true
      spec: docker/manifest.rootless.tmpl
      password:
        from_secret: docker_password
      username:
        from_secret: docker_username

  - name: manifest
    image: plugins/manifest
    settings:
      auto_tag: true
      ignore_missing: true
      spec: docker/manifest.tmpl
      password:
        from_secret: docker_password
      username:
        from_secret: docker_username

```

This will set `build.tag` to the tag.

However, auto_tag will cause drone-manifest to set `build.tags` to:

```go
// DefaultTags returns a set of default suggested tags.
func DefaultTags(ref string) []string {
	if !strings.HasPrefix(ref, "refs/tags/") {
		return []string{"latest"}
	}

	v := stripTagPrefix(ref)

	version, err := semver.NewVersion(v)

	if err != nil {
		return []string{"latest"}
	}

	if version.PreRelease != "" || version.Metadata != "" {
		return []string{
			version.String(),
		}
	}

	v = stripTagPrefix(ref)
	v = splitOff(splitOff(v, "+"), "-")
	dotParts := strings.SplitN(v, ".", 3)

	if version.Major == 0 {
		return []string{
			fmt.Sprintf("%0*d.%0*d", len(dotParts[0]), version.Major, len(dotParts[1]), version.Minor),
			fmt.Sprintf("%0*d.%0*d.%0*d", len(dotParts[0]), version.Major, len(dotParts[1]), version.Minor, len(dotParts[2]), version.Patch),
		}
	}

	return []string{
		fmt.Sprintf("%0*d", len(dotParts[0]), version.Major),
		fmt.Sprintf("%0*d.%0*d", len(dotParts[0]), version.Major, len(dotParts[1]), version.Minor),
		fmt.Sprintf("%0*d.%0*d.%0*d", len(dotParts[0]), version.Major, len(dotParts[1]), version.Minor, len(dotParts[2]), version.Patch),
	}
}
```

Now:
 
```go
$ gore 
gore version 0.5.4  :help for help
gore> :imp github.com/coreos/go-semver/semver
gore> semver.NewVersion("1.19-rc0")
(*semver.Version)(nil)
&errors.errorString{
  s: "1.19 is not in dotted-tri format",
}
gore> semver.NewVersion("1.19.0-rc0")
&semver.Version{
  Major:      1,
  Minor:      19,
  Patch:      0,
  PreRelease: "rc0",
  Metadata:   "",
}
nil
```

So actually we can just stick an unless around the build.tags section.

2023-02-09 17:12 UTC, techknowlogick approved these changes
<3

2023-02-10 01:13 UTC, techknowlogick requested changes
Argh… I’m sorry to do this. This works for manifest, but the arch specific builds also need to have constraints updated

2023-02-11 05:59 UTC, zeripath commented
Ok I don't know where to look for that. Any ideas?

2023-02-11 09:06 UTC, yardenshoham commented
I'm not sure but maybe here:
https://github.com/go-gitea/gitea/blob/fb1a2a13f05665764a6f91ed1a421b9e93c4e8c9/.drone.yml#L976
https://github.com/go-gitea/gitea/blob/fb1a2a13f05665764a6f91ed1a421b9e93c4e8c9/.drone.yml#L1040
https://github.com/go-gitea/gitea/blob/fb1a2a13f05665764a6f91ed1a421b9e93c4e8c9/.drone.yml#L1103
https://github.com/go-gitea/gitea/blob/fb1a2a13f05665764a6f91ed1a421b9e93c4e8c9/.drone.yml#L1264

2023-02-12 21:07 UTC, zeripath commented
Assuming we mean the docker images created by the lines with: `techknowlogick/drone-docker:latest`

Then... as long as we tag our RCs in the tri-format: e.g. `1.19.0-rc0` then this will work

2023-02-12 21:13 UTC, zeripath commented
An alternative is to start using `exclude` to exclude RCs.

2023-02-13 20:04 UTC, techknowlogick approved these changes

2023-02-18 14:12 UTC, lunny approved these changes

2023-02-19 14:24 UTC, merged