Fix and improve dashboard repo UI
go-gitea/gitea pull request #2285
Opened 2017-08-09 14:50 UTC by Morlinest

This commit contains one fix and few UI improvements:

1. (Fix) Do not show Vue template data, show spinner instead
2. Add search icon to input and show spinner/loader while loading data from server
3. Resolve race condition in search ajax callback (just simple check)
4. Add total count to repo search api (api/v1/repos/search) - new header `X-Total-Count`
5. Move search input and add filter for repositories - `All`, `Sources`, `Forks` and `Collaborative`
6. Add search limit to query (default value in meta tag `_search_limit`, filled by server)

Screenshots and animated gifs are in #2278 (scroll down; showing max 10 repos, this commit version is with default filled by server = 15).

First time working with Vue + new to Semantic UI so any advice is welcome.

2017-08-09 14:52 UTC, lunny commented
Also fix #2114 and replace #2205

2017-08-09 15:14 UTC, lafriks commented
@lunny I think it does not fixes nor replaces your mentioned issue/PR it just improves Dashboard UI

2017-08-09 15:37 UTC, Morlinest commented
Maybe merge #2205 first, I'll rebase and check with my code? There are some improvements in #2205, also some unused code is removed (that is why i didnt remove anything).

2017-08-09 16:02 UTC, lunny commented
@lafriks Yes, you are right. We need merge #2205 at first.

2017-08-11 11:23 UTC, Morlinest commented
What do you think about Vue components? I've created `search-repo` component (with x-template) and then used inside Vue. There is no need for `v-cloak` and `v-show` and `isMounted ` variable. It can be also reused later, on other pages (just example). For future improvements, I think we can create folder with vue components (x-templates) that can be generated/filled by server and just add to pages where we need them.

2017-08-13 22:42 UTC, andreynering commented on public/js/index.js
> +                let searchedQuery = this.searchQuery;
`let` -> `var` to not break on older browsers, since this is not being preprocessed.

2017-08-13 22:42 UTC, andreynering commented
LGTM

2017-08-14 07:47 UTC, Morlinest commented on public/js/index.js
> +                let searchedQuery = this.searchQuery;
Done

2017-08-14 08:11 UTC, Morlinest commented
Changed to Vue component. What about full client rendering of component? That means no mirrors or organizations rendering on server, remains only localization.

Next posible upgrades (of this PR):

1. Full client rendering of component (except localization) - preparation for future pure independent component (so it can be cached as js, bundled, etc)
2. Change concrete `#dashboard-repo-search` to universal `#app` - init Vue on any page, where we will need it, just add `id="#app"` to element (do not need new `Vue` on each page or for each new feature, every feature should be added as component)

2017-08-14 10:14 UTC, andreynering commented
@Morlinest I think these changes should be made in future PRs. We prefer small PRs when possible.

2017-08-14 10:21 UTC, Morlinest commented
@andreynering OK, I'll create new branch(es) and send new PR(s) :)

2017-08-14 14:59 UTC, Morlinest commented
@lunny @andreynering Should not be "mirror" tab removed? I've just created mirror and they are also shown in "My Repositories" tab. I can only add new filter. Or you want to have them on both tabs (`Mirrors` filter can be added anyway)?

2017-08-14 15:09 UTC, lunny commented
@Morlinest I agree to add a mirrors filter and remove the tab mirror. @andreynering any idea?

2017-08-14 15:38 UTC, andreynering commented
@lunny @Morlinest :+1: I agree with that.

2017-08-14 19:48 UTC, Morlinest commented
@lunny @andreynering Great, it is done (few hours ago :D, will update PR tomorrow). But this creates new question :). Now there is only 1 or 2 tabs (1 for "org user", 2 for "normal user"). What about this? I see two options:

1. Hide tabs panel when showing "org user", show 2 tabs when showing "normal user"
2. Dont show any tab, instead show 1 panel for "org user" and always show both 2 panels for "normal user"

2017-08-15 07:21 UTC, Morlinest commented
After adding `mirrors` filter and removing `mirror` tab:
1. Normal user
![image](https://user-images.githubusercontent.com/12720041/29305834-05ed0c46-819b-11e7-9ceb-9732e962c5fb.png)

2. Org user
![image](https://user-images.githubusercontent.com/12720041/29305804-e0203326-819a-11e7-8ec6-3fd565c27ccb.png)

2017-08-15 09:29 UTC, daviian commented
At first I want to thank you all for you hard and great work!
Just switched to gitea some days ago and I think it is time to start contributing, but I have to get into golang before ;-)

In my opinion the tab panel for the org user is redundant and should be removed.
It is totally clear that the box below is about a users repositories as the header states "My Repositories".

2017-08-15 09:37 UTC, Morlinest commented
@daviian Thanks (from all). I agree with you that solo tab panel for "org user" is redundant. Another question is, what to for "normal user" page - show 2 tabs or show 2 panels (one above other).

2017-08-15 09:43 UTC, daviian commented
@Morlinest I think there should be 2 panels. The collaborative repositories panel is gone. So why not use this freed space. And because of the pagination in the repositories panel they shouldn't take too much vertical space anyway.

2017-08-15 10:13 UTC, Morlinest commented
OK, I've did some practical tests... If you have only few orgs, its no problem to have 2 panels visible at the same time. But if you have for example 20 orgs, there is not enough space on screen to show both panels without scrolling... Also orgs does not have any pagination, so everythink is shown in one list.

I wanted to use 2 panels at first, but now I think "two tabs" for "normal user" and "no tab" for "org user" will fit best.

Also i want to add some kind of settings later to give user option to increase/decrease pagination limit (REST api for "repo/search" has limit of min 10 and max 50 records).

@lunny @andreynering Any idea?

2017-08-15 17:05 UTC, daviian commented
@Morlinest I thought about it and why not use something like accordions?

1. Normal User
![accordion](https://user-images.githubusercontent.com/5477981/29326612-87a314a0-81ec-11e7-87ce-37fa007021ea.png)

2. Org User
![orguser-accordion](https://user-images.githubusercontent.com/5477981/29326602-7e404914-81ec-11e7-8425-d7fc538df6ca.png)

So if a clicks on My Organizations the repository panel is collapsing and vice versa.
Adding of repositories and organizations is still just one click away.

2017-08-16 00:45 UTC, lunny commented
@Morlinest I don't like @daviian 's idea. Because I have hundreds of repositories and twenties of orgnizations on one of my Gitea instance. I think keep two tab is better.

2017-08-16 07:14 UTC, Morlinest commented
@lunny I agree. I have same opinion after some practical tests :). I will remove tab panel for "org user". Do you want to add `X-Total-Count` header to swagger doc = make it official?

2017-08-16 07:58 UTC, lunny commented
Or maybe just remove `My organizations` since there are the list on dashboard already.

2017-08-16 08:03 UTC, Morlinest commented
Can be removed in other PR. I like that preview of orgs, for me it is more clear as list.

2017-08-16 08:07 UTC, lunny commented
@Morlinest OK. LGTM

2017-08-16 08:09 UTC, lunny commented
@Morlinest A problem is you should put `All`, `Mirrors` to language-en-us file, otherwise LGTM.

2017-08-16 09:30 UTC, Morlinest commented
@lunny Added missing localization strings (`All`, `Sources`, `Mirrors` and `Collaborative`).

Should I add `X-Total-Count` to swagger doc? I don`t know if you want to solve the missing "total count" problem this way (#2277).

2017-08-16 10:15 UTC, lunny commented
@Morlinest maybe you can add `X-Total-Count` in another PR?

2017-08-16 10:39 UTC, Morlinest commented
@lunny If you mean "add to docs", sure I can. As feature, has to be in this PR, because it is the only (fastest) way I know how many repos user has.

2017-08-16 13:07 UTC, lunny requested changes

2017-08-16 13:07 UTC, lunny commented on templates/vue/repo-search.tmpl
> +<script type="text/x-template" id="repo-search-template">
I don't think the file should be in `templates/vue` dir. We classify the templates according features not the front-end framework it used.

2017-08-16 13:15 UTC, Morlinest commented on templates/vue/repo-search.tmpl
> +<script type="text/x-template" id="repo-search-template">
Where should I put it then? It's here for 2 (temporary) reasons:

1. There are part rendered by server
2. You can include it on any page as template for component (can't be included in js for reason 1)

2017-08-16 13:22 UTC, Morlinest commented on templates/vue/repo-search.tmpl
> +<script type="text/x-template" id="repo-search-template">
Or you want me just to rename the folder like `templates/components`?

2017-08-16 13:27 UTC, lunny commented on templates/vue/repo-search.tmpl
> +<script type="text/x-template" id="repo-search-template">
Just put it in `user/dashboard/`? an other page reference it?

2017-08-16 13:35 UTC, Morlinest commented on templates/vue/repo-search.tmpl
> +<script type="text/x-template" id="repo-search-template">
Not now, but can be referenced later. I just wanted to make it more universal.

2017-08-16 15:30 UTC, Morlinest commented
Rebased on master and changed `repo-search.tmpl` folder to `templates/user/dashboard`.

2017-08-17 01:31 UTC, lunny approved these changes

2017-08-17 01:31 UTC, merged

2017-08-18 19:33 UTC, strk commented
This change broke Go 1.7 support, please make sure #2331 is fixed before 1.2.0 is closed