Improve pull_request_template.md
go-gitea/gitea pull request #22888
Opened 2023-02-13 09:46 UTC by wolfogre

- It's a kind idea to hide the tips. However, it's easier to include them in the commit message if you cannot see them in the content of PR. Check `git log | grep 'Please check the following:'`. So don't hide it, expose it and help fix it.
- "for backports" is much clearer than "for bug fixes". I saw someone post a PR to a release branch because he/she believed it was the right way for a bugfix.
- "Allow edits by maintainers", or we have to ask the contributor to update the branch and he/she could be confused.

2023-02-13 12:48 UTC, yardenshoham commented
I don't really like that `---` rule. I'd prefer that info in the first PR comment.

2023-02-13 14:39 UTC, wolfogre commented
> I don't really like that `---` rule. I'd prefer that info in the first PR comment.

Why not?

If contributors don't like it, they don't have to use it, and they can still write things in the first comment.

If mergers don't like it, it's probably because it requires them to merge more carefully. And that is indeed my evil plan!😂

Just kidding, I'll update it to "the first comment" if most people don't like '---'.

2023-02-13 20:41 UTC, techknowlogick commented on .github/pull_request_template.md
>  Please check the following:
Could you wrap the tips in `<!-- start tips -->` and `<!-- end tips -->` so that we could have a webhook tool that strips them in case a contributor forgets?

2023-02-14 03:28 UTC, lunny approved these changes

2023-02-14 08:47 UTC, yardenshoham requested changes
If you do keep the `---` change (which, again, I am against). You'll have to make changes in at least one other place,
https://github.com/go-gitea/gitea/blob/7b5b739a2f9d9c84ec216ff629dbf0d1dd8a4322/CONTRIBUTING.md?plain=1#L266

The backports today take the original PR's summary

2023-02-14 09:59 UTC, wolfogre commented
> If you do keep the `---` change (which, again, I am against). You'll have to make changes in at least one other place,
> 
> https://github.com/go-gitea/gitea/blob/7b5b739a2f9d9c84ec216ff629dbf0d1dd8a4322/CONTRIBUTING.md?plain=1#L266
> 
> The backports today take the original PR's summary

I haven't thought about it, because I always send packports like `git cherry-pick [the commit id which has been merged to main]`, and the commit message (I believe it has been corrected) will be the body of new PR automatically, and the only thing I have to do is just add "Backport #xxx".

I don't know, maybe I'm not doing it the usual way. Whatever, if it turns out that the merger needs to be more careful, I'm fine with that. Even without `---`, the merger still has to check it again if the contributor keeps the deleted text in backport PR. However, if contributors know how to use `---` in the right way, it will be easier to check.

Maybe we can have a robot to send backport PRs automatically, and it's easy to recognize `---` and handle it. I heard you already did something like that. 👀

2023-02-14 10:31 UTC, wolfogre commented
> When I did it I followed these instructions so when I create the PR I literally concatenate them: [yardenshoham/gitea-backporter@`5ebdca2`/src/github.ts#L80](https://github.com/yardenshoham/gitea-backporter/blob/5ebdca217f8b22c18951e0bef014d60a7bc7679c/src/github.ts#L80)

You are right to follow the instructions, however, if the merger has adjusted the commit message and your awesome backporter uses the `originalPr.body` to send a backport, the merger has to adjust it again. That's not your fault, that's the merger's work, if your backporter removes `---`, that's a friendly help. If your backporter keeps it, it still does nothing wrong. 

BTW, could you please add a delay to backporter? I mean just help sending backports only for PRs which have been forgotten for maybe 24 hours, to avoid conflicts. Never mind if you already did.😄

2023-02-14 10:43 UTC, wxiaoguang commented
I agree with the "---" separator, or anything similar to help to distinguish commit-message and none-commit-message. It just helps the mergers to know which part is important while which part is not.

Mergers should always pay attention to the merge messages, and improve the message manually if necessary, instead of just clicking "Merge" without any check. Clicking "merge" without any check is the easiest work without any requirement, mergers should do far more than that. I have said many times in discord channel that the commit message was polluted, but various unrelated messages still go into git history.

2023-02-14 10:44 UTC, yardenshoham commented
@wolfogre 

No problem, I'll change my code to match whatever behavior is written in `CONTRIBUTING.md` but you have to agree that before this PR lands, there must be changes to `CONTRIBUTING.md`

Thanks for calling my backporter awesome!

2023-02-14 13:18 UTC, wolfogre commented
> ... I'll change my code to match whatever behavior is written in `CONTRIBUTING.md` but you have to agree that before this PR lands, there must be changes to `CONTRIBUTING.md`

TBH, I don't really know how to update `CONTRIBUTING.md`, it's clear and correct to say "with the rest of the summary matching the original PR." It's the merger's job to remove the `---`, not the backport sender. There's nothing wrong with keeping the `---` in a backport PR.

2023-02-15 11:42 UTC, a1012112796 commented on .github/pull_request_template.md
> +2. Make sure you have read contributing guidelines: https://github.com/go-gitea/gitea/blob/main/CONTRIBUTING.md .
```suggestion
2. Make sure you have read [contributing guidelines](CONTRIBUTING.md) .
```

wonder why use a full link here?

2023-02-21 00:13 UTC, techknowlogick approved these changes

2023-02-21 00:14 UTC, merged

2023-02-28 15:43 UTC, yardenshoham commented
Again, why I think the first comment is better than `---` https://github.com/go-gitea/gitea/commit/443dcc2db0676cae8b1b72c1b0b99e675c21177c