Only update needed columns when update user
go-gitea/gitea pull request #2296
Opened 2017-08-11 13:04 UTC by lunny

Also fix #1882. After this merged, I will back ported to branch release/v1.1.

2017-08-11 15:29 UTC, sapk commented on models/user.go
> +	u.Email = strings.ToLower(u.Email)
Can't we iterate over cols array and with a switch only do needed operation want matching col ?

Example : https://play.golang.org/p/PFVkvT3JYg

u.Email = strings.ToLower(u.Email)

2017-08-11 18:14 UTC, ethantkoenig requested changes

2017-08-11 18:14 UTC, ethantkoenig commented on models/user.go
> +	_, err := x.Id(u.ID).Cols(cols...).Update(u)
The `updated_unix` column won't be updated. I think we need to do something similar to https://github.com/go-gitea/gitea/pull/2204

2017-08-11 18:17 UTC, ethantkoenig commented
Adding a new function seems like overkill to me, is there a reason we can't just fix the `updateUser(..)` function to not write to `u.Avatar` (and require the caller of `updateUser()` to update `u.Avatar` if they actually need it)?

2017-08-11 21:24 UTC, sapk commented
@ethantkoenig We could  add a new func generateAvatar that is call before updateUser only when email is change or needed ?

2017-08-12 01:26 UTC, lunny commented
@ethantkoenig I think `updateUser` is not corrected in many place where only need to update serval columns but update all the columns. So I added a new function `updateUserCols` to do that. And there are still some place where we should use `updateUser` to update all the columns.
We cannot finish the work only improve `updateUser` function, so I create the new one.
For fix of #1882, it's not the PR's main idea. #1882 's problem is when user login, the avatar will be updated, so the avatar changed. In fact, the only needed change column on login is `last_login_time` but it update all the columns. When I change to `updateUserCols`, the bug is also fixed.

2017-08-12 01:29 UTC, lunny commented on models/user.go
> +	_, err := x.Id(u.ID).Cols(cols...).Update(u)
done.

2017-08-12 01:30 UTC, lunny commented on models/user.go
> +	u.Email = strings.ToLower(u.Email)
Didn't get what you mean.

2017-08-12 01:37 UTC, ethantkoenig approved these changes

2017-08-12 02:10 UTC, lunny commented
@sapk that could be another PR.

2017-08-12 02:30 UTC, ethantkoenig commented
LGTM

2017-08-12 05:00 UTC, lafriks commented
LGTM

2017-08-12 05:05 UTC, lafriks commented
Make LG-TM work

2017-08-12 12:06 UTC, sapk commented on models/user.go
> +	u.Email = strings.ToLower(u.Email)
Maybe it is overkill
```
// UpdateUserCols update user according special columns
func UpdateUserCols(u *User, cols ...string) error {
	//Format only when needed
	for _, v := range cols {
		switch v {
		case "email":
			// Organization does not need email
			u.Email = strings.ToLower(u.Email)
			if !u.IsOrganization() {
				if len(u.AvatarEmail) == 0 {
					u.AvatarEmail = u.Email
				}
			}
		case "name":
			u.LowerName = strings.ToLower(u.Name)
		case "location":
			u.Location = base.TruncateString(u.Location, 255)
		case "website":
			u.Website = base.TruncateString(u.Website, 255)
		case "description":
			u.Description = base.TruncateString(u.Description, 255)
		}
	}
	if !u.IsOrganization() {
		if len(u.AvatarEmail) > 0 {
			u.Avatar = base.HashEmail(u.AvatarEmail)
		}
	}
	_, err := x.Id(u.ID).Cols(cols...).Update(u)
	return err
}
```

2017-08-12 14:18 UTC, merged