CI: attempt to fix "push translations"
go-gitea/gitea pull request #22964
Opened 2023-02-18 04:05 UTC by 6543

https://drone.gitea.io/go-gitea/gitea/67531/1/4

-> https://github.com/appleboy/drone-git-push/blob/master/DOCS.md ?

2023-02-18 10:17 UTC, delvh commented
> fatal: couldn't find remote ref refs/pull/22964/head

Interesting.

2023-02-18 15:03 UTC, yardenshoham commented
BTW this branch is open on upstream

2023-02-24 15:05 UTC, yardenshoham commented
Can you close this and open one from a fork?

2023-02-24 22:29 UTC, appleboy requested changes

2023-02-24 22:29 UTC, appleboy commented on .drone.yml
> -    environment:
Just replace `appleboy/drone-git-push` with `appleboy/drone-git-push:linux-amd64`

2023-02-25 02:24 UTC, appleboy commented on .drone.yml
> -    environment:
@6543 I will update the latest image with multiple platforms.

2023-02-25 05:12 UTC, appleboy commented
@6543 Can you help to restart the build? I already fixed the issue. See https://hub.docker.com/layers/appleboy/drone-git-push/latest/images/sha256-66e30db1203e9b9fe6400d2471630c0c5cfe25dad8217ef48901cc55e21720f3?context=repo

2023-03-31 07:36 UTC, lunny commented
I think this pull request could be closed now because the push translations has been resolved. @6543

2023-04-07 10:09 UTC, closed without merging