Improve squash merge commit author and co-author with private emails
go-gitea/gitea pull request #22977
Opened 2023-02-18 22:23 UTC by brechtvl

When emails addresses are private, squash merges always use `@noreply.localhost` for the author of the squash commit. And the author is redundantly added as a co-author in the commit message.

Also without private mails, the redundant co-author is possible when committing with a signature that's different than the user full name and primary email.

Now try to find a commit by the same user in the list of commits, and prefer the signature from that over one constructed from the account settings.

2023-02-24 21:20 UTC, techknowlogick requested changes
Thanks for the PR :)
LGTM, just need to confirm it doesn't potentially leak private emails from web interface prior to approval.

2023-02-24 22:01 UTC, brechtvl commented
Thanks. And to state the obvious, the signature used in commits is already public information and preserved when using a merge commit or rebase as the merge style. So using it for the squash case as well does not expose private information.

2023-03-07 21:27 UTC, techknowlogick approved these changes

2023-03-07 21:27 UTC, techknowlogick commented
Thanks for your patience @brechtvl 🙏

2023-03-09 04:03 UTC, lunny commented on services/pull/merge_squash.go
> +			commitUser, _ := user_model.GetUserByEmail(ctx, commit.Author.Email)
We could cache the users by email so that we could not load it from database again.

2023-03-10 02:19 UTC, lunny approved these changes

2023-03-10 03:17 UTC, merged

2024-12-28 08:54 UTC, wxiaoguang commented
@brechtvl would you like to take a look at   Squash in PR with co-authored #31980  and Fix duplicate co-author in squashed merge commit messages #33020  ?