Add word-break to sidebar-item-link
go-gitea/gitea pull request #23146
Opened 2023-02-25 10:04 UTC by yp05327

Fixes https://github.com/go-gitea/gitea/issues/22953
![image](https://user-images.githubusercontent.com/18380374/221351117-1e4b8922-04ca-4717-8e3b-c338a61bc062.png)

2023-02-25 10:05 UTC, delvh approved these changes
Yep, that's one approach.
The other would have been to use overflow.
I'm fine with both.

2023-02-25 10:09 UTC, yardenshoham approved these changes
Very good!
![image](https://user-images.githubusercontent.com/20454870/221351333-cefddf55-da83-4b4d-97cb-2d306bb87206.png)

2023-02-25 10:11 UTC, yardenshoham commented
Should we backport to v1.18?

2023-02-25 11:37 UTC, silverwind requested changes
`overflow-wrap: break-word` should be preferred over `word-break: break-all` because the former results in better breaking where it will first look for natural break opportunities (whitespace) and only break inside a word as last-resort.

2023-02-25 11:51 UTC, silverwind commented
https://jsfiddle.net/silverwind/jy9v0r4d/ to show the difference between the two.

2023-02-25 11:51 UTC, silverwind commented on web_src/less/_repository.less
> +  word-break: break-all;
```suggestion
  overflow-wrap: break-word;
```

2023-02-25 12:01 UTC, silverwind commented
Actually, I think `word-break` is fine, reason being that its style of line breaking may be preferred in programming context because that's how editors usually wrap code as well:

<img width="112" alt="image" src="https://user-images.githubusercontent.com/115237/221355714-a0475c9b-84a6-4bcc-83e0-de26e15e8945.png">

<img width="107" alt="image" src="https://user-images.githubusercontent.com/115237/221355724-97b8a506-db78-4d8c-8d0c-833bf13f592b.png">

First case acutally looks better to me, being used to how editors break lines.

2023-02-25 12:02 UTC, silverwind approved these changes

2023-02-25 12:04 UTC, yp05327 commented
@silverwind 
I found that there were some places using them both. I'm not familiar with css, is it possible (or correct?) to use them both?
![image](https://user-images.githubusercontent.com/18380374/221355660-e013213c-eea3-4c24-a4d5-21c09ffb3b12.png)
![image](https://user-images.githubusercontent.com/18380374/221355684-22cf8551-2f2e-4e4e-aac1-5cb47ea308e0.png)

2023-02-25 14:43 UTC, silverwind commented
Can do such corrections in another PR. Having both `overflow-wrap: break-word` and `word-break: break-all` will probably result in soft-break style word breaks so the `word-break` has no effect and can be removed.

 Whether one or the other is to be used depends on context. If the text to be broken is prose, it should use `overflow-wrap`, otherwise `word-break` is an option in cases where hard breaks are acceptable.

2023-02-26 16:36 UTC, yardenshoham commented
Build failure unrelated

2023-02-27 20:19 UTC, techknowlogick commented
ping LG-TM bot

2023-02-27 20:19 UTC, merged