Pass --global when calling `git config --get`, for consistency with `git config --set`
go-gitea/gitea pull request #23157
Opened 2023-02-26 04:19 UTC by philip-peterson

This arose out of #22451; it seems we are checking using non-global settings to see if a config value is set, in order to decide whether to call another yes-global configuration command. This PR changes it so that both the check and the set are for global configuration.

2023-02-26 10:45 UTC, delvh approved these changes

2023-02-26 19:34 UTC, kdumontnu approved these changes
I think this fixes the primary issue. Thanks!

We also need to be careful in the future and maybe set `--git-dir` (or `--work-tree`?) for some commands too.. specifically, I think I was having issues in #22451 because gitea was using my

2023-02-28 00:36 UTC, techknowlogick requested changes, later dismissed
Blocking per @kdumontnu's comment. I agree that this LGTM and could be merged (mergers feel free to dismiss), but having had tools that work with git override my global git config unintentionally, the suggestion of adding in path to the config that is attempting to be changed is a good one.

2023-02-28 00:50 UTC, philip-peterson commented
I'm still trying to understand the ask here, which Git commands should use `--git-dir` or `--work-tree`? I wasn't able to repro any issues so if someone could provide a use-case for where this isn't the ideal situation that might help me understand.

2023-02-28 01:01 UTC, wxiaoguang commented
> Blocking per @kdumontnu's comment. I agree that this LGTM and could be merged (mergers feel free to dismiss), but having had tools that work with git override my global git config unintentionally, the suggestion of adding in path to the config that is attempting to be changed is a good one.



No, it won't override your global git config.

https://git-scm.com/book/en/v2/Getting-Started-First-Time-Git-Setup

> The next place Git looks is the ~/.gitconfig (or ~/.config/git/config) file, which is specific to each user. You can make Git read and write to this file by passing the --global option.

2023-02-28 01:02 UTC, kdumontnu commented
> Blocking per @kdumontnu's comment. I agree that this LGTM and could be merged (mergers feel free to dismiss), but having had tools that work with git override my global git config unintentionally, the suggestion of adding in path to the config that is attempting to be changed is a good one.

I'm not sure that was my intention with the comment. I think this PR is correct and complete. Since we already use the git config file from [`%(APP_DATA_PATH)s/home`](https://docs.gitea.io/en-us/config-cheat-sheet/#git-git) we won't modify the host global gitconfig. 

What I meant is that for some git commands (including the ones in the ones affected by this PR), the workdir config settings will override the global settings. 

Essentially, the issue I found in https://github.com/go-gitea/gitea/pull/22451 I believe was due to the combination of two potential bugs:
- `configUnsetAll` was using `DefaultContext, "config", "--get"` without the `"--global"` flag, so it was evaluating to "true", then trying to unset the value in my global config file (the one in `%(APP_DATA_PATH)s/home`), but then couldn't find it.
  - This PR fixes that issue
- BUT, why was `DefaultContext, "config", "--get"` evaluating to true in the first place? It could be because my system config file was set to `true` (but nope, I checked that). 
  - It is because my local `.git` config from this repo had the value set to true. So my theory is that somehow the git function we were using

2023-02-28 01:54 UTC, kdumontnu commented
Okay, to show the potential impact of the second issue in the comment above:
- Add the following lines at the beginning of `func configSet`
```
	fmt.Println("============= SET ==============")
	// local config will take precedence
	stdout, _, _ := NewCommand(DefaultContext, "config", "--get", "user.email").RunStdString(nil)
	fmt.Printf("user.email: %s\n", stdout)
```
(yeah, I could upload a patch file, but this is easier 😄 )
- from your local gitea dev repo
```
kyle@kyle-PC ~/1-develop/gitea (peterson/not-global) $ git config --get --local user.email
kyle@kyle-PC ~/1-develop/gitea (peterson/not-global) $ echo $?
1
```
Makes sense, no email is set in my local config ✔️ 
- Start the server and observe:
```
============= SET ==============
user.email: gitea@fake.local
```
This is the default email address gitea uses ✔️ 
- Change a local config setting:
```
kyle@kyle-PC ~/1-develop/gitea (peterson/not-global) $ git config --local user.email test@email.com
kyle@kyle-PC ~/1-develop/gitea (peterson/not-global) $ git config --get --local user.email
test@email.com
kyle@kyle-PC ~/1-develop/gitea (peterson/not-global) $ tail -n2 .git/config 
[user]
        email = test@email.com
```
- Rerun the server and observe:
```
============= SET ==============
user.email: test@email.com
```
😮 

This test case is rather benign, but imaging you have cloned gitea and are running gitea from that directory - this could lead to some strange issues, like I observed above.

2023-02-28 21:26 UTC, jolheiser commented
🎺 🤖

2023-02-28 21:26 UTC, merged

2023-03-06 04:05 UTC, philip-peterson commented
@kdumontnu I looked into your example. The thing is, it calls `git config` without `--global`, which AFAIK wherever that happens in Gitea, it's done inside of a specific repo as the CWD. I'm not sure I see an issue at this point, but maybe if you have a repro case you can open a new issue and mention this PR?