Cleanup the output from the gitea internal hooks
go-gitea/gitea pull request #23389
Opened 2023-03-09 09:01 UTC by adlternative

Some gitea hook output "Processing 2 references" is a little noisy, so let's cleanup them.

v1. 
Remove all hook output logic.

v2.
Just turn off VerbosePush setting to suppress output.

Want to fix #23364

2023-03-09 13:01 UTC, lunny requested changes

2023-03-09 13:01 UTC, lunny commented on cmd/hook.go
> -	if setting.Git.VerbosePush {
you can set the setting as false.

2023-03-09 13:12 UTC, adlternative commented on cmd/hook.go
> -	if setting.Git.VerbosePush {
> you can set the setting as false.

You mean that we should turn off the this setting & keep all the output here?
Or turn off the this setting & cleanup these output at the same time?

2023-03-09 14:56 UTC, lunny commented on cmd/hook.go
> -	if setting.Git.VerbosePush {
I mean, maybe this PR is unnecessary. You can disable that output via setting `[git]\nVERBOSE_PUSH=false`?

2023-03-10 05:45 UTC, adlternative commented on cmd/hook.go
> -	if setting.Git.VerbosePush {
OK, I will close this PR.

2023-03-10 05:45 UTC, closed without merging