Imrove scroll behavior to hash issuecomment(scroll position, auto expand if file is folded, and on refreshing) (#23513)
go-gitea/gitea pull request #23540
Opened 2023-03-17 10:25 UTC by GiteaBot

Backport #23513 by @HesterG

Close #23466
Right now on pull request "files Changed" tab, if a file is viewed, when the comments' links are visited, the comment will not be shown as the file is folded after viewed. This PR is to improve the behavior, to make the comment seen even the related file is folded, like on github.

And right now scroll position will be remembered and hence it won’t scroll to hashed comment after refreshing, this PR also adjust the scroll position remembering behavior: When there is hash comment in url, do not remember the scroll position.

Before:

https://user-images.githubusercontent.com/17645053/225512079-6cf79581-9346-44cf-95d6-06919642e6a8.mov

After:

https://user-images.githubusercontent.com/17645053/225523753-3f6728f2-977b-4ed0-a65c-63dcef2ace80.mov

Update - long comment's behavior after using `scrollTop ` (Comment div scroll to the position which is 30px below the diff header, or 30px below top on conversation tab):

https://user-images.githubusercontent.com/17645053/225614460-0602c1a6-229c-41f4-84d2-334e78251486.mov

2023-03-17 20:15 UTC, silverwind requested changes
Blocking because this introduces a regression, see https://github.com/go-gitea/gitea/pull/23513#issuecomment-1474356817.

2023-03-17 20:21 UTC, silverwind approved these changes
Unblocking, regression is not from this PR.

2023-03-18 01:04 UTC, lunny approved these changes

2023-03-18 02:22 UTC, techknowlogick commented
ping lg-tm

2023-03-18 02:59 UTC, merged