Fix pagionation on `/notifications/watching` page
go-gitea/gitea pull request #23564
Opened 2023-03-18 18:42 UTC by silverwind

The `q` parameter was not rendered in pagination links because `Pagination:AddParam` checks for existance of the parameter in `ctx.Data` where it was absent. Added the parameter there to fix it.

2023-03-18 18:46 UTC, delvh approved these changes

2023-03-20 20:20 UTC, yardenshoham requested changes
To avoid duplication you could use `keyword` instead of `ctx.FormTrim("q")` in https://github.com/go-gitea/gitea/blob/529bac1950adf4fb72433cb67f66b0eec49224fe/routers/web/user/notification.go#L381

2023-03-20 20:45 UTC, yardenshoham approved these changes

2023-03-21 00:43 UTC, jolheiser commented
🎺 🤖

2023-03-21 01:07 UTC, merged