Rename actions unit to `repo.actions` and add docs for it
go-gitea/gitea pull request #23733
Opened 2023-03-27 06:10 UTC by wolfogre

I neglected that the `NameKey` of `Unit` is not only for translation, but also configuration. Should be `repo.actions` to maintain consistency.

## :warning: BREAKING :warning:

If users already use `actions.actions` in config file, it will be treated as invalid unit key.

2023-03-27 06:23 UTC, lunny approved these changes

2023-03-27 08:31 UTC, delvh approved these changes
The good thing is:
Since it was previously undocumented, there likely aren't a lot of affected users.
I mean, I myself didn't know that this was possible, and I reviewed the original PR and have gotten somewhat familiar with the code base :sweat_smile:

2023-03-27 08:31 UTC, delvh commented on models/unit/unit.go
> -		"actions.actions",
Can we delete this source string now?

2023-03-27 08:44 UTC, yardenshoham commented
Backporting a breaking PR?

2023-03-27 10:44 UTC, wolfogre commented on models/unit/unit.go
> -		"actions.actions",
It has been used elsewhere.

2023-03-27 10:55 UTC, wxiaoguang commented
We have the `backport-locales.go`, so I guess backporting some translations are feasible now.

2023-03-27 21:01 UTC, techknowlogick requested changes, later dismissed
Blocking, as we shouldn't be backporting breaking changes. Is there a way to make the previous option an alias for the update option?

2023-03-27 23:51 UTC, lunny commented
> Blocking, as we shouldn't be backporting breaking changes. Is there a way to make the previous option an alias for the update option?

Since we have said actions is an experiment feature in v1.19, I think we could change it directly.

BTW: maybe we should also update `repo_unit` table? @wolfogre

2023-03-28 01:26 UTC, yp05327 commented
Just a question. Is it necessary/possible to change `action_XXX` to `repo_action_XXX` in db too, as we also have `activities.action` which has `action` table in db.

2023-03-28 01:40 UTC, lunny commented
> 

It should be another PR. Maybe we can rename the old table `action` to another name.

2023-03-28 03:08 UTC, wolfogre commented
> BTW: maybe we should also update `repo_unit` table?

@lunny 

Update what?

```go
type RepoUnit struct { //revive:disable-line:exported
	ID          int64
	RepoID      int64              `xorm:"INDEX(s)"`
	Type        unit.Type          `xorm:"INDEX(s)"`
	Config      convert.Conversion `xorm:"TEXT"`
	CreatedUnix timeutil.TimeStamp `xorm:"INDEX CREATED"`
}
```

It doesn't use the key string, just `unit.Type`. And if an existing repo has Actions enabled, we shouldn't touch it.

2023-03-28 03:32 UTC, wxiaoguang commented
By the way, there is another strong reason about why this "breaking" could be backported: Gitea declares that the Actions feature is experimental, so it's not surprised that the stable release needs some "breaking" fixes for such experimental feature.

2023-03-29 06:34 UTC, lunny commented
@techknowlogick please review again. I think the break is just an option on the ini file from `actions.actions` to `repo.actions`. @wolfogre

2023-04-03 03:30 UTC, 6543 commented
also ok with backpor that ...

2023-04-03 04:05 UTC, merged