Improve issue search
go-gitea/gitea pull request #2387
Opened 2017-08-25 03:08 UTC by ethantkoenig

Make improvements to issue search:
- Add support for searching comment contents
- Add unicode normalization and tokenization
- Move indexer specific code out of models and into a separate module (where it can potentially be reused in the future)
- Update bleve dependency
- Add integration tests for issue search

2017-08-30 14:21 UTC, lunny commented
It seems new issue on sqlite wasn't indexed.

2017-09-09 23:33 UTC, ethantkoenig commented
@lunny Fixed

2017-09-16 10:35 UTC, lunny commented
LGTM

2017-09-16 12:20 UTC, lafriks requested changes

2017-09-16 12:20 UTC, lafriks commented on integrations/pgsql.ini.tmpl
> +ISSUE_INDEXER_PATH = integrations/indexers/issues.bleve
Do not use same path for mysql, pgsql and sqlite as they will conflict when run in parallel

2017-09-16 16:23 UTC, ethantkoenig commented
@lafriks Good catch, fixed

2017-09-16 17:12 UTC, lafriks approved these changes

2017-09-16 17:13 UTC, lafriks commented
Would be great if these directories would also be added to `make clean` but otherwise LGTM

2017-09-16 17:26 UTC, lafriks approved these changes

2017-09-16 17:26 UTC, lafriks commented
make LG-TM work

2017-09-16 20:16 UTC, merged