Update hard-coded version to 1.2.0+dev
go-gitea/gitea pull request #2390
Opened 2017-08-25 10:09 UTC by strk

2017-08-25 10:12 UTC, strk commented
Sorry this is for 1.3.0+dev (force-pushed).
Will follow PR for 1.2 branch too

2017-08-25 10:23 UTC, lunny commented
How about 1.3.0-dev since it's target is 1.3.0 but isn't reach.

2017-08-25 10:33 UTC, strk commented
I'm still confused about + vs -
Before the change we used +
What's the difference, semantically ?

Will 1.3.0-dev be older than 1.3.0 ?
Will 1.3.0+dev be newer than 1.3.0 ?

2017-08-25 12:33 UTC, sapk requested changes

2017-08-25 12:33 UTC, sapk commented on integrations/version_test.go
> +	setting.AppVer = "1.3.0+dev"
I think you forget to update this like the main.go

2017-08-25 12:44 UTC, strk commented
I realized that the test doens't need to match the hard-coded version.
I'm actually tempted to use "test" in there instead, to avoid the
confusion (and I guess that test could test at least two versions...)

2017-09-03 06:23 UTC, lunny commented
It seems when we build via `TAGS="bindata" make generate build`, the version is still `Gitea version 1.1.0+534-g0307707ca built with: bindata`.

2017-09-03 21:12 UTC, strk commented
That's because the Makefile rule generates version via `git describe`,
which does not read the hard-coded version number in source code.

If you want a better description there, you can add a 1.3 tag 
pointing to the first commit which got into master branch, ie:

  git tag 1.3 a915a09e4f8edc7734c9374ad9f9a51b39241ee3

2017-09-04 01:53 UTC, lunny commented
So what's the meaning of the hard-code?

2017-09-04 07:54 UTC, strk commented
It's for when you `go get` or `go build`, or build from sources
(outside of a git repository).

This PR does not change policy, just fixes its current application

2017-09-09 01:48 UTC, ethantkoenig commented
LGTM

2017-09-26 10:14 UTC, strk commented
@lunny so is this good to merge now ?

2017-10-10 17:46 UTC, Morlinest commented
Shouldn't be version set only when you add tag? Now it should be `v1.2.0-dev` (or `v1.2.x-dev`) till next minor/major release.

2017-10-12 06:32 UTC, lunny commented
For master, I suggest always use `-` but `+`. It should be `v1.3.0-dev` means next release is v1.3.0

2017-10-12 06:35 UTC, daviian commented
LGTM

2017-10-12 11:40 UTC, merged