testing please ignore
go-gitea/gitea pull request #24309
Opened 2023-04-24 16:24 UTC by yardenshoham

Please check the following:
1. Make sure you are targeting the `main` branch, pull requests on release branches are only allowed for backports.
2. Make sure you have read contributing guidelines: https://github.com/go-gitea/gitea/blob/main/CONTRIBUTING.md .
3. Describe what your pull request does and which issue you're targeting (if any).
4. It is recommended to enable "Allow edits by maintainers", so maintainers can help more easily.
5. Your input here will be included in the commit message when this PR has been merged. If you don't want some content to be included, please separate them with a line like `---`.
6. Delete all these tips before posting.

2023-04-24 16:26 UTC, techknowlogick approved these changes, later dismissed

2023-04-24 16:26 UTC, delvh approved these changes

2023-04-24 16:29 UTC, delvh requested changes
I can't allow this

2023-04-24 16:30 UTC, techknowlogick requested changes

2023-04-24 16:30 UTC, techknowlogick commented on .air.toml
> +
```suggestion
```

2023-04-24 16:32 UTC, techknowlogick approved these changes, later dismissed

2023-04-24 16:35 UTC, techknowlogick approved these changes

2023-04-24 16:35 UTC, techknowlogick requested changes, later dismissed
changes required

2023-04-24 16:38 UTC, silverwind approved these changes

2023-04-24 16:41 UTC, silverwind requested changes, later dismissed
need changes

2023-04-24 16:44 UTC, jolheiser approved these changes

2023-04-24 16:46 UTC, jolheiser requested changes, later dismissed
❌

2023-04-24 16:46 UTC, yardenshoham commented
Closing because maintainers are sending me mixed signals

2023-04-24 19:18 UTC, yardenshoham commented
Gonna test some stuff here, I don't want to open another PR so feel free to unsubscribe

2023-04-24 19:40 UTC, pat-s approved these changes
42

2023-04-28 22:24 UTC, delvh requested changes, later dismissed
Still a hard no.

2023-04-28 22:24 UTC, jolheiser requested changes
no

2023-04-28 22:25 UTC, jolheiser requested changes, later dismissed
still no

2023-04-28 22:28 UTC, jolheiser requested changes
actually....no

2023-04-28 22:28 UTC, delvh submitted a review, later dismissed
Perhaps?

2023-04-28 22:29 UTC, jolheiser approved these changes

2023-04-28 22:31 UTC, jolheiser requested changes
nah

2023-04-28 22:32 UTC, yardenshoham commented
i'm so confused, hostile project i'm out

2023-04-28 22:32 UTC, closed without merging