Rename the swagger /markdown/raw `operationId` from `renderMarkdownRaw` to `renderRawMarkdown`
go-gitea/gitea pull request #24432
Opened 2023-04-29 19:44 UTC by yardenshoham

- Fixes #19025

To allow for code generation. See https://github.com/OpenAPITools/openapi-generator/issues/11827 for the reason a method ends with `Raw` breaks code generation.

## :warning: BREAKING :warning:

Previously generated API clients that used `renderMarkdownRaw` will break unless they regenerate and use `renderRawMarkdown`

2023-04-29 20:54 UTC, silverwind approved these changes

2023-04-29 22:12 UTC, delvh reviewed
I am quite unsure if I can approve this PR or not:
1. I haven't entirely understood how that breaks previously generated API clients but I'll assume it to be true.
2. I don't think it's our responsibility to fix that kind of bug. That sounds like an OpenAPI-specific bug
3. I don't like introducing a breaking change for this reason 
4. On the other hand, it is also nice if we can fix this bug in a (to me) relatively unintrusive way.

2023-04-30 01:11 UTC, techknowlogick requested changes
blocking for discussion's sake.

2023-04-30 15:17 UTC, silverwind commented
I don't understand where this "Raw" suffix issue originates but we may as well stamp it off as a bug in that code generator and close it.

2023-04-30 15:31 UTC, yardenshoham commented
Fair enough

2023-04-30 15:31 UTC, closed without merging