Don't run build and test if only docs changed
go-gitea/gitea pull request #24530
Opened 2023-05-05 01:34 UTC by lunny

As title.

2023-05-05 14:25 UTC, lunny commented
> Seems fine with me, but I'm not sure how the "required checks" will work if we skip the required checks.

Ah, yes. Gitea actions will also encounter this like problem.

2023-05-05 19:15 UTC, yardenshoham commented
> Seems fine with me, but I'm not sure how the "required checks" will work if we skip the required checks.

Relevant documentation page: https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-protected-branches/troubleshooting-required-status-checks#handling-skipped-but-required-checks

2023-05-14 14:09 UTC, yardenshoham approved these changes

2023-05-14 18:54 UTC, techknowlogick approved these changes

2023-05-14 18:55 UTC, techknowlogick commented on .github/workflows/pull-db-tests-docsignore.yml
> +  test-pgsql:
We need other DB tests to have no build required either

2023-05-14 18:56 UTC, techknowlogick commented on .github/workflows/pull-db-tests-docsignore.yml
> +      - run: echo "No build required"'
extra `'` at the end of this line

2023-05-14 18:56 UTC, techknowlogick requested changes
few minor things

2023-05-14 18:56 UTC, techknowlogick commented on .github/workflows/pull-compliance-docsignore.yml
> +      - run: echo "No build required"'
here too

2023-05-14 18:56 UTC, techknowlogick commented on .github/workflows/pull-docker-dryrun-docsignore.yml
> +      - run: echo "No build required"'
here too

2023-05-14 18:56 UTC, techknowlogick commented on .github/workflows/pull-e2e-tests-docsignore.yml
> +      - run: echo "No build required"'
here too

2023-05-16 02:26 UTC, techknowlogick approved these changes

2023-05-16 02:53 UTC, merged

2023-05-16 19:19 UTC, yardenshoham commented
Check https://github.com/go-gitea/gitea/pull/24757

2023-05-22 18:05 UTC, silverwind commented
This has some kind of regression where docs build no longer runs for PRs:

PR build was skipped:

https://github.com/go-gitea/gitea/actions/runs/5039932080/jobs/9038389389

It failed on main when landed:

https://github.com/go-gitea/gitea/actions/runs/5040058905/jobs/9038577074

2023-05-22 18:12 UTC, silverwind commented
@lunny revert this? It obviously wasn't tested enough, and I'd rather run too many actions than too few.

2023-05-22 23:46 UTC, lunny commented
> @lunny revert this? It obviously wasn't tested enough, and I'd rather run too many actions than too few.

We can't test it unless we merge it. I think the problem is at `compliance-docs`, I ever have a discuss with @techknowlogick at https://github.com/go-gitea/gitea/pull/24761#discussion_r1195827815.

2023-05-23 08:15 UTC, silverwind commented
Besides it not working, there is more wrong with this PR:

- A clean design should not need workflows that do nothing
- It introduced duplicate workflow names, making the actions overview confusing:

<img width="130" alt="image" src="https://github.com/go-gitea/gitea/assets/115237/b6c40df4-1d3e-4f11-be74-168af7b59996">

So I would still go for a clean revert.

BTW, in theory you can test locally with https://github.com/nektos/act.

2023-05-23 08:20 UTC, lunny commented
> Besides it not working, there is more wrong with this PR:
> 
>     * It introduced duplicate workflow names, making the workflow overview confusing.
> 
>     * A clean design should not need workflows that do nothing
> 
> 
> <img alt="image" width="130" src="https://user-images.githubusercontent.com/115237/240187626-b6c40df4-1d3e-4f11-be74-168af7b59996.png">
> 
> So I would still go for a clean revert.
> 
> BTW, in theory you can test locally with https://github.com/nektos/act.

The change is based on https://github.com/go-gitea/gitea/pull/24530#issuecomment-1536670068

2023-05-23 08:28 UTC, silverwind commented
Seems like a huge hack. I'm surprised GH docs even recommend it. Maybe it could still be one workflows and the skip condition could be determined via a shell script instead.