[API] Pull Requests
go-gitea/gitea pull request #248
Opened 2016-11-25 01:02 UTC by bkcsoft

Add Pull-Request API

Migrated and Rebased from https://github.com/gogits/gogs/pull/3755

2016-11-25 01:05 UTC, bkcsoft commented
Had to update the vendored `code.gitea.io/sdk` since it uses new stuff :slightly_smiling_face:

2016-11-25 01:10 UTC, bkcsoft commented on modules/context/api.go
> +// ReferencesGitRepo ... I have no clue what this does :laughing:
Anyone wanna have a crack at guessing what this function does? :laughing:

2016-11-25 01:21 UTC, lunny requested changes

2016-11-25 01:21 UTC, lunny commented on models/error.go
> +type ErrPullRequestAlreadyExists struct {
golint

2016-11-25 01:21 UTC, lunny commented on routers/api/v1/repo/pull.go
> +// Copyright 2015 The Gogs Authors. All rights reserved.
comment :)

2016-11-27 03:05 UTC, bkcsoft commented on routers/api/v1/repo/pull.go
> +// Copyright 2015 The Gogs Authors. All rights reserved.
Right, I'm not entirely sure if we can just change it, since I'm not the original author of this... @lstahlman is IIRC

2016-12-01 09:43 UTC, bkcsoft commented
There, fixed the things @lunny said, should be good for merging :)

2016-12-01 09:50 UTC, tboerger commented
LGTM

2016-12-01 10:27 UTC, Bwko commented
LGTM

2016-12-01 10:40 UTC, lunny approved these changes

2016-12-02 07:26 UTC, bkcsoft commented
Builds are failing because of Linting, Need to so some final testing before this goes into master though...

2016-12-02 10:00 UTC, bkcsoft commented
Builds are green! 😄

2016-12-02 10:26 UTC, bkcsoft commented
Verified that it works using the (currently under development) Gitea-importer in GitLab :)

2016-12-02 10:44 UTC, strk commented
So drop the status/wip label ? :)

2016-12-02 11:10 UTC, bkcsoft commented
@strk since it was "Green" I tacked on the wip-label so no-one accidentally merged it 😛

2016-12-02 11:10 UTC, merged

2016-12-02 11:12 UTC, strk commented
Ops, an accident occurred ! 
(please change the Milestone back to 1.0.0, it will help generating the CHANGELOG...)