add codecov.io service.
go-gitea/gitea pull request #2493
Opened 2017-09-12 02:15 UTC by appleboy

Add codecov.io coverage service. See https://codecov.io/gh/go-gitea/gitea

2017-09-12 02:19 UTC, appleboy commented on Makefile
> +		grep -h -v "^mode:" pkg.coverage.out >>  coverage.all;\
Just add this line and convert space to tabs.

2017-09-12 05:30 UTC, tboerger commented
Drone will get integrated coverage with 0.9

2017-09-12 05:31 UTC, lunny commented
@tboerger we can convert back when drone 0.9 is ready.

2017-09-12 06:30 UTC, ethantkoenig commented
FYI, `make coverage` is not run in CI as of #2492.

2017-09-12 06:32 UTC, appleboy commented
@ethantkoenig Yes. it will be fixed in this commit: https://github.com/go-gitea/gitea/pull/2493/commits/18ef72f6be28e65bf454f93b17b829aba761df5c

2017-09-12 06:56 UTC, lafriks commented
In generate_coverage there are lot of errors like `failed to parse profiles: open /srv/app/src/code.gitea.io/gitea/coverage.out: no such file or directory`

2017-09-12 07:24 UTC, lafriks approved these changes

2017-09-12 07:44 UTC, appleboy commented
Only two conditions we need to generate the coverage report.

```
when:
   event: [ push ]
   branch: [ master ]
```

or 

```
when:
  event: pull_request
```

2017-09-12 09:21 UTC, tboerger requested changes

2017-09-12 09:21 UTC, tboerger commented on .drone.yml
> +  test-master:
Why do you separate master and pull requests?

2017-09-12 09:22 UTC, tboerger commented
You can combine the conditions when event: push, pull_request and branch: master are combined it triggers for pushs on master AND pull requests against master.

2017-09-12 09:23 UTC, tboerger commented
Ah and beside that I would name the steps the same since anyway only one of them should be executed per build

2017-09-12 14:45 UTC, appleboy commented
@tboerger Done

2017-09-12 14:49 UTC, bkcsoft approved these changes

2017-09-12 14:49 UTC, bkcsoft commented
LGTM

2017-09-13 08:54 UTC, tboerger approved these changes

2017-09-13 08:54 UTC, tboerger commented
LGTM

2017-09-13 08:55 UTC, lafriks commented
@appleboy please rebase

2017-09-13 09:52 UTC, lafriks commented
Your makefile needs additional changes after my PR was merged to generate mysql.ini from mysql.ini.tmpl

2017-09-13 12:57 UTC, merged