更新服务设置无效的刷新方式 run-as-service-in-ubuntu.zh-cn.md
go-gitea/gitea pull request #25006
Opened 2023-05-30 15:03 UTC by yaoyingkeji

更新服务设置无效的刷新方式 run-as-service-in-ubuntu.zh-cn.md

2023-05-30 15:56 UTC, lunny approved these changes

2023-05-30 17:49 UTC, techknowlogick commented on docs/content/doc/installation/run-as-service-in-ubuntu.zh-cn.md
> +如果需要查看已有的服务，可以使用:
```suggestion

如果需要查看已有的服务，可以使用:

```

2023-05-30 17:49 UTC, techknowlogick commented on docs/content/doc/installation/run-as-service-in-ubuntu.zh-cn.md
> +如果想查看没被激活的服务文件怎么办呢？
```suggestion
如果想查看没被激活的服务文件怎么办呢？

```

2023-05-30 17:49 UTC, techknowlogick commented on docs/content/doc/installation/run-as-service-in-ubuntu.zh-cn.md
> +如果我们修改了一个服务文件，可是Systemd不知道，因为它缓存了一份服务，所以需要重新载入，否则它还是使用旧的。这个行为类似于service nginx reload，在这里是：
```suggestion
如果我们修改了一个服务文件，可是Systemd不知道，因为它缓存了一份服务，所以需要重新载入，否则它还是使用旧的。这个行为类似于service nginx reload，在这里是：

```

2023-05-30 17:49 UTC, techknowlogick commented on docs/content/doc/installation/run-as-service-in-ubuntu.zh-cn.md
> +最后，如果是删除服务文件的话，又不一样了，即使我们reload，Systemd已然可以使用自己缓存的服务文件，哪怕你用了daemon-reload更新。所以这时候要告诉Systemd，我们已经放弃不存在的服务文件了，让它也放弃自己缓存的那份：
```suggestion
最后，如果是删除服务文件的话，又不一样了，即使我们reload，Systemd已然可以使用自己缓存的服务文件，哪怕你用了daemon-reload更新。所以这时候要告诉Systemd，我们已经放弃不存在的服务文件了，让它也放弃自己缓存的那份：

```

2023-05-30 19:15 UTC, wxiaoguang requested changes
It doesn't read like an official document or manual.

1. It becomes different from the English version. If anything is important to maintain, the English version should be also be updated. Otherwise the translated contents would be lost in the future.
2. Many operations are basic systemd operations, it's not suitable for Gitea to cover more and more  systemd topics.
3. The sentences are too complex and not focused. For example, to tell users to do `daemon-reload`, the sentences could be as simple as: "If you modify the gitea.service file, you need to run `sudo systemctl daemon-reload` to make systemd reload the service config".

2023-12-25 19:41 UTC, denyskon commented
Can this be closed, or is there still need for this change?

2023-12-26 00:18 UTC, closed without merging