Add init support of orgmode document type on file view and readme
go-gitea/gitea pull request #2525
Opened 2017-09-17 03:22 UTC by lunny

will be part of #374 and replace #1527

2017-09-17 03:50 UTC, lunny commented
CI failed seems unrelated.

2017-09-18 14:58 UTC, JonasFranzDEV commented on modules/markup/orgmode/orgmode_test.go
> +const Repo = "gogits/gogs"
Why `gogits/gogs`?

2017-09-18 15:08 UTC, lunny commented on modules/markup/orgmode/orgmode_test.go
> +const Repo = "gogits/gogs"
No reason. Just copied from markdown test.

2017-09-20 03:29 UTC, ethantkoenig requested changes

2017-09-20 03:29 UTC, ethantkoenig commented on main.go
> +	_ "code.gitea.io/gitea/modules/markup/markdown"
Import order

2017-09-20 04:06 UTC, lunny commented on main.go
> +	_ "code.gitea.io/gitea/modules/markup/markdown"
done.

2017-09-20 05:08 UTC, ethantkoenig approved these changes

2017-09-20 23:31 UTC, sapk approved these changes

2017-09-20 23:32 UTC, sapk commented
LGTM

2017-09-21 03:18 UTC, lafriks commented
LGTM

2017-09-21 04:09 UTC, ethantkoenig approved these changes
LGTM, just two nits

2017-09-21 04:09 UTC, ethantkoenig commented on modules/markup/orgmode/orgmode_test.go
> +		assert.Equal(t, strings.TrimSpace(expected), strings.TrimSpace(string(buffer)))
nit: unnecessary cast of `buffer`

2017-09-21 04:09 UTC, ethantkoenig commented on modules/markup/orgmode/orgmode_test.go
> +		assert.Equal(t, strings.TrimSpace(expected), strings.TrimSpace(string(buffer)))
nit: unnecessary cast of buffer

2017-09-21 05:20 UTC, lunny commented
@ethantkoenig done.

2017-09-21 05:20 UTC, merged