Add password length check on install page
go-gitea/gitea pull request #25491
Opened 2023-06-24 12:36 UTC by earl-warren

- Resolves [#271](https://codeberg.org/forgejo/forgejo/issues/271)
- Ensure that the adminstrator password is at least `MIN_PASSWORD_LENGTH`.

2023-06-24 12:40 UTC, lunny approved these changes

2023-06-24 12:42 UTC, delvh approved these changes

2023-06-24 13:35 UTC, techknowlogick requested changes
Thanks for this PR. Could you add the min length the the html template too, so that it alerts users before they submit the form. Note that if they choose not to create an admin user then the restriction would need to be added dynamically.

2023-09-04 11:51 UTC, earl-warren commented
I'll re-open when and if these additional improvements are implemented. In the meantime if someone is motivated to do the work they are welcome to take this over.

2023-09-04 11:51 UTC, closed without merging