Show explanation if user cannot add new email
go-gitea/gitea pull request #25502
Opened 2023-06-25 13:08 UTC by n0toose

This change concerns the "Manage Email Addresses" submenu
in the Account settings.

2023-06-25 21:18 UTC, delvh approved these changes

2023-06-25 21:22 UTC, techknowlogick requested changes

2023-06-25 21:22 UTC, techknowlogick commented on options/locale/locale_en-US.ini
> +email_cant_add = You cannot add any new email addresses at this time. Please try again later.
Could you remove the "try again later"? As that may create confusion for the user, and they'll try to refresh the page without knowing why they can't add a new email. From the ticket you linked it sounds like the user hadn't verified their email yet.

2023-06-26 01:42 UTC, wxiaoguang commented
I do not think it is right to merge some "unclear" changes into code base.

I will figure out this problem by a new PR.

2023-06-26 02:07 UTC, wxiaoguang commented
I think I understand the problem now.

->  Clarify the reason why the user can't add a new email if there is a pending activation #25509

2023-06-26 02:34 UTC, techknowlogick commented
Thanks for this PR. I will close it in favour of the other PR.

2023-06-26 02:34 UTC, closed without merging