read-only checkboxes don't appear and don't entirely act the way one might expect
go-gitea/gitea pull request #25573
Opened 2023-06-28 22:46 UTC by saegl5

This pull request fades read-only checkboxes and checkmark, and it makes the checkboxes act more read-only/disabled by not changing the border-color when clicked.

Examples using light mode:
 
| Before | After |
| - | - |
| ![Kapture 2023-06-28 at 00 20 45](https://github.com/go-gitea/gitea/assets/63764270/0899fd5c-18a9-4290-9ba9-d3cf71033cf8) | ![Kapture 2023-06-28 at 00 23 12](https://github.com/go-gitea/gitea/assets/63764270/0db9be14-e16c-42ed-8fb1-999928fd1d25) |
| ![Kapture 2023-06-28 at 00 25 22](https://github.com/go-gitea/gitea/assets/63764270/65c6c380-b928-4e6c-b403-3655d3565896) | ![Kapture 2023-06-28 at 00 27 28](https://github.com/go-gitea/gitea/assets/63764270/d8c2a019-e07c-43a1-a7fa-93c0d4e01900) |
| | read-only checkboxes and checkmark are faded<br>and the checkboxes act more read-only/disabled |

Fixes/Closes/Resolves #25076

2023-06-28 23:27 UTC, saegl5 commented
Not sure how to report lint and test workflows. \
I have run `make mint` and `make test-e2e`, so far and rebased locally and here. However, doesn't reflect.

2023-06-29 00:26 UTC, techknowlogick approved these changes

2023-06-29 03:42 UTC, wxiaoguang commented
IMO `read-only` is not `disabled`. Standard HTML doesn't do so.

Could the HTML element get the disabled style instead of changing the "read-only" style?

2023-06-29 04:34 UTC, silverwind requested changes
Checkboxes have no readonly HTML attribute or state, so this is bad guidance from Fomantic UI and we should not use it.

Use disabled state instead: https://fomantic-ui.com/modules/checkbox.html#disabled

There is exactly 1 case of such a checkbox in all templates.

2023-06-29 06:57 UTC, saegl5 commented
@silverwind oh okay, so I'm guessing to put `disabled="disabled"` in templates/repo/pulls/fork.tmpl instead

2023-06-29 07:40 UTC, delvh approved these changes

2023-06-29 13:42 UTC, wxiaoguang commented on templates/repo/pulls/fork.tmpl
> +							<input type="checkbox" disabled="disabled" {{if .IsPrivate}}checked{{end}}>
```suggestion
							<input type="checkbox" disabled {{if .IsPrivate}}checked{{end}}>
```

2023-06-29 15:52 UTC, silverwind commented on templates/repo/pulls/fork.tmpl
>  						<div class="ui read-only checkbox">
```suggestion
						<div class="ui disabled checkbox">
```

2023-06-29 15:52 UTC, silverwind commented
As per fomantic docs, this is how HTML should look:

````html
<div class="ui disabled checkbox">
  <input type="checkbox" disabled>
  <label>Disabled</label>
</div>
````

Please test after mergin above suggestion

2023-06-29 21:15 UTC, saegl5 commented
@silverwind working on it...

2023-06-29 21:16 UTC, saegl5 commented on templates/repo/pulls/fork.tmpl
> +							<input type="checkbox" disabled="disabled" {{if .IsPrivate}}checked{{end}}>
@wxiaoguang works

2023-06-29 21:17 UTC, saegl5 commented on templates/repo/pulls/fork.tmpl
>  						<div class="ui read-only checkbox">
@silverwind works, too

2023-06-29 21:32 UTC, silverwind approved these changes

2023-06-29 22:16 UTC, merged