Fix sending mail with a non-latin display name. #2102
go-gitea/gitea pull request #2559
Opened 2017-09-20 09:33 UTC by rems4e

Signed-off-by: Rémi Saurel <contact@remi-saurel.com>

This pull request fixes #2102, where display name of email addresses containing non-latin characters cannot be used in the From: field when creating/updating issues (resulting in no email sent at all).

The fix is simple, it uses `Message.SetAddressHeader`, instead of `Message.SetHeader` with a custom-formatted `DisplayName <email@address>` from address.

2017-09-20 10:42 UTC, lafriks requested changes

2017-09-20 10:42 UTC, lafriks commented on modules/mailer/mailer.go
> +	return NewMessageFrom(to, setting.MailService.From, "", subject, body)
But as stated in https://github.com/go-gitea/gitea/blob/master/conf/app.ini#L312 From can be in format `"Sender" <sender@domain.ext>` so it should be parsed somehow and passed in both arguments

2017-09-20 11:19 UTC, rems4e commented
@lafriks OK, I overlooked this part. But parsing must also be done here too:

https://github.com/go-gitea/gitea/pull/2559/files#diff-91afb18937651f768645eff6cf5779a8R169

and keeping only the address part.

I will look into this.

2017-09-20 11:26 UTC, lafriks commented
@rems4e it actually already parses it here:
https://github.com/go-gitea/gitea/blob/master/modules/setting/setting.go#L1344

so probably new type field needs to be added `FromDisplayName` and assigned in same place where `FromEmail` is set and than it can be reused in your code

2017-09-20 11:28 UTC, rems4e commented
@lafriks Yes, see my edit above, it was my mistake and I managed to follow the track too ^^

2017-09-20 11:48 UTC, rems4e commented
This time it should be cleaner.

2017-09-20 11:59 UTC, lafriks approved these changes

2017-09-20 12:00 UTC, lafriks commented
LGTM

2017-09-21 04:04 UTC, ethantkoenig commented
LGTM

2017-09-21 04:29 UTC, merged

2017-10-25 15:52 UTC, ptman commented
Any chance of getting this backported to 1.2.x?

2017-10-25 16:04 UTC, lunny commented
seems it's not difficult.