Add reStructedText support and fix readme render bug
go-gitea/gitea pull request #2564
Opened 2017-09-21 07:28 UTC by lunny

should be part of #374, see below screenshots.

![-1](https://user-images.githubusercontent.com/81045/30683836-8333d668-9ee1-11e7-8795-7aff19e4c656.png)
![-2](https://user-images.githubusercontent.com/81045/30683837-8335f894-9ee1-11e7-92d1-6f62276fc791.png)

2017-09-22 07:40 UTC, lunny commented
Tests added and rebased.

2017-09-22 13:18 UTC, lafriks commented
LGTM

2017-09-22 19:21 UTC, JonasFranzDEV commented
@lafriks LGTM seems not to work

2017-09-22 21:11 UTC, Morlinest requested changes

2017-09-22 21:11 UTC, Morlinest commented on modules/markup/reStructuredText/reStructuredText.go
> +// Render renders reStructuredText rawbytes to HTML
Is not `rawbytes` in comment redudant? And should be unified with `RenderString` comment.

2017-09-22 21:11 UTC, Morlinest commented on modules/markup/reStructuredText/reStructuredText.go
> +// Name implements markup.Parser
I think function comment should tell what that function is doing, not which interface it fulfils.

2017-09-22 21:11 UTC, Morlinest commented on modules/markup/reStructuredText/reStructuredText.go
> +// Extensions implements markup.Parser
Same as for `Name()`

2017-09-22 21:11 UTC, Morlinest commented on modules/markup/reStructuredText/reStructuredText_test.go
> +	setting.AppSubURL = AppSubURL
Same as above.

2017-09-23 06:15 UTC, lunny commented
@Morlinest all done.

2017-09-24 05:47 UTC, ethantkoenig requested changes
IMO, using a third-party library that is "experimental/highly under development" ([README](https://github.com/hhatto/gorst#gorst)) is not a good idea. Would it be worth finding a more stable library, or waiting until this one becomes more mature?

2017-09-24 05:47 UTC, ethantkoenig commented on modules/markup/reStructuredText/reStructuredText.go
> +	w.Flush()
Check error

2017-09-24 05:51 UTC, lunny commented
@ethantkoenig Yes, but this is the most mature library I can find. Also, if #2570 could be merged, external tool could override internal library.

2017-09-24 06:02 UTC, lunny commented on modules/markup/reStructuredText/reStructuredText.go
> +	w.Flush()
done.

2017-09-24 10:27 UTC, Morlinest requested changes

2017-09-24 10:27 UTC, Morlinest commented on modules/markup/reStructuredText/reStructuredText_test.go
> +	}()
Now, when I look at whole change at once... Why you need to change settings? I see only `setting.AppSubURL` is used in `test()`.

2017-09-24 10:27 UTC, Morlinest commented on modules/markup/reStructuredText/reStructuredText_test.go
> +	buffer := RenderString(input, setting.AppSubURL, nil, false)
Use `setting.AppSubURL` as another `test()` argument. E.g. `test(t *testing.T, input, expected, appSubURL string)`

2017-09-24 10:27 UTC, Morlinest commented on modules/markup/reStructuredText/reStructuredText_test.go
> +const AppSubURL = AppURL + Repo + "/"
If you don't need all constants (look at comment for `defer`), merge them together. Also I think you can use unexported version. E.g. `const appSubURL = "http://localhost:3000/go-gitea/gitea/"`.

2017-09-24 10:27 UTC, Morlinest commented on modules/markup/reStructuredText/reStructuredText_test.go
> +func TestRender_Images(t *testing.T) {
If you don' need to change settings (look at `defer` comment above), you can merge both tests together, remove `setting` variable changes and `defer` and use `t.Run()` (just create array of test cases) to run tests in parallel.

2017-09-25 04:28 UTC, ethantkoenig approved these changes
I still do not think that using an unstable library is a good idea, but I'll approve so that I don't block the PR.

2017-09-25 05:12 UTC, lunny commented
@ethantkoenig I don't mind to put this PR later. If #2570 could be merged, it also resolved #374.

2017-09-25 05:13 UTC, lunny commented
And maybe https://github.com/demizer/go-rst is a better choice.

2018-07-21 18:13 UTC, flufmonster commented
@lunny go-rst is marked as `ABANDONED`. I think with #374 closed this could also be closed.

2018-07-22 14:40 UTC, closed without merging