Comments on pull files
go-gitea/gitea pull request #2583
Opened 2017-09-23 06:01 UTC by lunny

First step on comment in pull files, and will resolved #124, but still WIP.

2017-09-23 06:52 UTC, lafriks commented on templates/base/head.tmpl
> +	<link rel="stylesheet" href="{{AppSubUrl}}/css/main.css">
Why new css file? I think these css additions need to be done in less file and built into minimized index.css

2017-09-23 15:08 UTC, daviian requested changes

2017-09-23 15:20 UTC, lunny commented on models/issue_comment.go
> +	Line            int64  // + is left; - is right
Don't want to add an extra column, so I define the line, if it's greater than zero, it should the previous code line before the pull's commits. If it's less than zero, it should the line on this pull's commits.

2017-09-23 15:36 UTC, daviian commented on models/issue_comment.go
> +	Line            int64  // + is left; - is right
If everyone's happy with this I won't obstruct.

2017-09-24 05:58 UTC, ethantkoenig requested changes

2017-09-24 05:58 UTC, ethantkoenig commented on public/js/index.js
> +      btn: "Comment Code",
Shouldn't we use locales for these?

2017-10-09 22:00 UTC, bkcsoft commented
@lunny Got any screenshots? And are there visible when viewing a specific commit? (like here: https://try.gitea.io/gitea/gitea/commit/b7da5a6cb7c725232c1053a1ca705a6ac0dad467 )

2017-10-09 22:38 UTC, Morlinest commented on models/issue_comment.go
> +	Line            int64  // + is left; - is right
IMO, if you use `+/-`, it should be `-` for previous line and `+` for new line.

2017-10-10 00:57 UTC, lunny commented
@bkcsoft currently only for pull files. For specific commit should be another PR after this merged.

2018-04-23 05:58 UTC, lunny commented
@thehowl yes.

2018-04-23 05:58 UTC, closed without merging