fix go get subpackage bug
go-gitea/gitea pull request #2584
Opened 2017-09-23 06:28 UTC by lunny

will fix #2577

2017-09-23 06:53 UTC, lafriks commented
LGTM

2017-09-23 12:28 UTC, daviian requested changes

2017-09-23 12:28 UTC, daviian commented on routers/repo/http.go
>  func composeGoGetImport(owner, repo, sub string) string {
Please remove unused parameter `sub`

2017-09-23 12:43 UTC, lunny commented
@daviian done.

2017-09-23 12:54 UTC, daviian commented
LGTM

2017-09-23 13:05 UTC, daviian approved these changes

2017-09-23 13:24 UTC, merged

2017-10-01 12:11 UTC, sapk commented
This is not working on try.gitea.io (bae9cbc) but at first glance don't know why since it should :disappointed: 
https://try.gitea.io/Howl/gorepo/test/test?go-get=1
```
<html>
	<head>
		<meta name="go-import" content="localhost/Howl/gorepo/test/test git https://try.gitea.io/Howl/gorepo.git">
		<meta name="go-source" content="localhost/Howl/gorepo/test/test _ https://try.gitea.io/Howl/gorepo/src/master{/dir} https://try.gitea.io/Howl/gorepo/src/master{/dir}/{file}#L{line}">
	</head>
	<body>
		go get localhost/Howl/gorepo/test/test
	</body>
</html>```