do not use deprecatedSettingFatal for cosmetic reasons
go-gitea/gitea pull request #26007
Opened 2023-07-20 06:05 UTC by earl-warren

It breaks existing instances that would otherwise work perfectly fine. Failing to start an instance should only happen when there is a compelling reason to do so, for instance if the `app.ini` could not be modified in a way that is backward compatible. If the only motivation is to remove the setting for cosmetic reason, it must not be fatal.

2023-07-20 06:48 UTC, lunny commented
I think this is the original code in recent 4 or 5 versions. We have enough time to prompt administrator about the deprecated configurations. 

If it doesn't break the instance, users will never check the message and never remove the deprecated configurations.

2023-07-20 07:17 UTC, wxiaoguang commented
Quote https://github.com/go-gitea/gitea/pull/23911#issuecomment-1590497161

> Another problem is that I guess some "fatal" errors would make a lot of users reporting issues asking "why my Gitea doesn't start".
> Maybe we need to use code to help users to upgrade their app.ini automatically.


I am neutral for this change. Either can be done:

1. Revert the old behavior (no fatal)
2. Automatically update the app.ini if it is writable
3. Better "self-check" for various errors/warnings (https://github.com/go-gitea/gitea/issues/25994#issuecomment-1642992679)

2023-07-20 07:21 UTC, wxiaoguang approved these changes

2023-07-20 09:09 UTC, lunny commented on modules/setting/lfs.go
> +	lfsSec.Key("PATH").MustString(sec.Key("LFS_CONTENT_PATH").String())
lfsSec maybe nil

2023-07-20 09:24 UTC, lunny commented on modules/setting/lfs.go
> +			lfsSec = rootCfg.Section("storage.lfs")
```suggestion
			lfsSec = rootCfg.Section("lfs")
```

2023-07-20 09:25 UTC, lunny commented on modules/setting/lfs_test.go
> +[storage.lfs]
```suggestion
[lfs]
```

2023-07-20 11:56 UTC, delvh commented
Well… I am somewhat against removing this warning.
It is not just "cosmetic", it helps admins know what's going on in their instance.
I think it's better to make that explicit than that Gitea changes the config options slightly without notifying the admins who are left to wonder why something doesn't work anymore.
So it's not just "cosmetic", it serves a purpose.

I've started a survey among maintainers how we should handle config changes in the future.
We'll know the results of that in a little over a week (will post an issue describing how we will handle such changes then).
For 1.20, I think it's best to not change that warning, and simply use the new approach with 1.21.

2023-07-20 13:07 UTC, lunny approved these changes

2023-07-20 13:07 UTC, lunny commented
Maybe we can have another idea to prompt admin like have a top bar or others but not a fatal log. Or #25994

2023-07-20 13:23 UTC, techknowlogick requested changes
Blocking per the ongoing maintainer discussion

2023-07-20 13:35 UTC, wxiaoguang commented
@techknowlogick is there still disagreement about reverting it?

For 1.20.1 , quote: https://github.com/go-gitea/gitea/pull/26015#issuecomment-1643702225

> I am neutral for it, but actually:
> * If it needs to wait, then wait for it
> * If it doesn't need to wait, then `#26007` (this PR) doesn't seem useful after this release, because there might be a long time to next release.

2023-07-20 13:39 UTC, techknowlogick commented
@wxiaoguang Im wasn't sure what the conclusion of the chat was, so I figured waiting a moment before consensus was reached was ok.

2023-07-21 23:58 UTC, eeyrjmr commented
> I think this is the original code in recent 4 or 5 versions. We have enough time to prompt administrator about the deprecated configurations.
> 
> If it doesn't break the instance, users will never check the message and never remove the deprecated configurations.

yup, this "breaking" has been present for 1-2 years. It was fatal on windows when the [lfs] section was preferred  but since it was mentioned in the release notes I didn't bother reporting it.

Carrying dead code is just technical debt and as long as it is clearly states what needs to be corrected there shouldn't be any problem as it is the duty of a site admin to review the changes and update accordingly. Likewise it is the duty of the gitea maintainers to ensure  the release notes state this

2023-07-22 04:07 UTC, wxiaoguang commented
Again: @techknowlogick is there still disagreement about reverting it?

What's the final conclusion?

2023-07-23 10:40 UTC, closed without merging

2023-07-23 16:37 UTC, techknowlogick commented
@wxiaoguang I've had limited internet over the past days, but I think there is some decision by the maintainers that'll be acted upon.