Fix doubled issue tab introduced in migration v16
go-gitea/gitea pull request #2611
Opened 2017-09-26 21:50 UTC by daviian

Migration v16 creates UnitTypeIssue and UnitTypeExternalTracker for each repository with enabled external issue tracker as repo.EnableIssues is true even for external tracker.

And because both Unit Types exist the issue tab is shown twice.

The same behaviour is happening to UnitTypeWiki and UnitTypeExternalWiki, but because the tab is not changed in view it has no visual impact.

PR fixes both mistakes and removes UnitTypeIssue for repositories with UniTypeExternalTracker and removes UnitTypeWiki for repositories with UnitTypeExternalWiki.

2017-09-27 04:18 UTC, lafriks requested changes

2017-09-27 04:18 UTC, lafriks commented on models/migrations/v44.go
> +	err := x.Table("repository").Select("`repository`.id").
No need for repository table here. Just select form repo_unit directly

2017-09-27 04:18 UTC, lafriks commented on models/migrations/v44.go
> +	err = x.Table("repository").Select("`repository`.id").
Same as above

2017-09-27 08:24 UTC, daviian commented
@lafriks Included your requested changes

2017-09-27 08:29 UTC, lafriks approved these changes

2017-09-27 08:30 UTC, lafriks commented
LGTM

2017-09-27 08:32 UTC, Morlinest commented
LGTM :)

2017-09-28 12:41 UTC, lunny commented
LGTM

2017-09-28 13:13 UTC, lafriks commented
Make LG-TM work

2017-09-28 13:14 UTC, merged