Use Semantic UI's Search component for user and repo search
go-gitea/gitea pull request #2636
Opened 2017-10-01 17:30 UTC by harryxu

Current user and repo search input is not support keyboard navigation and must use mouse click to select item.

So I use Semantic UI's Search component replace the jquery ajax code and html generating code, for improve the UI  experience.

Here is the screenshots:

**New user search**
![](https://i.imgur.com/rO9tMqT.gif)

**New repo search**
![](https://i.imgur.com/Ex1Onsr.gif)

**Old user search** (Can only use mouse select):
![](https://i.imgur.com/ap1HzfD.gif)

2017-10-01 18:13 UTC, daviian requested changes

2017-10-01 18:13 UTC, daviian commented on public/js/index.js
> +            url: suburl + '/api/v1/repos/search?q={query}',
`uid` query parameter is missing.

2017-10-02 02:03 UTC, harryxu commented on public/js/index.js
> +            url: suburl + '/api/v1/repos/search?q={query}',
@dakira Fixed.

2017-10-02 03:57 UTC, ethantkoenig approved these changes
Looks good! Just one nit.

2017-10-02 03:57 UTC, ethantkoenig commented on public/js/index.js
>  // FIXME: merge common parts in two functions
nit: remove this comment now that it is stale

2017-10-02 08:12 UTC, daviian approved these changes

2017-10-02 08:18 UTC, daviian commented
Please remove comment as @ethantkoenig mentioned, otherwise LGTM

2017-10-02 13:53 UTC, harryxu commented
@ethantkoenig @daviian Done. 😃

2017-10-02 17:30 UTC, ethantkoenig commented
LGTM

2017-10-02 20:52 UTC, lafriks commented
Make LG-TM work again

2017-10-03 03:27 UTC, merged