Use /orgs instead of /org to match GitHub v3 API
go-gitea/gitea pull request #2639
Opened 2017-10-02 13:14 UTC by raphink

As per https://developer.github.com/v3/repos/#create

2017-10-02 14:28 UTC, sapk requested changes

2017-10-02 14:28 UTC, sapk commented on routers/api/v1/repo/repo.go
>  	//       500: error
You need to update the swagger:route (the url part) also. You can even edit {org} since in url params in swagger at not yet configured.

2017-10-02 14:33 UTC, sapk commented
The cherry on the cake would be to keep the old url available and mark it as depraceted in swagger.
- Keeping the old m.Post("/org/:orgname/repos", reqToken(), bind(api.CreateRepoOption{}), repo.CreateOrgRepo)
- Add an other (duplicate) swagger comment with deprected tag inside CreateOrgRepo.

2017-10-02 15:25 UTC, strk commented
But you're doing this under the `/v1/` group, shouldn't it go to `/v3/` group instead ?
Those versions are there for a reason...

2017-10-02 18:08 UTC, lafriks commented
I agree with @strk that v1 route should be left as it is and note added in swagger docs that it is deprecated and new one should be created under v3 that would be with GitHub compatible route

2017-10-03 07:45 UTC, raphink commented
@lafriks @strk Agreed, but I don't see a v3 in `routers/api`. Am I missing something?

2017-10-03 16:36 UTC, lafriks commented
@raphink no currently there is no such route. But you can add it ;)

2017-10-04 08:31 UTC, sapk requested changes

2017-10-04 08:31 UTC, sapk commented on routers/api/v1/repo/repo.go
> +	// swagger:route POST /org/{orgname}/repos organization createOrgRepo
/org**s**/{orgname}/repos

2017-10-04 13:47 UTC, raphink commented on routers/api/v1/repo/repo.go
> +	// swagger:route POST /org/{orgname}/repos organization createOrgRepo
Ah, thanks!

2017-10-05 09:39 UTC, jonasfranz approved these changes
I think this PR needs the BREAKING label since it changes the API urls.

2017-10-05 10:50 UTC, lafriks commented
@JonasFranzDEV that's why I think this should be done as new /v3 route and current marked as deprecated not to break existing API

2017-10-05 11:00 UTC, strk commented
Didn't we say that a *new* endpoint should have been added (`/v3/`) instead of changing any of the existing ones ?

2017-10-10 20:39 UTC, bkcsoft commented
Since we're not compatible with `GitHub v3` we shouldn't put things under `/v3/` until we are.

2017-10-11 15:59 UTC, raphink commented
Currently, my issue is to be able to use the Terraform github provider with gitea, which is currently not possible when creating repositories (due to that difference in paths).

2017-10-11 16:32 UTC, strk commented
@BKC why coulnd't we just put partial support /v3/ while it's being
implemented ? As long as the /v2 still works ?

2017-10-12 06:27 UTC, lunny commented
Put the routers to `/api/v3` and keep old router?

2017-10-12 06:33 UTC, daviian commented
I guess implementing `v3` isn't done in a single PR. So if nobody starts with it, we will never implemented it.

2017-10-12 06:37 UTC, lunny commented
Or keep both routers for compatibility since there are no conflicts between them.

2017-10-12 06:40 UTC, daviian commented
Wasn't against that suggestion. We should keep both and after `v3` is finished we should fix an end date of `v1` support

2017-10-15 06:44 UTC, bkcsoft commented
The current API uses `v1`, adding a `v3`-router is out or scope for this PR. (But please feel free to create a new one)

2019-01-23 18:13 UTC, techknowlogick commented
Closing per above discussion. Once we get a /v3/ route for API that is compatible with GitHub, then we can re-open this PR.

Thanks for contribution.

2019-01-23 18:13 UTC, closed without merging