Lint models/org.go
go-gitea/gitea pull request #264
Opened 2016-11-26 00:21 UTC by Bwko

2016-11-26 02:08 UTC, lunny requested changes

2016-11-26 02:08 UTC, lunny commented on models/org.go
> +	UID      int64 `xorm:"INDEX UNIQUE(s)"`
The default `GonicMapper` cannot recognize `UID` as `uid` in database. I think you have to add `UID` to the map in https://github.com/go-gitea/gitea/blob/master/models/models.go#L72

2016-11-26 11:43 UTC, lunny approved these changes

2016-11-26 12:22 UTC, lunny commented
LGTM

2016-11-26 12:54 UTC, strk commented
LGTM

2016-11-27 11:18 UTC, merged

2016-11-28 15:54 UTC, lunny commented
resolved #70