Use an abstract lock layer to allow distributed lock between multiple Gitea instances
go-gitea/gitea pull request #26486
Opened 2023-08-14 06:20 UTC by lunny

Fix #19620
Replace #22176

2023-08-14 09:25 UTC, delvh requested changes
I am absolutely not a fan of the variable naming in this PR.

2023-08-14 09:25 UTC, delvh commented on custom/conf/app.example.ini
> +;; Ignored by memory type, for redis, it likes "addrs=127.0.0.1:6379 db=0"
```suggestion
;; Ignored for the "memory" type. For "redis" use something like "addrs=127.0.0.1:6379 db=0"
```

2023-08-14 09:25 UTC, delvh commented on custom/conf/app.example.ini
> +;; Ignored by memory type, for redis, it likes "addrs=127.0.0.1:6379 db=0"
Wait, that or
```suggestion
;; Ignored for the "memory" type. For "redis" use something like `redis://127.0.0.1:6379/0`
```
?
cheatsheet and example config are not in sync at the moment…

2023-08-14 09:25 UTC, delvh commented on docs/content/administration/config-cheat-sheet.en-us.md
> +- `LOCK_SERVICE_CONN_STR`: **\<empty\>**: Ignored when `LOCK_SERVICE_TYPE` is `memory` type, for `redis`, it likes `redis://127.0.0.1:6379/0`
```suggestion
- `LOCK_SERVICE_CONN_STR`: **\<empty\>**: Ignored when `LOCK_SERVICE_TYPE` is `memory`. For `redis` use something like `addrs=127.0.0.1:6379 db=0`
```
Alternatively, it should be
```suggestion
- `LOCK_SERVICE_CONN_STR`: **\<empty\>**: Ignored when `LOCK_SERVICE_TYPE` is `memory`. For `redis` use something like `redis://127.0.0.1:6379/0`
```

2023-08-14 09:25 UTC, delvh commented on docs/content/administration/config-cheat-sheet.en-us.md
> +## Sync (`sync`)
I think a small description of what this section does would be useful.
`Sync` is such a universal term that it could mean _anything_, i.e. "PR reloading settings", "syncs with external mirrors", …
Perhaps we even need to think about renaming this section.

2023-08-14 09:25 UTC, delvh commented on docs/content/administration/config-cheat-sheet.en-us.md
> +- `LOCK_SERVICE_CONN_STR`: **\<empty\>**: Ignored when `LOCK_SERVICE_TYPE` is `memory` type, for `redis`, it likes `redis://127.0.0.1:6379/0`
By the way, can we please not use abbreviations for new configurations?
I don't think it helps the readability when admins first have to think about what that key even means.

2023-08-14 09:25 UTC, delvh commented on modules/setting/sync.go
> +			log.Fatal("LOCK_SERVICE_CONN_STR %s is not right for redis", connStr)
```suggestion
			log.Fatal("LOCK_SERVICE_CONN_STR %s is not a valid redis connection string", connStr)
```

2023-08-14 09:25 UTC, delvh commented on services/cron/tasks.go
> +	defer t.lock.Lock()
defer?

2023-11-22 02:11 UTC, harryzcy commented on modules/sync/lock.go
> +	pool := goredis.NewPool(client) // or, pool := redigo.NewPool(...)
why is the comment necessary

2023-11-22 02:11 UTC, harryzcy commented on services/pull/check.go
> +			log.Error("lock.Unlock: %v", err)
maybe we want to move the log to inside redisLockService, this "lock.Unlock" doesn't really provide information specific to this function, and then we can just `defer lock.Unlock()` here

2023-11-22 02:11 UTC, harryzcy commented on services/pull/pull.go
> +		if err != nil {
`_, err := lock.Unlock(); err != nil {`

2023-11-22 02:11 UTC, harryzcy commented on docs/content/administration/config-cheat-sheet.en-us.md
> +## Sync (`sync`)
Maybe we just call it `lock` here

2023-11-22 02:11 UTC, harryzcy commented on docs/content/administration/config-cheat-sheet.en-us.md
> +- `LOCK_SERVICE_CONN_STR`: **\<empty\>**: Ignored when `LOCK_SERVICE_TYPE` is `memory`. For `redis` use something like `redis://127.0.0.1:6379/0`
The example is different from test, which is `addrs=127.0.0.1:6379 db=0`

2024-08-09 22:22 UTC, closed without merging

2024-08-19 03:45 UTC, lunny commented
@delvh @harryzcy please review #31813