Swap highlighting  between tags and branches
go-gitea/gitea pull request #26577
Opened 2023-08-18 08:51 UTC by CaiCandong

In the dropdown box, the color when selected is `black` instead of highlighted, which seems a bit strange.
- Before:
<img src="https://github.com/go-gitea/gitea/assets/50507092/0ccb37d9-bfd2-475b-85db-040f205978d4" width="150px">

- After:
<img src="https://github.com/go-gitea/gitea/assets/50507092/b86e29e4-b5ac-42f2-9c3f-e03297de2d3a" width="150px">

2023-08-18 09:02 UTC, wxiaoguang commented
It's still strange. I think it could just GitHub's solution.

2023-08-18 10:39 UTC, silverwind commented
Agree, link color is strange to indicate "active tab". Preferably we should render actual tabs.

2023-08-18 12:38 UTC, delvh approved these changes

2023-08-18 14:26 UTC, silverwind requested changes
Blocking, current change is a regression. Color is meant to show clickability, not active tab. Real tabs would be preferred.

2023-08-21 09:02 UTC, yp05327 commented
[WIP] Maybe we need something like this:
![image](https://github.com/go-gitea/gitea/assets/18380374/96e7add3-1883-4827-bf39-e9ab8742cae3)

2023-08-21 09:07 UTC, CaiCandong commented
> [WIP] Maybe we need something like this: ![image](https://user-images.githubusercontent.com/18380374/261974252-96e7add3-1883-4827-bf39-e9ab8742cae3.png)

We need a tabs component,  but I'm not very familiar with Vue.js, can anyone propose a new PR to replace this?
![image](https://github.com/go-gitea/gitea/assets/50507092/edf68eb7-2f71-4b66-99df-d905d6d8429d)

2023-08-21 09:11 UTC, closed without merging

2023-08-21 11:28 UTC, wxiaoguang commented
->  Improve the branch selector tab UI #26631