Lint models/repo_mirror.go
go-gitea/gitea pull request #266
Opened 2016-11-26 00:31 UTC by Bwko

2016-11-26 02:03 UTC, lunny requested changes

2016-11-26 02:03 UTC, lunny commented on models/repo_mirror.go
> +//MirrorQueue holds an UniqueQueue object of the mirror
space

2016-11-26 08:27 UTC, strk commented
LGTM

2016-11-26 11:02 UTC, lunny approved these changes

2016-11-26 11:02 UTC, lunny commented
LGTM

2016-11-27 11:15 UTC, merged

2016-11-28 15:54 UTC, lunny commented
resolved #70