Lint models/repo_branch.go
go-gitea/gitea pull request #268
Opened 2016-11-26 00:41 UTC by Bwko

2016-11-26 01:42 UTC, lunny requested changes

2016-11-26 01:42 UTC, lunny commented on models/repo_branch.go
> +//GetBranches returns all the branches of a repository
space

2016-11-26 08:27 UTC, strk commented
LGTM

2016-11-26 11:00 UTC, lunny approved these changes

2016-11-26 11:01 UTC, lunny commented
LGTM

2016-11-27 11:14 UTC, merged

2016-11-28 15:55 UTC, lunny commented
resolved #70