fix .netrc authentication
go-gitea/gitea pull request #2700
Opened 2017-10-14 08:18 UTC by daviian

Fixes #2480

Reverted a part from #2184 to allow token usage without the need of 2FA.
But token is required im 2FA is enabled!

2017-10-14 08:54 UTC, lunny commented
@daviian but since https://github.com/drone/drone/pull/2241 merged. This PR will broke it again?

2017-10-14 09:04 UTC, lafriks requested changes
Yes I think that would break fixed drone

2017-10-14 09:21 UTC, daviian commented
And current drone only works with latest gitea release... and that's not good at all. Every gitea user that uses drone is now forced to upgrade

2017-10-14 09:24 UTC, lafriks commented
Drone support only 1.2 anyway as only 1.2 has status api

2017-10-14 09:28 UTC, daviian commented
But as you can see in issues users use drone in 1.1.4 and earlier as well.

2017-10-14 10:02 UTC, daviian commented
@lunny @lafriks I changed it to support both options. Username as token as well as password as token.

2017-10-14 10:23 UTC, lafriks approved these changes

2017-10-14 12:17 UTC, lunny commented
@daviian gitea 1.1.4 could use Gogs driver of drone.

2017-10-14 21:19 UTC, lafriks commented
@daviian I still think it's not a good idea to do this as .netrc anyway supports both username&password and drone is only that use this and now that it has already changed to use new way, let's than keep just one way not to have problems later.

2017-10-15 01:37 UTC, lunny commented
@lafriks but that ask people upgrade their drone to latest. So I will give this LGTM

2017-10-15 01:42 UTC, lafriks commented
LGTM

2017-10-15 01:48 UTC, Morlinest requested changes

2017-10-15 01:48 UTC, Morlinest commented on routers/repo/http.go
> +				} else {
`else if`

2017-10-15 01:48 UTC, Morlinest commented on routers/repo/http.go
> +						ctx.Handle(http.StatusInternalServerError, "GetUserByID", err)
missing `return`?

2017-10-15 14:51 UTC, Morlinest requested changes

2017-10-15 14:51 UTC, Morlinest commented on routers/repo/http.go
> +				} else {
```
// Assume username is token
authToken := authUsername

if !isUsernameToken {
	// Assume password is token
	authToken = authPasswd
```

2017-10-15 14:59 UTC, daviian commented
Make LG-TM work

2017-10-15 15:00 UTC, Morlinest approved these changes

2017-10-15 15:18 UTC, lafriks commented
Make it work again

2017-10-15 15:35 UTC, merged

2017-10-15 15:36 UTC, lafriks commented
@daviian please backport to 1.2 branch