Fix plain readme didn't render correctly on repo home page
go-gitea/gitea pull request #2705
Opened 2017-10-15 01:17 UTC by lunny

will fix #2701

2017-10-15 01:32 UTC, lafriks commented
@lunny I don't know why but integration tests fail

2017-10-15 01:33 UTC, lunny commented
@lafriks I think I find the problem, sent another commit.

2017-10-15 12:35 UTC, Morlinest requested changes

2017-10-15 12:35 UTC, Morlinest commented on routers/repo/view.go
>  				ctx.Data["IsMarkup"] = true
`ctx.Data["IsMarkup"]` is not needed anymore?

2017-10-16 01:54 UTC, lunny commented
@Morlinest done.

2017-10-16 06:53 UTC, lafriks commented
LGTM

2017-10-16 06:57 UTC, bkcsoft commented
LGTM

2017-10-16 07:04 UTC, merged