notifies admins on new user registration
go-gitea/gitea pull request #27128
Opened 2023-09-19 04:39 UTC by earl-warren

Sends email with information on the new user (time of creation and time of last sign-in) and a link to manage the new user from the admin panel

Refs: https://codeberg.org/forgejo/forgejo/issues/480

Reviewed-on: https://codeberg.org/forgejo/forgejo/pulls/1371
Co-authored-by: Aravinth Manivannan <realaravinth@batsense.net>
Co-committed-by: Aravinth Manivannan <realaravinth@batsense.net>

(cherry picked from commit 7d2d9970115c94954dacb45684f9e3c16117ebfe)

2023-09-19 08:14 UTC, lunny commented on services/mailer/mail_admin_new_user.go
> +	recipients, err := user_model.GetAllUsers(ctx)
This cannot be accepted by a large Gitea instance.

2023-09-19 08:15 UTC, lunny requested changes
https://github.com/go-gitea/gitea/pull/27128/files#r1329744515

2023-09-19 15:36 UTC, wxiaoguang commented on services/mailer/mail_admin_new_user.go
> +	recipients, err := user_model.GetAllUsers(ctx)
That's a bug. They would like to only send emails to admin, but they load all users ....

2023-09-19 18:54 UTC, delvh commented on services/mailer/mail_admin_new_user.go
> +	recipients, err := user_model.GetAllUsers(ctx)
Additionally, this sounds like something that should be fixed in SQL rather than Go, so please add a new method to only get all admins.

2023-09-19 18:54 UTC, delvh commented on services/mailer/mail_admin_new_user.go
> +	}
These two loops should be a single loop without an intermediate map.

2023-09-19 18:54 UTC, delvh commented on custom/conf/app.example.ini
> +;; Send email notifications to all instance admins on new user sign-ups. Options: enabled, true, false
```suggestion
;; Send an email to all admins when a new user signs up to inform the admins about this act. Options: true, false
```
Additionally, if you change the example config, please also document this in `docs/content/administration/config-cheat-sheet.en-us.md`

2023-09-19 18:54 UTC, delvh commented on custom/conf/app.example.ini
> +;NOTIFY_NEW_SIGN_UPS = false
What about calling it `SEND_NOTIFICATION_EMAIL_ON_NEW_USER`?

2023-09-19 18:54 UTC, delvh commented on options/locale/locale_en-US.ini
> +admin.new_user.subject = New user %s
```suggestion
admin.new_user.subject = New user %s just signed up
```
?

2023-09-19 18:54 UTC, delvh commented on services/notify/notify.go
> +// NewUserSignUp notifies deletion of a package to notifiers
copy-paste?
```suggestion
// NewUserSignUp notifies about a newly signed up user to notifiers
```

2023-09-19 18:54 UTC, delvh commented on services/notify/null.go
> +// NotifyNewUserSignUp notifies deletion of a package to notifiers
copy-paste?
```suggestion
```

Alternatively, to conform with the rest
```suggestion
// NotifyNewUserSignUp places a place holder function
```

2023-09-19 18:54 UTC, delvh commented on services/mailer/mail_admin_new_user.go
> +// Copyright 2023 The Forgejo Authors. All rights reserved.
I summon @techknowlogick

2023-09-19 18:54 UTC, delvh commented on services/mailer/mail_admin_new_user_test.go
> +		From:     "test@forgejo.org",
:raised_eyebrow:

2023-09-19 18:54 UTC, delvh commented on services/mailer/mail_admin_new_user_test.go
> +	newUser.LastLoginUnix = 1693648327
Can't we use the fixtures for this?

2023-09-19 18:54 UTC, delvh commented on services/mailer/mail_admin_new_user.go
> +	tplNewUserMail base.TplName = "admin_new_user"
Shouldn't the template be either in `templates/mail/notify` or `templates/mail/auth`?

2024-06-15 09:48 UTC, wxiaoguang commented
This PR is stale for long time and has many conflicts.

And there is a design problem: it doesn't seem right to do a full table scan when a user registers.

Feel free to reopen if there would be improvements.

2024-06-15 09:48 UTC, closed without merging