add a shortcut to user's profile page to admin user details
go-gitea/gitea pull request #27299
Opened 2023-09-27 02:33 UTC by techknowlogick

For admin's who need quick access to user's details page

![CleanShot 2023-09-26 at 22 33 30@2x](https://github.com/go-gitea/gitea/assets/164197/723a40a3-5d94-4150-b9a4-2b12bd35dece)

2023-09-27 03:41 UTC, denyskon approved these changes

2023-09-27 08:51 UTC, silverwind commented
Why red? Red should only be dangerous actions like deletion etc.

2023-09-27 12:54 UTC, wxiaoguang commented on templates/shared/user/profile_big_avatar.tmpl
> +			{{if and .IsSigned .IsAdmin}}
`IsAdmin` already means `IsSigned`

2023-09-27 12:54 UTC, wxiaoguang commented on templates/shared/user/profile_big_avatar.tmpl
> +			<li class="follow">
Why `follow` ....

2023-09-27 12:55 UTC, wxiaoguang commented on templates/shared/user/profile_big_avatar.tmpl
> +				<a class="ui basic red button" href="{{AppSubUrl}}/admin/users/{{.ContextUser.ID}}">
Why "red" (+1)

2023-09-27 13:47 UTC, denyskon requested changes
Please use a different colour

2023-10-07 01:52 UTC, techknowlogick commented on templates/shared/user/profile_big_avatar.tmpl
> +				<a class="ui basic red button" href="{{AppSubUrl}}/admin/users/{{.ContextUser.ID}}">
thanks. updated to green

2023-10-07 01:53 UTC, techknowlogick commented on templates/shared/user/profile_big_avatar.tmpl
> +			<li class="follow">
copy/paste issue. fixed now

2023-10-07 01:53 UTC, techknowlogick commented on templates/shared/user/profile_big_avatar.tmpl
> +			{{if and .IsSigned .IsAdmin}}
simplified

2023-10-07 02:14 UTC, techknowlogick commented
updated to an icon next to username instead of a button. screenshot has been updated too

2023-10-07 05:01 UTC, denyskon approved these changes
A bit weird line indent in the code 😆 but I like the idea

2023-10-07 05:03 UTC, wxiaoguang commented on templates/shared/user/profile_big_avatar.tmpl
> +						{{svg "octicon-gear" 18 "gt-mr-2"}}
Why `"gt-mr-2"`?

2023-10-07 23:54 UTC, techknowlogick commented on templates/shared/user/profile_big_avatar.tmpl
> +						{{svg "octicon-gear" 18 "gt-mr-2"}}
```suggestion
						{{svg "octicon-gear" 18}}
```

2023-10-08 01:59 UTC, wxiaoguang approved these changes
The indent doesn't look good to me, while it doesn't bother me.

2023-10-08 02:48 UTC, merged