fix(docs): Update default database value
go-gitea/gitea pull request #27330
Opened 2023-09-28 09:54 UTC by kosssi

When I read [Basics installation with Docker](https://docs.gitea.com/installation/install-with-docker#basics) I understand `SQLite` is used [by default](https://github.com/go-gitea/gitea/blob/72c68177ab78d026d25a0a440c35cdbc9723cd98/docker/root/etc/s6/gitea/setup#L45) but when I read [Configuration Cheat Sheet](https://docs.gitea.com/administration/config-cheat-sheet#database-database) I see `mysql` on DB_TYPE default value. It's only for Docker ?

So with this commit, I would like restore the truth 😇

2023-09-28 12:12 UTC, lunny approved these changes

2023-09-28 12:26 UTC, techknowlogick commented
It's made the default in docker because the image has a copy of Gitea with SQLite included, but the code itself sets mysql/Marion as the default if you're compiling from source, or even using one of the binaries downloaded from the CDN.

2023-09-28 20:36 UTC, adelowo approved these changes

2023-09-28 23:51 UTC, silverwind requested changes
app.example.ini not in sync

2023-09-28 23:59 UTC, silverwind commented
As far as the app is concerned, there is no default: https://github.com/go-gitea/gitea/blob/15a504cb9f83fbe40df252159f68c8ed510c99d1/modules/setting/database.go#L60

docker image defaults it to `sqlite`, all other deployments have no default, but they would have `mysql` if they copied the `app.example.ini`.

I guess we should move to a single default in app code, likely `sqlite`.

2024-04-03 01:51 UTC, techknowlogick commented
> I guess we should move to a single default in modules/setting/database.go, likely sqlite.

by setting the default as sqlite, it'll fail when not built with sqlite support

2024-08-11 09:57 UTC, denyskon commented
Closing as docs were moved to https://gitea.com/gitea/docs. Please reopen there if still relevant.

2024-08-11 09:57 UTC, closed without merging