Add dingtalk webhook
go-gitea/gitea pull request #2777
Opened 2017-10-25 04:22 UTC by lunny

As title.

2017-10-25 05:28 UTC, ethantkoenig requested changes
Tests would be nice

2017-10-25 05:28 UTC, ethantkoenig commented on models/webhook_dingtalk.go
> +			strings.TrimRight(commit.Message, "\r\n"), commit.Author.Name)
`commit.Author` may be nil (see #2771)

2017-10-25 05:28 UTC, ethantkoenig commented on models/webhook_dingtalk.go
> +			Title:       text,
Should `title` and `text` be reversed?

2017-10-25 05:28 UTC, ethantkoenig commented on models/webhook.go
> +			return fmt.Errorf("GetDiscordPayload: %v", err)
Wrong error message

2017-10-25 05:28 UTC, ethantkoenig commented on models/webhook_dingtalk.go
> +	// DingtalkPayload represents
nit: represents what?

2017-10-25 05:28 UTC, ethantkoenig commented on models/webhook_dingtalk.go
> +			Title:       text,
Should `title` and `text` be reversed?

2017-10-25 06:24 UTC, lunny commented
@ethantkoenig done.

2017-11-20 07:49 UTC, lunny commented
This is ready to review for v1.4

2017-11-20 09:00 UTC, lafriks commented
LGTM

2017-11-21 03:44 UTC, ethantkoenig approved these changes

2017-11-21 03:44 UTC, ethantkoenig commented
LGTM

2017-11-21 04:26 UTC, merged