Drop sha256-simd in favor of stdlib
go-gitea/gitea pull request #27895
Opened 2023-11-03 13:59 UTC by earl-warren

- In Go 1.21 the crypto/sha256 [got a massive improvement](https://go.dev/doc/go1.21#crypto/sha256) by utilizing the SHA instructions for AMD64 CPUs, which sha256-simd already was doing. The performance is now on par and I think it's preferable to use the standard library rather than a package when possible.

```
cpu: AMD Ryzen 5 3600X 6-Core Processor
                │  simd.txt   │               go.txt                │
                │   sec/op    │    sec/op     vs base               │
Hash/8Bytes-12    63.25n ± 1%    73.38n ± 1%  +16.02% (p=0.002 n=6)
Hash/64Bytes-12   98.73n ± 1%   105.30n ± 1%   +6.65% (p=0.002 n=6)
Hash/1K-12        567.2n ± 1%    572.8n ± 1%   +0.99% (p=0.002 n=6)
Hash/8K-12        4.062µ ± 1%    4.062µ ± 1%        ~ (p=0.396 n=6)
Hash/1M-12        512.1µ ± 0%    510.6µ ± 1%        ~ (p=0.485 n=6)
Hash/5M-12        2.556m ± 1%    2.564m ± 0%        ~ (p=0.093 n=6)
Hash/10M-12       5.112m ± 0%    5.127m ± 0%        ~ (p=0.093 n=6)
geomean           13.82µ         14.27µ        +3.28%

                │   simd.txt   │               go.txt                │
                │     B/s      │     B/s       vs base               │
Hash/8Bytes-12    120.6Mi ± 1%   104.0Mi ± 1%  -13.81% (p=0.002 n=6)
Hash/64Bytes-12   618.2Mi ± 1%   579.8Mi ± 1%   -6.22% (p=0.002 n=6)
Hash/1K-12        1.682Gi ± 1%   1.665Gi ± 1%   -0.98% (p=0.002 n=6)
Hash/8K-12        1.878Gi ± 1%   1.878Gi ± 1%        ~ (p=0.310 n=6)
Hash/1M-12        1.907Gi ± 0%   1.913Gi ± 1%        ~ (p=0.485 n=6)
Hash/5M-12        1.911Gi ± 1%   1.904Gi ± 0%        ~ (p=0.093 n=6)
Hash/10M-12       1.910Gi ± 0%   1.905Gi ± 0%        ~ (p=0.093 n=6)
geomean           1.066Gi        1.032Gi        -3.18%
```

(cherry picked from commit 4f64ee294ee05c93042b6ec68f0a179ec249dab9)

2023-11-03 15:30 UTC, lunny commented
But that's only for amd64? I think nowadays, arm64 is also important. Maybe we can wait or have a compile tag.

2023-11-03 18:39 UTC, delvh approved these changes

2023-11-03 18:39 UTC, delvh commented on go.mod
> +	github.com/minio/sha256-simd v1.0.1 // indirect
Where from?

2023-11-04 03:20 UTC, wxiaoguang commented
1. it doesn't really "drop", the minio package still uses it.
2. according to Go document: `SHA-224 and SHA-256 operations now use native instructions when available when GOARCH=amd64`, the Go package doesn't have arm64 support, while `minio/sha256-simd` has.

2023-11-04 06:43 UTC, lunny requested changes
blocked as it's a regression for arm64.

2023-11-04 11:04 UTC, closed without merging