Configurable SSH key exchange algorithm and MAC suite
go-gitea/gitea pull request #2806
Opened 2017-10-30 16:28 UTC by cumgun

Add new configuration keys `SSH_SERVER_KEY_EXCHANGES` and `SSH_SERVER_MACS` in order to configure key exchange algorithm and MAC suite.

2017-10-30 17:47 UTC, lafriks requested changes
Please add also defaults in code like for chippers here: https://github.com/cumgun/gitea/blob/33711b6a963ee5fc5b836acc6cc1c9f577493a16/modules/setting/setting.go#L114

2017-10-30 20:11 UTC, cumgun commented
@lafriks done

2017-10-31 04:56 UTC, lafriks approved these changes

2017-10-31 04:58 UTC, lafriks commented
LGTM

2017-11-02 12:21 UTC, sapk commented on modules/setting/setting.go
> +	serverKeyExchanges := sec.Key("SSH_SERVER_KEY_EXCHANGES").Strings(",")
Shouldn't this be a empty string ? 
For example if SSH_SERVER_KEY_EXCHANGES is not set serverKeyExchanges = "," -> len(serverKeyExchanges) > 0 == true

2017-11-02 12:24 UTC, sapk requested changes
~~~This will lead to a default list empty.~~~

2017-11-02 12:25 UTC, sapk commented on modules/setting/setting.go
> +	serverKeyExchanges := sec.Key("SSH_SERVER_KEY_EXCHANGES").Strings(",")
Sorry misread ...

2017-11-02 12:26 UTC, sapk approved these changes

2017-11-02 12:27 UTC, sapk commented
LGTM

2017-11-02 15:26 UTC, merged