Valid email address should only start with alphanumeric.
go-gitea/gitea pull request #28174
Opened 2023-11-22 15:37 UTC by dek5troza

This fixes issue #27847 where regular expression allowed email address to start with special symbols. Valid email addresses should start with alphanumeric character, and as such will be rendered as email. 

Added test cases from the bug report to validate, such input will not be rendered anymore as email address.

2023-11-22 23:49 UTC, lunny commented
Could it start with a number?

2023-11-23 08:01 UTC, lng2020 requested changes, later dismissed
I'm afraid it's not right. According to that issue, the correct test case should be 
```
test(
  "?a@example.com",
  `<p>?<a href="mailto:a@example.com" rel="nofollow">a@example.com</a></p>`
)
```
The expected behavior of that issue is `~` not rendered but `a@example.com` rendered.

2023-11-23 08:21 UTC, dek5troza commented
> I'm afraid it's not right. According to that issue, the correct test case should be
> 
> ```
> test(
>   "?a@example.com",
>   `<p>?<a href="mailto:a@example.com" rel="nofollow">a@example.com</a></p>`
> )
> ```
> 
> The expected behavior of that issue is `~` not rendered but `a@example.com` rendered.

Ok, I misunderstood the issue. I ll give it another go. Thanks

2023-11-23 19:06 UTC, dek5troza commented
Ok, so hopefully I understood the issue this time. It should handle those characters in the way you have described to me in the comment. Let me know, if I need to update anything else, and I will do it.

2023-11-28 04:33 UTC, wxiaoguang commented
According to RFC and Golang's mail.ParseAddress: `a*b@c.com`  `a~b@c.com` are all valid email addresses.

Although the old regexp doesn't look good, I do not see real benefit by introducing another incorrect patch.

2023-11-28 04:57 UTC, wxiaoguang commented
Made a small change (remove the `?` from regexp because it doesn't affect the result, there is no `?` in regexp body) and added some test cases.

https://github.com/dek5troza/gitea/pull/1

2023-11-28 08:50 UTC, dek5troza commented
> Made a small change (remove the `?` from regexp because it doesn't affect the result, there is no `?` in regexp body) and added some test cases.
> 
> [dek5troza#1](https://github.com/dek5troza/gitea/pull/1) (not ideal enough, see below)
> 
> Well, I am still not sure whether we should really use this patch.
> 
> Test code:
> 
> ```
> func main() {
> 	a, _ := mail.ParseAddress("~a@b.com")
> 	println(a.Address)
> 	a, _ = mail.ParseAddress("*a@b.com")
> 	println(a.Address)
> }
> ```
> 
> Because `~a@a.com` and `*a@a.com` are valid email addresses .......

I was just going by @lng2020 comment. Technically those are valid by RFC5322 but it's arguable how usable those are, as most email service providers would not allow them with rules and filters. 

If more changes are needed with this, I ll be happy to help and update.

2023-12-08 10:10 UTC, dek5troza commented
Hey guys, do you want me to update the patch, and separate ~something as valid email, or how would you like me to proceed with this?

2023-12-08 10:52 UTC, wxiaoguang commented
I do not have strong objection for the "arguable" RFC format. But there are still nits:

1. I still think it needs to "remove the ? from regexp because it doesn't affect the result, there is no ? in regexp body".
2. It needs more tests to show the behavior, especially the edge cases like `a*a` and `a~a` if they were not covered before.
3. It needs more comments to describe the decision and the different from the RFC.

2023-12-08 10:56 UTC, dek5troza commented
> I do not have strong objection for the "arguable" RFC format. But there are still nits:
> 
> 1. I still think it needs to "remove the ? from regexp because it doesn't affect the result, there is no ? in regexp body".
> 2. It needs more tests to show the behavior, especially the edge cases like `a*a` and `a~a` if they were not covered before.
> 3. It needs more comments to describe the decision and the difference from the RFC.

Cool, I ll give it till Monday, if there are more opinions, and start updating on Monday with things you have listed above.

2025-01-18 00:48 UTC, karlwilbur commented
I have worked with email validation before. I have a Ruby gem that does this. I am not suggesting that we try implementing a Ruby gem. 😆 But, maybe my work there might be helpful with sorting out validation and verification (tests of the validation code) within Gitea. Feel free to rip/refactor/repurpose as much of my code as you'd like:

https://rubygems.org/gems/email_validator
https://github.com/K-and-R/email_validator/blob/develop/lib/email_validator.rb

I also have a pretty thorough set of tests:
https://github.com/K-and-R/email_validator/blob/master/spec/email_validator_spec.rb

 I hope it helps!

2025-03-13 03:02 UTC, wxiaoguang commented
Inactive for long time, ping ~~

2025-03-13 08:44 UTC, dek5troza commented
> Inactive for long time, ping ~~

You are right, this slipped through.  I ll take a štab at it this weekend.

2025-04-20 10:32 UTC, wxiaoguang approved these changes

2025-04-20 10:41 UTC, lafriks approved these changes

2025-04-20 11:18 UTC, merged