chore: simplify docker build process.
go-gitea/gitea pull request #2827
Opened 2017-11-02 06:00 UTC by appleboy

> * git tag v1.9.2 will publish docker tags 1, 1.9 and 1.9.2
> * git tag v1.9.2-alpha.1 will publish docker tag 1.9.2-alpha.1

See the folllowings:

```diff
pipeline:
  publish_latest:
    image: plugins/docker
    repo: octocat/hello-world
-   tags: latest
+   default_tags: true
    when:
-     event: push
+     event: [ push, tag ]

- publish_release:
-   image: plugins/docker
-   repo: octocat/hello-world
-   tags: $DRONE_TAG
-   when:
-     event: tag
```

ref: https://discourse.drone.io/t/new-default-tags-parameter-for-docker-plugin/995

cc @lunny @tboerger

2017-11-02 06:07 UTC, lafriks commented
But will it keep only master branch for `latest`?

2017-11-02 06:31 UTC, appleboy commented
@lafriks Yes. it always does that since nobody can't create any branch on Gitea repo expect owner. Every need to fork this project to self-account and create a new branch, then send the PR.

2017-11-02 07:57 UTC, appleboy commented
@lafriks I created new PR to fix your problem. https://github.com/drone-plugins/drone-docker/pull/160

2017-11-02 08:03 UTC, lafriks commented
@appleboy but there is also release branches that could possibly make latest not to be from master branch

2017-11-02 08:05 UTC, appleboy commented
@lafriks Yes. so I created new PR to fix the condition for multiple branches.

2017-11-02 18:40 UTC, lafriks commented
Would leaving `branch: [ master ]` would build only master branch and tags? If so that would work for us I think

2018-04-29 12:56 UTC, appleboy commented
@lafriks We don't need to leave `branch: [ master ]`.

2018-04-29 12:58 UTC, appleboy commented
The docker plugin only builds image when branch equal to default branch of the project and push the tag event.

2018-04-29 13:18 UTC, lunny approved these changes

2018-04-30 01:12 UTC, bkcsoft reviewed
:thinking:

2018-04-30 01:12 UTC, bkcsoft commented on .drone.yml
>      image: plugins/docker:17.05
Seeing as the announcement was Oct '17 (17.10) should we have to update this image tag as well?

2018-04-30 01:12 UTC, bkcsoft commented on .drone.yml
>      image: plugins/docker:17.05
And this obviously

2018-04-30 01:13 UTC, bkcsoft requested changes
The above review comment should've been a "request change" :roll_eyes:

2018-04-30 01:21 UTC, bkcsoft approved these changes

2018-04-30 01:47 UTC, merged