1.21.2 changelog
go-gitea/gitea pull request #28387
Opened 2023-12-07 17:45 UTC by techknowlogick

To be rebuilt with latest golang version

2023-12-07 19:49 UTC, lunny commented
wait #28018, #28385 and backport of #28361

2023-12-07 22:40 UTC, lafriks approved these changes

2023-12-09 09:37 UTC, lunny approved these changes

2023-12-09 14:03 UTC, lafriks commented on CHANGELOG.md
> +## [1.21.2](https://github.com/go-gitea/gitea/releases/tag/1.21.1) - 2023-12-07
```suggestion
## [1.21.2](https://github.com/go-gitea/gitea/releases/tag/1.21.2) - 2023-12-09
```

2023-12-09 15:39 UTC, lunny requested changes
wait some PRs to be merged.

2023-12-12 05:25 UTC, lunny approved these changes

2023-12-12 06:23 UTC, merged