Docker integration
go-gitea/gitea pull request #288
Opened 2016-11-28 13:20 UTC by tboerger

To get a real docker container up and running I have updated the entire build process which integrates perfectly into our Drone environment. This will obsolete #125 and #117. Thank you guys for the work over there.

2016-11-28 14:35 UTC, leitzler commented
I'd strongly advice against running `edge` version of alpine too. `latest` is way better, but it shouldn't be used either. Go with `3.4` instead.

2016-11-28 15:14 UTC, tboerger commented
> I'd strongly advice against running edge version of alpine too. latest is way better, but it shouldn't be used either. Go with 3.4 instead.

I'm running `edge` for MANY containers for a quite long time without any issue. `gosu` is only part of the testing repo, and `shadow` is only available in the `edge` community repo for now.

2016-11-28 15:23 UTC, willemvd commented
Will it also run as a non root user aka docker run -u <random id> ?

2016-11-28 15:24 UTC, stevenroose commented
Is there a specific reason to use `alpine:edge` instead of just `latest`? I guess we want an environment as stable as possible to deploy Gitea in?

2016-11-28 15:35 UTC, tboerger commented
> Is there a specific reason to use alpine:edge instead of just latest? I guess we want an environment as stable as possible to deploy Gitea in?

Yeah, `gosu` and `shadow` packages. I can just say that edge is pretty stable. You can see lots of containers at https://github.com/dockhippie, most of them are based on alpine:edge and they are used heavily and they are working without known issues.

2016-11-28 15:35 UTC, tboerger commented
> Will it also run as a non root user aka docker run -u ?

I'm not sure if that is possible at all since daemons like openSSH are always started as root and it droppes the privileges later on.

2016-11-28 15:43 UTC, leitzler commented
`edge` is their **development** branch.. Or as they say on the wiki:

> Warning: "edge" is under constant development so be careful using it in production. It is possible that bugs in "edge" could cause data loss or could break your system.

I'm sure it works for many users, but a stable product should never rely on an unspecified development version. I'm sure that this will be a deal breaker for users of Gitea.

You don't want `latest` either since they may release 4.0 any day and that one include breaking changes that propagate down to Gitea too.

2016-11-28 16:26 UTC, tboerger commented
So I have replaced `gosu` with the smaller `su-exec` now, I have replaced the `shadow` usage with `addgroup` and `adduser` and I have changed the base image to 3.4.

2016-11-28 19:49 UTC, metalmatze commented
LGTM 🎉

2016-11-28 21:27 UTC, bkcsoft requested changes
Few things

2016-11-28 21:27 UTC, bkcsoft commented on docker/README.md
> -# Docker for Gogs
Why was this file removed?

2016-11-28 21:27 UTC, bkcsoft commented on docker/usr/bin/entrypoint
> +    mkdir -p ${FOLDER}
should be `mkdir -p "${FOLDER}" || true` no?
```
[bkc@bkc-ws] $ mkdir /usr
mkdir: cannot create directory ‘/usr’: File exists
[bkc@bkc-ws] $ echo $?
1
```

2016-11-28 21:48 UTC, leitzler commented on Dockerfile.rpi
> +    /var/cache/apk/* && \
Why split short lines with few arguments?

2016-11-28 22:16 UTC, tboerger commented on docker/usr/bin/entrypoint
> +    mkdir -p ${FOLDER}
-p works fine like it is

2016-11-28 22:17 UTC, tboerger commented on docker/README.md
> -# Docker for Gogs
Because multiple parts don't match anymore and instead of this file I would like to add a chapter to the docs and the example deployment repo.

2016-11-28 22:18 UTC, tboerger commented on Dockerfile.rpi
> +    /var/cache/apk/* && \
I would say personal style/taste.

2016-11-29 06:20 UTC, bkcsoft commented on docker/usr/bin/entrypoint
> +    mkdir -p ${FOLDER}
Heh nvm, I forgot to check with `-p` :smile:

2016-11-29 06:20 UTC, bkcsoft commented on docker/README.md
> -# Docker for Gogs
:+1:

2016-11-29 06:20 UTC, bkcsoft approved these changes

2016-11-29 06:21 UTC, bkcsoft commented
LGTM

2016-11-29 06:21 UTC, merged

2016-11-29 06:51 UTC, leitzler commented on Dockerfile.rpi
> +    /var/cache/apk/* && \
Fair enough! If you check out the most popular official images at Docker Hub, the usual way to split lines are per command (except for packages). In my opinion it adds readability, but as you say, it's a matter of style & taste.