Integration test for user deleting account
go-gitea/gitea pull request #2891
Opened 2017-11-11 23:10 UTC by ethantkoenig

2017-11-11 23:20 UTC, lafriks requested changes

2017-11-11 23:20 UTC, lafriks commented on integrations/integration_test.go
> -// Copyright 2017 The Gitea Authors. All rights reserved.
Please revert this change

2017-11-11 23:39 UTC, ethantkoenig commented on integrations/integration_test.go
> -// Copyright 2017 The Gitea Authors. All rights reserved.
My mistake, good catch

2017-11-12 00:23 UTC, lafriks approved these changes

2017-11-12 00:23 UTC, lafriks commented
LGTM

2017-11-12 13:23 UTC, lunny commented
LGTM

2017-11-12 13:36 UTC, merged