ETag TrimPrefix W/
go-gitea/gitea pull request #28957
Opened 2024-01-27 13:53 UTC by cchangwen

https://stackoverflow.com/questions/51973120/where-does-the-w-in-an-etag-appear-from

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/ETag#

 
Please check the following:
1. Make sure you are targeting the `main` branch, pull requests on release branches are only allowed for backports.
2. Make sure you have read contributing guidelines: https://github.com/go-gitea/gitea/blob/main/CONTRIBUTING.md .
3. Describe what your pull request does and which issue you're targeting (if any).
4. It is recommended to enable "Allow edits by maintainers", so maintainers can help more easily.
5. Your input here will be included in the commit message when this PR has been merged. If you don't want some content to be included, please separate them with a line like `---`.
6. Delete all these tips before posting.

2024-01-27 21:20 UTC, KN4CK3R requested changes

2024-01-27 21:20 UTC, KN4CK3R commented on modules/httpcache/httpcache.go
>  			item = strings.TrimSpace(item)
Each `item` could have the `W/` prefix.

2024-01-28 10:32 UTC, KN4CK3R approved these changes

2024-01-28 16:02 UTC, delvh approved these changes

2024-01-28 16:02 UTC, delvh commented on modules/httpcache/httpcache.go
> +			item = strings.TrimPrefix(strings.TrimSpace(item), "W/")
```suggestion
			item = strings.TrimPrefix(strings.TrimSpace(item), "W/") // https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/ETag#directives
```

2024-01-28 16:03 UTC, delvh commented
Is that an enhancement or a bugfix?

2024-01-28 20:33 UTC, KN4CK3R commented
I would say enhancement.

2024-01-29 15:52 UTC, silverwind approved these changes

2024-01-29 16:18 UTC, merged