Integrate alpine `noarch` packages into other architectures index
go-gitea/gitea pull request #29137
Opened 2024-02-11 21:35 UTC by KN4CK3R

The alpine package manager expects `noarch` packages in the index of other architectures too to be found.

2024-02-14 13:28 UTC, Xinayder commented
This is a nice way to fix the issue with noarch packages in the Alpine registry. I used a different approach in Forgejo, based on the information gathered on the official Alpine channels that noarch packages are literally just copied to the available architectures in the repository. 

However, one issue I had was when I uploaded a noarch package to a repository that doesn't exist. I believe the same issue is present in your PR, if the repo is new and the first package you're uploading is a noarch package, there are no available architectures on the repository and the noarch package won't be copied to the other architectures. 

The other thing I can say is, while it's nice that you keep track of the noarch packages on a separate "repo", it's not something done by Alpine, since there is no noarch repository on the official registry and apk doesn't support it yet.

2024-02-14 14:39 UTC, KN4CK3R commented
> there are no available architectures on the repository and the noarch package won't be copied to the other architectures

Yes, I know about the problem if there is no other package which provides an architecture. I decided to ignore it because I don't want to set some default architecture which may be correct or incorrect, the system just can't know about it.

> and apk doesn't support it yet.

Yes, maybe one client does in the future.

2024-02-14 19:44 UTC, lafriks commented on services/packages/alpine/repository.go
> +	IndexArchivFilename = IndexFilename + ".tar.gz"
```suggestion
	IndexArchiveFilename = IndexFilename + ".tar.gz"
```

2024-02-15 21:00 UTC, silverwind approved these changes

2024-02-24 05:12 UTC, wxiaoguang approved these changes

2024-02-24 05:18 UTC, lunny requested changes
The typo @KN4CK3R mentioned should be fixed before merging.

2024-02-25 04:28 UTC, lunny approved these changes

2024-02-25 15:10 UTC, merged