Skip blob content in `getTree`
go-gitea/gitea pull request #29253
Opened 2024-02-19 02:22 UTC by yp05327

Fix #29101

2024-02-19 02:32 UTC, lunny commented
Can you add a test?

2024-02-19 02:40 UTC, yp05327 commented
> Can you add a test?

This occurs randomly, how to test it correctly? 🤔

2024-02-19 05:44 UTC, yp05327 commented
The test got random results. Maybe we need to dig deeper to find out the real reason.
![image](https://github.com/go-gitea/gitea/assets/18380374/8ffc5391-26d3-4bcf-8c5f-e34db6cc5ef9)
![image](https://github.com/go-gitea/gitea/assets/18380374/c5373853-407f-4aba-a619-f7406f2dd279)

2024-02-19 08:31 UTC, KN4CK3R commented
My fix from #29104 prevented the error too but doesn't fix the real problem. Should be the same for this fix. Gave up at that point then. I may have a look at this again later.

2024-02-19 10:54 UTC, delvh approved these changes

2024-02-19 11:00 UTC, wxiaoguang requested changes
Mark as "request changes":

* The root cause should be figured out
* It needs tests and comments

2024-02-19 19:11 UTC, KN4CK3R commented
@yp05327 Are you fine with it if I would create a new PR containing your commit because there are other places too which should be changed. Otherwise we can merge your PR and I create a follow up PR.

2024-02-20 00:06 UTC, yp05327 commented
> @yp05327 Are you fine with it if I would create a new PR containing your commit because there are other places too which should be changed. Otherwise we can merge your PR and I create a follow up PR.

Never mind.

2024-02-20 00:06 UTC, closed without merging