Set pre-step status to `cancelled` if job is skipped
go-gitea/gitea pull request #29489
Opened 2024-02-29 06:33 UTC by sillyguodong

close #27496
1. set pre-step (Set up job) status to `cancelled` if job is skipped.
2. Adjust the icon for step in cancelled state.

before:
![image](https://github.com/go-gitea/gitea/assets/33891828/4bac2ba9-66de-4679-b7ed-fbae459c0c54)

after:
![image](https://github.com/go-gitea/gitea/assets/33891828/ead4871a-4e0f-4bb1-9fb4-37f4fdb78dfc)

2024-02-29 08:25 UTC, delvh approved these changes

2024-02-29 13:26 UTC, silverwind approved these changes

2024-02-29 14:13 UTC, lunny requested changes
I don't think it's right. `skipped` should be considered as success but `canceled` should be considered as `failure`.

2024-03-01 04:06 UTC, sillyguodong commented
> I don't think it's right. `skipped` should be considered as success but `canceled` should be considered as `failure`.

@lunny Got it.  In this PR, just set `pre-setp` status to `skipped` now and don't change frontend. 
On runner side, the reported status of the job's steps should also be `skipped`. I created a [PR](https://gitea.com/gitea/act_runner/pulls/500) in act_runner's repository that implements it.
Could you take a look.

2024-03-01 08:03 UTC, lunny approved these changes

2024-03-01 12:58 UTC, silverwind approved these changes

2024-03-01 13:23 UTC, merged