DOC: in ssh forwarding, user git must be allowed to run docker
go-gitea/gitea pull request #29634
Opened 2024-03-06 14:51 UTC by recumbentbirder

Added to doc for rootless Docker installation:  for SSH passthrough, the ssh user (git) has to be able to run docker.

2024-03-06 17:47 UTC, techknowlogick commented on docs/content/installation/with-docker-rootless.en-us.md
> +For this to work, the user `git` hast to be allowed to run `docker`.
```suggestion

For this to work, the user `git` hast to be allowed to run `docker`.
```

2024-03-06 17:50 UTC, techknowlogick commented on docs/content/installation/with-docker-rootless.en-us.md
> +For this to work, the user `git` has to be allowed to run `docker`.
```suggestion
For this to work, the user `git` has to be allowed to run the `docker` cli command. Please read through the [security considerations](https://docs.docker.com/engine/security/#docker-daemon-attack-surface) of providing non-root linux users access to the docker daemon.
```

2024-03-09 09:18 UTC, denyskon requested changes
Please submit the PR to main branch, it will be backported automatically then.

2024-03-11 17:12 UTC, techknowlogick commented
@denyskon for versioned docs, when clicking on edit it takes you to create a PR against the branch you were viewing.

2024-03-11 17:14 UTC, denyskon commented
Maybe we should change that?

2024-04-23 18:08 UTC, merged