Fix wiki toc link borken for non-English languages
go-gitea/gitea pull request #29931
Opened 2024-03-20 07:29 UTC by lunny

Fix #29877

2024-03-20 08:10 UTC, wxiaoguang commented
Why sometimes encode but sometimes not?


![image](https://github.com/go-gitea/gitea/assets/2114189/5ef4884a-8d7e-44cf-9fa3-330d3fc3c1ed)

2024-03-20 09:58 UTC, delvh approved these changes

2024-03-20 10:33 UTC, lafriks approved these changes

2024-03-20 10:42 UTC, lunny commented
> Why sometimes encode but sometimes not?
> 
> ![image](https://private-user-images.githubusercontent.com/2114189/314420800-5ef4884a-8d7e-44cf-9fa3-330d3fc3c1ed.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA5MjkyMDksIm5iZiI6MTcxMDkyODkwOSwicGF0aCI6Ii8yMTE0MTg5LzMxNDQyMDgwMC01ZWY0ODg0YS04ZDdlLTQ0Y2YtOWZhMy0zMzBkM2ZjM2MxZWQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMyMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMjBUMTAwMTQ5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZjVjYWViNGE0Njc2NjdjOTI1ODA5NTVhYTQ0ZTZhZmU2ZTk1MjExOTJkMTI3YTkwNTlmMWY0NTRkYzNmNDc3NCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.3gLcCMvq0fViQdYwnhpqOAo9MDpG5vIdkAl4-GrhhIA)

014c3a2

2024-03-20 10:59 UTC, silverwind commented
Not sure this is right. I'd certainly want to add some tests for sure.

2024-03-20 11:12 UTC, wxiaoguang commented
I don't know whether it is right either .... does the author or approvers have more information to write into comment?

2024-03-20 12:36 UTC, silverwind requested changes
needs deeper investigation

2024-03-20 18:47 UTC, silverwind commented
As per https://stackoverflow.com/a/50141030/808699 and https://jsfiddle.net/silverwind/pe0twrf8/, it seems unnecssary to encode when setting a `href` attribute.

2024-03-20 18:51 UTC, silverwind commented
Fiddle updated: https://jsfiddle.net/silverwind/pe0twrf8/2/

My conclusion is don't encode when writing into DOM, but do decode when reading from DOM.

2024-03-20 19:00 UTC, silverwind commented on web_src/js/markup/anchors.js
> +    a.setAttribute('href', `#${decodeURIComponent(originalId)}`);
```suggestion
    a.setAttribute('href', `#${originalId}`);
```

2024-03-20 19:03 UTC, silverwind commented on web_src/js/markup/anchors.js
> +    if (a.closest('.markup').querySelectorAll(`a[name="${decodeURIComponent(originalId)}"]`).length !== 1) {
```suggestion
    a.setAttribute('href', `#${originalId}`);
    if (a.closest('.markup').querySelectorAll(`a[name="${CSS.escape(originalId)}"]`).length !== 1) {
```

2024-03-20 19:28 UTC, silverwind commented
Apparently it does make a difference whether a link is generated or pre-existing in HTML:

https://jsfiddle.net/silverwind/2wy39d7e/

So backend-generated links will appear escaped and need a `decodeURIComponent` when reading them from DOM. JS-generated links can insert as unicode into DOM, but I guess for consistency we should also encode them.

2024-03-20 21:20 UTC, silverwind commented
I rewrote this file quite a bit now, the code is now easier to read and there is no more complex `querySelector` and only a single `click` listener that does it all.

Everything is working and I specifically tested with chinese links as well. @lunny can you try you test case on wiki as well?

2024-03-20 21:37 UTC, silverwind approved these changes

2024-03-20 21:37 UTC, silverwind commented
I've invalidated existing reviews because of substantial changes.

2024-03-20 21:38 UTC, silverwind commented on web_src/js/markup/anchors.js
> +    }
This block is matching GitHub behaviour. Ideally we would do this prefixing in backend later, but I didn't want to touch backend here.

2024-03-20 23:02 UTC, lafriks approved these changes

2024-03-20 23:02 UTC, merged

2024-03-21 02:14 UTC, lunny commented
It works but the links are still encoded which is different from Github's implementations. For modern web browsers, we don't need to encode them.

<img width="423" alt="image" src="https://github.com/go-gitea/gitea/assets/81045/19ee749b-c727-44cb-aafc-b4dee8fd9e87">

2024-03-21 08:04 UTC, silverwind commented
> It works but the links are still encoded which is different from Github's implementations. For modern web browsers, we don't need to encode them.

Yes, but it comes out encoded from the backend. I assume from the markup renderer, so would need to be fixed there first. If you can, raise a PR and then I will adapt the JS in the same PR to support this.