Fix:the rounded corners of the folded file are not displayed correctly
go-gitea/gitea pull request #29953
Opened 2024-03-21 02:32 UTC by HEREYUA

Fix:    [#29933](https://github.com/go-gitea/gitea/issues/29933)

**Before**

![image](https://github.com/go-gitea/gitea/assets/37935145/71ec80f6-5896-4e4a-b686-4d792c11ebe2)

**After**

![image](https://github.com/go-gitea/gitea/assets/37935145/81348a61-946a-4562-881d-8d873e50228f)

2024-03-21 02:57 UTC, lunny approved these changes

2024-03-21 08:07 UTC, silverwind commented
How does it look in expanded state?

2024-03-21 08:13 UTC, HEREYUA commented
It appears to display normally in the expanded state
![image](https://github.com/go-gitea/gitea/assets/37935145/04262d74-836a-45b4-9412-841c8c0907b5)

2024-03-21 08:25 UTC, silverwind commented
Looks okay, but I will check in detail later if this can be improved further so it only targets the collapsed state.

2024-03-21 13:57 UTC, delvh approved these changes

2024-03-21 14:03 UTC, silverwind requested changes
Block until I have investigated.

2024-03-27 19:59 UTC, silverwind commented
I pushed another alternative fix:

```css
.ui.segments:not(.horizontal) > .segment:has(~ .tw-hidden) {
  border-radius: 0.28571429rem;
}
```

This selector means "any segment that is followed by one or more hidden elements". In a situation with no hidden elements, `.ui.segments:not(.horizontal) > .segment:last-child` would match but with hidden elements, the method breaks because then the element is no longer the last child.

2024-03-27 20:00 UTC, silverwind approved these changes

2024-03-27 20:01 UTC, silverwind commented
@wxiaoguang fyi, above is another case where selecting for `.tw-hidden` is the only way to fix an issue 😉

2024-03-28 02:05 UTC, lunny approved these changes

2024-03-28 02:05 UTC, wxiaoguang reviewed
I think it is abused. I will take a look.

2024-03-28 11:35 UTC, silverwind commented
The only cleaner solution that I see it to remove collapsed elements from the DOM. It may be possible because I think this toggling is happening in our JS. Another solution may be to work something out with `<details>` element.

2024-03-28 11:38 UTC, silverwind commented on web_src/css/modules/segment.css
> +.ui.segments:not(.horizontal) > .segment:has(~ .tw-hidden) {
```suggestion
.ui.segments:not(.horizontal) > .segment:has(~ .tw-hidden) { /* workaround css issue with :last-child ignoring hidden elements */
```

2024-03-28 11:38 UTC, silverwind commented on web_src/css/modules/segment.css
> +.ui.segments:not(.horizontal) > .segment:has(~ .tw-hidden) { /* workaround css issue with :last-child ignoring hidden elements */
```suggestion
.ui.segments:not(.horizontal) > .segment:has(~ .tw-hidden) { /* workaround issue with :last-child ignoring hidden elements */
```

2024-03-29 15:39 UTC, merged