Reduce overhead of upgrades for users with custom stylesheets/JS
go-gitea/gitea pull request #3051
Opened 2017-12-01 15:41 UTC by techknowlogick

I have custom JS/CSS in use on my gitea instance and when I upgrade I have to edit head.tmpl and footer.tmpl to add in my changes again (otherwise I might have out of date templates). This will allow me to put all of my changes in header_extras.tmpl/footer_extras.tmpl and not worry about upgrading.

Open to suggestions regarding the names of the additional templates, or their locations.

2017-12-01 20:04 UTC, sapk requested changes
A little change needed and add 2-3 lines (in https://github.com/go-gitea/gitea/blob/master/docs/content/doc/advanced/customizing-gitea.en-us.md) recommending to use extra folder to add some custom header and footer resources to keep template updated.

2017-12-01 20:04 UTC, sapk commented on templates/base/footer.tmpl
> +{{template "base/footer_extras" .}}
Cleaner to create a folder extra at root of templates containing footer.tmpl and header.tmpl.

2017-12-01 20:41 UTC, techknowlogick commented
@sapk thanks for the feedback. I've changed the directory for the extras template files, and added in some documentation on when to use them.

2017-12-01 21:38 UTC, sapk approved these changes

2017-12-01 21:39 UTC, sapk commented
LGTM

2017-12-02 00:58 UTC, ethantkoenig commented
Would `custom` be a better directory name than `extras`?

2017-12-02 01:01 UTC, techknowlogick commented
@ethantkoenig Thanks for feedback. As `custom` is already a top level dir, when we tell people to go to the custom folder it might create confusion to have multiple dirs with the same name. (See use of `custom` on this page: https://docs.gitea.io/en-us/customizing-gitea/ )

2017-12-02 01:09 UTC, ethantkoenig commented
@techknowlogick Could we explicitly tell them to go to `templates/custom`, so they don't get confused?

2017-12-02 17:46 UTC, techknowlogick commented
@ethantkoenig yes, but then for the other custom directory we have to explicitly say not the `templates/custom` directory. For example we have instructions for adding the robots.txt, and serving public files to put all of those in `custom` or `custom/public`. There is also a user on discord that is currently confused about just even the one custom directory.

However, this is as much commitment to the idea of that folder name as I have, and so in light of the above if you still want me to change the directory name I will.

2017-12-02 19:32 UTC, ethantkoenig commented
I personally prefer `custom` over `extras`, for two reasons:
1. I think it more clearly describes the intent of the directory (customized template changes)
2. For consistency with the existing `custom` directory; every directory named `custom` is for some sort of custom change.

2017-12-02 20:55 UTC, techknowlogick commented
Ok. Sounds good. Im out right now, but will change it when I get home.

--
Matti


On Sat, Dec 2, 2017, at 02:32 PM, Ethan Koenig wrote:
> I personally prefer custom over extras, for two reasons:


>  1. I think it more clearly describes the intent of the directory
>     (customized template changes)
>  2. For consistency with the existing custom directory; every
>     directory named custom is for some sort of custom change.> — You are receiving this because you were mentioned. Reply to this
> email directly, view it on GitHub[1], or mute the thread[2].> 

Links:

  1. https://github.com/go-gitea/gitea/pull/3051#issuecomment-348714493
  2. https://github.com/notifications/unsubscribe-auth/AAKBZQcxjG4AK4lDtor0NG0oKLGNBz5Wks5s8aXlgaJpZM4QyhIL

2017-12-02 23:50 UTC, techknowlogick commented
@ethantkoenig I've updated it. Thanks again for the feedback.

cc: @lafriks

2017-12-02 23:51 UTC, lafriks commented
LGTM

2017-12-03 00:26 UTC, merged