Fix bugs in issue dashboard stats
go-gitea/gitea pull request #3073
Opened 2017-12-03 07:03 UTC by ethantkoenig

Fixes the following bugs in the issue dashboard:
* Previously, the "In your Repositories", "Assigned to you" and "Created to you" would show the stats for open issues, even if closed issues were selected
* Previously, the "In your Repositories" count would be incorrect when a repo that is not yours is selected (the count should be 0, because of all the issues currently in view, none are in repos that are yours)
* Previously, the simultaneously selecting "In your Repositories" and a repos that is not yours would result in all the issues in the repo being displayed (it should be none, since none of the issues in the repo are in repos that are yours)

Also fixes ignored errors in `GetUserIssueStats(..)`, and adds unit tests for affected functionality.

2017-12-14 14:41 UTC, lunny requested changes

2017-12-14 14:41 UTC, lunny commented on routers/user/home.go
> +			if !com.IsSliceContainsInt64(userRepoIDs, repoID) {
com is not import

2017-12-14 14:45 UTC, lunny commented
And I didn't find any change on issues page on my local tests.

2017-12-14 17:49 UTC, ethantkoenig commented on routers/user/home.go
> +			if !com.IsSliceContainsInt64(userRepoIDs, repoID) {
fixed

2017-12-14 17:52 UTC, ethantkoenig commented
@lunny Did you try following the scenarios I listed in the PR description? I see a difference in those scenarios.

2017-12-24 00:21 UTC, ethantkoenig commented
@lunny Friendly ping

2017-12-24 06:11 UTC, lunny commented on routers/user/home.go
> +			if !com.IsSliceContainsInt64(userRepoIDs, repoID) {
It seems not?

2017-12-24 16:08 UTC, ethantkoenig commented on routers/user/home.go
> +			if !com.IsSliceContainsInt64(userRepoIDs, repoID) {
Strange, fixed now

2017-12-25 14:57 UTC, lunny approved these changes

2017-12-25 14:58 UTC, lunny commented
LGTM

2017-12-25 21:28 UTC, lafriks commented
LGTM

2017-12-25 22:22 UTC, lafriks commented
Oh these random fails :( can you force push?

2017-12-25 23:13 UTC, ethantkoenig commented
@lafriks Do you still need a force push?

2017-12-25 23:25 UTC, lafriks commented
@ethantkoenig no, all good :)

2017-12-25 23:25 UTC, merged