Add API v3 routes for compitable with github
go-gitea/gitea pull request #3076
Opened 2017-12-03 11:56 UTC by lunny

Copy all v1 routes to v3 currently.

2017-12-03 12:16 UTC, lafriks commented
Can you add in the way that only one can be changed?

2017-12-03 13:48 UTC, lunny commented
@lafriks they point the same route function currently. So you will always change both.

2017-12-03 16:38 UTC, lafriks commented
@lunny there is PR to change api route name to match github (#2639) so it would be nice to be able to do that only for v3 and for v1 leave as it is to not break anything just in case

2017-12-03 20:43 UTC, bkcsoft requested changes

2017-12-03 20:43 UTC, bkcsoft commented on routers/api/v1/api.go
> +		apiRoutes(m)
Some of these routes are not GitHub-compatible. They shouldn't be added to `v3/` 😕

2017-12-04 02:36 UTC, lunny commented
OK. I think we could add new route `/v3` and only move github api v3 comiptable routes there.

2017-12-04 17:16 UTC, sapk commented
It would be best to also separate the route into sub-route to not have a "big file" like v1.

2018-06-17 14:55 UTC, bkcsoft commented on routers/api/v1/api.go
> +func apiRoutes(m *macaron.Macaron) {
I would add a `ghCompat bool` argument here, and `if !ghCompat { ... }` around any custom endpoints we have

2019-01-23 18:12 UTC, techknowlogick commented
Closing per above conversation, we can open a fresh PR that includes only routes compatible with GitHub v3

2019-01-23 18:12 UTC, closed without merging