Add support for searching users by email
go-gitea/gitea pull request #30908
Opened 2024-05-09 00:11 UTC by yp05327

Fix #30898

we have an option `SearchByEmail`, so enable it, then we can search user by email.
Also added a test for it.

2024-05-09 00:30 UTC, a1012112796 approved these changes

2024-05-09 00:44 UTC, techknowlogick requested changes
Temporarily blocking as this may expose hidden emails. Perhaps this should be admin only?

2024-05-09 06:38 UTC, yp05327 commented
Updated

2024-10-03 00:07 UTC, yp05327 commented
@techknowlogick 
Can you review this PR again?

2024-10-03 01:41 UTC, lunny approved these changes

2024-10-04 17:11 UTC, techknowlogick approved these changes

2024-10-04 17:45 UTC, merged