Fix `View File` button link if branch deleted on pull request files pages
go-gitea/gitea pull request #31063
Opened 2024-05-23 22:21 UTC by metiftikci

as title

2024-05-23 22:32 UTC, delvh approved these changes

2024-05-24 00:58 UTC, lunny commented on routers/web/repo/pull.go
> +			ctx.Data["SourcePath"] = pull.HeadRepo.Link() + "/src/commit/" + endCommitID
They are different. `endCommitID` is only the last commit of this pull request.

2024-05-24 00:58 UTC, lunny requested changes
per https://github.com/go-gitea/gitea/pull/31063/files#r1612526557

2024-05-24 07:45 UTC, metiftikci commented
this is also usefull when reviwing specific commit in pull request

github also not redirecting to branch

so if you do not want to change branch link behaviour, do you have any suggestion ? like should we check if branch deleted ?

2024-05-25 05:54 UTC, lunny commented
I mean if there are serveal commits on a pull request and when view files on one commit mode. The link should be that commit's id but not end commit id?

2024-05-25 07:48 UTC, metiftikci commented
This is how it work after change:

### Show All Commit: last commit

![image](https://github.com/go-gitea/gitea/assets/29250154/83d8c5c5-d394-48ec-af55-e9ec78c75342)

### View Range: last selected commit

![image](https://github.com/go-gitea/gitea/assets/29250154/a5fbecf7-bcd8-46c2-8cf6-5667c5cb5e4d)

### View One Commit: selected commit

![image](https://github.com/go-gitea/gitea/assets/29250154/e92c5322-1548-43a9-93bb-7e3d8305fb60)

2024-05-25 13:32 UTC, lunny approved these changes

2024-05-25 14:02 UTC, merged