Add test for IsUserAllowedToMerge with action user
go-gitea/gitea pull request #31094
Opened 2024-05-27 02:12 UTC by lunny

2024-05-27 19:30 UTC, delvh approved these changes

2024-05-27 19:30 UTC, delvh commented on services/pull/merge_test.go
> +func Test_IsUserAllowedToMerge(t *testing.T) {
```suggestion
func Test_ActionsUserCannotMerge(t *testing.T) {
```

2024-05-29 04:28 UTC, yp05327 commented
![image](https://github.com/go-gitea/gitea/assets/18380374/c57b2b9a-3924-46f1-95a2-66c97b3c72e0)
The root reason is here.
We only check the permission, and ignore the doer when white list is disabled.
Action user has the permission, but should not be allowed to merge.
So if you change the permission in test, it will fail.

2024-05-29 04:31 UTC, yp05327 requested changes
the test is not correct

2024-05-29 04:33 UTC, yp05327 commented
more details:
![image](https://github.com/go-gitea/gitea/assets/18380374/0e3c6ee6-538e-4982-b183-e736804103b3)
if you print the permission and the user, you can see action user has the permission, so `IsUserMergeWhitelisted` will return true.
![image](https://github.com/go-gitea/gitea/assets/18380374/771635bd-569b-4a59-85b3-f573a406f2ae)

2024-05-29 05:10 UTC, yp05327 commented
the write permission comes from here:
![image](https://github.com/go-gitea/gitea/assets/18380374/b71b3c43-60dc-4e36-bb93-97d4a7a06e47)

2024-05-30 07:20 UTC, lunny commented
Replaced by #31173

2024-05-30 07:20 UTC, closed without merging