Mention completion for issue editor.
go-gitea/gitea pull request #3136
Opened 2017-12-10 15:02 UTC by harryxu

Mention completion on issue editor.  `@mention` engine from [tribute](https://github.com/zurb/tribute).

### Demo:

New issue:

![new issue](https://i.imgur.com/GTpCVNs.gif)

View/Edit issue:
![view issue](https://i.imgur.com/X93Awxb.gif)

2017-12-10 17:08 UTC, tonivj5 approved these changes

2017-12-10 17:17 UTC, lafriks commented
Can you convert tribute css to less file and include into main gitea css? Then there would be no need for additional css include

2017-12-10 22:36 UTC, ethantkoenig requested changes
Mostly looks good, just a few minor things

2017-12-10 22:36 UTC, ethantkoenig commented on routers/repo/issue.go
> +	ctx.Data["RequireTribute"] = true
I believe we also should require tribute in [CompareAndPullRequest](https://github.com/go-gitea/gitea/blob/0d4c63fd70d0b255a9a17352cc47ec2b6ca13440/routers/repo/pull.go#L699)

2017-12-10 22:36 UTC, ethantkoenig commented on templates/base/footer.tmpl
> +
nit: delete blank line for consistency

2017-12-10 22:36 UTC, ethantkoenig commented on templates/base/footer.tmpl
> +			var user = item.original;
nit: should the function body (lines 76-81) be indented?

2017-12-11 03:38 UTC, harryxu commented
@lafriks I will check out later, but I see other JS plugin's css also included by this way.

2017-12-11 03:39 UTC, harryxu commented
@ethantkoenig Done.

2017-12-11 04:41 UTC, lafriks commented
@harryxu yes I know, this one has small css so it was just an idea, it's totally not required and not blocking this PR

2017-12-11 04:44 UTC, ethantkoenig approved these changes

2017-12-11 04:44 UTC, ethantkoenig commented
LGTM

2017-12-11 05:46 UTC, lunny commented
LGTM

2017-12-11 06:03 UTC, merged