Migrate to Xormigrate
go-gitea/gitea pull request #31523
Opened 2024-06-29 09:16 UTC by qwerty287

Migrate the migration handling to [xormigrate](src.techknowlogick.com/xormigrate) instead of the native handling.

The main difference between the methods: gitea has a version-based system, xormigrate uses id-based. This means: In theory, each migration could be executed standalone (xormigrate will however execute them in order).

This allows backporting migrations, and xormigrate is already in use in projects like woodpecker ci (and is working well there).

2024-07-28 04:10 UTC, lunny commented
Could you add description about
1) The comparasion between the two migrations method.
2) Why should we switch?
3) Is it safe enough fro a smooth upgrade? Could you add some tests for the upgrade includes a fresh Gitea installation and an upgrade operation.

2024-07-28 18:05 UTC, techknowlogick commented
@lunny, I have sponsored @qwerty287 to do this work. We should switch because it means we can backport migrations, and this library is already in use with the Woodpecker and Vicuna projects (projects that Gitea maintainers are also involved with/lead).

2024-07-29 05:28 UTC, lunny commented
> @lunny, I have sponsored @qwerty287 to do this work. We should switch because it means we can backport migrations, and this library is already in use with the Woodpecker and Vicuna projects (projects that Gitea maintainers are also involved with/lead).

Yes. But we still need more description on the issue content so that there are enough commit messages once this is merged.

2024-07-30 07:29 UTC, wxiaoguang commented
It seems that it goes back to history again.

Some concerns are not really resolved or mentioned (related issue/PR: #23511 , #23078 ,  #10625 , #8613 )

For example:

* https://github.com/go-gitea/gitea/pull/23078#issuecomment-1440290694

>  Assume users are in v1.19.3 which will add a new column, but for v1.20.0 has no migration for this column but v1.20.3 has, when user upgrade from v1.19.3 to v1.20.0 not v1.20.3, it will encounter problems.

2024-07-30 07:45 UTC, wxiaoguang commented
And one more thing, backporting database changes might break the compatibility promise.

To be clear, I do not mean "blocking". I only mean these edge cases should be clearly answered and documented. For example, what could be backported, what would happen, what should be prohibited from backporting.

----


https://docs.gitea.com/installation/upgrade-from-gitea#backup-for-downgrade

<details>

![image](https://github.com/user-attachments/assets/895ae91c-ef7f-431d-88d1-2fcbbb3ea042)

</details>

2024-08-01 04:25 UTC, lunny commented
Migrations in fact have dependencies, I think we need to indicate the dependencies for all old and new migrations. And migrations cannot exist standalone actually. The dependencies need to be defined.

2024-08-10 17:55 UTC, lunny commented
> > Migrations in fact have dependencies, I think we need to indicate the dependencies for all old and new migrations.
> 
> New migrations, yes, old ones, not necessary as they are probably not being backported.
> 
> I don't think this is something that must be directly in the code, only in a comment. Xormigrate does not need to know about this, migrations are executed in the order they're defined.
> 
> How should I handle this?

Even a new migration will have dependency, imagine two migrations will change the same tables, one is creating a column another is change the column type. So that the later one will depend on the first one in logic.
It will be very easy to miss that dependency when backport migrations. And this is a very easy example and I think there will be much more complexity ones. How will this PR/xormigrate handle the situations?

2024-08-18 18:26 UTC, lunny commented on models/migrations/v1_23/v304.go
> +	if err := x.DropTables(new(Version)); err != nil {
It's better to move the drop table after line 307.

2024-08-18 18:39 UTC, lunny commented
Assume we backport a migration to a stable version. Two problems need to be considered.
1) Does this backported migration have dependency migrations that haven't been backported? It's better to have clear dependencies on the code but not according to our brain which can reduce possible backport problems.
2) Once 1.xx.2 merged a backported migration, how user downgrades to 1.xx.1 like @wxiaoguang said? It's very important once 1.xx.2 have some big bugs for users. It's also a compatible promise. So maybe a rollback migration needs to be supported?

I don't know how woodpecker and Vicuna resolves these problems?

2024-08-23 20:54 UTC, techknowlogick commented
With backports, we could do more than modify the database; we could add doctor commands to be run, so we still meet the requirement of being changeable between minor versions.

2024-08-26 01:27 UTC, lunny commented
> With backports, we could do more than modify the database; we could add doctor commands to be run, so we still meet the requirement of being changeable between minor versions.

Since we have a web UI for administration, I think it's better to let the user do a self-check there and do a fix there. But not fix them automatically because some doctor commands may take a long time.

In summary, I couldn't find the necessary and obvious benefits to migrate to Xormigrate. It cannot resolve the backports in minor versions.

2024-08-30 06:25 UTC, lunny commented
> > It cannot resolve the backports in minor versions.
> 
> It cannot do that alone obviously, because if there's a dependency of a migration defined, it must be backported as well. Xormigrate is not an automation tool that does this, the devs still have to do this. Implementing strict dependency checking in xormigrate is not a big problem and could help here - if I should follow this approach let me know.

I think my concerns are still here which ask the migrations system support both dependency and rollback. And I can't guarantee the rollback can always work because some migrations are unrevertable. So that will still break the compatibility.
> 
>    Does this backported migration have dependency migrations that haven't been backported? It's better to have clear >dependencies on the code but not according to our brain which can reduce possible backport problems.
>    Once 1.xx.2 merged a backported migration, how user downgrades to 1.xx.1 like @wxiaoguang said? It's very important >once 1.xx.2 have some big bugs for users. It's also a compatible promise. So maybe a rollback migration needs to be >supported?

2024-09-17 00:38 UTC, lunny commented
> > Does this backported migration have dependency migrations that haven't been backported? It's better to have clear dependencies on the code but not according to our brain which can reduce possible backport problems.
> 
> That's what I said above. Currently xormigrate does not support this, but I can implement it there.
> 
> > Once 1.xx.2 merged a backported migration, how user downgrades to 1.xx.1 like @wxiaoguang said? It's very important once 1.xx.2 have some big bugs for users. It's also a compatible promise. So maybe a rollback migration needs to be supported?
> 
> Xormigrate supports rollbacks. You would probably need some cli command to perform this.

Thanks for the effort to push the pull request. I think even if both of these two features are implemented. Backporting migrations to a stable version is still dangerous. Most of the time, rollback cannot work well. Assume we delete a column in v1.22.1, I don't know how it can be rolled back when we are v1.22.2. The column data has been missed, it cannot be rolled back in real. If this pull request cannot bring real benefit but more risk, I don't know how should I agree to merge this.

Taking a look at Golang which Gitea has a similar versioning, I don't think they will have a traditional LTS version plan.

2024-09-18 03:19 UTC, techknowlogick commented
@lunny we don't need to add rollback support if this library is included. We also need to ensure that if any migrations are backported, they still meet our upgrade/downgrade on minor version compatibility promises.

One of the biggest benefits is that our migrations can align with migrations approaches in many other software offerings (rails, laravel, and many more) where instead of relying on a single int, all of the migrations that have been run are saved into the DB. We also don't need to no-op migrations, as we only had to do that because we relied on an int to be the same (allows for code cleanliness). We could also have doctor tasks run on prior versions without having to require a user to manually run something in the CLI.

> Assume we delete a column in v1.22.1, I don't know how it can be rolled back when we are v1.22.2. The column data has been missed, it cannot be rolled back in real. If this pull request cannot bring real benefit but more risk, I don't know how should I agree to merge this.

Deleting a column is already possible in the existing code on minor versions, the only thing that is stopping that is those PRs would be viewed by a maintainer and blocked. So we would keep those same policies, and if a migration that doesn't meet the upgrade/downgrade policy on minor versions it would be blocked.

2024-10-07 06:11 UTC, lunny commented
I cannot get what's the benefits. Oppositely, the conversion itself is full of risk, and allowing backport migrations is also full of risk because contributors/code reviewers need to remember the dependencies between migrations. I know the change will allow us to fix some bugs with migrations in stable minor versions. But I think the situation is very rare.

> One of the biggest benefits is that our migrations can align with migrations approaches in many other software offerings (rails, laravel, and many more) where instead of relying on a single int, all of the migrations that have been run are saved into the DB. We also don't need to no-op migrations, as we only had to do that because we relied on an int to be the same (allows for code cleanliness). We could also have doctor tasks run on prior versions without having to require a user to manually run something in the CLI.

2024-10-07 19:50 UTC, delvh commented on models/migrations/v1_23/v306.go
> +		// This should not happen
Erm… How are fresh installs handled?

2024-10-07 19:50 UTC, delvh commented on models/migrations/v1_23/v306.go
> +Please try upgrading to a lower version first (suggested v1.6.4), then upgrade to this version.`)
```suggestion
Please try upgrading to i.e. v1.6.4 first, then upgrade to this version.`)
```

2024-10-08 04:27 UTC, qwerty287 commented on models/migrations/v1_23/v306.go
> +		// This should not happen
This is a migration. It will not run on new DBs.

2024-10-08 07:02 UTC, delvh commented on models/migrations/v1_23/v306.go
> +		// This should not happen
That's exactly the question:
I guess the migrations are **initialized** when you are installing Gitea.
That is, they need to be run there as well, right?

2024-10-08 13:14 UTC, qwerty287 commented on models/migrations/v1_23/v306.go
> +		// This should not happen
No, migrations don't run on fresh DBs. Just models are synced.

2024-10-10 06:57 UTC, delvh approved these changes

2024-10-10 07:04 UTC, lunny requested changes
I believe we currently lack sufficient motivation to change our migration method.

2024-10-20 08:36 UTC, wxiaoguang commented
Well, it happens a lot. See my "pings" of these screenshots.

<details>

![image](https://github.com/user-attachments/assets/61370e86-b693-42f3-803e-1dd25e325577)

----

![image](https://github.com/user-attachments/assets/7cdaa11b-5dce-4c3f-a7e2-015bbd3a1658)

----

![image](https://github.com/user-attachments/assets/fa583815-ed1e-4e67-bee2-486f955b72d9)

----

![image](https://github.com/user-attachments/assets/253a628c-30c7-4485-a3a2-1213831109a1)

</details>


I guess there will be some new "sorrys" for this PR. And it is always a shame that some of the TOC team do not fulfill the responsibilities.


----

So , to be honest, at the moment, either:

1. Become a maintainer and help to improve and approve more PRs, and actively fix and push things, instead of waiting for others or leaving code to others.
2. Be patient to persuade others and use various proofs to prove the correctness and necessity
3. Ask ahead for ensure of the approvals and only make widely-accepted changes.

2024-10-20 08:47 UTC, wxiaoguang commented
> This allows backporting migrations, and xormigrate is already in use in projects like woodpecker ci (and is working well there).

My concern is still not addressed: https://github.com/go-gitea/gitea/pull/31523#issuecomment-2257664130

> > I don't know how woodpecker and Vicuna resolves these problems?
> 
> We usually don't do backports at woodpecker anymore.

So , if "don't do backports", then I guess the PR doesn't fulfill its purpose  "This allows backporting migrations", if there is no significant benefits, why take the risk to touch the stable existing migration mechanism?

2024-10-20 09:03 UTC, wxiaoguang commented
> @wxiaoguang please check out [#31523 (comment)](https://github.com/go-gitea/gitea/pull/31523#issuecomment-2357413059) for some answers to your questions

My opinions:

1. "rollback" is not practicable (actually it is not right in my mind and I would never do "rollback" for a app's database migration), so I agree.
2. Not only "deleting", there could be some "data fix", "default value" or other problems.

For example:

1. Should a data fix PR be backported to 1.19.3? Then 1.20.0 doesn't recognize it and reports 500 error?
2. If a newly added column needs some "default value" provided by 1.19.3, then 1.20.0 would insert wrong default values, then when user goes to 1.20:latest, then 500 error?

The "backporting" problem is more complicated that it looks, just like you said: "We usually don't do backports at woodpecker anymore."

So " if there is no significant benefits, why take the risk to touch the stable existing migration mechanism?"

2024-10-20 09:30 UTC, wxiaoguang commented
> One of the biggest benefits is that our migrations can align with migrations approaches in many other software offerings (rails, laravel, and many more) where instead of relying on a single int, all of the migrations that have been run are saved into the DB.

It looks quite trivial to me because Gitea already have heavily customized a lot of modules, include http/web/router/logger/queue/template/frontend, etc. Nothing is Gitea is really like "other software" at the moment. So making the migration system like or unlike others doesn't really matter.

> We also don't need to no-op migrations, as we only had to do that because we relied on an int to be the same (allows for code cleanliness). 

Why it ever needed to "no-op migrations"? As long as there is no backporting.


> We could also have doctor tasks run on prior versions without having to require a user to manually run something in the CLI.

It also involves "backporting", which is the most risky part in this mechanism.

2024-10-20 09:55 UTC, wxiaoguang commented
These no-op are mainly related to fix some legacy problems, but not related to backporting, instead, they have a hard dependency of the following migration, so, literally they are "replaced". Actually they do not need to be really removed (no-op), keeping the old code there would still be fine (just some duplicate or unnecessary changes).

For example, it ever added a table, then dropped that table. When using a name-based migration system, there should be a separate step to "remove the migration ID from database", otherwise there will be an unknown migration ID in database. It couldn't be simpler then "no-op".

![image](https://github.com/user-attachments/assets/777275e6-3cee-479f-9e16-abb173c2c1d0)

2024-10-20 10:11 UTC, wxiaoguang commented
After a quick code read, I think this PR's change is not mature (so if let me decide, I would also say "block" for it).

If we would really like to do it:

* It needs a complete design and document first.
* Some edge cases need to be clarified, for example: run an old Gitea with a new database, what happens.
    *  Would the old Gitea run? Then mismatched database would cause various problems (it happened a lot in history)
    * Would the old Gitea refuses to run? Then how could developers switch between 1.19 and 1.20 to work.
        * Old code shows an "UPDATE version = ..." hint, could easily force downgrading.
* What happens when there are unknown migration IDs in database?
* `x.Insert(&xormigrate.Migration{ID: i})` doesn't seem right. According to xormigrate, the old migration name should be filled into `Desc` field, while `ID` field should have some real ID-like values.
* It needs a sample to show how to write new migrations and needs some test code to cover the changes (convert from the old migration mechanism)

-----

But, before starting the work, I would like to see people have the consensus first: is it really worth to introduce xromigrate? (at the moment, my answer is no because the benfits seem quite trival to me)

2024-10-20 10:13 UTC, wxiaoguang commented
> > When using a name-based migration system, there should be a separate step to "remove the migration ID from database"
> 
> This could be directly added into xormigrate to have an automatic "cleanup" of this table.

Isn't it more complicated than just writing a "no-op" in the existing mechanism?

2024-10-26 03:42 UTC, wxiaoguang commented
Migrate to Xormigrate or not, we need this first: Refactor the DB migration system slightly #32344 

By #32344 , each migration has a clear version number, it does help the problem in https://github.com/go-gitea/gitea/pull/31523#issuecomment-2424804220: "`x.Insert(&xormigrate.Migration{ID: i})` doesn't seem right. According to xormigrate, the old migration name should be filled into Desc field, while ID field should have some real ID-like values."

2024-10-28 06:53 UTC, techknowlogick commented
As an update, I am starting a discussion with the other maintainers regarding this PR and possibly creating a formal RFC. There are the concerns above, and I hear/understand them. Our contribution document allows all maintainers to have a voice, which I hope will be able to feed into an RFC to allow for a robust approach that satisfies everyone.

Another big thank you to @qwerty287 for their work on his PR already.

2024-11-25 07:26 UTC, lunny commented
> Hey @techknowlogick, are there any news about this?

I think we can close this PR and also close the bounty before we have finished the discussion. But since @qwerty287 has put in a lot of effort on this PR, it's fair to award him as well. @techknowlogick

2024-12-12 00:43 UTC, lunny commented
Thank you for your effort. Given that this issue is far more complicated than we initially expected, it is not feasible to address it through the bounty program. Consequently, we have decided to remove it from the bounty list and close this PR.

2024-12-12 00:43 UTC, closed without merging

2024-12-12 01:29 UTC, jolheiser commented
The prior two comments in this thread appear to contradict each other, maybe they just need clarification?
Is @qwerty287 being compensated for the work put in for this PR? It reads like this work was initially sponsored.

2024-12-12 01:56 UTC, techknowlogick commented
@jolheiser they will be fully compensated.

@qwerty287 thank you again for all the work you put into this. After discussion with others, they have (very patiently) detailed why my approach and library would impact the project in a way that could cause a negative experience for the users. I was focused on one aspect, where there would be benefits without considering other. This is most certainly not a reflection on you or your ability as you executed my vision flawlessly, and the code you provided was top notch. I think I had a hammer in search of a nail, and saw how well it worked for you with woodpecker that I wanted to bring it over here. I think I in the future I will draw up a proposal and discuss with others prior to any large refactoring. Usually things like this are discussed, and I had casually talked about it, but for this change definitely not enough.

2024-12-12 01:59 UTC, techknowlogick commented
@jolheiser also to clarify Lunny's comment, he meant to remove it as an option for others to claim a bounty on it. In the case of this specific PR I had reached out to @qwerty287 and used the bounty system as a way for transferring funds as the tax man needs a receipt pretty much for all my expenses, so rather than foist that upon qwerty287 I opted to use the platform to make everything less painful