Make ParsePatch more performant
go-gitea/gitea pull request #3159
Opened 2017-12-11 23:00 UTC by bkcsoft

2017-12-11 23:44 UTC, lafriks commented
@bkcsoft build failure

2017-12-12 00:30 UTC, ethantkoenig requested changes
Unit tests would be nice

2017-12-12 00:30 UTC, ethantkoenig commented on models/git_diff.go
> +			newLine := bytes.Index(peek, []byte("\n"));
Why not `bytes.IndexByte`?

2017-12-12 00:30 UTC, ethantkoenig commented on models/git_diff.go
> +			if err != bufio.ErrBufferFull {
What if `err` is `nil`?

2017-12-12 00:30 UTC, ethantkoenig commented on models/git_diff.go
> +				input.Discard(newFile)
`newLine`?

2018-01-05 08:11 UTC, sapk reviewed
As it should provide performance improvement, benchmark would be nice to validate the result.

2018-01-25 08:55 UTC, bkcsoft commented
@ethantkoenig Not sure what unit-tests you're referring to 🤔 

@sapk Should go without saying that reading chunks at a time is faster than reading it character by character 🙂

2018-01-25 20:11 UTC, ethantkoenig commented
@bkcsoft I meant "It would be nice if you could add unit tests for the `ParsePatch` function" :smile:

2018-01-25 23:36 UTC, sapk commented
@bkcsoft Just to make sure. I have done https://github.com/sapk-fork/gitea/commit/52dcc4674cc656d948ebfb3a50f618e99a069a43. 
It give a improvement of x2 but failed to pass simple test validation.

2018-02-10 05:58 UTC, bkcsoft commented
@sapk Thanks! 😄 I'll use that test to fix the issue 🙂

2018-07-05 02:09 UTC, lunny commented
CI failed

2018-07-08 23:51 UTC, bkcsoft commented
I'll leave this for the next week (at least) as I'll have limited time to work on it

2019-01-23 15:11 UTC, bkcsoft commented
not working on this anymore, feel free to continue on it or not.

2019-01-23 15:11 UTC, closed without merging