fix: ignore failed LFS objects
go-gitea/gitea pull request #31623
Opened 2024-07-12 07:27 UTC by wolfogre

Partitally fix #31137.

When migrating LFS objects, if there's any object that failed (like some objects are losted, which is not really critical), Gitea will stop migrating LFS immediately but treat the migration as successful.

This PR makes it ignore failed objects and continue migrating. It may not be the best way to handle it, but a better way.

And to ensure data integrity of LFS objects, we may need to add an option to fail the migration if there's any error in the feature.

2024-07-12 14:12 UTC, 6543 requested changes
I would create an dedicated error where you can `errors.Is` check against ...

2024-07-12 14:13 UTC, 6543 commented
... so if repo_module.StoreMissingLfsObjectsInRepository is reused at other code parts we do handle this ... and only skip by case in the migrator

2024-07-14 18:21 UTC, lunny approved these changes

2024-07-23 08:29 UTC, wolfogre commented
@6543 

> I would create an dedicated error where you can errors.Is check against ...

A dedicated error to indicate "Not found" can help only when we can choose to "ignore and continue" or "stop and fail".
However, there are only "ignore and continue" or "stop and mark success", that's why I added the comment `TODO: Optionally return error to ensure data integrity of LFS objects`.

So I don't think it makes sense to block this PR. We should merge this first and focus on `TODO: Optionally return error to ensure data integrity of LFS objects`.

2024-07-23 16:24 UTC, 6543 commented
I still think it should be fixed in this pull

2024-07-24 03:24 UTC, wolfogre commented
> I still think it should be fixed in this pull

@6543  I understand you think this PR doesn't fix it completely (I agree with that so it's "Partially fix"), but it at least it doesn't makes things worse. And the introduced TODO comments indicate what we should do next.

---

By the way, you said "I would create an dedicated error ...", I'm not sure whether you mean you will do this or you suggest me to do this?

I thought it was "(If I have time) I would..." so I waited for two weeks. But I just noticed that it could be "(If I were you) I would...", so we need to clarify it. 😄 Never mind, It's just a friendly discussion about English studying between two non-native English speakers.

If you suggest me to do this, I would say I already tried,  but it need more work since we cannot check the error just from the message, it need follow the [spec](https://github.com/git-lfs/git-lfs/blob/main/docs/api/batch.md#response-errors) to differentiate error types, but Gitea misses it in LFS. So I chose to add the TODO and finish it in another PR.

2024-07-24 12:06 UTC, 6543 commented
I added the errors here: #31697

2024-07-24 12:13 UTC, 6543 commented
ok pushing to your branch was not intendet ... well @wolfogre either keep this pull and close mine or reverte my changes on your pull if you are not ok with it etc ...

2024-07-25 09:30 UTC, wolfogre commented
Close it since #31702 finished the work.

2024-07-25 09:30 UTC, closed without merging