Fix error when non-master branch repo view
go-gitea/gitea pull request #3190
Opened 2017-12-14 06:56 UTC by lunny

As title and will fix #3181

2017-12-15 08:34 UTC, lunny commented
depend go-gitea/git#98

2017-12-16 05:04 UTC, lunny commented
also fix #3202

2017-12-16 05:05 UTC, lunny commented
And the error is still copy git vendor checksum error.

2017-12-16 05:11 UTC, lunny commented
It's unnecessary to back port since https://github.com/go-gitea/gitea/issues/3204 didn't report 500.

2017-12-18 05:58 UTC, ethantkoenig requested changes

2017-12-18 05:58 UTC, ethantkoenig commented on models/fixtures/repo_unit.yml
> +
nit: please remove extra line

2017-12-18 05:58 UTC, ethantkoenig commented on integrations/links_test.go
> +func TestRepoLinksNoLogin(t *testing.T) {
Please add to the existing test in `integrations/repo_test.go`, instead of creating a duplicate.

2018-01-08 21:21 UTC, strk commented
What's up with this PR @lunny ? Can you fix Drone ?

2018-01-08 23:22 UTC, ethantkoenig approved these changes

2018-01-08 23:22 UTC, ethantkoenig commented on integrations/repo_test.go
> +func testRepoLinksNoLogin(repoPath string, t *testing.T) {
It would be nice to combine these tests with the existing tests above, but perhaps that can be a separate PR.

2018-04-12 01:02 UTC, lunny commented
closed by #3715

2018-04-12 01:02 UTC, closed without merging