Catch os... errors
go-gitea/gitea pull request #320
Opened 2016-11-30 23:27 UTC by Bwko

2016-12-01 06:59 UTC, tboerger commented on cmd/dump.go
> +		osErr := os.Remove(fileName)
Maybe we should keep ignoring this error?

2016-12-01 06:59 UTC, tboerger commented on cmd/dump.go
> +		osErr := os.Remove(fileName)
Same here

2016-12-01 06:59 UTC, tboerger commented on cmd/serve.go
> +	goLog "log"
Do we already have a logger here?

2016-12-01 06:59 UTC, tboerger commented on cmd/web.go
> +			osLog.Fatalf("Fail to remove unix socket directory %s: %v", listenAddr, osErr)
Just use the already available logger?

2016-12-01 06:59 UTC, tboerger commented on main.go
> +	err := app.Run(os.Args)
Generally I'm wrapping this directly into println

2016-12-01 06:59 UTC, tboerger commented on models/pull.go
> +		return fmt.Errorf("Fail to removee dir %s: %v", path.Join(pr.BaseRepo.RepoPath(), headFile), err)
Typo

2016-12-01 07:26 UTC, lunny commented on cmd/dump.go
> +		osErr := os.Remove(fileName)
`_ := os.Remove(fileName)` ?

2016-12-01 07:27 UTC, lunny commented on main.go
> +	err := app.Run(os.Args)
@tboerger Don't do that. Last time, it results in a bug I spent many time to fix it.

2016-12-01 07:36 UTC, tboerger commented on main.go
> +	err := app.Run(os.Args)
But now it's not a big difference

2016-12-01 07:37 UTC, tboerger commented on main.go
> +	err := app.Run(os.Args)
It's not using any logger, it's only printing to stdout. So we will have the same bug again

2016-12-01 07:39 UTC, lunny commented on main.go
> +	err := app.Run(os.Args)
yes, don't output anything to stdout when git via ssh.

2016-12-01 08:30 UTC, bkcsoft commented on cmd/dump.go
> +		osErr := os.Remove(fileName)
Here's a dump question... Why is it deleting a file it can't create in the first place? :trollface:

2016-12-01 08:35 UTC, bkcsoft requested changes
Don't do this 😆

2016-12-01 08:35 UTC, bkcsoft commented on cmd/serve.go
> +			goLog.Fatalf("Fail to change directory %s: %v", workDir, osErr)
Printing server-internal dirs to any random client?! 😱

2016-12-01 08:37 UTC, bkcsoft commented
Overall, change the format to this instead whenever possible. Keeps errors(variables) bound to their context(block).
```
if err := os.Remove(...); err != nil {
  [...]
}
```

2016-12-01 08:45 UTC, tboerger commented on cmd/dump.go
> +		osErr := os.Remove(fileName)
Good catch :D

2016-12-01 11:08 UTC, Bwko commented on main.go
> +	err := app.Run(os.Args)
@lunny how do you want me to fix this?

2016-12-01 11:22 UTC, lunny commented on cmd/serve.go
> +	goLog "log"
^

2016-12-01 11:25 UTC, lunny requested changes

2016-12-01 11:25 UTC, lunny commented on main.go
> +	fmt.Printf("Fail to run app with %s: %v", os.Args, err)
```Go
if err != nil
```

2016-12-01 11:25 UTC, lunny commented on modules/log/log.go
> +	"log"
module/log

2016-12-01 11:25 UTC, lunny commented on modules/ssh/ssh.go
> +	osLog "log"
same

2016-12-01 21:08 UTC, strk commented on cmd/dump.go
> +		osErr := os.Remove(fileName)
Maybe zip.Create might fail some some after file creation?

2016-12-01 22:57 UTC, Bwko commented
I've updated my PR.

2016-12-02 01:12 UTC, lunny commented
LGTM

2016-12-02 01:30 UTC, lunny approved these changes

2016-12-02 06:40 UTC, bkcsoft commented on main.go
> +	err := app.Run(os.Args)
@lunny `cmd/serve.go` always returns `nil`, so this isn't really an issue here :)

2016-12-02 06:40 UTC, bkcsoft approved these changes

2016-12-02 06:41 UTC, bkcsoft commented
LGTM

2016-12-02 06:41 UTC, merged

2016-12-02 12:51 UTC, tboerger commented
This partially solves https://github.com/go-gitea/gitea/issues/257