Fix the shaking issue for avatars with an aspect ratio that is not 1:1.
go-gitea/gitea pull request #32604
Opened 2024-11-22 00:56 UTC by kerwin612

before:
![1](https://github.com/user-attachments/assets/7b8502c2-8f71-4bad-9066-410039f66065)

after:
![2](https://github.com/user-attachments/assets/9aa7516d-65e6-4639-a975-0b57e7f78ccd)

2024-11-22 14:04 UTC, silverwind commented
Hmm I'm not sure about those changes. Would like to know why it resizes in first place. Maybe you put a demo avatar on https://demo.gitea.com/ for me to investigate.

2024-11-22 15:36 UTC, kerwin612 commented
> Hmm I'm not sure about those changes. Would like to know why it resizes in first place as I thought `aspect-ratio` would prevent any such resizing. Maybe you put a demo avatar on https://demo.gitea.com/ for me to investigate.

https://upload.wikimedia.org/wikipedia/en/3/3d/Longcat_is_loooooooooong.jpg  
The image I used is for testing purposes; my environment is the latest version of Edge browser on Windows.

2024-11-25 04:58 UTC, yp05327 commented
I can reproduce it. So something has changed from 686 to 705.

2024-11-25 06:13 UTC, tboerger approved these changes

2024-11-25 06:21 UTC, yp05327 commented
As it works in 686, and the removed lines in this PR are not newly added codes, so I guess there's other reasons caused it.
Before we figure out it, I suggest pending giving more approves.

2024-11-25 06:42 UTC, wxiaoguang requested changes
I do not think this change is right if you haven't really understood the problem.

Even without the "real" problem, is it clear about: why the `width` could be remove? What if there is an avatar with width=2000 and height=100?

2024-12-02 08:23 UTC, tboerger commented
> Even without the "real" problem, is it clear about: why the `width` could be remove? What if there is an avatar with width=2000 and height=100?

That would be fixed by a max-width attribute?

2025-03-05 06:27 UTC, closed without merging