Optimize the installation page
go-gitea/gitea pull request #32994
Opened 2024-12-26 14:18 UTC by kerwin612

2024-12-26 18:59 UTC, lunny commented
Could you post a screenshot?

2024-12-27 02:31 UTC, kerwin612 commented
![image](https://github.com/user-attachments/assets/e03d42b6-5697-4b55-ae26-f6f8e4b124b4)

2024-12-27 03:52 UTC, techknowlogick approved these changes

2024-12-27 05:39 UTC, wxiaoguang commented
I would say the UI looks more ugly than before, these "installing" texts are just redundancy, and the sizes (font/image) are uncoordinated.

Since there is already an animation, I do not see why adding more sentences makes sense.

2024-12-27 05:46 UTC, kerwin612 commented
> I would say the UI looks more ugly than before, these "installing" texts are just redundancy, and the sizes (font/image) are uncoordinated.
> 
> Since there is already an animation, I do not see why adding more sentences makes sense.

![image](https://github.com/user-attachments/assets/271fc177-9ca5-480b-a08e-a12eea29123a)
Title, animation, description; not conflicting...

2024-12-27 05:50 UTC, wxiaoguang commented
> Title, animation, description; not conflicting...

Your sample screenshot is well-designed and good-looking. And it does provide more details about each step, not just keep saying "installing" again and again.

2024-12-27 11:37 UTC, delvh approved these changes
LGTM after the short fix.

2024-12-27 11:37 UTC, delvh commented on templates/post-install.tmpl
> +							<p><a id="goto-user-login" href="{{AppSubUrl}}/user/login">{{ctx.Locale.Tr "install.installing_desc"}}...</a></p>
Please add the `...` to the translated string directly

2024-12-27 11:55 UTC, wxiaoguang requested changes
No, it doesn't look good to me

2024-12-27 20:15 UTC, techknowlogick commented
I apologize if this is getting into yak-shaving territory.

I think having both "installing" and "please wait" is important, as even though there is the animation, for screen-readers they won't see that animation. This way, they'll know there is something happening that they need to wait for.

2024-12-27 20:23 UTC, wxiaoguang commented
> I apologize if this is getting into yak-shaving territory.
> 
> I think having both "installing" and "please wait" is important, as even though there is the animation, for screen-readers they won't see that animation. This way, they'll know there is something happening that they need to wait for.

At least, the page should be well-designed and good-looking. But not adding more and more uncoordinated elements.

Have you ever seen other websites or apps use such layout ? Small font, large icon, small font, keep repeating "installing", and visually misaligned?

2024-12-31 01:58 UTC, kerwin612 commented
![l1](https://github.com/user-attachments/assets/83daf50f-b114-432d-80c4-d2ddb3a9c6a7)
![l2](https://github.com/user-attachments/assets/6521f4ea-4409-4236-ab36-c81627d5ccf4)

@wxiaoguang Is this OK?

2024-12-31 02:10 UTC, wxiaoguang commented
> @wxiaoguang Is this OK?

Yes, much better than before, looks good to me.

2024-12-31 02:19 UTC, kerwin612 commented
> > @wxiaoguang Is this OK?
> 
> Yes, much better than before, looks good to me. (maybe it needs to fine tune the icon size, but it should be easy to do so)

ok, icon resized slightly, I have commited.

2024-12-31 03:48 UTC, wxiaoguang commented
Thank you very much for improving the page.

I did some tests on my side, and I think some HTML element could be optimized too since we do not need them.

And we can add `aria-hidden="true"` to the image, then no need to set "alt" or expose it to screen reader.

![image](https://github.com/user-attachments/assets/ef8aca2d-9a92-4da5-8017-279e31830346)

2024-12-31 03:52 UTC, wxiaoguang approved these changes

2024-12-31 04:01 UTC, lunny approved these changes

2024-12-31 04:49 UTC, merged