Rename gogs.go to main.go with all references
go-gitea/gitea pull request #33
Opened 2016-11-03 10:10 UTC by metalmatze

Just to stick to the Go rule of thumb for the `main.go`.

2016-11-03 10:21 UTC, xinity commented
LGTM

2016-11-03 10:35 UTC, andreynering commented on scripts/build.sh
> +go build ../main.go
Shouldn't this have `-o gitea.go`?

2016-11-03 10:35 UTC, andreynering commented on scripts/build.sh
>  	GOGS_EXE=gogs.exe
I think we should review what this does, too.

2016-11-03 10:35 UTC, andreynering commented on scripts/build_freebsd.sh
> +CGO_ENABLED=0 GOOS=$outPlattform GOARCH=$outArch go build ../main.go
Same here

2016-11-03 10:35 UTC, andreynering commented on scripts/build_linux64.sh
> +CGO_ENABLED=0 GOOS=$outPlattform GOARCH=$outArch go build ../main.go
Same here

2016-11-03 10:38 UTC, metalmatze commented
I just updated the `scripts/` because it had a reference there.
We really should get rid of the `scripts/` and try to do this with a good `Makefile`.

2016-11-03 11:46 UTC, tboerger commented on scripts/build.sh
> +go build ../main.go
AFAIK it should take the directory name, but you can prove that I'm wrong :)

2016-11-03 11:46 UTC, tboerger commented on scripts/build.sh
>  	GOGS_EXE=gogs.exe
This also needs to be fixed.

2016-11-03 11:47 UTC, tboerger requested changes
Please replace the remaining `gogs` references within the scripts folder.

2016-11-03 18:57 UTC, tboerger commented
Beside the pending gogs references in scripts it needs a rebase.

2016-11-04 02:44 UTC, bkcsoft commented on scripts/build.sh
> +go build ../main.go
Even though the file is named `main.go` this is still incorrect, since @tboerger is correct :slightly_smiling_face:

2016-11-04 09:20 UTC, bkcsoft commented
Makefile is also outdated :slightly_smiling_face:

2016-11-04 12:51 UTC, metalmatze commented
Updated my branch with a force push. Rebased against current master and improved all the things said above! 👍

2016-11-04 13:10 UTC, strk commented
More references missing, "make" ends with: `cp '/home/strk/.go/bin/gogs' `
Check the Makefile please

2016-11-04 13:12 UTC, metalmatze commented
You're right. But I don't want to touch anything in `scripts/` or the `Makefile`. @tboerger is already working on replacing the existing `Makefile` completely. @tboerger could just merge this and then add his new `Makefile`. Don't want to waste energy there. :)

2016-11-04 13:34 UTC, tboerger commented
Yes, don't touch the makefile, merge this pr :)

2016-11-04 13:35 UTC, tboerger approved these changes

2016-11-04 13:35 UTC, tboerger commented
LGTM will integrate the makefile and build scripts stuff into my PR.

2016-11-04 13:50 UTC, strk commented
LGTM

2016-11-04 13:53 UTC, DblK commented
LGTM

2016-11-04 14:58 UTC, tboerger commented
LGTM

2016-11-04 22:44 UTC, merged