Templates for extra links in top navbar and repo tool tabs.
go-gitea/gitea pull request #3308
Opened 2018-01-05 21:49 UTC by AlbertoGP

These templates add content to the top navbar and to the repository page.
This way we do not have to copy and modify the whole template, and re-modify it after upgrading Gitea if
it changes.

I'll put a comment with more details under "Custom tabs for projects in web ui #1199".

This fixes "Custom tabs for projects in web ui #1199", and the intention of "Custom Routing / new Pages?! #2115" (but without routing changes).

2018-01-06 11:27 UTC, lafriks commented
Please place them under custom folder

2018-01-06 11:36 UTC, AlbertoGP commented
Sure, no problem. Is it fine if the tmpl files do not exist by default?

Please note that both "extra_tabs.tmpl" files are just placeholders, with their content commented out so they have no effect. The real ones go indeed into "custom/templates/".

2018-01-06 14:09 UTC, lafriks commented
I think at least empty files must exist

2018-01-06 15:27 UTC, AlbertoGP commented
All right, I've made both `.tmpl` files empty.

2018-01-06 17:01 UTC, techknowlogick requested changes
@AlbertoGP I think @lafriks meant for you to put templates in the custom folder in the templates dir (so `custom/templates/custom`). The templates shouldn't go into `base` folder.

See #3051 as an example of how this has been done already. Also you can see #3286

2018-01-06 17:14 UTC, AlbertoGP commented
Oh, I see now, thanks!
I'll put them in "templates/custom/", which also means they need different file names.

2018-01-07 09:55 UTC, lafriks commented
Could you also add info about this in gitea customization docs?

2018-01-07 10:04 UTC, AlbertoGP commented
Yes, of course: I tried doing that, but got blocked by "Documentation build: Partial "header.html" not found #3306".
I found a solution for that one, but to make it into a different pull request I need to move this one to another branch, which I'm doing right now.

2018-01-07 11:26 UTC, thehowl commented
CI fails seems to be unrelated. LGTM

2018-01-07 21:14 UTC, sapk approved these changes

2018-01-07 22:14 UTC, lafriks commented on docs/content/doc/advanced/customizing-gitea.en-us.md
> +If all you want is to add extra links to the top navigation bar, or extra tabs to the repository view, you can put them in `templates/custom/extra_links.tmpl` and `templates/custom/extra_tabs.tmpl` i
please change to:
you can put them in `extra_links.tmpl` and `extra_tabs.tmpl` inside your `custom/templates/custom/` directory

2018-01-08 16:30 UTC, lafriks commented
@techknowlogick needs your approval

2018-01-08 16:58 UTC, techknowlogick approved these changes

2018-01-08 16:59 UTC, techknowlogick commented
@lafriks thanks for the ping. approved.

2018-01-10 06:19 UTC, merged