Protected branch (gogits/gogs#3921)
go-gitea/gitea pull request #339
Opened 2016-12-02 10:42 UTC by denji

gogits/gogs#3921

2016-12-02 10:44 UTC, tboerger commented
Tracking issue is https://github.com/go-gitea/gitea/issues/32

2016-12-02 10:45 UTC, bkcsoft requested changes
2 things for Gitea acceptance :)

2016-12-02 10:45 UTC, bkcsoft commented on cmd/update.go
> +	"github.com/gogits/git-module"
Wrong module :)

2016-12-02 10:45 UTC, bkcsoft commented on models/protected_branch.go
> +	PROTECTED_BRANCH_USER_ID     = "__UER_ID"
These should be in CamelCase :)

2016-12-02 10:47 UTC, strk commented on models/protected_branch.go
> +// Copyright 2014 The Gogs Authors. All rights reserved.
It's 2016 (almost 2017!) :)

2016-12-02 10:48 UTC, bkcsoft commented on models/protected_branch.go
> +// Copyright 2014 The Gogs Authors. All rights reserved.
Also `Gitea Authors` ;)

2016-12-02 10:51 UTC, strk commented
Please also take your time to document all new methods and functions.
And ideally also see if you can add automated testcases for the new functions.
This will have to wait for 1.1.0 anyway (please someone add that milestone)

2016-12-02 11:04 UTC, strk commented
@denji please on next squash-rebase change the issue referenc from gogits/gogs#3921 to #32 (gitea issue)

2016-12-02 11:25 UTC, denji commented on models/protected_branch.go
> +// Copyright 2014 The Gogs Authors. All rights reserved.
```diff
+// Copyright 2016 The Gitea Authors. All rights reserved.
// Copyright 2014 The Gogs Authors. All rights reserved.
```

2016-12-02 11:28 UTC, denji commented on cmd/update.go
> +	"github.com/gogits/git-module"
Fixed
```go
(
	"code.gitea.io/git"
)
```

2016-12-02 11:29 UTC, denji commented on models/protected_branch.go
> +	PROTECTED_BRANCH_USER_ID     = "__UER_ID"
```go
const (
	ProtectedBranchUserID     = "__USER_ID"
	ProtectedBranchRepoID     = "__REPO_ID"
	ProtectedBranchAccessMode = "__ACCESS_MODE"
)
```

2016-12-02 16:02 UTC, tboerger requested changes
Please translate only languages you are familiar with, don't use something like Google translate.

2016-12-02 16:02 UTC, tboerger commented on conf/locale/locale_de-DE.ini
> +protected_branch=Schutz-Filialen
Please don't use Google translate, these translations doesn't make sense at all

2016-12-02 16:02 UTC, tboerger commented on conf/locale/locale_en-US.ini
> +protected_branch=Protection branches
Branch protection

2016-12-02 16:02 UTC, tboerger commented on conf/locale/locale_en-US.ini
> +settings.add_protected_branch=Unprotection branch
Enable protection

2016-12-02 16:02 UTC, tboerger commented on conf/locale/locale_en-US.ini
> +settings.delete_protected_branch=Protection branch
Disable protection

2016-12-02 16:02 UTC, tboerger commented on conf/locale/locale_fi-FI.ini
> +protected_branch=Suojaa oksat
Is this also Google translate?

2016-12-02 16:02 UTC, tboerger commented on conf/locale/locale_fr-FR.ini
> +protected_branch=La Protection des branches
Is this also Google translate?

2016-12-02 16:02 UTC, tboerger commented on conf/locale/locale_it-IT.ini
> +protected_branch=Protezione rami
Is this also Google translate?

2016-12-02 16:02 UTC, tboerger commented on conf/locale/locale_lv-LV.ini
> +protected_branch=Aizsardzības filiāles
Is this also Google translate?

2016-12-02 16:02 UTC, tboerger commented on conf/locale/locale_nl-NL.ini
> +protected_branch=Bescherming van de takken
Is this also Google translate?

2016-12-02 16:02 UTC, tboerger commented on conf/locale/locale_pl-PL.ini
> +protected_branch=Oddziały ochrona
Is this also Google translate?

2016-12-02 16:02 UTC, tboerger commented on conf/locale/locale_pt-BR.ini
> +protected_branch=Proteção ramos
Is this also Google translate?

2016-12-02 16:02 UTC, tboerger commented on conf/locale/locale_ru-RU.ini
> +protected_branch=Защита веток
Is this also Google translate?

2016-12-02 16:02 UTC, tboerger commented on conf/locale/locale_sr-SP.ini
> +protected_branch=Заштита грана
Is this also Google translate?

2016-12-02 16:02 UTC, tboerger commented on conf/locale/locale_sv-SE.ini
> +protected_branch=Skydd grenar
Is this also Google translate?

2016-12-02 16:02 UTC, tboerger commented on conf/locale/locale_tr-TR.ini
> +protected_branch=Koruma şube
Is this also Google translate?

2016-12-02 16:02 UTC, tboerger commented on conf/locale/locale_zh-CN.ini
> +protected_branch=保护树枝
Is this also Google translate?

2016-12-02 16:02 UTC, tboerger commented on models/migrations/migrations.go
> +	NewMigration("set protect branches updated with created", setProtectedBranchUpdatedWithCreated),
New migrations should always go into the last row

2016-12-02 16:54 UTC, tboerger commented on cmd/update.go
> +	// UserID, _ := strconv.ParseInt(os.Getenv(models.ProtectedBranchUserID), 10, 64)
Don't need that? Than drop it?

2016-12-02 16:54 UTC, tboerger commented on cmd/update.go
> +	RepoID, _ := strconv.ParseInt(os.Getenv(models.ProtectedBranchRepoID), 10, 64)
I would say local variables start lowercase

2016-12-02 17:21 UTC, bkcsoft requested changes

2016-12-02 17:21 UTC, bkcsoft commented on modules/ssh/ssh.go
> +			os.Setenv("REMOTE_ADDR", sConn.RemoteAddr().String())
Why is this added?

2016-12-02 17:21 UTC, bkcsoft commented on cmd/serve.go
> +	os.Setenv(models.ProtectedBranchUserID, fmt.Sprintf("%d", user.ID))
This is never used...

2016-12-02 17:21 UTC, bkcsoft commented on models/protected_branch.go
> +	ProtectedBranchUserID = "__USER_ID"
Prefix them like this `GITEA_USER_ID`

2016-12-02 17:22 UTC, bkcsoft commented on models/protected_branch.go
> +	ProtectedBranchUserID = "__USER_ID"
And I'd make it `GITEA_PUSHER_ID` since that makes more sense IMO

2016-12-02 17:28 UTC, bkcsoft approved these changes

2016-12-02 17:29 UTC, bkcsoft commented
I'd need to test this before I LG_TM. I'll see if I have some time to spare this weekend

2016-12-02 17:42 UTC, tboerger commented
Such a feature indeed requires manual testing

2016-12-02 17:45 UTC, bkcsoft commented
@tboerger for now at least ;)

2016-12-03 00:06 UTC, lunny commented on conf/locale/locale_zh-CN.ini
> +protected_branch=保护树枝
I think yes

2016-12-14 10:56 UTC, lunny requested changes

2016-12-14 10:56 UTC, lunny commented on models/protected_branch.go
> +		return err
When `has == 0` then `err == nil`

2016-12-14 10:56 UTC, lunny commented on models/migrations/v15.go
> +	} else if _, err = x.Exec("UPDATE protected_branch SET updated_unix = created_unix"); err != nil {
this code is no meaning

2016-12-14 11:56 UTC, denji commented on models/protected_branch.go
> +		return err
@lunny https://github.com/go-gitea/gitea/blob/73710c00a838c0/models/repo_collaboration.go#L160-L161

2016-12-14 18:06 UTC, ethantkoenig commented on cmd/update.go
> +				log.GitLogger.Fatal(2, "Protected Branch Cann't Push")
`"... Can't ..."` or `"... Cannot ..."`?

2016-12-14 18:06 UTC, ethantkoenig commented on routers/repo/http.go
> +				log.GitLogger.Error(2, "Protected Branch Cann't Push")
`"... Can't ..."` or `"... Cannot ..."`?

2016-12-24 02:41 UTC, lunny commented
Please resolve the conflict and we could review and merge it.

2016-12-25 07:10 UTC, bkcsoft requested changes
Slight grammar fix 🙂

2016-12-25 07:10 UTC, bkcsoft commented on cmd/update.go
> +				log.GitLogger.Fatal(2, "protected branch cannot be push")
`protected branches can not be pushed to`

2016-12-29 10:42 UTC, tboerger commented on models/migrations/migrations.go
> +	NewMigration("set protect branches updated with created", setProtectedBranchUpdatedWithCreated),
You don't need this migration, this is only required if you want to update content, the structure gets automatically migrated.

2016-12-29 20:21 UTC, bkcsoft requested changes

2016-12-29 20:21 UTC, bkcsoft commented on options/locale/locale_en-US.ini
> +settings.protected_branch_can_push_no=You can't push
`You can not push`

2016-12-29 20:21 UTC, bkcsoft commented on options/locale/locale_en-US.ini
> +settings.protected_branch_deletion_desc=The branch will be writable for developers. Are you sure?
maybe not use the term `developers`...

2016-12-29 21:27 UTC, bkcsoft requested changes
Sorry that I'm being a pain... :(

2016-12-29 21:27 UTC, bkcsoft commented on options/locale/locale_en-US.ini
> +settings.protected_branch_deletion_desc=The branch will be writable. Are you sure?
`Anyone with write permissions will be able to push directly to this branch. Are you sure?`

2016-12-30 13:44 UTC, bkcsoft approved these changes

2016-12-30 13:45 UTC, bkcsoft commented
LGTM

2016-12-30 16:29 UTC, lunny approved these changes

2016-12-30 16:42 UTC, lunny commented
[...ters/repo/setting.go:389 ProtectedBranch()] [E] GetProtectedBranches: no such table: protected_branch

You have to add `setProtectedBranchUpdatedWithCreated` to `odels/migrations/migrations.go`

2016-12-31 01:54 UTC, lunny commented
`html/template: "repo/settings/protected_branch" is undefined`, maybe you forget to add it to git?

2016-12-31 09:40 UTC, lunny requested changes
`html/template: "repo/settings/protected_branch" is undefined`

2016-12-31 09:40 UTC, lunny commented on cmd/serve.go
> +	log.GitLogger.Trace("User:%s access:%v repository:%s reponame:%s ip:%s", user.Name, requestedMode, repoPath, reponame, os.Getenv("REMOTE_ADDR"))
This line will panic when `git clone` an empty repo via SSH.

2016-12-31 09:40 UTC, lunny commented on models/migrations/v15.go
> +	"time"
This file name should be renamed to v16.go since v15.go has been used by another PR just merged.

2016-12-31 09:40 UTC, lunny commented on models/protected_branch.go
> +		return err
This line is OK.

2016-12-31 09:59 UTC, lunny commented
@ningdb, Could you see this PR?

2016-12-31 22:55 UTC, denji commented on models/protected_branch.go
> +		return err
@lunny https://github.com/go-xorm/xorm/commit/d75356fc733fce7683c6d961fc2aeb16ededc8ef ?

2017-01-11 19:24 UTC, Bwko commented
Don't know if this is normal, but it only shows this button: ![screenshot from 2017-01-11 20-21-24](https://cloud.githubusercontent.com/assets/23573579/21862950/b90c3a4a-d83b-11e6-81a4-673be48d04ce.png)
 When I press the button nothing happens, console log: `Completed /bwko/ddd/settings/branches 302 Found in 40.46314ms
`

2017-01-12 04:27 UTC, lunny commented
This is not completed.

2017-01-13 02:05 UTC, ethantkoenig requested changes

2017-01-13 02:05 UTC, ethantkoenig commented on cmd/serve.go
> +	os.Setenv(models.ProtectedBranchRepoID, fmt.Sprintf("%d", repo.ID))
Minor, but `strconv.Itoa` would probably be better than `fmt.Sprintf` here.

2017-01-13 02:05 UTC, ethantkoenig commented on routers/repo/http.go
> +	params[models.ProtectedBranchUserID] = fmt.Sprintf("%d", authUser.ID)
^

2017-01-13 02:05 UTC, ethantkoenig commented on routers/repo/http.go
> +	params[models.ProtectedBranchRepoID] = fmt.Sprintf("%d", repo.ID)
^

2017-01-27 06:39 UTC, lunny commented
@denji  conflicted?

2017-01-27 08:46 UTC, denji commented on routers/repo/http.go
> +	params[models.ProtectedBranchRepoID] = fmt.Sprintf("%d", repo.ID)
Itoa(int), repo.ID(int64)

2017-02-02 07:26 UTC, lunny commented
is this still wip?

2017-02-05 01:39 UTC, lunny commented
conflicted

2017-02-07 15:47 UTC, lunny commented
@denji I think this is still wip, any plan for this PR? I think This PR is very important for v1.1. If you have no more time on this PR. I would like to continue your work.

2017-02-09 03:56 UTC, lunny commented
See screenshot.
![untitled](https://cloud.githubusercontent.com/assets/81045/22768697/bb84d3a6-eebe-11e6-876b-ba67398c70cd.png)

2017-02-09 03:58 UTC, lunny approved these changes

2017-02-09 04:09 UTC, bkcsoft requested changes
Apart from this, there's a bunch of things that don't belong in this PR, like consistency-tests was updated for something completely different, there's been touches on Star-counts which doesn't belong here either. This needs to be fixed first :) (I'm assuming it's because of a broken rebase/merge on master)

2017-02-09 04:09 UTC, bkcsoft commented on cmd/serve.go
> +	// log.GitLogger.Trace("User:%s access:%v repository:%s reponame:%s ip:%s", user.Name, requestedMode, repoPath, reponame, os.Getenv("REMOTE_ADDR"))
Why is this here? commented?

2017-02-09 06:10 UTC, lunny commented on cmd/serve.go
> +	// log.GitLogger.Trace("User:%s access:%v repository:%s reponame:%s ip:%s", user.Name, requestedMode, repoPath, reponame, os.Getenv("REMOTE_ADDR"))
done.

2017-02-09 06:12 UTC, lunny commented
It's ready now for review.

2017-02-09 08:14 UTC, bkcsoft approved these changes

2017-02-11 10:12 UTC, tboerger commented on models/migrations/migrations.go
> +	NewMigration("set protect branches updated with created", setProtectedBranchUpdatedWithCreated),
It's an entirely new struct, that doesn't need any migration because of the anyway executed sync function

2017-02-11 11:00 UTC, lunny commented on models/migrations/migrations.go
> +	NewMigration("set protect branches updated with created", setProtectedBranchUpdatedWithCreated),
No. Sync on a migration is better safe. I have found the original method's bug, see #871. When you upgrade from an old version which haven't a column external_tracker_url, then a new version add this column by Sync not migration. but another new version will use this column, then the bug occupied.

2017-02-11 17:25 UTC, ethantkoenig commented on routers/repo/http.go
> +	params[models.ProtectedBranchRepoID] = fmt.Sprintf("%d", repo.ID)
Okay, nvm

2017-02-11 17:25 UTC, ethantkoenig approved these changes

2017-02-20 07:41 UTC, strk commented
For the record: Gogs got this via https://github.com/gogits/gogs/commit/7e09d210ba421a1baf03ef7ba8770bebe8d28b72

2017-02-20 08:53 UTC, tboerger commented on options/locale/TRANSLATORS
> +Denis Denisov <denji0k AT gmail DOT com>
This should be added to all our repos ;)

2017-02-20 08:54 UTC, tboerger commented on options/locale/locale_ru-RU.ini
> +settings.branches=Ветки
Since we switched to crowdin this have to be done within crowdin, otherwise we get into issues while we try to sync it.

2017-02-20 08:56 UTC, tboerger commented on templates/repo/settings/branches.tmpl
> +{{template "base/head" .}}
This file is generally not really good indented. Please fix the indentation.

2017-02-20 08:56 UTC, tboerger commented on templates/repo/settings/navbar.tmpl
> +		<a class="{{if .PageIsSettingsBranches}}active{{end}} item" href="{{.RepoLink}}/settings/branches">
Indent by one level

2017-02-20 08:57 UTC, tboerger approved these changes
I have added some minor comments, but otherwise I'm fine with that.

2017-02-20 13:39 UTC, strk commented on cmd/update.go
> +			fail("protected branches can not be pushed to", "protected branches can not be pushed to")
is .Fatal not really fatal that you add a fail() call afterwards ?

2017-02-20 13:59 UTC, strk commented
I've given this code a try but I'm refused any push, even to branches which are not protected.
The client says:
```
error: RPC failed; result=22, HTTP code = 403
fatal: The remote end hung up unexpectedly
fatal: The remote end hung up unexpectedly
Everything up-to-date
```

The server (http.log) says:
```
2017/02/20 14:58:17 [...routers/repo/http.go:462 serviceRPC()] [E] protected branches can not be pushed to
```

2017-02-20 14:05 UTC, strk commented
Also, the "Delete" button doesn't work, despite endpoint returnin 200 OK the protected branches are still listed in the "Branches" page in repository setting.

2017-02-20 14:18 UTC, lunny commented
Yes. I'm fixing that.

2017-02-20 14:19 UTC, lunny commented on cmd/update.go
> +			fail("protected branches can not be pushed to", "protected branches can not be pushed to")
indeed a problem.

2017-02-20 15:10 UTC, lunny commented on cmd/update.go
> +			fail("protected branches can not be pushed to", "protected branches can not be pushed to")
done.

2017-02-20 15:11 UTC, lunny commented on templates/repo/settings/branches.tmpl
> +{{template "base/head" .}}
done.

2017-02-20 15:11 UTC, lunny commented on options/locale/locale_ru-RU.ini
> +settings.branches=Ветки
removed this.

2017-02-20 15:11 UTC, lunny commented on options/locale/TRANSLATORS
> +Denis Denisov <denji0k AT gmail DOT com>
removed this.

2017-02-20 15:11 UTC, lunny commented
@strk please confirm.

2017-02-20 16:03 UTC, strk commented
@lunny just tried but still doesn't work for me. I hit "Delete" on a protected branch and it still sits there.
Also, I cannot push to a _new_ branch either.

2017-02-21 00:47 UTC, lunny commented
@strk please delete the old branch and fetch the newest branch.

2017-02-21 13:39 UTC, strk commented
LGTM after rebasing to current master (70ae6d197b28f018264798b07a16bf3acc36405c) and testing briefly. Note that the Gogs version of protected branches has a more fine-grained configuration for branch protection, you can check it on try.gogs.io.

2017-02-21 14:46 UTC, lunny commented
@strk Yes. We will improve the protected branch on v1.2.

2017-02-21 15:02 UTC, merged