Run goimports on the whole project
go-gitea/gitea pull request #34
Opened 2016-11-03 10:20 UTC by metalmatze

When opening this repository in my editor, I run goimports automatically. This is what it found.

2016-11-03 11:42 UTC, tboerger commented
LGTM

2016-11-03 16:49 UTC, lunny commented
LGTM

2016-11-03 16:52 UTC, strk commented
Could you please rebase and fix conflicts ?

2016-11-03 16:54 UTC, DblK commented
Since master has changed, @metalmatze can you update your PR?
Thanks

2016-11-03 18:58 UTC, tboerger commented
Please rebase as @strk mentioned.

2016-11-04 09:32 UTC, bkcsoft requested changes

2016-11-04 09:32 UTC, bkcsoft commented on modules/markdown/markdown_test.go
> +	. "github.com/gogits/gogs/modules/markdown"
nope

2016-11-04 09:32 UTC, bkcsoft commented on modules/markdown/markdown_test.go
>  	"github.com/gogits/gogs/modules/setting"
nope

2016-11-04 09:32 UTC, bkcsoft commented on models/repo_test.go
> +	. "github.com/gogits/gogs/models"
This needs to be changed

2016-11-04 09:32 UTC, bkcsoft commented on models/repo_test.go
>  	"github.com/gogits/gogs/modules/markdown"
and this

2016-11-04 10:08 UTC, metalmatze commented
Recreated the commit with the current `master`.
Wrong import paths are gone too. Sorry @bkcsoft.

2016-11-04 11:57 UTC, merged