Add the ability to use multiple labels as filters
go-gitea/gitea pull request #3438
Opened 2018-01-31 13:09 UTC by erjiaqing

Implements Issue #3430 

![multiplelabels](https://user-images.githubusercontent.com/5517838/35624310-9ba558f2-06c9-11e8-8b89-1fd16c3f73f8.png)

As in GitHub, when selecting multiple labels, only display those issues with all the labels selected.

I cannot figure out how to achieve this using the orm provided, so I write a subquery.

Then I use `Label.QueryString` and `Label.IsSelected` for the query string(issues?labels=xxx) and the tick before labels.

2018-02-02 19:25 UTC, jonasfranz requested changes

2018-02-02 19:25 UTC, JonasFranzDEV commented on models/issue_label.go
> +func (label *Label) CalQueryString(query []string) {
You should rename `query []string` to `labels []string`.
I think that the function name is not very self-explanatory at the first place. It should be renamed into `RestoreSelectedLabels` or `LoadSelectedLabelsFromQuery`.

2018-02-03 06:19 UTC, erjiaqing commented
In GitHub, when multiple labels are selected, only issues with **all of** the selected labels will be shown. However, in test, it is assumed that issues with **at least one of** the selected labels will be shown.
Maybe I have to change the tests?

2018-05-22 11:28 UTC, ernierasta commented
Drone will not show, what is the problem with CI... so I have no idea how serious problem with this commit is ...

This would be life saver, is there reason why it is not merged?
Can we make it merge? ;-)

2018-05-22 12:28 UTC, erjiaqing commented
I could remember that the last time, it reports that my commit cannot pass the unit test
it is because that:
```
 			IssuesOptions{
 				Labels:   "1,2",
 				Page:     1,
 				PageSize: 4,
 			},
-			[]int64{5, 2, 1},
+			[]int64{1}, // issues with **both** label 1 and 2, only issue 1 matches
 		},
```

I made a net  commit, and it should pass the test now, and this time, it reports another failure
I have no idea about this, maybe the structure of database had changed a lot
@ernierasta 
(I don't know if you will be notified for this)

2018-05-22 16:46 UTC, lafriks commented on models/issue.go
> +				Where(fmt.Sprintf(`issue.id IN (
Can't this be built using builder? cc: @lunny

2018-06-30 14:29 UTC, yasuokav commented
https://github.com/erjiaqing/gitea/blob/5f08f1bc0ac685c8e0fd983ca652ee363625395f/templates/repo/issue/list.tmpl#L135
```
<span class="octicon {{if eq $.SelectLabels .ID}}octicon-check{{end}}"></span><span class="label color" style="background-color: {{.Color}}"></span> {{.Name}}
```
`eq $.SelectLabels .ID` -> `.IsSelected`?

https://github.com/erjiaqing/gitea/blob/5f08f1bc0ac685c8e0fd983ca652ee363625395f/routers/repo/issue.go#L243
```
ctx.Data["SelectLabels"] = com.StrTo(selectLabels).MustInt64()
```
`selectLabels` is no longer an int

2018-07-09 00:09 UTC, bkcsoft commented on models/issue.go
> +			} else if len(labelIDs) == 1 {
This query could be fixed to do `> 0` instead of having 2 different queries

2019-01-19 07:35 UTC, closed without merging