Reduce repo indexer disk usage
go-gitea/gitea pull request #3452
Opened 2018-02-03 20:40 UTC by ethantkoenig

Reduces disk usage of the repo (i.e. code) indexer:
- Disables bleve's `_all` field (which meant that we were previously storing everything twice)
- Use the bleve unique token filter (https://github.com/blevesearch/bleve/pull/739), since we only display the first occurrence of the search term.

I saw as roughly 3x (1.5GB -> 500MB) reduction in disk usage as a result of these changes (of course, mileage will vary depending on what type of text/code you are indexing).

Also introduces a migration-like versions to the issue and repo indexers to facilitate changes (which will typically require rebuilding the index).

Yes, this PR shamelessly pulls in https://github.com/ethantkoenig/rupture as a dependency to facilitate tracking indexer versions and migrations; I am aware of no other alternatives.

2018-02-03 20:49 UTC, lafriks commented on modules/indexer/issue.go
>  	docMapping.AddFieldMappingsAt("RepoID", bleve.NewNumericFieldMapping())
Should this use `numericFieldMapping`?

2018-02-03 21:06 UTC, ethantkoenig commented on modules/indexer/issue.go
>  	docMapping.AddFieldMappingsAt("RepoID", bleve.NewNumericFieldMapping())
Yes, fixed

2018-02-04 08:35 UTC, lafriks approved these changes

2018-02-04 09:46 UTC, appleboy requested changes

2018-02-04 17:14 UTC, ethantkoenig commented
@appleboy Done

2018-02-05 08:43 UTC, appleboy approved these changes

2018-02-05 09:08 UTC, lafriks commented
@ethantkoenig please resolve conflicts

2018-02-05 17:38 UTC, ethantkoenig commented
@lafriks Resolved

2018-02-05 18:29 UTC, merged