Implement sendmail
go-gitea/gitea pull request #355
Opened 2016-12-05 21:43 UTC by couling

Implemented `sendmail` as an alternative to SMTP.
A number of gogs users have requested the ability to use `sendmail` as an alternative to SMTP: https://github.com/gogits/gogs/issues/997
For some users setting up SMTP accounts for gogs is a lot more trouble than it's worth.

To keep this change simple I've not added any addational configuration parameter.  Instead I've reused the SMTP host.  If this contains a "/" then it will be interpreted as the location of the sendmail binary.  This is safe because hostnames can't contain slashes. 

Other fields such as username and password will be ignored for sendmail.

2016-12-06 08:50 UTC, tboerger commented
I prefer real config options for that.

2016-12-06 08:51 UTC, tboerger commented
Beside that the linting fails within Drone.

2016-12-06 09:52 UTC, couling commented
Okay. I'll take a look and re-submit

2016-12-06 11:56 UTC, bkcsoft requested changes

2016-12-06 11:56 UTC, bkcsoft commented on modules/mailer/mailer.go
> +func (s *Sender) sendSendmail(from string, to []string, msg io.WriterTo) error {
This should really be implemented as a separate `Sender` instead, this way you don't have to do checks for every single sent email...

Config-reading and setup could be done here: https://github.com/go-gitea/gitea/pull/355/files#diff-bdf9b0a2ed1413ee986db72787e5b5d7R265

2016-12-07 19:37 UTC, couling commented
Okay. These changes should have addressed previous concerns.

2016-12-08 12:42 UTC, bkcsoft approved these changes

2016-12-24 02:47 UTC, lunny commented
LGTM

2016-12-25 13:54 UTC, bkcsoft commented
LGTM

2016-12-25 13:55 UTC, merged

2016-12-25 14:55 UTC, lunny commented
And maybe we need add some docs for all the new features after it is merged.

2017-01-04 20:01 UTC, couling commented
@lunny What would the best place to document this be?

2017-01-04 22:59 UTC, lunny commented
send PR to github.com/go-gitea/docs