Bug fix for edit-hook API endpoint
go-gitea/gitea pull request #365
Opened 2016-12-07 21:45 UTC by ethantkoenig

This fixes a bug in the `PATCH /repos/:ownername/:reponame/hooks/:id` API endpoint. Previously the response contained old information about the webhook; for instance, if a webhook had a url of `urlA`, and I made a request to update the url to `urlB`, the returned JSON object previously would have a `"url"` field of `urlA`, not `urlB`. 

Now the response contains the updated information (e.g. `urlB`).

I wasn't able to figure out a way to fix this without doing another call to `models.GetWebhookByRepoID`; if you find a way to avoid the second call, please let me know!

2016-12-08 12:36 UTC, bkcsoft requested changes
Otherwise it looks fine 🙂 (and what I did previously for labels IIRC)

2016-12-08 12:36 UTC, bkcsoft commented on routers/api/v1/repo/hook.go
> +	repoID := ctx.Repo.Repository.ID
Why the need for this? it's already pre-fetched :)

2016-12-08 14:04 UTC, ethantkoenig commented on routers/api/v1/repo/hook.go
> +	repoID := ctx.Repo.Repository.ID
Fixed.

2016-12-09 15:41 UTC, tboerger commented
If refetching is required LGTM

2016-12-09 19:11 UTC, bkcsoft approved these changes

2016-12-09 19:11 UTC, merged