Store OAuth2 session data in database
go-gitea/gitea pull request #3660
Opened 2018-03-12 19:37 UTC by lafriks

Currently OAuth2 sessions are saved only on filesystem in sessions directory independently of where gitea session is actually saved

2018-03-13 01:29 UTC, lunny requested changes

2018-03-13 01:29 UTC, lunny commented on vendor/github.com/lafriks/xormstore/xormstore.go
> +		st.e.Sync2(&xormSession{tableName: st.opts.TableName})
The error should be handled.

2018-03-13 01:31 UTC, lunny commented
@lafriks why save OAuth session to database not in file system?

2018-03-13 07:07 UTC, lafriks commented
@lunny probably currently there is no real reason. I wrote this code when trying to fix oath2 bug but error that file session storage was throwing about trying to delete unexisting file was just a consequence not a real source for that bug.
But more generally speaking this could be useful in future as currently we can specify to store Gitea session data in redis for example but oauth2 sessions will still be saved in file system so Gitea can not be load balanced because of that as if first request before redirecting to auth2 authorization service would hit one node and create session, if second request after authorization would hit other node, it would not know about such session and would fail with error.

2018-03-13 07:10 UTC, lunny commented
@lafriks seems good enough. Please follow my review, otherwise LGTM.

2018-03-18 19:52 UTC, jonasfranz requested changes
I get the following error if I try to login via github oauth at my local gitea instance:

`2018/03/18 20:49:52 [...routers/user/auth.go:411 handleOAuth2SignIn()] [E] UserSignIn: could not find a matching session for this request`

2018-03-18 19:52 UTC, JonasFranzDEV commented on modules/auth/oauth2/oauth2.go
> +		TableName: "oauth2_sessions",
IMHO we should use `oauth2_session` instead of `oauth2_sessions` because we currently use the singular for table names.

2018-03-18 22:31 UTC, lafriks commented
@JonasFranzDEV did you clear cookies (could be that some old cookie still be left that was stored in file system)>

2018-03-19 10:23 UTC, jonasfranz requested changes

2018-03-19 10:23 UTC, JonasFranzDEV commented on vendor/github.com/lafriks/xormstore/xormstore.go
> +	ID          string         `xorm:"VARCHAR(400) PK NAME 'id'"`
`VARCHAR(400)` results in an error when I use mysql:
```
panic: Error 1071: Specified key was too long; max key length is 767 bytes

goroutine 1 [running]:
code.gitea.io/gitea/vendor/github.com/lafriks/xormstore.NewOptions(0xc4206680b0, 0x113ce57, 0xf, 0xc42067d600, 0xc4206fb8f0, 0x1, 0x1, 0x0)
	/mnt/local_storage/jonasfranz/Go/src/code.gitea.io/gitea/vendor/github.com/lafriks/xormstore/xormstore.go:108 +0x2d2
code.gitea.io/gitea/modules/auth/oauth2.Init(0xc4206680b0)
	/mnt/local_storage/jonasfranz/Go/src/code.gitea.io/gitea/modules/auth/oauth2/oauth2.go:44 +0xb9
code.gitea.io/gitea/models.InitOAuth2()
	/mnt/local_storage/jonasfranz/Go/src/code.gitea.io/gitea/models/oauth2.go:101 +0x3f
code.gitea.io/gitea/routers.GlobalInit()
	/mnt/local_storage/jonasfranz/Go/src/code.gitea.io/gitea/routers/init.go:63 +0x56e
code.gitea.io/gitea/cmd.runWeb(0xc420344000, 0x0, 0x0)
	/mnt/local_storage/jonasfranz/Go/src/code.gitea.io/gitea/cmd/web.go:83 +0xa8
code.gitea.io/gitea/vendor/github.com/urfave/cli.HandleAction(0xfb0900, 0x117e690, 0xc420344000, 0xc42020f440, 0x0)
	/mnt/local_storage/jonasfranz/Go/src/code.gitea.io/gitea/vendor/github.com/urfave/cli/app.go:471 +0xad
code.gitea.io/gitea/vendor/github.com/urfave/cli.(*App).Run(0xc4200d5040, 0xc420030190, 0x1, 0x1, 0x0, 0x0)
	/mnt/local_storage/jonasfranz/Go/src/code.gitea.io/gitea/vendor/github.com/urfave/cli/app.go:246 +0x542
main.main()
	/mnt/local_storage/jonasfranz/Go/src/code.gitea.io/gitea/main.go:52 +0x40e
```
The error is returned at line 106 and is actually not handled!

When I change this to `VARCHAR(200)` for example, no error is thrown.

2018-03-19 10:24 UTC, JonasFranzDEV commented
@lafriks Now the authentication works (except the error reported (mysql)) but the table is empty. Is that an excepted behaviour?

2018-03-19 11:04 UTC, lafriks commented
@JonasFranzDEV it depends on goth lib usage and in how it is currently done in gitea it seams to store session only between when you redirect to oauth2 provider and when you get session back.

2018-04-09 10:54 UTC, lafriks commented
@lunny @JonasFranzDEV fixed

2018-04-09 11:27 UTC, lunny approved these changes

2018-04-10 18:08 UTC, jonasfranz approved these changes

2018-04-29 06:04 UTC, lafriks commented
Make LG-TM work

2018-04-29 06:06 UTC, lunny commented
@lafriks this pr is update to latest master commit. Code Review is passed already.

2018-04-29 06:09 UTC, merged