Switch syntax highlighting to PrismJS
go-gitea/gitea pull request #3685
Opened 2018-03-18 01:18 UTC by lafriks

Looks to be working fine except for diff views that still needs to be fixed. Would need some help on testing more source code to see if it does not break.

Fixes #3682

2018-03-18 02:01 UTC, appleboy approved these changes

2018-03-18 05:56 UTC, lunny requested changes

2018-03-18 05:56 UTC, lunny commented on modules/highlight/highlight.go
> +		".py":    "python",
There is no `.go` support?

2018-03-18 09:43 UTC, lafriks commented on modules/highlight/highlight.go
> +		".py":    "python",
There is, just in other dict

2018-03-18 10:49 UTC, lunny approved these changes

2018-03-18 23:53 UTC, lafriks commented
I have fixed diff view but currently changed line part highlight is still lost

2018-12-30 11:15 UTC, lafriks commented
That has to be tested

2019-01-23 18:14 UTC, techknowlogick commented
Closing due to performance reasons, and also because we will be switching to server side rendering (likely using chroma)

2019-01-23 18:14 UTC, closed without merging

2020-06-08 08:22 UTC, GitMensch commented
> Closing [...] because we will be switching to server side rendering (likely using chroma)

Reference: #7729.