Fix goreportcard badge link
go-gitea/gitea pull request #3709
Opened 2018-03-22 18:17 UTC by aalmiray

goreportcard does not handle correctly vanity links (see https://github.com/gojp/goreportcard/issues/192)
This PR updates the badge link to https://goreportcard.com/report/github.com/go-gitea/gitea

2018-03-23 01:40 UTC, thehowI commented
Stop wasting time. This is useless.

2018-03-23 03:13 UTC, techknowlogick requested changes
@aalmiray Thank you for this PR, while I am putting a no vote towards it, I do want to thank you for taking time to submit a PR, and I hope this doesn't discourage any future contributions.

The reason I am putting a "no" vote is because:
 `We are using custom Go import paths, this is comparable with the functionality delivered via gopkg.in, this gives us the flexibility to change the code hosting at any point in time in the case we want to start dogfooding ourself with hosting Gitea on Gitea.`

2018-03-23 06:16 UTC, thehowl commented
just to be clear: @thehowi is a copycat, not actually me

2018-05-18 09:19 UTC, lunny commented
As @techknowlogick said.

2018-05-18 09:19 UTC, closed without merging