Set default branchname on first push
go-gitea/gitea pull request #3715
Opened 2018-03-24 23:53 UTC by Bwko

Fixes #3204

2018-03-25 01:08 UTC, lunny requested changes

2018-03-25 01:08 UTC, lunny commented on models/action.go
> +		if err = repo.UpdateDefaultBranch(); err != nil {
why not update on line 536?

2018-03-25 12:11 UTC, jonasfranz approved these changes

2018-03-25 12:17 UTC, appleboy approved these changes

2018-03-25 12:18 UTC, lafriks commented
@lunny need your approval

2018-03-25 12:47 UTC, lunny approved these changes

2018-03-25 13:00 UTC, merged

2018-03-25 20:02 UTC, lafriks commented
@Bwko please backport to release/v1.4 branch

2018-04-11 18:10 UTC, lafriks commented
@Bwko small reminder ;)

2018-05-07 16:29 UTC, davidlt commented
This is a bit annoying for people doing `git clone --mirror` / `git push --mirror` and expecting `master` to be the default. This broke my workflow because now the first pushed branch becomes defaults, which is a bit random if you do `git push --mirror` and you have to go in the settings after each `git push --mirror` to set it to `master`.

2018-05-07 16:31 UTC, lafriks commented
@davidlt please open issue