Add EnableTimetracking option to app settings
go-gitea/gitea pull request #3719
Opened 2018-03-25 13:38 UTC by Bwko

Add an option to completely disable the time tracking feature.

2018-03-25 13:51 UTC, appleboy approved these changes

2018-03-25 18:17 UTC, lafriks requested changes
Also setting in repository settings should be hidden if global setting is set to false. Also would be nice if this would be added to admin server option list in UI

2018-03-25 18:17 UTC, lafriks commented on modules/setting/setting.go
>  	Service.DefaultEnableTimetracking = sec.Key("DEFAULT_ENABLE_TIMETRACKING").MustBool(true)
Shouldn't default be false if timetracking is disabled in server?

2018-03-26 21:40 UTC, Bwko commented
@lafriks I've updated my PR.

2018-03-28 18:25 UTC, JonasFranzDEV commented
@Bwko What is the default value of this option?

2018-03-28 19:42 UTC, Bwko commented
The time tracking is enabled by default

2018-04-09 09:55 UTC, lafriks approved these changes

2018-04-09 15:15 UTC, merged