Use the active branch for the code tab
go-gitea/gitea pull request #3720
Opened 2018-03-25 14:29 UTC by Bwko

Fixes #2147

2018-03-25 15:23 UTC, appleboy approved these changes

2018-03-25 18:06 UTC, jonasfranz approved these changes

2018-03-25 18:49 UTC, lafriks requested changes
Currently it breaks link at least from multiple places and it should be at least:
`{{if (and (not .IsBareRepo) (ne .BranchName .BaseRepo.DefaultBranch) .BranchLink)}}{{.BranchLink}}{{else}}{{.RepoLink}}{{end}}`

Also it does not seem to go to correct branch from commit lists as `BranchLink` does not seem to have value set in that handler

2018-03-27 19:00 UTC, Bwko commented
@lafriks Fixed

2018-04-09 09:54 UTC, lafriks approved these changes

2018-04-09 10:27 UTC, tonivj5 approved these changes

2018-04-09 10:34 UTC, merged

2018-04-09 10:34 UTC, lafriks commented
@Bwko please backport to release/1.4