API Endpoints for collaborators
go-gitea/gitea pull request #375
Opened 2016-12-12 02:03 UTC by ethantkoenig

Adds the following endpoints:
- `GET repos/:username/:reponame/collaborators`: list collaborator
- `GET repos/:username/:reponame/collaborators/:collaborator`: check if a user is a collaborator
- `DELETE repos/:username/:reponame/collaborators/:collaborator`: remove a collaborator

These endpoints are part of [the Github API](https://developer.github.com/v3/repos/collaborators/)

2016-12-12 21:44 UTC, bkcsoft commented
Relevant functions needed in `go-sdk` as well :)

2016-12-24 02:52 UTC, lunny commented
But there is no permission check?

2016-12-24 03:25 UTC, ethantkoenig commented
@lunny Fixed. I also added a check for the existing `PUT repos/:username/:reponame/collaborators/:collaborator` endpoint.

2016-12-25 13:50 UTC, bkcsoft requested changes

2016-12-25 13:50 UTC, bkcsoft commented on routers/api/v1/repo/collaborators.go
> +	if access < models.AccessModeWrite {
This should only be checked for private repos. For public repos anyone can fetch the list of collaborators :)

2016-12-25 13:50 UTC, bkcsoft commented on routers/api/v1/repo/collaborators.go
> +	if access < models.AccessModeWrite {
same as above

2016-12-26 00:16 UTC, ethantkoenig commented on routers/api/v1/repo/collaborators.go
> +	if access < models.AccessModeWrite {
It is always checked in the Github API, even for public repos.

2016-12-26 06:57 UTC, bkcsoft commented on routers/api/v1/repo/collaborators.go
> +	if access < models.AccessModeWrite {
ooh nvm then 😄

2016-12-26 06:57 UTC, bkcsoft approved these changes

2016-12-26 06:58 UTC, bkcsoft commented
LGTM

2016-12-26 07:32 UTC, lunny commented
LGTM

2016-12-26 07:37 UTC, merged