Fix to 3819 - Filtering issues by tags on main screen issues
go-gitea/gitea pull request #3824
Opened 2018-04-20 16:32 UTC by rvillablanca

This PR solves the issue 3819 where you can't filter issues by pressing on the tags.

Because there is a Default label set, there are many tags with same color and name like `bug`, but they have differents id so when you filter by pressing in one tag, you are filtering only for one repo.

Maybe this could be improved with another PR.

2018-04-20 17:52 UTC, techknowlogick commented
Just commenting here with issue ID so GitHub links them: #3819

2018-05-26 10:43 UTC, jonasfranz requested changes

2018-05-26 10:43 UTC, JonasFranzDEV commented on routers/user/home.go
> +	opts.Labels = selectLabels
Replace this with:
```go
opts.Labels = ctx.Query("labels")
```

2018-05-27 20:40 UTC, rvillablanca commented on routers/user/home.go
> +	opts.Labels = selectLabels
@JonasFranzDEV done!

2018-05-29 19:08 UTC, rvillablanca commented
I don't understand why Drone generates errors when compiling. I have updated the branch but It seems Drone couldn't get updated sources.
Ref commit: https://github.com/go-gitea/gitea/pull/3824/commits/7243ed9b4e19aad4b2073ed11d8488434f603d53

2018-05-29 19:14 UTC, techknowlogick commented
@rvillablanca This is an issue with Github where sometimes it caches old information. Let me re-trigger drone and likely the updated information will be loaded.

2018-10-19 12:14 UTC, lafriks commented
@JonasFranzDEV need your approval

2018-10-28 03:13 UTC, naiba commented
@JonasFranzDEV @lunny @lafriks Hi, Can you merge this PR? can wait for #5131

2018-10-28 03:16 UTC, techknowlogick approved these changes

2018-10-28 03:17 UTC, techknowlogick commented
@naiba This needs two successful approvals before it can be merged.

2018-10-28 05:56 UTC, lunny commented
@JonasFranzDEV need your approval.

2018-10-28 06:07 UTC, jonasfranz approved these changes

2018-10-28 06:55 UTC, merged

2018-10-28 07:18 UTC, techknowlogick commented
@rvillablanca thanks for the PR. Would you be able to backport this commit to the release/v1.6 branch? If you need any assistance or clarification please let me know and I'd be happy to help.

2018-10-29 17:41 UTC, rvillablanca commented
@techknowlogick I have created a PR #5219 for this purpose :+1:

2018-10-30 00:37 UTC, lunny commented
@techknowlogick I think we should keep the backport label even if this is merged.

2018-10-30 00:42 UTC, techknowlogick commented
@lunny ok.