Do not allow to reuse TOPT passcode
go-gitea/gitea pull request #3878
Opened 2018-05-01 18:13 UTC by lafriks

2018-05-01 20:55 UTC, cezar97 commented
Thank you for taking care of the security issues reported, even those with lower priority and exploitability like this one.

2018-05-01 20:58 UTC, techknowlogick commented
LGTM

2018-05-02 02:56 UTC, techknowlogick requested changes

2018-05-02 02:56 UTC, techknowlogick commented on models/migrations/migrations.go
> +	NewMigration("add last used passcode column for TOPT", addLastUsedPasscodeTOPT),
Incorrect acronym, this should be `TOTP` (per: https://en.wikipedia.org/wiki/Time-based_One-time_Password_algorithm). There are other places in this PR that have the incorrect acronym.

Sorry for noticing this after my LG-TM, this should be an easy fix though.

2018-05-02 04:49 UTC, jonasfranz approved these changes
LGTM except the typo reported

2018-05-02 05:46 UTC, lafriks commented
@techknowlogick fixed

2018-05-02 07:25 UTC, appleboy approved these changes

2018-05-02 13:55 UTC, techknowlogick approved these changes

2018-05-02 13:55 UTC, techknowlogick commented
thanks @lafriks, I've just approved.

2018-05-02 14:04 UTC, daviian requested changes
Can we just store the hash of it instead of the plain passcode? Seems to be a more trustable approach to solve this.
My gut says this should be handled as sensitive information.

2018-05-02 14:26 UTC, lafriks commented
@daviian it is one time usage passcode. Hashing would not give much anyway as it could be easily bruteforced back to normal value (only six digits so that would take few seconds to get value back from hash), I don't think it would change much if anything

2018-05-02 14:45 UTC, daviian approved these changes

2018-05-02 14:46 UTC, daviian commented
Don't want to block that PR ;)

But if it's that easy to bruteforce TOTP, why use it in the first place?

2018-05-02 14:49 UTC, techknowlogick commented
@daviian I think @lafriks means that it is easy to bruteforce a hash of 6 characters, so if an attacker has access to the DB a hash wouldn't really stop them from knowing what the token was. This is fine because tokens change every 30 seconds, and this is a protection just in case someone MITM a user to intercept the token so it can't be re-used.

2018-05-02 14:55 UTC, daviian commented
@techknowlogick @lafriks You are totally right! :+1:

2018-05-02 15:02 UTC, merged

2018-05-02 16:37 UTC, lafriks commented
As this is more enchantment and it is hard to backport to 1.4 without breaking upgrade process, I will not backport it

2018-05-02 22:32 UTC, cezar97 commented
Personally I don't care too much, but may I ask why finders don't receive any credits?  Indeed, it would be really appreciated... @go-gitea
@techknowlogick BTW instead of hashing, bcrypt should be considered: it's way more secure. But as you said, this is only a protection so there's no impact saving in plaintext the last OTP Token used. There's one for the stratch code, as currently it is in plaintext.
PS: can't knowing the last otp used help bruteforcing the private key, instead? Obviously the amount of time is far greater due to longer chars.

2018-05-02 22:47 UTC, techknowlogick commented
@cezar97 I can't speak on behalf of the other maintainers, but I've asked for a thanks to be added to the blog post for the release notes. As only owners see the security reports I wasn't able to add the appropriate thanks to my PR for the release blog post.

2018-05-03 04:03 UTC, lafriks commented
@cezar97 finders will get credits in blog post