Refactor User Settings
go-gitea/gitea pull request #3900
Opened 2018-05-05 16:30 UTC by daviian

Targets https://github.com/go-gitea/gitea/issues/2271 and reduces amount of menu items by combining contextual settings.

UI before PR:
<img width="1380" alt="old-menu" src="https://user-images.githubusercontent.com/5477981/39665159-114a8842-5090-11e8-8a63-6295f0545ceb.png">

UI after PR:
* Profile
<img width="1454" alt="profile" src="https://user-images.githubusercontent.com/5477981/39665165-1dd06eec-5090-11e8-8324-829d02ab5d1c.png">

* Account
<img width="1242" alt="account" src="https://user-images.githubusercontent.com/5477981/39665169-22aeab36-5090-11e8-950e-b8446322f866.png">

* Security
<img width="1218" alt="security" src="https://user-images.githubusercontent.com/5477981/39665171-283b573e-5090-11e8-83dd-21e55549222a.png">

2018-05-05 19:13 UTC, JonasFranzDEV commented
I think that Security is not the best place for Application Tokens.

2018-05-05 20:00 UTC, Mauladen commented
It looks good , but it is worth considering the comment @JonasFranzDEV

2018-05-05 21:44 UTC, lafriks commented
Maybe move 2fa to account and rename security to something else but I have no ideas what :)

2018-05-06 16:47 UTC, JonasFranzDEV commented
@daviian Maybe an extra category "Applications" or "API"  including access tokens.

2018-05-10 17:45 UTC, thehowl commented
big :+1: 

Can you create redirects from the old pages to the new locations? Such as `/user/settings/avatar` becoming `/user/settings` and so on.

Can you update `templates/user/profile.tmpl` link to "Change avatar"?

2018-05-11 08:53 UTC, daviian commented
@thehowl 
Which link do you mean? Do you want me to change the "Update Avatar" button to "Change Avatar"?

Redirects can be added of course, if needed. Do we already have them on other migrated routes as well?

2018-05-11 13:32 UTC, lunny commented
He means maybe other system (i.e. drone) reference some of these changed URLs.

2018-05-11 13:42 UTC, lafriks commented
I don't think they should reference user settings url's

2018-05-11 13:59 UTC, daviian commented
IMHO if an external service depends on frontend urls instead of the API it has to cope with from their perspective breaking changes.

2018-05-11 14:17 UTC, thehowl commented
@daviian I am referring to the link on the avatar if you're visiting your own profile (grep for user/settings on the template i mentioned).

And no, while this may break Drone in some way, I was actually referring to documentation or otherwise linking to those pages outside of gitea itself. Say I linked to https://try.gitea.io/user/settings/avatar . Currently, the URL works but after the PR it won't. We should try to avoid 404s.

2018-05-11 14:29 UTC, daviian commented
@thehowl Ah that one. Will fix that. And you've got me convinced that those redirects aren't only sugar :wink:

2018-05-11 14:45 UTC, daviian commented
@thehowl Problem is that for e.g. password/twofa there's no correct redirect, as they where on one page and now are on two different pages.

2018-05-12 13:29 UTC, thehowl commented on routers/routes/routes.go
> +			ctx.Redirect(setting.AppSubURL + "/user/settings/security")
Can you add `, http.StatusMovedPermanently` to each Redirect? This way it can be properly cached by browsers

2018-05-12 13:30 UTC, thehowl commented
Other than that, LGTM :+1:

2018-05-13 16:54 UTC, techknowlogick commented
LGTM

2018-05-14 00:51 UTC, appleboy requested changes
build fail. try to `make fmt` to fix code format.

2018-05-14 07:27 UTC, daviian commented
@appleboy How can it be that `make fmt` is now reporting issues despite a fine fmt check at the commit before without changing anything at the claimed code?

2018-05-14 18:23 UTC, thehowl approved these changes

2018-05-15 07:11 UTC, appleboy approved these changes

2018-05-15 10:07 UTC, merged