Compare git services in docs page
go-gitea/gitea pull request #3911
Opened 2018-05-07 14:03 UTC by lafriks

Fixes #3907

2018-05-07 14:29 UTC, daviian requested changes

2018-05-07 14:29 UTC, daviian commented on docs/content/doc/features/comparison.en-us.md
> +To help decide if Gitea is suited fot Your needs there is how it compares to other Git self hosted options.
Typo at `suited fot Your needs`. I'd also write `Your` in lower case.

2018-05-07 14:29 UTC, daviian commented on docs/content/doc/features/comparison.en-us.md
> +| Static Git-powerded pages |
Typo in `Git-powerded`

2018-05-07 14:29 UTC, daviian commented on docs/content/doc/features/comparison.en-us.md
> +| Granual user roles (Code, Issues, Wiki etc) |
Guess this should be `Granular`?

2018-05-07 23:04 UTC, lunny commented
How about group some items? And something maybe lost I know:
* Batch issues handler
* Topics
* Database supports

2018-05-08 22:07 UTC, lafriks commented
Finished, please review

@daviian @lunny fixed

2018-05-08 22:34 UTC, InExtremaRes commented
I don't know if it is relevant but I think Gogs support rebase merging for PRs in develop branch

2018-05-08 22:41 UTC, lafriks commented
@InExtremaRes you are right, fixed. Had x in wrong row, gogs does not support PR squash merging strategy

2018-05-09 01:58 UTC, lunny commented
Gogs has Branch manager, otherwise LGTM

2018-05-09 05:50 UTC, appleboy approved these changes

2018-05-09 08:00 UTC, daviian approved these changes

2018-05-09 08:08 UTC, daviian commented
Maybe we should clarify that we don't regularly check the other services for changed features!?

2018-05-09 08:16 UTC, lafriks commented
@daviian added

2018-05-09 08:17 UTC, daviian approved these changes

2018-05-09 09:06 UTC, tboerger approved these changes
I would prefer markdown formatted tables instead of plain HTML...

2018-05-09 09:56 UTC, lafriks commented
@tboerger if I manage to get it working with markdown tables, I will submit that as new PR

2018-05-09 09:57 UTC, merged

2018-05-10 09:02 UTC, lunny commented
Missed render type comparison,  Gitea supports orgmode and third-part render tool, Gogs support  Jupyter Notebook.