[WIP] Add cli commands to regen hooks & keys
go-gitea/gitea pull request #3979
Opened 2018-05-16 18:14 UTC by techknowlogick

Rewrite authorized_keys and hooks from command line

Fix #2491

2018-05-16 18:44 UTC, jonasfranz requested changes

2018-05-16 19:20 UTC, techknowlogick commented on cmd/admin.go
> +	err := models.SyncRepositoryHooks()
Thanks @JonasFranzDEV I've made this change, and the other change you requested.

2018-05-17 00:55 UTC, lunny commented
LGTM

2018-05-17 01:34 UTC, appleboy approved these changes

2018-05-17 01:35 UTC, merged

2018-05-17 07:58 UTC, lafriks commented
@techknowlogick please add this commands also to docs page (cli)

2018-05-17 07:59 UTC, lafriks commented
@appleboy please do not merge while all reviewers has not approved, it this case probably it was not so important but it's better to follow this rule even if requested changes was fixed

2018-05-17 08:15 UTC, lunny commented
yes @appleboy, @JonasFranzDEV didn't approve.

2018-05-17 13:27 UTC, techknowlogick commented
@lafriks I've added these docs to https://docs.gitea.io/en-us/command-line/ already, is there another place that they need to be?

2018-05-17 13:56 UTC, lafriks commented
@techknowlogick yes that what I mean, false alarm, all is good :)