LFS: make HTTP auth period configurable
go-gitea/gitea pull request #4035
Opened 2018-05-24 11:51 UTC by InonS

Authentication period is hard-coded for 5 minutes. For LFS this may be too short, so we made  the HTTP auth period configurable.

2018-05-24 12:29 UTC, jonasfranz approved these changes

2018-05-24 12:30 UTC, JonasFranzDEV commented
Please run `make fmt`.

2018-05-24 12:42 UTC, InonS commented
@JonasFranzDEV I pushed the commit which removes the semicolon, running `make fmt` changes nothing, but drone keeps referrencing the previous commit. How can we trigger drone ro rerun on this PR?

2018-05-24 12:44 UTC, InonS commented
@JonasFranzDEV how can we re-trigger drone to run now that I committed the semicolon fix?

2018-05-24 14:08 UTC, techknowlogick requested changes

2018-05-24 14:08 UTC, techknowlogick commented on docs/content/doc/advanced/config-cheat-sheet.en-us.md
> +- `LFS_HTTP_AUTH_EXPIRY_MINUTES`: **5**: LFS authentication validity period in minutes, pushes taking longer than this may fail.
Can you also add this to `/custom/conf/app.ini.sample`

2018-05-24 14:38 UTC, lafriks commented
I think default should be increased to at least 20 minutes or half hour as I think this really does create problems for it being so small

2018-05-24 21:40 UTC, sapk requested changes
time.Duration is a better format for expiry time option.

2018-05-24 21:40 UTC, sapk commented on modules/setting/setting.go
> +		HTTPAuthExpiryMinutes int    `ini:"LFS_HTTP_AUTH_EXPIRY_MINUTES"`
I find more logic and allow more flexible configuration to set this directly as time.Duration you can use mirror option like MIN_INTERVAL as an example and use a more short option name LFS_HTTP_AUTH_EXPIRY.

2018-05-27 16:13 UTC, lafriks approved these changes

2018-05-27 16:16 UTC, techknowlogick approved these changes

2018-05-27 16:40 UTC, lafriks commented
I think we should move this to 1.5 as it is quite safe change and should increase stability of LFS

2018-05-27 16:51 UTC, techknowlogick commented
@lafriks Sounds good. Let me do that. I had just moved it in preparation of release, however I agree that this would be good to get in sooner.

2018-05-27 17:44 UTC, lafriks commented
@sapk need your approval

2018-05-27 21:36 UTC, sapk requested changes
Code is good. The documentation need to be updated to the new duration format. Near to be merged :-).

2018-05-27 21:36 UTC, sapk commented on docs/content/doc/advanced/config-cheat-sheet.en-us.md
> +- `LFS_HTTP_AUTH_EXPIRY_MINUTES`: **20**: LFS authentication validity period in minutes, pushes taking longer than this may fail.
The doc isn't updated to new duration format.

2018-05-29 03:31 UTC, lunny commented
@InonS maybe you could follow @sapk 's advice

2018-05-29 05:43 UTC, lunny commented
@sapk need your approval.

2018-05-29 07:34 UTC, sapk approved these changes
Thanks, for this good PR.

2018-05-29 07:35 UTC, appleboy approved these changes

2018-05-29 08:07 UTC, merged

2018-06-04 08:51 UTC, ohwgiles commented
Why was this line introduced?
https://github.com/go-gitea/gitea/pull/4035/commits/ebdab8976e22b9b5f751e034a2e209354558e047#diff-60f5fca6d29eafbb30eb645a0cd4041fR832

It separates the new configuration variable from the other `LFS_` variables

2018-06-04 09:08 UTC, InonS commented
@ohwgiles points out that the config section should, in fact, still be in accordance with the "server" struct,  which contains the "LFS" struct. I should just remove the line
```
sec = Cfg.Section("LFS")
```

2018-06-04 12:01 UTC, sapk commented
@ohwgiles Good catch. Thanks

@InonS It is best to do a PR as it will follow all checks (CI, validation, ...) and keep history of why change has been maid. (And I personally doesn't have push right ^^)