对 Markdown 解析 增加 流程图 和 顺序图 的支持。
go-gitea/gitea pull request #4099
Opened 2018-06-02 00:04 UTC by Lao-liu

```flow
流程图代码：详见 http://flowchart.js.org/
```

```sequence
顺序图代码：详见 https://bramp.github.io/js-sequence-diagrams/
```

Please check the following:

1. Make sure you are targeting the `master` branch, pull requests on release branches are only allowed for bug fixes.
2. Read contributing guidelines: https://github.com/go-gitea/gitea/blob/master/CONTRIBUTING.md
3. Describe what your pull request does and which issue you're targeting (if any)

**You MUST delete the content above including this line before posting, otherwise your pull request will be invalid.**

2018-06-02 10:50 UTC, JonasFranzDEV commented
Please change title and comments/description to english since otherwise this issue will be invalid.

2018-06-02 11:42 UTC, lafriks requested changes

2018-06-02 11:42 UTC, lafriks commented on templates/base/footer.tmpl
> +    <script src="{{AppSubUrl}}/vendor/plugins/flow/flowchart.min.js"></script>
Spacing seems to be incorrect here

2018-06-02 11:42 UTC, lafriks commented on templates/base/footer.tmpl
> +            $('.language-flow').each((i, flow)=>{
ES6 syntax won't work on MS Internet Explorer

2018-06-03 01:20 UTC, lunny commented
@Lao-liu I translated your Chinese to English since we are an international community and not everyone know Chinese.

2018-06-03 01:55 UTC, Lao-liu commented on templates/base/footer.tmpl
> +    <script src="{{AppSubUrl}}/vendor/plugins/flow/flowchart.min.js"></script>
ok, change use tab replace space.

2018-06-03 01:56 UTC, Lao-liu commented on templates/base/footer.tmpl
> +            $('.language-flow').each((i, flow)=>{
don't use ES6 way.

2018-06-08 03:07 UTC, lunny commented
Maybe partial fix https://github.com/go-gitea/gitea/issues/3902

2018-09-11 00:17 UTC, techknowlogick commented
I worry about adding all of this JS as a dependency. This can be achieved with local template customization for users that need it.

2019-04-23 11:50 UTC, lafriks commented
imho this can be easily added in custom template as it is added only in frontend

2019-04-25 05:46 UTC, lunny commented
So let's close this one.

2019-04-25 05:46 UTC, closed without merging