Git-Trees API.
go-gitea/gitea pull request #4185
Opened 2018-06-08 16:30 UTC by Kasi-R

Started on Git-Trees API. Added methods for getting a tree and getting a tree recursively as per https://developer.github.com/v3/git/trees/

Creating a tree not done.

2018-06-13 05:43 UTC, lafriks requested changes

2018-06-13 05:43 UTC, lafriks commented on routers/api/v1/repo/tree.go
> +	"code.gitea.io/gitea/modules/context"
Import order wrong

2018-06-13 05:43 UTC, lafriks commented on routers/api/v1/repo/tree.go
> +type TreeEntry struct {
Types must be reused from sdk package

2018-06-13 05:43 UTC, lafriks commented on routers/api/v1/api.go
> +
Why so many empty lines here?

2018-06-13 10:15 UTC, Kasi-R commented
Done. I used the types from https://github.com/go-gitea/go-sdk/pull/109 however, i can change it to the types used in https://github.com/go-gitea/go-sdk/pull/94 if required.

2018-11-24 03:16 UTC, techknowlogick commented
@Kasi-R would it be possible to use other PR in SDK? I think it would be best to merge in functionality then another PR for enhancement.

2018-11-24 03:17 UTC, techknowlogick commented
@lafriks please update review. Can you also review gitea/go-sdk#94?

2018-11-24 11:04 UTC, lafriks commented on routers/api/v1/api.go
> +				m.Group("/trees", func() {
we should probably use github compatible route (`/git/trees`)

2018-11-24 11:05 UTC, lafriks commented
@techknowlogick done

2018-11-25 06:53 UTC, necaris approved these changes
Just a couple of small requests for better explanation of where some constants are coming from -- otherwise this looks good, very straightforward -- certainly simpler than my attempt #1978 !

2018-11-25 06:53 UTC, necaris commented on routers/api/v1/repo/tree.go
> +	BlobURL := make([]byte, RepoIDLen + 47)
@Kasi-R could you please add a comment or variable describing where the magic number `47` comes from?

2018-11-25 06:53 UTC, necaris commented on routers/api/v1/repo/tree.go
> +	TreeURL := make([]byte, RepoIDLen + 47)
See above -- same here please.

2018-11-25 06:53 UTC, necaris commented on routers/api/v1/repo/tree.go
> +	CopyPos := len(TreeURL) - 40
Similar request here -- where is the `40` coming from?

2018-11-26 06:44 UTC, closed without merging