Add security advice to contrib guide
go-gitea/gitea pull request #4187
Opened 2018-06-08 17:17 UTC by sapk

Just a little reminder.

Related to #4167

2018-06-08 17:19 UTC, rugk commented
Remember… on GitHub you could actually enforce 2FA for the organization.

2018-06-08 17:36 UTC, rugk approved these changes

2018-06-08 17:59 UTC, techknowlogick approved these changes

2018-06-08 20:42 UTC, axifive approved these changes

2018-06-09 03:47 UTC, lunny commented
LGTM

2018-06-09 05:51 UTC, daviian requested changes

2018-06-09 05:51 UTC, daviian commented on CONTRIBUTING.md
> +For security reasons, Maintainers should use 2FA for theirs accounts and
Little typo `their's' accounts`

2018-06-09 09:36 UTC, daviian approved these changes

2018-06-09 16:03 UTC, merged