Bugfix/watches
go-gitea/gitea pull request #4201
Opened 2018-06-09 21:55 UTC by daviian

Targets: https://github.com/go-gitea/gitea/issues/3343, https://github.com/go-gitea/gitea/issues/3782, https://github.com/go-gitea/gitea/issues/4149

What does it do:
* removes watches if users gets removed from a team or a team is deleted as a whole.
* also sets new team users to watch all team repositories.
* remove watch if user gets removed from the collaborators of a repo

2018-06-09 23:07 UTC, lafriks approved these changes

2018-06-09 23:11 UTC, daviian commented
@lafriks Please add status/wip as I've to add the migration to cleanup hanging watches

2018-06-15 08:18 UTC, bkcsoft commented
@daviian I don't think that the mgiration is necessary for this fix. It would be nice to have, but not something that should hold back this PR.

2018-06-15 08:23 UTC, daviian commented
@BKC It's already implemented. I'm currently in the middle of testing the migration locally ;) If it's fine i'll push.

2018-06-15 12:32 UTC, lunny requested changes

2018-06-15 12:32 UTC, lunny commented on models/migrations/v67.go
> +	sess := x.NewSession()
need 
```Go
defer sess.Close()
if err := sess.Begin(); err != nil {
return err
}
```

2018-06-15 12:38 UTC, daviian commented on models/migrations/v67.go
> +	sess := x.NewSession()
Oh yes. Totally forgot.

2018-06-15 12:39 UTC, lunny requested changes

2018-06-15 12:39 UTC, lunny commented on models/org_team.go
> +		if err := removeIssueWatchersByRepoID(e, teamUser.ID, repo.ID); err != nil {
teamUser.UID

2018-06-15 12:51 UTC, daviian commented
@lunny Added your suggestions

2018-06-19 05:00 UTC, lunny requested changes

2018-06-19 05:00 UTC, lunny commented on models/migrations/v67.go
> +				}
You should `repoCache[watch.RepoID] = repo`

2018-06-19 05:00 UTC, lunny commented on models/migrations/v67.go
> +					}
The same as above

2018-06-19 05:53 UTC, lunny commented
Please follow my comment, otherwise LGTM

2018-06-19 15:10 UTC, lunny approved these changes

2018-06-19 19:44 UTC, merged

2018-06-19 19:45 UTC, techknowlogick commented
@lafriks the ticket this was attached to was marked as backport, but you removed the label from this PR, should it still be backported?

2018-06-20 08:30 UTC, lunny commented
This will not be back port since it has a migration which will let user difficult upgrade from v1.4 to v1.5