Add a basic SMF manifest for SunOS platforms
go-gitea/gitea pull request #4238
Opened 2018-06-12 23:40 UTC by tuxillo

Hi,

A basic SMF file which might come handy for people use SunOS platforms like SmartOS, OmniOS, etc.

Regards,
Antonio Huete

2018-06-19 10:11 UTC, lafriks approved these changes

2018-06-19 10:20 UTC, tonivj5 approved these changes

2018-06-23 19:17 UTC, sjorge commented
Nice, that saves me the effort of writing one. This one works perfectly on SmartOS.

2018-06-23 20:30 UTC, tuxillo commented
@sjorge I've also made a port in pkgsrc WIP :-)

2018-06-24 02:30 UTC, sapk approved these changes

2018-06-24 03:06 UTC, techknowlogick requested changes

2018-06-24 03:06 UTC, techknowlogick commented on contrib/init/sunos/gitea.xml
> +			  <loctext xml:lang="C">Compact self-hosted GIT service</loctext>
Can you use "A painless, self-hosted Git service" instead? It is the tagline for Gitea

2018-06-24 09:03 UTC, sjorge commented
@tuxillo nice, I could not find it on the joyent/pkgsrc-wip repo though?

2018-06-24 11:16 UTC, lafriks commented
@techknowlogick need your approval

2018-06-24 13:31 UTC, tuxillo commented
@sjorge it's in pkgsrc-wip (https://github.com/NetBSD/pkgsrc-wip/commit/6f84130e7cb5ec214241a861b2a450db57613a78)

2018-06-24 16:16 UTC, techknowlogick approved these changes

2018-06-24 21:24 UTC, merged