Fix milestone appliance and permission checks
go-gitea/gitea pull request #4271
Opened 2018-06-18 13:42 UTC by JonasFranzDEV

Fixes #4270 and adds missing permission check which got removed.

Without the permission check every user can assign labels, etc to new issues if created via API.

2018-06-18 18:29 UTC, techknowlogick reviewed
Please add Gitea copyright notice to header of this file

2018-06-19 01:13 UTC, lunny requested changes

2018-06-19 01:13 UTC, lunny commented on routers/api/v1/repo/issue.go
> +		// setting labels is only allowed if user is writter
comment should be `... is not a writer`.

2018-06-19 01:21 UTC, lunny commented
Otherwise LGTM

2018-06-19 13:19 UTC, lafriks commented
@techknowlogick added copyright
@lunny fixed comment

2018-06-19 13:19 UTC, techknowlogick approved these changes

2018-06-19 13:25 UTC, sapk approved these changes

2018-06-19 15:09 UTC, lunny approved these changes

2018-06-19 15:15 UTC, merged