Keep preseeded database password
go-gitea/gitea pull request #4284
Opened 2018-06-20 20:42 UTC by tarelda

Simple fix to retain preseeded database password from configuration file in automatic deployments. References directly issue #4217

2018-06-21 05:07 UTC, lafriks approved these changes

2018-06-21 10:14 UTC, daviian requested changes

2018-06-21 10:14 UTC, daviian commented on routers/install.go
> +	form.DbPasswd = models.DbCfg.Passwd
Please move the line below `form.DbUser` to reflect the actual order of the install page form fields.

2018-06-24 18:10 UTC, daviian approved these changes

2018-07-04 00:09 UTC, techknowlogick commented
make LG-TM work

2018-07-04 00:09 UTC, merged