Notifications - Step 1
go-gitea/gitea pull request #429
Opened 2016-12-20 22:37 UTC by andreynering

First step to resolve #145

This deprecates #321

I plan 3 steps:

- [ ] Create database table and create/update notifications (this one)
- [ ] Refactor (delete dead code) regarding the `UserIssue` model, which was never actually used
- [ ] Actually have UI for notifications

2016-12-21 07:40 UTC, tboerger commented on models/notification.go
> +const (
Just put the constants in a single block

2016-12-21 07:40 UTC, tboerger commented on models/notification.go
> +	Status NotificationStatus `xorm:"SMALLINT INDEX NOT NULL"`
Really a separate type for simple integers?

2016-12-21 07:42 UTC, tboerger commented
Generally not bad, but you should select more collections from the db instead of firing lots of small queries

2016-12-21 08:11 UTC, lunny commented on models/notification.go
> +	Status NotificationStatus `xorm:"SMALLINT INDEX NOT NULL"`
I really like this. :)

2016-12-21 11:18 UTC, andreynering commented on models/notification.go
> +const (
It's necessary for iota and different types, as discussed below.

2016-12-21 11:20 UTC, andreynering commented on models/notification.go
> +	Status NotificationStatus `xorm:"SMALLINT INDEX NOT NULL"`
I also prefer enum, and others too, since I was asked to use this in the previous PR.

2016-12-22 16:19 UTC, andreynering commented
> you should select more collections from the db instead of firing lots of small queries

Updated. No more queries inside the loop.

2016-12-25 03:20 UTC, lunny requested changes
Except that then LGTM

2016-12-25 03:20 UTC, lunny commented on models/notification.go
> +	defer sess.Close()
put `sess.Close()` before `sess.Begin()`

2016-12-28 20:38 UTC, andreynering commented
Deprecated by https://github.com/go-gitea/gitea/pull/523

2016-12-28 20:38 UTC, closed without merging