[WIP] Add changelog for 1.5.0-RC1
go-gitea/gitea pull request #4324
Opened 2018-06-27 05:42 UTC by techknowlogick

As title

Blocked by #4323 

This has been generated by the automated script. I still need to go through and clean the list up a bit.

2018-06-27 06:40 UTC, sapk approved these changes

2018-06-27 08:19 UTC, daviian requested changes

2018-06-27 08:19 UTC, daviian commented on CHANGELOG.md
> +  * Fix #4255 - missing close tags in U2F (#4256)
regression from new feature

2018-06-27 08:19 UTC, daviian commented on CHANGELOG.md
> +  * Add missing token validation and missing alert in UI (#3976)
part of 1.4.2

2018-06-27 08:19 UTC, daviian commented on CHANGELOG.md
> +  * Fix Webhook and hook_task not cleaned up when delete repository (#4004)
part of 1.4.2

2018-06-27 08:19 UTC, daviian commented on CHANGELOG.md
> +  * Fix webhook bug of response info is not displayed in UI (#4000)
part of 1.4.2

2018-06-27 08:19 UTC, daviian commented on CHANGELOG.md
> +  * Fix writer cannot read bare repo guide (#4033)
part of 1.4.2

2018-06-27 08:19 UTC, daviian commented on CHANGELOG.md
> +  * Don't force due date to current time (#3830)
part of 1.4.2

2018-06-27 08:19 UTC, daviian commented on CHANGELOG.md
> +  * Fix wiki redirects (#3919)
part of 1.4.2

2018-06-27 08:19 UTC, daviian commented on CHANGELOG.md
> +  * Fix attachment ENABLED (#4064)
part of 1.4.2

2018-06-27 08:19 UTC, daviian commented on CHANGELOG.md
> +  * Added deletion of an empty line at the end of the file (#4050) (#4054)
part of 1.4.2

2018-06-27 08:19 UTC, daviian commented on CHANGELOG.md
> +  * Fix #4081 Check for leading / in base before removing it (#4082)
part of 1.4.2

2018-06-27 08:19 UTC, daviian commented on CHANGELOG.md
> +  * Add "error" as reserved username (#3882)
part of 1.4.1

2018-06-27 08:19 UTC, daviian commented on CHANGELOG.md
> +  * Do not allow inactive users to access repositories using private keys (#3887)
part of 1.4.1 and is Security

2018-06-27 08:19 UTC, daviian commented on CHANGELOG.md
> +  * Fix path cleanup in multiple places (#3871)
part of 1.4.1

2018-06-27 08:19 UTC, daviian commented on CHANGELOG.md
> +  * Remove unnecessary Safe tags (#3778)
part of 1.4.1

2018-06-27 08:19 UTC, daviian commented on CHANGELOG.md
> +  * Correctly check http git access rights for reverse proxy authorized users (#3721)
part of 1.4.1

2018-06-27 08:19 UTC, daviian commented on CHANGELOG.md
> +  * Fix to use only needed columns from tables to get repository git paths (#3870)
part 1.4.1

2018-06-27 08:19 UTC, daviian commented on CHANGELOG.md
> +  * Fix gpg expired bug when time is zero (#3584)
1.4.1

2018-06-27 08:19 UTC, daviian commented on CHANGELOG.md
> +  * Fix only updated_unix when adding a comment (#3855)
1.4.1

2018-06-27 08:19 UTC, daviian commented on CHANGELOG.md
> +  * Fix typo in deleteUser (#3781)
1.4.1

2018-06-27 08:19 UTC, daviian commented on CHANGELOG.md
> +  * Use the active branch for the code tab (#3720)
1.4.1

2018-06-27 08:19 UTC, daviian commented on CHANGELOG.md
> +  * Set default branchname on first push (#3715)
1.4.1

2018-06-27 08:19 UTC, daviian commented on CHANGELOG.md
> +  * Show Clipboard button if disable HTTP of git protocol (#3773)
1.4.1

2018-06-27 09:55 UTC, lafriks commented
I think changelog should be only generated from label changloge and milstone 1.5.0 to keep it clean:
https://github.com/go-gitea/gitea/issues?q=label%3Achangelog+is%3Aclosed+milestone%3A1.5.0

If anything else from this needs to be included label shoud be added to that PR

2018-06-27 09:56 UTC, lafriks requested changes
See my comment to have changelog cleaner and more useful

2018-06-27 13:32 UTC, techknowlogick commented
@lunny conflict resolved
@daviian / @lafriks thanks for feedback. I've changed the list to only include the items with changelog label

2018-06-27 14:10 UTC, lafriks commented
It is probably worth to review if there is anything else that is worth to mention in there and than label should be added to that issue

2018-06-27 14:50 UTC, axifive commented
@lafriks, may be sorting enhancement https://github.com/go-gitea/gitea/pull/3969

2018-06-30 02:07 UTC, techknowlogick commented
@axifive added.

@lafriks / @daviian please review changes

2018-07-01 06:02 UTC, lafriks approved these changes

2018-07-01 06:03 UTC, lafriks commented
@daviian need your approval

2018-07-01 07:38 UTC, appleboy approved these changes

2018-07-02 13:51 UTC, daviian approved these changes

2018-07-03 10:03 UTC, sapk commented
We can also add #4188 to indicate that binary can be check with the public key. We could also indicate the public key fingerprint.

2018-07-03 10:35 UTC, daviian commented
There are many more security fixes that didn't find it's way to a minor version of 1.4
These should be included as well.

Also I think there are further noticable PR's.
See https://github.com/go-gitea/gitea/pulls?page=2&q=is%3Aclosed+milestone%3A1.5.0+is%3Apr+-label%3Akind%2Fdocs++-label%3Abackport%2Fv1.4+-label%3Akind%2Fbug+-label%3Akind%2Ftranslation&utf8=%E2%9C%93
Of course not all of them, but some.

2018-07-03 14:16 UTC, lafriks commented
@daviian I added changelog label to 11 more PR's from that list, just need to add them also to this PR

2018-07-03 18:48 UTC, lafriks commented
@daviian @sapk done

2018-07-03 19:37 UTC, merged