Fix drone git@next plugin Gitea version display when building tag
go-gitea/gitea pull request #4380
Opened 2018-07-05 20:20 UTC by lafriks

Currently Drone CI when using git@next plugin to build tagged version gitea shows sha1 instead of actual version in footer.

Fixes #4359

See comments in issue for more details

2018-07-05 20:26 UTC, jonasfranz requested changes

2018-07-05 20:32 UTC, lafriks commented on Makefile
> +  GITEA_VERSION := $(shell git describe --tags --always | sed 's/-/+/' | sed 's/^v//')
done

2018-07-05 20:36 UTC, jonasfranz approved these changes

2018-07-06 01:40 UTC, lunny commented
conflict

2018-07-10 08:20 UTC, lafriks commented
@lunny conflict resolved

2018-07-10 13:36 UTC, lafriks commented
Drone failure is not related to PR

2018-07-10 14:44 UTC, axifive approved these changes

2018-07-10 17:26 UTC, Bwko approved these changes

2018-07-12 03:32 UTC, merged