fix markdown commit link generation
go-gitea/gitea pull request #4545
Opened 2018-07-29 12:37 UTC by adelowo

Fixes #4536

2018-07-29 18:10 UTC, lafriks commented
Will this not break relative url generation?

2018-07-29 18:45 UTC, adelowo commented
No It doesn't... I have tested it but another person can make sure to verify though

2018-08-21 08:18 UTC, adelowo commented
Has anyone tested this yet ?

2018-08-22 19:07 UTC, krombel commented
I have now build and tested it. It seems to successfully fix the issue

2018-08-23 15:27 UTC, krombel approved these changes

2018-09-17 21:22 UTC, lafriks requested changes
It does break images (that are in same repository) and links to other repository files

For example:
```
![deadline.png](deadline.png)
```

2018-09-18 11:18 UTC, adelowo commented
Thanks for the update @lafriks .... Would verify that and fix

2019-04-20 21:06 UTC, lafriks commented
@adelowo ping

2019-04-20 21:45 UTC, mrsdizzie commented
The problem In the title was actually fixed a different way in #6645

2019-04-21 01:00 UTC, techknowlogick commented
Closed per above comment.

2019-04-21 01:00 UTC, closed without merging