Fix integer constant overflows in tests
go-gitea/gitea pull request #4616
Opened 2018-08-04 20:00 UTC by menschel-d

Explicitly use int64 in order to avoid the following errors on 32 bit
architectures:

```
# code.gitea.io/gitea/integrations
./api_admin_test.go:50:34: constant 9223372036854775807 overflows int
./api_token_test.go:47:34: constant 9223372036854775807 overflows int
[...]
# code.gitea.io/gitea/models
./action_test.go:179:15: constant 9223372036854775807 overflows int
```

Futhermore, the magic constant 9223372036854775807 has been substituted with a numerically equivalent integer limit value.

---

I'm currently working on a BitBake recipe for Gitea in the context of Yocto/OpenEmbedded, and have stumbled upon the mentioned problems when compiling for the `qemuarm` target.
As I have little experience in Go programming, I've adapted the solution from [1].
If there are any problems in the code changes, just let me know.

[1] https://stackoverflow.com/a/16475045

2018-08-05 19:07 UTC, sapk requested changes

2018-08-05 19:07 UTC, sapk commented on models/unit_tests.go
> +const NonexistentID = math.MaxInt64
Can you simply do `int64(math.MaxInt64)` and don't edit others code part ?

2018-08-05 20:45 UTC, menschel-d commented
Thanks for the suggestion,  @sapk.
These changes should now also be easier to backport to the latest stable release.

2018-08-05 20:46 UTC, techknowlogick commented on .gitignore
> +# Backup files (i.e. from Vim)
This should belong in your global git ignore file, or at least create a new PR for it as it is unrelated to the current PR.

2018-08-05 20:56 UTC, menschel-d commented
Thanks for the quick reply, @techknowlogick. I've omitted the changes to `.gitignore` like you've requested.

2018-08-05 20:56 UTC, techknowlogick commented
Thanks @menschel-d 

LGTM

2018-08-06 08:52 UTC, sapk approved these changes
Thanks for the contrib.

2018-08-06 11:44 UTC, lafriks approved these changes

2018-08-06 11:52 UTC, merged