Minor fixes
go-gitea/gitea pull request #4866
Opened 2018-09-04 02:40 UTC by maiki

Just a bunch of periods and a fixed link.

2018-09-04 07:17 UTC, adelowo approved these changes

2018-09-04 07:32 UTC, adelowo commented
It'd be nice if you could update the PR title though

2018-09-04 12:28 UTC, davidak requested changes

2018-09-05 02:09 UTC, techknowlogick approved these changes

2018-09-05 02:47 UTC, merged