Make gitea serv use api/internal
go-gitea/gitea pull request #4886
Opened 2018-09-06 23:07 UTC by sapk

In order to limit concurrent access to database (mostly for SQLite)

Related: #4848

2018-09-07 00:14 UTC, lafriks commented
Git clone tests seems to fail now

2018-09-07 00:40 UTC, lunny requested changes

2018-09-07 00:40 UTC, lunny commented on modules/private/key.go
> +// Copyright 2017 The Gitea Authors. All rights reserved.
2018

2018-09-13 13:31 UTC, sapk commented
I have not much time until 2 weeks. I will look at tests since I test clone manually and it worked but I must have forget one corner case.

2018-10-23 16:54 UTC, sapk commented
I found the stupid mistake I made. :expressionless:
This PR should be good.

2018-10-24 08:25 UTC, lunny approved these changes

2018-10-24 08:40 UTC, sapk commented
@lunny I will have to verify but hook seems to only use const in models and already use private (api/internal). 
We could drop https://github.com/go-gitea/gitea/blob/master/cmd/hook.go#L69 that shouldn't be needed anymore but that will be in another PR.

2018-10-30 05:37 UTC, BetaCat0 approved these changes

2018-10-30 05:40 UTC, appleboy approved these changes

2018-10-30 06:20 UTC, merged