Ordering organizations and users by name
go-gitea/gitea pull request #49
Opened 2016-11-03 15:40 UTC by 0xbaadf00d

Relative to the issue #3845, this Pull Request add modifications to ordering by name Organizations and User Accounts.

It's more user friendly and make search more easy when organizations and user accounts are ordered by name rather than last update datetime.

I added new function `GetUsersByIDs` to decrease the number of SQL queries by using IN predicate rather than just running 1 SQL query per users.

2016-11-03 19:09 UTC, tboerger submitted a review, later dismissed
Just minor revert of changes.

2016-11-03 19:09 UTC, tboerger commented on templates/admin/org/list.tmpl
> -								<th>ID</th>
Please keep that, this is an admin view and I would print there as much information as possible.

2016-11-03 19:09 UTC, tboerger commented on templates/admin/repo/list.tmpl
> -								<th>ID</th>
Same as above.

2016-11-03 19:09 UTC, tboerger commented on templates/admin/user/list.tmpl
> -								<th>ID</th>
Same as above.

2016-11-03 19:57 UTC, 0xbaadf00d commented on templates/admin/org/list.tmpl
> -								<th>ID</th>
ok, but trust me, when you have more than 129 users, ID is just an annoyance and take a lot of place because the website CSS theme is not fluid.

2016-11-03 20:03 UTC, tboerger commented on templates/admin/org/list.tmpl
> -								<th>ID</th>
A proper listing is a different story, but I would like to keep this information.

2016-11-03 20:12 UTC, 0xbaadf00d commented on templates/admin/org/list.tmpl
> -								<th>ID</th>
ok

2016-11-03 20:38 UTC, DblK commented
Can you rebase it?

2016-11-03 21:01 UTC, 0xbaadf00d commented
You could choose "Rebase and Merge" during the merge process : https://github.com/blog/2243-rebase-and-merge-pull-requests

2016-11-03 22:21 UTC, bkcsoft requested changes

2016-11-03 22:21 UTC, bkcsoft commented on models/org.go
>  	if err = x.Sql(fmt.Sprintf(`SELECT repository.* FROM repository
Do we _really_ need to do raw SQL-query here?

2016-11-03 22:21 UTC, bkcsoft commented on models/org.go
>  	results, err := x.Query(fmt.Sprintf(`SELECT repository.id FROM repository
Same as above

2016-11-03 22:21 UTC, bkcsoft commented on models/org.go
>  	if err = x.Sql(fmt.Sprintf(`SELECT repository.* FROM repository
Same as above

2016-11-03 22:22 UTC, bkcsoft commented on models/org.go
> +		Where("uid=?", uid)
This should probably be `"org_user.uid=?"` no?

2016-11-03 22:28 UTC, 0xbaadf00d commented on models/org.go
> +		Where("uid=?", uid)
It seem correct, Here we want organizations ordered by name, and in GOGS, organization are just a simple user.

2016-11-03 22:30 UTC, 0xbaadf00d commented on models/org.go
>  	if err = x.Sql(fmt.Sprintf(`SELECT repository.* FROM repository
Probably not, but this code is not part of the pull request. It could be a part of another one (eg : rewrite and optimize all SQL queries)

2016-11-04 02:20 UTC, bkcsoft commented on models/org.go
>  	if err = x.Sql(fmt.Sprintf(`SELECT repository.* FROM repository
Well, if you're making that line better, you could just as well make it _even_ better :smile: Saves us another PR :+1:

2016-11-04 02:21 UTC, bkcsoft commented on models/org.go
> +		Where("uid=?", uid)
I meant in the `Where`-clause, since it's a JOIN :slightly_smiling_face:

2016-11-06 09:05 UTC, strk commented on models/org.go
> +		Where("uid=?", uid)
Better be safe than sorry, and consistent (also "org_id" is only in org_user but is explicitly listed.
BTW, I don't think you need to quote "org_user" and "user"...)

2016-11-06 09:31 UTC, strk commented on models/org.go
> +		Join("LEFT", "user", `"org_user".org_id="user".id`).
No JOIN should be needed here, as user id is already in the OrgUser table ?

2016-11-06 09:31 UTC, strk commented on models/org.go
> +		Join("LEFT", "user", `"org_user".org_id="user".id`).
```
                           Table "public.org_user"
  Column   |  Type   |                       Modifiers                       
-----------+---------+-------------------------------------------------------
 id        | integer | not null default nextval('org_user_id_seq'::regclass)
 uid       | bigint  | 
 org_id    | bigint  | 
 is_public | boolean | 
 is_owner  | boolean | 
 num_teams | integer | 
```

2016-11-08 22:48 UTC, andreynering commented on models/org.go
> +		Join("INNER", "user", `"user".id=team_user.uid`).
Hmm.. Ideally, we should not quote column names. Quoting is different between different databases. PostgreSQL uses ", MySQL uses `, etc. I think using [this Xorm function][quote] should work.

Same for other SQLs.

[quote]: https://godoc.org/github.com/go-xorm/xorm#Engine.QuoteStr

2016-11-09 01:02 UTC, lunny commented on models/org.go
> +		Join("INNER", "user", `"user".id=team_user.uid`).
XORM will use ` as the uniform quote and will replace it as database's self quote. So just use `,

```Go
Join("INNER", "user", "`user`.id=team_user.uid").
```

2016-11-09 08:17 UTC, 0xbaadf00d commented on models/org.go
> +		Join("LEFT", "user", `"org_user".org_id="user".id`).
Join is needed to order by Name

2016-11-09 08:43 UTC, lunny requested changes

2016-11-09 08:43 UTC, lunny commented on models/org.go
> +	org.Members, _ = GetUsersByIDs(ids)
but why ignore the errors?

2016-11-09 08:47 UTC, 0xbaadf00d commented on models/org.go
> +	org.Members, _ = GetUsersByIDs(ids)
cause in all cases `GetUsersByIDs` return an array.

2016-11-09 08:53 UTC, lunny commented on models/org.go
> +		Asc("user.name").
need quote on `user` too

2016-11-09 08:57 UTC, lunny commented on models/org.go
> +	org.Members, _ = GetUsersByIDs(ids)
But if get users failed, we should return error to external of function. I think this should be
```Go
org.members, err = GetUsersByIDs(ids)
return err
```

2016-11-09 14:34 UTC, bkcsoft submitted a review, later dismissed

2016-11-09 14:36 UTC, bkcsoft commented on models/org.go
> +	org.Members, _ = GetUsersByIDs(ids)
Agreed, always return errors

2016-11-09 14:49 UTC, 0xbaadf00d commented on models/org.go
> +	org.Members, _ = GetUsersByIDs(ids)
done

2016-11-09 18:27 UTC, bkcsoft requested changes

2016-11-09 18:27 UTC, bkcsoft commented on models/org.go
> +	if err != nil {
no need, just `return err`...

2016-11-09 20:28 UTC, 0xbaadf00d commented on models/org.go
> +	if err != nil {
you right. Fixed

2016-11-09 21:36 UTC, 0xbaadf00d commented on models/org.go
>  	if err = x.Sql(fmt.Sprintf(`SELECT repository.* FROM repository
I prefer 1 PR = 1 problem solved.

I will replace raw queries  with XORM chain operations in another PR.

2016-11-10 06:47 UTC, lunny approved these changes

2016-11-10 07:37 UTC, 0xbaadf00d commented on models/org.go
> +		Asc("name").
Done

2016-11-10 07:42 UTC, lunny commented
something wrong. @joubertredrat

2016-11-10 07:45 UTC, 0xbaadf00d commented
Yeah i dont know why... I have just rebase to avoid multiple commit.  Git show get right commit but github just explode. I will recreate PR within few minutes

2016-11-10 07:57 UTC, 0xbaadf00d commented
Something goes wrong, I close this issue, delete GOGS repos and fork Gitea. I will re-create PR without few hours

2016-11-10 07:57 UTC, closed without merging

2016-11-10 10:41 UTC, joubertredrat commented
@lunny strange, I don't have relation with this PR and my commit listed already have yours PRs in https://github.com/go-gitea/gitea/pull/5 and https://github.com/go-gitea/gitea/pull/54

2016-11-10 10:42 UTC, joubertredrat commented
@0xbaadf00d for me was same, was necessary to remove gogs fork and make new fork from Gitea