Use native go method to get current user rather than environment variable
go-gitea/gitea pull request #4930
Opened 2018-09-13 13:16 UTC by SagePtr

Fixes #1640, #4894

Native "os/user" go package has good function to retrieve current user, rather than relying on USER environment variable.

If getting current user doesn't work on target OS (for example, not yet implemented for it) - it falls back to old implementation with environment variables.

Unit test also changed, old one won't work because USER environment variable spoofing doesn't work anymore (unless os/user is not implemented for OS under which tests are run), now it just compares CurrentUser() with `whoami` command output (skipped on Windows where whoami behaves different way).

For Windows OS with "domain\username" format, only second part (username) is returned to match previous behavior and trim unnecessary prefix.

2018-09-13 14:12 UTC, adelowo approved these changes

2018-09-13 16:27 UTC, lafriks commented
Blocked until 1.6.0-rc1 is released

2018-09-18 18:10 UTC, sapk requested changes
Looks good just need a little change.

2018-09-18 18:10 UTC, sapk commented on modules/user/user_test.go
> +		return
Please use t.Skip in place of return with some explaination like the comment two line before.

2018-09-18 18:56 UTC, lafriks approved these changes

2018-09-18 23:23 UTC, sapk approved these changes

2018-10-18 07:08 UTC, merged