refactor: append, build variable and type switch
go-gitea/gitea pull request #4940
Opened 2018-09-15 05:43 UTC by appleboy

1. `append` chains to the same slice that can be done in a single `append` call
2. when predeclared identifiers shadowed in assignments
3. loops that copy big objects during each iteration
4. type switches that can benefit from type guard clause with a variable

2018-09-15 12:51 UTC, lafriks commented
Blocked till 1.6.0-rc1 is released

2018-09-16 23:49 UTC, techknowlogick commented on models/user.go
> +
Why space?

2018-09-17 00:35 UTC, appleboy commented on models/user.go
> +
See https://github.com/go-gitea/gitea/pull/4940/commits/a4f370b90cd2301b4933759f52bccf08b7fad1bb

2019-02-17 14:19 UTC, lafriks commented
Please resolve conflicts and sorry for forgetting to review it

2019-04-20 21:20 UTC, lafriks commented
@appleboy conflicts

2019-05-28 08:32 UTC, appleboy commented
@lafriks resolved conflicts.

2019-05-28 09:02 UTC, zeripath commented on modules/base/tool.go
> +	switch v := right.(type) {
Could we not refactor this further to get rid of the code duplication completely?

2019-05-28 09:04 UTC, zeripath approved these changes

2019-05-28 09:06 UTC, lunny requested changes

2019-05-28 09:06 UTC, lunny commented on models/issue_assignees_test.go
> +	expectedAssignees = append(expectedAssignees, user2, user3)
I think this may changed the tests?

2019-05-28 09:43 UTC, sapk approved these changes

2019-05-28 14:00 UTC, appleboy commented on models/issue_assignees_test.go
> +	expectedAssignees = append(expectedAssignees, user2, user3)
@lunny I don't know what do you mean?

2019-05-28 14:47 UTC, lunny approved these changes

2019-05-28 15:45 UTC, merged