Add command for migrating database
go-gitea/gitea pull request #4954
Opened 2018-09-18 12:10 UTC by rstefan1

Fixes #4948

2018-09-18 13:47 UTC, adelowo commented on cmd/migrate.go
> +// Copyright 2014 The Gogs Authors. All rights reserved.
This should be `2018 The Gitea Authors` I think since it is a new file

2018-09-18 14:04 UTC, jonasfranz submitted a review, later dismissed

2018-09-18 14:04 UTC, JonasFranzDEV commented on Gopkg.lock
> +
Please revert these changed lines

2018-09-18 18:46 UTC, lafriks requested changes

2018-09-18 18:46 UTC, lafriks commented on cmd/migrate.go
> +	"github.com/urfave/cli"
Add new line between gitea imports and external one

2018-09-19 16:06 UTC, lafriks approved these changes

2018-10-02 07:07 UTC, rstefan1 commented on Gopkg.lock
> +
@JonasFranzDEV  solved

2018-10-06 00:01 UTC, axifive approved these changes

2018-10-18 02:13 UTC, lunny commented
@JonasFranzDEV need your approval.

2018-10-28 23:50 UTC, techknowlogick commented
@JonasFranzDEV need you approval

2018-10-31 02:07 UTC, appleboy approved these changes

2018-10-31 03:14 UTC, merged