Add must-change-password flag to cli for creating a user
go-gitea/gitea pull request #4955
Opened 2018-09-18 13:56 UTC by adelowo

This is more like an addition to  https://github.com/go-gitea/gitea/pull/4489 .. This introduces a flag that mimics the aforementioned PR.

2018-09-18 14:03 UTC, jonasfranz approved these changes

2018-09-18 17:00 UTC, sapk approved these changes

2018-09-18 18:51 UTC, lafriks requested changes

2018-09-18 18:51 UTC, lafriks commented on cmd/admin.go
> +			cli.StringFlag{
It should be `cli.BoolFlag`. Also why default to false if from UI default is true?

2018-10-18 02:02 UTC, lunny commented
@lafriks need your approval.

2018-10-19 11:41 UTC, lafriks approved these changes

2018-10-20 22:05 UTC, merged