Explicitly use tls for mailer
go-gitea/gitea pull request #5024
Opened 2018-10-06 10:29 UTC by adelowo

Fixes https://github.com/go-gitea/gitea/issues/4820

2018-10-06 13:34 UTC, lunny approved these changes

2018-10-06 21:50 UTC, lafriks commented
It should probably use default depending on port set to not break compatibility

2018-11-01 05:47 UTC, techknowlogick approved these changes

2018-11-01 05:52 UTC, techknowlogick requested changes

2018-11-01 05:52 UTC, techknowlogick commented on modules/mailer/mailer.go
> -	if strings.HasSuffix(port, "465") {
Perhaps have the logic be
```
isSecureConn =  (port =465) || TLSEnabled
```
for backwards compatibility per @lafriks suggestion?

2018-11-02 00:39 UTC, adelowo commented
Sorry for not updating this on time. I have been a little busy this past 2 weeks.

I would be updating my other PRs before the start of next week

2018-11-02 00:39 UTC, techknowlogick commented
@adelowo no worries. We appreciate the time you are able to give.

2018-11-26 19:02 UTC, techknowlogick approved these changes

2018-11-26 19:21 UTC, merged