CN translation of README
go-gitea/gitea pull request #5049
Opened 2018-10-09 12:42 UTC by BetaCat0

2018-10-09 14:26 UTC, appleboy requested changes

2018-10-10 03:11 UTC, BetaCat0 commented on docs/README_ZH.md
> +本页面托管在我们Docker容器内的基础设施上， 它会在每次推送到`master` 分支的时候自动更新，如果你想自己管理这个页面，你可以从我们的docker镜像[gitea/docs](https://hub.docker.com/r/gitea/docs/)中获取它。
Thank you for reminding

2018-10-10 03:27 UTC, appleboy commented on docs/README_ZH.md
> +本页面使用了 [Hugo](https://github.com/spf13/hugo) 静态页面生成工具，如果您有维护它的意愿，则需要在本地计算机上下载并安装Hugo。Hugo 的安装教程不在本文档的讲述范围之内，详情请参见 [官方文档](https://gohugo.io/overview/installing/)。
```diff
- 安装Hugo
+ 安装Hugo
```

2018-10-15 04:00 UTC, lunny approved these changes

2018-10-17 14:30 UTC, appleboy approved these changes

2018-10-18 01:44 UTC, merged