Migrate to go modules
go-gitea/gitea pull request #5069
Opened 2018-10-11 02:13 UTC by coolaj86

Re: https://github.com/go-gitea/gitea/issues/5044

* [x] remove a few unused modules (bolt, gorilla)
* [x] `go mod init` and `go mod tidy` (adds `go.mod` and `go.sum`)
* [x] remove Gopkg.*
* [ ] update drone file? (doesn't look like there was much to do)

2018-10-11 10:08 UTC, jonasfranz requested changes

2018-10-11 10:08 UTC, JonasFranzDEV commented on .gitignore
> +vendor
IMHO we shouldn't remove the vendor dir.
If a dependency or its host goes down, we can't build Gitea anymore.

2018-10-11 10:08 UTC, JonasFranzDEV commented
Please update the makefile in order to make sure that our CI tasks are going to work.

2018-10-11 10:11 UTC, jonasfranz requested changes

2018-10-11 10:11 UTC, JonasFranzDEV commented on Makefile
> -.PHONY: vendor
Don't remove the vendor and test-vendor tasks.

2018-10-11 10:11 UTC, JonasFranzDEV commented on cmd/web.go
> -	context2 "github.com/gorilla/context"
Aren't these changes from https://github.com/go-gitea/gitea/pull/5068/files#diff-da541ef36e39344f2e12bddd91d363e2 ?

2018-10-11 13:38 UTC, lunny commented
Since Gitea depends on so many Go libraries. I would like to keep vendor to use `go mod vendor`.

2018-10-15 09:38 UTC, appleboy commented
@coolaj86 Add build test in Drone

```yaml
  build-with-go-module:
    image: golang:1.11
    pull: true
    environment:
      - TAGS="bindata sqlite"
      - GO111MODULE=on
    commands:
      - make clean
      - make generate
      - make build
    when:
      event: [ push, tag, pull_request ]
```

2018-10-16 09:17 UTC, xor-gate commented
As @lunny suggests indeed it is good to cache also in the `vendor` folder. Because when somebody decides to pull the plug out of a dependency you are screwed.

2018-11-02 20:16 UTC, techknowlogick commented on .drone.yml
> -    image: golang:1.9
Can you keep this pegged at 1.9 as it is currently the oldest version of go that is supported.

2018-11-02 20:16 UTC, techknowlogick commented on .drone.yml
> -    image: golang:1.9
(but the others can remain at 1.11 as we just need to ensure that 1.9 builds, but we will distribute the versions of gitea that are built with a more recent version)

2019-01-16 15:19 UTC, techknowlogick commented
Closing due to #5743

2019-01-16 15:19 UTC, closed without merging