ZH-CN translation of Installation part
go-gitea/gitea pull request #5089
Opened 2018-10-16 02:34 UTC by BetaCat0

ZH-CN translation of Installation part:

- [ ] run-as-service-in-ubuntu.en-us.md

2018-10-16 06:35 UTC, lunny approved these changes

2018-10-17 14:34 UTC, appleboy requested changes

2018-10-17 14:34 UTC, appleboy commented on docs/content/doc/installation/run-as-service-in-ubuntu.zh-cn.md
> +修改 user， home 目录以及其他必须的初始化参数，如果使用自定义端口，则需修改 PORT 参数，反之如果使用默认端口则需删除 -p 标记。
標點符號前後不需要空白

2018-10-17 14:40 UTC, BetaCat0 commented on docs/content/doc/installation/run-as-service-in-ubuntu.zh-cn.md
> +修改 user， home 目录以及其他必须的初始化参数，如果使用自定义端口，则需修改 PORT 参数，反之如果使用默认端口则需删除 -p 标记。
erased

2018-10-18 03:40 UTC, appleboy approved these changes

2018-10-18 05:19 UTC, merged