fix sqlite lock
go-gitea/gitea pull request #5184
Opened 2018-10-25 16:14 UTC by lunny

2018-10-26 09:39 UTC, lafriks approved these changes

2018-10-26 10:06 UTC, sapk requested changes

2018-10-26 10:06 UTC, sapk commented on models/issue_dependency.go
>  	exists, err := x.
Should this use e and not x ?
```suggestion
	exists, err := e.
```

2018-10-26 10:06 UTC, sapk commented on models/repo.go
>  	if err := repo.getUnits(x); err != nil {
Same here
```suggestion
	if err := repo.getUnits(e); err != nil {
```

2018-10-27 13:08 UTC, lunny commented
@sapk done.

2018-10-27 14:07 UTC, sapk approved these changes

2018-10-27 14:45 UTC, merged