Fix #5226 by adding CSRF checking to api reqToken and add CSRF to the POST header for deadline
go-gitea/gitea pull request #5250
Opened 2018-11-01 21:49 UTC by zeripath

#4840 attempted to prevent XSS attacks by preventing POSTs to API addresses without being logged in by Token or with BASIC auth. It did not add capability for providing a CSRF token.

This PR adds CSRF checking back in to the reqToken function with routers/api/v1/api.go and then adjusts the way deadlines are POSTed to pass in the CSRF token in as a header. 

Fixes #5226, #5249 

@beeonthego as far as I understand this would still prevent the XSS attacks. Is this correct?

2018-11-02 00:04 UTC, cezar97 commented
Hi @zeripath.
#4840 prevented CSRF and not XSS. It didn't add any CSRF Token because in this case it wasn't needed: forcing API authentication to API keys only, thus distrusting the cookies ( user session ), is enough, as an attacker doesn't know the key to make requests.
Because Gitea UI is using user session to authenticate the API, behavior broken by #4840,  issue #5226 was opened. As a solution, from #5249 seems that instead of using an API key for the UI ( BTW that was my proposal too because it seemed cleaner ), adding a CSRF check when using session is preferred, as @techknowlogick said.
So as far as I understand this PR, the API should validate a CSRF token only when session is used for authentication. No XSS attacks here, but yes, that's correct regarding CSRF.

2018-11-02 07:17 UTC, zeripath commented
Thanks for the clarification. As it stands the CSRF token will only be checked if there is no BASIC Auth or token. I should actually check that definitely means that the user is logged in with a session, however I'd be surprised if csrf.Validate would pass if there was no session.

2018-11-02 07:30 UTC, zeripath commented
Hmm ok looking again, I think there needs to be a check that the user is signed in before testing the CSRF, as it's possible to have a correct CSRF and session but not be logged in.

2018-11-02 09:30 UTC, kolaente requested changes

2018-11-02 09:30 UTC, kolaente commented on routers/api/v1/api.go
> +		if true == ctx.Data["IsApiToken"] {
Please use `if ctx.Data["IsApiToken"] {`.

2018-11-02 09:30 UTC, kolaente commented on routers/api/v1/api.go
> +			ctx.RequireCSRF()
You can add a `return` here and then drop the `else`

2018-11-02 13:35 UTC, zeripath commented
@cezar97 :
> @zeripath if the user is required to be logged in too, user and repo searching don't work when logged out?
> I'm referring to [#5249 (comment)](https://github.com/go-gitea/gitea/issues/5249#issuecomment-435146648) .

Those GET urls aren't protected by reqToken so aren't affected by this change. There are a few GET urls which are protected by reqToken - however, I think these are pure API urls.

I do think it may be worth rationalising and refactoring the API req* functions though. I don't think reqToken is a very good name for what it is doing. Also, I suspect that routes protected by reqAdmin are CSRF exploitable...

2018-11-02 14:57 UTC, zeripath commented
Hmm would it be helpful to go through the API urls systematically looking at where there might still be CSRF issues?

2018-11-02 17:13 UTC, cezar97 commented
> Hmm would it be helpful to go through the API urls systematically looking at where there might still be CSRF issues?

Only POST API routes are vulnerable, as GET ones follow the best practices and don't run any action, just display information that can't be retrieved by an attacker anyway.


> Also, I suspect that routes protected by reqAdmin are CSRF exploitable...

I'm not sure if the generic reqToken applys also on Admin API routes, for example before checking if the user is an Admin ( reqAdmin ), but if this is not the case then yes, they are affected too.

2018-11-03 11:57 UTC, zeripath commented
For clarity, @cezar97, the reqAdmin routes weren't being protected by reqToken and should have been. So I added that as a second commit.

2018-11-03 15:32 UTC, kolaente commented
> Only POST API routes are vulnerable, as GET ones follow the best practices and don't run any action, just display information that can't be retrieved by an attacker anyway.

No, things like the repo search can expose private repos.

2018-11-03 16:04 UTC, cezar97 commented
@kolaente thanks for your interest.

Of course there are GET routes that use the user session, but CSRF is about protecting state changing requests. The Gitea API runs actions only on POST, so these are the only ones vulnerable.
As said previously, even if an attacker send a GET requests to /user/emails he can't retrieve that information anyway, so that's why only POST are affected.

[Here](https://www.owasp.org/index.php/Cross-Site_Request_Forgery_(CSRF)) is a more detailed answer.


PS: I say that only POST is affected because that's what should be used for state changing requests. Again, the API follows this rule, the UI doesn't. That's why as a Proof of Concept I have 300+ followers on try.gitea.io ( it's an example of state changing request that use GET but shouldn't ).

2018-11-03 21:32 UTC, techknowlogick approved these changes

2018-11-03 21:33 UTC, techknowlogick commented
Looks great! 🎉

@kolaente would you be able to review again?

2018-11-03 22:17 UTC, kolaente commented
@cezar97 OK, I guess it doesn't make much of a difference if these are protected by CSRF or not.
Thanks for clarifying!

2018-11-03 22:18 UTC, kolaente approved these changes
Thanks!

2018-11-04 01:15 UTC, techknowlogick commented
Thanks for PR @zeripath. Now that this is merged, are you able to backport the commit to `release/v1.6` branch?

2018-11-04 01:15 UTC, merged