Add work wechat webhook
go-gitea/gitea pull request #5252
Opened 2018-11-02 02:04 UTC by rocklau

new feature: send events to work wechat group<chatid>

unit test done list
1. create new work wechat webhook
2. edit this webhook
3. push a commit, wechat group received this event

work flow: 

1. this command can get access token

get CORP_ID from https://work.weixin.qq.com/wework_admin/frame#profile

get APP_SECRET from your corporation app profile /wework_admin/frame#apps/modApiApp/

```bash
curl -X GET \
  'https://qyapi.weixin.qq.com/cgi-bin/gettoken?corpid=CORP_ID&corpsecret=CORP_APP_SECRET' 
```
```json 
{
    "errcode": 0,
    "errmsg": "ok",
    "access_token": "",
    "expires_in": 7200
}
```
2. and create your bot group 'gitea'
```bash
curl -X POST \
  'https://qyapi.weixin.qq.com/cgi-bin/appchat/create?access_token=ACCESS_TOKEN' \
  -H 'Content-Type: application/json' \
  -d '{
    "name" : "Gitea",
    "owner" : "XiaoMing",
    "userlist" : ["XiaoMing","XiaoHong"],
    "chatid" : "gitea"
}'
```
3. then we go to add new work wechat hook with access_token and chatid on gitea

TargetURL:https://qyapi.weixin.qq.com/cgi-bin/appchat/send?access_token=ACCESS_TOKEN

Chat ID: gitea

2018-11-02 02:09 UTC, techknowlogick requested changes

2018-11-02 02:09 UTC, techknowlogick commented on options/locale/locale_pt-BR.ini
> +settings.add_workwechat_hook_desc=Integre o <a href="%s">Work Wechat</a> em seu repositório.
Please add translations via https://crowdin.com/project/gitea

2018-11-02 02:09 UTC, rocklau commented on options/locale/locale_pt-BR.ini
> +settings.add_workwechat_hook_desc=Integre o <a href="%s">Work Wechat</a> em seu repositório.
ok.

2018-11-02 02:12 UTC, lunny requested changes

2018-11-02 02:12 UTC, lunny commented on models/webhook_workwechat.go
> +// Copyright 2017 The Gitea Authors. All rights reserved.
2018

2018-11-02 02:12 UTC, lunny commented on options/locale/locale_de-DE.ini
>  settings.add_dingtalk_hook_desc=<a href="%s">Dingtalk</a>-Integration zu deinem Repository hinzufügen.
don't translate them.

2018-11-02 02:12 UTC, lunny commented on routers/api/v1/convert/convert.go
> +	if w.HookTaskType == models.WORKWECHAT {
else if

2018-11-02 02:12 UTC, lunny commented on routers/repo/webhook.go
> +	if hookType == "workwechat" {
else if

2019-02-17 12:39 UTC, lunny commented
Please resolve conflicts.

2019-07-07 02:28 UTC, lunny commented
Please resolve conflicted files

2019-10-29 22:53 UTC, 6543 commented
@rocklau do you still work on this :( ?

2019-11-16 09:03 UTC, lunny commented
Please resolve the conflicts.

2019-12-28 19:32 UTC, 6543 commented
@rocklau #9422 made some changes ... so It is worth looking at it ... (you have to resolve conflicts anyway)

2019-12-28 19:34 UTC, 6543 commented
@rocklau  I know this PR is old ... but do you still have passion to get it upstream?

2019-12-30 10:11 UTC, closed without merging