[WIP] Prometheus endpoint
go-gitea/gitea pull request #5256
Opened 2018-11-02 10:58 UTC by gaydin

I want to try to finish the task #2751, initial commits are based on #678

I need help on several issues: 
1. How can l make an authorization token? 
It is necessary to use a token in app.ini and make it accessible from the section /admin?
Is need to make token in modules/gererate and save in configuration,If the token doesn't exist in configuration?
2. Do I need to add "metrics" in a [reservedUsernames](https://github.com/go-gitea/gitea/blob/master/models/user.go#L685)?
3. How can l correct dependencies? 
This PR is build successfully just if update it manually

sorry for my bad english :)

2018-11-02 12:40 UTC, gaydin commented
> For the deps, does `dep ensure -update github.com/golang/protobuf` solve the problem ?

Yes it helped. thank

2018-11-02 13:04 UTC, lunny submitted a review, later dismissed

2018-11-02 13:04 UTC, lunny commented on modules/metrics/collector.go
> +package metrics
comment head

2018-11-02 14:59 UTC, techknowlogick commented on modules/metrics/collector.go
> +	"github.com/prometheus/client_golang/prometheus"
Can you add an empty line between these two imports?

2018-11-02 15:58 UTC, gaydin commented
Bad idea to put metrics handler in a separate [file](https://github.com/go-gitea/gitea/blob/5e39a9e5a32f7909332a2c2525109d8b5174987d/routers/metrics.go)?

2018-11-02 16:58 UTC, techknowlogick commented
I think having it in separate file is best, because it is a unique area (just like how the api is split off into different files).

2018-11-03 14:45 UTC, lafriks approved these changes

2018-11-04 01:19 UTC, techknowlogick requested changes

2018-11-04 01:19 UTC, techknowlogick commented on modules/setting/setting.go
> +	Metrics = struct {
Are you able to add default values to `custom/conf/app.ini.sample` and also to `docs/content/doc/advanced/config-cheat-sheet.en-us.md`

2018-11-04 03:32 UTC, adelowo commented on modules/setting/setting.go
> +		Enable bool
Sounds like `Enabled` or `IsEnabled` would be a better fit for this ??

2018-11-04 15:25 UTC, techknowlogick approved these changes

2018-11-04 19:13 UTC, techknowlogick commented
@lunny please review again

2018-11-04 19:15 UTC, sapk approved these changes

2018-11-05 02:30 UTC, appleboy approved these changes

2018-11-05 03:08 UTC, techknowlogick commented
Maintainers note: Dismissing @lunny's review as requested change has been made, and there are 4 other positive reviews.

2018-11-05 03:20 UTC, merged