Comments list performance optimization
go-gitea/gitea pull request #5305
Opened 2018-11-09 03:07 UTC by lunny

Will also fix #5297

2018-11-10 09:52 UTC, zeripath requested changes

2018-11-11 04:57 UTC, lunny commented on models/issue_comment.go
> +func (c *Comment) loadAttachements(e Engine) (err error) {
done.

2018-11-11 17:48 UTC, zeripath commented on models/issue_comment_list.go
> +// loadAttributes loads all attributes, expect for attachments and comments
s/expect/except

2018-11-11 17:51 UTC, zeripath commented
How does this work for issues with a large number of comments?

It looks like this is going to get everything in one go.

2018-11-12 03:41 UTC, lunny commented
@zeripath This should have better performance than before when the issue has a large number of comments. The PR will reduce many database queries when loading comments attributes.

2018-12-27 10:59 UTC, lafriks commented
@lunny can you fix remainig issue with 500 error (see drone tests)

2019-01-02 12:58 UTC, lunny commented
@lafriks @JonasFranzDEV will fix this.

2019-01-04 14:11 UTC, lunny commented
@lafriks @jonasfranz fixed.

2019-04-02 05:23 UTC, lunny commented
It's ready to review.

2019-04-02 16:06 UTC, lafriks commented on models/issue_comment_list.go
> +			if !ok {
nit: This should be like in other functions:
```
if _, ok := issues[comment.Issue.ID]; !ok {
    issues[comment.Issue.ID] = comment.Issue
}
```

2019-04-16 14:38 UTC, lunny commented
@lafriks done.
@zeripath please review.

2019-04-16 14:52 UTC, zeripath approved these changes

2019-04-18 03:31 UTC, lafriks approved these changes

2019-04-18 05:00 UTC, merged