Updated Dutch translations
go-gitea/gitea pull request #533
Opened 2016-12-29 17:08 UTC by Bwko

As requested by  [@tboerger](https://github.com/go-gitea/gitea/pull/487#discussion_r94121404)
cc @mjwwit

2016-12-29 18:38 UTC, andreynering commented
Trusted LGTM

2016-12-29 19:53 UTC, bkcsoft requested changes
Otherwise Trusted LGTM

2016-12-29 19:53 UTC, bkcsoft commented on options/locale/locale_nl-NL.ini
> +kopie=Kopie
should be `mirror=Kopie`

2016-12-29 21:37 UTC, mjwwit requested changes
Loads better than before! I made a few small suggestions to make it more consistent.

2016-12-29 21:37 UTC, mjwwit commented on options/locale/locale_nl-NL.ini
>  update_profile=Profile bijwerken
update_profile=Profiel bijwerken

2016-12-29 21:37 UTC, mjwwit commented on options/locale/locale_nl-NL.ini
>  new_mirror=Nieuwe Kopie
new_mirror=Nieuwe kopie

2016-12-29 21:37 UTC, mjwwit commented on options/locale/locale_nl-NL.ini
> +err_empty_db_path=SQLite3 of TiDB database mag niet leeg.
err_empty_db_path=SQLite3 of TiDB database pad mag niet leeg zijn.

2016-12-29 21:37 UTC, mjwwit commented on options/locale/locale_nl-NL.ini
> +app_name_helper=Plaats hier je organisatienaam in hoofdletters!
app_name_helper=Plaats hier uw organisatienaam in hoofdletters!

2016-12-29 21:37 UTC, mjwwit commented on options/locale/locale_nl-NL.ini
> +ssh_helper=<strong>Weet je niet hoe?</strong> Lees dan onze handleiding voor het <a href="%s"> genereren van SSH sleutels</a> of voor <a href="%s"> algemene SSH</a> problemen.
ssh_helper=<strong>Weet u niet hoe?</strong> Lees dan onze handleiding voor het <a href="%s"> genereren van SSH sleutels</a> of voor <a href="%s"> algemene SSH</a> problemen.

2016-12-30 13:07 UTC, Bwko commented
@mjwwit & @bkcsoft Updated

2016-12-30 16:14 UTC, bkcsoft approved these changes

2016-12-30 16:15 UTC, bkcsoft commented
I'll have @mjwwit LG_TM since he apparently knows the language at hand 😉

2016-12-30 16:21 UTC, mjwwit commented
LGTM

2016-12-30 20:05 UTC, bkcsoft commented
something is wrong with LGTM...

2016-12-30 20:05 UTC, merged