Notifications - Step 2
go-gitea/gitea pull request #539
Opened 2016-12-30 18:56 UTC by andreynering

UI for notifications

2016-12-30 19:40 UTC, bkcsoft requested changes
Otherwise 💯 🎉

2016-12-30 19:40 UTC, bkcsoft commented on cmd/web.go
> +	m.Use(user.GetNotificationCount)
Doesn't this add unnecessary overhead for endpoints like `/api` that will _never_ use it? :)

2016-12-30 19:40 UTC, bkcsoft commented on public/less/_user.less
> +        .octicon-issue-opened, .octicon-git-pull-request {
Aren't these defined somewhere already that we can reuse? (for the activity/dashboard feed)

2016-12-31 01:06 UTC, lunny commented on cmd/web.go
> +	m.Use(user.GetNotificationCount)
^, why use a middleware here?

2017-01-02 15:21 UTC, metalmatze commented
If you're creating UI changes a little screenshot would be pretty helpful for just browsing github! 👍 😊

2017-01-02 18:55 UTC, andreynering commented on public/less/_user.less
> +        .octicon-issue-opened, .octicon-git-pull-request {
I don't think so.

2017-01-02 19:04 UTC, andreynering commented
Here a few pics:

- [1](https://cloud.githubusercontent.com/assets/7011819/21594733/371bc508-d10d-11e6-9264-9cd5a3ba6a83.png)
- [2](https://cloud.githubusercontent.com/assets/7011819/21594732/370f5cfa-d10d-11e6-8834-ab157169808f.png)
- [3](https://cloud.githubusercontent.com/assets/7011819/21594731/370a7604-d10d-11e6-90f9-9c8606233510.png)
- [4](https://cloud.githubusercontent.com/assets/7011819/21594730/36e99358-d10d-11e6-82d9-89efa83fd787.png)
- [5](https://cloud.githubusercontent.com/assets/7011819/21594729/36e69d56-d10d-11e6-8f92-ee547a76b3da.png)

It's working, but still very simple and missing some key functionality: pagination (must have), mark as read/unread, pinning a notification, others. Should this be done in this PR or on another ones?

2017-01-02 19:05 UTC, andreynering commented on cmd/web.go
> +	m.Use(user.GetNotificationCount)
Done

2017-01-02 22:07 UTC, bkcsoft commented
Pagination is a must for this one, the others can be extended on if necessary :)

2017-01-03 00:17 UTC, lunny commented
^

2017-01-05 01:27 UTC, lunny commented
LGTM

2017-01-05 01:29 UTC, appleboy approved these changes

2017-01-05 01:29 UTC, appleboy commented
LGTM

2017-01-05 08:46 UTC, strk commented
@bkcsoft are your requested changes good now ?

2017-01-05 13:53 UTC, merged

2017-01-05 15:01 UTC, gsantner commented
The Link in the UI is wrong when behind reverse proxy.
Mine is under `https://mydomain.xyz/gogitea` and everything links corretctly to subpaths (e.g. `https://mydomain.xyz/gogitea/issues`) but this one links to `https://mydomain.xyz/notifications` which, apparently doesn't exist.

2017-01-05 15:23 UTC, andreynering commented
@gsantner Thank you for pointing. That's easy to fix.