Set default less and css to new default name
go-gitea/gitea pull request #54
Opened 2016-11-03 18:36 UTC by joubertredrat

Remove mentions to Gogs on js, css and less files

2016-11-03 19:12 UTC, tboerger requested changes

2016-11-03 19:12 UTC, tboerger commented on public/css/index.css
>  code.wrap {
Unrelated changes for that PR?

2016-11-03 19:17 UTC, joubertredrat commented on public/css/index.css
>  code.wrap {
Only unnecessary spaces was removed. selector continue with same definitions.
https://github.com/go-gitea/gitea/blob/master/public/css/gogs.css#L31
https://github.com/joubertredrat/gitea/blob/changes-less-css/public/css/index.css#L31

2016-11-03 19:28 UTC, tboerger commented on public/css/index.css
>  code.wrap {
But there are css changes, you just renamed the less file.

2016-11-03 19:37 UTC, joubertredrat commented on public/css/index.css
>  code.wrap {
@tboerger was my fault, If you see on PR https://github.com/gogits/gogs/pull/3786, don't have empty lines on css, I don't know why, my npm display that less version is 2.7.1, but on my terminal was using 1.4.2. Now I solved this and generated correct css files, with no empty files and with `!important` as defined on less.

2016-11-03 20:53 UTC, tboerger approved these changes

2016-11-03 20:53 UTC, tboerger commented
LGTM

2016-11-03 20:54 UTC, DblK commented
LGTM

2016-11-04 11:01 UTC, joubertredrat commented
Done, with rebase

2016-11-04 11:02 UTC, joubertredrat commented
LGTM

2016-11-04 13:36 UTC, tboerger commented
LGTM

2016-11-04 14:41 UTC, lunny commented
LGTM

2016-11-04 16:45 UTC, xinity commented
LGTM

2016-11-04 22:24 UTC, merged