webhooks: Add `head_commit` field to push payload.
go-gitea/gitea pull request #5419
Opened 2018-11-27 18:29 UTC by HarshitOnGitHub

Would appreciate comments/feedback on whether the approach taken is correct or not. Have tested the changes manually.

Fixes: #5266.

2018-11-29 18:53 UTC, HarshitOnGitHub commented
(Updated dependency, build should pass now!)

2018-11-29 19:43 UTC, lafriks commented
Would be great if convert.ToCommit could be reused somehow to get api.PayloadCommit to not have so much duplicated code.

2018-12-27 11:06 UTC, lafriks commented
@HarshitOnGitHub can you fix to reuse `convert.ToCommit`?

2018-12-29 10:35 UTC, HarshitOnGitHub commented
@lafriks `convert.ToCommit` can't be used directly as it causes cyclic dependency. I was thinking of moving the function to some other place but couldn't decide on a good new place for it.

2019-01-02 08:37 UTC, HarshitOnGitHub commented
@lafriks Thoughts?

2019-01-19 16:48 UTC, HarshitOnGitHub commented
Any help/suggestions would be appreciated! :)

2019-01-19 16:57 UTC, lunny requested changes

2019-01-19 16:57 UTC, lunny commented on models/action.go
> +			HeadCommit: getHeadCommit(repo, opts.NewCommitID),
Could we get the head PayloadCommit from APIPayLoadCommits ?

2019-11-16 09:03 UTC, lunny commented
Please resolve the conflicts

2021-06-29 13:34 UTC, closed without merging