check if signups are allowed during SignUpPost
go-gitea/gitea pull request #5437
Opened 2018-11-30 23:37 UTC by romankl

Previously you could hide the sign up page with the following
configs:

```ini
[service]
SHOW_REGISTRATION_BUTTON          = false
```

This would remove the sign up button from the navbar, but the user could still access the page with a direct link. During the http post action, the go action checked if the key `SHOW_REGISTRATION_BUTTON` was set to true. If not, the user received a 403.

You can use this scenario for a semi-hidden sign up page that is only accessible through a direct link.

I've changed the check in this PR to check if the sign up is allowed or not. The user can access the sign up page (if it's enabled) and sign up even if the value of `SHOW_REGISTRATION_BUTTON` is `false`, the user can sign up.

Another solution could be:
- unify `SHOW_REGISTRATION_BUTTON ` with `DISABLE_REGISTRATION ` to
only show the registration page if it's enabled, but that would dis-
allow the mentioned scenario

fixes: https://github.com/go-gitea/gitea/issues/5183

2018-12-11 20:39 UTC, kolaente commented
I see no point in why we have two settings which try to achive the same goal. From a security perspective, only hiding the button and still enabling sign ups is useless if the path is kept the same, an attacker could just try to visit `gitea-instance.tld/register` and only hiding a button to that page wont prevent him from doing so.

So, I'd prefer to uinon these two settings.

2019-02-25 11:54 UTC, lunny approved these changes

2019-02-25 11:56 UTC, lunny commented
I think we can drop `SHOW_REGISTRATION_BUTTON` and always use `DISABLE_REGISTRATION`.

2019-02-26 20:06 UTC, zeripath commented
@lunny this PR doesn't actually drop `SHOW_REGISTRATION_BUTTON` - it's just that this PR disconnects `SHOW_REGISTRATION_BUTTON` and `DISABLE_REGISTRATION` - so if you set `SHOW_REGISTRATION_BUTTON` to false but leave `DISABLE_REGISTRATION` unset you can still register.

@romankl in order prevent a broken UI you need to change https://github.com/go-gitea/gitea/blob/master/modules/setting/service.go#L57 : 

```go
Service.ShowRegistrationButton = sec.Key("SHOW_REGISTRATION_BUTTON").MustBool(!(Service.DisableRegistration || Service.AllowOnlyExternalRegistration))
```

to

```go
Service.ShowRegistrationButton = sec.Key("SHOW_REGISTRATION_BUTTON").MustBool(true) && !(Service.DisableRegistration || Service.AllowOnlyExternalRegistration)
```

So that `DISABLE_REGISTRATION` and `ALLOW_ONLY_EXTERNAL_REGISTRATION` properly override `SHOW_REGISTRATION_BUTTON`

2019-02-26 20:07 UTC, zeripath requested changes
See my comment above.

2019-07-19 09:26 UTC, closed without merging