WIP: improve team members and repositories settings UI
go-gitea/gitea pull request #5457
Opened 2018-12-04 01:15 UTC by lunny

2018-12-08 14:36 UTC, lunny commented
It's ready to review. @go-gitea/maintainers

2018-12-09 00:55 UTC, lafriks requested changes

2018-12-09 00:55 UTC, lafriks commented on options/locale/locale_en-US.ini
> +teams.repos.none = No repository could be accessed by this team members.
Should be `No repositories can be accessed by this team.`

2018-12-09 00:55 UTC, lafriks commented on options/locale/locale_en-US.ini
> +teams.members.none = No member on this team.
Should be `No members in this team.`

2018-12-09 02:30 UTC, lunny commented
@lafriks done.

2018-12-09 02:39 UTC, techknowlogick commented
LGTM

2018-12-09 06:42 UTC, lafriks approved these changes

2018-12-09 06:42 UTC, merged