[WIP] Unit tests for models/pull.go
go-gitea/gitea pull request #555
Opened 2017-01-02 03:49 UTC by ethantkoenig

The main problem is that I'm not sure the best way to "mock out" git repositories in the filesystem to match the database fixtures.

Should we add a script to create these repos? This seems less-than-ideal, since the script would be really tedious, and it would have to be kept in-sync with the test fixtures. Does anyone have a better suggestion?

2017-01-02 17:45 UTC, andreynering commented
Failing for me and on Drone.

I think mocking Git is not trivial and should be discussed in a proposal.

Can you for now don't keep tests that touch Git?

2017-01-02 17:46 UTC, ethantkoenig commented
Sure

2017-01-02 23:29 UTC, bkcsoft commented on models/pull.go
> +		return nil, ErrPullRequestNotExist{0, 0, 0, repoID, "", ""}
Why was this changed? :)

2017-01-02 23:30 UTC, bkcsoft commented
Maybe we shouldn't moch git operations? maybe provide "well known" repos for testing?

2017-01-03 04:51 UTC, ethantkoenig commented on models/pull.go
> +		return nil, ErrPullRequestNotExist{0, 0, 0, repoID, "", ""}
The arguments were provided in the wrong order. Sorry, maybe this should have been in a separate PR.

2017-01-04 00:12 UTC, ethantkoenig commented
@bkcsoft @andreynering For now, I've added TODOs for the tests that require git.

2017-01-04 00:21 UTC, lunny commented
Well known repo ---> Gitea

2017-01-05 01:11 UTC, lunny requested changes

2017-01-05 01:11 UTC, lunny commented on models/pull.go
> +			fmt.Printf("User doesn't exist! (mergerId=%d)\n", pr.MergerID)
Unremoved trace code?

2017-01-05 01:11 UTC, lunny commented on models/pull.go
> +			fmt.Printf("loadAttirbutes(mergerId=%d): Error%v\n", pr.MergerID, err)
^

2017-01-05 02:09 UTC, ethantkoenig commented
@lunny Trace code removed, sorry about that

2017-01-06 13:04 UTC, andreynering commented on models/pull.go
>  )
Import grouping:

```go
 import (
 	"fmt"
 	"os"
 	"path"
 	"path/filepath"
 	"strconv"
 	"strings"
 	"time"
 
 	"code.gitea.io/git"
 	"code.gitea.io/gitea/modules/log"
 	"code.gitea.io/gitea/modules/process"
 	"code.gitea.io/gitea/modules/setting"
 	"code.gitea.io/gitea/modules/sync"
  	api "code.gitea.io/sdk/gitea"
 	"code.gitea.io/gitea/modules/base"

  	"github.com/Unknwon/com"
  	"github.com/go-xorm/xorm"
  )
```

2017-01-06 13:04 UTC, andreynering commented on models/pull_test.go
> +)
```go
import (
 	"testing"
 	"time"

 	"github.com/stretchr/testify/assert"
 )
```

2017-01-06 13:05 UTC, andreynering commented
Two little things. Otherwise LGTM

2017-01-06 14:58 UTC, lunny approved these changes

2017-01-06 14:59 UTC, lunny commented
LGTM

2017-01-06 20:57 UTC, strk commented
trusted LGTM

2017-01-06 21:19 UTC, merged