security: some organization endpoints can be accessed without authorization
go-gitea/gitea pull request #5604
Opened 2018-12-27 15:34 UTC by adelowo

Fixes #5603 

I didn't add `reqToken` for the `/api/v1/orgs/{org}` endpoint as the information that are
returns are minimal and there is no notion of a public or private organization in Gitea.

2019-01-01 15:17 UTC, JonasFranzDEV commented on routers/api/v1/api.go
> +				m.Get("", reqToken(), reqOrgMembership(), org.ListMembers)
Why should this require to be signed in or being member of the org? This may be public since organizations are public by default at the webinterface.

2019-01-01 15:20 UTC, jonasfranz requested changes

2019-01-01 15:20 UTC, JonasFranzDEV commented on routers/api/v1/api.go
> +				m.Combo("/:username").Get(reqToken(), reqOrgMembership(), org.IsMember).
This should only require to be signed in if the members are not public.

2019-04-20 21:21 UTC, lafriks commented
Is this still actual?

2019-04-21 03:50 UTC, lunny commented
@lafriks I think we should check some APIs haven't obey `REQUIRE_SIGNIN_VIEW = true` but not this PR.

2019-04-24 11:58 UTC, adelowo commented
Closing as per https://github.com/go-gitea/gitea/issues/5603#issuecomment-486092995

2019-04-24 11:58 UTC, closed without merging