Add docs about database migration
go-gitea/gitea pull request #5661
Opened 2019-01-07 21:40 UTC by Chouchen

Update documentation for database migrations from Gogs as asked in #4163

2019-01-08 07:48 UTC, lafriks approved these changes

2019-01-08 11:22 UTC, lunny requested changes
I think `Launch every major version` should before run `Rewrite all update hook of repositories`, that's not the correct sequence.

2019-01-08 11:34 UTC, jonasfranz approved these changes

2019-01-10 16:35 UTC, techknowlogick commented
@lunny changes have been made, please review.

2019-01-11 02:35 UTC, lunny approved these changes

2019-01-11 03:58 UTC, merged