Improve the performance of tree listing
go-gitea/gitea pull request #570
Opened 2017-01-03 11:22 UTC by typeless

1. Add two query strings `start` and `count` for the home page of repository.  If not supplied, the default values are: `?start=0&count=100`    
   
2. Remove redundant sorting operation, which is already done by git-mktree(1). See ftp://www.kernel.org/pub/software/scm/git/docs/git-mktree.html

The `count` value is hardwired for now.

For #502

2017-01-03 11:27 UTC, lunny requested changes

2017-01-03 11:27 UTC, lunny commented on routers/repo/view.go
> +	var start, count int = 0, 100
I prefer the count could be configured and If we ignored some files we have to give a hint on the UI.

2017-01-03 11:27 UTC, lunny commented on routers/repo/view.go
> +	if _start, ok := query["start"]; ok && len(_start) == 1 {
`ctx. QueryInt ("start")` is more convenient.

2017-01-03 11:27 UTC, lunny commented on routers/repo/view.go
> +	if _count, ok := query["count"]; ok && len(_count) == 1 {
`ctx.QueryInt ("count")`

2017-01-03 11:27 UTC, lunny commented on routers/repo/view.go
> +	entries = entries[start : start+count]
lost sort?

2017-01-03 11:30 UTC, typeless commented on routers/repo/view.go
> +	entries = entries[start : start+count]
According to ftp://www.kernel.org/pub/software/scm/git/docs/git-mktree.html, that has been done by git itself when creating the tree object. And my trivial testing seems to confirm it.

2017-01-03 11:36 UTC, typeless commented on routers/repo/view.go
> +	var start, count int = 0, 100
That would be better. Let me figure out how to do it properly.

2017-01-05 21:34 UTC, Bwko commented
When count is not set it shows no commits. When coun/startt > commits Gitea panics

2017-01-06 00:49 UTC, typeless commented
Please mark this as work-in-progress, I will finish this PR later (adding front-end controls as @lunny suggested).

@Bwko Thanks for pointing it out.

2017-01-06 19:28 UTC, Bwko commented
@typeless Good work :+1:  Only the sorting is alphabetically and not folder first.

2017-01-07 02:29 UTC, typeless commented
@Bwko My bad 😆 , didn't notice the nuances.

2017-01-07 02:51 UTC, appleboy requested changes

2017-01-07 02:51 UTC, appleboy commented on routers/repo/view.go
Remove redundant empty line.

2017-01-13 01:45 UTC, ethantkoenig requested changes

2017-01-13 01:45 UTC, ethantkoenig commented on routers/repo/view.go
> +	if (start == 0 && count == 0) || start+count < start || start+count > len(entries) {
Could we replace `start+count < start` with `count < 0`?

2017-01-23 11:24 UTC, lunny commented
@typeless Is this PR ready to review?

2017-01-24 01:41 UTC, typeless commented
@lunny The UI part is still missing if that is desired to be included in this PR.

2017-02-12 07:44 UTC, bkcsoft commented
@typeless UI would be required yes, otherwise there may be issue in the future :( Would be nice to have it fetch and render the next set of files via API, like GitHub has `load more entries...` when there's to many files 🙂

2017-02-12 07:46 UTC, bkcsoft commented
You could also just include the `base/paginate.tmpl`, but then you need to use `?page=0` and a static count 🙁

2017-02-14 06:24 UTC, lunny approved these changes

2017-02-14 06:25 UTC, lunny commented
@typeless Is this completed?

2017-02-14 09:49 UTC, typeless commented
@lunny I don't have a good idea about how the UI design should be done, before starting to get familiar with Semantic UI. Please bear with me as my spare timeslices for OSS projects are very limited recently.

If someone is willing to help implement the web UI (I am really not good at it), that would be appreciated.

2017-02-14 09:54 UTC, lunny commented
OK. Please give the permissions to let maintainers to push to your branch, it's in this PR right sidebar. And I will move this to v1.2.

2017-02-14 09:58 UTC, typeless commented
@lunny  Thanks. I have the "allow edits from maintainers" checked.

2017-02-14 22:46 UTC, bkcsoft commented
@typeless @lunny I can look at implementing lazy-loading during the weekend 😄

2017-02-23 13:50 UTC, lunny commented
@bkcsoft any update?

2017-04-07 02:19 UTC, bkcsoft commented
@lunny I've been swamped with work unfortunately 🙁

2018-12-22 01:49 UTC, closed without merging