More deadlocks
go-gitea/gitea pull request #5718
Opened 2019-01-13 14:52 UTC by zeripath

I've looked through the gitea code following the use x.NewSession() checking whether every request is made within the session in an attempt to prevent a deadlock. 

This PR accounts for most of the potential deadlocks I've found in those requests.

## Issues
* Although https://github.com/go-gitea/gitea/blob/master/models/issue.go#L1349 opens a session its call to IssuesList.loadAttributes cannot be called within the session because of an unusual bug https://github.com/go-xorm/xorm/issues/1185 . This doesn't need to happen within the session as this session is not a transaction
* `models/repo_mirror.go:SyncMirrors()` doesn't pass its session down to its children calls however, it doesn't create a transaction (despite updating the db) - this is likely reasonable as the transaction would lock the db whilst these somewhat long actions were ongoing. This could be refactored to have an ongoing mirror action flag in the db (changed and checked with a transaction of course) that would be cleaned up at the end of the method if data consistency was at risk from this. (I haven't looked deep into this and this is likely a non-issue.)

2019-01-13 14:57 UTC, lunny requested changes

2019-01-13 14:57 UTC, lunny commented on models/org.go
>  	return x.
```
e.
```

2019-01-13 15:03 UTC, zeripath commented on models/org.go
>  	return x.
OK I'm an idiot. Sorry.

2019-01-14 00:07 UTC, lafriks approved these changes

2019-01-14 02:09 UTC, lunny approved these changes

2019-01-14 02:29 UTC, merged