Config option to disable automatic repo watching
go-gitea/gitea pull request #5852
Opened 2019-01-25 18:54 UTC by sebastian-sauer

Add a new config option AUTO_WATCH_NEW_REPOS to enable / disable the automatic watching of
repos for new repositories and if a user is added to a team.

2019-01-25 22:08 UTC, lafriks commented
It would be great if that could be added also as per-user option

2019-01-25 22:50 UTC, adelowo requested changes
You also need to update `app.ini.sample` https://github.com/go-gitea/gitea/blob/master/custom/conf/app.ini.sample

2019-01-26 16:09 UTC, adelowo commented on models/org_team.go
> +	"code.gitea.io/gitea/modules/setting"
add a  new line before the "github" import

2019-01-26 16:19 UTC, kolaente approved these changes

2019-01-26 21:16 UTC, adelowo approved these changes

2019-01-27 09:25 UTC, merged

2019-01-27 11:15 UTC, kolaente commented
Mssql test failed when merging, can someone restart the build?

2020-01-21 12:59 UTC, trepmag commented
Hello, I tested the variable set to `AUTO_WATCH_NEW_REPOS=false` as follow:
- when adding a user to the Owner team of an Organization related repositories are being watch by this user
- when creating a repository that repository is getting watch by all user set in the related Organization Owner team

Is thoses use cases are intent to be covered by those use cases?

This was observed with `1.10.3`