Fix an error while adding a dependency via UI.
go-gitea/gitea pull request #5862
Opened 2019-01-26 12:13 UTC by HarshitOnGitHub

We were not checking if the `Repo` attribute is loaded or not before using it.

![image](https://user-images.githubusercontent.com/16687990/51786971-c0323080-2191-11e9-87af-d436d0fd29d4.png)

Fixes: #5783.

2019-01-26 13:15 UTC, zeripath requested changes

2019-01-26 13:15 UTC, zeripath commented on models/issue_comment.go
> +	if err = issue.LoadRepo(); err != nil {
You must load the repo from with the provided session `e`

2019-01-26 15:06 UTC, zeripath commented on models/issue_comment.go
> +	if err = issue.LoadRepo(); err != nil {
To be more explicit, when there is an open transaction you **MUST** use the provided `*xorm.Session` to do database lookups.

This line should read:

```go
     if err = issue.loadRepo(e); err != nil {
```

If you don't do this you will cause deadlocks.

2019-01-27 09:21 UTC, zeripath approved these changes

2019-01-27 09:22 UTC, kolaente approved these changes

2019-01-27 09:38 UTC, zeripath commented on models/issue_comment.go
> +	if err = issue.LoadRepo(); err != nil {
No problems. It was caught. That's the point of the review system. I've added bugs myself - see the debacle about the last migration. (Although I've more than suffered trying to create migration tests as my penance.)

Thanks for updating the tests too. I think they're due a rationalisation - we probably need to make the integration tests more story like - create repos, fix issues, upload stuff etc. At present they're more of a hodgepodge of almost unit tests which take too long to complete.

2019-01-27 11:31 UTC, merged

2019-01-28 10:54 UTC, HarshitOnGitHub commented
@lunny Done.

2019-01-28 13:02 UTC, adelowo commented
@zeripath Can you add `backport/done` label