Add data directory excluding sessions to dump (#586)
go-gitea/gitea pull request #587
Opened 2017-01-05 04:02 UTC by mkuhlmann

This includes the data directory inside a gitea dump. Sessions are excluded if the session provider is set to file and the session directory is a child of the data directory.

Closes #586

2017-01-05 13:39 UTC, mkuhlmann commented
Works now. The issue was an unset `PROVIDER_CONFIG` in custom app.ini. Then the configuration value is just empty and macaron uses a standard `data/sessions`. Thats another bug that should be resolved, since the expected behavior should session path to be relative to `APP_DATA_PATH` and not to the executable path. If `APP_DATA_PATH` is set to another location but `PROVIDER_CONFIG` is not set, sessions will be still saved to `data/sessions`.

I've hardcoded `data/sessions` to match [macarons](https://github.com/go-gitea/gitea/blob/9d1bc9aac88bda13e4b9319ab915bca1b65521f6/vendor/github.com/go-macaron/session/session.go#L113) fallback config var as a workaround and it works for now.

2017-01-05 13:47 UTC, lunny commented
LGTM

2017-01-06 00:35 UTC, bkcsoft requested changes
Please don't use uncommon abbreviations for variables :)

2017-01-06 00:35 UTC, bkcsoft commented on cmd/dump.go
> +	fis, err := dir.Readdir(0)
could we call it `files, err` instead?

2017-01-06 00:35 UTC, bkcsoft commented on cmd/dump.go
> +	for _, fi := range fis {
same hear, `file := range files`

2017-01-06 14:43 UTC, mkuhlmann commented
@bkcsoft Fixed, much cleaner now ;)

2017-01-07 21:36 UTC, strk commented
LGTM

2017-01-12 04:47 UTC, merged

2017-01-12 04:47 UTC, lunny commented
We have to merge this at first. @bkcsoft if you have any further information, please open another issue.