feat: support pid file.
go-gitea/gitea pull request #610
Opened 2017-01-08 06:32 UTC by appleboy

We can restart the app automatically by the following command.

```sh
kill -USR2 $(cat custom/run/app.pid)
```

2017-01-08 09:14 UTC, lunny commented
Why we need a pid file?

2017-01-08 09:48 UTC, appleboy commented
You can also use that information (just do a `cat filename.pid`) to kill the process yourself, using `echo filename.pid | xargs kill`. For develop purpose, you just build the binary and execute `kill -USR2 $(cat custom/run/app.pid)` command to restart app.

2017-01-08 11:30 UTC, tboerger commented
I never needed that before but LGTM

2017-01-08 11:34 UTC, 0xbaadf00d commented
What happening if PID file already exist (ie: the app crash) ?  I think PID file must don't be created if -p flag or explicit configuration on app.ini is not specified to avoid any issue or conflict with System D, supervisor, or other kind of tools

2017-01-08 13:25 UTC, appleboy commented
@0xbaadf00d You don't worry about the PID file exists or not. App can be restarted successfully if you remove the pid file. Just try the following command.

```sh
gitea web
rm -rf custom/run/app.pid
kill -USR2 gitea_pid
cat custom/run/app.pid
```

2017-01-08 15:43 UTC, Bwko commented
@appleboy What happens when a startup script also sets a PID?

2017-01-08 16:31 UTC, appleboy commented
@Bwko What kind of start script do you use?

2017-01-08 20:35 UTC, ekozan commented
what about windows ? it's work ?

2017-01-09 08:44 UTC, appleboy commented
@ekozan Yes. Also working on Windows platform.

2017-01-09 08:56 UTC, appleboy commented
@Bwko 

![screen shot 2017-01-09 at 4 53 55 pm](https://cloud.githubusercontent.com/assets/21979/21761227/70754b60-d68c-11e6-8b4c-7770ccb60f31.png)

Also working on [start-stop-daemon](http://man7.org/linux/man-pages/man8/start-stop-daemon.8.html) command

2017-01-09 09:43 UTC, metalmatze requested changes

2017-01-09 09:43 UTC, metalmatze commented on modules/setting/setting.go
> +	os.MkdirAll(filepath.Dir(pidPath), os.ModePerm)
Please check the error returned by `os.MkdirAll()`.

2017-01-09 11:21 UTC, Bwko commented
@appleboy Thanks :+1:  When you add metalmatze suggestions I'll LGT-M :smile:

2017-01-09 11:23 UTC, appleboy commented on modules/setting/setting.go
> +	os.MkdirAll(filepath.Dir(pidPath), os.ModePerm)
@metalmatze Done! Please review again.

2017-01-09 11:23 UTC, appleboy commented
@Bwko Done!

2017-01-09 11:31 UTC, Bwko commented on modules/setting/setting.go
> +	file, err := os.Create(pidPath)
Quoting bkcsoft on this one:

> Overall, change the format to this instead whenever possible. Keeps errors(variables) bound to their context(block).

`if err := os.Create(...); err != nil {
  [...]
}`

2017-01-09 11:31 UTC, Bwko commented on modules/setting/setting.go
> +		log.Fatal(4, "Can' create PID folder on %s", err)
Some nitpicking: missing a `t` here

2017-01-09 11:53 UTC, appleboy commented on modules/setting/setting.go
> +	file, err := os.Create(pidPath)
@Bwko We need `file` variable.

2017-01-09 12:00 UTC, Bwko commented on modules/setting/setting.go
> +	file, err := os.Create(pidPath)
Sorry my bad :sweat_smile:

2017-01-09 12:00 UTC, Bwko commented
LGTM

2017-01-09 13:49 UTC, lunny commented
need @metalmatze approve

2017-01-09 13:51 UTC, merged

2017-01-09 14:26 UTC, appleboy commented
@lunny @Bwko @metalmatze Thanks