Override xorm type mapping for U2F counter
go-gitea/gitea pull request #6232
Opened 2019-03-03 14:25 UTC by mporrato

Fix U2F authentication failure with token counter value >= 2^31 when using PostgreSQL.
Closes #6168

2019-03-03 15:01 UTC, jonasfranz commented
Maybe you should consider to add a migration.

2019-03-03 16:22 UTC, lafriks commented
Yes, this would need to add migration to update exisiting database

2019-03-03 18:16 UTC, zeripath approved these changes

2019-03-03 22:09 UTC, lafriks requested changes

2019-03-03 22:09 UTC, lafriks commented on models/migrations/v81.go
> +	if err := x.Sync2(new(U2FRegistration)); err != nil {
This won't fix existing database. You need to do manual column type change:
For postgres:
```
ALTER TABLE `u2f_registration` ALTER COLUMN `counter` TYPE bigint;
```
For MySQL:
```
ALTER TABLE `u2f_registration` MODIFY COLUMN `counter` BIGINT;
```
Microsoft SQL Server:
```
ALTER TABLE `u2f_registration` ALTER COLUMN `counter` bigint;
```
For SQLite you need to do in transaction:

* Rename old table:
```
ALTER TABLE `u2f_registration` RENAME TO `u2f_registration_old`;
```
* Create new table: `sess.Sync2(new(U2FRegistration))`
* Copy data from old to new one:
```
INSERT INTO `u2f_registration` SELECT * FROM `u2f_registration_old`;
```
* Drop old table
```
DROP TABLE IF EXISTS `u2f_registration_old`;
```

2019-03-04 02:11 UTC, lunny commented
Yesterday, I'm also investigate this bug. My yubikey could work with github but not gitea. I will try this PR to check if it fixed the bug.

2019-03-04 02:18 UTC, lunny commented
But it seems this doesn't fix my issue.

2019-03-04 07:40 UTC, mporrato commented
@lafriks I believe updating the sqlite3 schema is not needed since it has a single integer type which is big enough to hold an uint32. Sorry for my poor xorm knowledge: haven't used it before. :)

@lunny have you checked if your logs look like https://gist.github.com/mporrato/251450f7786075a887ad21a1728a5407 ? If that's the case, can you connect to the gitea db and do a `\d u2f_registration` ?

2019-03-04 09:20 UTC, lafriks requested changes

2019-03-04 09:20 UTC, lafriks commented on models/migrations/v81.go
> +	case "mysql":
You can add:
```
case "tidb":
	fallthrough
```
as MySQL has same syntax.

2019-03-04 09:20 UTC, lafriks commented on models/migrations/v81.go
> +		_, err = x.Exec("ALTER TABLE u2f_registration ALTER COLUMN \"counter\" SET DATA TYPE bigint")
xorm will fix correct esaping
```suggestion
		_, err = x.Exec("ALTER TABLE `u2f_registration` ALTER COLUMN `counter` SET DATA TYPE bigint")
```

2019-03-04 09:20 UTC, lafriks commented on models/migrations/v81.go
> +		_, err = x.Exec("ALTER TABLE u2f_registration ALTER COLUMN \"counter\" BIGINT")
Same here
```suggestion
		_, err = x.Exec("ALTER TABLE `u2f_registration` ALTER COLUMN `counter` BIGINT")
```

2019-03-04 09:20 UTC, lafriks commented on models/migrations/v81.go
> +		_, err = x.Exec("ALTER TABLE u2f_registration MODIFY `counter` BIGINT")
```suggestion
		_, err = x.Exec("ALTER TABLE `u2f_registration` MODIFY `counter` BIGINT")
```

2019-03-04 09:20 UTC, lafriks commented on models/migrations/v81.go
> +	case "sqlite3":
No need for empty case, this can be removed

2019-03-04 09:21 UTC, lafriks commented
No need to be sorry about, that's why there is review process to learn things :)

2019-03-04 22:34 UTC, lafriks approved these changes

2019-03-04 22:35 UTC, techknowlogick commented
I don’t think we need tidb case because for tidb v2 the protocol would be MySQL. Also should sessions be used?

2019-03-04 22:36 UTC, lafriks commented
@techknowlogick no session is needed for single sql command

2019-03-05 02:34 UTC, merged

2020-08-27 08:22 UTC, hpodhaisky commented
Is this problem still open? I am still getting "Could not read your security key." with  gitea 1.12.1 with sqlite3 on debian stable (buster). My solo key NFC works with github.