Fix to the new pull request button
go-gitea/gitea pull request #6248
Opened 2019-03-05 20:12 UTC by User00015

Fixing an issue where the new pull request button was pointing to an incorrect repository. 

To reproduce:

1) Create a fresh new gitea
2) Register as a new user, admin or otherwise.
3) Create a new organization.
4) Go to the organizations dashboard, 
5) Create a repository under that organization and initilize it
6) Return to the organization dashboard and select the newly created repository
7) Click the green new pull request icon

Expected Result:
You are taken to a branch-to-branch merge with the repository

Actual result:
You are taken to a non-existent fork that assumes to exist that leads to a 404

2019-03-05 20:17 UTC, techknowlogick commented on .gitignore
> +/.vs
Please revert the change to this file.

2019-03-05 20:27 UTC, User00015 reviewed
Removed.

2019-03-06 16:28 UTC, silverwind commented
> Removed.

Diff still shows a newline added, you might want to remove it :)

2019-03-06 17:13 UTC, User00015 reviewed
Removed for real this time.

2019-03-18 20:14 UTC, Piraty commented
please squash the commits and give it an appropriate comment

2019-03-18 21:02 UTC, zeripath requested changes
There's no need to squash commits - we squash them on merging.

2019-03-27 17:38 UTC, closed without merging