Notifications: mark as read/unread and pin
go-gitea/gitea pull request #629
Opened 2017-01-09 23:22 UTC by andreynering

2017-01-10 01:07 UTC, lunny commented
What's the pinned? And How to remove pinned?

2017-01-10 09:25 UTC, andreynering commented
I'm not good at UI, so suggestions and help are very welcome.

@lunny A pinned notification will always show. It will not be automatically marked as read when you open the issue, only when you click the "Mark as read" button.

2017-01-10 11:20 UTC, lunny commented
LGTM

2017-01-11 18:47 UTC, Bwko commented
LGTM

2017-01-12 02:33 UTC, ethantkoenig requested changes

2017-01-12 02:33 UTC, ethantkoenig commented on routers/user/notification.go
> +		c.Handle(500, "InvalidNotificationStatus", errors.New("Invalid notification status"))
Minor, but we should include the invalid status (i.e. `statusStr`) in the error message

2017-01-12 03:38 UTC, appleboy approved these changes

2017-01-12 04:27 UTC, merged

2017-01-15 15:57 UTC, gsantner commented
@andreynering 
Note: "Use relative URLs" did not fix the URL in the top navigation bar.
Points to `mydomain.xyz/notifications` instead of  `mydomain.xyz/gitea/notifications`  (with setted up /gitea/ as subdir)

2017-01-17 21:37 UTC, andreynering commented
@gsantner I couldn't find the link you cited. The topbar link should be OK:

https://github.com/go-gitea/gitea/pull/629/commits/993c7d65f559bd95af70e9c06175ef4470990204#diff-675f585d9cd6a202ba88a50dc67e52ffR85

2017-01-17 22:28 UTC, gsantner commented
@andreynering  Exactly at the line you pointed out, there is no "/gogs/" or "/gitea/" prefix.

![grafik](https://cloud.githubusercontent.com/assets/6735650/22042693/8a65044e-dd0c-11e6-8c9c-655d6961ee0b.png)

2017-01-17 23:16 UTC, andreynering commented
@gsantner Oh, you're right. Thanks for pointing out. It will be fixed as part of https://github.com/go-gitea/gitea/pull/660