Create third-party-tools.zh-cn.md
go-gitea/gitea pull request #6303
Opened 2019-03-11 13:13 UTC by maikebing

Translated the third-party-tools.zh-cn

2019-03-11 13:26 UTC, lunny approved these changes

2019-03-11 13:27 UTC, lunny commented
but the time is not right.

2019-03-12 19:06 UTC, jolheiser requested changes
Small nit

2019-03-12 19:06 UTC, jolheiser commented on docs/content/doc/advanced/third-party-tools.zh-cn.md
> +[[Gitea搭配Drone](https://docs.drone.io/installation/gitea/)
Duplicate opening bracket.

2019-03-13 09:49 UTC, maikebing commented on docs/content/doc/advanced/third-party-tools.zh-cn.md
> +[[Gitea搭配Drone](https://docs.drone.io/installation/gitea/)
OK！

2019-03-21 02:21 UTC, BetaCat0 commented on docs/content/doc/advanced/third-party-tools.zh-cn.md
> +title: "高级: 第三方工具"
“高级”换做“进阶”看起来似乎顺畅一些😀

2019-10-27 22:22 UTC, 6543 commented
i trust @lunny so ...:

2019-10-27 22:22 UTC, 6543 approved these changes

2019-11-08 22:32 UTC, merged