fix: remove org repository.
go-gitea/gitea pull request #633
Opened 2017-01-10 07:44 UTC by appleboy

Fix #614 

Don't check org repository count if deletes organization.

2017-01-10 09:12 UTC, lunny commented
Why this will resolve the issue?

2017-01-10 09:15 UTC, appleboy commented
https://github.com/go-gitea/gitea/blob/master/models/user.go#L940-L943

Must be return error or you will get the following error message.

> [...uters/org/setting.go:133 SettingsDelete()] [E] DeleteOrganization: deleteUser: user still has ownership of repositories [uid: 2]

2017-01-10 09:22 UTC, appleboy commented
Reproduce process in https://try.gitea.io/ :

1. Create organization
2. Create a report on the organization
3. Delete organization.

2017-01-10 09:34 UTC, tboerger commented on models/org.go
> +		// Note: don't wrapper error here.
For me it's obvious to not wrapping this error, so IMHO you can drop this comment.

2017-01-10 09:35 UTC, tboerger commented
But I still don't get how this will resolve the issue :)

2017-01-10 11:23 UTC, lunny commented
I think we need copy function `deleteUser` to `deleteOrg` and remove any no need codes. That's better.

2017-01-10 13:03 UTC, appleboy commented
@lunny I will do that.

2017-01-10 13:38 UTC, appleboy commented
@lunny Done. I copy function deleteUser to deleteOrg and remove any no need codes.

2017-01-10 13:40 UTC, appleboy commented
@tboerger You can see the following code:

https://github.com/go-gitea/gitea/blob/master/routers/org/setting.go#L128-L134

2017-01-10 13:53 UTC, lunny commented
So, maybe you can 
```Go
if IsErrUserOwnRepos(err) {
      return err
} else if err != nil {
      return fmt.Errorf("deleteUser: %v", err) 
}
```

2017-01-10 13:53 UTC, lunny commented
Otherwise LGTM

2017-01-10 13:53 UTC, lunny requested changes

2017-01-10 13:53 UTC, lunny commented on models/org.go
> +	// Check ownership of repository.
check u is an org?

2017-01-10 13:53 UTC, lunny commented on models/org.go
> +	return RewriteAllPublicKeys()
delete an org is no need to RewriteAllPublicKeys() ?

2017-01-10 14:17 UTC, appleboy commented on models/org.go
> +	return RewriteAllPublicKeys()
Good catch.

2017-01-10 14:17 UTC, appleboy commented on models/org.go
> +	return RewriteAllPublicKeys()
Done!.

2017-01-10 14:17 UTC, appleboy commented on models/org.go
> +	// Check ownership of repository.
Done.

2017-01-10 14:24 UTC, appleboy commented
@lunny Already done.

2017-01-10 18:36 UTC, Bwko commented on models/org.go
> +	return RewriteAllPublicKeys()
@lunny [Why did you add it then](https://github.com/appleboy/gitea/commit/ba134bd27abe099efcd748773c410b3aa78521fc#diff-97681c8a2932ea3c23325d3518374d98R239)? :stuck_out_tongue_winking_eye:

2017-01-11 00:53 UTC, lunny commented on models/org.go
> +	return RewriteAllPublicKeys()
😭 I don't know.

2017-01-11 00:53 UTC, lunny approved these changes

2017-01-11 06:57 UTC, Bwko commented
LGTM

2017-01-11 13:10 UTC, merged