docs: document setup with read-only config
go-gitea/gitea pull request #6348
Opened 2019-03-17 15:35 UTC by nodiscc

Ref. https://github.com/go-gitea/gitea/issues/5704

I don't know what the process to update doc translations is. I could update the french docs if needed.

2019-03-18 00:33 UTC, lunny approved these changes

2019-03-18 15:08 UTC, jolheiser requested changes

2019-03-18 15:08 UTC, jolheiser commented on docs/content/doc/installation/from-binary.en-us.md
> +If you don't want the web installer to be able to write the config file at all, it is also possible to make the config file read-only for the gitea user (owner/group `root:root`, mode `0660`), and se
`prealably` is not an English word.  
I think the intention is `prior` or `beforehand`, so I'd suggest re-wording to something like `All database configuration details must be preset in the config file...`

Thanks for the docs update! 😃

2019-03-21 00:49 UTC, axifive commented on docs/content/doc/installation/from-binary.en-us.md
> +
Please remove the extra line

2019-03-21 09:16 UTC, sapk commented
@nodiscc translation of docs is done directly by updating the file. The french doc is far outdated and a refresh could really be great. Don't hesitate to ping me in your PR if you do so I would gladly review it.

2019-03-21 19:26 UTC, nodiscc commented
@jolheiser @axifive Thank you, fixed following your review.

@sapk I will work on it, sure. 

Wouldn't it make sense for the docs to use a localization system like ~~gettext/transifex~~ (looks like https://github.com/go-gitea/gitea/tree/master/options/locale uses https://crowdin.com/) the one already in use by gitea? Else localized docs will keep lagging behind english ones.

Untranslated/out-of-date paragraphs would simply be displayed in english.

A minimalist alternative is a small banner on all localized pages `This documentation may be out of date, please refer to the [english documentation]($pagename.en-us.md) for latest information.`

2019-03-21 19:40 UTC, jolheiser requested changes
For consistency, should use Hugo `relref` function.

2019-03-21 19:40 UTC, jolheiser commented on docs/content/doc/installation/from-binary.en-us.md
> +If you don't want the web installer to be able to write the config file at all, it is also possible to make the config file read-only for the gitea user (owner/group `root:root`, mode `0660`), and se
Can you use the Hugo `relref` function here?
https://gohugo.io/content-management/cross-references/

`[command line documentation]({{< relref "doc/usage/command-line.en-us.md" >}})`

2019-04-01 13:56 UTC, lafriks approved these changes

2019-04-01 22:55 UTC, jolheiser commented
CI is failing.  
My bad, I gave you a wrong filename. It should be `command-line.md` and not `command-line.en-us.md`

2019-04-02 19:27 UTC, techknowlogick commented
@jolheiser updated.

2019-04-02 20:46 UTC, techknowlogick commented
Seems build is failing from untouched pages. I wonder if version of hugo in image we use has been updated.

2019-04-02 22:48 UTC, sapk commented
@techknowlogick I run the test on master and seems fine as the PR branch failed. It maybe related to the relative path.
I think it may need to use a relative `../usage/command-line.md` or an absolute `/doc/usage/command-line.md` relref but that strange since it seems to work on other parts. I will try to look into it.

2019-04-02 22:58 UTC, sapk requested changes
With those changes it should work.

2019-04-02 22:58 UTC, sapk commented on docs/content/doc/installation/from-binary.en-us.md
> +If you don't want the web installer to be able to write the config file at all, it is also possible to make the config file read-only for the gitea user (owner/group `root:root`, mode `0660`), and se
It seems that for relref you need to include the language. So this should be like this.
```suggestion
If you don't want the web installer to be able to write the config file at all, it is also possible to make the config file read-only for the gitea user (owner/group `root:root`, mode `0660`), and set `INSTALL_LOCK = true`. In that case all database configuration details must be set beforehand in the config file, as well as the `SECRET_KEY` and `INTERNAL_TOKEN` values. See the [command line documentation]({{< relref "doc/usage/command-line.en-us.md" >}}) for information on using `gitea generate secret INTERNAL_TOKEN`.
```
And rename the file `doc/usage/command-line.md` to `doc/usage/command-line.en-us.md`

2019-04-04 14:21 UTC, merged