Add pid flag to serve and don't set pid by default
go-gitea/gitea pull request #637
Opened 2017-01-10 19:42 UTC by Bwko

Solves the pid bug of #635

2017-01-11 01:02 UTC, appleboy approved these changes

2017-01-11 01:02 UTC, appleboy commented
LGTM

2017-01-11 01:07 UTC, appleboy requested changes

2017-01-11 01:07 UTC, appleboy commented on cmd/serve.go
>  		},
`git serve` don't need `pid` argument ?

2017-01-11 07:17 UTC, appleboy approved these changes

2017-01-13 10:03 UTC, tboerger commented on cmd/web.go
> +			Value: "/var/run/gitea.pid",
Why changing the current default?

2017-01-13 10:16 UTC, Bwko commented on cmd/web.go
> +			Value: "/var/run/gitea.pid",
`/var/run/` [Is the normal location for pid files](http://stackoverflow.com/a/5174433)

2017-01-14 02:12 UTC, lunny commented
LGTM

2017-01-14 02:15 UTC, merged