Reapply gogs hmac patch: https://github.com/gogs/gogs/commit/3609efe2…
go-gitea/gitea pull request #6430
Opened 2019-03-26 08:36 UTC by zobo

…e3d562547ae6497d67d56be7626727d0

Do not send "secret" field in webhook json but rather a header with HMAC.

Sending X-Gogs-Signature header and X-Hub-Signature with sha265= prefix.

Please check the following:

1. Make sure you are targeting the `master` branch, pull requests on release branches are only allowed for bug fixes.
2. Read contributing guidelines: https://github.com/go-gitea/gitea/blob/master/CONTRIBUTING.md
3. Describe what your pull request does and which issue you're targeting (if any)

**You MUST delete the content above including this line before posting, otherwise your pull request will be invalid.**

2019-03-26 11:29 UTC, lafriks commented
Please send PR to SDK first

2019-03-26 12:45 UTC, zobo commented
> Please send PR to SDK first

Thanks, will do.

2019-03-26 13:23 UTC, techknowlogick requested changes

2019-03-26 13:23 UTC, techknowlogick commented on models/webhook.go
> +		Header("X-Gogs-Signature", t.Signature).
Gogs signature is already set two lines down

2019-03-26 13:30 UTC, techknowlogick requested changes
This breaks Drone integration. Drone should get sent a patch to handle either the secret field OR validate the header, that way Drone is backwards compatible with older versions of Gitea too.

2019-03-27 14:51 UTC, zobo commented
> This breaks Drone integration. Drone should get sent a patch to handle either the secret field OR validate the header, that way Drone is backwards compatible with older versions of Gitea too.

Agreed, will work on that too.

2019-07-25 15:30 UTC, closed without merging