Fix permission bugs in team API
go-gitea/gitea pull request #647
Opened 2017-01-11 20:20 UTC by ethantkoenig

Some endpoints unnecessarily required the authenticated user to be an admin (basically everything removed from `api/v1/admin/org_team.go`).

Other endpoints didn't check that the authenticated user was an organization member.

2017-01-12 04:34 UTC, lunny requested changes

2017-01-12 04:34 UTC, lunny commented on routers/api/v1/org/team.go
> +	if !org.IsOrgMember(ctx.User.ID) {
This depends public or private status of org members. If public, then everyone could visit the members.

2017-01-12 04:34 UTC, lunny commented on routers/api/v1/org/team.go
> +	if !models.IsOrganizationMember(ctx.Org.Team.OrgID, ctx.User.ID) {
^

2017-01-12 16:51 UTC, ethantkoenig commented on routers/api/v1/org/team.go
> +	if !org.IsOrgMember(ctx.User.ID) {
I don't understand what you are saying; this is an endpoint for viewing an organization's teams, not for viewing the members of those teams.

Regardless, the corresponding endpoint in the Github API (`GET /orgs/:orgname/teams`) is only accessible to organization members, so I believe that is what we want to do here

2017-01-12 16:52 UTC, ethantkoenig commented on routers/api/v1/org/team.go
> +	if !models.IsOrganizationMember(ctx.Org.Team.OrgID, ctx.User.ID) {
The corresponding Github endpoint (`GET /teams/:id`) is only accessible to organization members (even if there are public members of the team), so I believe that is what we want to do here.

2017-01-14 02:22 UTC, lunny approved these changes

2017-01-14 02:22 UTC, lunny commented
LGTM

2017-01-19 23:19 UTC, Bwko commented
LGTM

2017-01-20 02:32 UTC, lunny commented
conflicted.

2017-01-20 03:39 UTC, appleboy approved these changes

2017-01-20 03:40 UTC, appleboy commented
LGTM

2017-01-20 03:41 UTC, ethantkoenig commented
Don't merge yet, there was something weird resolving the conflict

2017-01-20 05:16 UTC, merged

2017-06-22 09:41 UTC, theznx commented
Hello,
@ethantkoenig with this old commit you remove two use full endpoints : 
```
/admin/orgs/:orgname
/admin/teams/:teamid
```
Actually, in v1.1.2, there is no API endpoint to replace them.

If you didn't remove anything in the` /admin/users` endpoint, 
there was no permission bug with orgs and teams endpoints ? Or not?
_I'm just trying to understand ;)_

Maybe I should open a issue about that ?

Have a nice day

2017-06-22 13:16 UTC, ethantkoenig commented
@theznx The `POST /admin/orgs/:orgname/` endpoint was moved to `POST /orgs/:orgname`, and the `PATCH /admin/teams/:teamid` and `DELETE /admin/teams/:teamid` endpoints were moved to `PATCH /teams/:teamid` and `DELETE /teams/:teamid` respectively.

2017-06-23 09:18 UTC, theznx commented
@ethantkoenig Oh! Sorry for inconvenience.