fix upload attachments
go-gitea/gitea pull request #6481
Opened 2019-04-01 13:49 UTC by lunny

Should fix #4721

2019-04-01 13:52 UTC, lafriks approved these changes

2019-04-01 13:57 UTC, techknowlogick approved these changes

2019-04-01 14:00 UTC, lafriks requested changes
Please add new migration to call sync2 on attachmet table with new field

2019-04-01 14:32 UTC, lunny commented
@lafriks done.

2019-04-02 16:10 UTC, lafriks approved these changes

2019-04-02 19:25 UTC, merged

2019-04-07 01:56 UTC, chotaire commented
Tested as working in Gitea Version: 1.9.0+dev-61-g7ed65a98e. Thank you.