docs: update translation on notification page for zh-CN
go-gitea/gitea pull request #649
Opened 2017-01-12 01:55 UTC by xgitea

docs: update translation on notification page for zh-CN

2017-01-12 01:56 UTC, appleboy approved these changes

2017-01-12 01:57 UTC, appleboy commented
LGTM cc @lunny

2017-01-12 04:43 UTC, lunny commented
But you have to add English for `notification` as default.

2017-01-12 06:01 UTC, appleboy requested changes

2017-01-12 06:01 UTC, appleboy commented on options/locale/locale_zh-CN.ini
> +notifications = 通知
Missing English key.

2017-01-12 06:09 UTC, xgitea commented on options/locale/locale_zh-CN.ini
> +notifications = 通知
hi,@appleboy @lunny this english key exist.
[https://github.com/go-gitea/gitea/blob/master/options/locale/locale_en-US.ini](https://github.com/go-gitea/gitea/blob/master/options/locale/locale_en-US.ini)

page = Page
template = Template
language = Language
notifications = Notifications
create_new = Create...

2017-01-12 06:13 UTC, appleboy commented on options/locale/locale_zh-CN.ini
> +notifications = 通知
OK

2017-01-12 06:13 UTC, appleboy approved these changes

2017-01-12 06:50 UTC, tboerger commented
Hard to review or trust for me, that's up to @lunny and @appleboy

2017-01-13 09:26 UTC, lunny commented
LGTM

2017-01-13 09:31 UTC, lunny commented
Let L-G-T-M work

2017-01-13 09:31 UTC, merged