[WIP: don't merge] first batch of update
go-gitea/gitea pull request #65
Opened 2016-11-04 07:00 UTC by xinity

README update WIP.

leave the PR open until all updates are committed.
comments welcome of course :)

2016-11-04 08:28 UTC, tboerger requested changes

2016-11-04 08:28 UTC, tboerger commented on README.md
> +- Owners [@lunny](https://github.com/lunny), [@tboerger](https://github.com/tboerger) and [@bkcsoft](https://github.com/bkcsoft).
I would not mention that here, we can skip the maintainance of this part. You can see that anyway on the people page of the org.

2016-11-04 08:28 UTC, tboerger commented on README.md
> +1. **YOU MUST READ [Contributing Code](https://github.com/go-gitea/gitea/CONTRIBUTING.md) BEFORE STARTING TO WORK ON A PULL REQUEST**.
`You must read the [contributors guide]() before starting to work on a pull request`

2016-11-04 08:28 UTC, tboerger commented on README.md
> +## Current tip version: 0.9.99 (see [Releases](https://github.com/go-gitea/gitea/releases)
This should not be a headline, beside that this branch will be 1.0.0

2016-11-04 09:30 UTC, xinity commented on README.md
> +## Current tip version: 0.9.99 (see [Releases](https://github.com/go-gitea/gitea/releases)
agree @lunny 
i though at first to remove this line and simply link to the release page.

2016-11-04 20:55 UTC, xinity commented
I've taken care of changes requested, but github stills ask for them to be taken care of.
Did i miss something ?

2016-11-05 07:45 UTC, strk commented
I can see a "Dismiss review" link next to the "requested changes" record. I guess all maintainers do see that.
But given @tboerger requested the change I guess he's the one who should click that link, to confirm his request was addressed

2016-11-05 07:49 UTC, tboerger commented on README.md
> +4. If you think there are vulnerabilities in the project, please talk privately to **lunny@gitea.io**. Thanks!
security@gitea.io

2016-11-05 07:49 UTC, tboerger commented on README.md
> +**Current version: 1.0** (see [Releases](https://github.com/go-gitea/gitea/releases))
Please add a blank line here like on every headline

2016-11-05 07:49 UTC, tboerger commented on README.md
> +**Note: As Gitea is a [gogs](https://github.com/gogits/gogs) fork, tutorials and documentation related to gogs applies to Gitea too**
Gogs

2016-11-05 07:50 UTC, strk requested changes

2016-11-05 07:50 UTC, strk commented on README.md
> +**Current version: 1.0** (see [Releases](https://github.com/go-gitea/gitea/releases))
I think versions have 3 numbers, so would be 1.0.0 (but there's no such release made yet).
I agree on dropping this paragraph completely and just link to the releases page to figure out what the "current version" is.

2016-11-05 07:50 UTC, strk commented on README.md
> +1. **YOU MUST READ THE [Contributors Code](https://github.com/go-gitea/gitea/CONTRIBUTING.md) BEFORE STARTING TO WORK ON A PULL REQUEST**.
@tboerger asked to use "contributors guide" here, IIRC

2016-11-05 07:50 UTC, strk commented on README.md
> +4. If you think there are vulnerabilities in the project, please talk privately to **lunny@gitea.io**. Thanks!
@lunny wasn't there a wider address to contact owners/maintainers ?

2016-11-05 07:50 UTC, strk commented on README.md
>  - [Install from packages](https://gogs.io/docs/installation/install_from_packages.html)
I would drop the gogs.io links, those would not be releases of Gitea anyway.
Maybe also drop the count of ways to install, as that number is going to change a few times before becoming stable :)

2016-11-05 17:24 UTC, xinity commented on README.md
>  - [Install from packages](https://gogs.io/docs/installation/install_from_packages.html)
i agree but then there won't be any installation documentation links until we write one.
Doesn't matter ?

2016-11-08 13:13 UTC, strk commented on README.md
> +**Current version: 1.0.0** (see [Releases](https://github.com/go-gitea/gitea/releases))
How about drop the version number (will easily get outdated) and just point to the releases page ?

2016-11-08 13:13 UTC, strk commented on README.md
> +6. If your team/company is using Gogs and would like to put your logo on [our website](https://gitea.io), contact us by any means.
is using *Gitea ?

2016-11-08 13:14 UTC, strk commented on README.md
> +There are 2 ways to install Gitea:
Drop the count, those ways are going to change and we'll forget to update the count :)

2016-11-08 13:15 UTC, strk commented on README.md
> +- see [Maintainer page](https://github.com/orgs/go-gitea/people)
Capitalize See ?

2016-11-08 13:15 UTC, strk commented
Reviewed, feel free to ignore my review and have my LGTM :)

2016-11-08 13:15 UTC, xinity commented on README.md
> +- see [Maintainer page](https://github.com/orgs/go-gitea/people)
not sure about this one

2016-11-08 13:15 UTC, xinity commented on README.md
> +There are 2 ways to install Gitea:
done will push

2016-11-08 13:15 UTC, xinity commented on README.md
> +6. If your team/company is using Gogs and would like to put your logo on [our website](https://gitea.io), contact us by any means.
done will push

2016-11-08 13:16 UTC, xinity commented on README.md
> +**Current version: 1.0.0** (see [Releases](https://github.com/go-gitea/gitea/releases))
done will push

2016-11-08 14:18 UTC, tboerger requested changes

2016-11-08 14:18 UTC, tboerger commented on README.md
> -5. If you're interested in using APIs, we have experimental support with [documentation](https://godoc.org/github.com/go-gitea/go-sdk).
I would keep that and link to the godocs.

2016-11-08 14:18 UTC, tboerger commented on README.md
> +4. If you think there are vulnerabilities in the project, please talk privately to **security@gitea.io**. Thanks!
Numbering?

2016-11-08 14:18 UTC, tboerger commented on README.md
> +6. If your team/company is using Gitea and would like to put your logo on [our website](https://gitea.io), contact us by any means.
I would drop that for now.

2016-11-08 15:05 UTC, LefsFlarey commented on README.md
>  - See [contributors page](https://github.com/go-gitea/gitea/graphs/contributors) for full list of contributors.
Possibly `[Contributors]`, `[Maintainer]` and `[Translators]`?

2016-11-08 15:06 UTC, LefsFlarey commented on README.md
> +6. If your team/company is using Gitea and would like to put your logo on [our website](https://gitea.io), contact us by any means.
Agreed, we just became open source after all.

2016-11-08 15:30 UTC, strk approved these changes

2016-11-08 16:30 UTC, xinity commented on README.md
> +4. If you think there are vulnerabilities in the project, please talk privately to **security@gitea.io**. Thanks!
done will push

2016-11-08 16:30 UTC, xinity commented on README.md
> +6. If your team/company is using Gitea and would like to put your logo on [our website](https://gitea.io), contact us by any means.
done will push

2016-11-08 16:30 UTC, xinity commented on README.md
> -5. If you're interested in using APIs, we have experimental support with [documentation](https://godoc.org/github.com/go-gitea/go-sdk).
done will push

2016-11-08 20:40 UTC, strk commented on README.md
> +3. If you're interested in using APIs, we have experimental support with [documentation](https://godoc.org/github.com/go-gitea/go-sdk).
Gogs came back ?

2016-11-09 06:41 UTC, xinity commented
@strk are you sure?

2016-11-09 10:32 UTC, strk commented on README.md
> +3. If you're interested in using APIs, we have experimental support with [documentation](https://godoc.org/github.com/go-gitea/go-sdk).
sorry, I was wrong, all looks fine

2016-11-09 13:40 UTC, lunny commented
seems it's ready for merge. LGTM

2016-11-09 14:30 UTC, bkcsoft commented on README.md
> +**Note: As Gitea is a [Gogs](https://github.com/gogits/gogs) fork, tutorials and documentation related to gogs applies to Gitea too**
`fork of [Gogs]` sounds better no?

2016-11-09 15:29 UTC, strk commented
On Wed, Nov 09, 2016 at 06:30:13AM -0800, bkcsoft wrote:
> `fork of [Gogs]` sounds better no?

Nitpicking

2016-11-09 18:26 UTC, bkcsoft commented
@strk which is why I left it as a comment instead of `required change` :wink:

2016-11-10 08:44 UTC, strk commented
Do do we have your LGTM @bkcsoft ? So we can merge and move on

2016-11-10 09:21 UTC, lunny commented
@tboerger we need your approval changes.

2016-11-10 09:49 UTC, tboerger approved these changes

2016-11-10 10:52 UTC, merged