Update ru-RU translation
go-gitea/gitea pull request #657
Opened 2017-01-12 15:29 UTC by admik

Updated Russian translation.

2017-01-12 15:43 UTC, Bwko commented
@denji Could you take a look at this?

2017-01-12 18:57 UTC, tboerger commented
This review is totally up to the native speaker or people that can at least verify this is correct :)

2017-01-12 19:10 UTC, anton-dutov commented
I'm native russian speaker and i not sure for some translations
"issues" translated as "tasks" by myself that's wrong - "issue" most common mean nearest to "troubles" than to "task"
And
+unread=Не прочтенные
+read=Прочтенные
Should be
+read=Прочтённые
+unread=Не прочтённые
etc.

2017-01-12 19:20 UTC, anton-dutov commented on options/locale/locale_ru-RU.ini
> +no_unread=У вас нет не прочтенных уведомлений.
Use "Нет непрочитанных уведомлений"

2017-01-12 19:20 UTC, anton-dutov commented on options/locale/locale_ru-RU.ini
> +no_read=У вас нет прочтенных уведомлений.
Use "Нет прочитанных уведомлений"

2017-01-12 19:20 UTC, anton-dutov commented on options/locale/locale_ru-RU.ini
> +unread=Не прочтенные
Better is "Непрочитанные"

2017-01-12 19:20 UTC, anton-dutov commented on options/locale/locale_ru-RU.ini
> +read=Прочтенные
Same as previous "Прочитанные"

2017-01-13 02:42 UTC, admik commented
@anton-dutov @denji  I've changed translation according to your suggestions.

2017-01-15 13:04 UTC, kuntashov commented
@anton-dutov @admik 
"Проблема" is wrong translation for "issue"!
No one issue tracking software uses such translation. All of them translates "issue" into russian "Задача". It's common russian term for english "issue" for many popular issue tracking and project management software. 

Some examples:

* Mantis BT - https://github.com/mantisbt/mantisbt/blob/master/lang/strings_russian.txt#L1092
* Redmine - https://github.com/redmine/redmine/blob/master/config/locales/ru.yml#L530
* Bitbucket - https://www.transifex.com/atlassian/bitbucketorg/translate (need login to view translation)

All the more "issue" does not mean "troubles" in genereal. It means "an important question that is discussed and must be settled". See https://www.vocabulary.com/dictionary/issue

2017-01-16 03:58 UTC, admik commented
@anton-dutov @kuntashov  @denji @Bwko There is no exact translation for “issue” into Russian. Most tracking system translate it as a “task”, some as “request” (Atlassian Jira). I prefer translate it as a “task”, but I believe that translation as a “trouble” is ok. Should we vote?

2017-01-16 17:41 UTC, asosnoviy commented
А мне больше нравится "обсуждение".

2017-01-16 17:42 UTC, denji commented
@asosnoviy +1

2017-01-19 23:00 UTC, Lourens-Rich commented
Оставьте как "Задача" и не выпендривайтесь.

2017-01-22 01:40 UTC, anton-dutov commented
Предочитающие"задачи" побеждают, за сим извиняюсь внес смуту =)

2017-01-24 17:11 UTC, Bwko commented
@admik Any updates on this? Do you need to change anything or is it good to go?

2017-01-25 02:06 UTC, admik commented
@Bwko I've changed translation of 'issue' back to 'task', because this translation is being used in most tracking systems. Now it is good to go.

2017-01-25 15:42 UTC, Bwko commented
LGTM

2017-01-25 15:53 UTC, makhov requested changes

2017-01-25 15:53 UTC, makhov commented on options/locale/locale_ru-RU.ini
> +ssh_helper=<strong>Нужна помощь?</strong> Ознакомьтесь с нашим путеводителем по <a href="%s">созданию SSH-ключей</a> или посмотрите решения <a href="%s">частых задач, связанных с SSH</a>.
Может "ответы на частые вопросы по ssh"?
А то фраза не по-русски звучит

2017-01-25 18:05 UTC, svgorbunov commented on options/locale/locale_ru-RU.ini
> +ssh_helper=<strong>Нужна помощь?</strong> Ознакомьтесь с нашим путеводителем по <a href="%s">созданию SSH-ключей</a> или посмотрите решения <a href="%s">частых задач, связанных с SSH</a>.
Мне кажется, в данном случае, проще\лучше будет все-таки "решения частых проблем" (в английском варианте так и идет - problems). А вот "путеводителем", есть мнение, лучше заменить на "руководством" (как-то ближе к технической терминологии).

2017-01-25 18:16 UTC, makhov commented on options/locale/locale_ru-RU.ini
> +ssh_helper=<strong>Нужна помощь?</strong> Ознакомьтесь с нашим путеводителем по <a href="%s">созданию SSH-ключей</a> или посмотрите решения <a href="%s">частых задач, связанных с SSH</a>.
Согласен, так даже лучше

2017-01-25 19:36 UTC, svgorbunov commented on options/locale/locale_ru-RU.ini
> +ssh_helper=<strong>Нужна помощь?</strong> Ознакомьтесь с нашим путеводителем по <a href="%s">созданию SSH-ключей</a> или посмотрите решения <a href="%s">частых задач, связанных с SSH</a>.
@admik Что думаешь по этому поводу, как автор PR?

2017-01-26 03:06 UTC, admik commented on options/locale/locale_ru-RU.ini
> +ssh_helper=<strong>Нужна помощь?</strong> Ознакомьтесь с нашим путеводителем по <a href="%s">созданию SSH-ключей</a> или посмотрите решения <a href="%s">частых задач, связанных с SSH</a>.
@svgorbunov I support your suggestion. It sounds much better.

2017-01-26 04:53 UTC, makhov commented
LGTM

2017-01-26 05:15 UTC, denji approved these changes

2017-01-26 05:19 UTC, lunny commented
let L-G-T-M work

2017-01-26 05:20 UTC, lunny commented
LGTM

2017-01-26 05:20 UTC, merged

2017-01-26 05:29 UTC, admik commented on options/locale/locale_ru-RU.ini
> +repo_no_results=Не найдено ни одного репозитория.
@denji Your proposal to translate "There are no matched repositories found" as "Нет данных репозитория" in Russian means "There are no data in the repository". It is not correct.

2017-01-26 05:34 UTC, admik commented on options/locale/locale_ru-RU.ini
> +user_no_results=Не найдено ни одного пользователя.
@denji Your proposal to translate "There are no matched users found" as "Нет данных пользователя" in Russian means "There are no data about user". It is not correct.

2017-01-26 05:35 UTC, admik commented on options/locale/locale_ru-RU.ini
> +org_no_results=Не найдено ни одной организации.
@denji The same as previous.

2017-01-26 05:38 UTC, admik commented on options/locale/locale_ru-RU.ini
> +issues.label.filter_sort.reverse_alphabetically=С конца алфавита
@denji "Обратно по названию" doesn't sound good in Russian. "С конца алфавита" sounds much better.

2017-01-26 05:44 UTC, kuntashov commented on options/locale/locale_ru-RU.ini
> +issues.label.filter_sort.reverse_alphabetically=С конца алфавита
Usually "alphabetically" is translated as "По возрастанию", and "Reverse alphabetically" as "По убыванию".