Fix 6679
go-gitea/gitea pull request #6680
Opened 2019-04-19 19:09 UTC by ZerooCool

https://github.com/go-gitea/gitea/issues/6679

Please check the following:

1. Make sure you are targeting the `master` branch, pull requests on release branches are only allowed for bug fixes.
2. Read contributing guidelines: https://github.com/go-gitea/gitea/blob/master/CONTRIBUTING.md
3. Describe what your pull request does and which issue you're targeting (if any)

**You MUST delete the content above including this line before posting, otherwise your pull request will be invalid.**

2019-04-19 19:19 UTC, kolaente requested changes

2019-04-19 19:19 UTC, kolaente commented on public/less/_repository.less
> +                white-space: pre-wrap;
That's changing the code-diff view, not the readme.

2019-04-19 19:27 UTC, ZerooCool commented
Ok, that's not what's wanted then.
Here is the view of the HTML code (WordPress README displayed by default on our project) that I want to change because the code overflows.

An idea of CSS to modify?
In my online tests, the following CSS I modify: 
/vendor/plugins/semantic/semantic.min.css

2019-04-20 15:48 UTC, saitho commented
Adding the CSS property to \<pre> tags inside the `.non-diff-file-content .plain-text` class should be fine.
=> on file **public/less/_repository.less** add the following after line 327:
```
pre {
  white-space: pre-wrap;
}
```

Make sure to indent the lines properly. Rebuild the CSS file with `make generate-stylesheets` and commit that as well (as suggested by the DroneCI error message).

2019-04-22 17:55 UTC, lafriks commented
`make generate-stylesheets`

2019-04-22 20:00 UTC, ZerooCool commented
This pull request was not good.
Please, read the last message her : https://github.com/go-gitea/gitea/issues/6679

Please, apply the good request, i can't !

2019-05-02 11:41 UTC, zeripath commented
I'm going to close this as a duplicate

2019-05-02 11:41 UTC, closed without merging

2019-05-03 15:28 UTC, ZerooCool commented
Yes thank you.