only return head: null if source branch was deleted
go-gitea/gitea pull request #6705
Opened 2019-04-22 05:10 UTC by quantonganh

Fix #6613

2019-04-22 13:56 UTC, lunny commented
Could you add a test for it?

2019-04-24 04:10 UTC, lafriks commented on models/issue.go
> +func (issue *Issue) URL() string {
Why split to two functions if they return same data?

2019-05-02 07:15 UTC, quantonganh commented
> Could you add a test for it?

https://github.com/go-gitea/gitea/blob/a2f014f65da9b6a75dd644bd9c6f9be812294ce3/models/pull_test.go#L34

I understand that to add this test, we have to:
- create a PR
- merge that PR
- delete source branch
- get PR and assert that it is not nil

```
func TestPullRequest_APIFormat(t *testing.T) {
    assert.NoError(t, PrepareTestDatabase())
    pr := AssertExistsAndLoadBean(t, &PullRequest{ID: 1}).(*PullRequest)
    var (
        ctx  *context.context
        form auth.MergePullRequestForm
    )
    assert.NoError(t, pr.Merge(ctx.User, ctx.Repo.GitRepo, MergeStyle(form.Do), pr.GetDefaultMergeMessage()))

    gitRepo, err := git.OpenRepository(pr.HeadRepo.RepoPath())
    assert.NoError(t, err)
    assert.NoError(t, gitRepo.DeleteBranch(pr.HeadBranch, git.DeleteBranchOptions{
        Force: true,
    }))
    assert.Nil(t, pr.HeadRepo)
    assert.NotNil(t, pr.APIFormat())
}
```

I'm stuck at the 2nd step: I don't know how to pass the params to Merge(): https://github.com/go-gitea/gitea/blob/a2f014f65da9b6a75dd644bd9c6f9be812294ce3/models/pull.go#L400

2019-06-05 06:06 UTC, quantonganh commented
Build is passed: https://drone.gitea.io/go-gitea/gitea/9634

@lunny Could you please take a review?

2019-06-05 15:14 UTC, lunny requested changes

2019-06-05 23:46 UTC, quantonganh commented on models/pull.go
> +	if err != nil {
Fixed: https://github.com/go-gitea/gitea/pull/6705/commits/cf3f71408011f633316157336785118fdd97f8bf

2019-06-05 23:59 UTC, quantonganh commented on models/pull.go
> +	if err != nil {
How can I restart this (https://drone.gitea.io/go-gitea/gitea/9659/1/10) without pushing a new commit?

2019-06-06 00:35 UTC, lunny approved these changes

2019-07-08 02:38 UTC, lunny commented
conflicted

2019-07-08 07:28 UTC, quantonganh commented
> conflicted

@lunny rebased.

2019-07-08 07:32 UTC, lafriks approved these changes

2019-07-08 07:32 UTC, merged

2019-07-08 07:33 UTC, lafriks commented
Should we backport this to 1.9?

2019-07-08 07:41 UTC, lunny commented
I think we should.

2019-07-08 08:21 UTC, lafriks commented
@quantonganh please send backport for commit ff85a63 to `release/v1.9` branch

2019-07-08 08:54 UTC, quantonganh commented
@lafriks https://github.com/go-gitea/gitea/pull/7376