make sure to read interval value when making usee of redis or memcache
go-gitea/gitea pull request #6770
Opened 2019-04-26 18:45 UTC by adelowo

Fixes https://github.com/go-gitea/gitea/issues/6730

2019-04-26 18:46 UTC, lafriks approved these changes

2019-04-27 02:09 UTC, lunny approved these changes

2019-04-27 02:10 UTC, lunny requested changes
It seems Interval is for memory but TTL is for redis?

2019-04-27 17:03 UTC, adelowo commented
@lunny So a better solution is to tweak the UI based on what cache provider is being used? Show TTL if memcached or Redis but interval if memory ?

2019-05-06 12:44 UTC, closed without merging