[WIP] Oauth2 consumer
go-gitea/gitea pull request #679
Opened 2017-01-15 22:09 UTC by willemvd

This is a WIP PR for issue #26 
The OAuth2 login is configured as a new LoginSource, but with an alternative flow since this also involves callbacks from the OAuth2 provider.
For now the only implemented OAuth2 provider is GitHub
Outstanding points are the TODO's like fixing the login button to be only displayed when a OAuth2 provider is specified.

2017-01-16 05:47 UTC, bkcsoft requested changes
A couple of things. `macaron.Context` does _not_ belong in `models/`, if it's in there that's a bug that we should not encourage 🙂 

Otherwise AWESOME ‼️ 💯 🎉

2017-01-16 05:47 UTC, bkcsoft commented on models/login_source.go
> +		return true
You need to verify this...

2017-01-16 05:47 UTC, bkcsoft commented on models/login_source.go
> +	auths := make([]*LoginSource, 0, 6)
Can we maybe use `len(LoginNames)` instead of a hard-coded value?

2017-01-16 05:47 UTC, bkcsoft commented on models/login_source.go
> +		} else if !com.IsSliceContainsStr(strings.Split(cfg.AllowedDomains, ","), login[idx + 1:]) {
Is this done by `gofmt`? otherwise revert this line

2017-01-16 05:47 UTC, bkcsoft commented on models/login_source.go
> +func LoginViaOAuth2(cfg *OAuth2Config, ctx *macaron.Context, sess session.Store) {
`macaron.Context` does not belong in `models/`...

2017-01-16 05:47 UTC, bkcsoft commented on models/login_source.go
> +func ExternalUserLogin(user *User, login, password string, source *LoginSource, autoRegister bool, ctx *macaron.Context, sess session.Store) (*User, error) {
same as above...

2017-01-16 05:47 UTC, bkcsoft commented on models/login_source.go
> +func UserSignIn(username, password string, ctx *macaron.Context, sess session.Store) (*User, error) {
Same as above

2017-01-16 05:47 UTC, bkcsoft commented on models/login_source.go
> +	sources := make([]*LoginSource, 0, 5)
`len(...) - 1` ?

2017-01-16 05:47 UTC, bkcsoft commented on modules/auth/oauth2/oauth2.go
> +	gothic.Store = sessions.NewFilesystemStore(os.TempDir(), []byte(sessionUsersStoreKey))
Gitea has a defined session-dir and a temp-dir :)

2017-01-16 05:47 UTC, bkcsoft commented on modules/auth/oauth2/oauth2.go
> +	/*
Commented out code?

2017-01-16 05:47 UTC, bkcsoft commented on templates/admin/auth/edit.tmpl
> +                            <div class="inline required field">
Indentation

2017-01-16 05:47 UTC, bkcsoft commented on templates/admin/auth/new.tmpl
> +                                <label>{{.i18n.Tr "admin.auths.oauth2_provider"}}</label>
Indentation

2017-01-16 08:04 UTC, willemvd commented
macaron.Context is indeed a parameter that I added at some early stage, looked like the request was not properly filled in our own context when handling the callback. I will check if that is still needed

2017-01-16 08:08 UTC, willemvd commented on models/login_source.go
> +		return true
Not sure how to use this property correct if we are doing a call to the OAuth2 provider, suggestions?

2017-01-16 08:09 UTC, willemvd commented on models/login_source.go
> +		} else if !com.IsSliceContainsStr(strings.Split(cfg.AllowedDomains, ","), login[idx + 1:]) {
gofmt did this

2017-01-16 08:12 UTC, willemvd commented on models/login_source.go
> +	auths := make([]*LoginSource, 0, 6)
this can be any value, since it will look for all the configured login sources (and so depends on the environment how many this will be)

2017-01-16 08:13 UTC, willemvd commented on models/login_source.go
> +	sources := make([]*LoginSource, 0, 5)
This will lookup all activated loginSources, so this cannot be determined up front

2017-01-16 08:14 UTC, willemvd commented on modules/auth/oauth2/oauth2.go
> +	gothic.Store = sessions.NewFilesystemStore(os.TempDir(), []byte(sessionUsersStoreKey))
will use that!

2017-01-16 08:20 UTC, willemvd commented on modules/auth/oauth2/oauth2.go
> +	/*
yes part that I still need to have a look at. Need to check if it is required to do custom storing to determine valid requests in the callback

2017-01-16 08:36 UTC, willemvd commented on templates/admin/auth/edit.tmpl
> +                            <div class="inline required field">
will use proper tabs :)

2017-01-16 08:36 UTC, willemvd commented on templates/admin/auth/new.tmpl
> +                                <label>{{.i18n.Tr "admin.auths.oauth2_provider"}}</label>
will use proper tabs

2017-01-16 09:45 UTC, willemvd commented on modules/auth/oauth2/oauth2.go
> +	gothic.Store = sessions.NewFilesystemStore(os.TempDir(), []byte(sessionUsersStoreKey))
Think you mean : setting.SessionConfig.ProviderConfig = "data/sessions" ?
But this seems only valid when the session provider is file and not for instance memory

2017-01-16 10:00 UTC, willemvd commented
@bkcsoft  found out why I needed  the macaron.Context instead of our own context:
can't load package: import cycle not allowed
package code.gitea.io/gitea
	imports code.gitea.io/gitea/cmd
	imports code.gitea.io/gitea/models
	imports code.gitea.io/gitea/modules/auth/oauth2
	imports code.gitea.io/gitea/modules/context
	imports code.gitea.io/gitea/models

Maybe I can fix it by making a new oauth2 context in modules/auth/oauth2 and have the request and session in that as well? 
Only that seems not a very nice and clean way....

2017-01-16 10:57 UTC, willemvd commented
Changed the code a bit, so now the request, response and session are sent into the oauth2 module. This will prevent the import cycle and no macaron.Context is send around
Still maybe not the best way, but don't know a better way actually...

2017-01-17 08:49 UTC, willemvd commented
@bkcsoft resolved issues and did some cleanup of the code, could you please have another look (also on my comments on you previous review)

2017-01-20 10:11 UTC, bkcsoft approved these changes

2017-01-20 10:12 UTC, bkcsoft commented
@willemvd I'm still not exactly happy about passing around request/response either (essentially the same as passing around context...) what are they used? can't you just get what you need from them (variables) and pass that?

2017-01-20 11:36 UTC, willemvd commented
It seems not totally right, I agree.. Point is that the goth library requires the original request in it's method signatures and uses it for redirecting the client to the OAuth2 provider (http.Redirect : https://github.com/markbates/goth/blob/master/gothic/gothic.go#L55)
So seems no way to work around this, other then overriding the goth library or use some other implementation (or do it our self, if all other fails)

2017-01-21 02:38 UTC, bkcsoft reviewed
that should fix it

2017-01-21 02:38 UTC, bkcsoft commented on models/login_source.go
> +func LoginViaOAuth2(cfg *OAuth2Config, request *http.Request, response http.ResponseWriter) {
Move this to modules to fix one request/response-issue

2017-01-21 02:38 UTC, bkcsoft commented on models/login_source.go
> +func OAuth2UserLogin(provider string, request *http.Request, response http.ResponseWriter) (*User, error) {
Same with this

2017-01-21 02:38 UTC, bkcsoft commented on models/login_source.go
> +func OAuth2UserLoginCallback(provider string, request *http.Request, response http.ResponseWriter) (*User, string, error) {
And this

2017-01-23 10:34 UTC, willemvd commented
Changed it from WIP to final , please review 😄

2017-01-23 10:42 UTC, bkcsoft requested changes

2017-01-23 10:42 UTC, bkcsoft commented on modules/auth/oauth2/oauth2.go
> +	gothic.Store = sessions.NewFilesystemStore(os.TempDir(), []byte(sessionUsersStoreKey))
Please prefix the directory with `gitea-` :)

2017-01-23 11:31 UTC, willemvd commented on modules/auth/oauth2/oauth2.go
> +	gothic.Store = sessions.NewFilesystemStore(os.TempDir(), []byte(sessionUsersStoreKey))
changed it to use a new data/sessions/oauth2 folder based on the setting.WorkDir method

2017-01-23 11:55 UTC, bkcsoft requested changes
A few more things ^.^

2017-01-23 11:55 UTC, bkcsoft commented on modules/auth/oauth2/oauth2.go
> +	tmpDir := filepath.Join(dir, "data", "sessions", "oauth2")
We have `settings.AppDataPath` for this 🙂

2017-01-23 11:55 UTC, bkcsoft commented on modules/auth/oauth2/oauth2.go
> +	if err := os.MkdirAll(tmpDir, os.ModePerm); err != nil {
Should probably be `0700` 🙂

2017-01-23 11:55 UTC, bkcsoft commented on modules/auth/oauth2/oauth2.go
> +	tmpDir := filepath.Join(dir, "data", "sessions", "oauth2")
And since it's not really temporary (you never delete it) it should be called `sessionDir` 🙂

2017-01-23 12:41 UTC, bkcsoft approved these changes

2017-01-23 13:58 UTC, bkcsoft commented
I'd have to test this before saying L-G-T-M 🙂

2017-01-25 09:52 UTC, willemvd commented
oauth -> github search support

2017-01-25 11:38 UTC, strk commented on models/login_source.go
> +	sources := make([]*LoginSource, 0, 5)
You added a single LoginSource but you incremented this number by 2, either there's a bug in current code (short count) or in your patch (long count) ?

2017-01-25 12:20 UTC, willemvd commented on models/login_source.go
> +	sources := make([]*LoginSource, 0, 5)
see comment above, this can be any value because it is fetched from the database and so unpredictable, so what ever you want 😄

2017-01-26 15:31 UTC, lunny commented
Maybe add github logo on the button and change the button color to black is better? And the button could be in the center.

2017-01-27 06:36 UTC, lunny requested changes

2017-01-27 06:36 UTC, lunny commented on modules/auth/oauth2/oauth2.go
> +	sessionDir := filepath.Join(setting.AppDataPath, "sessions", "oauth2")
This is not corrected, setting.AppDataPath currently is empty. You maybe could make a function `InitOAuth2` and call it after `models.LoadConfigs()`

2017-01-27 07:21 UTC, willemvd commented on modules/auth/oauth2/oauth2.go
> +	sessionDir := filepath.Join(setting.AppDataPath, "sessions", "oauth2")
Was already creating such a function for registering the activated OAuth providers 😄 
Will add this as well

2017-01-27 08:32 UTC, willemvd commented
I'm not a styling guy , so if anyone could supply the code for fixing the Login button to some nice one! Better for everyone 😄

2017-01-30 13:17 UTC, lunny approved these changes

2017-01-30 13:17 UTC, lunny requested changes

2017-01-30 13:17 UTC, lunny commented on modules/auth/oauth2/oauth2.go
> +package oauth2
head comment missing.

2017-01-31 10:28 UTC, willemvd commented
added the possibility for creating a new account or connect to some existing account when logging in and you are not known in the system

2017-01-31 10:30 UTC, willemvd commented
outstanding point is the styling of the Login button and validating the OAuth flow on logging (now we always do an authentication request instead of checking if the user details can be fetched)

2017-01-31 11:43 UTC, strk commented
I don't understand the concept of a "primary" login source (User.LoginType).
Maybe we should ask @Unkwon for the design principle of that.

Right now, if I register via GitHub I don't see the GitHub link in the
`External Accounts` tab in user setting, while I do see it if I register
via name/password and only later sign-in via GitHub and associate to account.

As a user I don't see the need for this distinction. In both cases I have
both a username/password *and* an associated GitHub account. In one of the
cases I'm unable to *delete* the association with the GitHub account.

Personally, I'd *never* put the OAuth2 mechanism in the User.LoginType,
if that field should remain at all.

I do see a use for `User.LoginType` in the current code to avoid iterating
over *all* the enabled login types when the username is known, but this only
applies to the "iterateable" login types.

This confusion is what made me rewrite my `OpenID` PR so that it is not
considered a LoginSource at all.

2017-01-31 12:28 UTC, lunny approved these changes

2017-02-05 13:19 UTC, lunny commented
@willemvd conflicted.

2017-02-05 17:02 UTC, willemvd commented
@lunny merged, tested and pushed 😄

2017-02-06 16:53 UTC, strk commented
I'm sure this is due to myself having tested this branch before or something like that, but trying it out today I'm getting this at startup:
```
2017/02/06 17:52:11 [...itea/routers/init.go:54 GlobalInit()] [E] Failed to initialize ORM engine: migrate: do migrate: CreateIndexes RepoUnit: pq: relation "IDX_repo_unit_S" already exists
```

2017-02-06 16:54 UTC, strk commented
Forget the previous comment, it's also happening in the master branch

2017-02-07 12:14 UTC, lunny commented
LGTM

2017-02-07 19:44 UTC, strk commented
I just noticed another nasty consequence of having User.LoginType set to OAuth2: the User.IsLocal method would return `false` in that case, which would not allow updating a user's password. When registering a user with `OAuth2`, the form in this PR is still asking for a password, so a local password *does* exist, only cannot be used to be reset via `forgot_password`.

I keep thinking that User.LoginType should still only refer to the LoginSource to which the username/password pairs are to be sent, if anywhere (probably "LoginPlain" for these external-login-associated accounts, or "LoginNone" once it'll be supported)

2017-02-08 08:13 UTC, willemvd commented
Added the missed password reset and added an enhancement from goth where you can get the user if the OAuth2 AccessToken is still valid instead of re-authenticating (prevent flooding the OAuth2 provider with grant access requests)

2017-02-08 08:13 UTC, willemvd commented
Also fixed a merge conflict

2017-02-20 15:04 UTC, bkcsoft requested changes
I think a rebase/merge was messed up. The new migration _has_ to go at the end.

2017-02-20 15:04 UTC, bkcsoft commented on models/migrations/migrations.go
> +	NewMigration("create repo unit table and add units for all repos", addUnitsToTables),
This has to go at the end of the list

2017-02-20 15:04 UTC, bkcsoft commented on models/migrations/v16.go
>  package migrations
Why was the copyright-header removed?

2017-02-20 15:10 UTC, willemvd commented on models/migrations/migrations.go
> +	NewMigration("create repo unit table and add units for all repos", addUnitsToTables),
there was a new one added in master, mine  is after this one
https://github.com/go-gitea/gitea/pull/679/files#diff-7366023de6e87b891be868e3b8cf68e6R85-R86

2017-02-20 15:11 UTC, willemvd commented on models/migrations/v16.go
>  package migrations
it seems to be missing in master (https://github.com/go-gitea/gitea/blob/master/models/migrations/v16.go) and merged removed this, mine is v17.go

2017-02-20 15:12 UTC, willemvd commented
@bkcsoft please look at my comments, code from master is "broken" so that's why the merge looks messed up but isn't

2017-02-20 15:48 UTC, bkcsoft commented
When the changed are done you have my LGTM 😄

2017-02-20 20:25 UTC, willemvd commented
@bkcsoft what do you mean? 
migration.go change is because of a merge, mine is at the bottom of that file

For the missing copyright header in v16.go, I will create a new PR (since this is already wrong in the master)

Agree?

2017-02-20 20:59 UTC, willemvd commented on models/migrations/v16.go
>  package migrations
Created #992 to fix this missing header in master

2017-02-21 15:44 UTC, bkcsoft approved these changes

2017-02-21 15:44 UTC, bkcsoft commented
@willemvd That explains it 😄 Fix the conflicts and you have my LGTM

2017-02-21 15:54 UTC, strk commented
hint: rename v17 to v18 before rebasing again to master

2017-02-22 07:09 UTC, bkcsoft commented
LGTM :)

2017-02-22 07:09 UTC, bkcsoft commented
make L-G-T-M work!

2017-02-22 07:14 UTC, merged