Added ALWAYS_RENDER_RAW_FILES option to the repository section
go-gitea/gitea pull request #685
Opened 2017-01-17 00:03 UTC by geek1011

Used for serving raw files with the right content type, instead of text/plain. Fixes (#683). 

This option is disabled by default as it could be a potential security risk because the html in raw mode would render on the same domain as gitea.

2017-01-17 01:11 UTC, appleboy requested changes

2017-01-17 01:11 UTC, appleboy commented on modules/setting/setting.go
> +	Repository.AlwaysRenderRawFiles = sec.Key("ALWAYS_RENDER_RAW_FILES").MustBool()
You need also update `app.ini` configuration.

2017-01-17 01:11 UTC, appleboy commented on routers/repo/download.go
> +
remove empty line.

2017-01-17 01:11 UTC, appleboy commented on routers/repo/download.go
>  	} else if base.IsImageFile(buf) || base.IsPDFFile(buf) {
you should integrate this condition.

2017-01-17 01:11 UTC, geek1011 commented on modules/setting/setting.go
> +	Repository.AlwaysRenderRawFiles = sec.Key("ALWAYS_RENDER_RAW_FILES").MustBool()
Where?

2017-01-17 01:17 UTC, geek1011 commented on modules/setting/setting.go
> +	Repository.AlwaysRenderRawFiles = sec.Key("ALWAYS_RENDER_RAW_FILES").MustBool()
@appleboy Done.

2017-01-17 01:18 UTC, geek1011 commented on routers/repo/download.go
>  	} else if base.IsImageFile(buf) || base.IsPDFFile(buf) {
@appleboy I think it is more understandable this way.

2017-01-17 03:09 UTC, geek1011 commented on routers/repo/download.go
> +
Done

2017-01-17 09:15 UTC, tboerger commented
For reference: https://github.com/go-gitea/gitea/issues/683#issuecomment-273061000

2017-02-01 15:11 UTC, fwhcat commented
Hi. 👍 for merging this :)

2017-02-06 20:55 UTC, bkcsoft commented
I'm with @tboerger on this, this is a really bad idea...

2017-02-06 21:32 UTC, geek1011 commented
@bkcsoft Some people like me really need this option. Maybe it could be a build tag, and not offer prebuild builds with this option?

2017-02-12 15:11 UTC, bkcsoft commented
@geek1011 well, if one has to compile it themselfs anyway, it could just be a patch-set outside the project, because this is a _really_ bad idea and a huge security risk.

2017-02-15 15:40 UTC, lunny commented
So let's move it to 1.x.x

2017-03-02 12:18 UTC, geek1011 commented
Doesn't the csrf request token prevent this from being a security risk?

2017-03-12 17:20 UTC, strk commented
Sorry it's not clear to me what the security risk is. I understand is about running arbitrary javascript code embedded in HTML files put in a user repository. Now, cannot this be already done, only not by default ?

2017-03-12 17:22 UTC, geek1011 commented
@strk I think it would be submitting a form to delete a user or something like that.

2017-03-23 16:01 UTC, rugk commented
> I understand is about running arbitrary javascript code embedded in HTML files put in a user repository. 

Yes that's the issue…
CSRF tokens won't help since these are (as the name says) to protect from **cross-site** request forgeries, but here you are on the same site and an attacker can easily request a file with an CSRF token and extract it to use it in a request later.

Basically the attack is an XSS issue AFAIK. By opening a specific URL (with a file saved) untrusted code can be executed in the context of the Gitea installation. This can do anything…

So the fix is to disable it by default and if users need it add an option to enable parsing there. **Even in Gogs [it has been fixed already](https://github.com/gogits/gogs/issues/3608#issuecomment-287497363)**, so please don't get even slower than the original version. (Maybe also use the same config option for compatibility…)

> Now, cannot this be already done, only not by default ?

Uh, no? I don't understand what you mean…

2017-03-23 17:20 UTC, strk commented
On Thu, Mar 23, 2017 at 09:01:22AM -0700, rugk wrote:

> So the fix is to disable it by default and if users need it add an option to enable parsing there. **Even in Gogs [it has been fixed already](https://github.com/gogits/gogs/issues/3608#issuecomment-287497363)**, so please don't get even slower than the original version. (Maybe also use the same config option for compatibility…)

Thanks for the pointer, I think it is good to be compatible as much
as possible. And yes, I do feel your pain about becoming slower than
the original version... (want to help us ?)

> > Now, cannot this be already done, only not by default ?
> 
> Uh, no? I don't understand what you mean…

Passing the `render=1` parameter lets you receive HTML with arbitrary
javascript embedded, already.

2017-03-23 18:13 UTC, rugk commented
>  (want to help us ?)

You already have this PR, so what?
Or just use the code/patch from Gogs…

> Passing the `render=1` parameter lets you receive HTML with arbitrary javascript embedded, already.

Exactly that's the behaviour that needs to be disabled (by default!).

2017-03-23 18:17 UTC, rugk commented
Ah I saw that this PR does the opposite of fixing the render issue and should therefore be abolished.
Just as in https://github.com/gogits/gogs/commit/b3c4a39208331fd3798923bde01bf556b9e90c0d disable the rendering completely. Raw file means raw file meaning no parsing at all…

Of course you can allow users to use the `render=1` parameter **if** the admin enables a special option. Or just remove it entirely - if admins really want to use it they could configure their reverse-proxy server to add/change the Content-Type header or so.

2017-03-23 20:05 UTC, strk commented
On Thu, Mar 23, 2017 at 11:13:07AM -0700, rugk wrote:
> >  (want to help us ?)
> 
> You already have this PR, so what?

It's not just code that a project needs, but also organizational figures :)

2017-03-23 20:25 UTC, rugk commented
I'll keep posting issues and complaining about security-stuff, be sure… 😊

2017-03-23 21:11 UTC, tboerger commented
I still don't like this option. This is something that should be handled by a Webserver. If the option is there, we will have users that enable it because they simply don't understand the risk. And than somebody will complain about it.

2017-03-23 21:25 UTC, rugk commented
Then remove it entirely…

2017-03-23 22:42 UTC, strk commented
I think there are valid use cases where the security implication is not a concern: private hosting with only trusted users. For those cases, it's ok to let the admin allow rendering (even by default) the content. This is @geek1011 usecase, I think.

2017-03-24 17:50 UTC, rugk commented
Yes, but as @tboerger says, just use a reverse-proxy and add/modify then headers. There is no need to have this option in Gitea. (Users could not be aware of the risk ad enable it more or less accidentally or for just trying it out etc.)

On the other hand there is of course no need to discuss this. I am fine with an option, but please, please, finally **disable it by default**.

2017-03-24 18:10 UTC, tboerger commented
@lunny? @bkcsoft? I'm against this option.

2017-03-24 20:29 UTC, geek1011 commented
Thats a good idea. I might write some caddy middleware to fix the content type.

On Mar 23, 2017 5:11 PM, Thomas Boerger <notifications@github.com> wrote:

I still don't like this option. This is something that should be handled by a Webserver. If the option is there, we will have users that enable it because they simply don't understand the risk. And than somebody will complain about it.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://github.com/go-gitea/gitea/pull/685#issuecomment-288861322>, or mute the thread<https://github.com/notifications/unsubscribe-auth/ANQ-1YRCbqA8Ig_W2Csq153-tM6H73-nks5rouAVgaJpZM4LlGBh>.



On Mar 23, 2017 5:11 PM, Thomas Boerger <notifications@github.com> wrote:

I still don't like this option. This is something that should be handled by a Webserver. If the option is there, we will have users that enable it because they simply don't understand the risk. And than somebody will complain about it.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://github.com/go-gitea/gitea/pull/685#issuecomment-288861322>, or mute the thread<https://github.com/notifications/unsubscribe-auth/ANQ-1YRCbqA8Ig_W2Csq153-tM6H73-nks5rouAVgaJpZM4LlGBh>.



On Mar 23, 2017 5:11 PM, Thomas Boerger <notifications@github.com> wrote:

I still don't like this option. This is something that should be handled by a Webserver. If the option is there, we will have users that enable it because they simply don't understand the risk. And than somebody will complain about it.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://github.com/go-gitea/gitea/pull/685#issuecomment-288861322>, or mute the thread<https://github.com/notifications/unsubscribe-auth/ANQ-1YRCbqA8Ig_W2Csq153-tM6H73-nks5rouAVgaJpZM4LlGBh>.

2017-04-18 03:11 UTC, bkcsoft commented
General concensus seems to be that this is a bad idea all together, so I'm closing this 🙂 

Feel free to reopen if someone wants to discuss it further

2017-04-18 03:11 UTC, closed without merging

2017-04-18 10:08 UTC, rugk commented
So can we now implement/disable the rendering properly?

2017-04-18 20:00 UTC, strk commented
To recap: the reason raw rendering is considered unsafe is because
an attacker user could publish (via pushes to a repository)
malicious javascript code that would steal service credential from other
users watching the published code.

This means that administrators trusting all users to not be malicious
could really as well want to ALWAYS_RENDER_RAW_FILES, while those who
cannot trust users should NEVER_RENDER_RAW_FILES instead.

Rendering raw files from a _different_ domain would remove the danger
altogether.

So my proposal for a "proper" way to do things is:

 1. Allow setting a ROOT_URL_RAW variable to be used for serving
    raw files rendering. When set, raw files would be served only
    from the given domain, when unset, raw files would be disabled.

People trusting their users and NOT wanting to register another domain
could set ROOT_URL_RAW = %ROOT_URL, the others could leave that unset
(the default).

What do you think ?

2017-04-18 20:18 UTC, rugk commented
Great idea!

2017-04-19 07:14 UTC, bkcsoft commented
@strk I'm fine with that proposal 🙂

2017-04-19 07:19 UTC, strk commented
So anyone willing to implement ?
@geek1011 ?