gofmt
go-gitea/gitea pull request #690
Opened 2017-01-18 10:40 UTC by caiwp

gofmt  format code

2017-01-18 11:00 UTC, lunny commented
LGTM

2017-01-18 13:31 UTC, appleboy requested changes

2017-01-18 13:31 UTC, appleboy commented on models/access_test.go
>  	"github.com/stretchr/testify/assert"
move to the bottom of import section.

2017-01-20 02:42 UTC, caiwp commented on models/access_test.go
>  	"github.com/stretchr/testify/assert"
Just gofmt do

2017-01-20 03:27 UTC, appleboy requested changes

2017-01-20 03:27 UTC, appleboy commented on models/access_test.go
>  	"github.com/stretchr/testify/assert"
You must be following import path rule like https://github.com/go-gitea/gitea/blob/master/main.go#L9-L16

2017-01-21 03:50 UTC, bkcsoft requested changes
few things that ticks my OCD 😛

2017-01-21 03:50 UTC, bkcsoft commented on models/setup_for_test.go
> +	"gopkg.in/testfixtures.v2"
this change is wrong (no matter what goimports says 😆 )

2017-01-21 03:50 UTC, bkcsoft commented on modules/base/tool_test.go
>  	"github.com/Unknwon/i18n"
newline between `code.`- and `github.`-lines :)

2017-01-21 03:50 UTC, bkcsoft commented on modules/lfs/server.go
> -	"github.com/dgrijalva/jwt-go"
same as above, newline between "local" and "external" packages :)

2017-01-21 03:50 UTC, bkcsoft commented on modules/templates/helper.go
> +
no newline

2017-01-21 03:50 UTC, bkcsoft commented on modules/mailer/mailer.go
> +	"github.com/jaytaylor/html2text"
invalid change

2017-01-21 03:52 UTC, bkcsoft commented
Maybe we should document these guidelines?
```go
import (
  "encoding/json"
  "fmt"

  "code.gitea.io/gitea/models"

  "github.com/foo/bar"
)
```

So Stdlib, newline, local packages, newline, external packages. All in alphabetical order of course ^.^

2017-01-25 15:30 UTC, appleboy commented
@caiwp Any updates on this?

2017-01-25 15:37 UTC, lunny commented
Please rebase.

2017-02-05 01:39 UTC, lunny commented
conflicted

2017-02-10 14:45 UTC, tboerger commented on routers/api/v1/utils/hook.go
> +	"encoding/json"
This should be even above the api import.

2017-02-10 14:46 UTC, tboerger commented
Multiple conflicts, any update?

2017-02-13 01:10 UTC, caiwp commented
These submitted only problems involving formatted, as long as you are formatted before saving.

2017-02-13 01:10 UTC, closed without merging