Don't regenerate jwt secret
go-gitea/gitea pull request #6928
Opened 2019-05-13 10:26 UTC by sanjid133

Please check the following:

1. Make sure you are targeting the `master` branch, pull requests on release branches are only allowed for bug fixes.
2. Read contributing guidelines: https://github.com/go-gitea/gitea/blob/master/CONTRIBUTING.md
3. Describe what your pull request does and which issue you're targeting (if any)

**You MUST delete the content above including this line before posting, otherwise your pull request will be invalid.**

2019-05-13 10:41 UTC, zeripath approved these changes

2019-05-13 11:41 UTC, adelowo approved these changes

2019-05-13 12:39 UTC, zeripath commented on modules/setting/setting.go
> +		if len(OAuth2.JWTSecretBase64) == 0 && (err != nil || n != 32) {
```suggestion
		if err != nil || n != 32 {
```

We still want this to be regenerated if JWTSecretBase64 is not valid

2019-05-13 12:39 UTC, zeripath requested changes
See above

2019-05-13 12:52 UTC, zeripath commented
Hmm actually looking again is this actually even necessary at all?

It looks like this should work by default.

2019-05-13 14:39 UTC, lunny requested changes

2019-05-13 14:39 UTC, lunny commented on modules/setting/setting.go
> +		OAuth2.JWTSecretBase64 = Cfg.Section("oauth2").Key("JWT_SECRET").String()
This has been read from line 725.

2019-05-13 15:18 UTC, zeripath commented
Yeah @lunny I agree, I approved too quickly. I think this pr might actually be unnecessary. The change to the check line is wrong and introduced a security bug. The reloading of the secret seems also unnecessary.

@sanjid133 what was the reason behind this pr?

2019-05-14 03:48 UTC, sanjid133 commented
@zeripath If I mount the app.ini file as a secret in only read mode regenerating this token is creating an error.

2019-05-14 04:44 UTC, lunny commented
@sanjid133 that's another issue. I will close this PR since it will not resolve anything.

2019-05-14 04:44 UTC, closed without merging