Improve handling of non-square avatars
go-gitea/gitea pull request #7025
Opened 2019-05-23 21:16 UTC by rfwatson

Crop avatars before resizing them. This prevents a user's first experience of Gitea being a nasty aspect ratio on their avatar.

## Before

![Screenshot from 2019-05-23 23-03-36](https://user-images.githubusercontent.com/12555/58287098-7c9eaa80-7db0-11e9-91aa-43c6a87842f4.png)

## After

![Screenshot from 2019-05-23 23-04-58](https://user-images.githubusercontent.com/12555/58287105-7f010480-7db0-11e9-9df2-c6c72a28dce2.png)

## Discussion points

* As [mentioned](https://github.com/go-gitea/gitea/issues/1268#issuecomment-348737761) in #1268 it might be nice to improve the UX flow too, so users have more control over the cropping. I haven't attempted this but I feel like it's worth implementing a simple backend fix first. 

## Questions

* I'm not sure that I've included the `github.com/oliamb/cutter` dependency properly - maybe it should go in `vendor/` instead of a module? Go newbie here advice appreciated :see_no_evil:

2019-05-23 21:26 UTC, zeripath commented
You need to run make vendor and commit

2019-05-23 21:34 UTC, rfwatson commented
Committed the change to modules.txt but the build still seems to be failing

2019-05-24 02:21 UTC, zeripath commented
You haven't run make vendor and committed

2019-05-24 11:04 UTC, lafriks approved these changes

2019-05-24 12:15 UTC, zeripath approved these changes

2019-05-24 13:49 UTC, lunny requested changes

2019-05-24 13:49 UTC, lunny commented on modules/avatar/avatar.go
> +	"code.gitea.io/gitea/modules/setting"
import sequence.

2019-05-24 13:49 UTC, lunny commented on modules/avatar/avatar_test.go
> +	"code.gitea.io/gitea/modules/setting"
As above.

2019-05-25 09:43 UTC, lunny approved these changes

2019-05-25 11:46 UTC, merged