add API endpoints to update/delete protected branch
go-gitea/gitea pull request #7093
Opened 2019-05-31 10:47 UTC by quantonganh

Fix https://github.com/go-gitea/gitea/issues/2922

2019-05-31 20:38 UTC, techknowlogick commented
Thanks for PR :) The CI is currently failing due to needing a rebase on the latest commit of master.

I think additional routes for the API are needing for these methods, as well as swagger definitions.

2019-06-11 06:43 UTC, quantonganh commented
> I think additional routes for the API are needing for these methods, as well as swagger definitions.

Routes and swagger definitions have been added.
@techknowlogick Could you please take a review?

2019-08-27 09:25 UTC, davidsvantesson requested changes

2019-08-27 09:25 UTC, davidsvantesson commented on routers/api/v1/repo/branch.go
>  		}
else (other errors?)

2019-08-27 09:25 UTC, davidsvantesson commented on routers/api/v1/repo/branch.go
> +		}
else (other errors?)

2019-08-27 09:25 UTC, davidsvantesson commented on routers/api/v1/repo/branch.go
> +		}
else (other errors?)

2019-08-27 21:28 UTC, davidsvantesson commented on routers/api/v1/repo/branch.go
>  		}
Also, xorm will not give an error if there is no row in the database, but an empty object. So you have to check protectBranch against nil.

2019-08-27 22:14 UTC, davidsvantesson commented on templates/swagger/v1_json.tmpl
> +    "ProtectBranchForm": {
It's a bit problematic to reuse the same structure for API from documentation point of view. How do I know the format of XWhiteListTeams and XWhiteListUsers? Preferably they should be arrays. At least they should change name to XWhiteListTeamIDs and XWhiteListUserIDs

2019-09-27 14:04 UTC, lunny commented on modules/structs/repo_branch.go
>  }
I think we need more details about the branch protection settings but not only a `bool`.

2019-12-12 06:54 UTC, davidsvantesson commented
I think this one can be moved to 1.12, no chance for this release. I hope either this one or my new PR can get into next release.

2020-02-13 10:27 UTC, davidsvantesson commented
This one can be closed.

2020-02-13 10:33 UTC, closed without merging