Reject duplicate access token name
go-gitea/gitea pull request #7135
Opened 2019-06-05 18:52 UTC by adelowo

I have run into cases where I have multiple tokens with the same name and 
it becomes hard to find out which one is no longer being used, so it can be deleted

2019-06-06 00:40 UTC, lunny requested changes

2019-06-06 00:40 UTC, lunny commented on models/token.go
> +	exists, _ := x.Get(token)
I think 
```go
x.Table("token").Where("name=?", tokenName).Exist()
```
is better.

2019-10-29 22:34 UTC, 6543 commented
@adelowo whats the state?

2019-10-30 10:13 UTC, adelowo commented
Yikes. Will try to prepare this for 1.11

2020-04-06 17:11 UTC, 6543 commented
@adelowo  Can I take this too?

2020-04-06 17:11 UTC, adelowo commented
Yes.

2020-04-06 17:18 UTC, 6543 commented
new PR can be found here: https://github.com/go-gitea/gitea/pull/10994

2020-04-06 17:25 UTC, closed without merging

2020-04-13 19:21 UTC, 6543 commented
@adelowo merged: #10994 :tada:

2020-04-13 19:22 UTC, adelowo commented
Thanks.