Adjusts minimum Go version in documentation to 1.11
go-gitea/gitea pull request #7148
Opened 2019-06-06 20:39 UTC by saitho

Gitea uses the "-mod" option in go run which is introduced with Go v1.11.
Documentation states 1.9 as minimum version. Therefore we should update documentations. :)

2019-06-06 20:41 UTC, techknowlogick requested changes
Minimum go version supported is 1.10, as we need to ensure that `go build` works for that version. This will change when Gitea v1.9.0 is released when we can move to go 1.11

2019-06-06 21:26 UTC, saitho commented
I would be fine merging this with the release of 1.9.

2019-06-06 21:29 UTC, techknowlogick commented
> I would be fine merging this with the release of 1.9.

As we will be releasing Gitea 1.9 soon, there is a freeze and as such a change such as this will have to wait until after 1.9 is released.

> Just checked out master and noticed that I need Go v1.11 in order to compile it.

You shouldn't, and in fact each commit to master is checked that it can compile with Go v1.10

2019-06-06 21:41 UTC, saitho commented
Hm. Building with Go 1.10 fails saying that the option -mod is not available for "go run", pointing to this file: https://github.com/go-gitea/gitea/blob/master/modules/options/options.go on line 7.
Might also be a misconfiguration on my end, as I installed Go on a freshly installed Ubuntu. ^^

2019-06-06 21:44 UTC, techknowlogick commented
For reference here is the command you can run: https://github.com/go-gitea/gitea/blob/master/.drone.yml#L65 the makefile may not support 1.10, but running with just go build does

2019-06-07 00:43 UTC, xxxtonixxx commented
> Hm. Building with Go 1.10 fails saying that the option -mod is not available for "go run", pointing to this file: [/modules/options/options.go@`master`](https://github.com/go-gitea/gitea/blob/master/modules/options/options.go) [](/go-gitea/gitea/blob/HEAD@{2019-06-06T21:41:16Z}/modules/options/options.go) on line 7.
> Might also be a misconfiguration on my end, as I installed Go on a freshly installed Ubuntu. ^^

Fail happens when you build with bindata using makefile (`TAGS="bindata" make generate`). I think this should be remarked

2019-06-07 06:57 UTC, sapk commented
It is only the makefile that break compat for The build command. We can maybe introduce build-compat command. We check compat with 1.10 on the CI. The command `make release` or `make release-linux` (or the os of your choice) should still work.

2019-06-07 07:01 UTC, sapk commented
Looking at https://github.com/go-gitea/gitea/issues/7149#issuecomment-499779594 the command `make generate is maybe also broken by the need of Go1.11

2019-06-08 07:33 UTC, lunny commented
Maybe because I introduced the vfsgen and add `-mod=vendor` on `go generate`.

2019-06-08 07:55 UTC, lunny commented
I think we can fix this by remove `-mod=vendor` in `go generate` on release v1.9 and added it back on v1.10 :)

2019-07-08 00:45 UTC, techknowlogick commented
This has been accomplished in another PR. Thanks for PR :)

2019-07-08 00:45 UTC, closed without merging