Check for manual merging of a pull request
go-gitea/gitea pull request #719
Opened 2017-01-22 14:05 UTC by Bwko

When an **open** pull request got manually merged mark the pull request as merged
Fixes #283

2017-01-25 14:20 UTC, lunny requested changes

2017-01-25 16:48 UTC, Bwko commented
@lunny done :)

2017-01-26 03:08 UTC, lunny approved these changes

2017-01-26 04:48 UTC, lunny commented
LGTM

2017-02-05 12:49 UTC, appleboy approved these changes

2017-02-05 12:49 UTC, appleboy commented
LGTM

2017-02-05 13:07 UTC, merged