Dark theme markdown fixes
go-gitea/gitea pull request #7260
Opened 2019-06-20 03:40 UTC by Cherrg

* fixes tables in dark theme
* fix simpleMDE preview in dark theme

## Images

|                                                | OLD          | NEW        |
|:------------------------------------- |:-------------:|:-------------:|
| Tables in Markdown               | ![grafik](https://user-images.githubusercontent.com/24939127/59816583-f462e500-931c-11e9-9920-c4c5981d8a1f.png)  | ![grafik](https://user-images.githubusercontent.com/24939127/59816603-06dd1e80-931d-11e9-851b-0421ca46b9c8.png)  |
| Markdown editor wiki + repo  | ![grafik](https://user-images.githubusercontent.com/24939127/59816831-dba6ff00-931d-11e9-8447-0d9c27642005.png)  | ![grafik](https://user-images.githubusercontent.com/24939127/59816781-b31f0500-931d-11e9-9cbd-bcf70d851a5c.png) |

Signed-off-by: Michael Gnehr <michael@gnehr.de>

2019-06-20 08:49 UTC, silverwind commented
The scrollbar styling is Firefox-only as of now. Maybe we want to add site-wide dark scrollbars to the dark theme?

See [here](https://github.com/StylishThemes/Overlay-Scrollbars/blob/master/global-overlay-scrollbars.user.css) for cross-browser scrollbar styling.

2019-06-20 08:49 UTC, silverwind commented
The scrollbar styling is Firefox-only as of now. Maybe we want to add site-wide dark scrollbars to the dark theme?

See [here](https://github.com/StylishThemes/Overlay-Scrollbars/blob/master/global-overlay-scrollbars.user.css) for cross-browser scrollbar styling.

2019-06-20 09:08 UTC, lafriks commented
@silverwind that should probably be done in other PR

2019-06-20 09:47 UTC, lafriks commented
@silverwind that should probably be done in other PR

2019-06-20 10:04 UTC, silverwind commented
Then I suggest removing this non-portable scrollbar style here.

2019-06-20 10:31 UTC, lafriks requested changes
This should be globally added to all scrollbars and made portable but I would better see this done in other PR

2019-06-20 10:31 UTC, lafriks commented on public/less/themes/arc-green.less
> +        scrollbar-color: #2a2a2a white;
```suggestion
```

2019-06-20 10:31 UTC, lafriks commented on public/css/theme-arc-green.css
> +.repository.file.editor.edit .editor-preview,.repository.wiki.new .CodeMirror .editor-preview{background:#353945;scrollbar-color:#2a2a2a #fff}
```suggestion
.repository.file.editor.edit .editor-preview,.repository.wiki.new .CodeMirror .editor-preview{background:#353945}
```

2019-06-20 12:51 UTC, Cherrg commented
I will remove the FF scroolbar line there. 
I had added FF Scrollbar, as Chrome already got an colored scrollbar by semantic.css. FF was missing. (And Scrollbar was last thing with wrong color.)
You right lets do this globally on different PR.

2019-06-20 12:59 UTC, Cherrg commented on public/css/theme-arc-green.css
> +.repository.file.editor.edit .editor-preview,.repository.wiki.new .CodeMirror .editor-preview{background:#353945;scrollbar-color:#2a2a2a #fff}
Done in other Commit

2019-06-20 14:35 UTC, Cherrg commented
done, even created seperate PR for dark theme scrollbars: #7269

2019-06-21 08:20 UTC, lafriks approved these changes

2019-06-21 08:23 UTC, sapk approved these changes

2019-06-21 11:15 UTC, Cherrg commented
Please restart drone build. Ty

2019-06-21 13:27 UTC, merged