WIP: Experiment to convert macaron to chi
go-gitea/gitea pull request #7420
Opened 2019-07-11 01:26 UTC by lunny

This is not work yet.

2020-05-02 08:52 UTC, lunny commented
related with #7403

2020-11-12 22:37 UTC, 6543 approved these changes
its gitea_v1.14 time ... lests start with it

2020-11-12 23:17 UTC, lafriks approved these changes

2020-11-12 23:22 UTC, lafriks requested changes

2020-11-12 23:22 UTC, lafriks commented on go.mod
> +	github.com/go-chi/chi v4.1.2+incompatible
Just saw that go mod based go-chi v1.5.0 has just been released, we should use it
```suggestion
	github.com/go-chi/chi v1.5.0
```

2020-11-13 00:36 UTC, lunny commented
@lafriks done.

2020-11-13 01:33 UTC, 6543 approved these changes

2020-11-13 04:09 UTC, 6543 commented
@lunny the chi router do not pass things to our logger :/

2020-11-13 12:49 UTC, lafriks approved these changes

2020-11-13 12:49 UTC, lafriks commented
:rocket:

2020-11-13 12:50 UTC, lafriks commented
LGTM does not seems to like me :/

2020-11-13 12:51 UTC, merged