WIP: Refactor process package and introduce ProcessManager{} with tests
go-gitea/gitea pull request #75
Opened 2016-11-04 23:56 UTC by metalmatze

This is still WIP and other files need to be updated.
Some funcs that use this need get a ProcessManager instance passed.

2016-11-05 08:19 UTC, tboerger commented on modules/process/manager.go
> +		timeout = DefaultTimeout
Just set the default within the exec function?

2016-11-06 00:55 UTC, metalmatze commented
This is ready to merge.

2016-11-06 07:32 UTC, lunny commented on modules/process/manager.go
> +	pid := pm.counter + 1
Should this line put after the lock line?

2016-11-07 08:48 UTC, tboerger commented
@metalmatze travis is failing.

2016-11-07 20:04 UTC, metalmatze commented
Travis fails because there's no openssh-client on travis. I think I'll leave this for now, until we're drone only. Then this will pass.

2016-11-15 07:35 UTC, strk commented
@metalmatze did you try adding `openssh-client` to the `apt-get install` line in `before_install` of .travis.yml ?

2016-11-15 08:47 UTC, lunny commented
This PR is waiting until drone is ready. @tboerger

2016-11-15 09:06 UTC, strk commented
Drone PR is #96

2016-11-25 14:21 UTC, lunny commented
what's the block?

2016-11-25 14:26 UTC, tboerger commented
I have dropped the blocked panel

2016-11-25 14:29 UTC, lunny commented
So this only needed to rebase

2016-11-25 14:30 UTC, tboerger commented
Yes, and @metalmatze said that he will finish it this weekend

2016-12-03 09:32 UTC, tboerger commented
Do we want to move it to 1.1 @metalmatze?

2016-12-05 08:00 UTC, lunny commented
I just move this to 1.1 and if @metalmatze back and 1.0 is not released yet, please move it back.

2016-12-25 09:46 UTC, lunny commented
Please rebase and we can review continue.

2016-12-29 10:30 UTC, tboerger commented
@metalmatze can you finish that and resolve the conflicts?

2016-12-29 12:55 UTC, metalmatze commented
Yes I want to, but currently at 33C3 there's to less time. I'll try to rebase and finish on the weekend.

2016-12-31 17:08 UTC, metalmatze commented
Ok. Instead of rebasing I've now copied over my changes in `modules/process` and simply refactored all its use cases.

2017-01-16 12:02 UTC, lunny commented
Is this ready for review again?

2017-01-16 12:03 UTC, metalmatze commented
I guess. I fixed all the errors and rebased to the current `master`.

2017-01-16 12:28 UTC, lunny requested changes

2017-01-16 12:28 UTC, lunny commented on modules/process/manager.go
> +	pid := pm.counter + 1
^

2017-01-16 12:28 UTC, lunny commented
otherwise LGTM

2017-01-16 12:40 UTC, metalmatze commented on modules/process/manager.go
> +	pid := pm.counter + 1
Not necessarily. But probably better.

2017-01-16 13:43 UTC, lunny approved these changes

2017-01-16 21:56 UTC, tboerger commented
LGTM

2017-01-17 05:58 UTC, merged