Update DCO
go-gitea/gitea pull request #7679
Opened 2019-07-31 04:25 UTC by hoseinipeyrov

Please check the following:

1. Make sure you are targeting the `master` branch, pull requests on release branches are only allowed for bug fixes.
2. Read contributing guidelines: https://github.com/go-gitea/gitea/blob/master/CONTRIBUTING.md
3. Describe what your pull request does and which issue you're targeting (if any)

**You MUST delete the content above including this line before posting, otherwise your pull request will be invalid.**

2019-07-31 04:25 UTC, techknowlogick commented on DCO
> +Copyright (C) 2004, 20019 The Linux Foundation and its contributors.
```suggestion
Copyright (C) 2004, 2019 The Linux Foundation and its contributors.
```

2019-07-31 04:26 UTC, techknowlogick requested changes
I'm unsure of this change, because the official document at https://developercertificate.org/ still has 2006

2019-07-31 05:22 UTC, gary-kim requested changes

2019-07-31 05:22 UTC, gary-kim commented on DCO
> +Copyright (C) 2004, 20019 The Linux Foundation and its contributors.
This should still stay as 2006. Copyright years only get updated if the material itself is updated.

2019-08-01 18:04 UTC, techknowlogick commented
Thank you for your PR. I will be closing this as per above comments.

2019-08-01 18:04 UTC, closed without merging