Rewrite existing repo units if setting is not included in api body
go-gitea/gitea pull request #7763
Opened 2019-08-05 20:43 UTC by davidsvantesson

Fix for #7267 
In the API: PATCH ​/repos​/{owner}​/{repo}, if any advanced repo setting is not included in the body, corresponding repo_unit is rewritten (if existing) in order to retain the setting.

Signed-off-by: David Svantesson <davidsvantesson@gmail.com>

2019-08-05 21:01 UTC, lafriks requested changes

2019-08-05 21:01 UTC, lafriks commented on routers/api/v1/repo/repo.go
> +	} else {
```suggestion
	} else if *opts.HasIssues {
```

2019-08-05 21:01 UTC, lafriks commented on routers/api/v1/repo/repo.go
> +	} else {
same here

2019-08-05 21:01 UTC, lafriks commented on routers/api/v1/repo/repo.go
> +	} else {
same here

2019-08-05 21:29 UTC, davidsvantesson commented on routers/api/v1/repo/repo.go
> +	} else {
Fixed

2019-08-05 21:29 UTC, davidsvantesson commented on routers/api/v1/repo/repo.go
> +	} else {
Fixed

2019-08-05 21:29 UTC, davidsvantesson commented on routers/api/v1/repo/repo.go
> +	} else {
Fixed

2019-08-05 21:35 UTC, lafriks approved these changes

2019-08-06 01:15 UTC, lunny approved these changes

2019-08-10 07:38 UTC, davidsvantesson commented
Ready to be merged?

2019-08-10 09:32 UTC, merged

2019-08-10 09:33 UTC, lafriks commented
Please send backport to 1.9