[WIP] fix multiple bug with statuses api
go-gitea/gitea pull request #7785
Opened 2019-08-07 15:39 UTC by sapk

Fix #7784

2019-08-08 09:45 UTC, lafriks requested changes

2019-08-08 09:45 UTC, lafriks commented on routers/api/v1/repo/status.go
> +			getCommitStatuses(ctx, refSHA)
imho this would be better so that there is only one place where `getCommitStatuses` is called
```suggestion
			filter = refSHA
			break
```

2019-08-08 09:57 UTC, lafriks commented on routers/api/v1/repo/status.go
> +}
nit
```suggestion
}

```

2019-08-08 10:02 UTC, lafriks approved these changes

2019-08-08 20:58 UTC, zeripath approved these changes

2019-08-09 02:12 UTC, lunny commented
make L-G-T-M work

2019-08-09 02:13 UTC, merged

2019-08-09 02:13 UTC, lunny commented
@sapk Please send back port