Track labels changed on issue view & resolved #542
go-gitea/gitea pull request #788
Opened 2017-01-29 15:48 UTC by lunny

See the screenshot.
![untitled](https://cloud.githubusercontent.com/assets/81045/22405426/5e8a7f46-e67d-11e6-9c03-b0e53ca6df10.png)

2017-01-29 21:59 UTC, strk commented
LGTM, great new features this 1.1.0 :)

2017-01-29 22:11 UTC, bkcsoft reviewed
otherwise LGTM 🙂

2017-01-29 22:11 UTC, bkcsoft commented on models/issue.go
> +	for _, l := range labels {
Maybe we should `Sort` these first? should make it slightly faster in some cases 🙂

2017-01-29 22:11 UTC, bkcsoft commented on models/issue.go
> +	for _, oriLabel := range issue.Labels {
same here 🙂

2017-01-30 01:36 UTC, avelino approved these changes

2017-01-30 03:01 UTC, appleboy requested changes

2017-01-30 03:01 UTC, appleboy commented on routers/repo/issue_label.go
> +package repo
Missing Copyright.

2017-01-30 12:10 UTC, lunny commented on routers/repo/issue_label.go
> +package repo
done.

2017-01-30 12:10 UTC, lunny commented on models/issue.go
> +	for _, oriLabel := range issue.Labels {
done.

2017-01-30 12:46 UTC, bkcsoft commented
LGTM

2017-01-30 12:46 UTC, lunny commented
let L-G-T-M work

2017-01-30 12:46 UTC, merged

2017-02-05 14:41 UTC, lunny commented
resolved #789