Cleanup log messaging
go-gitea/gitea pull request #793
Opened 2017-01-29 21:05 UTC by gabrieljackson

This change corrects a few logging issues:

 * Standardized formatting errors with '%v'.
 * Standardized failure warning word usage.
 * Corrected an instance of using the standard log library when
   the gitea log library should be used instead.

This targets issue https://github.com/go-gitea/gitea/issues/775

2017-01-29 22:31 UTC, bkcsoft requested changes
Few things before LGTM :)

2017-01-29 22:31 UTC, bkcsoft commented on models/migrations/migrations.go
> +		fmt.Println("Failed to rename some attachments, old and new paths are saved into:", dumpPath)
Migrations run just like anything else so they shold probably use `log.Printf` like all the others

2017-01-29 22:31 UTC, bkcsoft commented on models/repo.go
>  				log.Info("Git config %s set to %s", configKey, defaultValue)
Infof ;)

2017-01-29 22:31 UTC, bkcsoft commented on modules/ssh/ssh.go
> +			panic(fmt.Sprintf("Failed to generate private key: %v - %s", err, stderr))
Maybe just use `log.Fatal` (which does `os.Exit(1)` at the end)

2017-01-30 01:37 UTC, gabrieljackson commented on modules/ssh/ssh.go
> +			panic(fmt.Sprintf("Failed to generate private key: %v - %s", err, stderr))
Good catch. I didn't even notice the failure message was wrapped in a panic call. I removed two other uses of `panic()` in the latest commit.

2017-01-30 12:12 UTC, lunny commented
LGTM

2017-01-30 12:21 UTC, appleboy approved these changes

2017-01-30 12:21 UTC, appleboy commented
LGTM

2017-01-31 15:17 UTC, lunny commented
@bkcsoft need your confirm and approve.

2017-02-02 14:24 UTC, bkcsoft approved these changes

2017-02-02 14:24 UTC, merged