Propose some references about ci/cd solutions compatibles with gitea
go-gitea/gitea pull request #7996
Opened 2019-08-27 07:45 UTC by camlafit

* No note about theirs integrations level, it's only a starting point.

2019-08-27 08:57 UTC, lafriks requested changes

2019-08-27 08:57 UTC, lafriks commented on docs/content/doc/advanced/ci-cd.en-us.md
> +Some CI/CD solutions are compatibles with Gitea. As following list can't be complete, the purpose is to give a starting point to integrate a CI/CD process in your gitea.
```suggestion
CI/CD solutions that have integration with Gitea. Following list is not complete,
the purpose is to give a starting point to integrate a CI/CD process with Your Gitea instance.
```

2019-08-27 08:57 UTC, lafriks commented on docs/content/doc/advanced/ci-cd.en-us.md
> + - Drone : https://drone.io
```suggestion
 - [Drone](https://drone.io/)
```

2019-08-27 08:57 UTC, lafriks commented on docs/content/doc/advanced/ci-cd.en-us.md
> + - Jenkins : https://plugins.jenkins.io/gitea
```suggestion
 - [Jenkins](https://jenkins.io/) with [Gitea plugin](https://plugins.jenkins.io/gitea)
```

2019-08-27 08:57 UTC, lafriks commented on docs/content/doc/advanced/ci-cd.en-us.md
> + - Agolia :  https://agola.io
```suggestion
 - [Agolia](https://agola.io/)
```

2019-08-27 08:57 UTC, lafriks commented on docs/content/doc/advanced/ci-cd.en-us.md
> + - Buildkite : https://buildkite.com and https://github.com/techknowlogick/gitea-buildkite-connector
```suggestion
 - [Buildkite](https://buildkite.com/) with [Gitea connector](https://github.com/techknowlogick/gitea-buildkite-connector)
```

2019-08-27 08:57 UTC, lafriks commented on docs/content/doc/advanced/ci-cd.en-us.md
> +Anothers CI/CD could be work with gitea as :
```suggestion
Others CI/CD solutions that partially can be integrated with Gitea:
```

2019-08-27 08:57 UTC, lafriks commented on docs/content/doc/advanced/ci-cd.en-us.md
> + - concourse-ci : https://www.concourse-ci.org and https://discuss.concourse-ci.org/t/concourse-ci-and-gitea-oauth/1475
```suggestion
 - [Concourse](https://concourse-ci.org/), see more info at [Concourse community forum](https://discuss.concourse-ci.org/t/concourse-ci-and-gitea-oauth/1475)
```

2019-08-27 09:27 UTC, camlafit commented
Hello

I've updated texts as suggested 

Thanks

2019-08-27 16:21 UTC, camlafit commented on docs/content/doc/advanced/ci-cd.en-us.md
> + - [Agolia](https://agola.io)
Yes ... I was thinking about algolia :/ 
Thanks

2019-08-27 16:28 UTC, camlafit commented
@techknowlogick but when i do my search to have an idea about compatible CI ecosystem, I haven't found this page. Act as an hidden page, is not intuitive to check this page.

As CI tools looks as a source management continuity, I think could be better to propose a specific page.

2019-08-27 20:48 UTC, lafriks commented
I agree about moving CI/CD to separate page. This PR should replace CI section with link to new page from 3rd party tools page

2019-08-28 04:18 UTC, appleboy requested changes

2019-08-28 04:18 UTC, appleboy commented on docs/content/doc/advanced/ci-cd.en-us.md
> +
remove the redundant empty line.

2019-08-28 11:57 UTC, camlafit commented on docs/content/doc/advanced/ci-cd.en-us.md
> +
Patch done thanks

2019-08-28 11:58 UTC, camlafit commented
> Please disregard my last comment. @lafriks has suggested a better way.

I've update third party page with a replacement link. Hope it's correct.

2019-08-28 13:46 UTC, jolheiser requested changes
Agree having a CI/CD page would be good for clarity. Just a few nits, thanks for the PR!

2019-08-29 06:39 UTC, camlafit commented on docs/content/doc/advanced/ci-cd.en-us.md
> + - [Drone](https://drone.io)
To continue with others CI, I've maintained CI link and add specific gitea link

2019-08-29 06:44 UTC, camlafit commented
Suggestions applied thanks

2019-08-29 12:13 UTC, lafriks commented on docs/content/doc/advanced/ci-cd.en-us.md
> +NOTE: These tools are not endorsed by Gitea. They are listed here for convenience only.
```suggestion
**NOTE:** These tools are not endorsed by Gitea. They are listed here for convenience only.
```

2019-08-29 12:13 UTC, lafriks commented on docs/content/doc/advanced/ci-cd.en-us.md
> + - [Concourse](https://www.concourse-ci.org), see more informations at [Concourse community forum](https://discuss.concourse-ci.org/t/concourse-ci-and-gitea-oauth/1475)
```suggestion
 - [Concourse](https://www.concourse-ci.org), see more information at [Concourse community forum](https://discuss.concourse-ci.org/t/concourse-ci-and-gitea-oauth/1475)
```

2019-08-29 16:05 UTC, camlafit commented
Patches applied

2019-08-29 16:29 UTC, techknowlogick approved these changes

2019-08-29 16:31 UTC, jolheiser approved these changes

2019-08-29 21:30 UTC, merged