Redirects for renamed repos
go-gitea/gitea pull request #807
Opened 2017-02-01 03:52 UTC by ethantkoenig

Adds a new table (`repo_redirect`) to track what previous names should be redirected to.

2017-02-02 15:01 UTC, lunny commented
But if A -> B, but C -> A, then A will never be visit?

2017-02-02 16:42 UTC, ethantkoenig commented
@lunny Good point, there are a lot of bugs with reusing previously-used repo names. I'll work on finding a solution.

2017-02-02 18:00 UTC, ethantkoenig commented
@lunny I've added changes so that whenever a repo is created or renamed, any redirects *from* the new name are deleted. I believe this should fix the problem.

2017-02-03 01:26 UTC, lunny requested changes

2017-02-03 01:26 UTC, lunny commented on models/repo_redirect.go
> +	if err := deleteRepoRedirect(x, ownerID, newRepoName); err != nil {
I would like you use a database transaction to do that.

2017-02-03 01:37 UTC, lunny approved these changes

2017-02-03 01:37 UTC, lunny commented on models/repo_redirect.go
> +	if err := deleteRepoRedirect(x, ownerID, newRepoName); err != nil {
^

2017-02-03 04:04 UTC, ethantkoenig commented on models/repo_redirect.go
> +	if err := deleteRepoRedirect(x, ownerID, newRepoName); err != nil {
Added :grinning:

2017-02-03 05:30 UTC, lunny commented on templates/repo/settings/options.tmpl
> +							<label for="repo_name">{{.i18n.Tr "repo.repo_name"}}</label>
why remove the prompt?

2017-02-03 05:58 UTC, lunny commented
Otherwise LGTM

2017-02-03 14:01 UTC, ethantkoenig commented on templates/repo/settings/options.tmpl
> +							<label for="repo_name">{{.i18n.Tr "repo.repo_name"}}</label>
The prompt warns that "This change will affect how links relate to the repository". Once we have redirects, what the prompt says will no longer be true.

2017-02-03 14:27 UTC, lunny commented on templates/repo/settings/options.tmpl
> +							<label for="repo_name">{{.i18n.Tr "repo.repo_name"}}</label>
OK

2017-02-03 17:31 UTC, bkcsoft commented
If I remember correcly, the way github does it is to redirect for X period of time, during that time no new repo can be created with that name. Sounds good?

2017-02-03 18:09 UTC, ethantkoenig commented
@bkcsoft Github lets you create a new repo with the old name immediately; I just checked. Perhaps it used to be as you described, but not anymore?

2017-02-05 01:38 UTC, lunny commented
conflicted

2017-02-05 14:29 UTC, appleboy approved these changes

2017-02-05 14:29 UTC, appleboy commented
LGTM

2017-02-05 14:35 UTC, merged

2017-02-07 13:43 UTC, lunny commented
resolved #806