use go 1.13
go-gitea/gitea pull request #8088
Opened 2019-09-04 18:54 UTC by techknowlogick

as title

2019-09-04 20:44 UTC, sapk requested changes
You need to update go.mod by upgrading the first line to enable 1.13 libs.

2019-09-05 02:21 UTC, techknowlogick commented
@sapk seems golangci-lint fails, and the reports contain incorrect information. I will look into this more.

2019-09-05 14:14 UTC, lafriks commented on go.mod
> +go 1.13
why update go.mod?

2019-09-05 14:14 UTC, lafriks commented
> 
> 
> You need to update go.mod by upgrading the first line to enable 1.13 libs.

why?

2019-09-05 20:04 UTC, sapk commented
@lafriks I need to find the link but I remember that the std lib are also versionned now and that go compiler will use the one specified in go.mod

2019-09-05 20:13 UTC, sapk commented
From https://golang.org/doc/go1.13
> If your code uses modules and your go.mod files specifies a language version, be sure it is set to at least 1.13 to get access to these language changes. You can do this by editing the go.mod file directly, or you can run go mod edit -go=1.13.

But I have also seen that some suggest to declare the minimal go version supported. This seems logic since it should be the lowest required std libs. I don't know go internal to say what is the best. 

On a sidenote, I hope we can use new error methods soon.

2019-09-06 05:51 UTC, lafriks commented
> 
> 
> From https://golang.org/doc/go1.13
> 
> > If your code uses modules and your go.mod files specifies a language version, be sure it is set to at least 1.13 to get access to these language changes. You can do this by editing the go.mod file directly, or you can run go mod edit -go=1.13.
> 
> But I have also seen that some suggest to declare the minimal go version supported. This seems logic since it should be the lowest required std libs. I don't know go internal to say what is the best.
> 
> On a sidenote, I hope we can use new error methods soon.

I should more carefully read release notes :D Thanks for pointing out to this ;)

2019-09-06 08:23 UTC, sapk commented
@lafriks go module is a good point providing a standard and more secure deps management but they are few quirks to get around and I also don't get some.

2019-09-09 20:49 UTC, techknowlogick commented
Currently blocked on: https://github.com/golangci/golangci-lint/issues/663

2019-09-09 22:19 UTC, guillep2k commented
> 
> 
> Currently blocked on: [golangci/golangci-lint#663](https://github.com/golangci/golangci-lint/issues/663)

Just in case, that issue was marked as duplicate of [golangci/golangci-lint#659](https://github.com/golangci/golangci-lint/issues/659)

2019-09-11 00:05 UTC, techknowlogick commented
deps have been upgraded and build now passes. In addition to golangci-lint, I also update swagger.

Please review :)

2019-09-11 08:49 UTC, sapk approved these changes

2019-09-12 10:07 UTC, lafriks approved these changes

2019-09-12 11:58 UTC, merged