Add checkbox to search for all the branches by commit message
go-gitea/gitea pull request #813
Opened 2017-02-01 19:32 UTC by gzsombor

This patch adds the ability to search for all the commits containing the entered text in their commit message, not only in the current branch

2017-02-04 17:06 UTC, andreynering requested changes
It's working, but need few changes.

2017-02-04 17:06 UTC, andreynering commented on options/locale/locale_en-US.ini
> +commits.searchAll = All
Use snake_case:

`searchAll` -> `search_all`

2017-02-04 17:06 UTC, andreynering commented on vendor/code.gitea.io/git/commit.go
> +	return c.repo.searchCommits(c.ID, keyword, all)
You should change this package directly in the vendor folder.

You should send PR to https://github.com/go-gitea/git first, and after aproved use [govendor][govendor] to update the changes here.

[govendor]: https://github.com/kardianos/govendor

2017-02-04 17:06 UTC, andreynering commented on templates/repo/commits_table.tmpl
> +				<input type="checkbox" name="all" id="all" value="true" {{.All}}><label for="all">{{.i18n.Tr "repo.commits.searchAll"}}</label>
Here, too:

`searchAll` -> `search_all`

2017-02-05 09:31 UTC, gzsombor commented
Hope, I've done it correctly, I've never used go before :)

2017-02-05 10:32 UTC, appleboy approved these changes

2017-02-05 10:33 UTC, appleboy commented
LGTM

2017-02-05 12:27 UTC, lunny commented
@andreynering please confirm.

2017-02-05 14:32 UTC, andreynering approved these changes

2017-02-05 14:34 UTC, andreynering commented
@lunny Approved

@gzsombor Thank you for your PRs and fast changes.

2017-02-05 14:37 UTC, lunny commented
@andreynering then change this to v1.1 or wait to v1.2?

2017-02-05 14:41 UTC, andreynering commented
@lunny I think this change is simple enough and can be merged now.

2017-02-05 14:42 UTC, andreynering commented
LGTM

2017-02-05 14:43 UTC, merged