oauth2 with remote Gitea
go-gitea/gitea pull request #8149
Opened 2019-09-11 04:23 UTC by techknowlogick

Fix #8093

2019-09-11 04:31 UTC, techknowlogick commented
I'm using go1.13 so my vendor file is different. This is blocked by https://github.com/go-gitea/gitea/pull/8088

2019-09-11 14:50 UTC, lunny requested changes

2019-09-11 14:50 UTC, lunny commented on vendor/github.com/blevesearch/segment/maketesttables.go
> -//  Copyright (c) 2015 Couchbase, Inc.
These files looks they should not be deleted in this PR.

2019-09-12 22:48 UTC, lafriks approved these changes

2019-09-13 01:27 UTC, lunny approved these changes

2019-09-13 02:15 UTC, merged