Include git-hook regeneration in restore documentation
go-gitea/gitea pull request #8181
Opened 2019-09-14 23:11 UTC by wranders

This PR is to include the git-hook regeneration command to the `restore` section of the `Backup and Restore` guide.

When migrating to a different installation method (eg. binary -> Docker), there is currently no mention of needing to regenerate git-hooks, causing `push` actions to fail on the new installation.

2019-09-14 23:59 UTC, guillep2k requested changes

2019-09-14 23:59 UTC, guillep2k commented on docs/content/doc/usage/backup-and-restore.en-us.md
> +This ensures that application and configuration file paths in repository git-hooks are consistent and applicable to the current installation. If these paths are not updated, repository `push` actions
```suggestion
This ensures that application and configuration file paths in repository git-hooks are consistent and applicable to the current installation. If these paths are not updated, repository `push` actions will fail.
```

2019-09-14 23:59 UTC, guillep2k commented on docs/content/doc/usage/backup-and-restore.en-us.md
> +With Gitea running, execute: `./gitea admin regenerate hooks`
```suggestion
With Gitea running, and from the directory Gitea's binary is located, execute: `./gitea admin regenerate hooks`
```

2019-09-15 00:12 UTC, wranders commented
Suggestions added.

Using `may` in the consequence language was to cover the possibility that paths could be valid in a migration, but there's no harm in running the command in that case.

2019-09-15 00:34 UTC, guillep2k commented
> 
> 
> Suggestions added.
> 
> Using `may` in the consequence language was to cover the possibility that paths could be valid in a migration, but there's no harm in running the command in that case.

Of course you're right, but in a migration guide I think it's better to play safe for the reasons you mention.

2019-09-15 00:35 UTC, guillep2k approved these changes

2019-09-15 02:36 UTC, lunny approved these changes

2019-09-15 02:37 UTC, merged