Fix newline in Unlicense
go-gitea/gitea pull request #8182
Opened 2019-09-15 01:39 UTC by Uthar

This removes an extra newline.

2019-09-15 04:34 UTC, guillep2k approved these changes

2019-09-15 10:18 UTC, lafriks commented
Is this change from upstream?

2019-09-15 22:53 UTC, techknowlogick requested changes
Thanks for PR. These are generated from an upstream source of https://github.com/spdx/license-list-data 

Please submit your changes to them first.

2019-10-27 21:36 UTC, 6543 approved these changes

2019-10-30 16:19 UTC, closed without merging