Fix bug when repository deleted but its issues not
go-gitea/gitea pull request #8207
Opened 2019-09-17 07:38 UTC by lunny

2019-09-17 09:03 UTC, guillep2k commented
So this is a paliative measure? Why would the issues remain in the database when the repos have been deleted?

2019-09-17 09:27 UTC, lafriks requested changes

2019-09-17 09:27 UTC, lafriks commented on models/issue_list.go
> +		if issue.Repo != nil {
merge both `if` in single condition
```suggestion
		if issue.Repo != nil && issue.Repo.IsTimetrackerEnabled() {
```

2019-09-24 06:38 UTC, lunny commented on models/issue_list.go
> +		if issue.Repo != nil {
done.

2019-09-24 06:41 UTC, lafriks commented on models/issue_list.go
> +		issue.loadRepo(e)
drone build fails:
```
models/issue_list.go:418:17: Error return value of `issue.loadRepo` is not checked (errcheck)
```

2019-10-03 03:17 UTC, guillep2k commented on routers/user/home.go
> +				commitStatus[issue.PullRequest.ID], _ = issue.PullRequest.GetLastCommitStatus()
Is it certain that the error can be ignored?

2019-10-03 03:17 UTC, guillep2k commented on routers/user/home.go
> +			issue.Repo = repo
```suggestion
		issue.Repo, ok := showReposMap[issue.RepoID]
		if ok {
```

2019-10-04 01:26 UTC, lunny commented
I think this could be closed. It assumes the data is broken but I think it should not.

2019-10-07 12:52 UTC, closed without merging