Extract actions on new pull request from models to pulls service
go-gitea/gitea pull request #8218
Opened 2019-09-18 00:46 UTC by lunny

As title.

2019-09-18 05:50 UTC, lafriks requested changes

2019-09-18 05:50 UTC, lafriks commented on services/pulls/pulls.go
> +func NewPullRequest(repo *models.Repository, pull *models.Issue, labelIDs []int64, uuids []string, pr *models.PullRequest, patch []byte, assigneeIDs []int64) (err error) {
```suggestion
func NewPullRequest(repo *models.Repository, pull *models.Issue, labelIDs []int64, uuids []string, pr *models.PullRequest, patch []byte, assigneeIDs []int64) error {
```

2019-09-18 05:50 UTC, lafriks commented on services/pulls/pulls.go
> +	if err = models.NewPullRequest(repo, pull, labelIDs, uuids, pr, patch, assigneeIDs); err != nil {
```suggestion
	if err := models.NewPullRequest(repo, pull, labelIDs, uuids, pr, patch, assigneeIDs); err != nil {
```

2019-09-18 05:50 UTC, lafriks commented on services/pulls/pulls.go
> +		return
```suggestion
		return err
```

2019-09-18 05:50 UTC, lafriks commented on services/pulls/pulls.go
> +	if err = models.NotifyWatchers(&models.Action{
```suggestion
	if err := models.NotifyWatchers(&models.Action{
```

2019-09-18 05:50 UTC, lafriks commented on services/pulls/pulls.go
> +	if err = models.PrepareWebhooks(repo, models.HookEventPullRequest, &api.PullRequestPayload{
```suggestion
	if err := models.PrepareWebhooks(repo, models.HookEventPullRequest, &api.PullRequestPayload{
```

2019-09-25 01:12 UTC, lunny commented
@lafriks done.

2019-09-25 08:46 UTC, lafriks commented on routers/api/v1/repo/pull.go
> +	pull_service "code.gitea.io/gitea/services/pulls"
import declared with same name as import above:
```
pull_service "code.gitea.io/gitea/modules/pull"
```

2019-09-25 08:47 UTC, lafriks requested changes

2019-09-25 08:47 UTC, lafriks commented on services/pulls/pulls.go
> +package pulls
It should probably be named `pull` to have same naming as it already is for `modules/pull`

2019-09-25 08:57 UTC, lunny commented
@lafriks done and moved `code.gitea.io/gitea/modules/pull` to `code.gitea.io/gitea/services/pull`

2019-09-26 15:34 UTC, guillep2k approved these changes

2019-09-26 19:21 UTC, lafriks approved these changes

2019-09-27 00:22 UTC, lunny commented
make L-G-T-M work

2019-09-27 00:22 UTC, merged