Fix assets key on release webhook
go-gitea/gitea pull request #8253
Opened 2019-09-20 16:46 UTC by danielflira

When repository has release webhook enabled, on update of releases the webhook goes without last assets included.

Release without attachment:
![image](https://user-images.githubusercontent.com/1221107/65336107-20039e80-db9c-11e9-9591-342308563b0c.png)

Adding new attachment:
![image](https://user-images.githubusercontent.com/1221107/65336277-783aa080-db9c-11e9-94a6-fd3dc1cffb17.png)

Webhook message without attachment:
```json
{
  "release": {
    "asset": []
  }
}
```

Release with attachment:
![image](https://user-images.githubusercontent.com/1221107/65343973-bfc92880-dbac-11e9-9894-89554d614d78.png)

2019-09-20 21:33 UTC, lafriks requested changes

2019-09-20 21:33 UTC, lafriks commented on services/release/release.go
> +	_ = models.AddReleaseAttachments(rel.ID, attachmentUUIDs)
I don't think you should be ignoring error here

2019-09-23 16:38 UTC, lunny approved these changes

2019-09-23 19:50 UTC, lafriks approved these changes

2019-09-24 06:55 UTC, merged

2019-09-24 06:55 UTC, lunny commented
Please send back port to v1.9