Test more reserved usernames
go-gitea/gitea pull request #8263
Opened 2019-09-23 06:13 UTC by strk

I noticed there endpoints that are not tested as being reserved, this
PR adds a few

2019-09-23 06:57 UTC, lafriks commented
Tests seem to fail, check drone log

2019-09-23 07:29 UTC, strk commented
We're clearing not enforcing reservation of some names, which we should instead reserve. Do you agree all names I added should be reserved ?

2019-09-23 20:36 UTC, guillep2k requested changes

2019-09-23 20:36 UTC, guillep2k commented on integrations/user_test.go
> +		"avatar",
```suggestion
		"avatars",
```

2019-09-24 10:58 UTC, guillep2k approved these changes

2019-09-24 11:24 UTC, lafriks approved these changes

2019-09-24 17:12 UTC, merged