Improve integration tests
go-gitea/gitea pull request #8276
Opened 2019-09-24 15:47 UTC by lunny

This PR tried to make integration tests locally easier and also fix some problem when parallel running different database integrations tests.

2019-09-24 16:28 UTC, guillep2k approved these changes

2019-09-24 17:56 UTC, lafriks approved these changes

2019-09-24 19:06 UTC, sapk requested changes
docker inspect command are not needed anymore.

2019-09-24 19:06 UTC, sapk commented on integrations/README.md
> +TEST_MYSQL_HOST=$(docker inspect -f 'localhost:3306' mysql) TEST_MYSQL_DBNAME=test TEST_MYSQL_USERNAME=root TEST_MYSQL_PASSWORD='' make test-mysql
```suggestion
TEST_MYSQL_HOST=localhost:3306 TEST_MYSQL_DBNAME=test TEST_MYSQL_USERNAME=root TEST_MYSQL_PASSWORD='' make test-mysql
```

2019-09-24 19:06 UTC, sapk commented on integrations/README.md
> +TEST_PGSQL_HOST=$(docker inspect -f 'localhost:5432' pgsql) TEST_PGSQL_DBNAME=test TEST_PGSQL_USERNAME=postgres TEST_PGSQL_PASSWORD=postgres make test-pgsql
```suggestion
TEST_PGSQL_HOST=localhost:5432 TEST_PGSQL_DBNAME=test TEST_PGSQL_USERNAME=postgres TEST_PGSQL_PASSWORD=postgres make test-pgsql
```

2019-09-24 19:06 UTC, sapk commented on integrations/README.md
> +TEST_MSSQL_HOST=$(docker inspect -f 'localhost:1433' mssql) TEST_MSSQL_DBNAME=gitea_test TEST_MSSQL_USERNAME=sa TEST_MSSQL_PASSWORD=MwantsaSecurePassword1 make test-mssql
```suggestion
TEST_MSSQL_HOST=localhost:1433 TEST_MSSQL_DBNAME=gitea_test TEST_MSSQL_USERNAME=sa TEST_MSSQL_PASSWORD=MwantsaSecurePassword1 make test-mssql
```

2019-09-24 19:06 UTC, sapk commented on integrations/README_ZH.md
> +TEST_MYSQL_HOST=$(docker inspect -f 'localhost:3306' mysql) TEST_MYSQL_DBNAME=test TEST_MYSQL_USERNAME=root TEST_MYSQL_PASSWORD='' make test-mysql
```suggestion
TEST_MYSQL_HOST=localhost:3306 TEST_MYSQL_DBNAME=test TEST_MYSQL_USERNAME=root TEST_MYSQL_PASSWORD='' make test-mysql
```

2019-09-24 19:06 UTC, sapk commented on integrations/README_ZH.md
> +TEST_PGSQL_HOST=$(docker inspect -f 'localhost:5432' pgsql) TEST_PGSQL_DBNAME=test TEST_PGSQL_USERNAME=postgres TEST_PGSQL_PASSWORD=postgres make test-pgsql
```suggestion
TEST_PGSQL_HOST=localhost:5432 TEST_PGSQL_DBNAME=test TEST_PGSQL_USERNAME=postgres TEST_PGSQL_PASSWORD=postgres make test-pgsql
```

2019-09-24 19:06 UTC, sapk commented on integrations/README_ZH.md
> +TEST_MSSQL_HOST=$(docker inspect -f 'localhost:1433' mssql) TEST_MSSQL_DBNAME=test TEST_MSSQL_USERNAME=sa TEST_MSSQL_PASSWORD=MwantsaSecurePassword1 make test-mssql#GPG
```suggestion
TEST_MSSQL_HOST=localhost:1433 TEST_MSSQL_DBNAME=test TEST_MSSQL_USERNAME=sa TEST_MSSQL_PASSWORD=MwantsaSecurePassword1 make test-mssql#GPG
```

2019-09-24 19:12 UTC, sapk requested changes
please add required step `generate-ini-mysql`

2019-09-24 19:12 UTC, sapk commented on Makefile
> +test-mysql\#%: integrations.mysql.test
```suggestion
test-mysql\#%: integrations.mysql.test generate-ini-mysql
```

2019-09-24 19:12 UTC, sapk commented on Makefile
> +test-mysql8\#%: integrations.mysql8.test
```suggestion
test-mysql8\#%: integrations.mysql8.test generate-ini-mysql8
```

2019-09-24 19:12 UTC, sapk commented on Makefile
> +test-pgsql\#%: integrations.pgsql.test
```suggestion
test-pgsql\#%: integrations.pgsql.test generate-ini-pgsql
```

2019-09-24 19:12 UTC, sapk commented on Makefile
> +test-mssql\#%: integrations.mssql.test
```suggestion
test-mssql\#%: integrations.mssql.test generate-ini-mssql
```

2019-09-24 19:14 UTC, sapk requested changes
I missed those two lines also ...

2019-09-24 19:14 UTC, sapk commented on integrations/README.md
> +TEST_MSSQL_HOST=$(docker inspect -f 'localhost:1433' mssql) TEST_MSSQL_DBNAME=test TEST_MSSQL_USERNAME=sa TEST_MSSQL_PASSWORD=MwantsaSecurePassword1 make test-mssql#GPG
```suggestion
TEST_MSSQL_HOST=localhost:1433 TEST_MSSQL_DBNAME=test TEST_MSSQL_USERNAME=sa TEST_MSSQL_PASSWORD=MwantsaSecurePassword1 make test-mssql#GPG
```

2019-09-24 19:14 UTC, sapk commented on integrations/README_ZH.md
> +TEST_MSSQL_HOST=$(docker inspect -f 'localhost:1433' mssql) TEST_MSSQL_DBNAME=gitea_test TEST_MSSQL_USERNAME=sa TEST_MSSQL_PASSWORD=MwantsaSecurePassword1 make test-mssql
```suggestion
TEST_MSSQL_HOST=localhost:1433 TEST_MSSQL_DBNAME=gitea_test TEST_MSSQL_USERNAME=sa TEST_MSSQL_PASSWORD=MwantsaSecurePassword1 make test-mssql
```

2019-09-25 00:37 UTC, lunny commented
All done.

2019-09-25 12:13 UTC, sapk approved these changes

2019-09-25 12:13 UTC, merged