Update CodeMirror to version 5.49.0
go-gitea/gitea pull request #8381
Opened 2019-10-04 15:39 UTC by oscarlofwenhamn

Solves #8379

2019-10-14 19:15 UTC, zeripath approved these changes
Have confirmed that the addon and mode directories match those in codemirror-5.49

2019-10-15 01:33 UTC, lunny commented
A javascript package management is to-do thing we need. So that we can use `npm` to confirm all the package versions and generate javascript sources.

2019-10-15 05:44 UTC, lafriks requested changes
https://github.com/go-gitea/gitea/blob/master/public/vendor/librejs.html#L96
https://github.com/go-gitea/gitea/blob/master/public/vendor/librejs.html#L101
https://github.com/go-gitea/gitea/blob/master/public/vendor/VERSIONS#L45

needs to be updated to new version

2019-10-15 08:13 UTC, lafriks approved these changes

2019-10-15 08:40 UTC, merged