Doc recommend to use reverse proxy if Apache/nginx is also running on…
go-gitea/gitea pull request #8384
Opened 2019-10-05 13:13 UTC by 8ctopus

My default goto when I wanted to setup https was the first option "Using the built-in server". I believe it can be useful to add a note that recommends the reverse proxy option if you already have a webserver running.

2019-10-05 16:19 UTC, lafriks approved these changes

2019-10-05 19:00 UTC, jolheiser requested changes

2019-10-05 19:00 UTC, jolheiser commented on docs/content/doc/usage/https-support.md
> +If you are using Apache or nginx on the server, it's recommended to check the [reverse proxy guide](../reverse-proxies).
This should use a Hugo relref.

```suggestion
If you are using Apache or nginx on the server, it's recommended to check the [reverse proxy guide]({{< relref "doc/usage/reverse-proxies.en-us.md" >}}).

2019-10-07 19:53 UTC, jolheiser approved these changes

2019-10-09 23:11 UTC, zeripath approved these changes

2019-10-09 23:11 UTC, merged