fix: wrong pages number which includes private repository count.
go-gitea/gitea pull request #844
Opened 2017-02-05 06:31 UTC by appleboy

fix #843

* Add unit testing.
* Add `GetPublicRepositoryCount` func
* Add `GetPrivateRepositoryCount` func

2017-02-05 06:47 UTC, lunny commented
trusted LGTM

2017-02-06 04:00 UTC, ethantkoenig requested changes

2017-02-06 04:00 UTC, ethantkoenig commented on models/repo.go
> +// GetPrivateRepositoryCount returns the total number of public repositories of user.
public -> private

2017-02-06 04:00 UTC, ethantkoenig commented on models/repo_test.go
> +	count, _ := GetRepositoryCount(&User{ID: int64(10)})
Could we assert that the returned `error` is `nil`, instead of just ignoring it?

2017-02-06 04:00 UTC, ethantkoenig commented on models/repo_test.go
> +	count, _ := GetPublicRepositoryCount(&User{ID: int64(10)})
^

2017-02-06 04:00 UTC, ethantkoenig commented on models/repo_test.go
> +	count, _ := GetPrivateRepositoryCount(&User{ID: int64(10)})
^

2017-02-06 04:00 UTC, ethantkoenig commented on routers/user/profile.go
> +				count, _ := models.GetPublicRepositoryCount(ctxUser)
Could we check if the returned `error` is `nil` instead of ignoring it?

2017-02-06 04:07 UTC, appleboy commented on models/repo.go
> +// GetPrivateRepositoryCount returns the total number of public repositories of user.
Why? Already has `getPrivateRepositoryCount`  private function.

2017-02-06 04:10 UTC, ethantkoenig commented on models/repo.go
> +// GetPrivateRepositoryCount returns the total number of public repositories of user.
`returns the total number of public repositories of user.` -> `returns the total number of private repositories of user.` :smile:

2017-02-06 04:15 UTC, appleboy commented on models/repo.go
> +// GetPrivateRepositoryCount returns the total number of public repositories of user.
@ethantkoenig understood. 👍

2017-02-06 04:20 UTC, appleboy commented on models/repo.go
> +// GetPrivateRepositoryCount returns the total number of public repositories of user.
Done

2017-02-06 04:20 UTC, appleboy commented on models/repo_test.go
> +	count, _ := GetRepositoryCount(&User{ID: int64(10)})
Done

2017-02-06 04:20 UTC, appleboy commented on models/repo_test.go
> +	count, _ := GetPublicRepositoryCount(&User{ID: int64(10)})
Done

2017-02-06 04:21 UTC, appleboy commented on models/repo_test.go
> +	count, _ := GetPrivateRepositoryCount(&User{ID: int64(10)})
Done

2017-02-06 04:21 UTC, appleboy commented on routers/user/profile.go
> +				count, _ := models.GetPublicRepositoryCount(ctxUser)
Done

2017-02-06 05:26 UTC, ethantkoenig approved these changes
LGTM

2017-02-06 05:26 UTC, ethantkoenig commented
LGTM

2017-02-06 15:18 UTC, merged