move front end source files to web_src and generate index.js minify version
go-gitea/gitea pull request #8440
Opened 2019-10-09 12:39 UTC by lunny

Fix #8430 and this will also reduce gitea package size since we moved frontend source files from public directory.

2019-10-09 14:19 UTC, guillep2k commented
Was `npm` already a requirement for building from source?

2019-10-09 14:24 UTC, guillep2k commented
Shouldn't we lock to a specific version of the minifier? Otherwise CI build might differ from the committed version.

2019-10-09 15:39 UTC, silverwind commented on Makefile
> +
This is unnecessary, just run `npm install --save-dev webpack` which will add it as a proper dependency.

2019-10-09 15:47 UTC, silverwind commented
This doesn't really solve https://github.com/go-gitea/gitea/issues/8430. All that webpack config does is copy source to destination. If you want to minify, you would at least want to add a minify plugin, for which I recommend `terser`:

https://github.com/webpack-contrib/terser-webpack-plugin

2019-10-10 06:50 UTC, gary-kim requested changes
We should add a `package.json` and handle dependencies there. We also need to set Webpack to production mode for the final compile, either in the Webpack config or in the command for it.

2019-10-10 07:08 UTC, lunny commented
@gary-kim we already have a `package.json` file on home dir.

2019-10-10 13:48 UTC, gary-kim commented
🤦 Forgot about LESS.
What @silverwind said then.

2019-10-20 09:38 UTC, closed without merging