[WIP] Write tests for issue API
go-gitea/gitea pull request #86
Opened 2016-11-05 17:05 UTC by andreynering

Please don't merge yet. Opened for discussion on testing approach.

2016-11-05 17:23 UTC, makhov requested changes

2016-11-05 17:23 UTC, makhov commented on modules/setting/setting.go
> +	if InstallLock && AppRunMode != RUN_MODE_TEST {
Change code for testing is a bad practice

2016-11-05 17:23 UTC, makhov commented on models/models.go
> +func Database() *sql.DB {
And now we can execute SQL queries from handlers?

2016-11-05 17:23 UTC, makhov commented on routers/api/v1/repo/issue_test.go
> +			So(w.Code, ShouldEqual, http.StatusOK)
Test which test nothing

2016-11-05 17:26 UTC, andreynering commented on modules/setting/setting.go
> +	if InstallLock && AppRunMode != RUN_MODE_TEST {
I agree. This is a WIP, we should abstract things using interfaces. I am open for suggestions on how to do it right.

2016-11-05 17:29 UTC, tboerger commented
@makhov glad that you are back :)

2016-11-05 17:37 UTC, andreynering commented on routers/api/v1/repo/issue_test.go
> +			So(w.Code, ShouldEqual, http.StatusOK)
Well, it tests if `/api/v1/repos/user1/foo/issues` returns status 200.

2016-11-06 10:53 UTC, makhov commented on routers/api/v1/repo/issue_test.go
> +			So(w.Code, ShouldEqual, http.StatusOK)
I see, but it useless info. `/api/v1/repos/user1/foo/issues` may returns 200 and `{"foo": "bar"}` in response body. Or `{"oops": "something went wrong"}`. Or `Fuck the json`, etc…

2016-11-06 10:53 UTC, makhov commented on modules/setting/setting.go
> +	if InstallLock && AppRunMode != RUN_MODE_TEST {
Ok, thank you. It's very important to write testable code 👍

2016-11-14 19:30 UTC, bkcsoft requested changes

2016-11-14 19:30 UTC, bkcsoft commented on modules/setting/setting.go
> +func GiteaPath() string {
Exported functions should have be commented :smile:

2016-11-14 19:30 UTC, bkcsoft commented on testdata/app_test.ini
> +# DON'T CHANGE IT. THIS IS NOT THE FILE GOGS WILL USE IN PRODUCTION
`GOGS` ? :trollface:

2016-11-14 19:30 UTC, bkcsoft commented on testdata/app_test.ini
> +APP_NAME = Gogs: Go Git Service
Same as above

2016-12-25 23:30 UTC, bkcsoft commented
As I'm a big promoter of unit-tests, I'd prefer if we'd start with the model-tests instead. That way we get rid of a bunch of edge-cases before going for e2e-tests (integration, like these ones). It's also extremely hard to force edge-cases from this level, and the amount of tests would blow out of proportions. Testing models is easier since we know what goes in an out, and we don't have to force edge-cases. I also suggest that we use in-memory sqlite database

2016-12-27 21:40 UTC, andreynering commented
So this need more discussion...

2016-12-27 21:40 UTC, closed without merging