Avoid re-issuing redundant cross-references.
go-gitea/gitea pull request #8734
Opened 2019-10-29 04:05 UTC by guillep2k

Fixes #8722 

This will avoid rewriting the reference if its the same as an existing one.

2019-10-29 07:04 UTC, 6543 commented
I'll test it this day ...

2019-10-29 07:32 UTC, lafriks requested changes

2019-10-29 07:32 UTC, lafriks commented on models/issue_xref.go
> +	err := sess.Find(&active)
```suggestion
```

2019-10-29 07:32 UTC, lafriks commented on models/issue_xref.go
> +	return active, err
```suggestion
	return active, sess.Find(&active)
```

2019-10-29 14:47 UTC, guillep2k commented on models/issue_xref.go
> +	return active, err
@lafriks done

2019-10-29 14:48 UTC, guillep2k commented
In theory this could be ported to 1.10.0.

2019-10-29 14:59 UTC, 6543 commented
this case does still produce redundancy:
```sh
create issue A
create issue B

from B reverence A
from B reverence A again
from B reverence A again
```
Result: same issue referenced in line ...

what i expect until there is a message in between no new reverence/update last rev

2019-10-29 15:06 UTC, guillep2k commented
> 
> 
> this case does still produce redundancy:
> 
> ```shell
> create issue A
> create issue B
> 
> from B reverence A
> from B reverence A again
> from B reverence A again
> ```
> 
> Result: same issue referenced in line ...
> 
> what i expect until there is a message in between no new reverence/update last rev

I don't think I should remove that case. If the issue was referenced twice, IMHO there should be two lines with references. The md parsing code will eliminate references from quotes and code, so I think it's worth leaving them.

Even from the algorithm point of view, think of what would happen if the users decides to delete the first comment? Should I parse all comments and check again all possible references before I delete the corresponding one?

Besides, the reference is not the same: they each point to a different comment#snug

2019-10-29 21:39 UTC, 6543 approved these changes

2019-11-02 22:12 UTC, 6543 commented
@lafriks can you review?

2019-11-18 12:58 UTC, lafriks approved these changes

2019-11-18 13:22 UTC, 6543 commented
@guillep2k can you resolve conflicts thx

2019-11-18 15:43 UTC, guillep2k commented
Conflicts solved

2019-11-18 23:42 UTC, lafriks commented
Make LG-TM work :)

2019-11-18 23:43 UTC, merged