fixes #8725: change footer from `© Gitea` to `Powered by Gitea`
go-gitea/gitea pull request #8735
Opened 2019-10-29 09:58 UTC by alexanderadam

I like [this proposal](https://github.com/go-gitea/gitea/issues/8725#issue-513583217) so I thought I just could make a PR for it.
I'm just not sure whether it should stay static or moved into the locale data.

2019-10-29 10:00 UTC, 6543 commented
close #8725

2019-10-29 10:53 UTC, lunny requested changes
Per my comment on https://github.com/go-gitea/gitea/issues/8725#issuecomment-547360573

2019-10-30 06:32 UTC, davidsvantesson commented
To show that the copyright notice is related to the product and not the content it could say something like
`Powered by Gitea © 2019`

2019-10-30 10:17 UTC, lafriks commented
> 
> 
> To show that the copyright notice is related to the product and not the content it could say something like
> `Powered by Gitea © 2019`

Just Powered by is enaugh imho

2019-10-31 13:48 UTC, guillep2k commented
Yes, I also think that © is not need.

2019-10-31 14:10 UTC, 6543 commented
@alexanderadam can you move `Powerd by` to `.i18n.Tr "powerd_by"` or kind of that ...

2019-10-31 15:44 UTC, lunny commented
@guillep2k but we should put the copyright information on some page on a former production. Maybe we could make a page on admin panel to display the copyright and other information.

2019-10-31 15:46 UTC, lafriks commented
@lunny I don't think it's needed as all copyright info is in source code

2019-10-31 15:55 UTC, lunny commented
@lafriks As I know, not everyone will see your copyright on codes. Many of them just download binary and use it. It's a binary or production not a service, so I think it's necessary and maybe we also need to add contributors there.

2019-10-31 16:47 UTC, alexanderadam commented
> I think it's necessary and maybe we also need to add contributors there.

Are you sure? That it's necessary? IMHO the copyright note adds no value here because the legal declaration is more or less the **license**. So linking the license would probably indeed add a value (which is already done for the JS libaries anyway).

Or maybe it would be good to have a general license page or so. But again: it would probably better to ask a proper lawyer regarding this instead everyone speculating here. :wink:

2019-10-31 17:20 UTC, guillep2k commented
> 
> 
> @lafriks As I know, not everyone will see your copyright on codes. Many of them just download binary and use it. It's a binary or production not a service, so I think it's necessary and maybe we also need to add contributors there.

I like that idea. "About Gitea" in the menu? 😁 (It could be only accessible for admin, but I'd make it accessible for all).

2019-10-31 17:26 UTC, 6543 commented
@guillep2k -> GDRP ;)

2019-10-31 18:00 UTC, davidsvantesson commented
@6543 God Damn Pull Request?  😁

2019-11-01 00:57 UTC, lunny commented
@6543 A [GDPR](https://eugdpr.org/) should be provided by the service provider who running a gitea instance but not with the gitea binary. 

@guillep2k I like your idea, we could add an `About Gitea` on the bottom and link to a page accessible by all. And then I think this PR could be merged because that should be another PR.

2019-11-05 13:38 UTC, gary-kim commented
I'm in support of the idea of having the `Powered by Gitea` message and making that a link to the `About Gitea` page. Always thought `© Gitea` was a bit weird.

2019-11-05 14:42 UTC, lunny commented
@alexanderadam Could you add an about page in this PR?

2019-11-06 09:00 UTC, alexanderadam commented
> @alexanderadam Could you add an about page in this PR?

It would be better if someone else could do this.

2019-12-15 14:41 UTC, gsantner commented
Just a approve away from merge right? so many forgotten PRs :smile:

2019-12-15 15:45 UTC, lafriks commented on templates/base/footer_content.tmpl
> +			Powered by Gitea {{if (or .ShowFooterVersion .PageIsAdmin)}}{{.i18n.Tr "version"}}: {{AppVer}}{{end}} {{if ShowFooterTemplateLoadTime}}{{.i18n.Tr "page"}}: <strong>{{LoadTimes .PageStartTime}}</st
`Powered by` should be translatable

2019-12-16 01:55 UTC, guillep2k commented on templates/base/footer_content.tmpl
> +			Powered by Gitea {{if (or .ShowFooterVersion .PageIsAdmin)}}{{.i18n.Tr "version"}}: {{AppVer}}{{end}} {{if ShowFooterTemplateLoadTime}}{{.i18n.Tr "page"}}: <strong>{{LoadTimes .PageStartTime}}</st
The whole string should be translatable, because there's no guaranteed word order for all languages (e.g. Japanese 「Giteaを搭載する」).

2019-12-28 13:05 UTC, 6543 commented
@alexanderadam what is the status of this?

2019-12-31 02:24 UTC, 6543 commented
@alexanderadam do you need help?

2020-01-04 18:36 UTC, 6543 commented
I think we should move this to 1.12.0 because @alexanderadam dont respond + this smal improvement block 1.11.0

2020-01-04 18:36 UTC, lafriks commented
I will fix it

2020-01-04 20:04 UTC, closed without merging