Mark review comment as invalidated when file is deleted
go-gitea/gitea pull request #8751
Opened 2019-10-30 14:13 UTC by succcubbus

When deleting a file with review comments these comment are now marked as outdated.

Fixes https://github.com/go-gitea/gitea/issues/5417

2019-10-30 15:11 UTC, ghost requested changes

2019-10-30 15:19 UTC, succcubbus commented on models/issue_comment.go
> +	if err != nil && strings.Contains(err.Error(), "fatal: no such path") {
Why not nested inside the error check?

Just personal preference, because i found that to be more confusing to read.

2019-10-30 15:22 UTC, jaqra commented on models/issue_comment.go
> +	if err != nil && strings.Contains(err.Error(), "fatal: no such path") {
I mean you can write this code **without** error check after:

```go
if err != nil {
    return err
}
```

Will be more clear and logical

2019-10-30 15:24 UTC, succcubbus commented on models/issue_comment.go
> +	if err != nil && strings.Contains(err.Error(), "fatal: no such path") {
The `if` I wrote is more specific and needs to be checked first. Otherwise it is unreachable because the error-`if` always returns, for any error.

2019-10-30 16:20 UTC, lafriks approved these changes

2019-10-31 00:28 UTC, 6543 approved these changes

2019-10-31 11:08 UTC, ghost approved these changes

2019-10-31 17:59 UTC, merged