Fix API deadline removal
go-gitea/gitea pull request #8759
Opened 2019-10-30 21:52 UTC by davidsvantesson

I got a comment by @bobemoe in #8696 and looked more into setting (and resetting) deadline via API. Because the variable is set to be of type "*time.Time" only nil or a full golang time is valid input. 

- This issue fixes so that deadline can be removed in the edit issue and edit pull endpoint by setting it to time zero (0001-01-01T00:00:00Z). 
- Also there was already a comment to the API that is now also handled in the implementation: "If using deadline only the date will be taken into account, and time of day ignored. "

This issue shouldn't be relevant for 1.9 branch but can be backported to 1.10.

2019-10-30 21:59 UTC, lafriks approved these changes

2019-10-31 00:15 UTC, 6543 approved these changes

2019-10-31 00:22 UTC, 6543 commented
we wont need deadline var if we put all together...
```
deadlineUnix = timeutil.TimeStamp(time.Date(form.Deadline.Year(), form.Deadline.Month(), form.Deadline.Day(), 23, 59, 59, 0, form.Deadline.Location()).Unix())
```
but it wont be so readable anymore ... so OK

2019-10-31 05:35 UTC, lunny commented
How about another param `removal` or another router method `DELETE` to do that? It's not friendly to let user use `0001-01-01T00:00:00Z`.

2019-10-31 05:58 UTC, davidsvantesson commented
@lunny Maybe that was why the additional /deadline endpoint was added? 
I think it would make sense to have removal param, but now there is a specific endpoint for it I am not sure about cluttering it more...

2019-10-31 09:06 UTC, bobemoe commented
Hmmm.

I agree setting to `0001-01-01T00:00:00Z`. Whats wrong with using `null`? Infact there is a description on the deadline endpoint "If set to null, the deadline is deleted."

My earlier experiment confirmed that `null` doesn't error so surely its a case of detecting it to trigger removal.

I was wondering why there was a specific endpoint for this single field, I was considering suggesting that once the deadline can be managed through the issue endpoint that we deprecated the then redundant deadline endpoint?

2019-10-31 09:23 UTC, davidsvantesson commented
@bobemoe I think null will be translated to golang `nil`, which would be the same as omitting the deadline. And in that case we don't want to change the deadline. That is why it works for the specific deadline endpoint, becuase there we can allow it to always update the deadline (new date or removed).

So the only think we can do if we want to have simpler way to remove deadline in the update issue endpoint is to add a parameter _unset deadline_ as suggested by lunny. Or we can change the _deadline_ parameter to a text string and then try to parse it (values like "" can then be treated as zero)

2019-11-02 07:02 UTC, lunny requested changes
For a better API usage, I think give a parameter `0000-01-01`.... is tricky.

2019-11-02 08:51 UTC, davidsvantesson commented
> For a better API usage, I think give a parameter `0000-01-01`.... is tricky.

I added parameter _unset_due_date_. 
Should the endpoint `/repos/{owner}/{repo}/issues/{index}/deadline` be marked as deprecated?

2019-11-02 09:45 UTC, lunny commented on routers/api/v1/repo/pull.go
> +	// summary: Update a pull request. If using deadline only the date will be taken into account, and time of day ignored. Deadline can be removed by setting it to "0001-01-01T00:00:00Z".
Need to update.

2019-11-02 09:45 UTC, lunny commented on templates/swagger/v1_json.tmpl
> +        "summary": "Update a pull request. If using deadline only the date will be taken into account, and time of day ignored. Deadline can be removed by setting it to \"0001-01-01T00:00:00Z\".",
As above.

2019-11-02 10:23 UTC, davidsvantesson commented on routers/api/v1/repo/pull.go
> +	// summary: Update a pull request. If using deadline only the date will be taken into account, and time of day ignored. Deadline can be removed by setting it to "0001-01-01T00:00:00Z".
Fixed

2019-11-03 09:24 UTC, lunny approved these changes

2019-11-03 14:41 UTC, 6543 commented
make lgtm work ..

2019-11-03 14:46 UTC, merged