Move release webhook to notification
go-gitea/gitea pull request #8817
Opened 2019-11-04 01:35 UTC by lunny

As title.

2019-11-04 22:57 UTC, 6543 commented
```
mode, _ := models.AccessLevel(doer, rel.Repo)
	if err := webhook.PrepareWebhooks(rel.Repo, models.HookEventRelease, &api.ReleasePayload{
		Action:     api.HookReleaseUpdated,
		Release:    rel.APIFormat(),
		Repository: rel.Repo.APIFormat(mode),
		Sender:     doer.APIFormat(),
	}); err != nil {
		log.Error("PrepareWebhooks: %v", err)
	}
```
exists 3 times only differ in `Action: xy`

does it make sence to move this in a seperate function wich is used by all three funcitons?

2019-11-05 01:38 UTC, lunny commented
@6543 done.

2019-11-05 02:08 UTC, 6543 approved these changes

2019-11-05 02:08 UTC, 6543 commented
CI.restart()

2019-11-05 02:08 UTC, techknowlogick commented
restarted

2019-11-05 02:12 UTC, 6543 requested changes

2019-11-05 02:12 UTC, 6543 commented on modules/notification/webhook/webhook.go
> -	"code.gitea.io/gitea/modules/webhook"
@lunny it works on your current branch but not avter merge!
-> we still need this import

2019-11-05 07:28 UTC, 6543 approved these changes

2019-11-05 08:56 UTC, 6543 commented
@techknowlogick can you reviwe&merge?

2019-11-06 08:15 UTC, zeripath approved these changes

2019-11-06 08:25 UTC, merged