Fix API Bug ( empty assignees )
go-gitea/gitea pull request #8873
Opened 2019-11-07 17:59 UTC by 6543

close #8872

2019-11-07 19:07 UTC, guillep2k reviewed
This just should work, but the function seems now overly complicated. Do you think you can simplify it a little? You could use `util.ExistsInSlice()`, so you can also filter out any duplicates that `multipleAssignees` may have.

2019-11-07 19:17 UTC, 6543 commented
@guillep2k done

2019-11-07 19:52 UTC, guillep2k commented on models/issue_assignees.go
> +	if util.ExistsInSlice("", multipleAssignees) {
My bad! `ExistsInSlice` requires an ordered slice; `IsStringInSlice` performs a linear search.
```suggestion
	if util.IsStringInSlice("", multipleAssignees) {
```

2019-11-07 20:50 UTC, guillep2k reviewed
I think you could just check if multipleAssignees is exactly [""], which is the bug you're trying to fix. And add oneAssignee if != "" and not already in the array. So, no loop needed. Also, if I recall correctly, GetUserIDsByNames() already checks for empty input, so there should be no need to check it here too.

2019-11-08 03:38 UTC, guillep2k commented on models/issue_assignees.go
> +	if multipleAssignees[0] != "" {
```suggestion
	if len(multipleAssignees) > 0 && multipleAssignees[0] != "" {
```

2019-11-08 04:21 UTC, guillep2k approved these changes

2019-11-08 12:24 UTC, lunny requested changes

2019-11-08 12:24 UTC, lunny commented on models/issue_assignees.go
> +	"code.gitea.io/gitea/modules/util"
wrong import order

2019-11-08 12:28 UTC, 6543 commented on models/issue_assignees.go
> +	"code.gitea.io/gitea/modules/util"
@lunny 

standart

Gitea

Thirdparty?

2019-11-09 00:26 UTC, lunny commented
How about add a test for function `MakeIDsFromAPIAssigneesToAdd`?

2019-11-10 00:30 UTC, 6543 commented
@lunny tests are added

2019-11-10 02:23 UTC, lunny approved these changes

2019-11-10 04:49 UTC, 6543 commented
@lunny I'm ready to merge if you are ..

2019-11-10 08:07 UTC, merged