Fix public activity showing private repos
go-gitea/gitea pull request #892
Opened 2017-02-10 17:32 UTC by thehowl

Fixes #811

2017-02-10 22:36 UTC, ethantkoenig requested changes

2017-02-10 22:36 UTC, ethantkoenig commented on models/repo.go
> +			e.Where("repo_id = ?", repo.ID).Cols("is_private").Update(&Action{
We should check the returned `error`

2017-02-10 22:36 UTC, ethantkoenig commented on models/repo.go
> +		}
Shouldn't we also mark the actions as public if the repo becomes public?

2017-02-10 22:43 UTC, thehowl commented on models/repo.go
> +		}
I've thought about that, and I am not sure whether having a feed that adds new events "in the past" would make much sense.

2017-02-10 22:53 UTC, ethantkoenig commented on models/repo.go
> +		}
Fair enough

2017-02-10 22:53 UTC, ethantkoenig commented
LGTM

2017-02-11 06:46 UTC, strk commented
It would be good to add tests for bugfixes, had you looked at what it would take ?

2017-02-11 07:27 UTC, lunny requested changes

2017-02-11 07:27 UTC, lunny commented on models/repo.go
> +				IsPrivate: true,
`IsPrivate: repo.IsPrivate`, ? And remove the `if repo.IsPrivate` ?

2017-02-11 07:34 UTC, thehowl commented on models/repo.go
> +				IsPrivate: true,
https://github.com/go-gitea/gitea/pull/892#discussion_r100639602

2017-02-11 07:44 UTC, lunny commented on models/repo.go
> +				IsPrivate: true,
?

2017-02-11 08:10 UTC, thehowl commented on models/repo.go
> +				IsPrivate: true,
We already discussed this in the linked comment. As I said, "I am not sure whether having a feed that adds new events "in the past" would make much sense.".

2017-02-11 08:12 UTC, thehowl commented
@strk, will look into tests later today

2017-02-11 08:13 UTC, lunny commented on models/repo.go
> +				IsPrivate: true,
OK.

2017-02-11 08:13 UTC, lunny approved these changes

2017-02-11 08:13 UTC, lunny commented
LGTM

2017-02-11 09:32 UTC, thehowl commented
Added a test, as requested by @strk.

2017-02-11 09:51 UTC, strk commented
LGTM, thanks for the test !

2017-02-11 10:57 UTC, merged