Githook highlighter
go-gitea/gitea pull request #8932
Opened 2019-11-12 11:03 UTC by Konctantin

Shell code highlighter for GitHook editor
![image](https://user-images.githubusercontent.com/82728/68666326-c5137580-0554-11ea-82b8-3ca8cb10aca1.png)
![image](https://user-images.githubusercontent.com/82728/68666502-16bc0000-0555-11ea-8bc1-01a476cffd5c.png)

2019-11-12 18:47 UTC, zeripath approved these changes

2019-11-12 19:06 UTC, sapk approved these changes

2019-11-12 19:25 UTC, zeripath commented
Sigh... TestGitHubDownloadRepo is failing because someone touched one of the issues it looks at.

2019-11-14 20:35 UTC, zeripath commented
@Konctantin - I think we're gonna merge #8973 before this one which will almost certainly conflict with this. Sorry about this.

2019-11-14 20:55 UTC, Konctantin commented
Ok, then after merge #8973 i will fix the conflict

2019-11-14 21:42 UTC, zeripath commented
Heya! Yeah it did conflict but if you can fix we should be able to get this merged this evening

2019-11-15 05:39 UTC, lunny requested changes

2019-11-15 05:39 UTC, lunny commented on web_src/js/index.js
> -    // Options
Why deleted these functions?

2019-11-15 06:20 UTC, Konctantin commented on web_src/js/index.js
> -    // Options
But I didn’t delete anything

2019-11-15 06:32 UTC, lunny approved these changes

2019-11-15 06:56 UTC, merged

2019-11-15 07:34 UTC, Konctantin commented
Thanks

2019-11-15 15:16 UTC, sapk commented
@Konctantin Thank you for your first contribution.