efactor submit review
go-gitea/gitea pull request #8954
Opened 2019-11-13 09:41 UTC by lunny

Please check the following:

1. Make sure you are targeting the `master` branch, pull requests on release branches are only allowed for bug fixes.
2. Read contributing guidelines: https://github.com/go-gitea/gitea/blob/master/CONTRIBUTING.md
3. Describe what your pull request does and which issue you're targeting (if any)

**You MUST delete the content above including this line before posting, otherwise your pull request will be invalid.**

2019-11-13 12:35 UTC, 6543 approved these changes
review code realy need some work :O

2019-11-13 12:36 UTC, 6543 commented
I also found inconsitenc how review comments and especialy the comments to that one only show up at normal comment page or only in file diff ?!?
(with and without this PR so its more a thing for another PR ...)

2019-11-13 13:04 UTC, lunny commented
There are three places to display code review comments. Dashboard feed ( from `action` table), pull request(issue) comments ( from `comment` table) and pull request files (from `comment` table).

2019-11-13 15:08 UTC, guillep2k commented
@lunny a notification for each comment seems like too much, and some context will be lost. For example:

Head comment: Mike, I'm especially concerned about X.
At line 1234: Fix this and that.
At line 5553: As above.

Users will get three mails, of which one mail says only "as above".

Also, the UI will just use the latest, so it would be pointless in that case.

2019-11-13 15:25 UTC, guillep2k requested changes

2019-11-13 15:25 UTC, guillep2k commented on models/review.go
> +		if _, err := sess.ID(review.ID).Cols("content, typpe").Update(review); err != nil {
```suggestion
		if _, err := sess.ID(review.ID).Cols("content, type").Update(review); err != nil {
```

2019-11-13 15:45 UTC, lunny commented
`NotifyPullRequestReview` will be invoked only once, it's strange you will receive 3 emails. I will check it again.

2019-11-13 20:27 UTC, guillep2k commented
> 
> 
> `NotifyPullRequestReview` will be invoked only once, it's strange you will receive 3 emails. I will check it again.

I misread your PR description; three records in `action` is OK. I thought you meant three notifications.

2019-11-13 23:56 UTC, guillep2k reviewed
@lunny It is indeed more manageable. 👍

Only two corrections and it will be OK. Only one mail is sent (as it should) and multiple `action` records are created properly in the dashboard. It will be very easy in a later PR to add the code review comments to the mail template (as I have it already worked out).

2019-11-13 23:56 UTC, guillep2k commented on modules/notification/action/action.go
> +			Content:   fmt.Sprintf("%d|%s", review.Issue.Index, strings.Split(content, "\n")[0]),
```suggestion
			Content:   fmt.Sprintf("%d|%s", review.Issue.Index, strings.Split(comm.Content, "\n")[0]),
```

2019-11-14 01:41 UTC, lunny commented
@guillep2k done.

2019-11-14 02:57 UTC, guillep2k approved these changes

2019-11-14 02:57 UTC, merged