WIP: Start to add tests for modules/base/tool
go-gitea/gitea pull request #90
Opened 2016-11-06 00:54 UTC by metalmatze

I started to write some tests for modules/base/tool.
I'm going to add more tomorrow.

2016-11-07 08:10 UTC, bkcsoft requested changes
otherwise awesome work 😄

2016-11-07 08:10 UTC, bkcsoft commented on modules/base/tool_test.go
> +	if result := ShortSha("veryverylong"); result != "veryverylo" {
please use a hex-value when testing hash-functions 🙂

2016-11-07 08:10 UTC, bkcsoft commented on modules/base/tool_test.go
> +		t.Errorf("got the wrong sha1sum for string foobar: %s", result)
"wrong short sha1sum"?

2016-11-07 08:10 UTC, bkcsoft commented on modules/base/tool_test.go
> +	if hash := HashEmail("lunny@gitea.io"); hash != "1b6d0c0e124d47ded12cd7115addeb11" {
I'd refrain against using real addresses when not necessary, this is why ’example.com’ exists 🙂

2016-11-07 20:28 UTC, metalmatze commented on modules/base/tool_test.go
> +	if result := ShortSha("veryverylong"); result != "veryverylo" {
I thought this was a hash-function too. But if you look closer it only shortens a string. Pretty bad function naming. But I don't want to change the API with the tests. That should be a different PR.

2016-11-07 20:36 UTC, metalmatze commented on modules/base/tool_test.go
> +	if result := ShortSha("veryverylong"); result != "veryverylo" {
https://github.com/go-gitea/gitea/pull/90/commits/7d6e0338085a7c066aa1373536ebd88f1837b839

2016-11-07 21:13 UTC, jbub commented
Hey @metalmatze, great work on adding tests, i have noticed that you are in some cases repeating and duplicating assert calls (for example `TestTruncateString`, `TestFileSize` or `TestEllipsisString`), you can remove some of the repetitions using table driven tests http://dave.cheney.net/2013/06/09/writing-table-driven-tests-in-go, in go 1.7 it can even speedup the tests by parallelizing them http://golang.rakyll.org/parallelize-test-tables/

2016-11-07 21:26 UTC, strk commented on modules/base/tool_test.go
> +		AvatarLink("gitea@example.com"),
If you need a test for a really federated avatar, try strk@kbt.io

2016-11-07 21:39 UTC, metalmatze commented on modules/base/tool_test.go
> +		AvatarLink("gitea@example.com"),
Doesn't make a difference for the test. right?

2016-11-07 22:23 UTC, metalmatze commented
Hey @jbub. Thanks for the hint.
It wasn't much work for me to duplicate those lines. Just a shortcut.
Parallelizing sounds pretty interesting though! :rocket:

2016-11-07 22:25 UTC, metalmatze commented
I'm done for now. I think we could merge this and add more tests in another PR. This one is pretty big anyway. Updated all the stuff @bkcsoft said. :+1: 

LGTY? :smile:

2016-11-08 05:55 UTC, strk commented on modules/base/tool_test.go
> +		AvatarLink("gitea@example.com"),
well, this one isn't really testing the *federated* part (I've seen packages just prefixing the hash with "cdn.libravatar.org" and be happy with it, it's not our case, we're actually doing the DNS lookups)

2016-11-08 05:56 UTC, strk commented
LGTM

2016-11-08 09:10 UTC, andreynering commented
Awesome work, LGTM

2016-11-08 09:27 UTC, bkcsoft commented on modules/base/tool_test.go
> +	if result := ShortSha("veryverylong"); result != "veryverylo" {
until it's fixed, please use ShaSums ;)

2016-11-08 09:30 UTC, bkcsoft commented
LGTM

2016-11-08 09:30 UTC, bkcsoft approved these changes

2016-11-08 09:30 UTC, merged