Don't rewrite non-gitea public keys
go-gitea/gitea pull request #906
Opened 2017-02-11 14:37 UTC by lunny

This will fix #424

2017-02-12 08:03 UTC, bkcsoft requested changes

2017-02-12 08:03 UTC, bkcsoft commented on models/ssh_key.go
> +		f.Close()
can we `defer f.Close()` instead?

2017-02-12 08:41 UTC, lunny commented on models/ssh_key.go
> +		f.Close()
No. We have to close the file and then rename it from tmp to normal.

2017-02-12 08:41 UTC, lunny commented
It seems drone down?

2017-02-12 12:29 UTC, strk commented
If I read the code correctly you're using full path to the gitea binary as the "tag", correct ?
This means if you change the gitea path and rewrite authorized keys you end up with duplicate keys, is that correct ? How does sshd behave in that case ? Is that something we need to handle somehow ? For example logging a warning if a possibly conflicting key is found ?

2017-02-12 12:44 UTC, travnick commented
I'd like to suggest to add new config option like "KEY_PREFIX_ID".
Then use prefix for keys like "gitea-KEY_PREFIX_ID". Now you are free to move around gitea without issues with duplicated keys.

By default KEY_PREFIX_ID should be an UUID that is generated during installation.

2017-02-12 12:53 UTC, lunny commented
I did not consider to move the place of the Gate binary.

2017-02-12 13:06 UTC, strk commented
As a contribution for the discussion, gitolite marks its section
with start and end block comments:
```
# gitolite start
...
# gitolite end
```

2017-02-12 13:25 UTC, strk commented
The prefix configuration would suffer from the same issue: if 
it changes, the match would fail.

Let's say this version LGTM - can be improved later.
At least this version does not require changing existing deploys,
and should work as long as the SSH access to repos work.

2017-02-12 15:17 UTC, bkcsoft commented on models/ssh_key.go
> +		f.Close()
you can still defer `f.Close()`, it will just not do anything if it's already closed :)

2017-02-12 15:27 UTC, bkcsoft commented
I would read the file line-by-line, appending each to the list of keys we wanna write. Sort the list, step through and remove duplicates.

Pseudo-code as fuck because I'm tired :trollface: 
```go
keys := getListsAsStringSlice()
f, _ := os.Open("authorized_keys")
for line := f.ReadLine() {
  keys := append(keys, line)
}
strings.Sort(keys)
outKeys := []string{keys[0]}
for i := 1; i < len(keys) - 1; i++ {
  if keys[i] != keys[i-1] {
    outKeys = append(outKeys, keys[i])
  }
}
f.Seek(0, io.SeekStart)
f.Write(outKeys)
```

2017-02-14 02:32 UTC, lunny commented
@bkcsoft You have to consider backup if the machine is down when it's writing keys. So `rename` is not an ignoreable step. Or maybe we need `copy` not `rename`.

2017-02-14 12:20 UTC, lunny commented on models/ssh_key.go
> +		f.Close()
So it's no need to use `defer f.Close()`.

2017-02-14 12:22 UTC, lunny commented
@travnick do you mean on the comment?

2017-02-14 13:09 UTC, travnick commented
@lunny what are you asking about exactly?

2017-02-14 22:49 UTC, bkcsoft commented on models/ssh_key.go
> +		f.Close()
`defer f.Close()` is good practice, if I'm not familiar with the code-base I'd assume that it defers it and then we have a bug 🙁

2017-02-14 22:50 UTC, bkcsoft commented
@lunny `copy` sounds better :)

2017-02-26 23:13 UTC, tboerger commented on models/ssh_key.go
> +		f.Close()
:+1: for defer, it's common practice to make sure the file gets always closed.

2017-02-26 23:13 UTC, tboerger commented on models/ssh_key.go
> +		f.Close()
That way you can also skip all the `f.Close()` calls.

2017-02-27 04:33 UTC, lunny commented on models/ssh_key.go
> +		f.Close()
done.

2017-02-27 04:34 UTC, lunny commented
@tboerger @bkcsoft @strk please confirm.

2017-02-27 05:40 UTC, bkcsoft requested changes

2017-02-27 05:40 UTC, bkcsoft commented on models/ssh_key.go
> +				scanner.Scan()
This will skip every other line no?

2017-02-27 06:18 UTC, tboerger commented on models/ssh_key.go
> +				scanner.Scan()
This will skip always the next line if the current line is the prefix

2017-02-27 08:14 UTC, bkcsoft approved these changes

2017-02-27 09:22 UTC, tboerger commented
Isn't it easier to have a start and an end marker line gitolite?

2017-02-27 10:01 UTC, lunny commented
It's also easy to this one. but it seems no need to add `end`.

2017-02-27 10:18 UTC, tboerger commented
But this implementation is harder to understand, at least that's my opinion.

2017-02-27 10:59 UTC, lunny commented
But it works. We can improve it in v1.2.

2017-02-27 13:38 UTC, strk commented on models/migrations/v21.go
> +	err = x.Iterate(new(PublicKey), func(idx int, bean interface{}) (err error) {
Is this assuming all authorized_keys belong to gitea ?

2017-02-27 13:40 UTC, lunny commented on models/migrations/v21.go
> +	err = x.Iterate(new(PublicKey), func(idx int, bean interface{}) (err error) {
If it's an old gitea, of course because every time you add a new public key. it will remove other non-gitea public key.

2017-02-27 13:40 UTC, lunny commented on models/migrations/v21.go
> +	err = x.Iterate(new(PublicKey), func(idx int, bean interface{}) (err error) {
For a new gitea, this will not be executed.

2017-02-27 20:16 UTC, bkcsoft commented
> We can improve it in v1.2.

No, we'd have to change for v2.0 since that would be a breaking change

2017-02-27 23:52 UTC, lunny commented
Where is the breakage?

2017-03-02 16:05 UTC, bkcsoft commented
The breakage is in the expected behaviour. Anyhow, this is LGTM to me 🙂

2017-03-02 16:36 UTC, merged