move semantic.dropdown.custom.js to webpack
go-gitea/gitea pull request #9064
Opened 2019-11-18 19:41 UTC by silverwind

This moves the file to webpack. Given that the language selector is present on all pages, it doesn't really make sense to lazy-load it.

Also disabled a annoying linter rule which insisted that imports can not contain a file extension.

Fixes: https://github.com/go-gitea/gitea/issues/8971

2019-11-18 19:45 UTC, silverwind commented
Both `web_src/vendor/gitgraph.js` and `web_src/vendor/semantic.dropdown` are actually customized versions. I wonder whether it would be wiserr to move them outside this vendor folder and add a comment to each about the customizations instead.

2019-11-18 22:59 UTC, zeripath approved these changes

2019-11-18 23:40 UTC, lafriks approved these changes

2019-11-19 00:34 UTC, lunny commented
/public/js/index.js will be increased from 58KB to 107KB after this PR. Is this necessary?

2019-11-19 00:35 UTC, lunny requested changes
Don't merge before we finished the discuss about the size increase.

2019-11-19 08:08 UTC, silverwind commented
My understanding is that that file adds some a11y attributes to dropdown buttons (but not `<select>` style buttons. Notably, this includes the language selector in the footer.

I think the code in the file duplicates with code bundled in `/vendor/plugins/semantic/semantic.min.js`, so we probably load almost the same code twice which is very bad.

I do wonder if we can maybe do away with this duplication and just manually add the a11y attribute ourselfs after render, eliminating the duplication. Maybe @Jookia can comment.

2019-11-19 08:13 UTC, Jookia commented
No, it requires changes to Semantic UI's code which is why it's duplicated.

2019-11-19 08:27 UTC, silverwind commented
You don't think we can just tack on a few `aria-*` attributes and get most of the features?

Another alternative may be to do a custom build of semantic JS with those changes built in.

2019-11-19 17:50 UTC, Jookia commented
No. It (and future accessibility improvements) need to modify Semantic UI's code.
The simplest solution would be to just unminify Semantic UI's code and merge the accessibility changes in and minify that.

2019-11-19 17:55 UTC, silverwind commented
Hmm that sounds like a plan. Could load semantic's JS from npm and apply our changes via https://github.com/ds300/patch-package.

2019-11-19 18:03 UTC, silverwind commented
Actually, `semantic-ui` package is [broken](https://github.com/Semantic-Org/Semantic-UI/issues/6818) on Node.js 12 and higher, it's not an option to add it as a dependency. Maybe if we switch to https://github.com/fomantic/Fomantic-UI.

2019-11-19 18:04 UTC, silverwind commented
@lunny regarding the size concern: we already load the unminified version at over 100kB, so strictly speaking, this is a improvement in bundle size. We should decide later what we do with semantic-ui, it will not be easy.

2019-11-19 18:05 UTC, Jookia commented
You can just copy in the unminified semantic.js from upstream's release without going through node

2019-11-19 18:08 UTC, silverwind commented
This one? https://github.com/Semantic-Org/Semantic-UI/blob/master/dist/semantic.js

Do you by change have a `.patch` against it?

2019-11-19 18:12 UTC, Jookia commented
Yes, that one- but at the revision v2.1.8 (or whatever Semantic-UI we're using)
And no, but all you have to do is splice in the semantic.dropdown.js code as the semantic.js contains it verbatim

2019-11-19 18:16 UTC, silverwind commented
Ok, I will attempt that later, it should not hinder this PR.

2019-11-19 18:47 UTC, silverwind commented
Rebased and reorganized files as mentioned in https://github.com/go-gitea/gitea/pull/9064#issuecomment-555178284. No functional changes, only comment additions.

2019-11-19 22:43 UTC, zeripath commented
@silverwind I think it's possible to rebase on to fomantic-ui but there are a few subtle changes that have been made that would require someone with more skill than me to fix.

If we were to base on fomantic we could even go as far as building on their less with themes etc and this drop the !important from our less...

2019-11-20 17:00 UTC, silverwind commented
@lunny care to unblock this? See my response https://github.com/go-gitea/gitea/pull/9064#issuecomment-555632878.

My point is that this change is a overall net reduction of JS size by around 50kB because we currently load `semantic.dropdown.custom.js` in a (to my understanding) blocking manner before `index.js`.

2019-11-20 17:02 UTC, silverwind commented
@zeripath @Jookia ideally we could upstream the a11y changes into `fomantic-ui` and eventually switch to that.

2019-11-21 13:16 UTC, lunny approved these changes

2019-11-21 17:18 UTC, silverwind commented
Waiting on https://github.com/go-gitea/gitea/pull/9047 to land, then I'll do another rebase and hope the CI gets its stuff together.

2019-11-21 22:00 UTC, silverwind commented
Ready to merge.

2019-11-21 23:30 UTC, merged