Fixed a reCAPTCHA error
go-gitea/gitea pull request #9079
Opened 2019-11-19 19:49 UTC by mzch

Please check the following:

1. Make sure you are targeting the `master` branch, pull requests on release branches are only allowed for bug fixes.
  **YES**
2. Read contributing guidelines: https://github.com/go-gitea/gitea/blob/master/CONTRIBUTING.md
  **YES**
3. Describe what your pull request does and which issue you're targeting (if any)
  This will fix reCAPTCHA error.

**You MUST delete the content above including this line before posting, otherwise your pull request will be invalid.**

2019-11-19 19:52 UTC, techknowlogick submitted a review, later dismissed
The default value is `RECAPTCHA_URL = https://www.google.com/recaptcha/` so this will fail for those who have set this to something else.

2019-11-19 20:00 UTC, baxandrei commented
@techknowlogick see this: https://github.com/go-gitea/gitea/issues/7870#issuecomment-555566306

2019-11-19 20:05 UTC, lafriks requested changes

2019-11-19 20:05 UTC, lafriks commented on modules/recaptcha/recaptcha.go
> +const apiURL = "/recaptcha/api/siteverify"
```suggestion
const apiURL = "api/siteverify"
```

2019-11-19 20:06 UTC, lafriks commented
You are right, there is bug, see:
https://play.golang.org/p/9wG1S8TvS33

I recommend in review correct solution

2019-11-19 21:00 UTC, lafriks approved these changes

2019-11-19 21:01 UTC, jolheiser approved these changes

2019-11-19 22:33 UTC, zeripath commented
Oh damn. Mea culpa. Could we fix urljoin instead/aswell? It's crazy that it's doing this. It absolutely should not be doing this as it will likely be causing other bugs too.

2019-11-19 23:03 UTC, mzch commented
I found another fix.

2019-11-19 23:03 UTC, closed without merging

2019-11-19 23:08 UTC, lafriks commented
@zeripath it is doing everything correctly imho

2019-11-20 07:03 UTC, baxandrei commented
I'm curious to see the solution, where can I find it?

2019-11-20 09:38 UTC, mzch commented
@baxandrei I think it comes from specs of ResolveReference()