Add self-hosted Gitlab migration support
go-gitea/gitea pull request #9096
Opened 2019-11-20 16:36 UTC by aqtrans

This extends [PR#9084](https://github.com/go-gitea/gitea/pull/9084) to allow migrating from self-hosted Gitlab instances. 

Detection is based on adding a '#gitlab' fragment to the end of the given Clone Address.

2019-12-04 06:39 UTC, maicWorkGithub commented
would you add an option `ignore certificate`?

2020-04-01 19:30 UTC, 6543 commented
no stale the main pull is not ready jet ...

2020-04-19 16:23 UTC, 6543 commented
@aqtrans can you rebase this pull?
since #9084 got merged?

2020-04-19 16:31 UTC, 6543 commented
you may want to wait for  #11136 to be merged :)

2020-04-19 20:02 UTC, 6543 commented
@aqtrans rebased for you. since I looked throu gitlab client's changes ... the lib update is only needed for reviews (#11137)

do you have a own gitlab instance to test with?

2020-04-19 20:03 UTC, 6543 commented on modules/migrations/gitlab.go
> +//   To allow self-hosting Gitlab instances, this matches based on the Host or a '#gitlab' fragment
```suggestion
// To allow self-hosting Gitlab instances, this matches based on the Host or a '#gitlab' fragment
```

2020-04-19 23:03 UTC, 6543 commented on modules/migrations/gitlab.go
> +//   To allow self-hosting Gitlab instances, this matches based on the Host or a '#gitlab' fragment
```suggestion
// To allow self-hosting Gitlab instances, this matches based on the Host or a '#gitlab' fragment
```

2020-04-19 23:04 UTC, 6543 commented on modules/migrations/gitlab.go
> +//   To allow self-hosting Gitlab instances, this matches based on the Host or a '#gitlab' fragment
again ... rebase deleted it somehow

2020-04-19 23:23 UTC, 6543 approved these changes
found a way to test it - worked just fine 🎉

2020-04-20 00:05 UTC, mrsdizzie commented
I think adding #gitlab to the URL for detection feels like a confusing interface -- we should just add a drop down menu or something even if gitlab is the only option for now. I know there should be gitea/gogs at some point too (there is a PR for it) and maybe/hopefully more in the future.

2020-04-20 00:08 UTC, 6543 requested changes
x

2020-04-25 20:48 UTC, 6543 commented
@aqtrans are you on this?

2020-04-29 01:08 UTC, 6543 commented
@techknowlogick can we add this to v1.12 since it works only UI has change ...

2020-04-29 03:43 UTC, guillep2k commented
I agree with @mrsdizzie here. There should be either a drop-down or a list of radio buttons (auto-detect, GitHub, GitLab, ... others to come). Slight problem here is that GitHub doesn't allow for a custom host address, which would be interesting for consistency (but it can't be helped since the api is provided by GitHub itself). Either way, IMHO it should not be a fragment of the URL. 😁

2020-04-29 04:25 UTC, techknowlogick commented
another +1 for what @mrsdizzie said. In GitLab they have a migration page where you first select the forge type (gitlab, github, gitea, etc..) and then it will have different settings based on what you've selected (for example github we may want to have different help text about personal tokens needed for migration), and we could also split mirror and migration as it has lead to confusion in past.

@guillep2k our GitHub migration logic would also in theory support github enterprise too at a custom URL.

I am thankful for this PR as it has brought up these discussions. If it goes in I wouldn't be upset, and so I won't be a blocker, but I think the high-level needs to be reviewed first. Maybe it goes in temporarily until we can get improve the migration experience?

2020-04-30 02:06 UTC, lunny commented on modules/migrations/gitlab.go
> +	if strings.EqualFold(u.Fragment, "gitlab") && opts.AuthUsername != "" {
For self-hosted gitlab, we need a new option on the UI to let user select.

2020-05-02 08:22 UTC, lunny commented
A new wizard UI is better. I propose we have a migration type selection page before current.
There are four migration types you can chose:

- Mirror from a git service
- Migrate from a github service
- Migrate from a gitlab service
- Migrate from other git service

2020-07-18 17:15 UTC, 6543 commented
no stale just nobody wants to contribute the frontend 😅

2020-08-25 21:27 UTC, capi commented
It would be great if this could be merged with the #gitlab fragment. I agree it's not "good UI" but at least it would work and I'm eagerly waiting to migrate some projects from my self-hosted Gitlab to Gitea. Thanks in advance!

2020-08-25 22:06 UTC, 6543 commented
@aqtrans do you have time, I wont for in the next weeks ...

2020-08-28 01:36 UTC, closed without merging