Configurable SSH cipher suite
go-gitea/gitea pull request #913
Opened 2017-02-12 11:43 UTC by spacetourist

As requested, merging change from Gogs.io

2017-02-12 11:51 UTC, lunny commented
LGTM

2017-02-12 14:56 UTC, bkcsoft requested changes

2017-02-12 14:56 UTC, bkcsoft commented on conf/app.ini
> +; Choose the ciphers to support for SSH connections
Please make it clear that this only affects Built-In SSH-server

2017-02-12 14:56 UTC, bkcsoft commented on routers/init.go
> +               log.Info("SSH server started on %s:%v. Cipher list (%v)", setting.SSH.ListenHost, setting.SSH.ListenPort, setting.SSH.ServerCiphers)
ListenPort should use `%d` not `%v`

2017-02-12 14:57 UTC, bkcsoft commented
Not exactly happy about having configs that only affect the build-in server, but for this it's hard to do otherwise 🙁

2017-02-12 18:24 UTC, ethantkoenig requested changes

2017-02-12 18:24 UTC, ethantkoenig commented on routers/init.go
> +               ssh.Listen(setting.SSH.ListenHost, setting.SSH.ListenPort, setting.SSH.ServerCiphers)
Please use tabs for indentation

2017-02-12 21:39 UTC, aaronjwood commented
Can I suggest that you prioritize AES-GCM above everything else? I think an authenticated encryption mode should be first on everyone's list.

It might be nice to prevent the use of the arcfour suites entirely. Since most modern chips have the AES-NI instruction set to accelerate AES operations most people would see better performance too.

2017-02-14 02:21 UTC, lunny commented
@aaronjwood Yes. I think the default values should be security enough.

2017-02-24 06:27 UTC, lunny commented
It seems no response here, let's move it to v1.2

2017-02-25 19:29 UTC, evantbyrne commented
According to the Go SSH documentation on [ssh.Config](https://godoc.org/golang.org/x/crypto/ssh#Config),

```
// The allowed cipher algorithms. If unspecified then a sensible
// default is used.
Ciphers []string
```

So it might be best to leave that ini option undefined by default, unless this cipher set differs from the default Go one and there is a specific rationale for such.

2017-02-27 00:20 UTC, tboerger commented on modules/setting/setting.go
> +	SSH.ServerCiphers = sec.Key("SSH_SERVER_CIPHERS").Strings(",")
Requires a default value?

2017-03-01 20:37 UTC, cdslashetc commented on conf/app.ini
> +; Choose the ciphers to support for SSH connections
```
; For built-in SSH server only, choose the ciphers to support for SSH connections,
; for system SSH this setting has no effect
```

2017-03-16 12:05 UTC, strk commented
It's somewhat ironic that Gogs is ahead of the community fork made to speed things up...
How about reviewers are less picky unless they have time to fix things themselves ?
I'll start with my LGTM here

2017-03-17 02:21 UTC, lunny commented
As @evantbyrne said, keep the default as Go did maybe a good choice. @spacetourist maybe you can change this?

2017-04-27 09:46 UTC, sapk commented
Any news ?

2017-04-27 09:54 UTC, lunny commented
If @evantbyrne no response. I think maintainers could do something.
I think this PR needs two fixes:
1. add more comment as @cdslashetc said.
2. change the default value as @evantbyrne said

2017-04-27 10:04 UTC, sapk commented
+ fix indentation

2017-10-18 21:44 UTC, lafriks commented
@bkcsoft @ethantkoenig fixed

2017-10-18 22:42 UTC, ethantkoenig approved these changes

2017-10-21 13:00 UTC, bkcsoft approved these changes

2017-10-21 13:06 UTC, lafriks commented
Make LG-TM work again

2017-10-21 13:13 UTC, merged

2017-10-21 16:27 UTC, ncwgf commented
This patch will report below error using SSH to `git fetch` who is not from fresh install
because `conf/app.ini` missed config `SSH_SERVER_CIPHERS`
problem solved by manually copy the setting from this commit to `conf/app.ini`
```
git fetch gitea
FATAL ERROR: Couldn't agree a client-to-server cipher (available: )
fatal: Could not read from remote repository.
```