feat: support search bar on star tab of user profile.
go-gitea/gitea pull request #917
Opened 2017-02-13 01:22 UTC by appleboy

2017-02-13 02:35 UTC, lunny commented
LGTM

2017-02-13 02:54 UTC, lunny requested changes

2017-02-13 02:54 UTC, lunny commented on models/repo.go
> +	if opts.Starred {
Maybe you could see https://github.com/go-gitea/gitea/blob/master/models/repo.go#L2156

2017-02-13 03:53 UTC, appleboy commented on models/repo.go
> +	if opts.Starred {
https://github.com/go-gitea/gitea/pull/917/commits/34de9e9ab44b4286722662a1ef3119deae814145

2017-02-13 04:24 UTC, lunny approved these changes

2017-02-14 06:33 UTC, tboerger commented on models/repo.go
> +			And("LOWER(lower_name) LIKE ?", "%"+opts.Keyword+"%")
Need lower here? Sounds like it should already be lower

2017-02-14 06:33 UTC, tboerger commented
I have not tested it but beside the single comment LGTM

2017-02-14 06:35 UTC, lunny commented on models/repo.go
> +			And("LOWER(lower_name) LIKE ?", "%"+opts.Keyword+"%")
^

2017-02-14 07:00 UTC, appleboy commented on models/repo.go
> +			And("LOWER(lower_name) LIKE ?", "%"+opts.Keyword+"%")
Done

2017-02-14 07:00 UTC, appleboy commented on models/repo.go
> +			And("LOWER(lower_name) LIKE ?", "%"+opts.Keyword+"%")
Waiting testing.

2017-02-14 07:26 UTC, lunny commented
let L-G-T-M work

2017-02-14 07:28 UTC, merged