Small optimization for getTeamIDs
go-gitea/gitea pull request #919
Opened 2017-02-13 03:21 UTC by lunny

The latest XORM has supported only Find IDs. So let's use the new method.

2017-02-13 04:25 UTC, appleboy approved these changes

2017-02-13 04:25 UTC, appleboy commented
LGTM

2017-02-14 01:48 UTC, ethantkoenig requested changes

2017-02-14 01:48 UTC, ethantkoenig commented on models/org.go
> +func (org *User) getOrgTeamIDs(e Engine, userID int64) ([]int64, error) {
Should this be `getUserTeamIDs` (to match `GetUserTeamIDs`)?

2017-02-14 01:48 UTC, ethantkoenig commented on models/org.go
> +		Asc("`user`.name").
Why is this `ORDER BY` necessary? We are only looking for one user (i.e. the user with ID `userID`)

Plus, if we get rid of the `ORDER BY`, we won't need to join with the `user` table :smile:

2017-02-14 03:25 UTC, lunny commented on models/org.go
> +func (org *User) getOrgTeamIDs(e Engine, userID int64) ([]int64, error) {
done.

2017-02-14 03:25 UTC, lunny commented on models/org.go
> +		Asc("`user`.name").
done.

2017-02-14 03:36 UTC, ethantkoenig approved these changes

2017-02-14 03:36 UTC, ethantkoenig commented
LGTM

2017-02-14 03:46 UTC, merged