Make consistent links to repository in the Slack/Mattermost notificiations
go-gitea/gitea pull request #9205
Opened 2019-11-29 07:04 UTC by lafriks

Fixes #9195

2019-11-29 07:20 UTC, guillep2k approved these changes

2019-11-29 07:59 UTC, lunny approved these changes

2019-11-29 09:24 UTC, cornelk commented
This fixes the link to the repo but leaves the comment links broken:

![1575019364_1722_29112019_](https://user-images.githubusercontent.com/3045857/69858467-06ce4b00-12cd-11ea-9c6d-5b075912b9f5.png)

2019-11-29 09:53 UTC, lunny requested changes
per @cornelk said

2019-11-29 11:44 UTC, lafriks commented
That is a separate issue not related to this PR

2019-11-29 12:00 UTC, lafriks commented
And it does work in Slack:
![image](https://user-images.githubusercontent.com/165205/69867788-8994dd00-12b0-11ea-80fb-77dbc92cd462.png)

2019-11-29 12:09 UTC, 6543 approved these changes

2019-11-29 15:56 UTC, lunny approved these changes

2019-11-30 10:23 UTC, merged

2019-11-30 10:25 UTC, lafriks commented
@cornelk Please submit separate issue for mattermost links