Batch updates for issues
go-gitea/gitea pull request #926
Opened 2017-02-14 01:09 UTC by ethantkoenig

#868

2017-02-14 22:39 UTC, bkcsoft commented
I don't like having `Add Label` and `Remove Label` split... Otherwise I have no comments, L-G-T-M :)

2017-02-14 22:41 UTC, bkcsoft requested changes
Please don't do this 😢

2017-02-14 22:41 UTC, bkcsoft commented on routers/repo/issue.go
> +func UpdateIssues(ctx *context.Context) {
Ooh god please no 😱

2017-02-15 01:24 UTC, ethantkoenig commented on routers/repo/issue.go
> +func UpdateIssues(ctx *context.Context) {
So do you want
- separate functions for milestones/labels/assignees, each of which can handle both a single or multiple issues?
- keep the pre-existing functions milestones/labels/assignees (which can only handle a single issue), and introduce 3 new milestones/labels/assignees for multiple issues?

Also, what is wrong with what I did? I don't mean to argue, I just want to learn.

2017-02-15 01:34 UTC, bkcsoft commented on routers/repo/issue.go
> +func UpdateIssues(ctx *context.Context) {
Preferably the first one. I'm not read up on the specific functions to give any advice, but I could have a look sometime during the week if you need pointers 🙂 

The part that was wrong (in my opinion), was taking 3 small and clean functions, and turning them into one huge, hard to read switch-statement 🙂

2017-02-15 20:41 UTC, ethantkoenig commented
@bkcsoft I have addressed your concerns (combine `Add Labels` and `Remove Labels` menus, split `UpdateIssues` back into multiple functions)

2017-02-18 15:44 UTC, andreynering approved these changes
Just two little sintax issues.

2017-02-18 15:44 UTC, andreynering commented on public/js/index.js
> +        "id": elementId
Missing indentation of `data` object

2017-02-18 15:44 UTC, andreynering commented on public/js/index.js
> +                    $labelMenu.data('issue-id'), $(this).data('id'));
I think, or keep function call on a single line, or keep each param in a line, like this:

```js
updateIssuesMeta(
  $labelMenu.data('update-url'),
  "detach",
  $labelMenu.data('issue-id'),
  $(this).data('id')
);
```

Same for similar cases below.

2017-02-18 15:47 UTC, andreynering commented
Useful feature. LGTM

Ref: https://github.com/gogits/gogs/issues/2049

2017-03-01 13:49 UTC, ethantkoenig commented
Rebased to resolve conflicts.

2017-03-10 06:33 UTC, lunny commented
conflicted.

2017-03-10 18:46 UTC, ethantkoenig commented
Rebased.

2017-03-11 03:01 UTC, lunny commented on routers/repo/issue.go
> +	stringIssueIDs := strings.Split(commaSeparatedIssueIDs, ",")
Why not use `x.In().Find()`? It's better performance.

2017-03-11 03:05 UTC, lunny commented on routers/repo/issue.go
> +	for _, issue := range issues {
```
IssueList(issues).LoadRepositories()
```

2017-03-11 03:18 UTC, lunny commented
otherwise LGTM

2017-03-11 17:42 UTC, ethantkoenig commented on routers/repo/issue.go
> +	stringIssueIDs := strings.Split(commaSeparatedIssueIDs, ",")
Fixed.

2017-03-11 17:42 UTC, ethantkoenig commented on routers/repo/issue.go
> +	for _, issue := range issues {
Fixed.

2017-03-11 17:42 UTC, ethantkoenig commented
@bkcsoft I've addressed your concerns from a few weeks ago; please re-review when you get the chance :smile:

2017-03-13 01:48 UTC, lunny commented
but seems you changed index.css file and not index.less ?

2017-03-13 01:48 UTC, ethantkoenig commented
Oh, didn't realize there was a `.less` file. Will update.

2017-03-13 17:20 UTC, ethantkoenig commented
@lunny Updated to use `_repository.less`.

2017-03-14 01:13 UTC, lunny commented
build failed and need @bkcsoft confirmation.

2017-03-15 01:09 UTC, bkcsoft approved these changes

2017-03-15 01:10 UTC, bkcsoft commented
LGTM

2017-03-15 01:10 UTC, merged