Combine Drone release steps
go-gitea/gitea pull request #9338
Opened 2019-12-12 19:37 UTC by silverwind

See https://github.com/go-gitea/gitea/issues/9324. I don't know if this will fix the issue but it seems worth a try to land this on master just to watch the release-master task run. If it does not work out, we can revert it.

2019-12-12 21:12 UTC, lafriks commented
I don't see how this does change things as checked out directory are shared between steps except if there are not in the same pipeline. Also imho js/css build step should be in different drone step

2019-12-13 07:35 UTC, silverwind commented
Yes, they should be shared but the only logical explanation for https://github.com/go-gitea/gitea/issues/9324 is that they aren't for some reason.

I do think it should be possible to produce a working release locally via `make release` and not only via CI, so I see the `release` task dependencies as must-haves.

2019-12-14 07:21 UTC, techknowlogick commented
So embedding works (we can see this with vendor'd css/js, as well as templates are embedded, this means go generate with bindata env is working.

I'm hesitant to merge this without testing, luckily drone allows us to run specific pipelines via CLI. I will test this change via CLI (which will allow me to also put in some debugging into drone that'll show more info (ex. `ls` of a specific dir before running `make release`)

2019-12-14 07:48 UTC, zeripath commented
This change means we lose testing on node10 doesn't it?

2019-12-14 07:54 UTC, techknowlogick reviewed
Just ran `drone exec --pipeline release-master` with the changes I suggested to this PR and it builds as expected.

Thank you for this PR @silverwind :)

2019-12-14 07:54 UTC, techknowlogick commented on .drone.yml
>    - name: build
```suggestion
   - name: static
```
There are steps below that depend on this being the step name

2019-12-14 07:54 UTC, techknowlogick commented on .drone.yml
>    - name: build
```suggestion
   - name: static
```

2019-12-14 07:54 UTC, techknowlogick commented
@zeripath nope, this is just for the release steps, the node10 container is still in the testing pipeline.

2019-12-14 19:46 UTC, axifive commented
@techknowlogick Can you also debugging already existing step in master? To understand why it's not worked, maybe this can help avoid similar errors in the future.

2019-12-15 01:22 UTC, techknowlogick commented
Oh, I know what's going on! I can't believe I missed it. The build & static step are run at the same time, this means that even though the files exist where they should, the go generate command ends up being run before the JS/CSS files are finished being generated. the "depends_on" needs to be removed from each step in the release pipelines to force each step to be run in sequence.

2019-12-15 01:22 UTC, techknowlogick requested changes
Blocking per my most recent comment.

2019-12-15 11:12 UTC, silverwind commented
@techknowlogick thanks for finding it. It's now clear to me that as soon as a `depends_on` is introduced, drone will parallelize (https://docker-runner.docs.drone.io/configuration/parallelism/). I went ahead and removed all `depends_on` in the release pipelines so they should now always serialize.

2019-12-15 11:47 UTC, zeripath approved these changes

2019-12-15 12:20 UTC, silverwind commented
Squashed and added new commit message.

2019-12-15 15:02 UTC, silverwind commented
One more tweak pushed which make `js css` dependencies of `generate`. This fixes the case where`make generate build` (which some people have in their build scripts) would result in `generate` running only once and too early.

2019-12-15 15:12 UTC, silverwind commented
One more tweak: Removed useless `go-all` target. Now `go-check` only runs once instead of twice and before `generate` which also depends on `go` present.

The `go` target itself could potentially also removed but I kept it because it allows for quicker building without `generate`. Thought, the same could also be achieved using `make gitea`.

2019-12-15 15:27 UTC, silverwind commented
`go` target removed as well for simplicity's sake. One can still run `make gitea` (`make gitea.exe` on Windows) to achieve the same.

2019-12-15 18:06 UTC, techknowlogick approved these changes

2019-12-15 18:06 UTC, techknowlogick commented
Thanks @silverwind for all of your work on this :)

2019-12-15 18:06 UTC, merged