AuthorizedKeysCommand should not query db directly
go-gitea/gitea pull request #9371
Opened 2019-12-16 14:53 UTC by zeripath

As per @lafriks comment.

AuthorizedKeysCommand should use API.

2019-12-16 15:10 UTC, sapk approved these changes

2019-12-16 15:50 UTC, lunny requested changes

2019-12-16 15:50 UTC, lunny commented on routers/private/internal.go
> +		m.Post("ssh/authorized_keys", AuthorizedPublicKeyByContent)
`/ssh`?

2019-12-16 15:50 UTC, lunny commented on routers/private/key.go
> +	"net/http"
import sequence.

2019-12-16 16:46 UTC, zeripath commented on routers/private/internal.go
> +		m.Post("ssh/authorized_keys", AuthorizedPublicKeyByContent)
```suggestion
		m.Post("/ssh/authorized_keys", AuthorizedPublicKeyByContent)
```

2019-12-16 17:10 UTC, zeripath commented on routers/private/key.go
> +	"net/http"
Done

2019-12-16 17:10 UTC, zeripath commented on routers/private/internal.go
> +		m.Post("ssh/authorized_keys", AuthorizedPublicKeyByContent)
Done

2019-12-16 17:46 UTC, axifive approved these changes

2019-12-17 00:42 UTC, lunny approved these changes

2019-12-17 01:48 UTC, techknowlogick approved these changes

2019-12-17 01:49 UTC, merged