[WIP] Add units to team
go-gitea/gitea pull request #947
Opened 2017-02-15 14:25 UTC by lunny

This PR allows you create one team who can only see issues or pull request or wikis.

2017-04-27 05:59 UTC, lunny commented
This is done and could be reviewed. When add/edit a team on organization, you could chose which units could be organization's repositories operated on the by this team. For example, we can define `tester` team which can only operate `issues` on all repositories the `tester` team could visit.

2017-04-28 14:36 UTC, bkcsoft requested changes
Few comments

2017-04-28 14:36 UTC, bkcsoft commented on models/unit.go
> +		UnitTypeExternalTracker,
Do we really need External as a separate unit? Can we enable both internal wiki and external wiki at the same time? (same for Tracker)

2017-04-28 14:36 UTC, bkcsoft commented on models/unit.go
>  		UnitTypeExternalWiki,
Same as above

2017-04-28 14:36 UTC, bkcsoft commented on models/unit.go
> +		"repo.ext_issues",
same as above

2017-04-28 14:36 UTC, bkcsoft commented on routers/repo/view.go
> +	ctx.Handle(404, "Home", fmt.Errorf(ctx.Tr("units.error.no_unit_allowed_repo")))
Why are we leaking information that this repo exists but have nothing to show? IMO no valid Units should be the same as Private.

2017-04-28 14:36 UTC, bkcsoft commented on routers/routes/routes.go
> +	m.Group("/:username/:reponame", func() {
Why was this moved?

2017-04-28 15:03 UTC, lunny commented on models/unit.go
> +		UnitTypeExternalTracker,
I think yes. Yes, we can.

2017-04-28 15:05 UTC, lunny commented on routers/routes/routes.go
> +	m.Group("/:username/:reponame", func() {
Move this for easy add middleware `contex.CheckUnit`. Before this, releases URLs are put on many places.

2017-04-28 23:20 UTC, bkcsoft approved these changes

2017-04-28 23:20 UTC, bkcsoft commented
LGTM

2017-05-18 08:53 UTC, sapk commented on models/migrations/v32.go
> +	_, err = x.Where("1=1").Update(&Team{
Not a expert in xorm but can't `.Where("1=1")` be removed ?

2017-05-18 09:12 UTC, sapk commented
This need rebase. 
I will try to test it but looking at code, I could give my trusted LGTM.

2017-05-18 09:41 UTC, lunny commented on models/migrations/v32.go
> +	_, err = x.Where("1=1").Update(&Team{
done.

2017-05-18 09:41 UTC, lunny commented
@sapk rebased

2017-05-18 14:54 UTC, merged

2017-07-31 22:27 UTC, kubatyszko commented
I know this PR is closed, but I believe I found an issue that might be related.
In my installation, *SOME* repos can't browse source, opening the repo (even clicking on <>code) redirects to /releases.

I think this PR modified a lot of routes related to releases, I wonder if that has anything to do with it...

2017-08-01 02:36 UTC, lunny commented
@kubatyszko could you post an issue to describe that?