Fix 404 when click compare on non-forked repository
go-gitea/gitea pull request #948
Opened 2017-02-15 14:54 UTC by lunny

Fix #936

2017-02-15 15:16 UTC, Bwko commented
LGTM

2017-02-15 15:26 UTC, lunny commented
OK. I will see that.

2017-02-16 04:50 UTC, lunny commented
@Bwko done.

2017-02-16 08:46 UTC, Bwko commented
LGTM

2017-02-21 15:00 UTC, ethantkoenig requested changes

2017-02-21 15:00 UTC, ethantkoenig commented on templates/repo/home.tmpl
> +					<a href="{{.BaseRepo.Link}}/compare/{{.BaseRepo.DefaultBranch}}...{{.BranchName}}">
Removing `{{.Username}}` fixes two-branches-inside-the-same-repo comparisons, but break comparisons across forks.

2017-03-02 05:43 UTC, lunny commented on templates/repo/home.tmpl
> +					<a href="{{.BaseRepo.Link}}/compare/{{.BaseRepo.DefaultBranch}}...{{.BranchName}}">
But on compare UI, it's not ready for compare between forks. I think this need another PR to do that. For this one, we should let the button works at first.
Gitea's vs Github's
![untitled](https://cloud.githubusercontent.com/assets/81045/23494484/14a87e3e-ff4e-11e6-9f85-3baa75ca9d1e.png)

2017-03-02 05:55 UTC, appleboy approved these changes

2017-03-02 05:55 UTC, appleboy commented
LGTM

2017-03-02 09:56 UTC, strk commented on templates/repo/home.tmpl
> +					<a href="{{.BaseRepo.Link}}/compare/{{.BaseRepo.DefaultBranch}}...{{.BranchName}}">
How about you just make sure that `.Username` expands to what you expect it to expand, and *later* work on allowing different names ?

2017-03-02 09:58 UTC, lunny commented on templates/repo/home.tmpl
> +					<a href="{{.BaseRepo.Link}}/compare/{{.BaseRepo.DefaultBranch}}...{{.BranchName}}">
I think the later work should be similar with github. Add two dropdown menus and list the forked repos.

2017-03-03 01:51 UTC, lunny commented
I will close this one since it will break comparing across forks and I will send another one.

2017-03-03 01:51 UTC, closed without merging

2017-03-03 02:00 UTC, lunny commented
Deprecated by #1104