Fix error logged when repos qs is empty
go-gitea/gitea pull request #9591
Opened 2020-01-02 19:07 UTC by guillep2k

Fixes invalid error log in the issues list for the user when no specific repositories are requested.

2020-01-02 19:08 UTC, techknowlogick approved these changes

2020-01-02 19:10 UTC, lafriks approved these changes

2020-01-02 19:10 UTC, jolheiser approved these changes

2020-01-02 19:13 UTC, techknowlogick commented
please run `make fmt`

2020-01-02 19:14 UTC, lafriks requested changes

2020-01-02 19:14 UTC, lafriks commented on routers/user/home.go
> +	if(reposQuery != "") {
```suggestion
	if len(reposQuery) != 0 {
```

2020-01-02 19:38 UTC, guillep2k commented
> 
> 
> please run `make fmt`

Sorry, it's been a while. Fixed by applying @lafriks suggestion.

2020-01-02 20:15 UTC, guillep2k commented
@lafriks done.

2020-01-02 22:53 UTC, techknowlogick approved these changes

2020-01-02 23:31 UTC, 6543 approved these changes

2020-01-03 18:43 UTC, lafriks approved these changes

2020-01-03 21:39 UTC, merged