Set Errored PRs out of StatusChecking
go-gitea/gitea pull request #9675
Opened 2020-01-09 19:48 UTC by zeripath

One of the consequences of the fix in #9282 to ensure that PRs are rechecked is that an PR which errors in TestPatch will remain in StatusChecking. This previously didn't matter as PRs would never get rechecked whilst Gitea was running however now this means that these broken PRs will get repeatedly tested.

This PR moves these PRs to StatusError.

2020-01-09 19:51 UTC, lafriks approved these changes

2020-01-09 20:03 UTC, jolheiser requested changes

2020-01-09 20:03 UTC, jolheiser commented on models/pull.go
> +		mergeable := (pr.Status != PullRequestStatusConflict || pr.Status != PullRequestStatusError) && !pr.IsWorkInProgress()
https://play.golang.org/p/g7lTrhTLrs3
```suggestion
		mergeable := !(pr.Status == PullRequestStatusConflict || pr.Status == PullRequestStatusError) && !pr.IsWorkInProgress()
```

2020-01-09 20:11 UTC, zeripath commented on models/pull.go
> +		mergeable := (pr.Status != PullRequestStatusConflict || pr.Status != PullRequestStatusError) && !pr.IsWorkInProgress()
as I've said before I'm an idiot

2020-01-09 20:12 UTC, jolheiser approved these changes

2020-01-10 00:14 UTC, merged

2020-01-10 00:14 UTC, lunny commented
Please send back port.