Fix missing updated time on migrated issues and comments
go-gitea/gitea pull request #9744
Opened 2020-01-13 13:28 UTC by lunny

Should fix #9741

2020-01-13 13:33 UTC, guillep2k approved these changes

2020-01-13 14:07 UTC, 6543 commented on modules/migrations/github_test.go
> +			Updated:    time.Date(2019, 11, 9, 17, 0, 29, 0, time.UTC),
```suggestion
			Updated:    time.Date(2019, 11, 12, 20, 29, 53, 0, time.UTC),
```

2020-01-13 14:09 UTC, 6543 commented on modules/migrations/github_test.go
> +			Updated:    time.Date(2019, 11, 12, 21, 0, 6, 0, time.UTC),
```suggestion
			Updated:    time.Date(2019, 11, 12, 22, 7, 14, 0, time.UTC),
```

2020-01-13 14:12 UTC, sapk submitted a review, later dismissed
Need adjustement on test data otherwise LGTM

2020-01-13 14:14 UTC, 6543 commented
@lunny found second bug:  
`func (g *GithubDownloaderV3) GetPullRequests(page, perPage int) ([]*base.PullRequest, error) {`  
need a patch too around Line  525  [link](https://github.com/go-gitea/gitea/pull/9744/files#diff-7bc639c7c172a3b1e01dc82ddc0d0886L525)

2020-01-13 14:16 UTC, 6543 requested changes
as comment

2020-01-13 15:01 UTC, 6543 commented
@sapk no there is a missing line ...

2020-01-13 15:14 UTC, 6543 commented on modules/migrations/github_test.go
> +			Updated:    time.Date(2019, 11, 12, 21, 54, 18, 0, time.UTC),
```suggestion
			Updated:    time.Date(2020, 1, 4, 11, 30, 1, 0, time.UTC),
```

2020-01-13 15:15 UTC, 6543 commented on modules/migrations/github_test.go
> +			Updated:    time.Date(2019, 11, 12, 21, 21, 43, 0, time.UTC),
```suggestion
			Updated:    time.Date(2019, 11, 12, 21, 39, 28, 0, time.UTC),
```

2020-01-13 15:16 UTC, 6543 commented
```diff
diff --git a/modules/migrations/github.go b/modules/migrations/github.go
index 379af12e7..9183c9318 100644
--- a/modules/migrations/github.go
+++ b/modules/migrations/github.go
@@ -525,6 +525,7 @@ func (g *GithubDownloaderV3) GetPullRequests(page, perPage int) ([]*base.PullReq
                        Milestone:      milestone,
                        State:          *pr.State,
                        Created:        *pr.CreatedAt,
+                       Updated:        *pr.UpdatedAt,
                        Closed:         pr.ClosedAt,
                        Labels:         labels,
                        Merged:         merged,
```

2020-01-14 02:09 UTC, techknowlogick commented
Is a new migration needed for these changes (not possible for backport, but what about master)?

2020-01-14 02:20 UTC, 6543 commented
migration is only needed if we like to fix old records

2020-01-14 02:38 UTC, techknowlogick commented
@6543 but this is new column

2020-01-14 03:37 UTC, lunny commented
@techknowlogick will add a migration.

2020-01-14 04:02 UTC, 6543 approved these changes

2020-01-14 05:04 UTC, 6543 commented
@techknowlogick colum already exist in db. But with wrong entrys for migrated issues ...

2020-01-14 05:06 UTC, techknowlogick commented
@6543 ah ok. Thanks for pointing that out. I thought this was a different struct.

2020-01-14 10:29 UTC, zeripath commented
Make lg-tm work

2020-01-14 10:29 UTC, merged