WIP: Webhook wechat
go-gitea/gitea pull request #9746
Opened 2020-01-13 16:10 UTC by 6543

use #5252 as source ... rebase & apply patches & refacotr ...

credits to: @rocklau

@rocklau may you have a look at?  (can't test this [dont have a wechat jet])

2020-01-13 16:10 UTC, 6543 commented
@rocklau may you have a look at?  (can't test this [dont have a wechat jet])

2020-01-13 16:21 UTC, 6543 commented on templates/repo/settings/webhook/list.tmpl
> +				<a class="item" href="{{.BaseLink}}/settings/hooks/workwechat/new">
```suggestion
				<a class="item" href="{{.BaseLink}}/workwechat/new">
```

2020-01-14 10:15 UTC, rocklau commented
Recommend integrate with this package.
https://github.com/xen0n/go-workwx

2020-03-15 18:46 UTC, 6543 commented
no stalebot no ;)

2020-06-16 10:14 UTC, Zoranner requested changes
LGTM

2020-09-23 10:14 UTC, 6543 commented on templates/repo/settings/webhook/list.tmpl
> +
```suggestion
```

2020-12-12 15:41 UTC, Zoranner requested changes
LGTM

2020-12-15 05:40 UTC, lunny commented
Since #12310 merge, this should be updated.

2020-12-15 07:59 UTC, 6543 commented
will do ...

2021-07-23 11:07 UTC, delvh commented
Is this not closed by #15910?

2021-07-23 11:26 UTC, 6543 commented
Closed by  #15910

2021-07-23 11:26 UTC, closed without merging