feat: expose url field on issue api.
go-gitea/gitea pull request #982
Opened 2017-02-19 15:08 UTC by appleboy

fix https://github.com/go-gitea/gitea/issues/402

2017-02-20 02:56 UTC, appleboy commented
This would be better include in 1.1.0 release.

2017-02-20 03:12 UTC, lunny commented
Let's decided it before release

2017-02-20 03:15 UTC, appleboy commented
@lunny OK

2017-02-26 05:22 UTC, lunny commented
trusted LGTM

2017-02-26 05:24 UTC, lunny commented
@rymai @bkcsoft could you confirm this?

2017-02-27 06:40 UTC, rymai commented on models/issue.go
> +		URL:      issue.HTMLURL(),
I'm not sure about that. From GitHub's API it seems that it should be the API URL to get the issue, not the HTML URL: https://developer.github.com/v3/issues/#get-a-single-issue

```
"url": "https://api.github.com/repos/octocat/Hello-World/issues/1347",
```

2017-02-27 06:44 UTC, appleboy commented on models/issue.go
> +		URL:      issue.HTMLURL(),
Didn't we define the API URL for Gitea? cc @lunny

2017-02-27 06:50 UTC, bkcsoft commented on models/issue.go
> +		URL:      issue.HTMLURL(),
Indeed it is the API-URL :) and that function doesn't exist, so we need a `issue.APIURL()` as well (should be fairly simple)

2017-02-27 06:50 UTC, bkcsoft commented on models/issue.go
> +		URL:      issue.HTMLURL(),
Indeed it is the API-URL :) and that function doesn't exist, so we need a `issue.APIURL()` as well (should be fairly simple)

2017-02-27 06:52 UTC, bkcsoft commented on models/issue.go
> +		URL:      issue.HTMLURL(),
Indeed it is the API-URL :) and that function doesn't exist, so we need a `issue.APIURL()` as well (should be fairly simple)

2017-02-27 06:53 UTC, lunny commented on models/issue.go
> +		URL:      issue.HTMLURL(),
@appleboy It seems there is not.

2017-02-27 07:03 UTC, appleboy commented on models/issue.go
> +		URL:      issue.HTMLURL(),
But we didn't have API URL in `app.ini`, we only have `ROOT_URL` config now.

2017-02-27 07:04 UTC, appleboy commented on models/issue.go
> +		URL:      issue.HTMLURL(),
maybe I can create another to add new `API_URL` setting in `app.ini`.

2017-02-27 07:17 UTC, lunny commented on models/issue.go
> +		URL:      issue.HTMLURL(),
Yes, I think you can.

2017-02-27 07:24 UTC, tboerger commented on models/issue.go
> +		URL:      issue.HTMLURL(),
We don't support a separate api url yet, so just take the regular url and append the api path

2017-02-27 07:34 UTC, bkcsoft commented on models/issue.go
> +		URL:      issue.HTMLURL(),
```go
func (i *Issue) APIURL() string {
  return path.Join(settings.AppURL, "/api/v1/repos/", issue.Repo.FullName(), "issues", issue.ID)
}
```

2017-02-27 07:36 UTC, bkcsoft commented on models/issue.go
> +		URL:      issue.HTMLURL(),
Preferably there should be 2 new functions:
```go
func (repo *Repo) APIURL() string {
  return path.Join(settings.AppURL, "/api/v1/repos/", repo.FullName())
}

func (issue *Issue) APIURL() string {
  return path.Join(issue.Repo.APIURL(), "issues", issue.ID)
}
```

2017-02-27 08:16 UTC, lunny commented on models/issue.go
> +		URL:      issue.HTMLURL(),
@bkcsoft maybe you can send a PR and we can close this one.

2017-02-27 08:25 UTC, appleboy commented on models/issue.go
> +		URL:      issue.HTMLURL(),
I will update this PR.

2017-02-27 08:56 UTC, lunny commented
build failed.

2017-02-27 09:15 UTC, bkcsoft commented
LGTM when the build succeeds :)

2017-02-27 09:15 UTC, bkcsoft commented
> models/issue.go:205: undefined: path in path.Join
models/issue.go:205: issue.Repo.APIURL undefined (type *Repository has no field or method APIURL)
models/repo.go:268: undefined: Repo
models/repo.go:269: undefined: settings in settings.AppURL
make: *** [Makefile:71: test] Error 1

Need to `import "path"`

2017-02-27 09:18 UTC, tboerger commented on models/repo.go
> +	return path.Join(settings.AppURL, "/api/v1/repos/", repo.FullName())
Does appurl include the sub path of gitea is not running on the top folder?

2017-02-27 10:34 UTC, appleboy commented
I will fix errors. Please wait.

2017-02-27 11:44 UTC, appleboy commented on models/repo.go
> +	return path.Join(settings.AppURL, "/api/v1/repos/", repo.FullName())
Good catch. `path.Join` will convert double slash to single slash.

2017-02-27 12:23 UTC, appleboy commented
@tboerger @bkcsoft Done. Please review again.

2017-02-27 16:17 UTC, appleboy commented
Add unit testing.

2017-02-27 16:20 UTC, appleboy commented on models/repo.go
> +	return strings.TrimRight(setting.AppURL, "/") + "/" + path.Join("api/v1/repos", repo.FullName())
Support `setting.AppURL` include end slash or not

2017-02-27 17:08 UTC, tboerger commented
LGTM

2017-02-27 20:12 UTC, bkcsoft commented on models/repo.go
> +	return strings.TrimRight(setting.AppURL, "/") + "/" + path.Join("api/v1/repos", repo.FullName())
No need for that, `path.Join` does that automagically 🙂

2017-02-27 20:13 UTC, bkcsoft requested changes

2017-02-27 20:13 UTC, bkcsoft commented on models/issue.go
> +	return strings.TrimRight(issue.Repo.APIURL(), "/") + "/" + path.Join("issues", fmt.Sprint(issue.ID))
Unnecessary, `path.Join` trims extra slashes

2017-02-28 01:36 UTC, lunny commented
conflicted.

2017-02-28 04:32 UTC, appleboy commented on models/repo.go
> +	return strings.TrimRight(setting.AppURL, "/") + "/" + path.Join("api/v1/repos", repo.FullName())
@bkcsoft `path.Join` will replace `//` with `/`

```go
setting.AppURL = "https://try.gitea.io/"
path.Join(setting.AppURL, "api/v1/repos", repo.FullName())
# output: https:/try.gitea.io/api/v1/repos/user01/test
```

see https://play.golang.org/p/-0CJvOEZ5N

2017-02-28 04:37 UTC, appleboy commented on models/issue.go
> +	return strings.TrimRight(issue.Repo.APIURL(), "/") + "/" + path.Join("issues", fmt.Sprint(issue.ID))
same above.

see https://play.golang.org/p/-0CJvOEZ5N

2017-02-28 04:43 UTC, appleboy commented
@lunny fix conflicts and wait for build status.

2017-03-01 08:37 UTC, tboerger commented on models/repo.go
> +	return strings.TrimRight(setting.AppURL, "/") + "/" + path.Join("api/v1/repos", repo.FullName())
Yeah, path.Join destroys absolute urls.

2017-03-01 08:37 UTC, tboerger commented
LGTM

2017-03-02 09:54 UTC, lunny commented
@appleboy maybe you should rebase and push --force.

2017-03-02 10:04 UTC, appleboy commented
@lunny I always use `git pull --rebase origin master` on target branch.

2017-03-02 11:19 UTC, lunny commented on models/repo_test.go
> +func TestRepoAPIURL(t *testing.T) {
lint?

2017-03-02 14:36 UTC, appleboy commented on models/repo_test.go
> +func TestRepoAPIURL(t *testing.T) {
Nothing output lint errors after execute `make lint` command.

2017-03-02 16:03 UTC, bkcsoft commented on models/repo.go
> +	return strings.TrimRight(setting.AppURL, "/") + "/" + path.Join("api/v1/repos", repo.FullName())
I don't see how that is relevant, it's supposed to be an absolute URL, not a relative one.

Works just fine IMO: https://play.golang.org/p/Rc734RIuJu

2017-03-02 16:03 UTC, bkcsoft commented on models/repo_test.go
> +func TestRepoAPIURL(t *testing.T) {
Linting doesn't apply to `*_test.go` 🙂

2017-03-02 16:16 UTC, appleboy commented on models/repo.go
> +	return strings.TrimRight(setting.AppURL, "/") + "/" + path.Join("api/v1/repos", repo.FullName())
@bkcsoft Please see the result from your url

```
https:/try.gitea.io/api/v1/repos/user01/repo01
```

Wrong: `https:/`
Correct: `https://`

2017-03-03 02:34 UTC, ethantkoenig requested changes

2017-03-03 02:34 UTC, ethantkoenig commented on models/issue_test.go
> +func TestIssueReplaceLabels(t *testing.T) {
Why was this test renamed?

2017-03-03 02:40 UTC, appleboy commented on models/issue_test.go
> +func TestIssueReplaceLabels(t *testing.T) {
https://golang.org/doc/effective_go.html#mixed-caps

2017-03-03 02:42 UTC, appleboy commented
@lunny @bkcsoft remove `trim` from API URL.

2017-03-03 02:46 UTC, ethantkoenig commented on models/issue_test.go
> +func TestIssueReplaceLabels(t *testing.T) {
I thought that the naming conventions for tests matched those of testable examples (https://blog.golang.org/examples)? Was I mistaken?

2017-03-03 08:14 UTC, bkcsoft approved these changes

2017-03-03 08:18 UTC, appleboy commented on models/issue_test.go
> +func TestIssueReplaceLabels(t *testing.T) {
@ethantkoenig revert.

2017-03-03 08:55 UTC, lunny commented
need @ethantkoenig confirmation.

2017-03-03 14:33 UTC, ethantkoenig approved these changes

2017-03-03 14:35 UTC, merged

2017-03-05 15:16 UTC, rymai commented
Thanks @appleboy! ❤️