Add option to prevent LDAP from deactivating everything on empty search
go-gitea/gitea pull request #9879
Opened 2020-01-19 21:15 UTC by zeripath

It appears that some LDAPs will simply return an empty search results if there is an error during searching rather than report the error. In those circumstances Gitea would completely deactivate all LDAP users.

This is clearly not ideal - add a configuration option to LDAP configuration which will mean that by default an empty search results will not deactivate any users and instead an error will be logged. An authentication option can be turned on for those situations where this behaviour would be intended.

Fix #7949

2020-01-19 21:47 UTC, guillep2k reviewed
This should require a migration step, I think. What should the migration value be? I vote for `AllowDeactivateAll=false`.

2020-01-19 21:47 UTC, guillep2k commented on options/locale/locale_en-US.ini
> +auths.allow_deactivate_all = Allow an empty search update result to deactivate all users
```suggestion
auths.allow_deactivate_all = Allow an empty search result to deactivate all users
```

2020-01-19 22:17 UTC, zeripath commented
It's actually not in the db like that. It's JSON so it will default to false already.

2020-01-19 22:45 UTC, guillep2k approved these changes

2020-01-20 02:33 UTC, 6543 approved these changes

2020-01-20 02:52 UTC, lunny requested changes

2020-01-20 02:52 UTC, lunny commented on modules/auth/ldap/ldap.go
> +	AllowDeactivateAll    bool   // Allow an empty search response to deactivate all users from this source
You should add migrations.

2020-01-20 02:55 UTC, lunny approved these changes

2020-01-20 03:47 UTC, merged

2020-01-20 10:55 UTC, dioss-Machiel commented
Is it at all possible to get this fix into a 1.10 release?

2020-01-20 12:30 UTC, zeripath commented
We could probably backport it to 1.11?

I think 1.10 is now security fixes only. `git cherry-pick c5014a7` might work to put it on 1.10 but it will likely conflict.

2020-01-20 13:50 UTC, guillep2k commented
> 
> 
> We could probably backport it to 1.11?
> 
> I think 1.10 is now security fixes only. `git cherry-pick c5014a7` might work to put it on 1.10 but it will likely conflict.

Sounds like we're close to 1.11, but if anybody wants port this to 1.10.4 and fix the conflicts or do it by hand, I have no problem reviewing the PR from zero.

2020-01-20 14:59 UTC, lunny commented
@zeripath If we marked this as feature, I don't think we should send backport to v1.11. Or we may should label this as bug.

2020-01-20 15:16 UTC, zeripath commented
@dioss-Machiel Looks like it applied cleanly to release/v1.10?

2020-01-20 15:59 UTC, dioss-Machiel commented
I applied it manually, seems to be fine.

2020-01-20 17:31 UTC, zeripath commented
I've marked this as a bug. I'm not sure where the bug is because LDAP shouldn't be returning an empty result without an error.