Fix issues/pulls dashboard paging error
go-gitea/gitea pull request #9998
Opened 2020-01-26 09:29 UTC by lunny

Fix #9952

2020-01-26 23:46 UTC, guillep2k approved these changes

2020-01-26 23:56 UTC, zeripath approved these changes

2020-01-27 14:39 UTC, 6543 requested changes
this solves the one problem but create a new one!!

now if a repo is selected the other repo's are gone (not visilbe to select anymore)

2020-01-28 05:02 UTC, lunny commented
Don't merge, @6543 I will check that.

2020-02-03 02:20 UTC, closed without merging